In [2]:
import cmapPy

In [3]:
import pandas as pd
import numpy as np

In [4]:
pd

In [5]:
 import cmapPy.pandasGEXpress.parse as pa

In [6]:
df=pa.parse("PAAD.gct", convert_neg_666=True)

In [7]:
df

In [8]:
df1=df.data_df
df1.head()

cid,aab1-Primary solid Tumor,aab4-Primary solid Tumor,aab6-Primary solid Tumor,aab8-Primary solid Tumor,aab9-Primary solid Tumor,aaba-Primary solid Tumor,aabe-Primary solid Tumor,aabf-Primary solid Tumor,aabh-Primary solid Tumor,aabi-Primary solid Tumor,...,aauh-Primary solid Tumor,aaui-Primary solid Tumor,aaul-Primary solid Tumor,a8t3-Primary solid Tumor,a8t5-Primary solid Tumor,a89d-Solid Tissue Normal,a89d-Primary solid Tumor,a8sy-Primary solid Tumor,a8lh-Primary solid Tumor,aapl-Primary solid Tumor
rid,,,,,,,,,,,,,,,,,,,,,
SLC35E2,7.45,8.1,7.2,8.0,7.65,8.1,8.2,8.2,7.55,8.45,...,8.45,7.95,8.3,8.05,8.2,7.25,7.4,7.35,7.2,9.05
A1BG,6.40,5.8,6.4,5.8,6.70,6.6,6.3,6.5,5.70,6.30,...,7.10,7.10,6.7,7.00,6.9,7.10,7.3,7.90,6.0,6.90
A1CF,4.70,5.7,3.0,5.1,4.40,4.2,1.6,6.8,6.00,NaN,...,5.40,6.40,6.5,4.40,3.3,3.60,6.2,1.20,4.9,2.00
A2BP1,-1.00,1.1,NaN,NaN,0.10,NaN,NaN,1.7,0.40,-1.50,...,3.50,1.30,-0.3,NaN,2.1,2.00,0.0,NaN,2.0,NaN
A2LD1,7.50,6.8,7.3,7.5,7.40,6.6,7.1,6.8,8.00,5.80,...,6.50,7.30,6.1,6.70,6.5,6.70,6.7,6.50,6.9,6.70

In [9]:
missing_data = df1.isnull()

In [10]:
missing_data.head()

cid,aab1-Primary solid Tumor,aab4-Primary solid Tumor,aab6-Primary solid Tumor,aab8-Primary solid Tumor,aab9-Primary solid Tumor,aaba-Primary solid Tumor,aabe-Primary solid Tumor,aabf-Primary solid Tumor,aabh-Primary solid Tumor,aabi-Primary solid Tumor,...,aauh-Primary solid Tumor,aaui-Primary solid Tumor,aaul-Primary solid Tumor,a8t3-Primary solid Tumor,a8t5-Primary solid Tumor,a89d-Solid Tissue Normal,a89d-Primary solid Tumor,a8sy-Primary solid Tumor,a8lh-Primary solid Tumor,aapl-Primary solid Tumor
rid,,,,,,,,,,,,,,,,,,,,,
SLC35E2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
A1BG,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
A1CF,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
A2BP1,False,False,True,True,False,True,True,False,False,False,...,False,False,False,True,False,False,False,True,False,True
A2LD1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
for row in missing_data.index.tolist():
    print(row)
    print(missing_data.loc[row].value_counts())
    print("")

SLC35E2
False    183
Name: SLC35E2, dtype: int64

A1BG
False    183
Name: A1BG, dtype: int64

A1CF
False    181
True       2
Name: A1CF, dtype: int64

A2BP1
False    141
True      42
Name: A2BP1, dtype: int64

A2LD1
False    183
Name: A2LD1, dtype: int64

A2ML1
False    156
True      27
Name: A2ML1, dtype: int64

A2M
False    183
Name: A2M, dtype: int64

A4GALT
False    183
Name: A4GALT, dtype: int64

A4GNT
False    174
True       9
Name: A4GNT, dtype: int64

AAA1
False    125
True      58
Name: AAA1, dtype: int64

AAAS
False    183
Name: AAAS, dtype: int64

AACSL
False    107
True      76
Name: AACSL, dtype: int64

AACS
False    183
Name: AACS, dtype: int64

AADAC
False    179
True       4
Name: AADAC, dtype: int64

AADAT
False    183
Name: AADAT, dtype: int64

AAGAB
False    183
Name: AAGAB, dtype: int64

AAK1
False    183
Name: AAK1, dtype: int64

AAMP
False    183
Name: AAMP, dtype: int64

AANAT
False    123
True      60
Name: AANAT, dtype: int64

AARS2
False    183
Name: AARS2, dtype: int64

AARSD1
False    183
Name: AARSD1, dtype: int64

AARS
False    183
Name: AARS, dtype: int64

AASDHPPT
False    183
Name: AASDHPPT, dtype: int64

AASDH
False    183
Name: AASDH, dtype: int64

AASS
False    183
Name: AASS, dtype: int64

AATF
False    183
Name: AATF, dtype: int64

AATK
False    183
Name: AATK, dtype: int64

ABAT
False    183
Name: ABAT, dtype: int64

ABCA10
False    183
Name: ABCA10, dtype: int64

ABCA11P
False    183
Name: ABCA11P, dtype: int64

ABCA12
False    176
True       7
Name: ABCA12, dtype: int64

ABCA13
False    179
True       4
Name: ABCA13, dtype: int64

ABCA17P
False    182
True       1
Name: ABCA17P, dtype: int64

ABCA1
False    183
Name: ABCA1, dtype: int64

ABCA2
False    183
Name: ABCA2, dtype: int64

ABCA3
False    183
Name: ABCA3, dtype: int64

ABCA4
False    180
True       3
Name: ABCA4, dtype: int64

ABCA5
False    183
Name: ABCA5, dtype: int64

ABCA6
False    183
Name: ABCA6, dtype: int64

ABCA7
False    183
Name: ABCA7, dtype: int64

ABCA8
False    183
Name: ABCA8, dtype: int64

ABCA9
False    183
Name: ABCA9, dtype: int64

ABCB10
False    183
Name: ABCB10, dtype: int64

ABCB11
False    168
True      15
Name: ABCB11, dtype: int64

ABCB1
False    183
Name: ABCB1, dtype: int64

ABCB4
False    183
Name: ABCB4, dtype: int64

ABCB5
False    172
True      11
Name: ABCB5, dtype: int64

ABCB6
False    183
Name: ABCB6, dtype: int64

ABCB7
False    183
Name: ABCB7, dtype: int64

ABCB8
False    183
Name: ABCB8, dtype: int64

ABCB9
False    183
Name: ABCB9, dtype: int64

ABCC10
False    183
Name: ABCC10, dtype: int64

ABCC11
False    172
True      11
Name: ABCC11, dtype: int64

ABCC13
False    93
True     90
Name: ABCC13, dtype: int64

ABCC1
False    183
Name: ABCC1, dtype: int64

ABCC2
False    183
Name: ABCC2, dtype: int64

ABCC3
False    183
Name: ABCC3, dtype: int64

ABCC4
False    183
Name: ABCC4, dtype: int64

ABCC5
False    183
Name: ABCC5, dtype: int64

ABCC6P1
False    175
True       8
Name: ABCC6P1, dtype: int64

ABCC6P2
False    183
Name: ABCC6P2, dtype: int64

ABCC6
False    183
Name: ABCC6, dtype: int64

ABCC8
False    183
Name: ABCC8, dtype: int64

ABCC9
False    183
Name: ABCC9, dtype: int64

ABCD1
False    183
Name: ABCD1, dtype: int64

ABCD2
False    181
True       2
Name: ABCD2, dtype: int64

ABCD3
False    183
Name: ABCD3, dtype: int64

ABCD4
False    183
Name: ABCD4, dtype: int64

ABCE1
False    183
Name: ABCE1, dtype: int64

ABCF1
False    183
Name: ABCF1, dtype: int64

ABCF2
False    183
Name: ABCF2, dtype: int64

ABCF3
False    183
Name: ABCF3, dtype: int64

ABCG1
False    183
Name: ABCG1, dtype: int64

ABCG2
False    183
Name: ABCG2, dtype: int64

ABCG4
False    182
True       1
Name: ABCG4, dtype: int64

ABCG5
False    171
True      12
Name: ABCG5, dtype: int64

ABCG8
False    135
True      48
Name: ABCG8, dtype: int64

ABHD10
False    183
Name: ABHD10, dtype: int64

ABHD11
False    183
Name: ABHD11, dtype: int64

ABHD12B
False    161
True      22
Name: ABHD12B, dtype: int64

ABHD12
False    183
Name: ABHD12, dtype: int64

ABHD13
False    183
Name: ABHD13, dtype: int64

ABHD14A
False    183
Name: ABHD14A, dtype: int64

ABHD14B
False    183
Name: ABHD14B, dtype: int64

ABHD15
False    183
Name: ABHD15, dtype: int64

ABHD1
False    181
True       2
Name: ABHD1, dtype: int64

ABHD2
False    183
Name: ABHD2, dtype: int64

ABHD3
False    183
Name: ABHD3, dtype: int64

ABHD4
False    183
Name: ABHD4, dtype: int64

ABHD5
False    183
Name: ABHD5, dtype: int64

ABHD6
False    183
Name: ABHD6, dtype: int64

ABHD8
False    183
Name: ABHD8, dtype: int64

ABI1
False    183
Name: ABI1, dtype: int64

ABI2
False    183
Name: ABI2, dtype: int64

ABI3BP
False    183
Name: ABI3BP, dtype: int64

ABI3
False    183
Name: ABI3, dtype: int64

ABL1
False    183
Name: ABL1, dtype: int64

ABL2
False    183
Name: ABL2, dtype: int64

ABLIM1
False    183
Name: ABLIM1, dtype: int64

ABLIM2
False    183
Name: ABLIM2, dtype: int64

ABLIM3
False    183
Name: ABLIM3, dtype: int64

ABO
False    182
True       1
Name: ABO, dtype: int64

ABP1
False    183
Name: ABP1, dtype: int64

ABRA
False    133
True      50
Name: ABRA, dtype: int64

ABR
False    183
Name: ABR, dtype: int64

ABT1
False    183
Name: ABT1, dtype: int64

ABTB1
False    183
Name: ABTB1, dtype: int64

ABTB2
False    183
Name: ABTB2, dtype: int64

ACAA1
False    183
Name: ACAA1, dtype: int64

ACAA2
False    183
Name: ACAA2, dtype: int64

ACACA
False    183
Name: ACACA, dtype: int64

ACACB
False    183
Name: ACACB, dtype: int64

ACAD10
False    183
Name: ACAD10, dtype: int64

ACAD11
False    183
Name: ACAD11, dtype: int64

ACAD8
False    183
Name: ACAD8, dtype: int64

ACAD9
False    183
Name: ACAD9, dtype: int64

ACADL
False    177
True       6
Name: ACADL, dtype: int64

ACADM
False    183
Name: ACADM, dtype: int64

ACADSB
False    183
Name: ACADSB, dtype: int64

ACADS
False    183
Name: ACADS, dtype: int64

ACADVL
False    183
Name: ACADVL, dtype: int64

ACAN
False    183
Name: ACAN, dtype: int64

ACAP1
False    183
Name: ACAP1, dtype: int64

ACAP2
False    183
Name: ACAP2, dtype: int64

ACAP3
False    183
Name: ACAP3, dtype: int64

ACAT1
False    183
Name: ACAT1, dtype: int64

ACAT2
False    183
Name: ACAT2, dtype: int64

ACBD3
False    183
Name: ACBD3, dtype: int64

ACBD4
False    183
Name: ACBD4, dtype: int64

ACBD5
False    183
Name: ACBD5, dtype: int64

ACBD6
False    183
Name: ACBD6, dtype: int64

ACBD7
False    183
Name: ACBD7, dtype: int64

ACCN1
False    171
True      12
Name: ACCN1, dtype: int64

ACCN2
False    183
Name: ACCN2, dtype: int64

ACCN3
False    183
Name: ACCN3, dtype: int64

ACCN4
False    171
True      12
Name: ACCN4, dtype: int64

ACCS
False    183
Name: ACCS, dtype: int64

ACD
False    183
Name: ACD, dtype: int64

ACE2
False    183
Name: ACE2, dtype: int64

ACER1
True     100
False     83
Name: ACER1, dtype: int64

ACER2
False    183
Name: ACER2, dtype: int64

ACER3
False    183
Name: ACER3, dtype: int64

ACE
False    183
Name: ACE, dtype: int64

ACHE
False    183
Name: ACHE, dtype: int64

ACIN1
False    183
Name: ACIN1, dtype: int64

ACLY
False    183
Name: ACLY, dtype: int64

ACMSD
False    168
True      15
Name: ACMSD, dtype: int64

ACN9
False    183
Name: ACN9, dtype: int64

ACO1
False    183
Name: ACO1, dtype: int64

ACO2
False    183
Name: ACO2, dtype: int64

ACOT11
False    183
Name: ACOT11, dtype: int64

ACOT13
False    183
Name: ACOT13, dtype: int64

ACOT1
False    183
Name: ACOT1, dtype: int64

ACOT2
False    183
Name: ACOT2, dtype: int64

ACOT4
False    183
Name: ACOT4, dtype: int64

ACOT6
False    146
True      37
Name: ACOT6, dtype: int64

ACOT7
False    183
Name: ACOT7, dtype: int64

ACOT8
False    183
Name: ACOT8, dtype: int64

ACOT9
False    183
Name: ACOT9, dtype: int64

ACOX1
False    183
Name: ACOX1, dtype: int64

ACOX2
False    183
Name: ACOX2, dtype: int64

ACOX3
False    183
Name: ACOX3, dtype: int64

ACOXL
False    176
True       7
Name: ACOXL, dtype: int64

ACP1
False    183
Name: ACP1, dtype: int64

ACP2
False    183
Name: ACP2, dtype: int64

ACP5
False    183
Name: ACP5, dtype: int64

ACP6
False    183
Name: ACP6, dtype: int64

ACPL2
False    183
Name: ACPL2, dtype: int64

ACPP
False    182
True       1
Name: ACPP, dtype: int64

ACRBP
False    183
Name: ACRBP, dtype: int64

ACRC
False    183
Name: ACRC, dtype: int64

ACRV1
False    138
True      45
Name: ACRV1, dtype: int64

ACR
False    166
True      17
Name: ACR, dtype: int64

ACSBG1
False    183
Name: ACSBG1, dtype: int64

ACSBG2
False    128
True      55
Name: ACSBG2, dtype: int64

ACSF2
False    183
Name: ACSF2, dtype: int64

ACSF3
False    183
Name: ACSF3, dtype: int64

ACSL1
False    183
Name: ACSL1, dtype: int64

ACSL3
False    183
Name: ACSL3, dtype: int64

ACSL4

False    183
Name: ACSL4, dtype: int64

ACSL5
False    183
Name: ACSL5, dtype: int64

ACSL6
False    182
True       1
Name: ACSL6, dtype: int64

ACSM1
False    182
True       1
Name: ACSM1, dtype: int64

ACSM2A
False    104
True      79
Name: ACSM2A, dtype: int64

ACSM2B
False    92
True     91
Name: ACSM2B, dtype: int64

ACSM3
False    183
Name: ACSM3, dtype: int64

ACSM5
False    179
True       4
Name: ACSM5, dtype: int64

ACSS1
False    183
Name: ACSS1, dtype: int64

ACSS2
False    183
Name: ACSS2, dtype: int64

ACSS3
False    183
Name: ACSS3, dtype: int64

ACTA1
False    175
True       8
Name: ACTA1, dtype: int64

ACTA2
False    183
Name: ACTA2, dtype: int64

ACTBL2
False    174
True       9
Name: ACTBL2, dtype: int64

ACTB
False    183
Name: ACTB, dtype: int64

ACTC1
False    181
True       2
Name: ACTC1, dtype: int64

ACTG1
False    183
Name: ACTG1, dtype: int64

ACTG2
False    183
Name: ACTG2, dtype: int64

ACTL6A
False    183
Name: ACTL6A, dtype: int64

ACTL6B
False    152
True      31
Name: ACTL6B, dtype: int64

ACTL8
False    92
True     91
Name: ACTL8, dtype: int64

ACTN1
False    183
Name: ACTN1, dtype: int64

ACTN2
False    182
True       1
Name: ACTN2, dtype: int64

ACTN3
False    161
True      22
Name: ACTN3, dtype: int64

ACTN4
False    183
Name: ACTN4, dtype: int64

ACTR10
False    183
Name: ACTR10, dtype: int64

ACTR1A
False    183
Name: ACTR1A, dtype: int64

ACTR1B
False    183
Name: ACTR1B, dtype: int64

ACTR2
False    183
Name: ACTR2, dtype: int64

ACTR3B
False    183
Name: ACTR3B, dtype: int64

ACTR3C
False    183
Name: ACTR3C, dtype: int64

ACTR3
False    183
Name: ACTR3, dtype: int64

ACTR5
False    183
Name: ACTR5, dtype: int64

ACTR6
False    183
Name: ACTR6, dtype: int64

ACTR8
False    183
Name: ACTR8, dtype: int64

ACVR1B
False    183
Name: ACVR1B, dtype: int64

ACVR1C
False    183
Name: ACVR1C, dtype: int64

ACVR1
False    183
Name: ACVR1, dtype: int64

ACVR2A
False    183
Name: ACVR2A, dtype: int64

ACVR2B
False    183
Name: ACVR2B, dtype: int64

ACVRL1
False    183
Name: ACVRL1, dtype: int64

ACY1
False    183
Name: ACY1, dtype: int64

ACY3
False    183
Name: ACY3, dtype: int64

ACYP1
False    183
Name: ACYP1, dtype: int64

ACYP2
False    183
Name: ACYP2, dtype: int64

ADAD2
False    157
True      26
Name: ADAD2, dtype: int64

ADAL
False    183
Name: ADAL, dtype: int64

ADAM10
False    183
Name: ADAM10, dtype: int64

ADAM11
False    181
True       2
Name: ADAM11, dtype: int64

ADAM12
False    183
Name: ADAM12, dtype: int64

ADAM15
False    183
Name: ADAM15, dtype: int64

ADAM17
False    183
Name: ADAM17, dtype: int64

ADAM19
False    183
Name: ADAM19, dtype: int64

ADAM20
False    166
True      17
Name: ADAM20, dtype: int64

ADAM21P1
False    119
True      64
Name: ADAM21P1, dtype: int64

ADAM21
False    174
True       9
Name: ADAM21, dtype: int64

ADAM22
False    183
Name: ADAM22, dtype: int64

ADAM23
False    183
Name: ADAM23, dtype: int64

ADAM28
False    183
Name: ADAM28, dtype: int64

ADAM29
False    117
True      66
Name: ADAM29, dtype: int64

ADAM32
False    182
True       1
Name: ADAM32, dtype: int64

ADAM33
False    182
True       1
Name: ADAM33, dtype: int64

ADAM6
False    183
Name: ADAM6, dtype: int64

ADAM8
False    183
Name: ADAM8, dtype: int64

ADAM9
False    183
Name: ADAM9, dtype: int64

ADAMDEC1
False    181
True       2
Name: ADAMDEC1, dtype: int64

ADAMTS10
False    183
Name: ADAMTS10, dtype: int64

ADAMTS12
False    183
Name: ADAMTS12, dtype: int64

ADAMTS13
False    183
Name: ADAMTS13, dtype: int64

ADAMTS14
False    183
Name: ADAMTS14, dtype: int64

ADAMTS15
False    182
True       1
Name: ADAMTS15, dtype: int64

ADAMTS16
False    183
Name: ADAMTS16, dtype: int64

ADAMTS17
False    183
Name: ADAMTS17, dtype: int64

ADAMTS18
False    180
True       3
Name: ADAMTS18, dtype: int64

ADAMTS19
False    93
True     90
Name: ADAMTS19, dtype: int64

ADAMTS1
False    183
Name: ADAMTS1, dtype: int64

ADAMTS2
False    183
Name: ADAMTS2, dtype: int64

ADAMTS3
False    182
True       1
Name: ADAMTS3, dtype: int64

ADAMTS4
False    183
Name: ADAMTS4, dtype: int64

ADAMTS5
False    183
Name: ADAMTS5, dtype: int64

ADAMTS6
False    183
Name: ADAMTS6, dtype: int64

ADAMTS7
False    183
Name: ADAMTS7, dtype: int64

ADAMTS8
False    183
Name: ADAMTS8, dtype: int64

ADAMTS9
False    183
Name: ADAMTS9, dtype: int64

ADAMTSL1
False    183
Name: ADAMTSL1, dtype: int64

ADAMTSL2
False    183
Name: ADAMTSL2, dtype: int64

ADAMTSL3
False    183
Name: ADAMTSL3, dtype: int64

ADAMTSL4
False    183
Name: ADAMTSL4, dtype: int64

ADAMTSL5
False    182
True       1
Name: ADAMTSL5, dtype: int64

ADAP1
False    183
Name: ADAP1, dtype: int64

ADAP2
False    183
Name: ADAP2, dtype: int64

ADARB1
False    183
Name: ADARB1, dtype: int64

ADARB2
False    174
True       9
Name: ADARB2, dtype: int64

ADAR
False    183
Name: ADAR, dtype: int64

ADAT1
False    183
Name: ADAT1, dtype: int64

ADAT2
False    183
Name: ADAT2, dtype: int64

ADAT3
False    183
Name: ADAT3, dtype: int64

ADA
False    183
Name: ADA, dtype: int64

ADCK1
False    183
Name: ADCK1, dtype: int64

ADCK2
False    183
Name: ADCK2, dtype: int64

ADCK4
False    183
Name: ADCK4, dtype: int64

ADCK5
False    183
Name: ADCK5, dtype: int64

ADCY10
False    158
True      25
Name: ADCY10, dtype: int64

ADCY1
False    183
Name: ADCY1, dtype: int64

ADCY2
False    183
Name: ADCY2, dtype: int64

ADCY3
False    183
Name: ADCY3, dtype: int64

ADCY4
False    183
Name: ADCY4, dtype: int64

ADCY5
False    183
Name: ADCY5, dtype: int64

ADCY6
False    183
Name: ADCY6, dtype: int64

ADCY7
False    183
Name: ADCY7, dtype: int64

ADCY8
True     96
False    87
Name: ADCY8, dtype: int64

ADCY9
False    183
Name: ADCY9, dtype: int64

ADCYAP1R1
False    138
True      45
Name: ADCYAP1R1, dtype: int64

ADCYAP1
False    182
True       1
Name: ADCYAP1, dtype: int64

ADC
False    183
Name: ADC, dtype: int64

ADD1
False    183
Name: ADD1, dtype: int64

ADD2
False    183
Name: ADD2, dtype: int64

ADD3
False    183
Name: ADD3, dtype: int64

ADH1A
False    174
True       9
Name: ADH1A, dtype: int64

ADH1B
False    181
True       2
Name: ADH1B, dtype: int64

ADH1C
False    183
Name: ADH1C, dtype: int64

ADH4
False    161
True      22
Name: ADH4, dtype: int64

ADH5
False    183
Name: ADH5, dtype: int64

ADH6
False    182
True       1
Name: ADH6, dtype: int64

ADHFE1
False    183
Name: ADHFE1, dtype: int64

ADI1
False    183
Name: ADI1, dtype: int64

ADIPOQ
False    135
True      48
Name: ADIPOQ, dtype: int64

ADIPOR1
False    183
Name: ADIPOR1, dtype: int64

ADIPOR2
False    183
Name: ADIPOR2, dtype: int64

ADK
False    183
Name: ADK, dtype: int64

ADM2
False    183
Name: ADM2, dtype: int64

ADM
False    183
Name: ADM, dtype: int64

ADNP2
False    183
Name: ADNP2, dtype: int64

ADNP
False    183
Name: ADNP, dtype: int64

ADORA1
False    183
Name: ADORA1, dtype: int64

ADORA2A
False    183
Name: ADORA2A, dtype: int64

ADORA2B
False    183
Name: ADORA2B, dtype: int64

ADORA3
False    183
Name: ADORA3, dtype: int64

ADO
False    183
Name: ADO, dtype: int64

ADPGK
False    183
Name: ADPGK, dtype: int64

ADPRHL1
False    183
Name: ADPRHL1, dtype: int64

ADPRHL2
False    183
Name: ADPRHL2, dtype: int64

ADPRH
False    183
Name: ADPRH, dtype: int64

ADRA1A
False    151
True      32
Name: ADRA1A, dtype: int64

ADRA1B
False    183
Name: ADRA1B, dtype: int64

ADRA1D
False    180
True       3
Name: ADRA1D, dtype: int64

ADRA2A
False    183
Name: ADRA2A, dtype: int64

ADRA2B
False    183
Name: ADRA2B, dtype: int64

ADRA2C
False    183
Name: ADRA2C, dtype: int64

ADRB1
False    183
Name: ADRB1, dtype: int64

ADRB2
False    183
Name: ADRB2, dtype: int64

ADRB3
False    172
True      11
Name: ADRB3, dtype: int64

ADRBK1
False    183
Name: ADRBK1, dtype: int64

ADRBK2
False    183
Name: ADRBK2, dtype: int64

ADRM1
False    183
Name: ADRM1, dtype: int64

ADSL
False    183
Name: ADSL, dtype: int64

ADSSL1
False    183
Name: ADSSL1, dtype: int64

ADSS
False    183
Name: ADSS, dtype: int64

AEBP1
False    183
Name: AEBP1, dtype: int64

AEBP2
False    183
Name: AEBP2, dtype: int64

AEN
False    183
Name: AEN, dtype: int64

AES
False    183
Name: AES, dtype: int64

AFAP1L1
False    183
Name: AFAP1L1, dtype: int64

AFAP1L2
False    183
Name: AFAP1L2, dtype: int64

AFAP1
False    183
Name: AFAP1, dtype: int64

AFARP1
False    172
True      11
Name: AFARP1, dtype: int64

AFF1
False    183
Name: AFF1, dtype: int64

AFF2

False    183
Name: AFF2, dtype: int64

AFF3
False    183
Name: AFF3, dtype: int64

AFF4
False    183
Name: AFF4, dtype: int64

AFG3L1
False    183
Name: AFG3L1, dtype: int64

AFG3L2
False    183
Name: AFG3L2, dtype: int64

AFMID
False    183
Name: AFMID, dtype: int64

AFM
True     96
False    87
Name: AFM, dtype: int64

AFP
False    108
True      75
Name: AFP, dtype: int64

AFTPH
False    183
Name: AFTPH, dtype: int64

AG2
False    183
Name: AG2, dtype: int64

AGAP11
False    183
Name: AGAP11, dtype: int64

AGAP1
False    183
Name: AGAP1, dtype: int64

AGAP2
False    183
Name: AGAP2, dtype: int64

AGAP3
False    183
Name: AGAP3, dtype: int64

AGAP4
False    183
Name: AGAP4, dtype: int64

AGAP5
False    183
Name: AGAP5, dtype: int64

AGAP6
False    183
Name: AGAP6, dtype: int64

AGAP7
False    183
Name: AGAP7, dtype: int64

AGAP8
False    183
Name: AGAP8, dtype: int64

AGA
False    183
Name: AGA, dtype: int64

AGBL2
False    183
Name: AGBL2, dtype: int64

AGBL3
False    183
Name: AGBL3, dtype: int64

AGBL4
False    164
True      19
Name: AGBL4, dtype: int64

AGBL5
False    183
Name: AGBL5, dtype: int64

AGER
False    183
Name: AGER, dtype: int64

AGFG1
False    183
Name: AGFG1, dtype: int64

AGFG2
False    183
Name: AGFG2, dtype: int64

AGGF1
False    183
Name: AGGF1, dtype: int64

AGK
False    183
Name: AGK, dtype: int64

AGL
False    183
Name: AGL, dtype: int64

AGMAT
False    183
Name: AGMAT, dtype: int64

AGPAT1
False    183
Name: AGPAT1, dtype: int64

AGPAT2
False    183
Name: AGPAT2, dtype: int64

AGPAT3
False    183
Name: AGPAT3, dtype: int64

AGPAT4
False    183
Name: AGPAT4, dtype: int64

AGPAT5
False    183
Name: AGPAT5, dtype: int64

AGPAT6
False    183
Name: AGPAT6, dtype: int64

AGPAT9
False    183
Name: AGPAT9, dtype: int64

AGPHD1
False    183
Name: AGPHD1, dtype: int64

AGPS
False    183
Name: AGPS, dtype: int64

AGR2
False    180
True       3
Name: AGR2, dtype: int64

AGR3
False    179
True       4
Name: AGR3, dtype: int64

AGRN
False    183
Name: AGRN, dtype: int64

AGRP
False    160
True      23
Name: AGRP, dtype: int64

AGTPBP1
False    183
Name: AGTPBP1, dtype: int64

AGTR1
False    183
Name: AGTR1, dtype: int64

AGTR2
False    110
True      73
Name: AGTR2, dtype: int64

AGTRAP
False    183
Name: AGTRAP, dtype: int64

AGT
False    183
Name: AGT, dtype: int64

AGXT2L1
False    126
True      57
Name: AGXT2L1, dtype: int64

AGXT2L2
False    183
Name: AGXT2L2, dtype: int64

AGXT
False    141
True      42
Name: AGXT, dtype: int64

AHCTF1
False    183
Name: AHCTF1, dtype: int64

AHCYL1
False    183
Name: AHCYL1, dtype: int64

AHCYL2
False    183
Name: AHCYL2, dtype: int64

AHCY
False    183
Name: AHCY, dtype: int64

AHDC1
False    183
Name: AHDC1, dtype: int64

AHI1
False    183
Name: AHI1, dtype: int64

AHNAK2
False    183
Name: AHNAK2, dtype: int64

AHNAK
False    183
Name: AHNAK, dtype: int64

AHRR
False    183
Name: AHRR, dtype: int64

AHR
False    183
Name: AHR, dtype: int64

AHSA1
False    183
Name: AHSA1, dtype: int64

AHSA2
False    183
Name: AHSA2, dtype: int64

AHSG
False    158
True      25
Name: AHSG, dtype: int64

AHSP
True     103
False     80
Name: AHSP, dtype: int64

AICDA
False    160
True      23
Name: AICDA, dtype: int64

AIDA
False    183
Name: AIDA, dtype: int64

AIF1L
False    183
Name: AIF1L, dtype: int64

AIF1
False    183
Name: AIF1, dtype: int64

AIFM1
False    183
Name: AIFM1, dtype: int64

AIFM2
False    183
Name: AIFM2, dtype: int64

AIFM3
False    183
Name: AIFM3, dtype: int64

AIG1
False    183
Name: AIG1, dtype: int64

AIM1L
False    182
True       1
Name: AIM1L, dtype: int64

AIM1
False    183
Name: AIM1, dtype: int64

AIM2
False    179
True       4
Name: AIM2, dtype: int64

AIMP1
False    183
Name: AIMP1, dtype: int64

AIMP2
False    183
Name: AIMP2, dtype: int64

AIPL1
True     128
False     55
Name: AIPL1, dtype: int64

AIP
False    183
Name: AIP, dtype: int64

AIRE
False    144
True      39
Name: AIRE, dtype: int64

AJAP1
False    181
True       2
Name: AJAP1, dtype: int64

AK1
False    183
Name: AK1, dtype: int64

AK2
False    183
Name: AK2, dtype: int64

AK3L1
False    183
Name: AK3L1, dtype: int64

AK3
False    183
Name: AK3, dtype: int64

AK5
False    183
Name: AK5, dtype: int64

AK7
False    183
Name: AK7, dtype: int64

AKAP10
False    183
Name: AKAP10, dtype: int64

AKAP11
False    183
Name: AKAP11, dtype: int64

AKAP12
False    183
Name: AKAP12, dtype: int64

AKAP13
False    183
Name: AKAP13, dtype: int64

AKAP14
True     125
False     58
Name: AKAP14, dtype: int64

AKAP1
False    183
Name: AKAP1, dtype: int64

AKAP2
False    181
True       2
Name: AKAP2, dtype: int64

AKAP3
False    182
True       1
Name: AKAP3, dtype: int64

AKAP4
True     121
False     62
Name: AKAP4, dtype: int64

AKAP5
False    183
Name: AKAP5, dtype: int64

AKAP6
False    183
Name: AKAP6, dtype: int64

AKAP7
False    183
Name: AKAP7, dtype: int64

AKAP8L
False    183
Name: AKAP8L, dtype: int64

AKAP8
False    183
Name: AKAP8, dtype: int64

AKAP9
False    183
Name: AKAP9, dtype: int64

AKD1
False    183
Name: AKD1, dtype: int64

AKIRIN1
False    183
Name: AKIRIN1, dtype: int64

AKIRIN2
False    183
Name: AKIRIN2, dtype: int64

AKNAD1
False    142
True      41
Name: AKNAD1, dtype: int64

AKNA
False    183
Name: AKNA, dtype: int64

AKR1A1
False    183
Name: AKR1A1, dtype: int64

AKR1B10
False    180
True       3
Name: AKR1B10, dtype: int64

AKR1B15
False    158
True      25
Name: AKR1B15, dtype: int64

AKR1B1
False    183
Name: AKR1B1, dtype: int64

AKR1C1
False    183
Name: AKR1C1, dtype: int64

AKR1C2
False    183
Name: AKR1C2, dtype: int64

AKR1C3
False    183
Name: AKR1C3, dtype: int64

AKR1C4
False    168
True      15
Name: AKR1C4, dtype: int64

AKR1D1
True     115
False     68
Name: AKR1D1, dtype: int64

AKR1E2
False    183
Name: AKR1E2, dtype: int64

AKR7A2
False    183
Name: AKR7A2, dtype: int64

AKR7A3
False    183
Name: AKR7A3, dtype: int64

AKR7L
False    183
Name: AKR7L, dtype: int64

AKT1S1
False    183
Name: AKT1S1, dtype: int64

AKT1
False    183
Name: AKT1, dtype: int64

AKT2
False    183
Name: AKT2, dtype: int64

AKT3
False    183
Name: AKT3, dtype: int64

AKTIP
False    183
Name: AKTIP, dtype: int64

ALAD
False    183
Name: ALAD, dtype: int64

ALAS1
False    183
Name: ALAS1, dtype: int64

ALAS2
False    142
True      41
Name: ALAS2, dtype: int64

ALB
False    182
True       1
Name: ALB, dtype: int64

ALCAM
False    183
Name: ALCAM, dtype: int64

ALDH16A1
False    183
Name: ALDH16A1, dtype: int64

ALDH18A1
False    183
Name: ALDH18A1, dtype: int64

ALDH1A1
False    183
Name: ALDH1A1, dtype: int64

ALDH1A2
False    182
True       1
Name: ALDH1A2, dtype: int64

ALDH1A3
False    183
Name: ALDH1A3, dtype: int64

ALDH1B1
False    183
Name: ALDH1B1, dtype: int64

ALDH1L1
False    181
True       2
Name: ALDH1L1, dtype: int64

ALDH1L2
False    183
Name: ALDH1L2, dtype: int64

ALDH2
False    183
Name: ALDH2, dtype: int64

ALDH3A1
False    182
True       1
Name: ALDH3A1, dtype: int64

ALDH3A2
False    183
Name: ALDH3A2, dtype: int64

ALDH3B1
False    183
Name: ALDH3B1, dtype: int64

ALDH3B2
False    180
True       3
Name: ALDH3B2, dtype: int64

ALDH4A1
False    183
Name: ALDH4A1, dtype: int64

ALDH5A1
False    183
Name: ALDH5A1, dtype: int64

ALDH6A1
False    183
Name: ALDH6A1, dtype: int64

ALDH7A1
False    183
Name: ALDH7A1, dtype: int64

ALDH8A1
False    183
Name: ALDH8A1, dtype: int64

ALDH9A1
False    183
Name: ALDH9A1, dtype: int64

ALDOA
False    183
Name: ALDOA, dtype: int64

ALDOB
False    183
Name: ALDOB, dtype: int64

ALDOC
False    183
Name: ALDOC, dtype: int64

ALG10B
False    183
Name: ALG10B, dtype: int64

ALG10
False    183
Name: ALG10, dtype: int64

ALG11
False    183
Name: ALG11, dtype: int64

ALG12
False    183
Name: ALG12, dtype: int64

ALG13
False    183
Name: ALG13, dtype: int64

ALG14
False    183
Name: ALG14, dtype: int64

ALG1L2
False    110
True      73
Name: ALG1L2, dtype: int64

ALG1L
False    183
Name: ALG1L, dtype: int64

ALG1
False    183
Name: ALG1, dtype: int64

ALG2
False    183
Name: ALG2, dtype: int64

ALG3
False    183
Name: ALG3, dtype: int64

ALG5
False    183
Name: ALG5, dtype: int64

ALG6
False    183
Name: ALG6, dtype: int64

ALG8
False    183
Name: ALG8, dtype: int64

ALG9
False    183
Name: ALG9, dtype: int64

ALKBH1
False    183
Name: ALKBH1, dtype: int64

ALKBH2
False    183
Name: ALKBH2, dtype: int64

ALKBH3
False    183
Name: ALKBH3, dtype: int64

ALKBH4
False    183
Name: ALKBH4, dtype: int64

ALKBH5
False    183
Name: ALKBH5, dtype: int64

ALKBH6

False    183
Name: ALKBH6, dtype: int64

ALKBH7
False    183
Name: ALKBH7, dtype: int64

ALKBH8
False    183
Name: ALKBH8, dtype: int64

ALK
False    175
True       8
Name: ALK, dtype: int64

ALLC
False    140
True      43
Name: ALLC, dtype: int64

ALMS1P
False    161
True      22
Name: ALMS1P, dtype: int64

ALMS1
False    183
Name: ALMS1, dtype: int64

ALOX12B
False    177
True       6
Name: ALOX12B, dtype: int64

ALOX12P2
False    181
True       2
Name: ALOX12P2, dtype: int64

ALOX12
False    182
True       1
Name: ALOX12, dtype: int64

ALOX15B
False    183
Name: ALOX15B, dtype: int64

ALOX15
False    162
True      21
Name: ALOX15, dtype: int64

ALOX5AP
False    183
Name: ALOX5AP, dtype: int64

ALOX5
False    183
Name: ALOX5, dtype: int64

ALOXE3
False    180
True       3
Name: ALOXE3, dtype: int64

ALPI
False    136
True      47
Name: ALPI, dtype: int64

ALPK1
False    183
Name: ALPK1, dtype: int64

ALPK2
False    183
Name: ALPK2, dtype: int64

ALPK3
False    183
Name: ALPK3, dtype: int64

ALPL
False    183
Name: ALPL, dtype: int64

ALPPL2
False    157
True      26
Name: ALPPL2, dtype: int64

ALPP
False    159
True      24
Name: ALPP, dtype: int64

ALS2CL
False    183
Name: ALS2CL, dtype: int64

ALS2CR11
False    177
True       6
Name: ALS2CR11, dtype: int64

ALS2CR12
False    165
True      18
Name: ALS2CR12, dtype: int64

ALS2CR4
False    183
Name: ALS2CR4, dtype: int64

ALS2CR8
False    183
Name: ALS2CR8, dtype: int64

ALS2
False    183
Name: ALS2, dtype: int64

ALX1
False    106
True      77
Name: ALX1, dtype: int64

ALX3
False    183
Name: ALX3, dtype: int64

AMAC1L2
False    160
True      23
Name: AMAC1L2, dtype: int64

AMAC1L3
True     100
False     83
Name: AMAC1L3, dtype: int64

AMACR
False    183
Name: AMACR, dtype: int64

AMBP
False    183
Name: AMBP, dtype: int64

AMBRA1
False    183
Name: AMBRA1, dtype: int64

AMD1
False    183
Name: AMD1, dtype: int64

AMDHD1
False    180
True       3
Name: AMDHD1, dtype: int64

AMDHD2
False    183
Name: AMDHD2, dtype: int64

AMFR
False    183
Name: AMFR, dtype: int64

AMHR2
False    163
True      20
Name: AMHR2, dtype: int64

AMH
False    173
True      10
Name: AMH, dtype: int64

AMICA1
False    183
Name: AMICA1, dtype: int64

AMIGO1
False    183
Name: AMIGO1, dtype: int64

AMIGO2
False    183
Name: AMIGO2, dtype: int64

AMIGO3
False    183
Name: AMIGO3, dtype: int64

AMMECR1L
False    183
Name: AMMECR1L, dtype: int64

AMMECR1
False    183
Name: AMMECR1, dtype: int64

AMN1
False    183
Name: AMN1, dtype: int64

AMN
False    182
True       1
Name: AMN, dtype: int64

AMOTL1
False    183
Name: AMOTL1, dtype: int64

AMOTL2
False    183
Name: AMOTL2, dtype: int64

AMOT
False    183
Name: AMOT, dtype: int64

AMPD1
False    157
True      26
Name: AMPD1, dtype: int64

AMPD2
False    183
Name: AMPD2, dtype: int64

AMPD3
False    183
Name: AMPD3, dtype: int64

AMPH
False    183
Name: AMPH, dtype: int64

AMTN
False    132
True      51
Name: AMTN, dtype: int64

AMT
False    183
Name: AMT, dtype: int64

AMY1A
False    175
True       8
Name: AMY1A, dtype: int64

AMY2A
False    179
True       4
Name: AMY2A, dtype: int64

AMY2B
False    183
Name: AMY2B, dtype: int64

AMZ1
False    182
True       1
Name: AMZ1, dtype: int64

AMZ2P1
False    183
Name: AMZ2P1, dtype: int64

AMZ2
False    183
Name: AMZ2, dtype: int64

ANAPC10
False    183
Name: ANAPC10, dtype: int64

ANAPC11
False    183
Name: ANAPC11, dtype: int64

ANAPC13
False    183
Name: ANAPC13, dtype: int64

ANAPC16
False    183
Name: ANAPC16, dtype: int64

ANAPC1
False    183
Name: ANAPC1, dtype: int64

ANAPC2
False    183
Name: ANAPC2, dtype: int64

ANAPC4
False    183
Name: ANAPC4, dtype: int64

ANAPC5
False    183
Name: ANAPC5, dtype: int64

ANAPC7
False    183
Name: ANAPC7, dtype: int64

ANGEL1
False    183
Name: ANGEL1, dtype: int64

ANGEL2
False    183
Name: ANGEL2, dtype: int64

ANGPT1
False    183
Name: ANGPT1, dtype: int64

ANGPT2
False    183
Name: ANGPT2, dtype: int64

ANGPT4
False    156
True      27
Name: ANGPT4, dtype: int64

ANGPTL1
False    183
Name: ANGPTL1, dtype: int64

ANGPTL2
False    183
Name: ANGPTL2, dtype: int64

ANGPTL3
False    162
True      21
Name: ANGPTL3, dtype: int64

ANGPTL4
False    183
Name: ANGPTL4, dtype: int64

ANGPTL5
False    145
True      38
Name: ANGPTL5, dtype: int64

ANGPTL6
False    180
True       3
Name: ANGPTL6, dtype: int64

ANGPTL7
False    167
True      16
Name: ANGPTL7, dtype: int64

ANG
False    183
Name: ANG, dtype: int64

ANK1
False    183
Name: ANK1, dtype: int64

ANK2
False    183
Name: ANK2, dtype: int64

ANK3
False    183
Name: ANK3, dtype: int64

ANKAR
False    183
Name: ANKAR, dtype: int64

ANKDD1A
False    183
Name: ANKDD1A, dtype: int64

ANKFN1
False    170
True      13
Name: ANKFN1, dtype: int64

ANKFY1
False    183
Name: ANKFY1, dtype: int64

ANKHD1-EIF4EBP3
False    183
Name: ANKHD1-EIF4EBP3, dtype: int64

ANKHD1
False    183
Name: ANKHD1, dtype: int64

ANKH
False    183
Name: ANKH, dtype: int64

ANKIB1
False    183
Name: ANKIB1, dtype: int64

ANKK1
False    179
True       4
Name: ANKK1, dtype: int64

ANKLE1
False    183
Name: ANKLE1, dtype: int64

ANKLE2
False    183
Name: ANKLE2, dtype: int64

ANKMY1
False    183
Name: ANKMY1, dtype: int64

ANKMY2
False    183
Name: ANKMY2, dtype: int64

ANKRA2
False    183
Name: ANKRA2, dtype: int64

ANKRD10
False    183
Name: ANKRD10, dtype: int64

ANKRD11
False    183
Name: ANKRD11, dtype: int64

ANKRD12
False    183
Name: ANKRD12, dtype: int64

ANKRD13A
False    183
Name: ANKRD13A, dtype: int64

ANKRD13B
False    183
Name: ANKRD13B, dtype: int64

ANKRD13C
False    183
Name: ANKRD13C, dtype: int64

ANKRD13D
False    183
Name: ANKRD13D, dtype: int64

ANKRD16
False    183
Name: ANKRD16, dtype: int64

ANKRD17
False    183
Name: ANKRD17, dtype: int64

ANKRD19
False    183
Name: ANKRD19, dtype: int64

ANKRD1
False    181
True       2
Name: ANKRD1, dtype: int64

ANKRD20A3
False    182
True       1
Name: ANKRD20A3, dtype: int64

ANKRD20A4
False    144
True      39
Name: ANKRD20A4, dtype: int64

ANKRD20B
False    178
True       5
Name: ANKRD20B, dtype: int64

ANKRD22
False    183
Name: ANKRD22, dtype: int64

ANKRD23
False    183
Name: ANKRD23, dtype: int64

ANKRD24
False    183
Name: ANKRD24, dtype: int64

ANKRD26P1
False    96
True     87
Name: ANKRD26P1, dtype: int64

ANKRD26
False    183
Name: ANKRD26, dtype: int64

ANKRD27
False    183
Name: ANKRD27, dtype: int64

ANKRD28
False    183
Name: ANKRD28, dtype: int64

ANKRD29
False    183
Name: ANKRD29, dtype: int64

ANKRD2
False    178
True       5
Name: ANKRD2, dtype: int64

ANKRD30B
False    97
True     86
Name: ANKRD30B, dtype: int64

ANKRD31
False    135
True      48
Name: ANKRD31, dtype: int64

ANKRD32
False    183
Name: ANKRD32, dtype: int64

ANKRD33
False    137
True      46
Name: ANKRD33, dtype: int64

ANKRD34A
False    183
Name: ANKRD34A, dtype: int64

ANKRD34B
False    122
True      61
Name: ANKRD34B, dtype: int64

ANKRD34C
False    154
True      29
Name: ANKRD34C, dtype: int64

ANKRD35
False    183
Name: ANKRD35, dtype: int64

ANKRD36BP1
False    182
True       1
Name: ANKRD36BP1, dtype: int64

ANKRD36B
False    182
True       1
Name: ANKRD36B, dtype: int64

ANKRD36
False    183
Name: ANKRD36, dtype: int64

ANKRD37
False    183
Name: ANKRD37, dtype: int64

ANKRD39
False    183
Name: ANKRD39, dtype: int64

ANKRD40
False    183
Name: ANKRD40, dtype: int64

ANKRD42
False    183
Name: ANKRD42, dtype: int64

ANKRD43
False    183
Name: ANKRD43, dtype: int64

ANKRD44
False    183
Name: ANKRD44, dtype: int64

ANKRD45
False    179
True       4
Name: ANKRD45, dtype: int64

ANKRD46
False    183
Name: ANKRD46, dtype: int64

ANKRD49
False    183
Name: ANKRD49, dtype: int64

ANKRD50
False    183
Name: ANKRD50, dtype: int64

ANKRD52
False    183
Name: ANKRD52, dtype: int64

ANKRD53
False    183
Name: ANKRD53, dtype: int64

ANKRD54
False    183
Name: ANKRD54, dtype: int64

ANKRD55
False    169
True      14
Name: ANKRD55, dtype: int64

ANKRD56
False    183
Name: ANKRD56, dtype: int64

ANKRD57
False    183
Name: ANKRD57, dtype: int64

ANKRD58
False    183
Name: ANKRD58, dtype: int64

ANKRD5
False    183
Name: ANKRD5, dtype: int64

ANKRD6
False    183
Name: ANKRD6, dtype: int64

ANKRD7
False    139
True      44
Name: ANKRD7, dtype: int64

ANKRD9
False    183
Name: ANKRD9, dtype: int64

ANKS1A
False    183
Name: ANKS1A, dtype: int64

ANKS1B
False    181
True       2
Name: ANKS1B, dtype: int64

ANKS3
False    183
Name: ANKS3, dtype: int64

ANKS4B
False    180
True       3
Name: ANKS4B, dtype: int64

ANKS6
False    183
Name: ANKS6, dtype: int64

ANKZF1

False    183
Name: ANKZF1, dtype: int64

ANLN
False    183
Name: ANLN, dtype: int64

ANO10
False    183
Name: ANO10, dtype: int64

ANO1
False    183
Name: ANO1, dtype: int64

ANO2
False    183
Name: ANO2, dtype: int64

ANO3
False    179
True       4
Name: ANO3, dtype: int64

ANO4
False    182
True       1
Name: ANO4, dtype: int64

ANO5
False    183
Name: ANO5, dtype: int64

ANO6
False    183
Name: ANO6, dtype: int64

ANO7
False    183
Name: ANO7, dtype: int64

ANO8
False    183
Name: ANO8, dtype: int64

ANO9
False    183
Name: ANO9, dtype: int64

ANP32A
False    183
Name: ANP32A, dtype: int64

ANP32B
False    183
Name: ANP32B, dtype: int64

ANP32C
False    165
True      18
Name: ANP32C, dtype: int64

ANP32E
False    183
Name: ANP32E, dtype: int64

ANPEP
False    183
Name: ANPEP, dtype: int64

ANTXR1
False    183
Name: ANTXR1, dtype: int64

ANTXR2
False    183
Name: ANTXR2, dtype: int64

ANUBL1
False    183
Name: ANUBL1, dtype: int64

ANXA10
False    182
True       1
Name: ANXA10, dtype: int64

ANXA11
False    183
Name: ANXA11, dtype: int64

ANXA13
False    182
True       1
Name: ANXA13, dtype: int64

ANXA1
False    183
Name: ANXA1, dtype: int64

ANXA2P1
False    183
Name: ANXA2P1, dtype: int64

ANXA2P2
False    183
Name: ANXA2P2, dtype: int64

ANXA2P3
False    181
True       2
Name: ANXA2P3, dtype: int64

ANXA2
False    183
Name: ANXA2, dtype: int64

ANXA3
False    183
Name: ANXA3, dtype: int64

ANXA4
False    183
Name: ANXA4, dtype: int64

ANXA5
False    183
Name: ANXA5, dtype: int64

ANXA6
False    183
Name: ANXA6, dtype: int64

ANXA7
False    183
Name: ANXA7, dtype: int64

ANXA8L2
False    176
True       7
Name: ANXA8L2, dtype: int64

ANXA8
False    179
True       4
Name: ANXA8, dtype: int64

ANXA9
False    183
Name: ANXA9, dtype: int64

AOAH
False    183
Name: AOAH, dtype: int64

AOC2
False    183
Name: AOC2, dtype: int64

AOC3
False    183
Name: AOC3, dtype: int64

AOX1
False    183
Name: AOX1, dtype: int64

AP1AR
False    183
Name: AP1AR, dtype: int64

AP1B1
False    183
Name: AP1B1, dtype: int64

AP1G1
False    183
Name: AP1G1, dtype: int64

AP1G2
False    183
Name: AP1G2, dtype: int64

AP1M1
False    183
Name: AP1M1, dtype: int64

AP1M2
False    183
Name: AP1M2, dtype: int64

AP1S1
False    183
Name: AP1S1, dtype: int64

AP1S2
False    183
Name: AP1S2, dtype: int64

AP1S3
False    183
Name: AP1S3, dtype: int64

AP2A1
False    183
Name: AP2A1, dtype: int64

AP2A2
False    183
Name: AP2A2, dtype: int64

AP2B1
False    183
Name: AP2B1, dtype: int64

AP2M1
False    183
Name: AP2M1, dtype: int64

AP2S1
False    183
Name: AP2S1, dtype: int64

AP3B1
False    183
Name: AP3B1, dtype: int64

AP3B2
False    181
True       2
Name: AP3B2, dtype: int64

AP3D1
False    183
Name: AP3D1, dtype: int64

AP3M1
False    183
Name: AP3M1, dtype: int64

AP3M2
False    183
Name: AP3M2, dtype: int64

AP3S1
False    183
Name: AP3S1, dtype: int64

AP3S2
False    183
Name: AP3S2, dtype: int64

AP4B1
False    183
Name: AP4B1, dtype: int64

AP4E1
False    183
Name: AP4E1, dtype: int64

AP4M1
False    183
Name: AP4M1, dtype: int64

AP4S1
False    183
Name: AP4S1, dtype: int64

APAF1
False    183
Name: APAF1, dtype: int64

APBA1
False    183
Name: APBA1, dtype: int64

APBA2
False    183
Name: APBA2, dtype: int64

APBA3
False    183
Name: APBA3, dtype: int64

APBB1IP
False    183
Name: APBB1IP, dtype: int64

APBB1
False    183
Name: APBB1, dtype: int64

APBB2
False    183
Name: APBB2, dtype: int64

APBB3
False    183
Name: APBB3, dtype: int64

APC2
False    183
Name: APC2, dtype: int64

APCDD1L
False    182
True       1
Name: APCDD1L, dtype: int64

APCDD1
False    183
Name: APCDD1, dtype: int64

APCS
False    166
True      17
Name: APCS, dtype: int64

APC
False    183
Name: APC, dtype: int64

APEH
False    183
Name: APEH, dtype: int64

APEX1
False    183
Name: APEX1, dtype: int64

APEX2
False    183
Name: APEX2, dtype: int64

APH1A
False    183
Name: APH1A, dtype: int64

APH1B
False    183
Name: APH1B, dtype: int64

API5
False    183
Name: API5, dtype: int64

APIP
False    183
Name: APIP, dtype: int64

APITD1
False    183
Name: APITD1, dtype: int64

APLF
False    183
Name: APLF, dtype: int64

APLNR
False    183
Name: APLNR, dtype: int64

APLN
False    183
Name: APLN, dtype: int64

APLP1
False    183
Name: APLP1, dtype: int64

APLP2
False    183
Name: APLP2, dtype: int64

APOA1BP
False    183
Name: APOA1BP, dtype: int64

APOA1
False    178
True       5
Name: APOA1, dtype: int64

APOA4
False    114
True      69
Name: APOA4, dtype: int64

APOA5
True     100
False     83
Name: APOA5, dtype: int64

APOB48R
False    183
Name: APOB48R, dtype: int64

APOBEC1
False    170
True      13
Name: APOBEC1, dtype: int64

APOBEC2
False    179
True       4
Name: APOBEC2, dtype: int64

APOBEC3A
False    182
True       1
Name: APOBEC3A, dtype: int64

APOBEC3B
False    183
Name: APOBEC3B, dtype: int64

APOBEC3C
False    183
Name: APOBEC3C, dtype: int64

APOBEC3D
False    183
Name: APOBEC3D, dtype: int64

APOBEC3F
False    183
Name: APOBEC3F, dtype: int64

APOBEC3G
False    183
Name: APOBEC3G, dtype: int64

APOBEC3H
False    179
True       4
Name: APOBEC3H, dtype: int64

APOBEC4
False    144
True      39
Name: APOBEC4, dtype: int64

APOB
False    183
Name: APOB, dtype: int64

APOC1P1
True     94
False    89
Name: APOC1P1, dtype: int64

APOC1
False    183
Name: APOC1, dtype: int64

APOC2
False    183
Name: APOC2, dtype: int64

APOC3
False    97
True     86
Name: APOC3, dtype: int64

APOC4
False    134
True      49
Name: APOC4, dtype: int64

APOD
False    183
Name: APOD, dtype: int64

APOE
False    183
Name: APOE, dtype: int64

APOF
False    101
True      82
Name: APOF, dtype: int64

APOH
False    174
True       9
Name: APOH, dtype: int64

APOL1
False    183
Name: APOL1, dtype: int64

APOL2
False    183
Name: APOL2, dtype: int64

APOL3
False    183
Name: APOL3, dtype: int64

APOL4
False    183
Name: APOL4, dtype: int64

APOL6
False    183
Name: APOL6, dtype: int64

APOLD1
False    183
Name: APOLD1, dtype: int64

APOM
False    183
Name: APOM, dtype: int64

APOOL
False    183
Name: APOOL, dtype: int64

APOO
False    183
Name: APOO, dtype: int64

APPBP2
False    183
Name: APPBP2, dtype: int64

APPL1
False    183
Name: APPL1, dtype: int64

APPL2
False    183
Name: APPL2, dtype: int64

APP
False    183
Name: APP, dtype: int64

APRT
False    183
Name: APRT, dtype: int64

APTX
False    183
Name: APTX, dtype: int64

AQP10
False    166
True      17
Name: AQP10, dtype: int64

AQP11
False    183
Name: AQP11, dtype: int64

AQP12A
False    103
True      80
Name: AQP12A, dtype: int64

AQP12B
False    163
True      20
Name: AQP12B, dtype: int64

AQP1
False    183
Name: AQP1, dtype: int64

AQP2
False    167
True      16
Name: AQP2, dtype: int64

AQP3
False    183
Name: AQP3, dtype: int64

AQP4
False    178
True       5
Name: AQP4, dtype: int64

AQP5
False    180
True       3
Name: AQP5, dtype: int64

AQP6
False    180
True       3
Name: AQP6, dtype: int64

AQP7P1
False    181
True       2
Name: AQP7P1, dtype: int64

AQP7P3
False    153
True      30
Name: AQP7P3, dtype: int64

AQP7
False    183
Name: AQP7, dtype: int64

AQP8
False    162
True      21
Name: AQP8, dtype: int64

AQP9
False    183
Name: AQP9, dtype: int64

AQPEP
False    177
True       6
Name: AQPEP, dtype: int64

AQR
False    183
Name: AQR, dtype: int64

ARAF
False    183
Name: ARAF, dtype: int64

ARAP1
False    183
Name: ARAP1, dtype: int64

ARAP2
False    183
Name: ARAP2, dtype: int64

ARAP3
False    183
Name: ARAP3, dtype: int64

ARCN1
False    183
Name: ARCN1, dtype: int64

ARC
False    182
True       1
Name: ARC, dtype: int64

AREG
False    183
Name: AREG, dtype: int64

ARF1
False    183
Name: ARF1, dtype: int64

ARF3
False    183
Name: ARF3, dtype: int64

ARF4
False    183
Name: ARF4, dtype: int64

ARF5
False    183
Name: ARF5, dtype: int64

ARF6
False    183
Name: ARF6, dtype: int64

ARFGAP1
False    183
Name: ARFGAP1, dtype: int64

ARFGAP2
False    183
Name: ARFGAP2, dtype: int64

ARFGAP3
False    183
Name: ARFGAP3, dtype: int64

ARFGEF1
False    183
Name: ARFGEF1, dtype: int64

ARFGEF2
False    183
Name: ARFGEF2, dtype: int64

ARFIP1
False    183
Name: ARFIP1, dtype: int64

ARFIP2
False    183
Name: ARFIP2, dtype: int64

ARFRP1
False    183
Name: ARFRP1, dtype: int64

ARG1
False    136
True      47
Name: ARG1, dtype: int64

ARG2
False    183
Name: ARG2, dtype: int64

ARGFXP2
False    137
True      46
Name: ARGFXP2, dtype: int64

ARGLU1
False    183
Name: ARGLU1, dtype: int64

ARHGAP10
False    183
Name: ARHGAP10, dtype: int64

ARHGAP11A
False    183
Name: ARHGAP11A, dtype: int64

ARHGAP11B
False    181
True       2
Name: ARHGAP11B, dtype: int64

ARHGAP12
False    183
Name: ARHGAP12, dtype: int64

ARHGAP15
False    183
Name: ARHGAP15, dtype: int64

ARHGAP17
False    183
Name: ARHGAP17, dtype: int64

ARHGAP18
False    183
Name: ARHGAP18, dtype: int64

ARHGAP19
False    183
Name: ARHGAP19, dtype: int64

ARHGAP1
False    183
Name: ARHGAP1, dtype: int64

ARHGAP20

False    183
Name: ARHGAP20, dtype: int64

ARHGAP21
False    183
Name: ARHGAP21, dtype: int64

ARHGAP22
False    183
Name: ARHGAP22, dtype: int64

ARHGAP23
False    183
Name: ARHGAP23, dtype: int64

ARHGAP24
False    183
Name: ARHGAP24, dtype: int64

ARHGAP25
False    183
Name: ARHGAP25, dtype: int64

ARHGAP26
False    183
Name: ARHGAP26, dtype: int64

ARHGAP27
False    183
Name: ARHGAP27, dtype: int64

ARHGAP28
False    183
Name: ARHGAP28, dtype: int64

ARHGAP29
False    183
Name: ARHGAP29, dtype: int64

ARHGAP30
False    183
Name: ARHGAP30, dtype: int64

ARHGAP31
False    183
Name: ARHGAP31, dtype: int64

ARHGAP32
False    183
Name: ARHGAP32, dtype: int64

ARHGAP33
False    183
Name: ARHGAP33, dtype: int64

ARHGAP36
False    139
True      44
Name: ARHGAP36, dtype: int64

ARHGAP39
False    183
Name: ARHGAP39, dtype: int64

ARHGAP42
False    183
Name: ARHGAP42, dtype: int64

ARHGAP4
False    183
Name: ARHGAP4, dtype: int64

ARHGAP5
False    183
Name: ARHGAP5, dtype: int64

ARHGAP6
False    183
Name: ARHGAP6, dtype: int64

ARHGAP8
False    183
Name: ARHGAP8, dtype: int64

ARHGAP9
False    183
Name: ARHGAP9, dtype: int64

ARHGDIA
False    183
Name: ARHGDIA, dtype: int64

ARHGDIB
False    183
Name: ARHGDIB, dtype: int64

ARHGDIG
False    174
True       9
Name: ARHGDIG, dtype: int64

ARHGEF10L
False    183
Name: ARHGEF10L, dtype: int64

ARHGEF10
False    183
Name: ARHGEF10, dtype: int64

ARHGEF11
False    183
Name: ARHGEF11, dtype: int64

ARHGEF12
False    183
Name: ARHGEF12, dtype: int64

ARHGEF15
False    183
Name: ARHGEF15, dtype: int64

ARHGEF16
False    183
Name: ARHGEF16, dtype: int64

ARHGEF17
False    183
Name: ARHGEF17, dtype: int64

ARHGEF18
False    183
Name: ARHGEF18, dtype: int64

ARHGEF19
False    183
Name: ARHGEF19, dtype: int64

ARHGEF1
False    183
Name: ARHGEF1, dtype: int64

ARHGEF2
False    183
Name: ARHGEF2, dtype: int64

ARHGEF33
False    183
Name: ARHGEF33, dtype: int64

ARHGEF35
False    183
Name: ARHGEF35, dtype: int64

ARHGEF37
False    183
Name: ARHGEF37, dtype: int64

ARHGEF38
False    179
True       4
Name: ARHGEF38, dtype: int64

ARHGEF3
False    183
Name: ARHGEF3, dtype: int64

ARHGEF4
False    183
Name: ARHGEF4, dtype: int64

ARHGEF5
False    183
Name: ARHGEF5, dtype: int64

ARHGEF6
False    183
Name: ARHGEF6, dtype: int64

ARHGEF7
False    183
Name: ARHGEF7, dtype: int64

ARHGEF9
False    183
Name: ARHGEF9, dtype: int64

ARID1A
False    183
Name: ARID1A, dtype: int64

ARID1B
False    183
Name: ARID1B, dtype: int64

ARID2
False    183
Name: ARID2, dtype: int64

ARID3A
False    183
Name: ARID3A, dtype: int64

ARID3B
False    183
Name: ARID3B, dtype: int64

ARID3C
True     102
False     81
Name: ARID3C, dtype: int64

ARID4A
False    183
Name: ARID4A, dtype: int64

ARID4B
False    183
Name: ARID4B, dtype: int64

ARID5A
False    183
Name: ARID5A, dtype: int64

ARID5B
False    183
Name: ARID5B, dtype: int64

ARIH1
False    183
Name: ARIH1, dtype: int64

ARIH2
False    183
Name: ARIH2, dtype: int64

ARL10
False    183
Name: ARL10, dtype: int64

ARL11
False    183
Name: ARL11, dtype: int64

ARL13A
False    102
True      81
Name: ARL13A, dtype: int64

ARL13B
False    183
Name: ARL13B, dtype: int64

ARL14
False    180
True       3
Name: ARL14, dtype: int64

ARL15
False    183
Name: ARL15, dtype: int64

ARL16
False    183
Name: ARL16, dtype: int64

ARL17A
False    183
Name: ARL17A, dtype: int64

ARL17B
False    167
True      16
Name: ARL17B, dtype: int64

ARL1
False    183
Name: ARL1, dtype: int64

ARL2BP
False    183
Name: ARL2BP, dtype: int64

ARL2
False    183
Name: ARL2, dtype: int64

ARL3
False    183
Name: ARL3, dtype: int64

ARL4A
False    183
Name: ARL4A, dtype: int64

ARL4C
False    183
Name: ARL4C, dtype: int64

ARL4D
False    183
Name: ARL4D, dtype: int64

ARL5A
False    183
Name: ARL5A, dtype: int64

ARL5B
False    183
Name: ARL5B, dtype: int64

ARL5C
True     118
False     65
Name: ARL5C, dtype: int64

ARL6IP1
False    183
Name: ARL6IP1, dtype: int64

ARL6IP4
False    183
Name: ARL6IP4, dtype: int64

ARL6IP5
False    183
Name: ARL6IP5, dtype: int64

ARL6IP6
False    183
Name: ARL6IP6, dtype: int64

ARL6
False    183
Name: ARL6, dtype: int64

ARL8A
False    183
Name: ARL8A, dtype: int64

ARL8B
False    183
Name: ARL8B, dtype: int64

ARL9
False    183
Name: ARL9, dtype: int64

ARMC10
False    183
Name: ARMC10, dtype: int64

ARMC1
False    183
Name: ARMC1, dtype: int64

ARMC2
False    183
Name: ARMC2, dtype: int64

ARMC3
False    176
True       7
Name: ARMC3, dtype: int64

ARMC4
False    162
True      21
Name: ARMC4, dtype: int64

ARMC5
False    183
Name: ARMC5, dtype: int64

ARMC6
False    183
Name: ARMC6, dtype: int64

ARMC7
False    183
Name: ARMC7, dtype: int64

ARMC8
False    183
Name: ARMC8, dtype: int64

ARMC9
False    183
Name: ARMC9, dtype: int64

ARMCX1
False    183
Name: ARMCX1, dtype: int64

ARMCX2
False    183
Name: ARMCX2, dtype: int64

ARMCX3
False    183
Name: ARMCX3, dtype: int64

ARMCX5
False    183
Name: ARMCX5, dtype: int64

ARMCX6
False    183
Name: ARMCX6, dtype: int64

ARMS2
True     105
False     78
Name: ARMS2, dtype: int64

ARNT2
False    183
Name: ARNT2, dtype: int64

ARNTL2
False    183
Name: ARNTL2, dtype: int64

ARNTL
False    183
Name: ARNTL, dtype: int64

ARNT
False    183
Name: ARNT, dtype: int64

ARPC1A
False    183
Name: ARPC1A, dtype: int64

ARPC1B
False    183
Name: ARPC1B, dtype: int64

ARPC2
False    183
Name: ARPC2, dtype: int64

ARPC3
False    183
Name: ARPC3, dtype: int64

ARPC4
False    183
Name: ARPC4, dtype: int64

ARPC5L
False    183
Name: ARPC5L, dtype: int64

ARPC5
False    183
Name: ARPC5, dtype: int64

ARPM1
False    183
Name: ARPM1, dtype: int64

ARPP19
False    183
Name: ARPP19, dtype: int64

ARPP21
False    116
True      67
Name: ARPP21, dtype: int64

ARRB1
False    183
Name: ARRB1, dtype: int64

ARRB2
False    183
Name: ARRB2, dtype: int64

ARRDC1
False    183
Name: ARRDC1, dtype: int64

ARRDC2
False    183
Name: ARRDC2, dtype: int64

ARRDC3
False    183
Name: ARRDC3, dtype: int64

ARRDC4
False    183
Name: ARRDC4, dtype: int64

ARRDC5
False    177
True       6
Name: ARRDC5, dtype: int64

ARSA
False    183
Name: ARSA, dtype: int64

ARSB
False    183
Name: ARSB, dtype: int64

ARSD
False    183
Name: ARSD, dtype: int64

ARSE
False    183
Name: ARSE, dtype: int64

ARSF
False    104
True      79
Name: ARSF, dtype: int64

ARSG
False    183
Name: ARSG, dtype: int64

ARSH
False    138
True      45
Name: ARSH, dtype: int64

ARSI
False    183
Name: ARSI, dtype: int64

ARSJ
False    183
Name: ARSJ, dtype: int64

ARSK
False    183
Name: ARSK, dtype: int64

ART1
True     102
False     81
Name: ART1, dtype: int64

ART3
False    167
True      16
Name: ART3, dtype: int64

ART4
False    181
True       2
Name: ART4, dtype: int64

ART5
False    178
True       5
Name: ART5, dtype: int64

ARTN
False    183
Name: ARTN, dtype: int64

ARV1
False    183
Name: ARV1, dtype: int64

ARVCF
False    183
Name: ARVCF, dtype: int64

ARX
False    176
True       7
Name: ARX, dtype: int64

AR
False    181
True       2
Name: AR, dtype: int64

AS3MT
False    183
Name: AS3MT, dtype: int64

ASAH1
False    183
Name: ASAH1, dtype: int64

ASAH2B
False    171
True      12
Name: ASAH2B, dtype: int64

ASAH2
False    179
True       4
Name: ASAH2, dtype: int64

ASAM
False    183
Name: ASAM, dtype: int64

ASAP1
False    183
Name: ASAP1, dtype: int64

ASAP2
False    183
Name: ASAP2, dtype: int64

ASAP3
False    183
Name: ASAP3, dtype: int64

ASB12
False    167
True      16
Name: ASB12, dtype: int64

ASB13
False    183
Name: ASB13, dtype: int64

ASB14
False    183
Name: ASB14, dtype: int64

ASB16
False    183
Name: ASB16, dtype: int64

ASB1
False    183
Name: ASB1, dtype: int64

ASB2
False    183
Name: ASB2, dtype: int64

ASB3
False    183
Name: ASB3, dtype: int64

ASB4
False    160
True      23
Name: ASB4, dtype: int64

ASB5
False    96
True     87
Name: ASB5, dtype: int64

ASB6
False    183
Name: ASB6, dtype: int64

ASB7
False    183
Name: ASB7, dtype: int64

ASB8
False    183
Name: ASB8, dtype: int64

ASB9
False    183
Name: ASB9, dtype: int64

ASCC1
False    183
Name: ASCC1, dtype: int64

ASCC2
False    183
Name: ASCC2, dtype: int64

ASCC3
False    183
Name: ASCC3, dtype: int64

ASCL1
False    171
True      12
Name: ASCL1, dtype: int64

ASCL2
False    182
True       1
Name: ASCL2, dtype: int64

ASCL3
False    117
True      66
Name: ASCL3, dtype: int64

ASCL4
False    106
True      77
Name: ASCL4, dtype: int64

ASF1A
False    183
Name: ASF1A, dtype: int64

ASF1B
False    183
Name: ASF1B, dtype: int64

ASFMR1
False    95
True     88
Name: ASFMR1, dtype: int64

ASGR1
False    183
Name: ASGR1, dtype: int64

ASGR2

False    182
True       1
Name: ASGR2, dtype: int64

ASH1L
False    183
Name: ASH1L, dtype: int64

ASH2L
False    183
Name: ASH2L, dtype: int64

ASIP
False    133
True      50
Name: ASIP, dtype: int64

ASL
False    183
Name: ASL, dtype: int64

ASMTL
False    183
Name: ASMTL, dtype: int64

ASMT
False    132
True      51
Name: ASMT, dtype: int64

ASNA1
False    183
Name: ASNA1, dtype: int64

ASNSD1
False    183
Name: ASNSD1, dtype: int64

ASNS
False    183
Name: ASNS, dtype: int64

ASPA
False    182
True       1
Name: ASPA, dtype: int64

ASPDH
False    166
True      17
Name: ASPDH, dtype: int64

ASPG
False    159
True      24
Name: ASPG, dtype: int64

ASPHD1
False    183
Name: ASPHD1, dtype: int64

ASPHD2
False    183
Name: ASPHD2, dtype: int64

ASPH
False    183
Name: ASPH, dtype: int64

ASPM
False    183
Name: ASPM, dtype: int64

ASPN
False    183
Name: ASPN, dtype: int64

ASPRV1
False    183
Name: ASPRV1, dtype: int64

ASPSCR1
False    183
Name: ASPSCR1, dtype: int64

ASRGL1
False    183
Name: ASRGL1, dtype: int64

ASS1
False    183
Name: ASS1, dtype: int64

ASTE1
False    183
Name: ASTE1, dtype: int64

ASTL
False    114
True      69
Name: ASTL, dtype: int64

ASTN1
False    179
True       4
Name: ASTN1, dtype: int64

ASTN2
False    183
Name: ASTN2, dtype: int64

ASXL1
False    183
Name: ASXL1, dtype: int64

ASXL2
False    183
Name: ASXL2, dtype: int64

ASXL3
False    183
Name: ASXL3, dtype: int64

ATAD1
False    183
Name: ATAD1, dtype: int64

ATAD2B
False    183
Name: ATAD2B, dtype: int64

ATAD2
False    183
Name: ATAD2, dtype: int64

ATAD3A
False    183
Name: ATAD3A, dtype: int64

ATAD3B
False    183
Name: ATAD3B, dtype: int64

ATAD3C
False    183
Name: ATAD3C, dtype: int64

ATAD5
False    183
Name: ATAD5, dtype: int64

ATCAY
False    178
True       5
Name: ATCAY, dtype: int64

ATE1
False    183
Name: ATE1, dtype: int64

ATF1
False    183
Name: ATF1, dtype: int64

ATF2
False    183
Name: ATF2, dtype: int64

ATF3
False    183
Name: ATF3, dtype: int64

ATF4
False    183
Name: ATF4, dtype: int64

ATF5
False    183
Name: ATF5, dtype: int64

ATF6B
False    183
Name: ATF6B, dtype: int64

ATF6
False    183
Name: ATF6, dtype: int64

ATF7IP2
False    183
Name: ATF7IP2, dtype: int64

ATF7IP
False    183
Name: ATF7IP, dtype: int64

ATF7
False    183
Name: ATF7, dtype: int64

ATG10
False    183
Name: ATG10, dtype: int64

ATG12
False    183
Name: ATG12, dtype: int64

ATG16L1
False    183
Name: ATG16L1, dtype: int64

ATG16L2
False    183
Name: ATG16L2, dtype: int64

ATG2A
False    183
Name: ATG2A, dtype: int64

ATG2B
False    183
Name: ATG2B, dtype: int64

ATG3
False    183
Name: ATG3, dtype: int64

ATG4A
False    183
Name: ATG4A, dtype: int64

ATG4B
False    183
Name: ATG4B, dtype: int64

ATG4C
False    183
Name: ATG4C, dtype: int64

ATG4D
False    183
Name: ATG4D, dtype: int64

ATG5
False    183
Name: ATG5, dtype: int64

ATG7
False    183
Name: ATG7, dtype: int64

ATG9A
False    183
Name: ATG9A, dtype: int64

ATG9B
False    183
Name: ATG9B, dtype: int64

ATHL1
False    183
Name: ATHL1, dtype: int64

ATIC
False    183
Name: ATIC, dtype: int64

ATL1
False    183
Name: ATL1, dtype: int64

ATL2
False    183
Name: ATL2, dtype: int64

ATL3
False    183
Name: ATL3, dtype: int64

ATMIN
False    183
Name: ATMIN, dtype: int64

ATM
False    183
Name: ATM, dtype: int64

ATN1
False    183
Name: ATN1, dtype: int64

ATOH1
True     99
False    84
Name: ATOH1, dtype: int64

ATOH7
False    169
True      14
Name: ATOH7, dtype: int64

ATOH8
False    183
Name: ATOH8, dtype: int64

ATOX1
False    183
Name: ATOX1, dtype: int64

ATP10A
False    183
Name: ATP10A, dtype: int64

ATP10B
False    181
True       2
Name: ATP10B, dtype: int64

ATP10D
False    183
Name: ATP10D, dtype: int64

ATP11A
False    183
Name: ATP11A, dtype: int64

ATP11B
False    183
Name: ATP11B, dtype: int64

ATP11C
False    183
Name: ATP11C, dtype: int64

ATP12A
True     99
False    84
Name: ATP12A, dtype: int64

ATP13A1
False    183
Name: ATP13A1, dtype: int64

ATP13A2
False    183
Name: ATP13A2, dtype: int64

ATP13A3
False    183
Name: ATP13A3, dtype: int64

ATP13A4
False    181
True       2
Name: ATP13A4, dtype: int64

ATP13A5
False    105
True      78
Name: ATP13A5, dtype: int64

ATP1A1
False    183
Name: ATP1A1, dtype: int64

ATP1A2
False    183
Name: ATP1A2, dtype: int64

ATP1A3
False    183
Name: ATP1A3, dtype: int64

ATP1A4
False    136
True      47
Name: ATP1A4, dtype: int64

ATP1B1
False    183
Name: ATP1B1, dtype: int64

ATP1B2
False    183
Name: ATP1B2, dtype: int64

ATP1B3
False    183
Name: ATP1B3, dtype: int64

ATP2A1
False    183
Name: ATP2A1, dtype: int64

ATP2A2
False    183
Name: ATP2A2, dtype: int64

ATP2A3
False    183
Name: ATP2A3, dtype: int64

ATP2B1
False    183
Name: ATP2B1, dtype: int64

ATP2B2
False    180
True       3
Name: ATP2B2, dtype: int64

ATP2B3
False    159
True      24
Name: ATP2B3, dtype: int64

ATP2B4
False    183
Name: ATP2B4, dtype: int64

ATP2C1
False    183
Name: ATP2C1, dtype: int64

ATP2C2
False    183
Name: ATP2C2, dtype: int64

ATP4A
True     100
False     83
Name: ATP4A, dtype: int64

ATP4B
True     117
False     66
Name: ATP4B, dtype: int64

ATP5A1
False    183
Name: ATP5A1, dtype: int64

ATP5B
False    183
Name: ATP5B, dtype: int64

ATP5C1
False    183
Name: ATP5C1, dtype: int64

ATP5D
False    183
Name: ATP5D, dtype: int64

ATP5EP2
False    183
Name: ATP5EP2, dtype: int64

ATP5E
False    183
Name: ATP5E, dtype: int64

ATP5F1
False    183
Name: ATP5F1, dtype: int64

ATP5G1
False    183
Name: ATP5G1, dtype: int64

ATP5G2
False    183
Name: ATP5G2, dtype: int64

ATP5G3
False    183
Name: ATP5G3, dtype: int64

ATP5H
False    183
Name: ATP5H, dtype: int64

ATP5I
False    183
Name: ATP5I, dtype: int64

ATP5J2
False    183
Name: ATP5J2, dtype: int64

ATP5J
False    183
Name: ATP5J, dtype: int64

ATP5L2
False    116
True      67
Name: ATP5L2, dtype: int64

ATP5L
False    183
Name: ATP5L, dtype: int64

ATP5O
False    183
Name: ATP5O, dtype: int64

ATP5SL
False    183
Name: ATP5SL, dtype: int64

ATP5S
False    183
Name: ATP5S, dtype: int64

ATP6AP1L
False    183
Name: ATP6AP1L, dtype: int64

ATP6AP1
False    183
Name: ATP6AP1, dtype: int64

ATP6AP2
False    183
Name: ATP6AP2, dtype: int64

ATP6V0A1
False    183
Name: ATP6V0A1, dtype: int64

ATP6V0A2
False    183
Name: ATP6V0A2, dtype: int64

ATP6V0A4
False    165
True      18
Name: ATP6V0A4, dtype: int64

ATP6V0B
False    183
Name: ATP6V0B, dtype: int64

ATP6V0C
False    183
Name: ATP6V0C, dtype: int64

ATP6V0D1
False    183
Name: ATP6V0D1, dtype: int64

ATP6V0D2
False    182
True       1
Name: ATP6V0D2, dtype: int64

ATP6V0E1
False    183
Name: ATP6V0E1, dtype: int64

ATP6V0E2
False    183
Name: ATP6V0E2, dtype: int64

ATP6V1A
False    183
Name: ATP6V1A, dtype: int64

ATP6V1B1
False    183
Name: ATP6V1B1, dtype: int64

ATP6V1B2
False    183
Name: ATP6V1B2, dtype: int64

ATP6V1C1
False    183
Name: ATP6V1C1, dtype: int64

ATP6V1C2
False    183
Name: ATP6V1C2, dtype: int64

ATP6V1D
False    183
Name: ATP6V1D, dtype: int64

ATP6V1E1
False    183
Name: ATP6V1E1, dtype: int64

ATP6V1E2
False    183
Name: ATP6V1E2, dtype: int64

ATP6V1F
False    183
Name: ATP6V1F, dtype: int64

ATP6V1G1
False    183
Name: ATP6V1G1, dtype: int64

ATP6V1G2
False    183
Name: ATP6V1G2, dtype: int64

ATP6V1H
False    183
Name: ATP6V1H, dtype: int64

ATP7A
False    183
Name: ATP7A, dtype: int64

ATP7B
False    183
Name: ATP7B, dtype: int64

ATP8A1
False    183
Name: ATP8A1, dtype: int64

ATP8A2
False    183
Name: ATP8A2, dtype: int64

ATP8B1
False    183
Name: ATP8B1, dtype: int64

ATP8B2
False    183
Name: ATP8B2, dtype: int64

ATP8B3
False    183
Name: ATP8B3, dtype: int64

ATP8B4
False    183
Name: ATP8B4, dtype: int64

ATP8B5P
False    183
Name: ATP8B5P, dtype: int64

ATP9A
False    183
Name: ATP9A, dtype: int64

ATP9B
False    183
Name: ATP9B, dtype: int64

ATPAF1
False    183
Name: ATPAF1, dtype: int64

ATPAF2
False    183
Name: ATPAF2, dtype: int64

ATPBD4
False    183
Name: ATPBD4, dtype: int64

ATPIF1
False    183
Name: ATPIF1, dtype: int64

ATRIP
False    183
Name: ATRIP, dtype: int64

ATRNL1
False    182
True       1
Name: ATRNL1, dtype: int64

ATRN
False    183
Name: ATRN, dtype: int64

ATRX
False    183
Name: ATRX, dtype: int64

ATR
False    183
Name: ATR, dtype: int64

ATXN10
False    183
Name: ATXN10, dtype: int64

ATXN1L
False    183
Name: ATXN1L, dtype: int64

ATXN1
False    183
Name: ATXN1, dtype: int64

ATXN2L
False    183
Name: ATXN2L, dtype: int64

ATXN2
False    183
Name: ATXN2, dtype: int64

ATXN3
False    183
Name: ATXN3, dtype: int64

ATXN7L1
False    183
Name: ATXN7L1, dtype: int64

ATXN7L2

False    183
Name: ATXN7L2, dtype: int64

ATXN7L3B
False    183
Name: ATXN7L3B, dtype: int64

ATXN7L3
False    183
Name: ATXN7L3, dtype: int64

ATXN7
False    183
Name: ATXN7, dtype: int64

AUH
False    183
Name: AUH, dtype: int64

AUP1
False    183
Name: AUP1, dtype: int64

AURKAIP1
False    183
Name: AURKAIP1, dtype: int64

AURKAPS1
False    183
Name: AURKAPS1, dtype: int64

AURKA
False    183
Name: AURKA, dtype: int64

AURKB
False    183
Name: AURKB, dtype: int64

AURKC
False    182
True       1
Name: AURKC, dtype: int64

AUTS2
False    183
Name: AUTS2, dtype: int64

AVEN
False    183
Name: AVEN, dtype: int64

AVIL
False    183
Name: AVIL, dtype: int64

AVL9
False    183
Name: AVL9, dtype: int64

AVPI1
False    183
Name: AVPI1, dtype: int64

AVPR1A
False    181
True       2
Name: AVPR1A, dtype: int64

AVPR1B
False    158
True      25
Name: AVPR1B, dtype: int64

AVPR2
False    182
True       1
Name: AVPR2, dtype: int64

AWAT2
True     125
False     58
Name: AWAT2, dtype: int64

AXIN1
False    183
Name: AXIN1, dtype: int64

AXIN2
False    183
Name: AXIN2, dtype: int64

AXL
False    183
Name: AXL, dtype: int64

AZGP1
False    183
Name: AZGP1, dtype: int64

AZI1
False    183
Name: AZI1, dtype: int64

AZI2
False    183
Name: AZI2, dtype: int64

AZIN1
False    183
Name: AZIN1, dtype: int64

AZU1
False    147
True      36
Name: AZU1, dtype: int64

B2M
False    183
Name: B2M, dtype: int64

B3GALNT1
False    183
Name: B3GALNT1, dtype: int64

B3GALNT2
False    183
Name: B3GALNT2, dtype: int64

B3GALT1
False    152
True      31
Name: B3GALT1, dtype: int64

B3GALT2
False    183
Name: B3GALT2, dtype: int64

B3GALT4
False    183
Name: B3GALT4, dtype: int64

B3GALT5
False    181
True       2
Name: B3GALT5, dtype: int64

B3GALT6
False    183
Name: B3GALT6, dtype: int64

B3GALTL
False    183
Name: B3GALTL, dtype: int64

B3GAT1
False    181
True       2
Name: B3GAT1, dtype: int64

B3GAT2
False    182
True       1
Name: B3GAT2, dtype: int64

B3GAT3
False    183
Name: B3GAT3, dtype: int64

B3GNT1
False    183
Name: B3GNT1, dtype: int64

B3GNT2
False    183
Name: B3GNT2, dtype: int64

B3GNT3
False    183
Name: B3GNT3, dtype: int64

B3GNT4
False    183
Name: B3GNT4, dtype: int64

B3GNT5
False    183
Name: B3GNT5, dtype: int64

B3GNT6
False    169
True      14
Name: B3GNT6, dtype: int64

B3GNT7
False    183
Name: B3GNT7, dtype: int64

B3GNT8
False    183
Name: B3GNT8, dtype: int64

B3GNT9
False    183
Name: B3GNT9, dtype: int64

B3GNTL1
False    183
Name: B3GNTL1, dtype: int64

B4GALNT1
False    183
Name: B4GALNT1, dtype: int64

B4GALNT2
False    101
True      82
Name: B4GALNT2, dtype: int64

B4GALNT3
False    183
Name: B4GALNT3, dtype: int64

B4GALNT4
False    183
Name: B4GALNT4, dtype: int64

B4GALT1
False    183
Name: B4GALT1, dtype: int64

B4GALT2
False    183
Name: B4GALT2, dtype: int64

B4GALT3
False    183
Name: B4GALT3, dtype: int64

B4GALT4
False    183
Name: B4GALT4, dtype: int64

B4GALT5
False    183
Name: B4GALT5, dtype: int64

B4GALT6
False    183
Name: B4GALT6, dtype: int64

B4GALT7
False    183
Name: B4GALT7, dtype: int64

B9D1
False    183
Name: B9D1, dtype: int64

B9D2
False    183
Name: B9D2, dtype: int64

BAALC
False    183
Name: BAALC, dtype: int64

BAAT
False    182
True       1
Name: BAAT, dtype: int64

BACE1
False    183
Name: BACE1, dtype: int64

BACE2
False    183
Name: BACE2, dtype: int64

BACH1
False    183
Name: BACH1, dtype: int64

BACH2
False    183
Name: BACH2, dtype: int64

BAD
False    183
Name: BAD, dtype: int64

BAG1
False    183
Name: BAG1, dtype: int64

BAG2
False    183
Name: BAG2, dtype: int64

BAG3
False    183
Name: BAG3, dtype: int64

BAG4
False    183
Name: BAG4, dtype: int64

BAG5
False    183
Name: BAG5, dtype: int64

BAGE2
False    155
True      28
Name: BAGE2, dtype: int64

BAHCC1
False    183
Name: BAHCC1, dtype: int64

BAHD1
False    183
Name: BAHD1, dtype: int64

BAI1
False    182
True       1
Name: BAI1, dtype: int64

BAI2
False    183
Name: BAI2, dtype: int64

BAI3
False    180
True       3
Name: BAI3, dtype: int64

BAIAP2L1
False    183
Name: BAIAP2L1, dtype: int64

BAIAP2L2
False    183
Name: BAIAP2L2, dtype: int64

BAIAP2
False    183
Name: BAIAP2, dtype: int64

BAIAP3
False    183
Name: BAIAP3, dtype: int64

BAK1
False    183
Name: BAK1, dtype: int64

BAMBI
False    183
Name: BAMBI, dtype: int64

BANF1
False    183
Name: BANF1, dtype: int64

BANK1
False    182
True       1
Name: BANK1, dtype: int64

BANP
False    183
Name: BANP, dtype: int64

BAP1
False    183
Name: BAP1, dtype: int64

BARD1
False    182
True       1
Name: BARD1, dtype: int64

BARHL1
True     113
False     70
Name: BARHL1, dtype: int64

BARX1
False    175
True       8
Name: BARX1, dtype: int64

BARX2
False    181
True       2
Name: BARX2, dtype: int64

BASP1
False    183
Name: BASP1, dtype: int64

BAT1
False    183
Name: BAT1, dtype: int64

BAT2L1
False    183
Name: BAT2L1, dtype: int64

BAT2L2
False    183
Name: BAT2L2, dtype: int64

BAT2
False    183
Name: BAT2, dtype: int64

BAT3
False    183
Name: BAT3, dtype: int64

BAT4
False    183
Name: BAT4, dtype: int64

BAT5
False    183
Name: BAT5, dtype: int64

BATF2
False    183
Name: BATF2, dtype: int64

BATF3
False    183
Name: BATF3, dtype: int64

BATF
False    183
Name: BATF, dtype: int64

BAX
False    183
Name: BAX, dtype: int64

BAZ1A
False    183
Name: BAZ1A, dtype: int64

BAZ1B
False    183
Name: BAZ1B, dtype: int64

BAZ2A
False    183
Name: BAZ2A, dtype: int64

BAZ2B
False    183
Name: BAZ2B, dtype: int64

BBC3
False    183
Name: BBC3, dtype: int64

BBOX1
False    174
True       9
Name: BBOX1, dtype: int64

BBS10
False    183
Name: BBS10, dtype: int64

BBS12
False    183
Name: BBS12, dtype: int64

BBS1
False    183
Name: BBS1, dtype: int64

BBS2
False    183
Name: BBS2, dtype: int64

BBS4
False    183
Name: BBS4, dtype: int64

BBS5
False    183
Name: BBS5, dtype: int64

BBS7
False    183
Name: BBS7, dtype: int64

BBS9
False    183
Name: BBS9, dtype: int64

BBX
False    183
Name: BBX, dtype: int64

BCAM
False    183
Name: BCAM, dtype: int64

BCAN
False    183
Name: BCAN, dtype: int64

BCAP29
False    183
Name: BCAP29, dtype: int64

BCAP31
False    183
Name: BCAP31, dtype: int64

BCAR1
False    183
Name: BCAR1, dtype: int64

BCAR3
False    183
Name: BCAR3, dtype: int64

BCAS1
False    182
True       1
Name: BCAS1, dtype: int64

BCAS2
False    183
Name: BCAS2, dtype: int64

BCAS3
False    183
Name: BCAS3, dtype: int64

BCAS4
False    183
Name: BCAS4, dtype: int64

BCAT1
False    183
Name: BCAT1, dtype: int64

BCAT2
False    183
Name: BCAT2, dtype: int64

BCCIP
False    183
Name: BCCIP, dtype: int64

BCDIN3D
False    183
Name: BCDIN3D, dtype: int64

BCHE
False    183
Name: BCHE, dtype: int64

BCKDHA
False    183
Name: BCKDHA, dtype: int64

BCKDHB
False    183
Name: BCKDHB, dtype: int64

BCKDK
False    183
Name: BCKDK, dtype: int64

BCL10
False    183
Name: BCL10, dtype: int64

BCL11A
False    183
Name: BCL11A, dtype: int64

BCL11B
False    183
Name: BCL11B, dtype: int64

BCL2A1
False    183
Name: BCL2A1, dtype: int64

BCL2L10
False    176
True       7
Name: BCL2L10, dtype: int64

BCL2L11
False    183
Name: BCL2L11, dtype: int64

BCL2L12
False    183
Name: BCL2L12, dtype: int64

BCL2L13
False    183
Name: BCL2L13, dtype: int64

BCL2L14
False    182
True       1
Name: BCL2L14, dtype: int64

BCL2L15
False    183
Name: BCL2L15, dtype: int64

BCL2L1
False    183
Name: BCL2L1, dtype: int64

BCL2L2
False    183
Name: BCL2L2, dtype: int64

BCL2
False    183
Name: BCL2, dtype: int64

BCL3
False    183
Name: BCL3, dtype: int64

BCL6B
False    183
Name: BCL6B, dtype: int64

BCL6
False    183
Name: BCL6, dtype: int64

BCL7A
False    183
Name: BCL7A, dtype: int64

BCL7B
False    183
Name: BCL7B, dtype: int64

BCL7C
False    183
Name: BCL7C, dtype: int64

BCL8
False    156
True      27
Name: BCL8, dtype: int64

BCL9L
False    183
Name: BCL9L, dtype: int64

BCL9
False    183
Name: BCL9, dtype: int64

BCLAF1
False    183
Name: BCLAF1, dtype: int64

BCMO1
False    182
True       1
Name: BCMO1, dtype: int64

BCO2
False    183
Name: BCO2, dtype: int64

BCORL1
False    183
Name: BCORL1, dtype: int64

BCORL2
False    94
True     89
Name: BCORL2, dtype: int64

BCOR
False    183
Name: BCOR, dtype: int64

BCR
False    183
Name: BCR, dtype: int64

BCS1L
False    183
Name: BCS1L, dtype: int64

BDH1
False    183
Name: BDH1, dtype: int64

BDH2
False    183
Name: BDH2, dtype: int64

BDKRB1
False    183
Name: BDKRB1, dtype: int64

BDKRB2
False    183
Name: BDKRB2, dtype: int64

BDNFOS
False    183
Name: BDNFOS, dtype: int64

BDNF
False    183
Name: BDNF, dtype: int64

BDP1

False    183
Name: BDP1, dtype: int64

BEAN
False    183
Name: BEAN, dtype: int64

BECN1
False    183
Name: BECN1, dtype: int64

BEGAIN
False    183
Name: BEGAIN, dtype: int64

BEND3
False    183
Name: BEND3, dtype: int64

BEND4
False    165
True      18
Name: BEND4, dtype: int64

BEND5
False    183
Name: BEND5, dtype: int64

BEND6
False    183
Name: BEND6, dtype: int64

BEND7
False    183
Name: BEND7, dtype: int64

BEST1
False    183
Name: BEST1, dtype: int64

BEST2
True     114
False     69
Name: BEST2, dtype: int64

BEST3
False    169
True      14
Name: BEST3, dtype: int64

BEST4
False    183
Name: BEST4, dtype: int64

BET1L
False    183
Name: BET1L, dtype: int64

BET1
False    183
Name: BET1, dtype: int64

BET3L
False    132
True      51
Name: BET3L, dtype: int64

BEX1
False    183
Name: BEX1, dtype: int64

BEX2
False    183
Name: BEX2, dtype: int64

BEX4
False    183
Name: BEX4, dtype: int64

BEX5
False    183
Name: BEX5, dtype: int64

BFAR
False    183
Name: BFAR, dtype: int64

BFSP1
False    183
Name: BFSP1, dtype: int64

BFSP2
False    137
True      46
Name: BFSP2, dtype: int64

BGLAP
False    183
Name: BGLAP, dtype: int64

BGN
False    183
Name: BGN, dtype: int64

BHLHA15
False    179
True       4
Name: BHLHA15, dtype: int64

BHLHB9
False    183
Name: BHLHB9, dtype: int64

BHLHE22
False    183
Name: BHLHE22, dtype: int64

BHLHE40
False    183
Name: BHLHE40, dtype: int64

BHLHE41
False    183
Name: BHLHE41, dtype: int64

BHMT2
False    183
Name: BHMT2, dtype: int64

BHMT
False    162
True      21
Name: BHMT, dtype: int64

BICC1
False    182
True       1
Name: BICC1, dtype: int64

BICD1
False    183
Name: BICD1, dtype: int64

BICD2
False    183
Name: BICD2, dtype: int64

BID
False    183
Name: BID, dtype: int64

BIK
False    183
Name: BIK, dtype: int64

BIN1
False    183
Name: BIN1, dtype: int64

BIN2
False    183
Name: BIN2, dtype: int64

BIN3
False    183
Name: BIN3, dtype: int64

BIRC2
False    183
Name: BIRC2, dtype: int64

BIRC3
False    183
Name: BIRC3, dtype: int64

BIRC5
False    183
Name: BIRC5, dtype: int64

BIRC6
False    183
Name: BIRC6, dtype: int64

BIRC7
False    178
True       5
Name: BIRC7, dtype: int64

BIVM
False    183
Name: BIVM, dtype: int64

BLCAP
False    183
Name: BLCAP, dtype: int64

BLK
False    179
True       4
Name: BLK, dtype: int64

BLMH
False    183
Name: BLMH, dtype: int64

BLM
False    183
Name: BLM, dtype: int64

BLNK
False    183
Name: BLNK, dtype: int64

BLOC1S1
False    183
Name: BLOC1S1, dtype: int64

BLOC1S2
False    183
Name: BLOC1S2, dtype: int64

BLOC1S3
False    183
Name: BLOC1S3, dtype: int64

BLVRA
False    183
Name: BLVRA, dtype: int64

BLVRB
False    183
Name: BLVRB, dtype: int64

BLZF1
False    183
Name: BLZF1, dtype: int64

BMF
False    183
Name: BMF, dtype: int64

BMI1
False    183
Name: BMI1, dtype: int64

BMP1
False    183
Name: BMP1, dtype: int64

BMP2K
False    183
Name: BMP2K, dtype: int64

BMP2
False    183
Name: BMP2, dtype: int64

BMP3
False    178
True       5
Name: BMP3, dtype: int64

BMP4
False    183
Name: BMP4, dtype: int64

BMP5
False    174
True       9
Name: BMP5, dtype: int64

BMP6
False    183
Name: BMP6, dtype: int64

BMP7
False    183
Name: BMP7, dtype: int64

BMP8A
False    183
Name: BMP8A, dtype: int64

BMP8B
False    183
Name: BMP8B, dtype: int64

BMPER
False    182
True       1
Name: BMPER, dtype: int64

BMPR1A
False    183
Name: BMPR1A, dtype: int64

BMPR1B
False    182
True       1
Name: BMPR1B, dtype: int64

BMPR2
False    183
Name: BMPR2, dtype: int64

BMS1P4
False    183
Name: BMS1P4, dtype: int64

BMS1P5
False    183
Name: BMS1P5, dtype: int64

BMS1
False    183
Name: BMS1, dtype: int64

BMX
False    183
Name: BMX, dtype: int64

BNC1
False    163
True      20
Name: BNC1, dtype: int64

BNC2
False    183
Name: BNC2, dtype: int64

BNIP1
False    183
Name: BNIP1, dtype: int64

BNIP2
False    183
Name: BNIP2, dtype: int64

BNIP3L
False    183
Name: BNIP3L, dtype: int64

BNIP3
False    183
Name: BNIP3, dtype: int64

BNIPL
False    183
Name: BNIPL, dtype: int64

BOC
False    183
Name: BOC, dtype: int64

BOD1L
False    183
Name: BOD1L, dtype: int64

BOD1
False    183
Name: BOD1, dtype: int64

BOK
False    183
Name: BOK, dtype: int64

BOLA1
False    183
Name: BOLA1, dtype: int64

BOLA2
False    183
Name: BOLA2, dtype: int64

BOLA3
False    183
Name: BOLA3, dtype: int64

BOP1
False    183
Name: BOP1, dtype: int64

BPGM
False    183
Name: BPGM, dtype: int64

BPHL
False    183
Name: BPHL, dtype: int64

BPIL2
True     127
False     56
Name: BPIL2, dtype: int64

BPI
False    171
True      12
Name: BPI, dtype: int64

BPNT1
False    183
Name: BPNT1, dtype: int64

BPTF
False    183
Name: BPTF, dtype: int64

BRAF
False    183
Name: BRAF, dtype: int64

BRAP
False    183
Name: BRAP, dtype: int64

BRCA1
False    183
Name: BRCA1, dtype: int64

BRCA2
False    183
Name: BRCA2, dtype: int64

BRCC3
False    183
Name: BRCC3, dtype: int64

BRD1
False    183
Name: BRD1, dtype: int64

BRD2
False    183
Name: BRD2, dtype: int64

BRD3
False    183
Name: BRD3, dtype: int64

BRD4
False    183
Name: BRD4, dtype: int64

BRD7P3
False    122
True      61
Name: BRD7P3, dtype: int64

BRD7
False    183
Name: BRD7, dtype: int64

BRD8
False    183
Name: BRD8, dtype: int64

BRD9
False    183
Name: BRD9, dtype: int64

BRDT
True     128
False     55
Name: BRDT, dtype: int64

BREA2
False    181
True       2
Name: BREA2, dtype: int64

BRE
False    183
Name: BRE, dtype: int64

BRF1
False    183
Name: BRF1, dtype: int64

BRF2
False    183
Name: BRF2, dtype: int64

BRI3BP
False    183
Name: BRI3BP, dtype: int64

BRI3
False    183
Name: BRI3, dtype: int64

BRIP1
False    183
Name: BRIP1, dtype: int64

BRIX1
False    183
Name: BRIX1, dtype: int64

BRMS1L
False    183
Name: BRMS1L, dtype: int64

BRMS1
False    183
Name: BRMS1, dtype: int64

BRP44L
False    183
Name: BRP44L, dtype: int64

BRP44
False    183
Name: BRP44, dtype: int64

BRPF1
False    183
Name: BRPF1, dtype: int64

BRPF3
False    183
Name: BRPF3, dtype: int64

BRS3
False    123
True      60
Name: BRS3, dtype: int64

BRSK1
False    183
Name: BRSK1, dtype: int64

BRSK2
False    182
True       1
Name: BRSK2, dtype: int64

BRWD1
False    183
Name: BRWD1, dtype: int64

BRWD3
False    183
Name: BRWD3, dtype: int64

BSCL2
False    183
Name: BSCL2, dtype: int64

BSDC1
False    183
Name: BSDC1, dtype: int64

BSG
False    183
Name: BSG, dtype: int64

BSND
True     93
False    90
Name: BSND, dtype: int64

BSN
False    183
Name: BSN, dtype: int64

BSPRY
False    183
Name: BSPRY, dtype: int64

BST1
False    183
Name: BST1, dtype: int64

BST2
False    183
Name: BST2, dtype: int64

BTAF1
False    183
Name: BTAF1, dtype: int64

BTBD10
False    183
Name: BTBD10, dtype: int64

BTBD11
False    183
Name: BTBD11, dtype: int64

BTBD12
False    183
Name: BTBD12, dtype: int64

BTBD16
False    182
True       1
Name: BTBD16, dtype: int64

BTBD17
False    155
True      28
Name: BTBD17, dtype: int64

BTBD18
False    156
True      27
Name: BTBD18, dtype: int64

BTBD19
False    183
Name: BTBD19, dtype: int64

BTBD1
False    183
Name: BTBD1, dtype: int64

BTBD2
False    183
Name: BTBD2, dtype: int64

BTBD3
False    183
Name: BTBD3, dtype: int64

BTBD6
False    183
Name: BTBD6, dtype: int64

BTBD7
False    183
Name: BTBD7, dtype: int64

BTBD8
False    176
True       7
Name: BTBD8, dtype: int64

BTBD9
False    183
Name: BTBD9, dtype: int64

BTC
False    181
True       2
Name: BTC, dtype: int64

BTD
False    183
Name: BTD, dtype: int64

BTF3L4
False    183
Name: BTF3L4, dtype: int64

BTF3
False    183
Name: BTF3, dtype: int64

BTG1
False    183
Name: BTG1, dtype: int64

BTG2
False    183
Name: BTG2, dtype: int64

BTG3
False    183
Name: BTG3, dtype: int64

BTK
False    183
Name: BTK, dtype: int64

BTLA
False    181
True       2
Name: BTLA, dtype: int64

BTN1A1
False    151
True      32
Name: BTN1A1, dtype: int64

BTN2A1
False    183
Name: BTN2A1, dtype: int64

BTN2A2
False    183
Name: BTN2A2, dtype: int64

BTN2A3
False    183
Name: BTN2A3, dtype: int64

BTN3A1
False    183
Name: BTN3A1, dtype: int64

BTN3A2
False    183
Name: BTN3A2, dtype: int64

BTN3A3
False    183
Name: BTN3A3, dtype: int64

BTNL3
False    141
True      42
Name: BTNL3, dtype: int64

BTNL8
False    177
True       6
Name: BTNL8, dtype: int64

BTNL9
False    183
Name: BTNL9, dtype: int64

BTRC
False    183
Name: BTRC, dtype: int64

BUB1B

False    183
Name: BUB1B, dtype: int64

BUB1
False    183
Name: BUB1, dtype: int64

BUB3
False    183
Name: BUB3, dtype: int64

BUD13
False    183
Name: BUD13, dtype: int64

BUD31
False    183
Name: BUD31, dtype: int64

BVES
False    183
Name: BVES, dtype: int64

BYSL
False    183
Name: BYSL, dtype: int64

BZRAP1
False    183
Name: BZRAP1, dtype: int64

BZW1
False    183
Name: BZW1, dtype: int64

BZW2
False    183
Name: BZW2, dtype: int64

C10orf105
False    182
True       1
Name: C10orf105, dtype: int64

C10orf107
False    181
True       2
Name: C10orf107, dtype: int64

C10orf108
False    183
Name: C10orf108, dtype: int64

C10orf10
False    183
Name: C10orf10, dtype: int64

C10orf110
False    183
Name: C10orf110, dtype: int64

C10orf111
False    182
True       1
Name: C10orf111, dtype: int64

C10orf114
False    183
Name: C10orf114, dtype: int64

C10orf116
False    183
Name: C10orf116, dtype: int64

C10orf118
False    183
Name: C10orf118, dtype: int64

C10orf119
False    183
Name: C10orf119, dtype: int64

C10orf11
False    183
Name: C10orf11, dtype: int64

C10orf125
False    183
Name: C10orf125, dtype: int64

C10orf128
False    180
True       3
Name: C10orf128, dtype: int64

C10orf129
True     108
False     75
Name: C10orf129, dtype: int64

C10orf12
False    183
Name: C10orf12, dtype: int64

C10orf131
False    123
True      60
Name: C10orf131, dtype: int64

C10orf137
False    183
Name: C10orf137, dtype: int64

C10orf140
False    183
Name: C10orf140, dtype: int64

C10orf18
False    183
Name: C10orf18, dtype: int64

C10orf25
False    183
Name: C10orf25, dtype: int64

C10orf26
False    183
Name: C10orf26, dtype: int64

C10orf27
True     116
False     67
Name: C10orf27, dtype: int64

C10orf28
False    183
Name: C10orf28, dtype: int64

C10orf2
False    183
Name: C10orf2, dtype: int64

C10orf32
False    183
Name: C10orf32, dtype: int64

C10orf35
False    183
Name: C10orf35, dtype: int64

C10orf41
False    183
Name: C10orf41, dtype: int64

C10orf46
False    183
Name: C10orf46, dtype: int64

C10orf47
False    183
Name: C10orf47, dtype: int64

C10orf4
False    183
Name: C10orf4, dtype: int64

C10orf50
False    98
True     85
Name: C10orf50, dtype: int64

C10orf54
False    183
Name: C10orf54, dtype: int64

C10orf55
False    179
True       4
Name: C10orf55, dtype: int64

C10orf57
False    183
Name: C10orf57, dtype: int64

C10orf58
False    183
Name: C10orf58, dtype: int64

C10orf62
False    106
True      77
Name: C10orf62, dtype: int64

C10orf67
False    165
True      18
Name: C10orf67, dtype: int64

C10orf68
False    182
True       1
Name: C10orf68, dtype: int64

C10orf72
False    183
Name: C10orf72, dtype: int64

C10orf75
False    183
Name: C10orf75, dtype: int64

C10orf76
False    183
Name: C10orf76, dtype: int64

C10orf78
False    183
Name: C10orf78, dtype: int64

C10orf79
False    182
True       1
Name: C10orf79, dtype: int64

C10orf81
False    183
Name: C10orf81, dtype: int64

C10orf82
False    139
True      44
Name: C10orf82, dtype: int64

C10orf84
False    183
Name: C10orf84, dtype: int64

C10orf88
False    183
Name: C10orf88, dtype: int64

C10orf90
False    141
True      42
Name: C10orf90, dtype: int64

C10orf91
False    167
True      16
Name: C10orf91, dtype: int64

C10orf93
False    170
True      13
Name: C10orf93, dtype: int64

C10orf95
False    183
Name: C10orf95, dtype: int64

C10orf99
True     101
False     82
Name: C10orf99, dtype: int64

C11orf10
False    183
Name: C11orf10, dtype: int64

C11orf16
False    126
True      57
Name: C11orf16, dtype: int64

C11orf17
False    183
Name: C11orf17, dtype: int64

C11orf1
False    183
Name: C11orf1, dtype: int64

C11orf20
False    161
True      22
Name: C11orf20, dtype: int64

C11orf21
False    182
True       1
Name: C11orf21, dtype: int64

C11orf24
False    183
Name: C11orf24, dtype: int64

C11orf2
False    183
Name: C11orf2, dtype: int64

C11orf30
False    183
Name: C11orf30, dtype: int64

C11orf31
False    183
Name: C11orf31, dtype: int64

C11orf34
True     106
False     77
Name: C11orf34, dtype: int64

C11orf35
False    183
Name: C11orf35, dtype: int64

C11orf41
False    183
Name: C11orf41, dtype: int64

C11orf42
False    150
True      33
Name: C11orf42, dtype: int64

C11orf45
False    183
Name: C11orf45, dtype: int64

C11orf46
False    183
Name: C11orf46, dtype: int64

C11orf48
False    183
Name: C11orf48, dtype: int64

C11orf49
False    183
Name: C11orf49, dtype: int64

C11orf51
False    183
Name: C11orf51, dtype: int64

C11orf52
False    183
Name: C11orf52, dtype: int64

C11orf53
False    178
True       5
Name: C11orf53, dtype: int64

C11orf54
False    183
Name: C11orf54, dtype: int64

C11orf57
False    183
Name: C11orf57, dtype: int64

C11orf58
False    183
Name: C11orf58, dtype: int64

C11orf59
False    183
Name: C11orf59, dtype: int64

C11orf61
False    183
Name: C11orf61, dtype: int64

C11orf63
False    182
True       1
Name: C11orf63, dtype: int64

C11orf65
False    181
True       2
Name: C11orf65, dtype: int64

C11orf66
False    183
Name: C11orf66, dtype: int64

C11orf67
False    183
Name: C11orf67, dtype: int64

C11orf68
False    183
Name: C11orf68, dtype: int64

C11orf70
False    182
True       1
Name: C11orf70, dtype: int64

C11orf71
False    183
Name: C11orf71, dtype: int64

C11orf73
False    183
Name: C11orf73, dtype: int64

C11orf74
False    183
Name: C11orf74, dtype: int64

C11orf75
False    183
Name: C11orf75, dtype: int64

C11orf80
False    183
Name: C11orf80, dtype: int64

C11orf82
False    183
Name: C11orf82, dtype: int64

C11orf83
False    183
Name: C11orf83, dtype: int64

C11orf84
False    183
Name: C11orf84, dtype: int64

C11orf85
False    112
True      71
Name: C11orf85, dtype: int64

C11orf86
False    174
True       9
Name: C11orf86, dtype: int64

C11orf87
False    162
True      21
Name: C11orf87, dtype: int64

C11orf88
False    170
True      13
Name: C11orf88, dtype: int64

C11orf90
False    166
True      17
Name: C11orf90, dtype: int64

C11orf92
False    183
Name: C11orf92, dtype: int64

C11orf93
False    183
Name: C11orf93, dtype: int64

C11orf95
False    183
Name: C11orf95, dtype: int64

C11orf9
False    183
Name: C11orf9, dtype: int64

C12orf10
False    183
Name: C12orf10, dtype: int64

C12orf11
False    183
Name: C12orf11, dtype: int64

C12orf23
False    183
Name: C12orf23, dtype: int64

C12orf24
False    183
Name: C12orf24, dtype: int64

C12orf26
False    183
Name: C12orf26, dtype: int64

C12orf27
False    180
True       3
Name: C12orf27, dtype: int64

C12orf29
False    183
Name: C12orf29, dtype: int64

C12orf32
False    183
Name: C12orf32, dtype: int64

C12orf34
False    183
Name: C12orf34, dtype: int64

C12orf35
False    183
Name: C12orf35, dtype: int64

C12orf36
False    175
True       8
Name: C12orf36, dtype: int64

C12orf39
True     101
False     82
Name: C12orf39, dtype: int64

C12orf41
False    183
Name: C12orf41, dtype: int64

C12orf42
False    129
True      54
Name: C12orf42, dtype: int64

C12orf43
False    183
Name: C12orf43, dtype: int64

C12orf44
False    183
Name: C12orf44, dtype: int64

C12orf45
False    183
Name: C12orf45, dtype: int64

C12orf47
False    183
Name: C12orf47, dtype: int64

C12orf48
False    183
Name: C12orf48, dtype: int64

C12orf49
False    183
Name: C12orf49, dtype: int64

C12orf4
False    183
Name: C12orf4, dtype: int64

C12orf51
False    183
Name: C12orf51, dtype: int64

C12orf52
False    183
Name: C12orf52, dtype: int64

C12orf53
False    183
Name: C12orf53, dtype: int64

C12orf54
False    118
True      65
Name: C12orf54, dtype: int64

C12orf56
False    135
True      48
Name: C12orf56, dtype: int64

C12orf57
False    183
Name: C12orf57, dtype: int64

C12orf59
False    183
Name: C12orf59, dtype: int64

C12orf5
False    183
Name: C12orf5, dtype: int64

C12orf60
False    183
Name: C12orf60, dtype: int64

C12orf61
False    183
Name: C12orf61, dtype: int64

C12orf62
False    183
Name: C12orf62, dtype: int64

C12orf63
False    165
True      18
Name: C12orf63, dtype: int64

C12orf65
False    183
Name: C12orf65, dtype: int64

C12orf66
False    183
Name: C12orf66, dtype: int64

C12orf68
False    183
Name: C12orf68, dtype: int64

C12orf69
False    182
True       1
Name: C12orf69, dtype: int64

C12orf70
False    180
True       3
Name: C12orf70, dtype: int64

C12orf71
False    113
True      70
Name: C12orf71, dtype: int64

C12orf72
False    183
Name: C12orf72, dtype: int64

C12orf73
False    183
Name: C12orf73, dtype: int64

C12orf74

False    177
True       6
Name: C12orf74, dtype: int64

C12orf75
False    183
Name: C12orf75, dtype: int64

C12orf76
False    183
Name: C12orf76, dtype: int64

C12orf77
True     128
False     55
Name: C12orf77, dtype: int64

C13orf15
False    183
Name: C13orf15, dtype: int64

C13orf16
False    168
True      15
Name: C13orf16, dtype: int64

C13orf18
False    183
Name: C13orf18, dtype: int64

C13orf1
False    183
Name: C13orf1, dtype: int64

C13orf23
False    183
Name: C13orf23, dtype: int64

C13orf26
False    134
True      49
Name: C13orf26, dtype: int64

C13orf27
False    183
Name: C13orf27, dtype: int64

C13orf29
False    183
Name: C13orf29, dtype: int64

C13orf30
False    163
True      20
Name: C13orf30, dtype: int64

C13orf31
False    183
Name: C13orf31, dtype: int64

C13orf33
False    183
Name: C13orf33, dtype: int64

C13orf34
False    183
Name: C13orf34, dtype: int64

C13orf35
True     105
False     78
Name: C13orf35, dtype: int64

C13orf36
False    173
True      10
Name: C13orf36, dtype: int64

C13orf37
False    183
Name: C13orf37, dtype: int64

C13orf38
False    144
True      39
Name: C13orf38, dtype: int64

C13orf39
True     112
False     71
Name: C13orf39, dtype: int64

C14orf101
False    183
Name: C14orf101, dtype: int64

C14orf102
False    183
Name: C14orf102, dtype: int64

C14orf104
False    183
Name: C14orf104, dtype: int64

C14orf105
False    182
True       1
Name: C14orf105, dtype: int64

C14orf106
False    183
Name: C14orf106, dtype: int64

C14orf109
False    183
Name: C14orf109, dtype: int64

C14orf115
False    159
True      24
Name: C14orf115, dtype: int64

C14orf118
False    183
Name: C14orf118, dtype: int64

C14orf119
False    183
Name: C14orf119, dtype: int64

C14orf126
False    183
Name: C14orf126, dtype: int64

C14orf128
False    183
Name: C14orf128, dtype: int64

C14orf129
False    183
Name: C14orf129, dtype: int64

C14orf132
False    183
Name: C14orf132, dtype: int64

C14orf135
False    183
Name: C14orf135, dtype: int64

C14orf138
False    183
Name: C14orf138, dtype: int64

C14orf139
False    183
Name: C14orf139, dtype: int64

C14orf142
False    183
Name: C14orf142, dtype: int64

C14orf143
False    183
Name: C14orf143, dtype: int64

C14orf145
False    183
Name: C14orf145, dtype: int64

C14orf147
False    183
Name: C14orf147, dtype: int64

C14orf148
False    182
True       1
Name: C14orf148, dtype: int64

C14orf149
False    183
Name: C14orf149, dtype: int64

C14orf153
False    183
Name: C14orf153, dtype: int64

C14orf156
False    183
Name: C14orf156, dtype: int64

C14orf159
False    183
Name: C14orf159, dtype: int64

C14orf162
True     105
False     78
Name: C14orf162, dtype: int64

C14orf166B
False    112
True      71
Name: C14orf166B, dtype: int64

C14orf166
False    183
Name: C14orf166, dtype: int64

C14orf167
False    183
Name: C14orf167, dtype: int64

C14orf169
False    183
Name: C14orf169, dtype: int64

C14orf174
False    182
True       1
Name: C14orf174, dtype: int64

C14orf176
False    183
Name: C14orf176, dtype: int64

C14orf178
False    120
True      63
Name: C14orf178, dtype: int64

C14orf179
False    183
Name: C14orf179, dtype: int64

C14orf180
False    145
True      38
Name: C14orf180, dtype: int64

C14orf181
False    183
Name: C14orf181, dtype: int64

C14orf182
False    180
True       3
Name: C14orf182, dtype: int64

C14orf184
False    177
True       6
Name: C14orf184, dtype: int64

C14orf19
False    178
True       5
Name: C14orf19, dtype: int64

C14orf1
False    183
Name: C14orf1, dtype: int64

C14orf21
False    183
Name: C14orf21, dtype: int64

C14orf28
False    183
Name: C14orf28, dtype: int64

C14orf2
False    183
Name: C14orf2, dtype: int64

C14orf33
False    183
Name: C14orf33, dtype: int64

C14orf34
False    172
True      11
Name: C14orf34, dtype: int64

C14orf37
False    183
Name: C14orf37, dtype: int64

C14orf39
True     117
False     66
Name: C14orf39, dtype: int64

C14orf43
False    183
Name: C14orf43, dtype: int64

C14orf45
False    183
Name: C14orf45, dtype: int64

C14orf49
False    183
Name: C14orf49, dtype: int64

C14orf4
False    183
Name: C14orf4, dtype: int64

C14orf50
False    183
Name: C14orf50, dtype: int64

C14orf64
False    179
True       4
Name: C14orf64, dtype: int64

C14orf68
False    139
True      44
Name: C14orf68, dtype: int64

C14orf72
False    183
Name: C14orf72, dtype: int64

C14orf73
False    183
Name: C14orf73, dtype: int64

C14orf79
False    183
Name: C14orf79, dtype: int64

C14orf80
False    183
Name: C14orf80, dtype: int64

C14orf93
False    183
Name: C14orf93, dtype: int64

C15orf17
False    183
Name: C15orf17, dtype: int64

C15orf21
False    183
Name: C15orf21, dtype: int64

C15orf23
False    183
Name: C15orf23, dtype: int64

C15orf24
False    183
Name: C15orf24, dtype: int64

C15orf26
False    150
True      33
Name: C15orf26, dtype: int64

C15orf27
False    183
Name: C15orf27, dtype: int64

C15orf28
False    177
True       6
Name: C15orf28, dtype: int64

C15orf29
False    183
Name: C15orf29, dtype: int64

C15orf2
False    105
True      78
Name: C15orf2, dtype: int64

C15orf33
False    182
True       1
Name: C15orf33, dtype: int64

C15orf34
False    183
Name: C15orf34, dtype: int64

C15orf37
False    183
Name: C15orf37, dtype: int64

C15orf38
False    183
Name: C15orf38, dtype: int64

C15orf39
False    183
Name: C15orf39, dtype: int64

C15orf40
False    183
Name: C15orf40, dtype: int64

C15orf41
False    183
Name: C15orf41, dtype: int64

C15orf42
False    183
Name: C15orf42, dtype: int64

C15orf44
False    183
Name: C15orf44, dtype: int64

C15orf48
False    183
Name: C15orf48, dtype: int64

C15orf51
False    180
True       3
Name: C15orf51, dtype: int64

C15orf52
False    183
Name: C15orf52, dtype: int64

C15orf53
False    104
True      79
Name: C15orf53, dtype: int64

C15orf54
False    150
True      33
Name: C15orf54, dtype: int64

C15orf55
False    151
True      32
Name: C15orf55, dtype: int64

C15orf56
False    181
True       2
Name: C15orf56, dtype: int64

C15orf57
False    183
Name: C15orf57, dtype: int64

C15orf58
False    183
Name: C15orf58, dtype: int64

C15orf59
False    183
Name: C15orf59, dtype: int64

C15orf5
True     94
False    89
Name: C15orf5, dtype: int64

C15orf61
False    183
Name: C15orf61, dtype: int64

C15orf62
False    183
Name: C15orf62, dtype: int64

C15orf63
False    183
Name: C15orf63, dtype: int64

C16orf11
True     108
False     75
Name: C16orf11, dtype: int64

C16orf13
False    183
Name: C16orf13, dtype: int64

C16orf3
False    175
True       8
Name: C16orf3, dtype: int64

C16orf42
False    183
Name: C16orf42, dtype: int64

C16orf45
False    183
Name: C16orf45, dtype: int64

C16orf46
False    183
Name: C16orf46, dtype: int64

C16orf48
False    183
Name: C16orf48, dtype: int64

C16orf52
False    183
Name: C16orf52, dtype: int64

C16orf53
False    183
Name: C16orf53, dtype: int64

C16orf54
False    183
Name: C16orf54, dtype: int64

C16orf55
False    183
Name: C16orf55, dtype: int64

C16orf57
False    183
Name: C16orf57, dtype: int64

C16orf58
False    183
Name: C16orf58, dtype: int64

C16orf59
False    183
Name: C16orf59, dtype: int64

C16orf5
False    183
Name: C16orf5, dtype: int64

C16orf61
False    183
Name: C16orf61, dtype: int64

C16orf62
False    183
Name: C16orf62, dtype: int64

C16orf63
False    183
Name: C16orf63, dtype: int64

C16orf68
False    183
Name: C16orf68, dtype: int64

C16orf70
False    183
Name: C16orf70, dtype: int64

C16orf71
False    183
Name: C16orf71, dtype: int64

C16orf72
False    183
Name: C16orf72, dtype: int64

C16orf73
False    98
True     85
Name: C16orf73, dtype: int64

C16orf74
False    182
True       1
Name: C16orf74, dtype: int64

C16orf75
False    183
Name: C16orf75, dtype: int64

C16orf79
False    182
True       1
Name: C16orf79, dtype: int64

C16orf7
False    183
Name: C16orf7, dtype: int64

C16orf80
False    183
Name: C16orf80, dtype: int64

C16orf81
False    140
True      43
Name: C16orf81, dtype: int64

C16orf82
True     109
False     74
Name: C16orf82, dtype: int64

C16orf86
False    183
Name: C16orf86, dtype: int64

C16orf87
False    183
Name: C16orf87, dtype: int64

C16orf88
False    183
Name: C16orf88, dtype: int64

C16orf89
False    183
Name: C16orf89, dtype: int64

C16orf91
False    183
Name: C16orf91, dtype: int64

C16orf93
False    183
Name: C16orf93, dtype: int64

C17orf100
False    183
Name: C17orf100, dtype: int64

C17orf101
False    183
Name: C17orf101, dtype: int64

C17orf102
False    94
True     89
Name: C17orf102, dtype: int64

C17orf103
False    183
Name: C17orf103, dtype: int64

C17orf104
False    183
Name: C17orf104, dtype: int64

C17orf106

False    183
Name: C17orf106, dtype: int64

C17orf107
False    183
Name: C17orf107, dtype: int64

C17orf108
False    183
Name: C17orf108, dtype: int64

C17orf28
False    183
Name: C17orf28, dtype: int64

C17orf37
False    183
Name: C17orf37, dtype: int64

C17orf39
False    183
Name: C17orf39, dtype: int64

C17orf42
False    183
Name: C17orf42, dtype: int64

C17orf44
False    183
Name: C17orf44, dtype: int64

C17orf46
False    174
True       9
Name: C17orf46, dtype: int64

C17orf47
False    180
True       3
Name: C17orf47, dtype: int64

C17orf48
False    183
Name: C17orf48, dtype: int64

C17orf49
False    183
Name: C17orf49, dtype: int64

C17orf50
False    167
True      16
Name: C17orf50, dtype: int64

C17orf51
False    183
Name: C17orf51, dtype: int64

C17orf53
False    183
Name: C17orf53, dtype: int64

C17orf54
True     109
False     74
Name: C17orf54, dtype: int64

C17orf55
False    183
Name: C17orf55, dtype: int64

C17orf56
False    183
Name: C17orf56, dtype: int64

C17orf57
False    183
Name: C17orf57, dtype: int64

C17orf58
False    183
Name: C17orf58, dtype: int64

C17orf59
False    183
Name: C17orf59, dtype: int64

C17orf60
False    182
True       1
Name: C17orf60, dtype: int64

C17orf61
False    183
Name: C17orf61, dtype: int64

C17orf62
False    183
Name: C17orf62, dtype: int64

C17orf63
False    183
Name: C17orf63, dtype: int64

C17orf64
False    125
True      58
Name: C17orf64, dtype: int64

C17orf65
False    183
Name: C17orf65, dtype: int64

C17orf66
False    117
True      66
Name: C17orf66, dtype: int64

C17orf67
False    183
Name: C17orf67, dtype: int64

C17orf68
False    183
Name: C17orf68, dtype: int64

C17orf69
False    183
Name: C17orf69, dtype: int64

C17orf70
False    183
Name: C17orf70, dtype: int64

C17orf71
False    183
Name: C17orf71, dtype: int64

C17orf72
False    183
Name: C17orf72, dtype: int64

C17orf73
False    160
True      23
Name: C17orf73, dtype: int64

C17orf75
False    183
Name: C17orf75, dtype: int64

C17orf76
False    183
Name: C17orf76, dtype: int64

C17orf78
False    95
True     88
Name: C17orf78, dtype: int64

C17orf79
False    183
Name: C17orf79, dtype: int64

C17orf80
False    183
Name: C17orf80, dtype: int64

C17orf81
False    183
Name: C17orf81, dtype: int64

C17orf82
False    183
Name: C17orf82, dtype: int64

C17orf85
False    183
Name: C17orf85, dtype: int64

C17orf86
False    183
Name: C17orf86, dtype: int64

C17orf87
False    183
Name: C17orf87, dtype: int64

C17orf88
True     103
False     80
Name: C17orf88, dtype: int64

C17orf89
False    183
Name: C17orf89, dtype: int64

C17orf90
False    183
Name: C17orf90, dtype: int64

C17orf91
False    183
Name: C17orf91, dtype: int64

C17orf93
False    128
True      55
Name: C17orf93, dtype: int64

C17orf95
False    183
Name: C17orf95, dtype: int64

C17orf96
False    183
Name: C17orf96, dtype: int64

C17orf97
False    183
Name: C17orf97, dtype: int64

C17orf98
True     121
False     62
Name: C17orf98, dtype: int64

C17orf99
False    161
True      22
Name: C17orf99, dtype: int64

C18orf10
False    183
Name: C18orf10, dtype: int64

C18orf16
False    128
True      55
Name: C18orf16, dtype: int64

C18orf18
False    183
Name: C18orf18, dtype: int64

C18orf19
False    183
Name: C18orf19, dtype: int64

C18orf1
False    183
Name: C18orf1, dtype: int64

C18orf21
False    183
Name: C18orf21, dtype: int64

C18orf22
False    183
Name: C18orf22, dtype: int64

C18orf25
False    183
Name: C18orf25, dtype: int64

C18orf2
False    109
True      74
Name: C18orf2, dtype: int64

C18orf32
False    183
Name: C18orf32, dtype: int64

C18orf34
False    169
True      14
Name: C18orf34, dtype: int64

C18orf45
False    183
Name: C18orf45, dtype: int64

C18orf54
False    183
Name: C18orf54, dtype: int64

C18orf55
False    183
Name: C18orf55, dtype: int64

C18orf56
False    182
True       1
Name: C18orf56, dtype: int64

C18orf8
False    183
Name: C18orf8, dtype: int64

C19orf10
False    183
Name: C19orf10, dtype: int64

C19orf12
False    183
Name: C19orf12, dtype: int64

C19orf18
False    180
True       3
Name: C19orf18, dtype: int64

C19orf20
False    183
Name: C19orf20, dtype: int64

C19orf21
False    183
Name: C19orf21, dtype: int64

C19orf22
False    183
Name: C19orf22, dtype: int64

C19orf23
False    183
Name: C19orf23, dtype: int64

C19orf24
False    183
Name: C19orf24, dtype: int64

C19orf25
False    183
Name: C19orf25, dtype: int64

C19orf26
False    183
Name: C19orf26, dtype: int64

C19orf28
False    183
Name: C19orf28, dtype: int64

C19orf29
False    183
Name: C19orf29, dtype: int64

C19orf2
False    183
Name: C19orf2, dtype: int64

C19orf30
False    171
True      12
Name: C19orf30, dtype: int64

C19orf33
False    182
True       1
Name: C19orf33, dtype: int64

C19orf34
False    102
True      81
Name: C19orf34, dtype: int64

C19orf35
False    183
Name: C19orf35, dtype: int64

C19orf36
False    183
Name: C19orf36, dtype: int64

C19orf38
False    183
Name: C19orf38, dtype: int64

C19orf39
False    183
Name: C19orf39, dtype: int64

C19orf40
False    183
Name: C19orf40, dtype: int64

C19orf42
False    183
Name: C19orf42, dtype: int64

C19orf43
False    183
Name: C19orf43, dtype: int64

C19orf44
False    183
Name: C19orf44, dtype: int64

C19orf45
False    171
True      12
Name: C19orf45, dtype: int64

C19orf46
False    183
Name: C19orf46, dtype: int64

C19orf47
False    183
Name: C19orf47, dtype: int64

C19orf48
False    183
Name: C19orf48, dtype: int64

C19orf50
False    183
Name: C19orf50, dtype: int64

C19orf51
False    183
Name: C19orf51, dtype: int64

C19orf52
False    183
Name: C19orf52, dtype: int64

C19orf53
False    183
Name: C19orf53, dtype: int64

C19orf54
False    183
Name: C19orf54, dtype: int64

C19orf55
False    183
Name: C19orf55, dtype: int64

C19orf56
False    183
Name: C19orf56, dtype: int64

C19orf57
False    183
Name: C19orf57, dtype: int64

C19orf59
False    181
True       2
Name: C19orf59, dtype: int64

C19orf60
False    183
Name: C19orf60, dtype: int64

C19orf61
False    183
Name: C19orf61, dtype: int64

C19orf62
False    183
Name: C19orf62, dtype: int64

C19orf63
False    183
Name: C19orf63, dtype: int64

C19orf66
False    183
Name: C19orf66, dtype: int64

C19orf69
False    122
True      61
Name: C19orf69, dtype: int64

C19orf6
False    183
Name: C19orf6, dtype: int64

C19orf70
False    183
Name: C19orf70, dtype: int64

C19orf71
False    182
True       1
Name: C19orf71, dtype: int64

C19orf73
False    183
Name: C19orf73, dtype: int64

C19orf76
False    183
Name: C19orf76, dtype: int64

C19orf77
False    183
Name: C19orf77, dtype: int64

C1D
False    183
Name: C1D, dtype: int64

C1GALT1C1
False    183
Name: C1GALT1C1, dtype: int64

C1GALT1
False    183
Name: C1GALT1, dtype: int64

C1QA
False    183
Name: C1QA, dtype: int64

C1QBP
False    183
Name: C1QBP, dtype: int64

C1QB
False    183
Name: C1QB, dtype: int64

C1QC
False    183
Name: C1QC, dtype: int64

C1QL1
False    183
Name: C1QL1, dtype: int64

C1QL2
False    92
True     91
Name: C1QL2, dtype: int64

C1QL3
False    175
True       8
Name: C1QL3, dtype: int64

C1QL4
False    148
True      35
Name: C1QL4, dtype: int64

C1QTNF1
False    183
Name: C1QTNF1, dtype: int64

C1QTNF2
False    183
Name: C1QTNF2, dtype: int64

C1QTNF3
False    183
Name: C1QTNF3, dtype: int64

C1QTNF4
False    179
True       4
Name: C1QTNF4, dtype: int64

C1QTNF6
False    183
Name: C1QTNF6, dtype: int64

C1QTNF7
False    183
Name: C1QTNF7, dtype: int64

C1QTNF8
True     113
False     70
Name: C1QTNF8, dtype: int64

C1QTNF9B
False    169
True      14
Name: C1QTNF9B, dtype: int64

C1QTNF9
False    170
True      13
Name: C1QTNF9, dtype: int64

C1RL
False    183
Name: C1RL, dtype: int64

C1R
False    183
Name: C1R, dtype: int64

C1S
False    183
Name: C1S, dtype: int64

C1orf101
False    182
True       1
Name: C1orf101, dtype: int64

C1orf103
False    183
Name: C1orf103, dtype: int64

C1orf104
False    183
Name: C1orf104, dtype: int64

C1orf105
False    97
True     86
Name: C1orf105, dtype: int64

C1orf106
False    182
True       1
Name: C1orf106, dtype: int64

C1orf107
False    183
Name: C1orf107, dtype: int64

C1orf109
False    183
Name: C1orf109, dtype: int64

C1orf110
False    150
True      33
Name: C1orf110, dtype: int64

C1orf111
False    120
True      63
Name: C1orf111, dtype: int64

C1orf112
False    183
Name: C1orf112, dtype: int64

C1orf113
False    183
Name: C1orf113, dtype: int64

C1orf114
False    183
Name: C1orf114, dtype: int64

C1orf115
False    183
Name: C1orf115, dtype: int64

C1orf116
False    183
Name: C1orf116, dtype: int64

C1orf122
False    183
Name: C1orf122, dtype: int64

C1orf123
False    183
Name: C1orf123, dtype: int64

C1orf124
False    183
Name: C1orf124, dtype: int64

C1orf125
False    165
True      18
Name: C1orf125, dtype: int64

C1orf126
False    183
Name: C1orf126, dtype: int64

C1orf127
False    183
Name: C1orf127, dtype: int64

C1orf128
False    183
Name: C1orf128, dtype: int64

C1orf129
True     116
False     67
Name: C1orf129, dtype: int64

C1orf130
False    183
Name: C1orf130, dtype: int64

C1orf131
False    183
Name: C1orf131, dtype: int64

C1orf133
False    183
Name: C1orf133, dtype: int64

C1orf135
False    183
Name: C1orf135, dtype: int64

C1orf144
False    183
Name: C1orf144, dtype: int64

C1orf150
False    169
True      14
Name: C1orf150, dtype: int64

C1orf151
False    183
Name: C1orf151, dtype: int64

C1orf152

False    183
Name: C1orf152, dtype: int64

C1orf156
False    183
Name: C1orf156, dtype: int64

C1orf158
False    111
True      72
Name: C1orf158, dtype: int64

C1orf159
False    183
Name: C1orf159, dtype: int64

C1orf161
False    156
True      27
Name: C1orf161, dtype: int64

C1orf162
False    183
Name: C1orf162, dtype: int64

C1orf163
False    183
Name: C1orf163, dtype: int64

C1orf168
False    172
True      11
Name: C1orf168, dtype: int64

C1orf170
False    183
Name: C1orf170, dtype: int64

C1orf172
False    183
Name: C1orf172, dtype: int64

C1orf173
False    171
True      12
Name: C1orf173, dtype: int64

C1orf174
False    183
Name: C1orf174, dtype: int64

C1orf175
False    182
True       1
Name: C1orf175, dtype: int64

C1orf177
False    170
True      13
Name: C1orf177, dtype: int64

C1orf180
True     106
False     77
Name: C1orf180, dtype: int64

C1orf182
False    165
True      18
Name: C1orf182, dtype: int64

C1orf183
False    183
Name: C1orf183, dtype: int64

C1orf186
False    183
Name: C1orf186, dtype: int64

C1orf187
False    169
True      14
Name: C1orf187, dtype: int64

C1orf190
False    181
True       2
Name: C1orf190, dtype: int64

C1orf192
False    183
Name: C1orf192, dtype: int64

C1orf194
False    137
True      46
Name: C1orf194, dtype: int64

C1orf198
False    183
Name: C1orf198, dtype: int64

C1orf200
False    146
True      37
Name: C1orf200, dtype: int64

C1orf201
False    183
Name: C1orf201, dtype: int64

C1orf203
False    183
Name: C1orf203, dtype: int64

C1orf204
False    183
Name: C1orf204, dtype: int64

C1orf210
False    182
True       1
Name: C1orf210, dtype: int64

C1orf212
False    183
Name: C1orf212, dtype: int64

C1orf213
False    183
Name: C1orf213, dtype: int64

C1orf216
False    183
Name: C1orf216, dtype: int64

C1orf21
False    183
Name: C1orf21, dtype: int64

C1orf220
False    183
Name: C1orf220, dtype: int64

C1orf223
False    131
True      52
Name: C1orf223, dtype: int64

C1orf226
False    183
Name: C1orf226, dtype: int64

C1orf227
False    121
True      62
Name: C1orf227, dtype: int64

C1orf228
False    182
True       1
Name: C1orf228, dtype: int64

C1orf229
False    182
True       1
Name: C1orf229, dtype: int64

C1orf230
False    165
True      18
Name: C1orf230, dtype: int64

C1orf25
False    183
Name: C1orf25, dtype: int64

C1orf26
False    183
Name: C1orf26, dtype: int64

C1orf27
False    183
Name: C1orf27, dtype: int64

C1orf31
False    183
Name: C1orf31, dtype: int64

C1orf35
False    183
Name: C1orf35, dtype: int64

C1orf38
False    183
Name: C1orf38, dtype: int64

C1orf43
False    183
Name: C1orf43, dtype: int64

C1orf49
False    95
True     88
Name: C1orf49, dtype: int64

C1orf50
False    183
Name: C1orf50, dtype: int64

C1orf51
False    183
Name: C1orf51, dtype: int64

C1orf52
False    183
Name: C1orf52, dtype: int64

C1orf53
False    183
Name: C1orf53, dtype: int64

C1orf54
False    183
Name: C1orf54, dtype: int64

C1orf55
False    183
Name: C1orf55, dtype: int64

C1orf56
False    183
Name: C1orf56, dtype: int64

C1orf57
False    183
Name: C1orf57, dtype: int64

C1orf58
False    183
Name: C1orf58, dtype: int64

C1orf59
False    183
Name: C1orf59, dtype: int64

C1orf61
False    151
True      32
Name: C1orf61, dtype: int64

C1orf63
False    183
Name: C1orf63, dtype: int64

C1orf64
True     125
False     58
Name: C1orf64, dtype: int64

C1orf65
False    114
True      69
Name: C1orf65, dtype: int64

C1orf66
False    183
Name: C1orf66, dtype: int64

C1orf69
False    183
Name: C1orf69, dtype: int64

C1orf70
False    183
Name: C1orf70, dtype: int64

C1orf74
False    183
Name: C1orf74, dtype: int64

C1orf77
False    183
Name: C1orf77, dtype: int64

C1orf83
False    183
Name: C1orf83, dtype: int64

C1orf84
False    183
Name: C1orf84, dtype: int64

C1orf85
False    183
Name: C1orf85, dtype: int64

C1orf86
False    183
Name: C1orf86, dtype: int64

C1orf87
True     121
False     62
Name: C1orf87, dtype: int64

C1orf88
False    183
Name: C1orf88, dtype: int64

C1orf89
False    183
Name: C1orf89, dtype: int64

C1orf91
False    183
Name: C1orf91, dtype: int64

C1orf92
False    121
True      62
Name: C1orf92, dtype: int64

C1orf93
False    183
Name: C1orf93, dtype: int64

C1orf94
False    133
True      50
Name: C1orf94, dtype: int64

C1orf95
False    181
True       2
Name: C1orf95, dtype: int64

C1orf96
False    183
Name: C1orf96, dtype: int64

C1orf97
False    183
Name: C1orf97, dtype: int64

C1orf9
False    183
Name: C1orf9, dtype: int64

C20orf103
False    183
Name: C20orf103, dtype: int64

C20orf106
False    141
True      42
Name: C20orf106, dtype: int64

C20orf107
False    177
True       6
Name: C20orf107, dtype: int64

C20orf108
False    183
Name: C20orf108, dtype: int64

C20orf111
False    183
Name: C20orf111, dtype: int64

C20orf112
False    183
Name: C20orf112, dtype: int64

C20orf114
False    169
True      14
Name: C20orf114, dtype: int64

C20orf117
False    183
Name: C20orf117, dtype: int64

C20orf118
False    183
Name: C20orf118, dtype: int64

C20orf11
False    183
Name: C20orf11, dtype: int64

C20orf123
True     124
False     59
Name: C20orf123, dtype: int64

C20orf12
False    183
Name: C20orf12, dtype: int64

C20orf132
False    183
Name: C20orf132, dtype: int64

C20orf134
False    183
Name: C20orf134, dtype: int64

C20orf135
False    183
Name: C20orf135, dtype: int64

C20orf141
True     101
False     82
Name: C20orf141, dtype: int64

C20orf144
True     114
False     69
Name: C20orf144, dtype: int64

C20orf151
False    181
True       2
Name: C20orf151, dtype: int64

C20orf152
False    149
True      34
Name: C20orf152, dtype: int64

C20orf160
False    183
Name: C20orf160, dtype: int64

C20orf165
False    182
True       1
Name: C20orf165, dtype: int64

C20orf177
False    183
Name: C20orf177, dtype: int64

C20orf186
True     115
False     68
Name: C20orf186, dtype: int64

C20orf194
False    183
Name: C20orf194, dtype: int64

C20orf195
False    183
Name: C20orf195, dtype: int64

C20orf196
False    183
Name: C20orf196, dtype: int64

C20orf197
False    174
True       9
Name: C20orf197, dtype: int64

C20orf199
False    183
Name: C20orf199, dtype: int64

C20orf200
False    167
True      16
Name: C20orf200, dtype: int64

C20orf201
False    106
True      77
Name: C20orf201, dtype: int64

C20orf202
False    183
Name: C20orf202, dtype: int64

C20orf203
False    173
True      10
Name: C20orf203, dtype: int64

C20orf20
False    183
Name: C20orf20, dtype: int64

C20orf24
False    183
Name: C20orf24, dtype: int64

C20orf26
False    175
True       8
Name: C20orf26, dtype: int64

C20orf27
False    183
Name: C20orf27, dtype: int64

C20orf29
False    183
Name: C20orf29, dtype: int64

C20orf30
False    183
Name: C20orf30, dtype: int64

C20orf3
False    183
Name: C20orf3, dtype: int64

C20orf43
False    183
Name: C20orf43, dtype: int64

C20orf46
False    183
Name: C20orf46, dtype: int64

C20orf4
False    183
Name: C20orf4, dtype: int64

C20orf54
False    183
Name: C20orf54, dtype: int64

C20orf56
False    181
True       2
Name: C20orf56, dtype: int64

C20orf70
True     118
False     65
Name: C20orf70, dtype: int64

C20orf72
False    183
Name: C20orf72, dtype: int64

C20orf7
False    183
Name: C20orf7, dtype: int64

C20orf85
False    112
True      71
Name: C20orf85, dtype: int64

C20orf94
False    183
Name: C20orf94, dtype: int64

C20orf96
False    183
Name: C20orf96, dtype: int64

C21orf119
False    183
Name: C21orf119, dtype: int64

C21orf121
False    96
True     87
Name: C21orf121, dtype: int64

C21orf122
False    183
Name: C21orf122, dtype: int64

C21orf125
False    180
True       3
Name: C21orf125, dtype: int64

C21orf128
False    95
True     88
Name: C21orf128, dtype: int64

C21orf129
False    168
True      15
Name: C21orf129, dtype: int64

C21orf130
False    178
True       5
Name: C21orf130, dtype: int64

C21orf15
False    172
True      11
Name: C21orf15, dtype: int64

C21orf29
False    172
True      11
Name: C21orf29, dtype: int64

C21orf2
False    183
Name: C21orf2, dtype: int64

C21orf33
False    183
Name: C21orf33, dtype: int64

C21orf34
False    183
Name: C21orf34, dtype: int64

C21orf45
False    183
Name: C21orf45, dtype: int64

C21orf49
False    183
Name: C21orf49, dtype: int64

C21orf56
False    183
Name: C21orf56, dtype: int64

C21orf57
False    183
Name: C21orf57, dtype: int64

C21orf58
False    183
Name: C21orf58, dtype: int64

C21orf59
False    183
Name: C21orf59, dtype: int64

C21orf62
False    180
True       3
Name: C21orf62, dtype: int64

C21orf63
False    183
Name: C21orf63, dtype: int64

C21orf67
False    183
Name: C21orf67, dtype: int64

C21orf70
False    183
Name: C21orf70, dtype: int64

C21orf71
False    148
True      35
Name: C21orf71, dtype: int64

C21orf7
False    183
Name: C21orf7, dtype: int64

C21orf81
False    148
True      35
Name: C21orf81, dtype: int64

C21orf82
False    182
True       1
Name: C21orf82, dtype: int64

C21orf84
False    143
True      40
Name: C21orf84, dtype: int64

C21orf88
False    181
True       2
Name: C21orf88, dtype: int64

C21orf90
False    152
True      31
Name: C21orf90, dtype: int64

C21orf91
False    183
Name: C21orf91, dtype: int64

C21orf96
False    141
True      42
Name: C21orf96, dtype: int64

C22orf13
False    183
Name: C22orf13, dtype: int64

C22orf15
False    171
True      12
Name: C22orf15, dtype: int64

C22orf23
False    183
Name: C22orf23, dtype: int64

C22orf24
False    156
True      27
Name: C22orf24, dtype: int64

C22orf25
False    183
Name: C22orf25, dtype: int64

C22orf26
False    183
Name: C22orf26, dtype: int64

C22orf27

False    183
Name: C22orf27, dtype: int64

C22orf28
False    183
Name: C22orf28, dtype: int64

C22orf29
False    183
Name: C22orf29, dtype: int64

C22orf30
False    183
Name: C22orf30, dtype: int64

C22orf31
False    128
True      55
Name: C22orf31, dtype: int64

C22orf32
False    183
Name: C22orf32, dtype: int64

C22orf34
False    162
True      21
Name: C22orf34, dtype: int64

C22orf36
False    183
Name: C22orf36, dtype: int64

C22orf39
False    183
Name: C22orf39, dtype: int64

C22orf40
False    183
Name: C22orf40, dtype: int64

C22orf41
False    177
True       6
Name: C22orf41, dtype: int64

C22orf42
False    122
True      61
Name: C22orf42, dtype: int64

C22orf43
False    149
True      34
Name: C22orf43, dtype: int64

C22orf45
False    175
True       8
Name: C22orf45, dtype: int64

C22orf46
False    183
Name: C22orf46, dtype: int64

C22orf9
False    183
Name: C22orf9, dtype: int64

C2CD2L
False    183
Name: C2CD2L, dtype: int64

C2CD2
False    183
Name: C2CD2, dtype: int64

C2CD3
False    183
Name: C2CD3, dtype: int64

C2CD4A
False    183
Name: C2CD4A, dtype: int64

C2CD4B
False    183
Name: C2CD4B, dtype: int64

C2CD4C
False    183
Name: C2CD4C, dtype: int64

C2CD4D
False    182
True       1
Name: C2CD4D, dtype: int64

C2orf15
False    183
Name: C2orf15, dtype: int64

C2orf16
False    183
Name: C2orf16, dtype: int64

C2orf18
False    183
Name: C2orf18, dtype: int64

C2orf24
False    183
Name: C2orf24, dtype: int64

C2orf27A
False    183
Name: C2orf27A, dtype: int64

C2orf28
False    183
Name: C2orf28, dtype: int64

C2orf29
False    183
Name: C2orf29, dtype: int64

C2orf34
False    183
Name: C2orf34, dtype: int64

C2orf39
False    171
True      12
Name: C2orf39, dtype: int64

C2orf3
False    183
Name: C2orf3, dtype: int64

C2orf40
False    179
True       4
Name: C2orf40, dtype: int64

C2orf42
False    183
Name: C2orf42, dtype: int64

C2orf43
False    183
Name: C2orf43, dtype: int64

C2orf44
False    183
Name: C2orf44, dtype: int64

C2orf47
False    183
Name: C2orf47, dtype: int64

C2orf48
False    170
True      13
Name: C2orf48, dtype: int64

C2orf49
False    183
Name: C2orf49, dtype: int64

C2orf50
False    181
True       2
Name: C2orf50, dtype: int64

C2orf52
False    178
True       5
Name: C2orf52, dtype: int64

C2orf54
False    183
Name: C2orf54, dtype: int64

C2orf55
False    183
Name: C2orf55, dtype: int64

C2orf56
False    183
Name: C2orf56, dtype: int64

C2orf58
False    183
Name: C2orf58, dtype: int64

C2orf60
False    183
Name: C2orf60, dtype: int64

C2orf61
False    153
True      30
Name: C2orf61, dtype: int64

C2orf62
False    178
True       5
Name: C2orf62, dtype: int64

C2orf63
False    183
Name: C2orf63, dtype: int64

C2orf64
False    183
Name: C2orf64, dtype: int64

C2orf65
False    182
True       1
Name: C2orf65, dtype: int64

C2orf66
False    134
True      49
Name: C2orf66, dtype: int64

C2orf67
False    183
Name: C2orf67, dtype: int64

C2orf68
False    183
Name: C2orf68, dtype: int64

C2orf69
False    183
Name: C2orf69, dtype: int64

C2orf70
False    181
True       2
Name: C2orf70, dtype: int64

C2orf71
False    131
True      52
Name: C2orf71, dtype: int64

C2orf72
False    182
True       1
Name: C2orf72, dtype: int64

C2orf73
False    165
True      18
Name: C2orf73, dtype: int64

C2orf74
False    183
Name: C2orf74, dtype: int64

C2orf76
False    183
Name: C2orf76, dtype: int64

C2orf77
False    183
Name: C2orf77, dtype: int64

C2orf79
False    183
Name: C2orf79, dtype: int64

C2orf7
False    183
Name: C2orf7, dtype: int64

C2orf80
True     128
False     55
Name: C2orf80, dtype: int64

C2orf81
False    183
Name: C2orf81, dtype: int64

C2orf82
False    158
True      25
Name: C2orf82, dtype: int64

C2orf84
False    180
True       3
Name: C2orf84, dtype: int64

C2orf85
False    137
True      46
Name: C2orf85, dtype: int64

C2orf86
False    183
Name: C2orf86, dtype: int64

C2orf88
False    183
Name: C2orf88, dtype: int64

C2orf89
False    183
Name: C2orf89, dtype: int64

C2
False    183
Name: C2, dtype: int64

C3AR1
False    183
Name: C3AR1, dtype: int64

C3P1
True     127
False     56
Name: C3P1, dtype: int64

C3orf10
False    183
Name: C3orf10, dtype: int64

C3orf14
False    183
Name: C3orf14, dtype: int64

C3orf15
False    183
Name: C3orf15, dtype: int64

C3orf17
False    183
Name: C3orf17, dtype: int64

C3orf18
False    183
Name: C3orf18, dtype: int64

C3orf19
False    183
Name: C3orf19, dtype: int64

C3orf1
False    183
Name: C3orf1, dtype: int64

C3orf20
True     99
False    84
Name: C3orf20, dtype: int64

C3orf21
False    183
Name: C3orf21, dtype: int64

C3orf23
False    183
Name: C3orf23, dtype: int64

C3orf24
True     101
False     82
Name: C3orf24, dtype: int64

C3orf26
False    183
Name: C3orf26, dtype: int64

C3orf30
True     119
False     64
Name: C3orf30, dtype: int64

C3orf31
False    183
Name: C3orf31, dtype: int64

C3orf32
False    182
True       1
Name: C3orf32, dtype: int64

C3orf33
False    183
Name: C3orf33, dtype: int64

C3orf34
False    183
Name: C3orf34, dtype: int64

C3orf35
False    183
Name: C3orf35, dtype: int64

C3orf36
False    183
Name: C3orf36, dtype: int64

C3orf37
False    183
Name: C3orf37, dtype: int64

C3orf38
False    183
Name: C3orf38, dtype: int64

C3orf39
False    183
Name: C3orf39, dtype: int64

C3orf42
False    183
Name: C3orf42, dtype: int64

C3orf43
True     102
False     81
Name: C3orf43, dtype: int64

C3orf45
False    160
True      23
Name: C3orf45, dtype: int64

C3orf47
False    183
Name: C3orf47, dtype: int64

C3orf48
False    111
True      72
Name: C3orf48, dtype: int64

C3orf49
False    92
True     91
Name: C3orf49, dtype: int64

C3orf50
False    105
True      78
Name: C3orf50, dtype: int64

C3orf52
False    183
Name: C3orf52, dtype: int64

C3orf54
False    183
Name: C3orf54, dtype: int64

C3orf55
False    177
True       6
Name: C3orf55, dtype: int64

C3orf57
False    183
Name: C3orf57, dtype: int64

C3orf58
False    183
Name: C3orf58, dtype: int64

C3orf59
False    183
Name: C3orf59, dtype: int64

C3orf62
False    183
Name: C3orf62, dtype: int64

C3orf63
False    183
Name: C3orf63, dtype: int64

C3orf64
False    183
Name: C3orf64, dtype: int64

C3orf65
False    104
True      79
Name: C3orf65, dtype: int64

C3orf67
False    183
Name: C3orf67, dtype: int64

C3orf70
False    183
Name: C3orf70, dtype: int64

C3orf71
False    183
Name: C3orf71, dtype: int64

C3orf72
False    106
True      77
Name: C3orf72, dtype: int64

C3orf75
False    183
Name: C3orf75, dtype: int64

C3
False    183
Name: C3, dtype: int64

C4A
False    183
Name: C4A, dtype: int64

C4BPA
False    182
True       1
Name: C4BPA, dtype: int64

C4BPB
False    182
True       1
Name: C4BPB, dtype: int64

C4orf10
False    183
Name: C4orf10, dtype: int64

C4orf12
False    183
Name: C4orf12, dtype: int64

C4orf14
False    183
Name: C4orf14, dtype: int64

C4orf19
False    183
Name: C4orf19, dtype: int64

C4orf21
False    183
Name: C4orf21, dtype: int64

C4orf23
False    183
Name: C4orf23, dtype: int64

C4orf26
False    126
True      57
Name: C4orf26, dtype: int64

C4orf27
False    183
Name: C4orf27, dtype: int64

C4orf29
False    183
Name: C4orf29, dtype: int64

C4orf31
False    182
True       1
Name: C4orf31, dtype: int64

C4orf32
False    183
Name: C4orf32, dtype: int64

C4orf33
False    183
Name: C4orf33, dtype: int64

C4orf34
False    183
Name: C4orf34, dtype: int64

C4orf36
False    178
True       5
Name: C4orf36, dtype: int64

C4orf37
False    139
True      44
Name: C4orf37, dtype: int64

C4orf38
False    182
True       1
Name: C4orf38, dtype: int64

C4orf39
False    181
True       2
Name: C4orf39, dtype: int64

C4orf3
False    183
Name: C4orf3, dtype: int64

C4orf41
False    183
Name: C4orf41, dtype: int64

C4orf42
False    183
Name: C4orf42, dtype: int64

C4orf43
False    183
Name: C4orf43, dtype: int64

C4orf44
False    180
True       3
Name: C4orf44, dtype: int64

C4orf46
False    183
Name: C4orf46, dtype: int64

C4orf47
False    179
True       4
Name: C4orf47, dtype: int64

C4orf48
False    180
True       3
Name: C4orf48, dtype: int64

C4orf49
False    179
True       4
Name: C4orf49, dtype: int64

C4orf50
False    109
True      74
Name: C4orf50, dtype: int64

C4orf52
False    183
Name: C4orf52, dtype: int64

C4orf6
False    104
True      79
Name: C4orf6, dtype: int64

C4orf7
False    173
True      10
Name: C4orf7, dtype: int64

C5AR1
False    183
Name: C5AR1, dtype: int64

C5orf13
False    183
Name: C5orf13, dtype: int64

C5orf15
False    183
Name: C5orf15, dtype: int64

C5orf20
False    171
True      12
Name: C5orf20, dtype: int64

C5orf22
False    183
Name: C5orf22, dtype: int64

C5orf23
False    183
Name: C5orf23, dtype: int64

C5orf24
False    183
Name: C5orf24, dtype: int64

C5orf25
False    183
Name: C5orf25, dtype: int64

C5orf27
False    181
True       2
Name: C5orf27, dtype: int64

C5orf28
False    183
Name: C5orf28, dtype: int64

C5orf30
False    183
Name: C5orf30, dtype: int64

C5orf32
False    183
Name: C5orf32, dtype: int64

C5orf33
False    183
Name: C5orf33, dtype: int64

C5orf34
False    183
Name: C5orf34, dtype: int64

C5orf35
False    183
Name: C5orf35, dtype: int64

C5orf36
False    183
Name: C5orf36, dtype: int64

C5orf38
False    164
True      19
Name: C5orf38, dtype: int64

C5orf39
False    183
Name: C5orf39, dtype: int64

C5orf40
False    134
True      49
Name: C5orf40, dtype: int64

C5orf41

False    183
Name: C5orf41, dtype: int64

C5orf42
False    183
Name: C5orf42, dtype: int64

C5orf43
False    183
Name: C5orf43, dtype: int64

C5orf44
False    183
Name: C5orf44, dtype: int64

C5orf45
False    183
Name: C5orf45, dtype: int64

C5orf46
False    177
True       6
Name: C5orf46, dtype: int64

C5orf47
True     100
False     83
Name: C5orf47, dtype: int64

C5orf49
False    182
True       1
Name: C5orf49, dtype: int64

C5orf4
False    183
Name: C5orf4, dtype: int64

C5orf51
False    183
Name: C5orf51, dtype: int64

C5orf52
True     127
False     56
Name: C5orf52, dtype: int64

C5orf53
False    183
Name: C5orf53, dtype: int64

C5orf54
False    183
Name: C5orf54, dtype: int64

C5orf55
False    183
Name: C5orf55, dtype: int64

C5orf56
False    183
Name: C5orf56, dtype: int64

C5orf58
False    174
True       9
Name: C5orf58, dtype: int64

C5orf62
False    183
Name: C5orf62, dtype: int64

C5
False    183
Name: C5, dtype: int64

C6orf103
True     113
False     70
Name: C6orf103, dtype: int64

C6orf105
False    182
True       1
Name: C6orf105, dtype: int64

C6orf106
False    183
Name: C6orf106, dtype: int64

C6orf108
False    183
Name: C6orf108, dtype: int64

C6orf114
False    182
True       1
Name: C6orf114, dtype: int64

C6orf115
False    183
Name: C6orf115, dtype: int64

C6orf118
True     103
False     80
Name: C6orf118, dtype: int64

C6orf120
False    183
Name: C6orf120, dtype: int64

C6orf122
False    183
Name: C6orf122, dtype: int64

C6orf123
False    175
True       8
Name: C6orf123, dtype: int64

C6orf124
False    183
Name: C6orf124, dtype: int64

C6orf125
False    183
Name: C6orf125, dtype: int64

C6orf126
True     92
False    91
Name: C6orf126, dtype: int64

C6orf127
False    97
True     86
Name: C6orf127, dtype: int64

C6orf129
False    183
Name: C6orf129, dtype: int64

C6orf130
False    183
Name: C6orf130, dtype: int64

C6orf132
False    182
True       1
Name: C6orf132, dtype: int64

C6orf134
False    183
Name: C6orf134, dtype: int64

C6orf136
False    183
Name: C6orf136, dtype: int64

C6orf138
False    182
True       1
Name: C6orf138, dtype: int64

C6orf141
False    182
True       1
Name: C6orf141, dtype: int64

C6orf142
False    173
True      10
Name: C6orf142, dtype: int64

C6orf145
False    183
Name: C6orf145, dtype: int64

C6orf146
False    109
True      74
Name: C6orf146, dtype: int64

C6orf147
False    180
True       3
Name: C6orf147, dtype: int64

C6orf150
False    183
Name: C6orf150, dtype: int64

C6orf153
False    183
Name: C6orf153, dtype: int64

C6orf154
False    183
Name: C6orf154, dtype: int64

C6orf155
False    182
True       1
Name: C6orf155, dtype: int64

C6orf15
False    160
True      23
Name: C6orf15, dtype: int64

C6orf162
False    183
Name: C6orf162, dtype: int64

C6orf163
False    180
True       3
Name: C6orf163, dtype: int64

C6orf164
False    182
True       1
Name: C6orf164, dtype: int64

C6orf165
False    183
Name: C6orf165, dtype: int64

C6orf167
False    183
Name: C6orf167, dtype: int64

C6orf168
False    183
Name: C6orf168, dtype: int64

C6orf170
False    183
Name: C6orf170, dtype: int64

C6orf174
False    183
Name: C6orf174, dtype: int64

C6orf176
False    178
True       5
Name: C6orf176, dtype: int64

C6orf182
False    183
Name: C6orf182, dtype: int64

C6orf186
False    181
True       2
Name: C6orf186, dtype: int64

C6orf192
False    183
Name: C6orf192, dtype: int64

C6orf195
False    136
True      47
Name: C6orf195, dtype: int64

C6orf1
False    183
Name: C6orf1, dtype: int64

C6orf201
False    182
True       1
Name: C6orf201, dtype: int64

C6orf203
False    183
Name: C6orf203, dtype: int64

C6orf204
False    183
Name: C6orf204, dtype: int64

C6orf208
False    176
True       7
Name: C6orf208, dtype: int64

C6orf211
False    183
Name: C6orf211, dtype: int64

C6orf217
False    177
True       6
Name: C6orf217, dtype: int64

C6orf218
False    134
True      49
Name: C6orf218, dtype: int64

C6orf222
False    180
True       3
Name: C6orf222, dtype: int64

C6orf223
False    181
True       2
Name: C6orf223, dtype: int64

C6orf225
False    183
Name: C6orf225, dtype: int64

C6orf226
False    183
Name: C6orf226, dtype: int64

C6orf227
False    166
True      17
Name: C6orf227, dtype: int64

C6orf25
True     100
False     83
Name: C6orf25, dtype: int64

C6orf26
False    183
Name: C6orf26, dtype: int64

C6orf27
False    182
True       1
Name: C6orf27, dtype: int64

C6orf35
False    183
Name: C6orf35, dtype: int64

C6orf41
False    183
Name: C6orf41, dtype: int64

C6orf47
False    183
Name: C6orf47, dtype: int64

C6orf48
False    183
Name: C6orf48, dtype: int64

C6orf52
False    181
True       2
Name: C6orf52, dtype: int64

C6orf57
False    183
Name: C6orf57, dtype: int64

C6orf58
False    135
True      48
Name: C6orf58, dtype: int64

C6orf59
False    178
True       5
Name: C6orf59, dtype: int64

C6orf62
False    183
Name: C6orf62, dtype: int64

C6orf64
False    183
Name: C6orf64, dtype: int64

C6orf70
False    183
Name: C6orf70, dtype: int64

C6orf72
False    183
Name: C6orf72, dtype: int64

C6orf81
False    179
True       4
Name: C6orf81, dtype: int64

C6orf89
False    183
Name: C6orf89, dtype: int64

C6orf97
False    183
Name: C6orf97, dtype: int64

C6
False    183
Name: C6, dtype: int64

C7orf10
False    183
Name: C7orf10, dtype: int64

C7orf11
False    183
Name: C7orf11, dtype: int64

C7orf13
False    183
Name: C7orf13, dtype: int64

C7orf16
True     107
False     76
Name: C7orf16, dtype: int64

C7orf23
False    183
Name: C7orf23, dtype: int64

C7orf25
False    183
Name: C7orf25, dtype: int64

C7orf26
False    183
Name: C7orf26, dtype: int64

C7orf27
False    183
Name: C7orf27, dtype: int64

C7orf28A
False    183
Name: C7orf28A, dtype: int64

C7orf28B
False    183
Name: C7orf28B, dtype: int64

C7orf29
False    183
Name: C7orf29, dtype: int64

C7orf30
False    183
Name: C7orf30, dtype: int64

C7orf31
False    183
Name: C7orf31, dtype: int64

C7orf34
True     112
False     71
Name: C7orf34, dtype: int64

C7orf36
False    183
Name: C7orf36, dtype: int64

C7orf40
False    183
Name: C7orf40, dtype: int64

C7orf41
False    183
Name: C7orf41, dtype: int64

C7orf42
False    183
Name: C7orf42, dtype: int64

C7orf43
False    183
Name: C7orf43, dtype: int64

C7orf44
False    183
Name: C7orf44, dtype: int64

C7orf46
False    183
Name: C7orf46, dtype: int64

C7orf47
False    183
Name: C7orf47, dtype: int64

C7orf49
False    183
Name: C7orf49, dtype: int64

C7orf4
False    120
True      63
Name: C7orf4, dtype: int64

C7orf50
False    183
Name: C7orf50, dtype: int64

C7orf51
False    183
Name: C7orf51, dtype: int64

C7orf52
False    166
True      17
Name: C7orf52, dtype: int64

C7orf53
False    183
Name: C7orf53, dtype: int64

C7orf54
False    157
True      26
Name: C7orf54, dtype: int64

C7orf55
False    183
Name: C7orf55, dtype: int64

C7orf57
False    167
True      16
Name: C7orf57, dtype: int64

C7orf58
False    183
Name: C7orf58, dtype: int64

C7orf59
False    183
Name: C7orf59, dtype: int64

C7orf60
False    183
Name: C7orf60, dtype: int64

C7orf61
False    183
Name: C7orf61, dtype: int64

C7orf63
False    183
Name: C7orf63, dtype: int64

C7orf64
False    183
Name: C7orf64, dtype: int64

C7orf65
True     111
False     72
Name: C7orf65, dtype: int64

C7orf68
False    183
Name: C7orf68, dtype: int64

C7orf69
False    114
True      69
Name: C7orf69, dtype: int64

C7orf70
False    183
Name: C7orf70, dtype: int64

C7orf71
True     92
False    91
Name: C7orf71, dtype: int64

C7
False    183
Name: C7, dtype: int64

C8A
False    146
True      37
Name: C8A, dtype: int64

C8B
False    163
True      20
Name: C8B, dtype: int64

C8G
False    180
True       3
Name: C8G, dtype: int64

C8ORFK29
False    181
True       2
Name: C8ORFK29, dtype: int64

C8orf12
True     109
False     74
Name: C8orf12, dtype: int64

C8orf30A
False    183
Name: C8orf30A, dtype: int64

C8orf31
False    182
True       1
Name: C8orf31, dtype: int64

C8orf33
False    183
Name: C8orf33, dtype: int64

C8orf34
False    182
True       1
Name: C8orf34, dtype: int64

C8orf37
False    183
Name: C8orf37, dtype: int64

C8orf38
False    183
Name: C8orf38, dtype: int64

C8orf39
False    183
Name: C8orf39, dtype: int64

C8orf40
False    183
Name: C8orf40, dtype: int64

C8orf41
False    183
Name: C8orf41, dtype: int64

C8orf42
False    183
Name: C8orf42, dtype: int64

C8orf44
False    183
Name: C8orf44, dtype: int64

C8orf45
False    183
Name: C8orf45, dtype: int64

C8orf46
False    182
True       1
Name: C8orf46, dtype: int64

C8orf47
False    182
True       1
Name: C8orf47, dtype: int64

C8orf48
False    183
Name: C8orf48, dtype: int64

C8orf4
False    183
Name: C8orf4, dtype: int64

C8orf51
False    183
Name: C8orf51, dtype: int64

C8orf55
False    183
Name: C8orf55, dtype: int64

C8orf56

False    138
True      45
Name: C8orf56, dtype: int64

C8orf58
False    183
Name: C8orf58, dtype: int64

C8orf59
False    183
Name: C8orf59, dtype: int64

C8orf73
False    183
Name: C8orf73, dtype: int64

C8orf74
True     98
False    85
Name: C8orf74, dtype: int64

C8orf75
False    157
True      26
Name: C8orf75, dtype: int64

C8orf76
False    183
Name: C8orf76, dtype: int64

C8orf77
False    183
Name: C8orf77, dtype: int64

C8orf79
False    183
Name: C8orf79, dtype: int64

C8orf80
False    181
True       2
Name: C8orf80, dtype: int64

C8orf83
False    183
Name: C8orf83, dtype: int64

C8orf84
False    183
Name: C8orf84, dtype: int64

C8orf85
False    182
True       1
Name: C8orf85, dtype: int64

C9orf100
False    183
Name: C9orf100, dtype: int64

C9orf102
False    183
Name: C9orf102, dtype: int64

C9orf103
False    183
Name: C9orf103, dtype: int64

C9orf106
False    132
True      51
Name: C9orf106, dtype: int64

C9orf109
False    183
Name: C9orf109, dtype: int64

C9orf110
False    182
True       1
Name: C9orf110, dtype: int64

C9orf114
False    183
Name: C9orf114, dtype: int64

C9orf116
False    183
Name: C9orf116, dtype: int64

C9orf117
False    183
Name: C9orf117, dtype: int64

C9orf119
False    183
Name: C9orf119, dtype: int64

C9orf11
False    121
True      62
Name: C9orf11, dtype: int64

C9orf122
False    183
Name: C9orf122, dtype: int64

C9orf123
False    183
Name: C9orf123, dtype: int64

C9orf125
False    183
Name: C9orf125, dtype: int64

C9orf128
False    147
True      36
Name: C9orf128, dtype: int64

C9orf129
False    183
Name: C9orf129, dtype: int64

C9orf130
False    183
Name: C9orf130, dtype: int64

C9orf131
False    164
True      19
Name: C9orf131, dtype: int64

C9orf135
False    148
True      35
Name: C9orf135, dtype: int64

C9orf139
False    179
True       4
Name: C9orf139, dtype: int64

C9orf140
False    183
Name: C9orf140, dtype: int64

C9orf142
False    183
Name: C9orf142, dtype: int64

C9orf144B
False    102
True      81
Name: C9orf144B, dtype: int64

C9orf150
False    183
Name: C9orf150, dtype: int64

C9orf152
False    182
True       1
Name: C9orf152, dtype: int64

C9orf153
False    146
True      37
Name: C9orf153, dtype: int64

C9orf156
False    183
Name: C9orf156, dtype: int64

C9orf163
False    182
True       1
Name: C9orf163, dtype: int64

C9orf167
False    183
Name: C9orf167, dtype: int64

C9orf169
False    178
True       5
Name: C9orf169, dtype: int64

C9orf16
False    183
Name: C9orf16, dtype: int64

C9orf170
False    160
True      23
Name: C9orf170, dtype: int64

C9orf171
False    133
True      50
Name: C9orf171, dtype: int64

C9orf172
False    182
True       1
Name: C9orf172, dtype: int64

C9orf173
False    154
True      29
Name: C9orf173, dtype: int64

C9orf21
False    183
Name: C9orf21, dtype: int64

C9orf23
False    183
Name: C9orf23, dtype: int64

C9orf24
False    183
Name: C9orf24, dtype: int64

C9orf25
False    183
Name: C9orf25, dtype: int64

C9orf30
False    183
Name: C9orf30, dtype: int64

C9orf37
False    183
Name: C9orf37, dtype: int64

C9orf3
False    183
Name: C9orf3, dtype: int64

C9orf40
False    183
Name: C9orf40, dtype: int64

C9orf41
False    183
Name: C9orf41, dtype: int64

C9orf43
False    183
Name: C9orf43, dtype: int64

C9orf44
False    171
True      12
Name: C9orf44, dtype: int64

C9orf45
False    183
Name: C9orf45, dtype: int64

C9orf46
False    183
Name: C9orf46, dtype: int64

C9orf47
False    179
True       4
Name: C9orf47, dtype: int64

C9orf4
False    141
True      42
Name: C9orf4, dtype: int64

C9orf50
False    170
True      13
Name: C9orf50, dtype: int64

C9orf53
True     94
False    89
Name: C9orf53, dtype: int64

C9orf57
True     120
False     63
Name: C9orf57, dtype: int64

C9orf5
False    183
Name: C9orf5, dtype: int64

C9orf64
False    183
Name: C9orf64, dtype: int64

C9orf66
False    183
Name: C9orf66, dtype: int64

C9orf68
False    183
Name: C9orf68, dtype: int64

C9orf69
False    183
Name: C9orf69, dtype: int64

C9orf6
False    183
Name: C9orf6, dtype: int64

C9orf70
False    136
True      47
Name: C9orf70, dtype: int64

C9orf71
True     122
False     61
Name: C9orf71, dtype: int64

C9orf72
False    183
Name: C9orf72, dtype: int64

C9orf78
False    183
Name: C9orf78, dtype: int64

C9orf7
False    183
Name: C9orf7, dtype: int64

C9orf80
False    183
Name: C9orf80, dtype: int64

C9orf82
False    183
Name: C9orf82, dtype: int64

C9orf84
False    173
True      10
Name: C9orf84, dtype: int64

C9orf85
False    183
Name: C9orf85, dtype: int64

C9orf86
False    183
Name: C9orf86, dtype: int64

C9orf89
False    183
Name: C9orf89, dtype: int64

C9orf91
False    183
Name: C9orf91, dtype: int64

C9orf93
False    183
Name: C9orf93, dtype: int64

C9orf95
False    183
Name: C9orf95, dtype: int64

C9orf96
False    181
True       2
Name: C9orf96, dtype: int64

C9orf98
False    183
Name: C9orf98, dtype: int64

C9orf9
False    183
Name: C9orf9, dtype: int64

C9
False    122
True      61
Name: C9, dtype: int64

CA10
False    158
True      25
Name: CA10, dtype: int64

CA11
False    183
Name: CA11, dtype: int64

CA12
False    183
Name: CA12, dtype: int64

CA13
False    183
Name: CA13, dtype: int64

CA14
False    182
True       1
Name: CA14, dtype: int64

CA1
True     107
False     76
Name: CA1, dtype: int64

CA2
False    183
Name: CA2, dtype: int64

CA3
False    183
Name: CA3, dtype: int64

CA4
False    167
True      16
Name: CA4, dtype: int64

CA5A
True     93
False    90
Name: CA5A, dtype: int64

CA5BP
False    183
Name: CA5BP, dtype: int64

CA5B
False    183
Name: CA5B, dtype: int64

CA7
False    152
True      31
Name: CA7, dtype: int64

CA8
False    183
Name: CA8, dtype: int64

CA9
False    182
True       1
Name: CA9, dtype: int64

CAB39L
False    183
Name: CAB39L, dtype: int64

CAB39
False    183
Name: CAB39, dtype: int64

CABC1
False    183
Name: CABC1, dtype: int64

CABIN1
False    183
Name: CABIN1, dtype: int64

CABLES1
False    183
Name: CABLES1, dtype: int64

CABLES2
False    183
Name: CABLES2, dtype: int64

CABP1
False    183
Name: CABP1, dtype: int64

CABP4
False    182
True       1
Name: CABP4, dtype: int64

CABP7
False    183
Name: CABP7, dtype: int64

CABYR
False    183
Name: CABYR, dtype: int64

CACHD1
False    183
Name: CACHD1, dtype: int64

CACNA1A
False    183
Name: CACNA1A, dtype: int64

CACNA1B
False    178
True       5
Name: CACNA1B, dtype: int64

CACNA1C
False    183
Name: CACNA1C, dtype: int64

CACNA1D
False    183
Name: CACNA1D, dtype: int64

CACNA1E
False    180
True       3
Name: CACNA1E, dtype: int64

CACNA1F
False    182
True       1
Name: CACNA1F, dtype: int64

CACNA1G
False    183
Name: CACNA1G, dtype: int64

CACNA1H
False    183
Name: CACNA1H, dtype: int64

CACNA1I
False    182
True       1
Name: CACNA1I, dtype: int64

CACNA1S
False    94
True     89
Name: CACNA1S, dtype: int64

CACNA2D1
False    182
True       1
Name: CACNA2D1, dtype: int64

CACNA2D2
False    183
Name: CACNA2D2, dtype: int64

CACNA2D3
False    183
Name: CACNA2D3, dtype: int64

CACNA2D4
False    183
Name: CACNA2D4, dtype: int64

CACNB1
False    183
Name: CACNB1, dtype: int64

CACNB2
False    183
Name: CACNB2, dtype: int64

CACNB3
False    183
Name: CACNB3, dtype: int64

CACNB4
False    183
Name: CACNB4, dtype: int64

CACNG1
False    117
True      66
Name: CACNG1, dtype: int64

CACNG2
True     112
False     71
Name: CACNG2, dtype: int64

CACNG3
True     93
False    90
Name: CACNG3, dtype: int64

CACNG4
False    183
Name: CACNG4, dtype: int64

CACNG5
True     95
False    88
Name: CACNG5, dtype: int64

CACNG6
False    160
True      23
Name: CACNG6, dtype: int64

CACNG7
False    111
True      72
Name: CACNG7, dtype: int64

CACNG8
True     105
False     78
Name: CACNG8, dtype: int64

CACYBP
False    183
Name: CACYBP, dtype: int64

CADM1
False    183
Name: CADM1, dtype: int64

CADM2
False    169
True      14
Name: CADM2, dtype: int64

CADM3
False    182
True       1
Name: CADM3, dtype: int64

CADM4
False    183
Name: CADM4, dtype: int64

CADPS2
False    183
Name: CADPS2, dtype: int64

CADPS
False    183
Name: CADPS, dtype: int64

CAD
False    183
Name: CAD, dtype: int64

CAGE1
False    112
True      71
Name: CAGE1, dtype: int64

CALB1
False    177
True       6
Name: CALB1, dtype: int64

CALB2
False    183
Name: CALB2, dtype: int64

CALCA
False    138
True      45
Name: CALCA, dtype: int64

CALCB
False    132
True      51
Name: CALCB, dtype: int64

CALCOCO1
False    183
Name: CALCOCO1, dtype: int64

CALCOCO2
False    183
Name: CALCOCO2, dtype: int64

CALCRL
False    183
Name: CALCRL, dtype: int64

CALCR
False    165
True      18
Name: CALCR, dtype: int64

CALD1
False    183
Name: CALD1, dtype: int64

CALHM1
False    162
True      21
Name: CALHM1, dtype: int64

CALHM2
False    183
Name: CALHM2, dtype: int64

CALHM3
False    176
True       7
Name: CALHM3, dtype: int64

CALM1
False    183
Name: CALM1, dtype: int64

CALM2
False    183
Name: CALM2, dtype: int64

CALM3
False    183
Name: CALM3, dtype: int64

CALML3
False    100
True      83
Name: CALML3, dtype: int64

CALML4
False    183
Name: CALML4, dtype: int64

CALML5
False    128
True      55
Name: CALML5, dtype: int64

CALML6
False    155
True      28
Name: CALML6, dtype: int64

CALN1
False    170
True      13
Name: CALN1, dtype: int64

CALR3
True     114
False     69
Name: CALR3, dtype: int64

CALR

False    183
Name: CALR, dtype: int64

CALU
False    183
Name: CALU, dtype: int64

CALY
False    174
True       9
Name: CALY, dtype: int64

CAMK1D
False    183
Name: CAMK1D, dtype: int64

CAMK1G
False    183
Name: CAMK1G, dtype: int64

CAMK1
False    183
Name: CAMK1, dtype: int64

CAMK2A
False    182
True       1
Name: CAMK2A, dtype: int64

CAMK2B
False    181
True       2
Name: CAMK2B, dtype: int64

CAMK2D
False    183
Name: CAMK2D, dtype: int64

CAMK2G
False    183
Name: CAMK2G, dtype: int64

CAMK2N1
False    183
Name: CAMK2N1, dtype: int64

CAMK2N2
False    183
Name: CAMK2N2, dtype: int64

CAMK4
False    183
Name: CAMK4, dtype: int64

CAMKK1
False    183
Name: CAMKK1, dtype: int64

CAMKK2
False    183
Name: CAMKK2, dtype: int64

CAMKV
False    135
True      48
Name: CAMKV, dtype: int64

CAMLG
False    183
Name: CAMLG, dtype: int64

CAMP
False    153
True      30
Name: CAMP, dtype: int64

CAMSAP1L1
False    183
Name: CAMSAP1L1, dtype: int64

CAMSAP1
False    183
Name: CAMSAP1, dtype: int64

CAMTA1
False    183
Name: CAMTA1, dtype: int64

CAMTA2
False    183
Name: CAMTA2, dtype: int64

CAND1
False    183
Name: CAND1, dtype: int64

CAND2
False    183
Name: CAND2, dtype: int64

CANT1
False    183
Name: CANT1, dtype: int64

CANX
False    183
Name: CANX, dtype: int64

CAP1
False    183
Name: CAP1, dtype: int64

CAP2
False    183
Name: CAP2, dtype: int64

CAPG
False    183
Name: CAPG, dtype: int64

CAPN10
False    183
Name: CAPN10, dtype: int64

CAPN11
False    180
True       3
Name: CAPN11, dtype: int64

CAPN12
False    183
Name: CAPN12, dtype: int64

CAPN13
False    180
True       3
Name: CAPN13, dtype: int64

CAPN14
False    173
True      10
Name: CAPN14, dtype: int64

CAPN1
False    183
Name: CAPN1, dtype: int64

CAPN2
False    183
Name: CAPN2, dtype: int64

CAPN3
False    183
Name: CAPN3, dtype: int64

CAPN5
False    183
Name: CAPN5, dtype: int64

CAPN6
False    183
Name: CAPN6, dtype: int64

CAPN7
False    183
Name: CAPN7, dtype: int64

CAPN8
False    182
True       1
Name: CAPN8, dtype: int64

CAPN9
False    180
True       3
Name: CAPN9, dtype: int64

CAPNS1
False    183
Name: CAPNS1, dtype: int64

CAPNS2
False    149
True      34
Name: CAPNS2, dtype: int64

CAPRIN1
False    183
Name: CAPRIN1, dtype: int64

CAPRIN2
False    183
Name: CAPRIN2, dtype: int64

CAPS2
False    183
Name: CAPS2, dtype: int64

CAPSL
False    147
True      36
Name: CAPSL, dtype: int64

CAPS
False    183
Name: CAPS, dtype: int64

CAPZA1
False    183
Name: CAPZA1, dtype: int64

CAPZA2
False    183
Name: CAPZA2, dtype: int64

CAPZA3
False    127
True      56
Name: CAPZA3, dtype: int64

CAPZB
False    183
Name: CAPZB, dtype: int64

CARD10
False    183
Name: CARD10, dtype: int64

CARD11
False    183
Name: CARD11, dtype: int64

CARD14
False    183
Name: CARD14, dtype: int64

CARD16
False    183
Name: CARD16, dtype: int64

CARD17
True     109
False     74
Name: CARD17, dtype: int64

CARD6
False    183
Name: CARD6, dtype: int64

CARD8
False    183
Name: CARD8, dtype: int64

CARD9
False    183
Name: CARD9, dtype: int64

CARHSP1
False    183
Name: CARHSP1, dtype: int64

CARKD
False    183
Name: CARKD, dtype: int64

CARM1
False    183
Name: CARM1, dtype: int64

CARNS1
False    183
Name: CARNS1, dtype: int64

CARS2
False    183
Name: CARS2, dtype: int64

CARS
False    183
Name: CARS, dtype: int64

CARTPT
False    155
True      28
Name: CARTPT, dtype: int64

CASC1
False    183
Name: CASC1, dtype: int64

CASC2
False    183
Name: CASC2, dtype: int64

CASC3
False    183
Name: CASC3, dtype: int64

CASC4
False    183
Name: CASC4, dtype: int64

CASC5
False    183
Name: CASC5, dtype: int64

CASD1
False    183
Name: CASD1, dtype: int64

CASKIN1
False    177
True       6
Name: CASKIN1, dtype: int64

CASKIN2
False    183
Name: CASKIN2, dtype: int64

CASK
False    183
Name: CASK, dtype: int64

CASP10
False    183
Name: CASP10, dtype: int64

CASP12
False    173
True      10
Name: CASP12, dtype: int64

CASP14
True     127
False     56
Name: CASP14, dtype: int64

CASP1
False    183
Name: CASP1, dtype: int64

CASP2
False    183
Name: CASP2, dtype: int64

CASP3
False    183
Name: CASP3, dtype: int64

CASP4
False    183
Name: CASP4, dtype: int64

CASP5
False    169
True      14
Name: CASP5, dtype: int64

CASP6
False    183
Name: CASP6, dtype: int64

CASP7
False    183
Name: CASP7, dtype: int64

CASP8AP2
False    183
Name: CASP8AP2, dtype: int64

CASP8
False    183
Name: CASP8, dtype: int64

CASP9
False    183
Name: CASP9, dtype: int64

CASQ1
False    174
True       9
Name: CASQ1, dtype: int64

CASQ2
False    182
True       1
Name: CASQ2, dtype: int64

CASR
False    179
True       4
Name: CASR, dtype: int64

CASS4
False    182
True       1
Name: CASS4, dtype: int64

CAST
False    183
Name: CAST, dtype: int64

CASZ1
False    183
Name: CASZ1, dtype: int64

CATSPER1
False    181
True       2
Name: CATSPER1, dtype: int64

CATSPER2P1
False    183
Name: CATSPER2P1, dtype: int64

CATSPER2
False    183
Name: CATSPER2, dtype: int64

CATSPER3
False    183
Name: CATSPER3, dtype: int64

CATSPERB
False    182
True       1
Name: CATSPERB, dtype: int64

CATSPERG
False    183
Name: CATSPERG, dtype: int64

CAT
False    183
Name: CAT, dtype: int64

CAV1
False    183
Name: CAV1, dtype: int64

CAV2
False    183
Name: CAV2, dtype: int64

CAV3
True     110
False     73
Name: CAV3, dtype: int64

CBARA1
False    183
Name: CBARA1, dtype: int64

CBFA2T2
False    183
Name: CBFA2T2, dtype: int64

CBFA2T3
False    183
Name: CBFA2T3, dtype: int64

CBFB
False    183
Name: CBFB, dtype: int64

CBLB
False    183
Name: CBLB, dtype: int64

CBLC
False    181
True       2
Name: CBLC, dtype: int64

CBLL1
False    183
Name: CBLL1, dtype: int64

CBLN1
False    180
True       3
Name: CBLN1, dtype: int64

CBLN2
False    153
True      30
Name: CBLN2, dtype: int64

CBLN3
False    183
Name: CBLN3, dtype: int64

CBLN4
False    179
True       4
Name: CBLN4, dtype: int64

CBL
False    183
Name: CBL, dtype: int64

CBR1
False    183
Name: CBR1, dtype: int64

CBR3
False    183
Name: CBR3, dtype: int64

CBR4
False    183
Name: CBR4, dtype: int64

CBS
False    183
Name: CBS, dtype: int64

CBWD1
False    183
Name: CBWD1, dtype: int64

CBWD2
False    183
Name: CBWD2, dtype: int64

CBWD3
False    183
Name: CBWD3, dtype: int64

CBWD5
False    107
True      76
Name: CBWD5, dtype: int64

CBWD6
False    183
Name: CBWD6, dtype: int64

CBX1
False    183
Name: CBX1, dtype: int64

CBX2
False    183
Name: CBX2, dtype: int64

CBX3
False    183
Name: CBX3, dtype: int64

CBX4
False    183
Name: CBX4, dtype: int64

CBX5
False    183
Name: CBX5, dtype: int64

CBX6
False    183
Name: CBX6, dtype: int64

CBX7
False    183
Name: CBX7, dtype: int64

CBX8
False    183
Name: CBX8, dtype: int64

CBY1
False    183
Name: CBY1, dtype: int64

CC2D1A
False    183
Name: CC2D1A, dtype: int64

CC2D1B
False    183
Name: CC2D1B, dtype: int64

CC2D2A
False    183
Name: CC2D2A, dtype: int64

CC2D2B
False    183
Name: CC2D2B, dtype: int64

CCAR1
False    183
Name: CCAR1, dtype: int64

CCBE1
False    181
True       2
Name: CCBE1, dtype: int64

CCBL1
False    183
Name: CCBL1, dtype: int64

CCBL2
False    183
Name: CCBL2, dtype: int64

CCBP2
False    183
Name: CCBP2, dtype: int64

CCDC101
False    183
Name: CCDC101, dtype: int64

CCDC102A
False    183
Name: CCDC102A, dtype: int64

CCDC102B
False    183
Name: CCDC102B, dtype: int64

CCDC103
False    183
Name: CCDC103, dtype: int64

CCDC104
False    183
Name: CCDC104, dtype: int64

CCDC106
False    183
Name: CCDC106, dtype: int64

CCDC107
False    183
Name: CCDC107, dtype: int64

CCDC108
False    180
True       3
Name: CCDC108, dtype: int64

CCDC109A
False    183
Name: CCDC109A, dtype: int64

CCDC109B
False    183
Name: CCDC109B, dtype: int64

CCDC110
False    183
Name: CCDC110, dtype: int64

CCDC111
False    183
Name: CCDC111, dtype: int64

CCDC112
False    183
Name: CCDC112, dtype: int64

CCDC113
False    183
Name: CCDC113, dtype: int64

CCDC114
False    183
Name: CCDC114, dtype: int64

CCDC115
False    183
Name: CCDC115, dtype: int64

CCDC116
False    182
True       1
Name: CCDC116, dtype: int64

CCDC117
False    183
Name: CCDC117, dtype: int64

CCDC11
False    183
Name: CCDC11, dtype: int64

CCDC120
False    183
Name: CCDC120, dtype: int64

CCDC121
False    183
Name: CCDC121, dtype: int64

CCDC122
False    183
Name: CCDC122, dtype: int64

CCDC123
False    183
Name: CCDC123, dtype: int64

CCDC124
False    183
Name: CCDC124, dtype: int64

CCDC125
False    183
Name: CCDC125, dtype: int64

CCDC126
False    183
Name: CCDC126, dtype: int64

CCDC127
False    183
Name: CCDC127, dtype: int64

CCDC129
False    171
True      12
Name: CCDC129, dtype: int64

CCDC12
False    183
Name: CCDC12, dtype: int64

CCDC130
False    183
Name: CCDC130, dtype: int64

CCDC132
False    183
Name: CCDC132, dtype: int64

CCDC134
False    183
Name: CCDC134, dtype: int64

CCDC135
False    174
True       9
Name: CCDC135, dtype: int64

CCDC136

False    183
Name: CCDC136, dtype: int64

CCDC137
False    183
Name: CCDC137, dtype: int64

CCDC138
False    183
Name: CCDC138, dtype: int64

CCDC13
False    183
Name: CCDC13, dtype: int64

CCDC141
False    181
True       2
Name: CCDC141, dtype: int64

CCDC142
False    183
Name: CCDC142, dtype: int64

CCDC144A
False    173
True      10
Name: CCDC144A, dtype: int64

CCDC144B
False    180
True       3
Name: CCDC144B, dtype: int64

CCDC144C
False    150
True      33
Name: CCDC144C, dtype: int64

CCDC144NL
False    104
True      79
Name: CCDC144NL, dtype: int64

CCDC146
False    183
Name: CCDC146, dtype: int64

CCDC147
False    178
True       5
Name: CCDC147, dtype: int64

CCDC148
False    183
Name: CCDC148, dtype: int64

CCDC149
False    183
Name: CCDC149, dtype: int64

CCDC14
False    183
Name: CCDC14, dtype: int64

CCDC150
False    182
True       1
Name: CCDC150, dtype: int64

CCDC151
False    183
Name: CCDC151, dtype: int64

CCDC152
False    183
Name: CCDC152, dtype: int64

CCDC153
False    183
Name: CCDC153, dtype: int64

CCDC154
False    180
True       3
Name: CCDC154, dtype: int64

CCDC155
False    105
True      78
Name: CCDC155, dtype: int64

CCDC157
False    183
Name: CCDC157, dtype: int64

CCDC158
False    181
True       2
Name: CCDC158, dtype: int64

CCDC159
False    183
Name: CCDC159, dtype: int64

CCDC15
False    183
Name: CCDC15, dtype: int64

CCDC160
False    176
True       7
Name: CCDC160, dtype: int64

CCDC163P
False    181
True       2
Name: CCDC163P, dtype: int64

CCDC17
False    182
True       1
Name: CCDC17, dtype: int64

CCDC18
False    183
Name: CCDC18, dtype: int64

CCDC19
False    183
Name: CCDC19, dtype: int64

CCDC21
False    183
Name: CCDC21, dtype: int64

CCDC22
False    183
Name: CCDC22, dtype: int64

CCDC23
False    183
Name: CCDC23, dtype: int64

CCDC24
False    183
Name: CCDC24, dtype: int64

CCDC25
False    183
Name: CCDC25, dtype: int64

CCDC28A
False    183
Name: CCDC28A, dtype: int64

CCDC28B
False    183
Name: CCDC28B, dtype: int64

CCDC30
False    183
Name: CCDC30, dtype: int64

CCDC33
False    165
True      18
Name: CCDC33, dtype: int64

CCDC34
False    183
Name: CCDC34, dtype: int64

CCDC36
False    182
True       1
Name: CCDC36, dtype: int64

CCDC37
True     116
False     67
Name: CCDC37, dtype: int64

CCDC39
False    183
Name: CCDC39, dtype: int64

CCDC3
False    183
Name: CCDC3, dtype: int64

CCDC40
False    183
Name: CCDC40, dtype: int64

CCDC41
False    183
Name: CCDC41, dtype: int64

CCDC42B
False    182
True       1
Name: CCDC42B, dtype: int64

CCDC42
True     94
False    89
Name: CCDC42, dtype: int64

CCDC43
False    183
Name: CCDC43, dtype: int64

CCDC45
False    183
Name: CCDC45, dtype: int64

CCDC46
False    183
Name: CCDC46, dtype: int64

CCDC47
False    183
Name: CCDC47, dtype: int64

CCDC48
False    183
Name: CCDC48, dtype: int64

CCDC50
False    183
Name: CCDC50, dtype: int64

CCDC51
False    183
Name: CCDC51, dtype: int64

CCDC52
False    183
Name: CCDC52, dtype: int64

CCDC53
False    183
Name: CCDC53, dtype: int64

CCDC54
False    116
True      67
Name: CCDC54, dtype: int64

CCDC55
False    183
Name: CCDC55, dtype: int64

CCDC56
False    183
Name: CCDC56, dtype: int64

CCDC57
False    183
Name: CCDC57, dtype: int64

CCDC58
False    183
Name: CCDC58, dtype: int64

CCDC59
False    183
Name: CCDC59, dtype: int64

CCDC60
True     104
False     79
Name: CCDC60, dtype: int64

CCDC61
False    183
Name: CCDC61, dtype: int64

CCDC62
False    182
True       1
Name: CCDC62, dtype: int64

CCDC64B
False    181
True       2
Name: CCDC64B, dtype: int64

CCDC64
False    183
Name: CCDC64, dtype: int64

CCDC65
False    181
True       2
Name: CCDC65, dtype: int64

CCDC66
False    183
Name: CCDC66, dtype: int64

CCDC67
False    175
True       8
Name: CCDC67, dtype: int64

CCDC68
False    183
Name: CCDC68, dtype: int64

CCDC69
False    183
Name: CCDC69, dtype: int64

CCDC6
False    183
Name: CCDC6, dtype: int64

CCDC71
False    183
Name: CCDC71, dtype: int64

CCDC72
False    183
Name: CCDC72, dtype: int64

CCDC73
False    183
Name: CCDC73, dtype: int64

CCDC74A
False    183
Name: CCDC74A, dtype: int64

CCDC74B
False    183
Name: CCDC74B, dtype: int64

CCDC75
False    183
Name: CCDC75, dtype: int64

CCDC76
False    183
Name: CCDC76, dtype: int64

CCDC77
False    183
Name: CCDC77, dtype: int64

CCDC78
False    183
Name: CCDC78, dtype: int64

CCDC79
True     125
False     58
Name: CCDC79, dtype: int64

CCDC7
False    183
Name: CCDC7, dtype: int64

CCDC80
False    183
Name: CCDC80, dtype: int64

CCDC81
False    183
Name: CCDC81, dtype: int64

CCDC82
False    183
Name: CCDC82, dtype: int64

CCDC84
False    183
Name: CCDC84, dtype: int64

CCDC85A
False    183
Name: CCDC85A, dtype: int64

CCDC85B
False    183
Name: CCDC85B, dtype: int64

CCDC85C
False    183
Name: CCDC85C, dtype: int64

CCDC86
False    183
Name: CCDC86, dtype: int64

CCDC87
False    183
Name: CCDC87, dtype: int64

CCDC88A
False    183
Name: CCDC88A, dtype: int64

CCDC88B
False    183
Name: CCDC88B, dtype: int64

CCDC88C
False    183
Name: CCDC88C, dtype: int64

CCDC89
False    183
Name: CCDC89, dtype: int64

CCDC8
False    183
Name: CCDC8, dtype: int64

CCDC90A
False    183
Name: CCDC90A, dtype: int64

CCDC90B
False    183
Name: CCDC90B, dtype: int64

CCDC91
False    183
Name: CCDC91, dtype: int64

CCDC92
False    183
Name: CCDC92, dtype: int64

CCDC93
False    183
Name: CCDC93, dtype: int64

CCDC94
False    183
Name: CCDC94, dtype: int64

CCDC96
False    183
Name: CCDC96, dtype: int64

CCDC97
False    183
Name: CCDC97, dtype: int64

CCDC99
False    183
Name: CCDC99, dtype: int64

CCDC9
False    183
Name: CCDC9, dtype: int64

CCHCR1
False    183
Name: CCHCR1, dtype: int64

CCIN
False    182
True       1
Name: CCIN, dtype: int64

CCKAR
False    96
True     87
Name: CCKAR, dtype: int64

CCKBR
False    174
True       9
Name: CCKBR, dtype: int64

CCK
False    168
True      15
Name: CCK, dtype: int64

CCL11
False    181
True       2
Name: CCL11, dtype: int64

CCL13
False    180
True       3
Name: CCL13, dtype: int64

CCL14-CCL15
False    127
True      56
Name: CCL14-CCL15, dtype: int64

CCL14
False    182
True       1
Name: CCL14, dtype: int64

CCL15
False    179
True       4
Name: CCL15, dtype: int64

CCL16
False    148
True      35
Name: CCL16, dtype: int64

CCL17
False    178
True       5
Name: CCL17, dtype: int64

CCL18
False    182
True       1
Name: CCL18, dtype: int64

CCL19
False    181
True       2
Name: CCL19, dtype: int64

CCL20
False    181
True       2
Name: CCL20, dtype: int64

CCL21
False    183
Name: CCL21, dtype: int64

CCL22
False    182
True       1
Name: CCL22, dtype: int64

CCL23
False    174
True       9
Name: CCL23, dtype: int64

CCL24
False    173
True      10
Name: CCL24, dtype: int64

CCL25
False    118
True      65
Name: CCL25, dtype: int64

CCL26
False    182
True       1
Name: CCL26, dtype: int64

CCL27
True     92
False    91
Name: CCL27, dtype: int64

CCL28
False    181
True       2
Name: CCL28, dtype: int64

CCL2
False    183
Name: CCL2, dtype: int64

CCL3L1
False    181
True       2
Name: CCL3L1, dtype: int64

CCL3L3
False    111
True      72
Name: CCL3L3, dtype: int64

CCL3
False    183
Name: CCL3, dtype: int64

CCL4L2
False    181
True       2
Name: CCL4L2, dtype: int64

CCL4
False    183
Name: CCL4, dtype: int64

CCL5
False    183
Name: CCL5, dtype: int64

CCL7
False    158
True      25
Name: CCL7, dtype: int64

CCL8
False    180
True       3
Name: CCL8, dtype: int64

CCM2
False    183
Name: CCM2, dtype: int64

CCNA1
False    181
True       2
Name: CCNA1, dtype: int64

CCNA2
False    183
Name: CCNA2, dtype: int64

CCNB1IP1
False    183
Name: CCNB1IP1, dtype: int64

CCNB1
False    183
Name: CCNB1, dtype: int64

CCNB2
False    183
Name: CCNB2, dtype: int64

CCNB3
False    183
Name: CCNB3, dtype: int64

CCNC
False    183
Name: CCNC, dtype: int64

CCND1
False    183
Name: CCND1, dtype: int64

CCND2
False    183
Name: CCND2, dtype: int64

CCND3
False    183
Name: CCND3, dtype: int64

CCNDBP1
False    183
Name: CCNDBP1, dtype: int64

CCNE1
False    183
Name: CCNE1, dtype: int64

CCNE2
False    183
Name: CCNE2, dtype: int64

CCNF
False    183
Name: CCNF, dtype: int64

CCNG1
False    183
Name: CCNG1, dtype: int64

CCNG2
False    183
Name: CCNG2, dtype: int64

CCNH
False    183
Name: CCNH, dtype: int64

CCNI2
False    183
Name: CCNI2, dtype: int64

CCNI
False    183
Name: CCNI, dtype: int64

CCNJL
False    183
Name: CCNJL, dtype: int64

CCNJ
False    183
Name: CCNJ, dtype: int64

CCNK
False    183
Name: CCNK, dtype: int64

CCNL1
False    183
Name: CCNL1, dtype: int64

CCNL2
False    183
Name: CCNL2, dtype: int64

CCNO
False    182
True       1
Name: CCNO, dtype: int64

CCNT1
False    183
Name: CCNT1, dtype: int64

CCNT2
False    183
Name: CCNT2, dtype: int64

CCNYL1
False    183
Name: CCNYL1, dtype: int64

CCNY
False    183
Name: CCNY, dtype: int64

CCPG1
False    183
Name: CCPG1, dtype: int64

CCR10
False    183
Name: CCR10, dtype: int64

CCR1
False    183
Name: CCR1, dtype: int64

CCR2

False    183
Name: CCR2, dtype: int64

CCR3
False    169
True      14
Name: CCR3, dtype: int64

CCR4
False    176
True       7
Name: CCR4, dtype: int64

CCR5
False    183
Name: CCR5, dtype: int64

CCR6
False    183
Name: CCR6, dtype: int64

CCR7
False    182
True       1
Name: CCR7, dtype: int64

CCR8
False    175
True       8
Name: CCR8, dtype: int64

CCR9
False    179
True       4
Name: CCR9, dtype: int64

CCRL1
False    183
Name: CCRL1, dtype: int64

CCRL2
False    183
Name: CCRL2, dtype: int64

CCRN4L
False    183
Name: CCRN4L, dtype: int64

CCS
False    183
Name: CCS, dtype: int64

CCT2
False    183
Name: CCT2, dtype: int64

CCT3
False    183
Name: CCT3, dtype: int64

CCT4
False    183
Name: CCT4, dtype: int64

CCT5
False    183
Name: CCT5, dtype: int64

CCT6A
False    183
Name: CCT6A, dtype: int64

CCT6B
False    183
Name: CCT6B, dtype: int64

CCT6P1
False    183
Name: CCT6P1, dtype: int64

CCT7
False    183
Name: CCT7, dtype: int64

CCT8
False    183
Name: CCT8, dtype: int64

CD101
False    183
Name: CD101, dtype: int64

CD109
False    183
Name: CD109, dtype: int64

CD14
False    183
Name: CD14, dtype: int64

CD151
False    183
Name: CD151, dtype: int64

CD160
False    183
Name: CD160, dtype: int64

CD163L1
False    183
Name: CD163L1, dtype: int64

CD163
False    183
Name: CD163, dtype: int64

CD164L2
False    182
True       1
Name: CD164L2, dtype: int64

CD164
False    183
Name: CD164, dtype: int64

CD177
False    180
True       3
Name: CD177, dtype: int64

CD180
False    183
Name: CD180, dtype: int64

CD19
False    170
True      13
Name: CD19, dtype: int64

CD1A
False    178
True       5
Name: CD1A, dtype: int64

CD1B
False    160
True      23
Name: CD1B, dtype: int64

CD1C
False    181
True       2
Name: CD1C, dtype: int64

CD1D
False    183
Name: CD1D, dtype: int64

CD1E
False    182
True       1
Name: CD1E, dtype: int64

CD200R1
False    182
True       1
Name: CD200R1, dtype: int64

CD200
False    183
Name: CD200, dtype: int64

CD207
False    182
True       1
Name: CD207, dtype: int64

CD209
False    183
Name: CD209, dtype: int64

CD226
False    182
True       1
Name: CD226, dtype: int64

CD22
False    183
Name: CD22, dtype: int64

CD244
False    183
Name: CD244, dtype: int64

CD247
False    183
Name: CD247, dtype: int64

CD248
False    183
Name: CD248, dtype: int64

CD24
False    183
Name: CD24, dtype: int64

CD274
False    182
True       1
Name: CD274, dtype: int64

CD276
False    183
Name: CD276, dtype: int64

CD27
False    183
Name: CD27, dtype: int64

CD28
False    182
True       1
Name: CD28, dtype: int64

CD2AP
False    183
Name: CD2AP, dtype: int64

CD2BP2
False    183
Name: CD2BP2, dtype: int64

CD2
False    183
Name: CD2, dtype: int64

CD300A
False    183
Name: CD300A, dtype: int64

CD300C
False    183
Name: CD300C, dtype: int64

CD300E
False    155
True      28
Name: CD300E, dtype: int64

CD300LB
False    183
Name: CD300LB, dtype: int64

CD300LF
False    183
Name: CD300LF, dtype: int64

CD300LG
False    152
True      31
Name: CD300LG, dtype: int64

CD302
False    183
Name: CD302, dtype: int64

CD320
False    183
Name: CD320, dtype: int64

CD33
False    183
Name: CD33, dtype: int64

CD34
False    183
Name: CD34, dtype: int64

CD36
False    183
Name: CD36, dtype: int64

CD37
False    183
Name: CD37, dtype: int64

CD38
False    182
True       1
Name: CD38, dtype: int64

CD3D
False    183
Name: CD3D, dtype: int64

CD3EAP
False    183
Name: CD3EAP, dtype: int64

CD3E
False    183
Name: CD3E, dtype: int64

CD3G
False    180
True       3
Name: CD3G, dtype: int64

CD40LG
False    181
True       2
Name: CD40LG, dtype: int64

CD40
False    183
Name: CD40, dtype: int64

CD44
False    183
Name: CD44, dtype: int64

CD46
False    183
Name: CD46, dtype: int64

CD47
False    183
Name: CD47, dtype: int64

CD48
False    183
Name: CD48, dtype: int64

CD4
False    183
Name: CD4, dtype: int64

CD52
False    183
Name: CD52, dtype: int64

CD53
False    183
Name: CD53, dtype: int64

CD55
False    183
Name: CD55, dtype: int64

CD58
False    183
Name: CD58, dtype: int64

CD59
False    183
Name: CD59, dtype: int64

CD5L
False    106
True      77
Name: CD5L, dtype: int64

CD5
False    183
Name: CD5, dtype: int64

CD63
False    183
Name: CD63, dtype: int64

CD68
False    183
Name: CD68, dtype: int64

CD69
False    183
Name: CD69, dtype: int64

CD6
False    183
Name: CD6, dtype: int64

CD70
False    181
True       2
Name: CD70, dtype: int64

CD72
False    183
Name: CD72, dtype: int64

CD74
False    183
Name: CD74, dtype: int64

CD79A
False    183
Name: CD79A, dtype: int64

CD79B
False    183
Name: CD79B, dtype: int64

CD7
False    183
Name: CD7, dtype: int64

CD80
False    182
True       1
Name: CD80, dtype: int64

CD81
False    183
Name: CD81, dtype: int64

CD82
False    183
Name: CD82, dtype: int64

CD83
False    183
Name: CD83, dtype: int64

CD84
False    183
Name: CD84, dtype: int64

CD86
False    183
Name: CD86, dtype: int64

CD8A
False    183
Name: CD8A, dtype: int64

CD8B
False    183
Name: CD8B, dtype: int64

CD93
False    183
Name: CD93, dtype: int64

CD96
False    183
Name: CD96, dtype: int64

CD97
False    183
Name: CD97, dtype: int64

CD99L2
False    183
Name: CD99L2, dtype: int64

CD99
False    183
Name: CD99, dtype: int64

CD9
False    183
Name: CD9, dtype: int64

CDADC1
False    183
Name: CDADC1, dtype: int64

CDAN1
False    183
Name: CDAN1, dtype: int64

CDA
False    183
Name: CDA, dtype: int64

CDC123
False    183
Name: CDC123, dtype: int64

CDC14A
False    183
Name: CDC14A, dtype: int64

CDC14B
False    183
Name: CDC14B, dtype: int64

CDC14C
False    180
True       3
Name: CDC14C, dtype: int64

CDC16
False    183
Name: CDC16, dtype: int64

CDC20B
False    166
True      17
Name: CDC20B, dtype: int64

CDC20
False    183
Name: CDC20, dtype: int64

CDC23
False    183
Name: CDC23, dtype: int64

CDC25A
False    183
Name: CDC25A, dtype: int64

CDC25B
False    183
Name: CDC25B, dtype: int64

CDC25C
False    182
True       1
Name: CDC25C, dtype: int64

CDC26
False    183
Name: CDC26, dtype: int64

CDC27
False    183
Name: CDC27, dtype: int64

CDC34
False    183
Name: CDC34, dtype: int64

CDC37L1
False    183
Name: CDC37L1, dtype: int64

CDC37
False    183
Name: CDC37, dtype: int64

CDC40
False    183
Name: CDC40, dtype: int64

CDC42BPA
False    183
Name: CDC42BPA, dtype: int64

CDC42BPB
False    183
Name: CDC42BPB, dtype: int64

CDC42BPG
False    183
Name: CDC42BPG, dtype: int64

CDC42EP1
False    183
Name: CDC42EP1, dtype: int64

CDC42EP2
False    183
Name: CDC42EP2, dtype: int64

CDC42EP3
False    183
Name: CDC42EP3, dtype: int64

CDC42EP4
False    183
Name: CDC42EP4, dtype: int64

CDC42EP5
False    183
Name: CDC42EP5, dtype: int64

CDC42SE1
False    183
Name: CDC42SE1, dtype: int64

CDC42SE2
False    183
Name: CDC42SE2, dtype: int64

CDC42
False    183
Name: CDC42, dtype: int64

CDC45
False    183
Name: CDC45, dtype: int64

CDC5L
False    183
Name: CDC5L, dtype: int64

CDC6
False    183
Name: CDC6, dtype: int64

CDC73
False    183
Name: CDC73, dtype: int64

CDC7
False    183
Name: CDC7, dtype: int64

CDCA2
False    183
Name: CDCA2, dtype: int64

CDCA3
False    183
Name: CDCA3, dtype: int64

CDCA4
False    183
Name: CDCA4, dtype: int64

CDCA5
False    183
Name: CDCA5, dtype: int64

CDCA7L
False    183
Name: CDCA7L, dtype: int64

CDCA7
False    183
Name: CDCA7, dtype: int64

CDCA8
False    183
Name: CDCA8, dtype: int64

CDCP1
False    183
Name: CDCP1, dtype: int64

CDCP2
False    147
True      36
Name: CDCP2, dtype: int64

CDH10
False    169
True      14
Name: CDH10, dtype: int64

CDH11
False    183
Name: CDH11, dtype: int64

CDH12
False    181
True       2
Name: CDH12, dtype: int64

CDH13
False    183
Name: CDH13, dtype: int64

CDH15
False    177
True       6
Name: CDH15, dtype: int64

CDH16
False    159
True      24
Name: CDH16, dtype: int64

CDH17
False    183
Name: CDH17, dtype: int64

CDH18
False    132
True      51
Name: CDH18, dtype: int64

CDH19
False    179
True       4
Name: CDH19, dtype: int64

CDH1
False    183
Name: CDH1, dtype: int64

CDH20
False    173
True      10
Name: CDH20, dtype: int64

CDH22
False    177
True       6
Name: CDH22, dtype: int64

CDH23
False    183
Name: CDH23, dtype: int64

CDH24
False    183
Name: CDH24, dtype: int64

CDH26
False    182
True       1
Name: CDH26, dtype: int64

CDH2
False    183
Name: CDH2, dtype: int64

CDH3
False    183
Name: CDH3, dtype: int64

CDH4
False    175
True       8
Name: CDH4, dtype: int64

CDH5
False    183
Name: CDH5, dtype: int64

CDH6
False    183
Name: CDH6, dtype: int64

CDH8
False    151
True      32
Name: CDH8, dtype: int64

CDHR1

False    179
True       4
Name: CDHR1, dtype: int64

CDHR2
False    182
True       1
Name: CDHR2, dtype: int64

CDHR3
False    183
Name: CDHR3, dtype: int64

CDHR4
False    112
True      71
Name: CDHR4, dtype: int64

CDHR5
False    182
True       1
Name: CDHR5, dtype: int64

CDIPT
False    183
Name: CDIPT, dtype: int64

CDK10
False    183
Name: CDK10, dtype: int64

CDK11A
False    183
Name: CDK11A, dtype: int64

CDK11B
False    183
Name: CDK11B, dtype: int64

CDK12
False    183
Name: CDK12, dtype: int64

CDK13
False    183
Name: CDK13, dtype: int64

CDK14
False    183
Name: CDK14, dtype: int64

CDK15
False    154
True      29
Name: CDK15, dtype: int64

CDK16
False    183
Name: CDK16, dtype: int64

CDK17
False    183
Name: CDK17, dtype: int64

CDK18
False    183
Name: CDK18, dtype: int64

CDK19
False    183
Name: CDK19, dtype: int64

CDK1
False    183
Name: CDK1, dtype: int64

CDK20
False    183
Name: CDK20, dtype: int64

CDK2AP1
False    183
Name: CDK2AP1, dtype: int64

CDK2AP2
False    183
Name: CDK2AP2, dtype: int64

CDK2
False    183
Name: CDK2, dtype: int64

CDK3
False    183
Name: CDK3, dtype: int64

CDK4
False    183
Name: CDK4, dtype: int64

CDK5R1
False    183
Name: CDK5R1, dtype: int64

CDK5R2
False    181
True       2
Name: CDK5R2, dtype: int64

CDK5RAP1
False    183
Name: CDK5RAP1, dtype: int64

CDK5RAP2
False    183
Name: CDK5RAP2, dtype: int64

CDK5RAP3
False    183
Name: CDK5RAP3, dtype: int64

CDK5
False    183
Name: CDK5, dtype: int64

CDK6
False    183
Name: CDK6, dtype: int64

CDK7
False    183
Name: CDK7, dtype: int64

CDK8
False    183
Name: CDK8, dtype: int64

CDK9
False    183
Name: CDK9, dtype: int64

CDKAL1
False    183
Name: CDKAL1, dtype: int64

CDKL1
False    183
Name: CDKL1, dtype: int64

CDKL2
False    183
Name: CDKL2, dtype: int64

CDKL3
False    183
Name: CDKL3, dtype: int64

CDKL4
False    101
True      82
Name: CDKL4, dtype: int64

CDKL5
False    180
True       3
Name: CDKL5, dtype: int64

CDKN1A
False    183
Name: CDKN1A, dtype: int64

CDKN1B
False    183
Name: CDKN1B, dtype: int64

CDKN1C
False    183
Name: CDKN1C, dtype: int64

CDKN2AIPNL
False    183
Name: CDKN2AIPNL, dtype: int64

CDKN2AIP
False    183
Name: CDKN2AIP, dtype: int64

CDKN2A
False    183
Name: CDKN2A, dtype: int64

CDKN2BAS
False    180
True       3
Name: CDKN2BAS, dtype: int64

CDKN2B
False    183
Name: CDKN2B, dtype: int64

CDKN2C
False    183
Name: CDKN2C, dtype: int64

CDKN2D
False    183
Name: CDKN2D, dtype: int64

CDKN3
False    183
Name: CDKN3, dtype: int64

CDNF
False    183
Name: CDNF, dtype: int64

CDO1
False    183
Name: CDO1, dtype: int64

CDON
False    183
Name: CDON, dtype: int64

CDR1
False    173
True      10
Name: CDR1, dtype: int64

CDR2L
False    183
Name: CDR2L, dtype: int64

CDR2
False    183
Name: CDR2, dtype: int64

CDRT15P
False    179
True       4
Name: CDRT15P, dtype: int64

CDRT1
False    177
True       6
Name: CDRT1, dtype: int64

CDRT4
False    183
Name: CDRT4, dtype: int64

CDS1
False    183
Name: CDS1, dtype: int64

CDS2
False    183
Name: CDS2, dtype: int64

CDSN
False    180
True       3
Name: CDSN, dtype: int64

CDT1
False    183
Name: CDT1, dtype: int64

CDV3
False    183
Name: CDV3, dtype: int64

CDX1
False    180
True       3
Name: CDX1, dtype: int64

CDX2
False    183
Name: CDX2, dtype: int64

CDYL2
False    183
Name: CDYL2, dtype: int64

CDYL
False    183
Name: CDYL, dtype: int64

CEACAM16
True     97
False    86
Name: CEACAM16, dtype: int64

CEACAM18
False    102
True      81
Name: CEACAM18, dtype: int64

CEACAM19
False    183
Name: CEACAM19, dtype: int64

CEACAM1
False    183
Name: CEACAM1, dtype: int64

CEACAM20
True     92
False    91
Name: CEACAM20, dtype: int64

CEACAM21
False    183
Name: CEACAM21, dtype: int64

CEACAM22P
False    141
True      42
Name: CEACAM22P, dtype: int64

CEACAM3
False    177
True       6
Name: CEACAM3, dtype: int64

CEACAM4
False    182
True       1
Name: CEACAM4, dtype: int64

CEACAM5
False    180
True       3
Name: CEACAM5, dtype: int64

CEACAM6
False    181
True       2
Name: CEACAM6, dtype: int64

CEACAM7
False    176
True       7
Name: CEACAM7, dtype: int64

CEACAM8
False    106
True      77
Name: CEACAM8, dtype: int64

CEBPA
False    183
Name: CEBPA, dtype: int64

CEBPB
False    183
Name: CEBPB, dtype: int64

CEBPD
False    183
Name: CEBPD, dtype: int64

CEBPE
False    166
True      17
Name: CEBPE, dtype: int64

CEBPG
False    183
Name: CEBPG, dtype: int64

CEBPZ
False    183
Name: CEBPZ, dtype: int64

CECR1
False    183
Name: CECR1, dtype: int64

CECR2
False    178
True       5
Name: CECR2, dtype: int64

CECR4
False    167
True      16
Name: CECR4, dtype: int64

CECR5
False    183
Name: CECR5, dtype: int64

CECR6
False    183
Name: CECR6, dtype: int64

CECR7
False    180
True       3
Name: CECR7, dtype: int64

CELA1
True     127
False     56
Name: CELA1, dtype: int64

CELA2A
False    152
True      31
Name: CELA2A, dtype: int64

CELA2B
False    140
True      43
Name: CELA2B, dtype: int64

CELA3A
False    169
True      14
Name: CELA3A, dtype: int64

CELA3B
False    161
True      22
Name: CELA3B, dtype: int64

CELF1
False    183
Name: CELF1, dtype: int64

CELF2
False    183
Name: CELF2, dtype: int64

CELF3
False    182
True       1
Name: CELF3, dtype: int64

CELF4
False    182
True       1
Name: CELF4, dtype: int64

CELF5
False    183
Name: CELF5, dtype: int64

CELF6
False    183
Name: CELF6, dtype: int64

CELP
False    123
True      60
Name: CELP, dtype: int64

CELSR1
False    183
Name: CELSR1, dtype: int64

CELSR2
False    183
Name: CELSR2, dtype: int64

CELSR3
False    183
Name: CELSR3, dtype: int64

CEL
False    183
Name: CEL, dtype: int64

CEMP1
False    183
Name: CEMP1, dtype: int64

CEND1
False    181
True       2
Name: CEND1, dtype: int64

CENPA
False    182
True       1
Name: CENPA, dtype: int64

CENPBD1
False    183
Name: CENPBD1, dtype: int64

CENPB
False    183
Name: CENPB, dtype: int64

CENPC1
False    183
Name: CENPC1, dtype: int64

CENPE
False    183
Name: CENPE, dtype: int64

CENPF
False    183
Name: CENPF, dtype: int64

CENPH
False    183
Name: CENPH, dtype: int64

CENPI
False    182
True       1
Name: CENPI, dtype: int64

CENPJ
False    183
Name: CENPJ, dtype: int64

CENPK
False    183
Name: CENPK, dtype: int64

CENPL
False    183
Name: CENPL, dtype: int64

CENPM
False    183
Name: CENPM, dtype: int64

CENPN
False    183
Name: CENPN, dtype: int64

CENPO
False    183
Name: CENPO, dtype: int64

CENPP
False    183
Name: CENPP, dtype: int64

CENPQ
False    183
Name: CENPQ, dtype: int64

CENPT
False    183
Name: CENPT, dtype: int64

CENPV
False    183
Name: CENPV, dtype: int64

CENPW
False    183
Name: CENPW, dtype: int64

CEP110
False    183
Name: CEP110, dtype: int64

CEP120
False    183
Name: CEP120, dtype: int64

CEP135
False    183
Name: CEP135, dtype: int64

CEP152
False    183
Name: CEP152, dtype: int64

CEP164
False    183
Name: CEP164, dtype: int64

CEP170L
False    169
True      14
Name: CEP170L, dtype: int64

CEP170
False    183
Name: CEP170, dtype: int64

CEP192
False    183
Name: CEP192, dtype: int64

CEP250
False    183
Name: CEP250, dtype: int64

CEP290
False    183
Name: CEP290, dtype: int64

CEP350
False    183
Name: CEP350, dtype: int64

CEP55
False    183
Name: CEP55, dtype: int64

CEP57
False    183
Name: CEP57, dtype: int64

CEP63
False    183
Name: CEP63, dtype: int64

CEP68
False    183
Name: CEP68, dtype: int64

CEP70
False    183
Name: CEP70, dtype: int64

CEP72
False    183
Name: CEP72, dtype: int64

CEP76
False    183
Name: CEP76, dtype: int64

CEP78
False    183
Name: CEP78, dtype: int64

CEP97
False    183
Name: CEP97, dtype: int64

CEPT1
False    183
Name: CEPT1, dtype: int64

CER1
True     106
False     77
Name: CER1, dtype: int64

CERCAM
False    183
Name: CERCAM, dtype: int64

CERKL
False    183
Name: CERKL, dtype: int64

CERK
False    183
Name: CERK, dtype: int64

CES1
False    183
Name: CES1, dtype: int64

CES2
False    183
Name: CES2, dtype: int64

CES3
False    183
Name: CES3, dtype: int64

CES4
False    178
True       5
Name: CES4, dtype: int64

CES7
True     94
False    89
Name: CES7, dtype: int64

CES8
False    183
Name: CES8, dtype: int64

CETN2
False    183
Name: CETN2, dtype: int64

CETN3
False    183
Name: CETN3, dtype: int64

CETN4P
False    163
True      20
Name: CETN4P, dtype: int64

CETP
False    183
Name: CETP, dtype: int64

CFB
False    183
Name: CFB, dtype: int64

CFC1B
False    171
True      12
Name: CFC1B, dtype: int64

CFDP1
False    183
Name: CFDP1, dtype: int64

CFD
False    183
Name: CFD, dtype: int64

CFHR1
False    141
True      42
Name: CFHR1, dtype: int64

CFHR3
False    174
True       9
Name: CFHR3, dtype: int64

CFH
False    183
Name: CFH, dtype: int64

CFI
False    183
Name: CFI, dtype: int64

CFL1

False    183
Name: CFL1, dtype: int64

CFL2
False    183
Name: CFL2, dtype: int64

CFLAR
False    183
Name: CFLAR, dtype: int64

CFLP1
False    156
True      27
Name: CFLP1, dtype: int64

CFP
False    183
Name: CFP, dtype: int64

CFTR
False    180
True       3
Name: CFTR, dtype: int64

CG030
False    183
Name: CG030, dtype: int64

CGA
False    115
True      68
Name: CGA, dtype: int64

CGB1
False    118
True      65
Name: CGB1, dtype: int64

CGB2
False    136
True      47
Name: CGB2, dtype: int64

CGB5
False    166
True      17
Name: CGB5, dtype: int64

CGB7
False    170
True      13
Name: CGB7, dtype: int64

CGB8
False    151
True      32
Name: CGB8, dtype: int64

CGB
False    167
True      16
Name: CGB, dtype: int64

CGGBP1
False    183
Name: CGGBP1, dtype: int64

CGNL1
False    183
Name: CGNL1, dtype: int64

CGN
False    183
Name: CGN, dtype: int64

CGREF1
False    183
Name: CGREF1, dtype: int64

CGRRF1
False    183
Name: CGRRF1, dtype: int64

CH25H
False    183
Name: CH25H, dtype: int64

CHAC1
False    183
Name: CHAC1, dtype: int64

CHAC2
False    183
Name: CHAC2, dtype: int64

CHADL
False    183
Name: CHADL, dtype: int64

CHAD
False    182
True       1
Name: CHAD, dtype: int64

CHAF1A
False    183
Name: CHAF1A, dtype: int64

CHAF1B
False    183
Name: CHAF1B, dtype: int64

CHAT
False    97
True     86
Name: CHAT, dtype: int64

CHCHD10
False    183
Name: CHCHD10, dtype: int64

CHCHD1
False    183
Name: CHCHD1, dtype: int64

CHCHD2
False    183
Name: CHCHD2, dtype: int64

CHCHD3
False    183
Name: CHCHD3, dtype: int64

CHCHD4
False    183
Name: CHCHD4, dtype: int64

CHCHD5
False    183
Name: CHCHD5, dtype: int64

CHCHD6
False    183
Name: CHCHD6, dtype: int64

CHCHD7
False    183
Name: CHCHD7, dtype: int64

CHCHD8
False    183
Name: CHCHD8, dtype: int64

CHD1L
False    183
Name: CHD1L, dtype: int64

CHD1
False    183
Name: CHD1, dtype: int64

CHD2
False    183
Name: CHD2, dtype: int64

CHD3
False    183
Name: CHD3, dtype: int64

CHD4
False    183
Name: CHD4, dtype: int64

CHD5
False    182
True       1
Name: CHD5, dtype: int64

CHD6
False    183
Name: CHD6, dtype: int64

CHD7
False    183
Name: CHD7, dtype: int64

CHD8
False    183
Name: CHD8, dtype: int64

CHD9
False    183
Name: CHD9, dtype: int64

CHDH
False    183
Name: CHDH, dtype: int64

CHEK1
False    183
Name: CHEK1, dtype: int64

CHEK2
False    183
Name: CHEK2, dtype: int64

CHERP
False    183
Name: CHERP, dtype: int64

CHFR
False    183
Name: CHFR, dtype: int64

CHGA
False    182
True       1
Name: CHGA, dtype: int64

CHGB
False    183
Name: CHGB, dtype: int64

CHI3L1
False    183
Name: CHI3L1, dtype: int64

CHI3L2
False    182
True       1
Name: CHI3L2, dtype: int64

CHIC1
False    183
Name: CHIC1, dtype: int64

CHIC2
False    183
Name: CHIC2, dtype: int64

CHID1
False    183
Name: CHID1, dtype: int64

CHIT1
False    183
Name: CHIT1, dtype: int64

CHKA
False    183
Name: CHKA, dtype: int64

CHKB-CPT1B
False    183
Name: CHKB-CPT1B, dtype: int64

CHKB
False    183
Name: CHKB, dtype: int64

CHL1
False    182
True       1
Name: CHL1, dtype: int64

CHML
False    183
Name: CHML, dtype: int64

CHMP1A
False    183
Name: CHMP1A, dtype: int64

CHMP1B
False    183
Name: CHMP1B, dtype: int64

CHMP2A
False    183
Name: CHMP2A, dtype: int64

CHMP2B
False    183
Name: CHMP2B, dtype: int64

CHMP4A
False    183
Name: CHMP4A, dtype: int64

CHMP4B
False    183
Name: CHMP4B, dtype: int64

CHMP4C
False    183
Name: CHMP4C, dtype: int64

CHMP5
False    183
Name: CHMP5, dtype: int64

CHMP6
False    183
Name: CHMP6, dtype: int64

CHMP7
False    183
Name: CHMP7, dtype: int64

CHM
False    183
Name: CHM, dtype: int64

CHN1
False    183
Name: CHN1, dtype: int64

CHN2
False    183
Name: CHN2, dtype: int64

CHODL
False    176
True       7
Name: CHODL, dtype: int64

CHORDC1
False    183
Name: CHORDC1, dtype: int64

CHP2
False    150
True      33
Name: CHP2, dtype: int64

CHPF2
False    183
Name: CHPF2, dtype: int64

CHPF
False    183
Name: CHPF, dtype: int64

CHPT1
False    183
Name: CHPT1, dtype: int64

CHP
False    183
Name: CHP, dtype: int64

CHRAC1
False    183
Name: CHRAC1, dtype: int64

CHRDL1
False    182
True       1
Name: CHRDL1, dtype: int64

CHRDL2
False    179
True       4
Name: CHRDL2, dtype: int64

CHRD
False    183
Name: CHRD, dtype: int64

CHRFAM7A
False    183
Name: CHRFAM7A, dtype: int64

CHRM1
False    167
True      16
Name: CHRM1, dtype: int64

CHRM2
True     92
False    91
Name: CHRM2, dtype: int64

CHRM3
False    183
Name: CHRM3, dtype: int64

CHRM4
False    181
True       2
Name: CHRM4, dtype: int64

CHRM5
False    178
True       5
Name: CHRM5, dtype: int64

CHRNA10
False    183
Name: CHRNA10, dtype: int64

CHRNA1
False    177
True       6
Name: CHRNA1, dtype: int64

CHRNA2
False    108
True      75
Name: CHRNA2, dtype: int64

CHRNA3
False    183
Name: CHRNA3, dtype: int64

CHRNA4
False    92
True     91
Name: CHRNA4, dtype: int64

CHRNA5
False    183
Name: CHRNA5, dtype: int64

CHRNA6
False    159
True      24
Name: CHRNA6, dtype: int64

CHRNA7
False    178
True       5
Name: CHRNA7, dtype: int64

CHRNA9
False    108
True      75
Name: CHRNA9, dtype: int64

CHRNB1
False    183
Name: CHRNB1, dtype: int64

CHRNB2
False    183
Name: CHRNB2, dtype: int64

CHRNB3
False    103
True      80
Name: CHRNB3, dtype: int64

CHRNB4
False    179
True       4
Name: CHRNB4, dtype: int64

CHRNE
False    183
Name: CHRNE, dtype: int64

CHRNG
False    118
True      65
Name: CHRNG, dtype: int64

CHST10
False    183
Name: CHST10, dtype: int64

CHST11
False    183
Name: CHST11, dtype: int64

CHST12
False    183
Name: CHST12, dtype: int64

CHST13
False    179
True       4
Name: CHST13, dtype: int64

CHST14
False    183
Name: CHST14, dtype: int64

CHST15
False    183
Name: CHST15, dtype: int64

CHST1
False    183
Name: CHST1, dtype: int64

CHST2
False    183
Name: CHST2, dtype: int64

CHST3
False    183
Name: CHST3, dtype: int64

CHST4
False    178
True       5
Name: CHST4, dtype: int64

CHST5
False    182
True       1
Name: CHST5, dtype: int64

CHST6
False    182
True       1
Name: CHST6, dtype: int64

CHST7
False    183
Name: CHST7, dtype: int64

CHST8
False    182
True       1
Name: CHST8, dtype: int64

CHST9
False    178
True       5
Name: CHST9, dtype: int64

CHSY1
False    183
Name: CHSY1, dtype: int64

CHSY3
False    183
Name: CHSY3, dtype: int64

CHTF18
False    183
Name: CHTF18, dtype: int64

CHTF8
False    183
Name: CHTF8, dtype: int64

CHUK
False    183
Name: CHUK, dtype: int64

CHURC1
False    183
Name: CHURC1, dtype: int64

CIAO1
False    183
Name: CIAO1, dtype: int64

CIAPIN1
False    183
Name: CIAPIN1, dtype: int64

CIB1
False    183
Name: CIB1, dtype: int64

CIB2
False    183
Name: CIB2, dtype: int64

CIB3
True     125
False     58
Name: CIB3, dtype: int64

CIC
False    183
Name: CIC, dtype: int64

CIDEA
False    108
True      75
Name: CIDEA, dtype: int64

CIDEB
False    183
Name: CIDEB, dtype: int64

CIDECP
False    183
Name: CIDECP, dtype: int64

CIDEC
False    176
True       7
Name: CIDEC, dtype: int64

CIITA
False    183
Name: CIITA, dtype: int64

CILP2
False    183
Name: CILP2, dtype: int64

CILP
False    183
Name: CILP, dtype: int64

CINP
False    183
Name: CINP, dtype: int64

CIR1
False    183
Name: CIR1, dtype: int64

CIRBP
False    183
Name: CIRBP, dtype: int64

CIRH1A
False    183
Name: CIRH1A, dtype: int64

CISD1
False    183
Name: CISD1, dtype: int64

CISD2
False    183
Name: CISD2, dtype: int64

CISD3
False    183
Name: CISD3, dtype: int64

CISH
False    183
Name: CISH, dtype: int64

CITED1
False    183
Name: CITED1, dtype: int64

CITED2
False    183
Name: CITED2, dtype: int64

CITED4
False    183
Name: CITED4, dtype: int64

CIT
False    183
Name: CIT, dtype: int64

CIZ1
False    183
Name: CIZ1, dtype: int64

CKAP2L
False    183
Name: CKAP2L, dtype: int64

CKAP2
False    183
Name: CKAP2, dtype: int64

CKAP4
False    183
Name: CKAP4, dtype: int64

CKAP5
False    183
Name: CKAP5, dtype: int64

CKB
False    183
Name: CKB, dtype: int64

CKLF
False    183
Name: CKLF, dtype: int64

CKMT1A
False    183
Name: CKMT1A, dtype: int64

CKMT1B
False    183
Name: CKMT1B, dtype: int64

CKMT2
False    182
True       1
Name: CKMT2, dtype: int64

CKM
False    164
True      19
Name: CKM, dtype: int64

CKS1B
False    183
Name: CKS1B, dtype: int64

CKS2
False    183
Name: CKS2, dtype: int64

CLASP1
False    183
Name: CLASP1, dtype: int64

CLASP2
False    183
Name: CLASP2, dtype: int64

CLCA1
False    134
True      49
Name: CLCA1, dtype: int64

CLCA2
False    162
True      21
Name: CLCA2, dtype: int64

CLCA3P
False    129
True      54
Name: CLCA3P, dtype: int64

CLCA4
False    152
True      31
Name: CLCA4, dtype: int64

CLCC1
False    183
Name: CLCC1, dtype: int64

CLCF1
False    183
Name: CLCF1, dtype: int64

CLCN1

False    177
True       6
Name: CLCN1, dtype: int64

CLCN2
False    183
Name: CLCN2, dtype: int64

CLCN3
False    183
Name: CLCN3, dtype: int64

CLCN4
False    183
Name: CLCN4, dtype: int64

CLCN5
False    183
Name: CLCN5, dtype: int64

CLCN6
False    183
Name: CLCN6, dtype: int64

CLCN7
False    183
Name: CLCN7, dtype: int64

CLCNKA
False    179
True       4
Name: CLCNKA, dtype: int64

CLCNKB
False    177
True       6
Name: CLCNKB, dtype: int64

CLC
False    117
True      66
Name: CLC, dtype: int64

CLDN10
False    181
True       2
Name: CLDN10, dtype: int64

CLDN11
False    183
Name: CLDN11, dtype: int64

CLDN12
False    183
Name: CLDN12, dtype: int64

CLDN14
False    180
True       3
Name: CLDN14, dtype: int64

CLDN15
False    183
Name: CLDN15, dtype: int64

CLDN16
False    171
True      12
Name: CLDN16, dtype: int64

CLDN18
False    180
True       3
Name: CLDN18, dtype: int64

CLDN19
False    100
True      83
Name: CLDN19, dtype: int64

CLDN1
False    183
Name: CLDN1, dtype: int64

CLDN20
False    161
True      22
Name: CLDN20, dtype: int64

CLDN23
False    183
Name: CLDN23, dtype: int64

CLDN2
False    182
True       1
Name: CLDN2, dtype: int64

CLDN3
False    182
True       1
Name: CLDN3, dtype: int64

CLDN4
False    183
Name: CLDN4, dtype: int64

CLDN5
False    183
Name: CLDN5, dtype: int64

CLDN6
False    175
True       8
Name: CLDN6, dtype: int64

CLDN7
False    183
Name: CLDN7, dtype: int64

CLDN8
False    143
True      40
Name: CLDN8, dtype: int64

CLDN9
False    183
Name: CLDN9, dtype: int64

CLDND1
False    183
Name: CLDND1, dtype: int64

CLDND2
False    181
True       2
Name: CLDND2, dtype: int64

CLEC10A
False    183
Name: CLEC10A, dtype: int64

CLEC11A
False    183
Name: CLEC11A, dtype: int64

CLEC12A
False    181
True       2
Name: CLEC12A, dtype: int64

CLEC12B
False    156
True      27
Name: CLEC12B, dtype: int64

CLEC14A
False    183
Name: CLEC14A, dtype: int64

CLEC16A
False    183
Name: CLEC16A, dtype: int64

CLEC17A
False    165
True      18
Name: CLEC17A, dtype: int64

CLEC18A
False    183
Name: CLEC18A, dtype: int64

CLEC18B
False    179
True       4
Name: CLEC18B, dtype: int64

CLEC18C
False    150
True      33
Name: CLEC18C, dtype: int64

CLEC1A
False    183
Name: CLEC1A, dtype: int64

CLEC2B
False    183
Name: CLEC2B, dtype: int64

CLEC2D
False    183
Name: CLEC2D, dtype: int64

CLEC2L
False    176
True       7
Name: CLEC2L, dtype: int64

CLEC3B
False    183
Name: CLEC3B, dtype: int64

CLEC4A
False    183
Name: CLEC4A, dtype: int64

CLEC4C
True     99
False    84
Name: CLEC4C, dtype: int64

CLEC4D
False    166
True      17
Name: CLEC4D, dtype: int64

CLEC4E
False    183
Name: CLEC4E, dtype: int64

CLEC4F
False    173
True      10
Name: CLEC4F, dtype: int64

CLEC4GP1
False    132
True      51
Name: CLEC4GP1, dtype: int64

CLEC4G
False    165
True      18
Name: CLEC4G, dtype: int64

CLEC4M
True     112
False     71
Name: CLEC4M, dtype: int64

CLEC5A
False    183
Name: CLEC5A, dtype: int64

CLEC6A
False    119
True      64
Name: CLEC6A, dtype: int64

CLEC7A
False    183
Name: CLEC7A, dtype: int64

CLEC9A
False    173
True      10
Name: CLEC9A, dtype: int64

CLECL1
False    179
True       4
Name: CLECL1, dtype: int64

CLGN
False    182
True       1
Name: CLGN, dtype: int64

CLIC1
False    183
Name: CLIC1, dtype: int64

CLIC2
False    183
Name: CLIC2, dtype: int64

CLIC3
False    183
Name: CLIC3, dtype: int64

CLIC4
False    183
Name: CLIC4, dtype: int64

CLIC5
False    183
Name: CLIC5, dtype: int64

CLIC6
False    183
Name: CLIC6, dtype: int64

CLINT1
False    183
Name: CLINT1, dtype: int64

CLIP1
False    183
Name: CLIP1, dtype: int64

CLIP2
False    183
Name: CLIP2, dtype: int64

CLIP3
False    183
Name: CLIP3, dtype: int64

CLIP4
False    183
Name: CLIP4, dtype: int64

CLK1
False    183
Name: CLK1, dtype: int64

CLK2P
False    183
Name: CLK2P, dtype: int64

CLK2
False    183
Name: CLK2, dtype: int64

CLK3
False    183
Name: CLK3, dtype: int64

CLK4
False    183
Name: CLK4, dtype: int64

CLLU1OS
False    107
True      76
Name: CLLU1OS, dtype: int64

CLLU1
False    131
True      52
Name: CLLU1, dtype: int64

CLMN
False    183
Name: CLMN, dtype: int64

CLN3
False    183
Name: CLN3, dtype: int64

CLN5
False    183
Name: CLN5, dtype: int64

CLN6
False    183
Name: CLN6, dtype: int64

CLN8
False    183
Name: CLN8, dtype: int64

CLNK
False    139
True      44
Name: CLNK, dtype: int64

CLNS1A
False    183
Name: CLNS1A, dtype: int64

CLOCK
False    183
Name: CLOCK, dtype: int64

CLP1
False    183
Name: CLP1, dtype: int64

CLPB
False    183
Name: CLPB, dtype: int64

CLPP
False    183
Name: CLPP, dtype: int64

CLPS
False    165
True      18
Name: CLPS, dtype: int64

CLPTM1L
False    183
Name: CLPTM1L, dtype: int64

CLPTM1
False    183
Name: CLPTM1, dtype: int64

CLPX
False    183
Name: CLPX, dtype: int64

CLRN3
False    183
Name: CLRN3, dtype: int64

CLSPN
False    182
True       1
Name: CLSPN, dtype: int64

CLSTN1
False    183
Name: CLSTN1, dtype: int64

CLSTN2
False    183
Name: CLSTN2, dtype: int64

CLSTN3
False    183
Name: CLSTN3, dtype: int64

CLTA
False    183
Name: CLTA, dtype: int64

CLTB
False    183
Name: CLTB, dtype: int64

CLTCL1
False    183
Name: CLTCL1, dtype: int64

CLTC
False    183
Name: CLTC, dtype: int64

CLUAP1
False    183
Name: CLUAP1, dtype: int64

CLUL1
False    178
True       5
Name: CLUL1, dtype: int64

CLU
False    183
Name: CLU, dtype: int64

CLVS1
False    177
True       6
Name: CLVS1, dtype: int64

CLVS2
True     92
False    91
Name: CLVS2, dtype: int64

CLYBL
False    183
Name: CLYBL, dtype: int64

CMA1
False    129
True      54
Name: CMA1, dtype: int64

CMAH
False    183
Name: CMAH, dtype: int64

CMAS
False    183
Name: CMAS, dtype: int64

CMBL
False    183
Name: CMBL, dtype: int64

CMC1
False    183
Name: CMC1, dtype: int64

CMIP
False    183
Name: CMIP, dtype: int64

CMKLR1
False    183
Name: CMKLR1, dtype: int64

CMPK1
False    183
Name: CMPK1, dtype: int64

CMPK2
False    183
Name: CMPK2, dtype: int64

CMTM1
False    183
Name: CMTM1, dtype: int64

CMTM2
False    181
True       2
Name: CMTM2, dtype: int64

CMTM3
False    183
Name: CMTM3, dtype: int64

CMTM4
False    183
Name: CMTM4, dtype: int64

CMTM5
False    158
True      25
Name: CMTM5, dtype: int64

CMTM6
False    183
Name: CMTM6, dtype: int64

CMTM7
False    183
Name: CMTM7, dtype: int64

CMTM8
False    183
Name: CMTM8, dtype: int64

CMYA5
False    183
Name: CMYA5, dtype: int64

CN5H6.4
False    183
Name: CN5H6.4, dtype: int64

CNBP
False    183
Name: CNBP, dtype: int64

CNDP1
False    160
True      23
Name: CNDP1, dtype: int64

CNDP2
False    183
Name: CNDP2, dtype: int64

CNFN
False    183
Name: CNFN, dtype: int64

CNGA1
False    183
Name: CNGA1, dtype: int64

CNGA3
False    178
True       5
Name: CNGA3, dtype: int64

CNGA4
False    179
True       4
Name: CNGA4, dtype: int64

CNGB1
False    150
True      33
Name: CNGB1, dtype: int64

CNGB3
True     105
False     78
Name: CNGB3, dtype: int64

CNIH2
False    183
Name: CNIH2, dtype: int64

CNIH3
False    183
Name: CNIH3, dtype: int64

CNIH4
False    183
Name: CNIH4, dtype: int64

CNIH
False    183
Name: CNIH, dtype: int64

CNKSR1
False    183
Name: CNKSR1, dtype: int64

CNKSR2
False    180
True       3
Name: CNKSR2, dtype: int64

CNKSR3
False    183
Name: CNKSR3, dtype: int64

CNN1
False    183
Name: CNN1, dtype: int64

CNN2
False    183
Name: CNN2, dtype: int64

CNN3
False    183
Name: CNN3, dtype: int64

CNNM1
False    183
Name: CNNM1, dtype: int64

CNNM2
False    183
Name: CNNM2, dtype: int64

CNNM3
False    183
Name: CNNM3, dtype: int64

CNNM4
False    183
Name: CNNM4, dtype: int64

CNOT10
False    183
Name: CNOT10, dtype: int64

CNOT1
False    183
Name: CNOT1, dtype: int64

CNOT2
False    183
Name: CNOT2, dtype: int64

CNOT3
False    183
Name: CNOT3, dtype: int64

CNOT4
False    183
Name: CNOT4, dtype: int64

CNOT6L
False    183
Name: CNOT6L, dtype: int64

CNOT6
False    183
Name: CNOT6, dtype: int64

CNOT7
False    183
Name: CNOT7, dtype: int64

CNOT8
False    183
Name: CNOT8, dtype: int64

CNO
False    183
Name: CNO, dtype: int64

CNPY1
False    92
True     91
Name: CNPY1, dtype: int64

CNPY2
False    183
Name: CNPY2, dtype: int64

CNPY3
False    183
Name: CNPY3, dtype: int64

CNPY4
False    183
Name: CNPY4, dtype: int64

CNP
False    183
Name: CNP, dtype: int64

CNR1
False    183
Name: CNR1, dtype: int64

CNR2
False    151
True      32
Name: CNR2, dtype: int64

CNRIP1
False    183
Name: CNRIP1, dtype: int64

CNST
False    183
Name: CNST, dtype: int64

CNTD1
False    183
Name: CNTD1, dtype: int64

CNTD2
False    181
True       2
Name: CNTD2, dtype: int64

CNTFR
False    178
True       5
Name: CNTFR, dtype: int64

CNTF
False    180
True       3
Name: CNTF, dtype: int64

CNTLN
False    183
Name: CNTLN, dtype: int64

CNTN1
False    182
True       1
Name: CNTN1, dtype: int64

CNTN2
False    177
True       6
Name: CNTN2, dtype: int64

CNTN3
False    182
True       1
Name: CNTN3, dtype: int64

CNTN4
False    183
Name: CNTN4, dtype: int64

CNTN5

False    149
True      34
Name: CNTN5, dtype: int64

CNTN6
False    106
True      77
Name: CNTN6, dtype: int64

CNTNAP1
False    183
Name: CNTNAP1, dtype: int64

CNTNAP2
False    183
Name: CNTNAP2, dtype: int64

CNTNAP3
False    183
Name: CNTNAP3, dtype: int64

CNTNAP4
False    109
True      74
Name: CNTNAP4, dtype: int64

CNTNAP5
False    139
True      44
Name: CNTNAP5, dtype: int64

CNTROB
False    183
Name: CNTROB, dtype: int64

COASY
False    183
Name: COASY, dtype: int64

COBLL1
False    183
Name: COBLL1, dtype: int64

COBL
False    183
Name: COBL, dtype: int64

COBRA1
False    183
Name: COBRA1, dtype: int64

COCH
False    183
Name: COCH, dtype: int64

COG1
False    183
Name: COG1, dtype: int64

COG2
False    183
Name: COG2, dtype: int64

COG3
False    183
Name: COG3, dtype: int64

COG4
False    183
Name: COG4, dtype: int64

COG5
False    183
Name: COG5, dtype: int64

COG6
False    183
Name: COG6, dtype: int64

COG7
False    183
Name: COG7, dtype: int64

COG8
False    183
Name: COG8, dtype: int64

COIL
False    183
Name: COIL, dtype: int64

COL10A1
False    183
Name: COL10A1, dtype: int64

COL11A1
False    180
True       3
Name: COL11A1, dtype: int64

COL11A2
False    183
Name: COL11A2, dtype: int64

COL12A1
False    183
Name: COL12A1, dtype: int64

COL13A1
False    183
Name: COL13A1, dtype: int64

COL14A1
False    183
Name: COL14A1, dtype: int64

COL15A1
False    183
Name: COL15A1, dtype: int64

COL16A1
False    183
Name: COL16A1, dtype: int64

COL17A1
False    183
Name: COL17A1, dtype: int64

COL18A1
False    183
Name: COL18A1, dtype: int64

COL19A1
False    154
True      29
Name: COL19A1, dtype: int64

COL1A1
False    183
Name: COL1A1, dtype: int64

COL1A2
False    183
Name: COL1A2, dtype: int64

COL20A1
True     104
False     79
Name: COL20A1, dtype: int64

COL21A1
False    183
Name: COL21A1, dtype: int64

COL22A1
False    183
Name: COL22A1, dtype: int64

COL23A1
False    183
Name: COL23A1, dtype: int64

COL24A1
False    182
True       1
Name: COL24A1, dtype: int64

COL25A1
False    179
True       4
Name: COL25A1, dtype: int64

COL27A1
False    183
Name: COL27A1, dtype: int64

COL28A1
False    181
True       2
Name: COL28A1, dtype: int64

COL29A1
False    167
True      16
Name: COL29A1, dtype: int64

COL2A1
False    144
True      39
Name: COL2A1, dtype: int64

COL3A1
False    183
Name: COL3A1, dtype: int64

COL4A1
False    183
Name: COL4A1, dtype: int64

COL4A2
False    183
Name: COL4A2, dtype: int64

COL4A3BP
False    183
Name: COL4A3BP, dtype: int64

COL4A3
False    180
True       3
Name: COL4A3, dtype: int64

COL4A4
False    183
Name: COL4A4, dtype: int64

COL4A5
False    183
Name: COL4A5, dtype: int64

COL4A6
False    183
Name: COL4A6, dtype: int64

COL5A1
False    183
Name: COL5A1, dtype: int64

COL5A2
False    183
Name: COL5A2, dtype: int64

COL5A3
False    183
Name: COL5A3, dtype: int64

COL6A1
False    183
Name: COL6A1, dtype: int64

COL6A2
False    183
Name: COL6A2, dtype: int64

COL6A3
False    183
Name: COL6A3, dtype: int64

COL6A4P2
False    180
True       3
Name: COL6A4P2, dtype: int64

COL6A6
False    179
True       4
Name: COL6A6, dtype: int64

COL7A1
False    183
Name: COL7A1, dtype: int64

COL8A1
False    183
Name: COL8A1, dtype: int64

COL8A2
False    183
Name: COL8A2, dtype: int64

COL9A1
False    181
True       2
Name: COL9A1, dtype: int64

COL9A2
False    183
Name: COL9A2, dtype: int64

COL9A3
False    183
Name: COL9A3, dtype: int64

COLEC10
False    176
True       7
Name: COLEC10, dtype: int64

COLEC11
False    183
Name: COLEC11, dtype: int64

COLEC12
False    183
Name: COLEC12, dtype: int64

COLQ
False    183
Name: COLQ, dtype: int64

COMMD10
False    183
Name: COMMD10, dtype: int64

COMMD1
False    183
Name: COMMD1, dtype: int64

COMMD2
False    183
Name: COMMD2, dtype: int64

COMMD3
False    183
Name: COMMD3, dtype: int64

COMMD4
False    183
Name: COMMD4, dtype: int64

COMMD5
False    183
Name: COMMD5, dtype: int64

COMMD6
False    183
Name: COMMD6, dtype: int64

COMMD7
False    183
Name: COMMD7, dtype: int64

COMMD8
False    183
Name: COMMD8, dtype: int64

COMMD9
False    183
Name: COMMD9, dtype: int64

COMP
False    181
True       2
Name: COMP, dtype: int64

COMTD1
False    183
Name: COMTD1, dtype: int64

COMT
False    183
Name: COMT, dtype: int64

COPA
False    183
Name: COPA, dtype: int64

COPB1
False    183
Name: COPB1, dtype: int64

COPB2
False    183
Name: COPB2, dtype: int64

COPE
False    183
Name: COPE, dtype: int64

COPG2
False    183
Name: COPG2, dtype: int64

COPG
False    183
Name: COPG, dtype: int64

COPS2
False    183
Name: COPS2, dtype: int64

COPS3
False    183
Name: COPS3, dtype: int64

COPS4
False    183
Name: COPS4, dtype: int64

COPS5
False    183
Name: COPS5, dtype: int64

COPS6
False    183
Name: COPS6, dtype: int64

COPS7A
False    183
Name: COPS7A, dtype: int64

COPS7B
False    183
Name: COPS7B, dtype: int64

COPS8
False    183
Name: COPS8, dtype: int64

COPZ1
False    183
Name: COPZ1, dtype: int64

COPZ2
False    183
Name: COPZ2, dtype: int64

COQ10A
False    183
Name: COQ10A, dtype: int64

COQ10B
False    183
Name: COQ10B, dtype: int64

COQ2
False    183
Name: COQ2, dtype: int64

COQ3
False    183
Name: COQ3, dtype: int64

COQ4
False    183
Name: COQ4, dtype: int64

COQ5
False    183
Name: COQ5, dtype: int64

COQ6
False    183
Name: COQ6, dtype: int64

COQ7
False    183
Name: COQ7, dtype: int64

COQ9
False    183
Name: COQ9, dtype: int64

CORIN
False    183
Name: CORIN, dtype: int64

CORO1A
False    183
Name: CORO1A, dtype: int64

CORO1B
False    183
Name: CORO1B, dtype: int64

CORO1C
False    183
Name: CORO1C, dtype: int64

CORO2A
False    183
Name: CORO2A, dtype: int64

CORO2B
False    183
Name: CORO2B, dtype: int64

CORO6
False    183
Name: CORO6, dtype: int64

CORO7
False    183
Name: CORO7, dtype: int64

CORT
False    180
True       3
Name: CORT, dtype: int64

COTL1
False    183
Name: COTL1, dtype: int64

COX10
False    183
Name: COX10, dtype: int64

COX11
False    183
Name: COX11, dtype: int64

COX15
False    183
Name: COX15, dtype: int64

COX16
False    183
Name: COX16, dtype: int64

COX17
False    183
Name: COX17, dtype: int64

COX18
False    183
Name: COX18, dtype: int64

COX19
False    183
Name: COX19, dtype: int64

COX4I1
False    183
Name: COX4I1, dtype: int64

COX4I2
False    183
Name: COX4I2, dtype: int64

COX4NB
False    183
Name: COX4NB, dtype: int64

COX5A
False    183
Name: COX5A, dtype: int64

COX5B
False    183
Name: COX5B, dtype: int64

COX6A1
False    183
Name: COX6A1, dtype: int64

COX6A2
True     103
False     80
Name: COX6A2, dtype: int64

COX6B1
False    183
Name: COX6B1, dtype: int64

COX6B2
False    182
True       1
Name: COX6B2, dtype: int64

COX6C
False    183
Name: COX6C, dtype: int64

COX7A1
False    183
Name: COX7A1, dtype: int64

COX7A2L
False    183
Name: COX7A2L, dtype: int64

COX7A2
False    183
Name: COX7A2, dtype: int64

COX7B
False    183
Name: COX7B, dtype: int64

COX7C
False    183
Name: COX7C, dtype: int64

COX8A
False    183
Name: COX8A, dtype: int64

CP110
False    183
Name: CP110, dtype: int64

CPA1
False    178
True       5
Name: CPA1, dtype: int64

CPA2
False    169
True      14
Name: CPA2, dtype: int64

CPA3
False    183
Name: CPA3, dtype: int64

CPA4
False    182
True       1
Name: CPA4, dtype: int64

CPA5
False    105
True      78
Name: CPA5, dtype: int64

CPA6
False    160
True      23
Name: CPA6, dtype: int64

CPAMD8
False    183
Name: CPAMD8, dtype: int64

CPB1
False    177
True       6
Name: CPB1, dtype: int64

CPB2
False    138
True      45
Name: CPB2, dtype: int64

CPD
False    183
Name: CPD, dtype: int64

CPEB1
False    181
True       2
Name: CPEB1, dtype: int64

CPEB2
False    183
Name: CPEB2, dtype: int64

CPEB3
False    183
Name: CPEB3, dtype: int64

CPEB4
False    183
Name: CPEB4, dtype: int64

CPE
False    183
Name: CPE, dtype: int64

CPLX1
False    183
Name: CPLX1, dtype: int64

CPLX2
False    181
True       2
Name: CPLX2, dtype: int64

CPLX3
False    123
True      60
Name: CPLX3, dtype: int64

CPLX4
True     125
False     58
Name: CPLX4, dtype: int64

CPM
False    183
Name: CPM, dtype: int64

CPN1
True     95
False    88
Name: CPN1, dtype: int64

CPN2
False    148
True      35
Name: CPN2, dtype: int64

CPNE1
False    183
Name: CPNE1, dtype: int64

CPNE2
False    183
Name: CPNE2, dtype: int64

CPNE3
False    183
Name: CPNE3, dtype: int64

CPNE4
False    176
True       7
Name: CPNE4, dtype: int64

CPNE5
False    183
Name: CPNE5, dtype: int64

CPNE6
False    132
True      51
Name: CPNE6, dtype: int64

CPNE7
False    183
Name: CPNE7, dtype: int64

CPNE8
False    183
Name: CPNE8, dtype: int64

CPNE9
False    172
True      11
Name: CPNE9, dtype: int64

CPOX
False    183
Name: CPOX, dtype: int64

CPO
False    167
True      16
Name: CPO, dtype: int64

CPPED1
False    183
Name: CPPED1, dtype: int64

CPS1
False    183
Name: CPS1, dtype: int64

CPSF1

False    183
Name: CPSF1, dtype: int64

CPSF2
False    183
Name: CPSF2, dtype: int64

CPSF3L
False    183
Name: CPSF3L, dtype: int64

CPSF3
False    183
Name: CPSF3, dtype: int64

CPSF4L
False    96
True     87
Name: CPSF4L, dtype: int64

CPSF4
False    183
Name: CPSF4, dtype: int64

CPSF6
False    183
Name: CPSF6, dtype: int64

CPSF7
False    183
Name: CPSF7, dtype: int64

CPT1A
False    183
Name: CPT1A, dtype: int64

CPT1B
False    183
Name: CPT1B, dtype: int64

CPT1C
False    183
Name: CPT1C, dtype: int64

CPT2
False    183
Name: CPT2, dtype: int64

CPVL
False    183
Name: CPVL, dtype: int64

CPXM1
False    183
Name: CPXM1, dtype: int64

CPXM2
False    183
Name: CPXM2, dtype: int64

CPZ
False    183
Name: CPZ, dtype: int64

CP
False    183
Name: CP, dtype: int64

CR1L
False    126
True      57
Name: CR1L, dtype: int64

CR1
False    183
Name: CR1, dtype: int64

CR2
False    174
True       9
Name: CR2, dtype: int64

CRABP1
False    169
True      14
Name: CRABP1, dtype: int64

CRABP2
False    183
Name: CRABP2, dtype: int64

CRADD
False    183
Name: CRADD, dtype: int64

CRAMP1L
False    183
Name: CRAMP1L, dtype: int64

CRAT
False    183
Name: CRAT, dtype: int64

CRB1
False    150
True      33
Name: CRB1, dtype: int64

CRB2
False    171
True      12
Name: CRB2, dtype: int64

CRB3
False    183
Name: CRB3, dtype: int64

CRBN
False    183
Name: CRBN, dtype: int64

CRCP
False    183
Name: CRCP, dtype: int64

CRCT1
False    152
True      31
Name: CRCT1, dtype: int64

CREB1
False    183
Name: CREB1, dtype: int64

CREB3L1
False    183
Name: CREB3L1, dtype: int64

CREB3L2
False    183
Name: CREB3L2, dtype: int64

CREB3L3
False    175
True       8
Name: CREB3L3, dtype: int64

CREB3L4
False    183
Name: CREB3L4, dtype: int64

CREB3
False    183
Name: CREB3, dtype: int64

CREB5
False    183
Name: CREB5, dtype: int64

CREBBP
False    183
Name: CREBBP, dtype: int64

CREBL2
False    183
Name: CREBL2, dtype: int64

CREBZF
False    183
Name: CREBZF, dtype: int64

CREG1
False    183
Name: CREG1, dtype: int64

CREG2
False    181
True       2
Name: CREG2, dtype: int64

CRELD1
False    183
Name: CRELD1, dtype: int64

CRELD2
False    183
Name: CRELD2, dtype: int64

CREM
False    183
Name: CREM, dtype: int64

CRHBP
False    176
True       7
Name: CRHBP, dtype: int64

CRHR1
False    147
True      36
Name: CRHR1, dtype: int64

CRHR2
False    128
True      55
Name: CRHR2, dtype: int64

CRH
False    138
True      45
Name: CRH, dtype: int64

CRIM1
False    183
Name: CRIM1, dtype: int64

CRIP1
False    183
Name: CRIP1, dtype: int64

CRIP2
False    183
Name: CRIP2, dtype: int64

CRIP3
False    175
True       8
Name: CRIP3, dtype: int64

CRIPAK
False    183
Name: CRIPAK, dtype: int64

CRIPT
False    183
Name: CRIPT, dtype: int64

CRISP2
False    156
True      27
Name: CRISP2, dtype: int64

CRISP3
False    177
True       6
Name: CRISP3, dtype: int64

CRISPLD1
False    183
Name: CRISPLD1, dtype: int64

CRISPLD2
False    183
Name: CRISPLD2, dtype: int64

CRKL
False    183
Name: CRKL, dtype: int64

CRK
False    183
Name: CRK, dtype: int64

CRLF1
False    182
True       1
Name: CRLF1, dtype: int64

CRLF2
False    129
True      54
Name: CRLF2, dtype: int64

CRLF3
False    183
Name: CRLF3, dtype: int64

CRLS1
False    183
Name: CRLS1, dtype: int64

CRMP1
False    183
Name: CRMP1, dtype: int64

CRNKL1
False    183
Name: CRNKL1, dtype: int64

CROCCL1
False    183
Name: CROCCL1, dtype: int64

CROCCL2
False    183
Name: CROCCL2, dtype: int64

CROCC
False    183
Name: CROCC, dtype: int64

CROT
False    183
Name: CROT, dtype: int64

CRP
False    177
True       6
Name: CRP, dtype: int64

CRTAC1
False    183
Name: CRTAC1, dtype: int64

CRTAM
False    183
Name: CRTAM, dtype: int64

CRTAP
False    183
Name: CRTAP, dtype: int64

CRTC1
False    183
Name: CRTC1, dtype: int64

CRTC2
False    183
Name: CRTC2, dtype: int64

CRTC3
False    183
Name: CRTC3, dtype: int64

CRY1
False    183
Name: CRY1, dtype: int64

CRY2
False    183
Name: CRY2, dtype: int64

CRYAA
True     106
False     77
Name: CRYAA, dtype: int64

CRYAB
False    183
Name: CRYAB, dtype: int64

CRYBA2
False    174
True       9
Name: CRYBA2, dtype: int64

CRYBA4
False    100
True      83
Name: CRYBA4, dtype: int64

CRYBB1
False    179
True       4
Name: CRYBB1, dtype: int64

CRYBB2
False    166
True      17
Name: CRYBB2, dtype: int64

CRYBB3
False    159
True      24
Name: CRYBB3, dtype: int64

CRYBG3
False    183
Name: CRYBG3, dtype: int64

CRYGD
False    106
True      77
Name: CRYGD, dtype: int64

CRYGN
False    169
True      14
Name: CRYGN, dtype: int64

CRYGS
False    183
Name: CRYGS, dtype: int64

CRYL1
False    183
Name: CRYL1, dtype: int64

CRYM
False    183
Name: CRYM, dtype: int64

CRYZL1
False    183
Name: CRYZL1, dtype: int64

CRYZ
False    183
Name: CRYZ, dtype: int64

CSAD
False    183
Name: CSAD, dtype: int64

CSAG1
False    118
True      65
Name: CSAG1, dtype: int64

CSAG3
False    97
True     86
Name: CSAG3, dtype: int64

CSDAP1
False    183
Name: CSDAP1, dtype: int64

CSDA
False    183
Name: CSDA, dtype: int64

CSDC2
False    183
Name: CSDC2, dtype: int64

CSDE1
False    183
Name: CSDE1, dtype: int64

CSE1L
False    183
Name: CSE1L, dtype: int64

CSF1R
False    183
Name: CSF1R, dtype: int64

CSF1
False    183
Name: CSF1, dtype: int64

CSF2RA
False    183
Name: CSF2RA, dtype: int64

CSF2RB
False    183
Name: CSF2RB, dtype: int64

CSF2
False    176
True       7
Name: CSF2, dtype: int64

CSF3R
False    183
Name: CSF3R, dtype: int64

CSF3
False    160
True      23
Name: CSF3, dtype: int64

CSGALNACT1
False    183
Name: CSGALNACT1, dtype: int64

CSGALNACT2
False    183
Name: CSGALNACT2, dtype: int64

CSK
False    183
Name: CSK, dtype: int64

CSMD1
False    173
True      10
Name: CSMD1, dtype: int64

CSMD2
False    183
Name: CSMD2, dtype: int64

CSMD3
False    111
True      72
Name: CSMD3, dtype: int64

CSNK1A1L
False    170
True      13
Name: CSNK1A1L, dtype: int64

CSNK1A1P
False    126
True      57
Name: CSNK1A1P, dtype: int64

CSNK1A1
False    183
Name: CSNK1A1, dtype: int64

CSNK1D
False    183
Name: CSNK1D, dtype: int64

CSNK1E
False    183
Name: CSNK1E, dtype: int64

CSNK1G1
False    183
Name: CSNK1G1, dtype: int64

CSNK1G2
False    183
Name: CSNK1G2, dtype: int64

CSNK1G3
False    183
Name: CSNK1G3, dtype: int64

CSNK2A1P
False    183
Name: CSNK2A1P, dtype: int64

CSNK2A1
False    183
Name: CSNK2A1, dtype: int64

CSNK2A2
False    183
Name: CSNK2A2, dtype: int64

CSNK2B
False    183
Name: CSNK2B, dtype: int64

CSPG4
False    183
Name: CSPG4, dtype: int64

CSPG5
False    183
Name: CSPG5, dtype: int64

CSPP1
False    183
Name: CSPP1, dtype: int64

CSRNP1
False    183
Name: CSRNP1, dtype: int64

CSRNP2
False    183
Name: CSRNP2, dtype: int64

CSRNP3
False    182
True       1
Name: CSRNP3, dtype: int64

CSRP1
False    183
Name: CSRP1, dtype: int64

CSRP2BP
False    183
Name: CSRP2BP, dtype: int64

CSRP2
False    183
Name: CSRP2, dtype: int64

CST1
False    180
True       3
Name: CST1, dtype: int64

CST2
False    181
True       2
Name: CST2, dtype: int64

CST3
False    183
Name: CST3, dtype: int64

CST4
False    178
True       5
Name: CST4, dtype: int64

CST5
False    158
True      25
Name: CST5, dtype: int64

CST6
False    180
True       3
Name: CST6, dtype: int64

CST7
False    183
Name: CST7, dtype: int64

CSTA
False    183
Name: CSTA, dtype: int64

CSTB
False    183
Name: CSTB, dtype: int64

CSTF1
False    183
Name: CSTF1, dtype: int64

CSTF2T
False    183
Name: CSTF2T, dtype: int64

CSTF2
False    183
Name: CSTF2, dtype: int64

CSTF3
False    183
Name: CSTF3, dtype: int64

CSTL1
True     117
False     66
Name: CSTL1, dtype: int64

CS
False    183
Name: CS, dtype: int64

CT62
False    148
True      35
Name: CT62, dtype: int64

CTAGE1
False    183
Name: CTAGE1, dtype: int64

CTAGE4
False    183
Name: CTAGE4, dtype: int64

CTAGE5
False    183
Name: CTAGE5, dtype: int64

CTAGE6
False    179
True       4
Name: CTAGE6, dtype: int64

CTAGE9
False    183
Name: CTAGE9, dtype: int64

CTBP1
False    183
Name: CTBP1, dtype: int64

CTBP2
False    183
Name: CTBP2, dtype: int64

CTBS
False    183
Name: CTBS, dtype: int64

CTCFL
False    183
Name: CTCFL, dtype: int64

CTCF
False    183
Name: CTCF, dtype: int64

CTDP1
False    183
Name: CTDP1, dtype: int64

CTDSP1
False    183
Name: CTDSP1, dtype: int64

CTDSP2

False    183
Name: CTDSP2, dtype: int64

CTDSPL2
False    183
Name: CTDSPL2, dtype: int64

CTDSPL
False    183
Name: CTDSPL, dtype: int64

CTF1
False    183
Name: CTF1, dtype: int64

CTGF
False    183
Name: CTGF, dtype: int64

CTHRC1
False    183
Name: CTHRC1, dtype: int64

CTH
False    183
Name: CTH, dtype: int64

CTLA4
False    182
True       1
Name: CTLA4, dtype: int64

CTNNA1
False    183
Name: CTNNA1, dtype: int64

CTNNA2
False    179
True       4
Name: CTNNA2, dtype: int64

CTNNA3
False    157
True      26
Name: CTNNA3, dtype: int64

CTNNAL1
False    183
Name: CTNNAL1, dtype: int64

CTNNB1
False    183
Name: CTNNB1, dtype: int64

CTNNBIP1
False    183
Name: CTNNBIP1, dtype: int64

CTNNBL1
False    183
Name: CTNNBL1, dtype: int64

CTNND1
False    183
Name: CTNND1, dtype: int64

CTNND2
False    182
True       1
Name: CTNND2, dtype: int64

CTNS
False    183
Name: CTNS, dtype: int64

CTPS2
False    183
Name: CTPS2, dtype: int64

CTPS
False    183
Name: CTPS, dtype: int64

CTR9
False    183
Name: CTR9, dtype: int64

CTRB1
False    166
True      17
Name: CTRB1, dtype: int64

CTRB2
False    171
True      12
Name: CTRB2, dtype: int64

CTRC
False    176
True       7
Name: CTRC, dtype: int64

CTRL
False    183
Name: CTRL, dtype: int64

CTSA
False    183
Name: CTSA, dtype: int64

CTSB
False    183
Name: CTSB, dtype: int64

CTSC
False    183
Name: CTSC, dtype: int64

CTSD
False    183
Name: CTSD, dtype: int64

CTSE
False    182
True       1
Name: CTSE, dtype: int64

CTSF
False    183
Name: CTSF, dtype: int64

CTSG
False    177
True       6
Name: CTSG, dtype: int64

CTSH
False    183
Name: CTSH, dtype: int64

CTSK
False    183
Name: CTSK, dtype: int64

CTSL1
False    183
Name: CTSL1, dtype: int64

CTSL2
False    183
Name: CTSL2, dtype: int64

CTSO
False    183
Name: CTSO, dtype: int64

CTSS
False    183
Name: CTSS, dtype: int64

CTSW
False    183
Name: CTSW, dtype: int64

CTSZ
False    183
Name: CTSZ, dtype: int64

CTTNBP2NL
False    183
Name: CTTNBP2NL, dtype: int64

CTTNBP2
False    183
Name: CTTNBP2, dtype: int64

CTTN
False    183
Name: CTTN, dtype: int64

CTU1
False    183
Name: CTU1, dtype: int64

CTU2
False    183
Name: CTU2, dtype: int64

CTXN1
False    183
Name: CTXN1, dtype: int64

CTXN2
False    152
True      31
Name: CTXN2, dtype: int64

CUBN
False    183
Name: CUBN, dtype: int64

CUEDC1
False    183
Name: CUEDC1, dtype: int64

CUEDC2
False    183
Name: CUEDC2, dtype: int64

CUL1
False    183
Name: CUL1, dtype: int64

CUL2
False    183
Name: CUL2, dtype: int64

CUL3
False    183
Name: CUL3, dtype: int64

CUL4A
False    183
Name: CUL4A, dtype: int64

CUL4B
False    183
Name: CUL4B, dtype: int64

CUL5
False    183
Name: CUL5, dtype: int64

CUL7
False    183
Name: CUL7, dtype: int64

CUL9
False    183
Name: CUL9, dtype: int64

CUTA
False    183
Name: CUTA, dtype: int64

CUTC
False    183
Name: CUTC, dtype: int64

CUX1
False    183
Name: CUX1, dtype: int64

CUX2
False    176
True       7
Name: CUX2, dtype: int64

CUZD1
False    183
Name: CUZD1, dtype: int64

CWC15
False    183
Name: CWC15, dtype: int64

CWC22
False    183
Name: CWC22, dtype: int64

CWC25
False    183
Name: CWC25, dtype: int64

CWC27
False    183
Name: CWC27, dtype: int64

CWF19L1
False    183
Name: CWF19L1, dtype: int64

CWF19L2
False    183
Name: CWF19L2, dtype: int64

CWH43
False    108
True      75
Name: CWH43, dtype: int64

CX3CL1
False    183
Name: CX3CL1, dtype: int64

CX3CR1
False    183
Name: CX3CR1, dtype: int64

CXADRP2
False    99
True     84
Name: CXADRP2, dtype: int64

CXADRP3
False    113
True      70
Name: CXADRP3, dtype: int64

CXADR
False    183
Name: CXADR, dtype: int64

CXCL10
False    183
Name: CXCL10, dtype: int64

CXCL11
False    183
Name: CXCL11, dtype: int64

CXCL12
False    183
Name: CXCL12, dtype: int64

CXCL13
False    181
True       2
Name: CXCL13, dtype: int64

CXCL14
False    183
Name: CXCL14, dtype: int64

CXCL16
False    183
Name: CXCL16, dtype: int64

CXCL17
False    182
True       1
Name: CXCL17, dtype: int64

CXCL1
False    183
Name: CXCL1, dtype: int64

CXCL2
False    183
Name: CXCL2, dtype: int64

CXCL3
False    181
True       2
Name: CXCL3, dtype: int64

CXCL5
False    182
True       1
Name: CXCL5, dtype: int64

CXCL6
False    180
True       3
Name: CXCL6, dtype: int64

CXCL9
False    183
Name: CXCL9, dtype: int64

CXCR1
False    181
True       2
Name: CXCR1, dtype: int64

CXCR2P1
False    169
True      14
Name: CXCR2P1, dtype: int64

CXCR2
False    179
True       4
Name: CXCR2, dtype: int64

CXCR3
False    183
Name: CXCR3, dtype: int64

CXCR4
False    183
Name: CXCR4, dtype: int64

CXCR5
False    183
Name: CXCR5, dtype: int64

CXCR6
False    183
Name: CXCR6, dtype: int64

CXCR7
False    183
Name: CXCR7, dtype: int64

CXXC1
False    183
Name: CXXC1, dtype: int64

CXXC4
False    176
True       7
Name: CXXC4, dtype: int64

CXXC5
False    183
Name: CXXC5, dtype: int64

CXorf1
True     120
False     63
Name: CXorf1, dtype: int64

CXorf21
False    183
Name: CXorf21, dtype: int64

CXorf22
False    112
True      71
Name: CXorf22, dtype: int64

CXorf23
False    183
Name: CXorf23, dtype: int64

CXorf26
False    183
Name: CXorf26, dtype: int64

CXorf30
False    96
True     87
Name: CXorf30, dtype: int64

CXorf36
False    183
Name: CXorf36, dtype: int64

CXorf38
False    183
Name: CXorf38, dtype: int64

CXorf40A
False    183
Name: CXorf40A, dtype: int64

CXorf40B
False    183
Name: CXorf40B, dtype: int64

CXorf42
False    183
Name: CXorf42, dtype: int64

CXorf48
True     92
False    91
Name: CXorf48, dtype: int64

CXorf49B
False    135
True      48
Name: CXorf49B, dtype: int64

CXorf50B
False    182
True       1
Name: CXorf50B, dtype: int64

CXorf56
False    183
Name: CXorf56, dtype: int64

CXorf57
False    183
Name: CXorf57, dtype: int64

CXorf58
False    117
True      66
Name: CXorf58, dtype: int64

CXorf59
True     104
False     79
Name: CXorf59, dtype: int64

CXorf61
True     115
False     68
Name: CXorf61, dtype: int64

CXorf65
False    163
True      20
Name: CXorf65, dtype: int64

CYB561D1
False    183
Name: CYB561D1, dtype: int64

CYB561D2
False    183
Name: CYB561D2, dtype: int64

CYB561
False    183
Name: CYB561, dtype: int64

CYB5A
False    183
Name: CYB5A, dtype: int64

CYB5B
False    183
Name: CYB5B, dtype: int64

CYB5D1
False    183
Name: CYB5D1, dtype: int64

CYB5D2
False    183
Name: CYB5D2, dtype: int64

CYB5R1
False    183
Name: CYB5R1, dtype: int64

CYB5R2
False    183
Name: CYB5R2, dtype: int64

CYB5R3
False    183
Name: CYB5R3, dtype: int64

CYB5R4
False    183
Name: CYB5R4, dtype: int64

CYB5RL
False    183
Name: CYB5RL, dtype: int64

CYBASC3
False    183
Name: CYBASC3, dtype: int64

CYBA
False    183
Name: CYBA, dtype: int64

CYBB
False    183
Name: CYBB, dtype: int64

CYBRD1
False    183
Name: CYBRD1, dtype: int64

CYC1
False    183
Name: CYC1, dtype: int64

CYCS
False    183
Name: CYCS, dtype: int64

CYFIP1
False    183
Name: CYFIP1, dtype: int64

CYFIP2
False    183
Name: CYFIP2, dtype: int64

CYGB
False    183
Name: CYGB, dtype: int64

CYHR1
False    183
Name: CYHR1, dtype: int64

CYLD
False    183
Name: CYLD, dtype: int64

CYMP
False    132
True      51
Name: CYMP, dtype: int64

CYP11A1
False    180
True       3
Name: CYP11A1, dtype: int64

CYP17A1
False    146
True      37
Name: CYP17A1, dtype: int64

CYP19A1
False    181
True       2
Name: CYP19A1, dtype: int64

CYP1A1
False    138
True      45
Name: CYP1A1, dtype: int64

CYP1A2
True     125
False     58
Name: CYP1A2, dtype: int64

CYP1B1
False    183
Name: CYP1B1, dtype: int64

CYP20A1
False    183
Name: CYP20A1, dtype: int64

CYP21A2
False    183
Name: CYP21A2, dtype: int64

CYP24A1
False    172
True      11
Name: CYP24A1, dtype: int64

CYP26A1
False    175
True       8
Name: CYP26A1, dtype: int64

CYP26B1
False    183
Name: CYP26B1, dtype: int64

CYP26C1
False    146
True      37
Name: CYP26C1, dtype: int64

CYP27A1
False    183
Name: CYP27A1, dtype: int64

CYP27B1
False    183
Name: CYP27B1, dtype: int64

CYP27C1
False    180
True       3
Name: CYP27C1, dtype: int64

CYP2A6
False    129
True      54
Name: CYP2A6, dtype: int64

CYP2A7
True     109
False     74
Name: CYP2A7, dtype: int64

CYP2B6
False    171
True      12
Name: CYP2B6, dtype: int64

CYP2B7P1
False    183
Name: CYP2B7P1, dtype: int64

CYP2C18
False    181
True       2
Name: CYP2C18, dtype: int64

CYP2C19
False    166
True      17
Name: CYP2C19, dtype: int64

CYP2C8
False    182
True       1
Name: CYP2C8, dtype: int64

CYP2C9
False    179
True       4
Name: CYP2C9, dtype: int64

CYP2D6
False    181
True       2
Name: CYP2D6, dtype: int64

CYP2D7P1
False    181
True       2
Name: CYP2D7P1, dtype: int64

CYP2E1
False    183
Name: CYP2E1, dtype: int64

CYP2F1
True     120
False     63
Name: CYP2F1, dtype: int64

CYP2J2
False    183
Name: CYP2J2, dtype: int64

CYP2R1
False    183
Name: CYP2R1, dtype: int64

CYP2S1
False    183
Name: CYP2S1, dtype: int64

CYP2U1
False    183
Name: CYP2U1, dtype: int64

CYP2W1
False    181
True       2
Name: CYP2W1, dtype: int64

CYP39A1
False    183
Name: CYP39A1, dtype: int64

CYP3A43
True     110
False     73
Name: CYP3A43, dtype: int64

CYP3A4
False    176
True       7
Name: CYP3A4, dtype: int64

CYP3A5
False    183
Name: CYP3A5, dtype: int64

CYP3A7

False    179
True       4
Name: CYP3A7, dtype: int64

CYP46A1
False    182
True       1
Name: CYP46A1, dtype: int64

CYP4A11
False    163
True      20
Name: CYP4A11, dtype: int64

CYP4B1
False    181
True       2
Name: CYP4B1, dtype: int64

CYP4F11
False    183
Name: CYP4F11, dtype: int64

CYP4F12
False    181
True       2
Name: CYP4F12, dtype: int64

CYP4F22
False    172
True      11
Name: CYP4F22, dtype: int64

CYP4F2
False    156
True      27
Name: CYP4F2, dtype: int64

CYP4F3
False    182
True       1
Name: CYP4F3, dtype: int64

CYP4F8
False    103
True      80
Name: CYP4F8, dtype: int64

CYP4V2
False    183
Name: CYP4V2, dtype: int64

CYP4X1
False    183
Name: CYP4X1, dtype: int64

CYP4Z1
False    103
True      80
Name: CYP4Z1, dtype: int64

CYP4Z2P
True     126
False     57
Name: CYP4Z2P, dtype: int64

CYP51A1
False    183
Name: CYP51A1, dtype: int64

CYP7A1
False    140
True      43
Name: CYP7A1, dtype: int64

CYP7B1
False    182
True       1
Name: CYP7B1, dtype: int64

CYP8B1
False    173
True      10
Name: CYP8B1, dtype: int64

CYR61
False    183
Name: CYR61, dtype: int64

CYS1
False    183
Name: CYS1, dtype: int64

CYSLTR1
False    182
True       1
Name: CYSLTR1, dtype: int64

CYSLTR2
False    182
True       1
Name: CYSLTR2, dtype: int64

CYTH1
False    183
Name: CYTH1, dtype: int64

CYTH2
False    183
Name: CYTH2, dtype: int64

CYTH3
False    183
Name: CYTH3, dtype: int64

CYTH4
False    183
Name: CYTH4, dtype: int64

CYTIP
False    183
Name: CYTIP, dtype: int64

CYTL1
False    182
True       1
Name: CYTL1, dtype: int64

CYTSA
False    183
Name: CYTSA, dtype: int64

CYTSB
False    183
Name: CYTSB, dtype: int64

CYYR1
False    183
Name: CYYR1, dtype: int64

CYorf15A
False    114
True      69
Name: CYorf15A, dtype: int64

CYorf15B
False    119
True      64
Name: CYorf15B, dtype: int64

D2HGDH
False    183
Name: D2HGDH, dtype: int64

D4S234E
False    183
Name: D4S234E, dtype: int64

DAAM1
False    183
Name: DAAM1, dtype: int64

DAAM2
False    183
Name: DAAM2, dtype: int64

DAB1
False    169
True      14
Name: DAB1, dtype: int64

DAB2IP
False    183
Name: DAB2IP, dtype: int64

DAB2
False    183
Name: DAB2, dtype: int64

DACH1
False    183
Name: DACH1, dtype: int64

DACH2
False    164
True      19
Name: DACH2, dtype: int64

DACT1
False    183
Name: DACT1, dtype: int64

DACT2
False    183
Name: DACT2, dtype: int64

DACT3
False    183
Name: DACT3, dtype: int64

DAD1L
True     125
False     58
Name: DAD1L, dtype: int64

DAD1
False    183
Name: DAD1, dtype: int64

DAG1
False    183
Name: DAG1, dtype: int64

DAGLA
False    183
Name: DAGLA, dtype: int64

DAGLB
False    183
Name: DAGLB, dtype: int64

DAK
False    183
Name: DAK, dtype: int64

DALRD3
False    183
Name: DALRD3, dtype: int64

DAND5
False    177
True       6
Name: DAND5, dtype: int64

DAO
False    113
True      70
Name: DAO, dtype: int64

DAP3
False    183
Name: DAP3, dtype: int64

DAPK1
False    183
Name: DAPK1, dtype: int64

DAPK2
False    183
Name: DAPK2, dtype: int64

DAPK3
False    183
Name: DAPK3, dtype: int64

DAPL1
False    176
True       7
Name: DAPL1, dtype: int64

DAPP1
False    183
Name: DAPP1, dtype: int64

DAP
False    183
Name: DAP, dtype: int64

DARC
False    183
Name: DARC, dtype: int64

DARS2
False    183
Name: DARS2, dtype: int64

DARS
False    183
Name: DARS, dtype: int64

DAXX
False    183
Name: DAXX, dtype: int64

DAZ1
True     117
False     66
Name: DAZ1, dtype: int64

DAZAP1
False    183
Name: DAZAP1, dtype: int64

DAZAP2
False    183
Name: DAZAP2, dtype: int64

DAZL
False    124
True      59
Name: DAZL, dtype: int64

DBC1
False    183
Name: DBC1, dtype: int64

DBF4B
False    183
Name: DBF4B, dtype: int64

DBF4
False    183
Name: DBF4, dtype: int64

DBH
False    176
True       7
Name: DBH, dtype: int64

DBI
False    183
Name: DBI, dtype: int64

DBN1
False    183
Name: DBN1, dtype: int64

DBNDD1
False    183
Name: DBNDD1, dtype: int64

DBNDD2
False    183
Name: DBNDD2, dtype: int64

DBNL
False    183
Name: DBNL, dtype: int64

DBP
False    183
Name: DBP, dtype: int64

DBR1
False    183
Name: DBR1, dtype: int64

DBT
False    183
Name: DBT, dtype: int64

DBX2
False    153
True      30
Name: DBX2, dtype: int64

DCAF10
False    183
Name: DCAF10, dtype: int64

DCAF11
False    183
Name: DCAF11, dtype: int64

DCAF12L1
False    136
True      47
Name: DCAF12L1, dtype: int64

DCAF12L2
False    141
True      42
Name: DCAF12L2, dtype: int64

DCAF12
False    183
Name: DCAF12, dtype: int64

DCAF13
False    183
Name: DCAF13, dtype: int64

DCAF15
False    183
Name: DCAF15, dtype: int64

DCAF16
False    183
Name: DCAF16, dtype: int64

DCAF17
False    183
Name: DCAF17, dtype: int64

DCAF4L1
False    183
Name: DCAF4L1, dtype: int64

DCAF4
False    183
Name: DCAF4, dtype: int64

DCAF5
False    183
Name: DCAF5, dtype: int64

DCAF6
False    183
Name: DCAF6, dtype: int64

DCAF7
False    183
Name: DCAF7, dtype: int64

DCAF8
False    183
Name: DCAF8, dtype: int64

DCAKD
False    183
Name: DCAKD, dtype: int64

DCBLD1
False    183
Name: DCBLD1, dtype: int64

DCBLD2
False    183
Name: DCBLD2, dtype: int64

DCC
False    142
True      41
Name: DCC, dtype: int64

DCDC1
False    147
True      36
Name: DCDC1, dtype: int64

DCDC2B
False    115
True      68
Name: DCDC2B, dtype: int64

DCDC2
False    182
True       1
Name: DCDC2, dtype: int64

DCHS1
False    183
Name: DCHS1, dtype: int64

DCHS2
False    181
True       2
Name: DCHS2, dtype: int64

DCI
False    183
Name: DCI, dtype: int64

DCK
False    183
Name: DCK, dtype: int64

DCLK1
False    183
Name: DCLK1, dtype: int64

DCLK2
False    183
Name: DCLK2, dtype: int64

DCLK3
False    182
True       1
Name: DCLK3, dtype: int64

DCLRE1A
False    183
Name: DCLRE1A, dtype: int64

DCLRE1B
False    183
Name: DCLRE1B, dtype: int64

DCLRE1C
False    183
Name: DCLRE1C, dtype: int64

DCN
False    183
Name: DCN, dtype: int64

DCP1A
False    183
Name: DCP1A, dtype: int64

DCP1B
False    183
Name: DCP1B, dtype: int64

DCP2
False    183
Name: DCP2, dtype: int64

DCPS
False    183
Name: DCPS, dtype: int64

DCST1
False    123
True      60
Name: DCST1, dtype: int64

DCST2
False    183
Name: DCST2, dtype: int64

DCTD
False    183
Name: DCTD, dtype: int64

DCTN1
False    183
Name: DCTN1, dtype: int64

DCTN2
False    183
Name: DCTN2, dtype: int64

DCTN3
False    183
Name: DCTN3, dtype: int64

DCTN4
False    183
Name: DCTN4, dtype: int64

DCTN5
False    183
Name: DCTN5, dtype: int64

DCTN6
False    183
Name: DCTN6, dtype: int64

DCTPP1
False    183
Name: DCTPP1, dtype: int64

DCT
False    122
True      61
Name: DCT, dtype: int64

DCUN1D1
False    183
Name: DCUN1D1, dtype: int64

DCUN1D2
False    183
Name: DCUN1D2, dtype: int64

DCUN1D3
False    183
Name: DCUN1D3, dtype: int64

DCUN1D4
False    183
Name: DCUN1D4, dtype: int64

DCUN1D5
False    183
Name: DCUN1D5, dtype: int64

DCXR
False    183
Name: DCXR, dtype: int64

DCX
False    176
True       7
Name: DCX, dtype: int64

DDA1
False    183
Name: DDA1, dtype: int64

DDAH1
False    183
Name: DDAH1, dtype: int64

DDAH2
False    183
Name: DDAH2, dtype: int64

DDB1
False    183
Name: DDB1, dtype: int64

DDB2
False    183
Name: DDB2, dtype: int64

DDC
False    181
True       2
Name: DDC, dtype: int64

DDHD1
False    183
Name: DDHD1, dtype: int64

DDHD2
False    183
Name: DDHD2, dtype: int64

DDI2
False    183
Name: DDI2, dtype: int64

DDIT3
False    183
Name: DDIT3, dtype: int64

DDIT4L
False    182
True       1
Name: DDIT4L, dtype: int64

DDIT4
False    183
Name: DDIT4, dtype: int64

DDN
False    180
True       3
Name: DDN, dtype: int64

DDOST
False    183
Name: DDOST, dtype: int64

DDO
False    183
Name: DDO, dtype: int64

DDR1
False    183
Name: DDR1, dtype: int64

DDR2
False    183
Name: DDR2, dtype: int64

DDRGK1
False    183
Name: DDRGK1, dtype: int64

DDTL
False    183
Name: DDTL, dtype: int64

DDT
False    183
Name: DDT, dtype: int64

DDX10
False    183
Name: DDX10, dtype: int64

DDX11L2
False    183
Name: DDX11L2, dtype: int64

DDX11
False    183
Name: DDX11, dtype: int64

DDX12
False    183
Name: DDX12, dtype: int64

DDX17
False    183
Name: DDX17, dtype: int64

DDX18
False    183
Name: DDX18, dtype: int64

DDX19A
False    183
Name: DDX19A, dtype: int64

DDX19B
False    183
Name: DDX19B, dtype: int64

DDX1
False    183
Name: DDX1, dtype: int64

DDX20
False    183
Name: DDX20, dtype: int64

DDX21
False    183
Name: DDX21, dtype: int64

DDX23
False    183
Name: DDX23, dtype: int64

DDX24
False    183
Name: DDX24, dtype: int64

DDX25
False    166
True      17
Name: DDX25, dtype: int64

DDX26B
False    183
Name: DDX26B, dtype: int64

DDX27

False    183
Name: DDX27, dtype: int64

DDX28
False    183
Name: DDX28, dtype: int64

DDX31
False    183
Name: DDX31, dtype: int64

DDX39
False    183
Name: DDX39, dtype: int64

DDX3X
False    183
Name: DDX3X, dtype: int64

DDX3Y
False    145
True      38
Name: DDX3Y, dtype: int64

DDX41
False    183
Name: DDX41, dtype: int64

DDX42
False    183
Name: DDX42, dtype: int64

DDX43
False    174
True       9
Name: DDX43, dtype: int64

DDX46
False    183
Name: DDX46, dtype: int64

DDX47
False    183
Name: DDX47, dtype: int64

DDX49
False    183
Name: DDX49, dtype: int64

DDX4
False    108
True      75
Name: DDX4, dtype: int64

DDX50
False    183
Name: DDX50, dtype: int64

DDX51
False    183
Name: DDX51, dtype: int64

DDX52
False    183
Name: DDX52, dtype: int64

DDX54
False    183
Name: DDX54, dtype: int64

DDX55
False    183
Name: DDX55, dtype: int64

DDX56
False    183
Name: DDX56, dtype: int64

DDX58
False    183
Name: DDX58, dtype: int64

DDX59
False    183
Name: DDX59, dtype: int64

DDX5
False    183
Name: DDX5, dtype: int64

DDX60L
False    183
Name: DDX60L, dtype: int64

DDX60
False    183
Name: DDX60, dtype: int64

DDX6
False    183
Name: DDX6, dtype: int64

DEAF1
False    183
Name: DEAF1, dtype: int64

DECR1
False    183
Name: DECR1, dtype: int64

DECR2
False    183
Name: DECR2, dtype: int64

DEDD2
False    183
Name: DEDD2, dtype: int64

DEDD
False    183
Name: DEDD, dtype: int64

DEF6
False    183
Name: DEF6, dtype: int64

DEF8
False    183
Name: DEF8, dtype: int64

DEFA1B
False    114
True      69
Name: DEFA1B, dtype: int64

DEFA4
True     128
False     55
Name: DEFA4, dtype: int64

DEFB1
False    181
True       2
Name: DEFB1, dtype: int64

DEGS1
False    183
Name: DEGS1, dtype: int64

DEGS2
False    183
Name: DEGS2, dtype: int64

DEK
False    183
Name: DEK, dtype: int64

DEM1
False    183
Name: DEM1, dtype: int64

DENND1A
False    183
Name: DENND1A, dtype: int64

DENND1B
False    183
Name: DENND1B, dtype: int64

DENND1C
False    183
Name: DENND1C, dtype: int64

DENND2A
False    183
Name: DENND2A, dtype: int64

DENND2C
False    183
Name: DENND2C, dtype: int64

DENND2D
False    183
Name: DENND2D, dtype: int64

DENND3
False    183
Name: DENND3, dtype: int64

DENND4A
False    183
Name: DENND4A, dtype: int64

DENND4B
False    183
Name: DENND4B, dtype: int64

DENND4C
False    183
Name: DENND4C, dtype: int64

DENND5A
False    183
Name: DENND5A, dtype: int64

DENND5B
False    183
Name: DENND5B, dtype: int64

DENR
False    183
Name: DENR, dtype: int64

DEPDC1B
False    183
Name: DEPDC1B, dtype: int64

DEPDC1
False    182
True       1
Name: DEPDC1, dtype: int64

DEPDC4
False    182
True       1
Name: DEPDC4, dtype: int64

DEPDC5
False    183
Name: DEPDC5, dtype: int64

DEPDC6
False    183
Name: DEPDC6, dtype: int64

DEPDC7
False    182
True       1
Name: DEPDC7, dtype: int64

DERA
False    183
Name: DERA, dtype: int64

DERL1
False    183
Name: DERL1, dtype: int64

DERL2
False    183
Name: DERL2, dtype: int64

DERL3
False    183
Name: DERL3, dtype: int64

DES
False    182
True       1
Name: DES, dtype: int64

DET1
False    183
Name: DET1, dtype: int64

DEXI
False    183
Name: DEXI, dtype: int64

DFFA
False    183
Name: DFFA, dtype: int64

DFFB
False    183
Name: DFFB, dtype: int64

DFNA5
False    183
Name: DFNA5, dtype: int64

DFNB31
False    183
Name: DFNB31, dtype: int64

DFNB59
False    183
Name: DFNB59, dtype: int64

DGAT1
False    183
Name: DGAT1, dtype: int64

DGAT2
False    183
Name: DGAT2, dtype: int64

DGCR10
False    149
True      34
Name: DGCR10, dtype: int64

DGCR11
False    183
Name: DGCR11, dtype: int64

DGCR14
False    183
Name: DGCR14, dtype: int64

DGCR2
False    183
Name: DGCR2, dtype: int64

DGCR5
False    183
Name: DGCR5, dtype: int64

DGCR6L
False    183
Name: DGCR6L, dtype: int64

DGCR6
False    183
Name: DGCR6, dtype: int64

DGCR8
False    183
Name: DGCR8, dtype: int64

DGCR9
False    183
Name: DGCR9, dtype: int64

DGKA
False    183
Name: DGKA, dtype: int64

DGKB
False    181
True       2
Name: DGKB, dtype: int64

DGKD
False    183
Name: DGKD, dtype: int64

DGKE
False    183
Name: DGKE, dtype: int64

DGKG
False    183
Name: DGKG, dtype: int64

DGKH
False    183
Name: DGKH, dtype: int64

DGKI
False    181
True       2
Name: DGKI, dtype: int64

DGKQ
False    183
Name: DGKQ, dtype: int64

DGKZ
False    183
Name: DGKZ, dtype: int64

DGUOK
False    183
Name: DGUOK, dtype: int64

DHCR24
False    183
Name: DHCR24, dtype: int64

DHCR7
False    183
Name: DHCR7, dtype: int64

DHDDS
False    183
Name: DHDDS, dtype: int64

DHDH
False    183
Name: DHDH, dtype: int64

DHDPSL
False    182
True       1
Name: DHDPSL, dtype: int64

DHFRL1
False    183
Name: DHFRL1, dtype: int64

DHFR
False    183
Name: DHFR, dtype: int64

DHH
False    182
True       1
Name: DHH, dtype: int64

DHODH
False    183
Name: DHODH, dtype: int64

DHPS
False    183
Name: DHPS, dtype: int64

DHRS11
False    183
Name: DHRS11, dtype: int64

DHRS12
False    183
Name: DHRS12, dtype: int64

DHRS13
False    183
Name: DHRS13, dtype: int64

DHRS1
False    183
Name: DHRS1, dtype: int64

DHRS2
False    183
Name: DHRS2, dtype: int64

DHRS3
False    183
Name: DHRS3, dtype: int64

DHRS4L1
False    183
Name: DHRS4L1, dtype: int64

DHRS4L2
False    183
Name: DHRS4L2, dtype: int64

DHRS4
False    183
Name: DHRS4, dtype: int64

DHRS7B
False    183
Name: DHRS7B, dtype: int64

DHRS7
False    183
Name: DHRS7, dtype: int64

DHRS9
False    183
Name: DHRS9, dtype: int64

DHRSX
False    183
Name: DHRSX, dtype: int64

DHTKD1
False    183
Name: DHTKD1, dtype: int64

DHX15
False    183
Name: DHX15, dtype: int64

DHX16
False    183
Name: DHX16, dtype: int64

DHX29
False    183
Name: DHX29, dtype: int64

DHX30
False    183
Name: DHX30, dtype: int64

DHX32
False    183
Name: DHX32, dtype: int64

DHX33
False    183
Name: DHX33, dtype: int64

DHX34
False    183
Name: DHX34, dtype: int64

DHX35
False    183
Name: DHX35, dtype: int64

DHX36
False    183
Name: DHX36, dtype: int64

DHX37
False    183
Name: DHX37, dtype: int64

DHX38
False    183
Name: DHX38, dtype: int64

DHX40P1
True     115
False     68
Name: DHX40P1, dtype: int64

DHX40
False    183
Name: DHX40, dtype: int64

DHX57
False    183
Name: DHX57, dtype: int64

DHX58
False    183
Name: DHX58, dtype: int64

DHX8
False    183
Name: DHX8, dtype: int64

DHX9
False    183
Name: DHX9, dtype: int64

DIABLO
False    183
Name: DIABLO, dtype: int64

DIAPH1
False    183
Name: DIAPH1, dtype: int64

DIAPH2
False    183
Name: DIAPH2, dtype: int64

DIAPH3
False    183
Name: DIAPH3, dtype: int64

DICER1
False    183
Name: DICER1, dtype: int64

DIDO1
False    183
Name: DIDO1, dtype: int64

DIMT1L
False    183
Name: DIMT1L, dtype: int64

DIO1
False    163
True      20
Name: DIO1, dtype: int64

DIO2
False    183
Name: DIO2, dtype: int64

DIO3OS
False    178
True       5
Name: DIO3OS, dtype: int64

DIO3
False    182
True       1
Name: DIO3, dtype: int64

DIP2A
False    183
Name: DIP2A, dtype: int64

DIP2B
False    183
Name: DIP2B, dtype: int64

DIP2C
False    183
Name: DIP2C, dtype: int64

DIRAS1
False    183
Name: DIRAS1, dtype: int64

DIRAS2
False    182
True       1
Name: DIRAS2, dtype: int64

DIRAS3
False    183
Name: DIRAS3, dtype: int64

DIRC1
False    150
True      33
Name: DIRC1, dtype: int64

DIRC2
False    183
Name: DIRC2, dtype: int64

DIRC3
False    182
True       1
Name: DIRC3, dtype: int64

DIS3L2
False    183
Name: DIS3L2, dtype: int64

DIS3L
False    183
Name: DIS3L, dtype: int64

DIS3
False    183
Name: DIS3, dtype: int64

DISC1
False    183
Name: DISC1, dtype: int64

DISC2
True     102
False     81
Name: DISC2, dtype: int64

DISP1
False    183
Name: DISP1, dtype: int64

DISP2
False    183
Name: DISP2, dtype: int64

DIXDC1
False    183
Name: DIXDC1, dtype: int64

DKC1
False    183
Name: DKC1, dtype: int64

DKFZP434K028
False    140
True      43
Name: DKFZP434K028, dtype: int64

DKFZP434L187
False    92
True     91
Name: DKFZP434L187, dtype: int64

DKFZP586I1420
False    183
Name: DKFZP586I1420, dtype: int64

DKFZP686I15217
False    183
Name: DKFZP686I15217, dtype: int64

DKFZp434J0226
False    180
True       3
Name: DKFZp434J0226, dtype: int64

DKFZp566F0947
False    162
True      21
Name: DKFZp566F0947, dtype: int64

DKFZp686O24166
False    183
Name: DKFZp686O24166, dtype: int64

DKFZp761E198
False    183
Name: DKFZp761E198, dtype: int64

DKFZp779M0652
False    177
True       6
Name: DKFZp779M0652, dtype: int64

DKK1

False    179
True       4
Name: DKK1, dtype: int64

DKK2
False    182
True       1
Name: DKK2, dtype: int64

DKK3
False    183
Name: DKK3, dtype: int64

DKK4
False    167
True      16
Name: DKK4, dtype: int64

DKKL1
False    156
True      27
Name: DKKL1, dtype: int64

DLAT
False    183
Name: DLAT, dtype: int64

DLC1
False    183
Name: DLC1, dtype: int64

DLD
False    183
Name: DLD, dtype: int64

DLEC1
False    183
Name: DLEC1, dtype: int64

DLEU1
False    183
Name: DLEU1, dtype: int64

DLEU2L
False    173
True      10
Name: DLEU2L, dtype: int64

DLEU2
False    183
Name: DLEU2, dtype: int64

DLEU7
False    179
True       4
Name: DLEU7, dtype: int64

DLG1
False    183
Name: DLG1, dtype: int64

DLG2
False    182
True       1
Name: DLG2, dtype: int64

DLG3
False    183
Name: DLG3, dtype: int64

DLG4
False    183
Name: DLG4, dtype: int64

DLG5
False    183
Name: DLG5, dtype: int64

DLGAP1
False    168
True      15
Name: DLGAP1, dtype: int64

DLGAP2
False    177
True       6
Name: DLGAP2, dtype: int64

DLGAP3
False    183
Name: DLGAP3, dtype: int64

DLGAP4
False    183
Name: DLGAP4, dtype: int64

DLGAP5
False    183
Name: DLGAP5, dtype: int64

DLK1
False    173
True      10
Name: DLK1, dtype: int64

DLK2
False    182
True       1
Name: DLK2, dtype: int64

DLL1
False    183
Name: DLL1, dtype: int64

DLL3
False    163
True      20
Name: DLL3, dtype: int64

DLL4
False    183
Name: DLL4, dtype: int64

DLST
False    183
Name: DLST, dtype: int64

DLX1
False    176
True       7
Name: DLX1, dtype: int64

DLX2
False    135
True      48
Name: DLX2, dtype: int64

DLX3
False    179
True       4
Name: DLX3, dtype: int64

DLX4
False    179
True       4
Name: DLX4, dtype: int64

DLX5
False    182
True       1
Name: DLX5, dtype: int64

DLX6AS
True     102
False     81
Name: DLX6AS, dtype: int64

DLX6
False    123
True      60
Name: DLX6, dtype: int64

DMAP1
False    183
Name: DMAP1, dtype: int64

DMBT1
False    182
True       1
Name: DMBT1, dtype: int64

DMBX1
False    175
True       8
Name: DMBX1, dtype: int64

DMC1
False    180
True       3
Name: DMC1, dtype: int64

DMD
False    183
Name: DMD, dtype: int64

DMGDH
False    183
Name: DMGDH, dtype: int64

DMKN
False    183
Name: DMKN, dtype: int64

DMP1
False    141
True      42
Name: DMP1, dtype: int64

DMPK
False    183
Name: DMPK, dtype: int64

DMRT1
True     124
False     59
Name: DMRT1, dtype: int64

DMRT2
False    167
True      16
Name: DMRT2, dtype: int64

DMRT3
False    129
True      54
Name: DMRT3, dtype: int64

DMRTA1
False    180
True       3
Name: DMRTA1, dtype: int64

DMRTA2
False    110
True      73
Name: DMRTA2, dtype: int64

DMRTC1B
False    179
True       4
Name: DMRTC1B, dtype: int64

DMTF1
False    183
Name: DMTF1, dtype: int64

DMWD
False    183
Name: DMWD, dtype: int64

DMXL1
False    183
Name: DMXL1, dtype: int64

DMXL2
False    183
Name: DMXL2, dtype: int64

DNA2
False    183
Name: DNA2, dtype: int64

DNAH10
False    183
Name: DNAH10, dtype: int64

DNAH11
False    182
True       1
Name: DNAH11, dtype: int64

DNAH12
False    180
True       3
Name: DNAH12, dtype: int64

DNAH14
False    182
True       1
Name: DNAH14, dtype: int64

DNAH17
False    183
Name: DNAH17, dtype: int64

DNAH1
False    183
Name: DNAH1, dtype: int64

DNAH2
False    183
Name: DNAH2, dtype: int64

DNAH3
False    178
True       5
Name: DNAH3, dtype: int64

DNAH5
False    183
Name: DNAH5, dtype: int64

DNAH6
False    183
Name: DNAH6, dtype: int64

DNAH7
False    183
Name: DNAH7, dtype: int64

DNAH8
False    142
True      41
Name: DNAH8, dtype: int64

DNAH9
False    182
True       1
Name: DNAH9, dtype: int64

DNAI1
False    167
True      16
Name: DNAI1, dtype: int64

DNAI2
False    98
True     85
Name: DNAI2, dtype: int64

DNAJA1
False    183
Name: DNAJA1, dtype: int64

DNAJA2
False    183
Name: DNAJA2, dtype: int64

DNAJA3
False    183
Name: DNAJA3, dtype: int64

DNAJA4
False    183
Name: DNAJA4, dtype: int64

DNAJB11
False    183
Name: DNAJB11, dtype: int64

DNAJB12
False    183
Name: DNAJB12, dtype: int64

DNAJB13
False    179
True       4
Name: DNAJB13, dtype: int64

DNAJB14
False    183
Name: DNAJB14, dtype: int64

DNAJB1
False    183
Name: DNAJB1, dtype: int64

DNAJB2
False    183
Name: DNAJB2, dtype: int64

DNAJB3
True     94
False    89
Name: DNAJB3, dtype: int64

DNAJB4
False    183
Name: DNAJB4, dtype: int64

DNAJB5
False    183
Name: DNAJB5, dtype: int64

DNAJB6
False    183
Name: DNAJB6, dtype: int64

DNAJB7
False    174
True       9
Name: DNAJB7, dtype: int64

DNAJB9
False    183
Name: DNAJB9, dtype: int64

DNAJC10
False    183
Name: DNAJC10, dtype: int64

DNAJC11
False    183
Name: DNAJC11, dtype: int64

DNAJC12
False    183
Name: DNAJC12, dtype: int64

DNAJC13
False    183
Name: DNAJC13, dtype: int64

DNAJC14
False    183
Name: DNAJC14, dtype: int64

DNAJC15
False    183
Name: DNAJC15, dtype: int64

DNAJC16
False    183
Name: DNAJC16, dtype: int64

DNAJC17
False    183
Name: DNAJC17, dtype: int64

DNAJC18
False    183
Name: DNAJC18, dtype: int64

DNAJC19
False    183
Name: DNAJC19, dtype: int64

DNAJC1
False    183
Name: DNAJC1, dtype: int64

DNAJC21
False    183
Name: DNAJC21, dtype: int64

DNAJC22
False    183
Name: DNAJC22, dtype: int64

DNAJC24
False    183
Name: DNAJC24, dtype: int64

DNAJC25
False    183
Name: DNAJC25, dtype: int64

DNAJC27
False    183
Name: DNAJC27, dtype: int64

DNAJC28
False    183
Name: DNAJC28, dtype: int64

DNAJC2
False    183
Name: DNAJC2, dtype: int64

DNAJC30
False    183
Name: DNAJC30, dtype: int64

DNAJC3
False    183
Name: DNAJC3, dtype: int64

DNAJC4
False    183
Name: DNAJC4, dtype: int64

DNAJC5B
False    181
True       2
Name: DNAJC5B, dtype: int64

DNAJC5
False    183
Name: DNAJC5, dtype: int64

DNAJC6
False    183
Name: DNAJC6, dtype: int64

DNAJC7
False    183
Name: DNAJC7, dtype: int64

DNAJC8
False    183
Name: DNAJC8, dtype: int64

DNAJC9
False    183
Name: DNAJC9, dtype: int64

DNAL1
False    183
Name: DNAL1, dtype: int64

DNAL4
False    183
Name: DNAL4, dtype: int64

DNALI1
False    183
Name: DNALI1, dtype: int64

DNASE1L1
False    183
Name: DNASE1L1, dtype: int64

DNASE1L2
False    181
True       2
Name: DNASE1L2, dtype: int64

DNASE1L3
False    179
True       4
Name: DNASE1L3, dtype: int64

DNASE1
False    183
Name: DNASE1, dtype: int64

DNASE2B
False    173
True      10
Name: DNASE2B, dtype: int64

DNASE2
False    183
Name: DNASE2, dtype: int64

DND1
False    183
Name: DND1, dtype: int64

DNER
False    183
Name: DNER, dtype: int64

DNHD1
False    183
Name: DNHD1, dtype: int64

DNLZ
False    183
Name: DNLZ, dtype: int64

DNM1L
False    183
Name: DNM1L, dtype: int64

DNM1P35
False    183
Name: DNM1P35, dtype: int64

DNM1
False    183
Name: DNM1, dtype: int64

DNM2
False    183
Name: DNM2, dtype: int64

DNM3
False    183
Name: DNM3, dtype: int64

DNMBP
False    183
Name: DNMBP, dtype: int64

DNMT1
False    183
Name: DNMT1, dtype: int64

DNMT3A
False    183
Name: DNMT3A, dtype: int64

DNMT3B
False    183
Name: DNMT3B, dtype: int64

DNPEP
False    183
Name: DNPEP, dtype: int64

DNTTIP1
False    183
Name: DNTTIP1, dtype: int64

DNTTIP2
False    183
Name: DNTTIP2, dtype: int64

DOC2A
False    183
Name: DOC2A, dtype: int64

DOC2B
False    182
True       1
Name: DOC2B, dtype: int64

DOCK10
False    183
Name: DOCK10, dtype: int64

DOCK11
False    183
Name: DOCK11, dtype: int64

DOCK1
False    183
Name: DOCK1, dtype: int64

DOCK2
False    183
Name: DOCK2, dtype: int64

DOCK3
False    183
Name: DOCK3, dtype: int64

DOCK4
False    183
Name: DOCK4, dtype: int64

DOCK5
False    183
Name: DOCK5, dtype: int64

DOCK6
False    183
Name: DOCK6, dtype: int64

DOCK7
False    183
Name: DOCK7, dtype: int64

DOCK8
False    183
Name: DOCK8, dtype: int64

DOCK9
False    183
Name: DOCK9, dtype: int64

DOHH
False    183
Name: DOHH, dtype: int64

DOK1
False    183
Name: DOK1, dtype: int64

DOK2
False    183
Name: DOK2, dtype: int64

DOK3
False    183
Name: DOK3, dtype: int64

DOK4
False    183
Name: DOK4, dtype: int64

DOK5
False    183
Name: DOK5, dtype: int64

DOK6
False    183
Name: DOK6, dtype: int64

DOK7
False    182
True       1
Name: DOK7, dtype: int64

DOLK
False    183
Name: DOLK, dtype: int64

DOLPP1
False    183
Name: DOLPP1, dtype: int64

DOM3Z
False    183
Name: DOM3Z, dtype: int64

DONSON
False    183
Name: DONSON, dtype: int64

DOPEY1
False    183
Name: DOPEY1, dtype: int64

DOPEY2
False    183
Name: DOPEY2, dtype: int64

DOT1L
False    183
Name: DOT1L, dtype: int64

DPAGT1
False    183
Name: DPAGT1, dtype: int64

DPCD
False    183
Name: DPCD, dtype: int64

DPCR1
False    177
True       6
Name: DPCR1, dtype: int64

DPEP1
False    183
Name: DPEP1, dtype: int64

DPEP2
False    183
Name: DPEP2, dtype: int64

DPEP3
False    147
True      36
Name: DPEP3, dtype: int64

DPF1
False    178
True       5
Name: DPF1, dtype: int64

DPF2
False    183
Name: DPF2, dtype: int64

DPF3
False    183
Name: DPF3, dtype: int64

DPH1
False    183
Name: DPH1, dtype: int64

DPH2

False    183
Name: DPH2, dtype: int64

DPH3B
False    183
Name: DPH3B, dtype: int64

DPH3
False    183
Name: DPH3, dtype: int64

DPH5
False    183
Name: DPH5, dtype: int64

DPM1
False    183
Name: DPM1, dtype: int64

DPM2
False    183
Name: DPM2, dtype: int64

DPM3
False    183
Name: DPM3, dtype: int64

DPP10
False    164
True      19
Name: DPP10, dtype: int64

DPP3
False    183
Name: DPP3, dtype: int64

DPP4
False    183
Name: DPP4, dtype: int64

DPP6
False    182
True       1
Name: DPP6, dtype: int64

DPP7
False    183
Name: DPP7, dtype: int64

DPP8
False    183
Name: DPP8, dtype: int64

DPP9
False    183
Name: DPP9, dtype: int64

DPPA4
False    129
True      54
Name: DPPA4, dtype: int64

DPRXP4
False    167
True      16
Name: DPRXP4, dtype: int64

DPT
False    183
Name: DPT, dtype: int64

DPY19L1
False    183
Name: DPY19L1, dtype: int64

DPY19L2P1
False    150
True      33
Name: DPY19L2P1, dtype: int64

DPY19L2P2
False    183
Name: DPY19L2P2, dtype: int64

DPY19L2P4
False    174
True       9
Name: DPY19L2P4, dtype: int64

DPY19L2
False    183
Name: DPY19L2, dtype: int64

DPY19L3
False    183
Name: DPY19L3, dtype: int64

DPY19L4
False    183
Name: DPY19L4, dtype: int64

DPY30
False    183
Name: DPY30, dtype: int64

DPYD
False    183
Name: DPYD, dtype: int64

DPYSL2
False    183
Name: DPYSL2, dtype: int64

DPYSL3
False    183
Name: DPYSL3, dtype: int64

DPYSL4
False    182
True       1
Name: DPYSL4, dtype: int64

DPYSL5
False    157
True      26
Name: DPYSL5, dtype: int64

DPYS
False    169
True      14
Name: DPYS, dtype: int64

DQX1
False    178
True       5
Name: DQX1, dtype: int64

DR1
False    183
Name: DR1, dtype: int64

DRAM1
False    183
Name: DRAM1, dtype: int64

DRAM2
False    183
Name: DRAM2, dtype: int64

DRAP1
False    183
Name: DRAP1, dtype: int64

DRD1
False    178
True       5
Name: DRD1, dtype: int64

DRD2
False    181
True       2
Name: DRD2, dtype: int64

DRD4
False    178
True       5
Name: DRD4, dtype: int64

DRD5
False    118
True      65
Name: DRD5, dtype: int64

DRG1
False    183
Name: DRG1, dtype: int64

DRG2
False    183
Name: DRG2, dtype: int64

DRP2
False    181
True       2
Name: DRP2, dtype: int64

DSC1
False    99
True     84
Name: DSC1, dtype: int64

DSC2
False    183
Name: DSC2, dtype: int64

DSC3
False    180
True       3
Name: DSC3, dtype: int64

DSCAML1
False    181
True       2
Name: DSCAML1, dtype: int64

DSCAM
False    167
True      16
Name: DSCAM, dtype: int64

DSCC1
False    183
Name: DSCC1, dtype: int64

DSCR3
False    183
Name: DSCR3, dtype: int64

DSCR6
False    183
Name: DSCR6, dtype: int64

DSCR9
False    172
True      11
Name: DSCR9, dtype: int64

DSEL
False    183
Name: DSEL, dtype: int64

DSE
False    183
Name: DSE, dtype: int64

DSG1
False    147
True      36
Name: DSG1, dtype: int64

DSG2
False    183
Name: DSG2, dtype: int64

DSG3
False    175
True       8
Name: DSG3, dtype: int64

DSG4
False    120
True      63
Name: DSG4, dtype: int64

DSN1
False    183
Name: DSN1, dtype: int64

DSP
False    183
Name: DSP, dtype: int64

DSTN
False    183
Name: DSTN, dtype: int64

DSTYK
False    183
Name: DSTYK, dtype: int64

DST
False    183
Name: DST, dtype: int64

DTD1
False    183
Name: DTD1, dtype: int64

DTHD1
False    169
True      14
Name: DTHD1, dtype: int64

DTL
False    183
Name: DTL, dtype: int64

DTNA
False    183
Name: DTNA, dtype: int64

DTNBP1
False    183
Name: DTNBP1, dtype: int64

DTNB
False    183
Name: DTNB, dtype: int64

DTWD1
False    183
Name: DTWD1, dtype: int64

DTWD2
False    183
Name: DTWD2, dtype: int64

DTX1
False    183
Name: DTX1, dtype: int64

DTX2
False    183
Name: DTX2, dtype: int64

DTX3L
False    183
Name: DTX3L, dtype: int64

DTX3
False    183
Name: DTX3, dtype: int64

DTX4
False    183
Name: DTX4, dtype: int64

DTYMK
False    183
Name: DTYMK, dtype: int64

DULLARD
False    183
Name: DULLARD, dtype: int64

DUOX1
False    183
Name: DUOX1, dtype: int64

DUOX2
False    182
True       1
Name: DUOX2, dtype: int64

DUOXA1
False    181
True       2
Name: DUOXA1, dtype: int64

DUOXA2
False    180
True       3
Name: DUOXA2, dtype: int64

DUS1L
False    183
Name: DUS1L, dtype: int64

DUS2L
False    183
Name: DUS2L, dtype: int64

DUS3L
False    183
Name: DUS3L, dtype: int64

DUS4L
False    183
Name: DUS4L, dtype: int64

DUSP10
False    183
Name: DUSP10, dtype: int64

DUSP11
False    183
Name: DUSP11, dtype: int64

DUSP12
False    183
Name: DUSP12, dtype: int64

DUSP13
False    118
True      65
Name: DUSP13, dtype: int64

DUSP14
False    183
Name: DUSP14, dtype: int64

DUSP15
False    183
Name: DUSP15, dtype: int64

DUSP16
False    183
Name: DUSP16, dtype: int64

DUSP18
False    183
Name: DUSP18, dtype: int64

DUSP19
False    183
Name: DUSP19, dtype: int64

DUSP1
False    183
Name: DUSP1, dtype: int64

DUSP22
False    183
Name: DUSP22, dtype: int64

DUSP23
False    183
Name: DUSP23, dtype: int64

DUSP26
False    182
True       1
Name: DUSP26, dtype: int64

DUSP27
False    164
True      19
Name: DUSP27, dtype: int64

DUSP28
False    183
Name: DUSP28, dtype: int64

DUSP2
False    183
Name: DUSP2, dtype: int64

DUSP3
False    183
Name: DUSP3, dtype: int64

DUSP4
False    183
Name: DUSP4, dtype: int64

DUSP5P
False    177
True       6
Name: DUSP5P, dtype: int64

DUSP5
False    183
Name: DUSP5, dtype: int64

DUSP6
False    183
Name: DUSP6, dtype: int64

DUSP7
False    183
Name: DUSP7, dtype: int64

DUSP8
False    183
Name: DUSP8, dtype: int64

DUSP9
False    168
True      15
Name: DUSP9, dtype: int64

DUT
False    183
Name: DUT, dtype: int64

DVL1
False    183
Name: DVL1, dtype: int64

DVL2
False    183
Name: DVL2, dtype: int64

DVL3
False    183
Name: DVL3, dtype: int64

DVWA
False    119
True      64
Name: DVWA, dtype: int64

DYDC2
False    174
True       9
Name: DYDC2, dtype: int64

DYM
False    183
Name: DYM, dtype: int64

DYNC1H1
False    183
Name: DYNC1H1, dtype: int64

DYNC1I1
False    183
Name: DYNC1I1, dtype: int64

DYNC1I2
False    183
Name: DYNC1I2, dtype: int64

DYNC1LI1
False    183
Name: DYNC1LI1, dtype: int64

DYNC1LI2
False    183
Name: DYNC1LI2, dtype: int64

DYNC2H1
False    183
Name: DYNC2H1, dtype: int64

DYNC2LI1
False    183
Name: DYNC2LI1, dtype: int64

DYNLL1
False    183
Name: DYNLL1, dtype: int64

DYNLL2
False    183
Name: DYNLL2, dtype: int64

DYNLRB1
False    183
Name: DYNLRB1, dtype: int64

DYNLRB2
False    177
True       6
Name: DYNLRB2, dtype: int64

DYNLT1
False    183
Name: DYNLT1, dtype: int64

DYNLT3
False    183
Name: DYNLT3, dtype: int64

DYRK1A
False    183
Name: DYRK1A, dtype: int64

DYRK1B
False    183
Name: DYRK1B, dtype: int64

DYRK2
False    183
Name: DYRK2, dtype: int64

DYRK3
False    183
Name: DYRK3, dtype: int64

DYRK4
False    183
Name: DYRK4, dtype: int64

DYSFIP1
True     95
False    88
Name: DYSFIP1, dtype: int64

DYSF
False    183
Name: DYSF, dtype: int64

DYX1C1
False    183
Name: DYX1C1, dtype: int64

DZIP1L
False    183
Name: DZIP1L, dtype: int64

DZIP1
False    183
Name: DZIP1, dtype: int64

DZIP3
False    183
Name: DZIP3, dtype: int64

E2F1
False    183
Name: E2F1, dtype: int64

E2F2
False    183
Name: E2F2, dtype: int64

E2F3
False    183
Name: E2F3, dtype: int64

E2F4
False    183
Name: E2F4, dtype: int64

E2F5
False    183
Name: E2F5, dtype: int64

E2F6
False    183
Name: E2F6, dtype: int64

E2F7
False    183
Name: E2F7, dtype: int64

E2F8
False    182
True       1
Name: E2F8, dtype: int64

E4F1
False    183
Name: E4F1, dtype: int64

EAF1
False    183
Name: EAF1, dtype: int64

EAF2
False    183
Name: EAF2, dtype: int64

EAPP
False    183
Name: EAPP, dtype: int64

EARS2
False    183
Name: EARS2, dtype: int64

EBAG9
False    183
Name: EBAG9, dtype: int64

EBF1
False    183
Name: EBF1, dtype: int64

EBF2
False    180
True       3
Name: EBF2, dtype: int64

EBF3
False    183
Name: EBF3, dtype: int64

EBF4
False    183
Name: EBF4, dtype: int64

EBI3
False    183
Name: EBI3, dtype: int64

EBNA1BP2
False    183
Name: EBNA1BP2, dtype: int64

EBPL
False    183
Name: EBPL, dtype: int64

EBP
False    183
Name: EBP, dtype: int64

ECD
False    183
Name: ECD, dtype: int64

ECE1
False    183
Name: ECE1, dtype: int64

ECE2
False    183
Name: ECE2, dtype: int64

ECEL1
False    180
True       3
Name: ECEL1, dtype: int64

ECH1
False    183
Name: ECH1, dtype: int64

ECHDC1
False    183
Name: ECHDC1, dtype: int64

ECHDC2
False    183
Name: ECHDC2, dtype: int64

ECHDC3
False    183
Name: ECHDC3, dtype: int64

ECHS1
False    183
Name: ECHS1, dtype: int64

ECM1
False    183
Name: ECM1, dtype: int64

ECM2
False    183
Name: ECM2, dtype: int64

ECSCR

False    183
Name: ECSCR, dtype: int64

ECSIT
False    183
Name: ECSIT, dtype: int64

ECT2L
False    182
True       1
Name: ECT2L, dtype: int64

ECT2
False    183
Name: ECT2, dtype: int64

EDA2R
False    183
Name: EDA2R, dtype: int64

EDARADD
False    183
Name: EDARADD, dtype: int64

EDAR
False    180
True       3
Name: EDAR, dtype: int64

EDA
False    183
Name: EDA, dtype: int64

EDC3
False    183
Name: EDC3, dtype: int64

EDC4
False    183
Name: EDC4, dtype: int64

EDEM1
False    183
Name: EDEM1, dtype: int64

EDEM2
False    183
Name: EDEM2, dtype: int64

EDEM3
False    183
Name: EDEM3, dtype: int64

EDF1
False    183
Name: EDF1, dtype: int64

EDIL3
False    183
Name: EDIL3, dtype: int64

EDN1
False    183
Name: EDN1, dtype: int64

EDN2
False    181
True       2
Name: EDN2, dtype: int64

EDN3
False    183
Name: EDN3, dtype: int64

EDNRA
False    183
Name: EDNRA, dtype: int64

EDNRB
False    183
Name: EDNRB, dtype: int64

EEA1
False    183
Name: EEA1, dtype: int64

EED
False    183
Name: EED, dtype: int64

EEF1A1P9
False    183
Name: EEF1A1P9, dtype: int64

EEF1A1
False    183
Name: EEF1A1, dtype: int64

EEF1A2
False    183
Name: EEF1A2, dtype: int64

EEF1B2
False    183
Name: EEF1B2, dtype: int64

EEF1DP3
False    173
True      10
Name: EEF1DP3, dtype: int64

EEF1D
False    183
Name: EEF1D, dtype: int64

EEF1E1
False    183
Name: EEF1E1, dtype: int64

EEF1G
False    183
Name: EEF1G, dtype: int64

EEF2K
False    183
Name: EEF2K, dtype: int64

EEF2
False    183
Name: EEF2, dtype: int64

EEFSEC
False    183
Name: EEFSEC, dtype: int64

EEPD1
False    183
Name: EEPD1, dtype: int64

EFCAB10
False    183
Name: EFCAB10, dtype: int64

EFCAB1
False    180
True       3
Name: EFCAB1, dtype: int64

EFCAB2
False    183
Name: EFCAB2, dtype: int64

EFCAB3
True     100
False     83
Name: EFCAB3, dtype: int64

EFCAB4A
False    183
Name: EFCAB4A, dtype: int64

EFCAB4B
False    183
Name: EFCAB4B, dtype: int64

EFCAB5
False    175
True       8
Name: EFCAB5, dtype: int64

EFCAB6
False    183
Name: EFCAB6, dtype: int64

EFCAB7
False    183
Name: EFCAB7, dtype: int64

EFEMP1
False    183
Name: EFEMP1, dtype: int64

EFEMP2
False    183
Name: EFEMP2, dtype: int64

EFHA1
False    183
Name: EFHA1, dtype: int64

EFHA2
False    183
Name: EFHA2, dtype: int64

EFHB
False    175
True       8
Name: EFHB, dtype: int64

EFHC1
False    183
Name: EFHC1, dtype: int64

EFHC2
False    183
Name: EFHC2, dtype: int64

EFHD1
False    183
Name: EFHD1, dtype: int64

EFHD2
False    183
Name: EFHD2, dtype: int64

EFNA1
False    183
Name: EFNA1, dtype: int64

EFNA2
False    173
True      10
Name: EFNA2, dtype: int64

EFNA3
False    183
Name: EFNA3, dtype: int64

EFNA4
False    183
Name: EFNA4, dtype: int64

EFNA5
False    183
Name: EFNA5, dtype: int64

EFNB1
False    183
Name: EFNB1, dtype: int64

EFNB2
False    183
Name: EFNB2, dtype: int64

EFNB3
False    183
Name: EFNB3, dtype: int64

EFR3A
False    183
Name: EFR3A, dtype: int64

EFR3B
False    183
Name: EFR3B, dtype: int64

EFS
False    183
Name: EFS, dtype: int64

EFTUD1
False    183
Name: EFTUD1, dtype: int64

EFTUD2
False    183
Name: EFTUD2, dtype: int64

EGFL6
False    183
Name: EGFL6, dtype: int64

EGFL7
False    183
Name: EGFL7, dtype: int64

EGFL8
False    183
Name: EGFL8, dtype: int64

EGFLAM
False    183
Name: EGFLAM, dtype: int64

EGFR
False    183
Name: EGFR, dtype: int64

EGF
False    175
True       8
Name: EGF, dtype: int64

EGLN1
False    183
Name: EGLN1, dtype: int64

EGLN2
False    183
Name: EGLN2, dtype: int64

EGLN3
False    183
Name: EGLN3, dtype: int64

EGOT
False    177
True       6
Name: EGOT, dtype: int64

EGR1
False    183
Name: EGR1, dtype: int64

EGR2
False    183
Name: EGR2, dtype: int64

EGR3
False    183
Name: EGR3, dtype: int64

EGR4
False    180
True       3
Name: EGR4, dtype: int64

EHBP1L1
False    183
Name: EHBP1L1, dtype: int64

EHBP1
False    183
Name: EHBP1, dtype: int64

EHD1
False    183
Name: EHD1, dtype: int64

EHD2
False    183
Name: EHD2, dtype: int64

EHD3
False    183
Name: EHD3, dtype: int64

EHD4
False    183
Name: EHD4, dtype: int64

EHF
False    183
Name: EHF, dtype: int64

EHHADH
False    183
Name: EHHADH, dtype: int64

EHMT1
False    183
Name: EHMT1, dtype: int64

EHMT2
False    183
Name: EHMT2, dtype: int64

EI24
False    183
Name: EI24, dtype: int64

EID1
False    183
Name: EID1, dtype: int64

EID2B
False    183
Name: EID2B, dtype: int64

EID2
False    183
Name: EID2, dtype: int64

EID3
False    183
Name: EID3, dtype: int64

EIF1AD
False    183
Name: EIF1AD, dtype: int64

EIF1AX
False    183
Name: EIF1AX, dtype: int64

EIF1AY
False    120
True      63
Name: EIF1AY, dtype: int64

EIF1B
False    183
Name: EIF1B, dtype: int64

EIF1
False    183
Name: EIF1, dtype: int64

EIF2AK1
False    183
Name: EIF2AK1, dtype: int64

EIF2AK2
False    183
Name: EIF2AK2, dtype: int64

EIF2AK3
False    183
Name: EIF2AK3, dtype: int64

EIF2AK4
False    183
Name: EIF2AK4, dtype: int64

EIF2A
False    183
Name: EIF2A, dtype: int64

EIF2B1
False    183
Name: EIF2B1, dtype: int64

EIF2B2
False    183
Name: EIF2B2, dtype: int64

EIF2B3
False    183
Name: EIF2B3, dtype: int64

EIF2B4
False    183
Name: EIF2B4, dtype: int64

EIF2B5
False    183
Name: EIF2B5, dtype: int64

EIF2C1
False    183
Name: EIF2C1, dtype: int64

EIF2C2
False    183
Name: EIF2C2, dtype: int64

EIF2C3
False    183
Name: EIF2C3, dtype: int64

EIF2C4
False    183
Name: EIF2C4, dtype: int64

EIF2S1
False    183
Name: EIF2S1, dtype: int64

EIF2S2
False    183
Name: EIF2S2, dtype: int64

EIF2S3
False    183
Name: EIF2S3, dtype: int64

EIF3A
False    183
Name: EIF3A, dtype: int64

EIF3B
False    183
Name: EIF3B, dtype: int64

EIF3CL
False    183
Name: EIF3CL, dtype: int64

EIF3C
False    175
True       8
Name: EIF3C, dtype: int64

EIF3D
False    183
Name: EIF3D, dtype: int64

EIF3E
False    183
Name: EIF3E, dtype: int64

EIF3F
False    183
Name: EIF3F, dtype: int64

EIF3G
False    183
Name: EIF3G, dtype: int64

EIF3H
False    183
Name: EIF3H, dtype: int64

EIF3IP1
False    119
True      64
Name: EIF3IP1, dtype: int64

EIF3I
False    183
Name: EIF3I, dtype: int64

EIF3J
False    183
Name: EIF3J, dtype: int64

EIF3K
False    183
Name: EIF3K, dtype: int64

EIF3L
False    183
Name: EIF3L, dtype: int64

EIF3M
False    183
Name: EIF3M, dtype: int64

EIF4A1
False    183
Name: EIF4A1, dtype: int64

EIF4A2
False    183
Name: EIF4A2, dtype: int64

EIF4A3
False    183
Name: EIF4A3, dtype: int64

EIF4B
False    183
Name: EIF4B, dtype: int64

EIF4E1B
False    99
True     84
Name: EIF4E1B, dtype: int64

EIF4E2
False    183
Name: EIF4E2, dtype: int64

EIF4E3
False    183
Name: EIF4E3, dtype: int64

EIF4EBP1
False    183
Name: EIF4EBP1, dtype: int64

EIF4EBP2
False    183
Name: EIF4EBP2, dtype: int64

EIF4EBP3
False    183
Name: EIF4EBP3, dtype: int64

EIF4ENIF1
False    183
Name: EIF4ENIF1, dtype: int64

EIF4E
False    183
Name: EIF4E, dtype: int64

EIF4G1
False    183
Name: EIF4G1, dtype: int64

EIF4G2
False    183
Name: EIF4G2, dtype: int64

EIF4G3
False    183
Name: EIF4G3, dtype: int64

EIF4H
False    183
Name: EIF4H, dtype: int64

EIF5A2
False    183
Name: EIF5A2, dtype: int64

EIF5AL1
False    183
Name: EIF5AL1, dtype: int64

EIF5A
False    183
Name: EIF5A, dtype: int64

EIF5B
False    183
Name: EIF5B, dtype: int64

EIF5
False    183
Name: EIF5, dtype: int64

EIF6
False    183
Name: EIF6, dtype: int64

ELAC1
False    183
Name: ELAC1, dtype: int64

ELAC2
False    183
Name: ELAC2, dtype: int64

ELANE
False    155
True      28
Name: ELANE, dtype: int64

ELAVL1
False    183
Name: ELAVL1, dtype: int64

ELAVL2
False    173
True      10
Name: ELAVL2, dtype: int64

ELAVL3
False    170
True      13
Name: ELAVL3, dtype: int64

ELAVL4
False    173
True      10
Name: ELAVL4, dtype: int64

ELF1
False    183
Name: ELF1, dtype: int64

ELF2
False    183
Name: ELF2, dtype: int64

ELF3
False    183
Name: ELF3, dtype: int64

ELF4
False    183
Name: ELF4, dtype: int64

ELF5
False    158
True      25
Name: ELF5, dtype: int64

ELFN1
False    183
Name: ELFN1, dtype: int64

ELFN2
False    183
Name: ELFN2, dtype: int64

ELK1
False    183
Name: ELK1, dtype: int64

ELK3
False    183
Name: ELK3, dtype: int64

ELK4
False    183
Name: ELK4, dtype: int64

ELL2
False    183
Name: ELL2, dtype: int64

ELL3
False    183
Name: ELL3, dtype: int64

ELL
False    183
Name: ELL, dtype: int64

ELMO1
False    183
Name: ELMO1, dtype: int64

ELMO2
False    183
Name: ELMO2, dtype: int64

ELMO3
False    183
Name: ELMO3, dtype: int64

ELMOD1
False    178
True       5
Name: ELMOD1, dtype: int64

ELMOD2

False    183
Name: ELMOD2, dtype: int64

ELMOD3
False    183
Name: ELMOD3, dtype: int64

ELN
False    183
Name: ELN, dtype: int64

ELOF1
False    183
Name: ELOF1, dtype: int64

ELOVL1
False    183
Name: ELOVL1, dtype: int64

ELOVL2
False    183
Name: ELOVL2, dtype: int64

ELOVL3
False    175
True       8
Name: ELOVL3, dtype: int64

ELOVL4
False    183
Name: ELOVL4, dtype: int64

ELOVL5
False    183
Name: ELOVL5, dtype: int64

ELOVL6
False    183
Name: ELOVL6, dtype: int64

ELOVL7
False    183
Name: ELOVL7, dtype: int64

ELP2P
False    183
Name: ELP2P, dtype: int64

ELP2
False    183
Name: ELP2, dtype: int64

ELP3
False    183
Name: ELP3, dtype: int64

ELP4
False    183
Name: ELP4, dtype: int64

ELTD1
False    183
Name: ELTD1, dtype: int64

EMB
False    183
Name: EMB, dtype: int64

EMCN
False    183
Name: EMCN, dtype: int64

EMD
False    183
Name: EMD, dtype: int64

EME1
False    183
Name: EME1, dtype: int64

EME2
False    183
Name: EME2, dtype: int64

EMG1
False    183
Name: EMG1, dtype: int64

EMID1
False    183
Name: EMID1, dtype: int64

EMID2
False    181
True       2
Name: EMID2, dtype: int64

EMILIN1
False    183
Name: EMILIN1, dtype: int64

EMILIN2
False    183
Name: EMILIN2, dtype: int64

EMILIN3
False    183
Name: EMILIN3, dtype: int64

EML1
False    183
Name: EML1, dtype: int64

EML2
False    183
Name: EML2, dtype: int64

EML3
False    183
Name: EML3, dtype: int64

EML4
False    183
Name: EML4, dtype: int64

EML5
False    183
Name: EML5, dtype: int64

EML6
False    183
Name: EML6, dtype: int64

EMP1
False    183
Name: EMP1, dtype: int64

EMP2
False    183
Name: EMP2, dtype: int64

EMP3
False    183
Name: EMP3, dtype: int64

EMR1
False    180
True       3
Name: EMR1, dtype: int64

EMR2
False    183
Name: EMR2, dtype: int64

EMR3
False    168
True      15
Name: EMR3, dtype: int64

EMR4P
False    177
True       6
Name: EMR4P, dtype: int64

EMX1
False    145
True      38
Name: EMX1, dtype: int64

EMX2OS
False    174
True       9
Name: EMX2OS, dtype: int64

EMX2
False    171
True      12
Name: EMX2, dtype: int64

EN1
False    173
True      10
Name: EN1, dtype: int64

EN2
False    143
True      40
Name: EN2, dtype: int64

ENAH
False    183
Name: ENAH, dtype: int64

ENAM
False    177
True       6
Name: ENAM, dtype: int64

ENC1
False    183
Name: ENC1, dtype: int64

ENDOD1
False    183
Name: ENDOD1, dtype: int64

ENDOG
False    183
Name: ENDOG, dtype: int64

ENDOU
False    177
True       6
Name: ENDOU, dtype: int64

ENGASE
False    183
Name: ENGASE, dtype: int64

ENG
False    183
Name: ENG, dtype: int64

ENHO
False    182
True       1
Name: ENHO, dtype: int64

ENKUR
False    183
Name: ENKUR, dtype: int64

ENO1
False    183
Name: ENO1, dtype: int64

ENO2
False    183
Name: ENO2, dtype: int64

ENO3
False    183
Name: ENO3, dtype: int64

ENOPH1
False    183
Name: ENOPH1, dtype: int64

ENOSF1
False    183
Name: ENOSF1, dtype: int64

ENOX1
False    183
Name: ENOX1, dtype: int64

ENOX2
False    183
Name: ENOX2, dtype: int64

ENPEP
False    183
Name: ENPEP, dtype: int64

ENPP1
False    183
Name: ENPP1, dtype: int64

ENPP2
False    183
Name: ENPP2, dtype: int64

ENPP3
False    177
True       6
Name: ENPP3, dtype: int64

ENPP4
False    183
Name: ENPP4, dtype: int64

ENPP5
False    183
Name: ENPP5, dtype: int64

ENPP6
False    180
True       3
Name: ENPP6, dtype: int64

ENPP7
False    121
True      62
Name: ENPP7, dtype: int64

ENSA
False    183
Name: ENSA, dtype: int64

ENTHD1
False    171
True      12
Name: ENTHD1, dtype: int64

ENTPD1
False    183
Name: ENTPD1, dtype: int64

ENTPD2
False    183
Name: ENTPD2, dtype: int64

ENTPD3
False    183
Name: ENTPD3, dtype: int64

ENTPD4
False    183
Name: ENTPD4, dtype: int64

ENTPD5
False    183
Name: ENTPD5, dtype: int64

ENTPD6
False    183
Name: ENTPD6, dtype: int64

ENTPD7
False    183
Name: ENTPD7, dtype: int64

ENTPD8
False    183
Name: ENTPD8, dtype: int64

ENY2
False    183
Name: ENY2, dtype: int64

EOMES
False    179
True       4
Name: EOMES, dtype: int64

EP300
False    183
Name: EP300, dtype: int64

EP400NL
False    183
Name: EP400NL, dtype: int64

EP400
False    183
Name: EP400, dtype: int64

EPAS1
False    183
Name: EPAS1, dtype: int64

EPB41L1
False    183
Name: EPB41L1, dtype: int64

EPB41L2
False    183
Name: EPB41L2, dtype: int64

EPB41L3
False    183
Name: EPB41L3, dtype: int64

EPB41L4A
False    183
Name: EPB41L4A, dtype: int64

EPB41L4B
False    183
Name: EPB41L4B, dtype: int64

EPB41L5
False    183
Name: EPB41L5, dtype: int64

EPB41
False    183
Name: EPB41, dtype: int64

EPB42
True     126
False     57
Name: EPB42, dtype: int64

EPB49
False    183
Name: EPB49, dtype: int64

EPC1
False    183
Name: EPC1, dtype: int64

EPC2
False    183
Name: EPC2, dtype: int64

EPCAM
False    183
Name: EPCAM, dtype: int64

EPDR1
False    183
Name: EPDR1, dtype: int64

EPHA10
False    183
Name: EPHA10, dtype: int64

EPHA1
False    183
Name: EPHA1, dtype: int64

EPHA2
False    183
Name: EPHA2, dtype: int64

EPHA3
False    183
Name: EPHA3, dtype: int64

EPHA4
False    183
Name: EPHA4, dtype: int64

EPHA5
False    166
True      17
Name: EPHA5, dtype: int64

EPHA6
False    178
True       5
Name: EPHA6, dtype: int64

EPHA7
False    179
True       4
Name: EPHA7, dtype: int64

EPHA8
False    166
True      17
Name: EPHA8, dtype: int64

EPHB1
False    183
Name: EPHB1, dtype: int64

EPHB2
False    183
Name: EPHB2, dtype: int64

EPHB3
False    183
Name: EPHB3, dtype: int64

EPHB4
False    183
Name: EPHB4, dtype: int64

EPHB6
False    183
Name: EPHB6, dtype: int64

EPHX1
False    183
Name: EPHX1, dtype: int64

EPHX2
False    183
Name: EPHX2, dtype: int64

EPHX3
False    182
True       1
Name: EPHX3, dtype: int64

EPHX4
False    183
Name: EPHX4, dtype: int64

EPM2AIP1
False    183
Name: EPM2AIP1, dtype: int64

EPM2A
False    183
Name: EPM2A, dtype: int64

EPN1
False    183
Name: EPN1, dtype: int64

EPN2
False    183
Name: EPN2, dtype: int64

EPN3
False    181
True       2
Name: EPN3, dtype: int64

EPOR
False    183
Name: EPOR, dtype: int64

EPO
False    149
True      34
Name: EPO, dtype: int64

EPPK1
False    183
Name: EPPK1, dtype: int64

EPR1
False    182
True       1
Name: EPR1, dtype: int64

EPRS
False    183
Name: EPRS, dtype: int64

EPS15L1
False    183
Name: EPS15L1, dtype: int64

EPS15
False    183
Name: EPS15, dtype: int64

EPS8L1
False    183
Name: EPS8L1, dtype: int64

EPS8L2
False    183
Name: EPS8L2, dtype: int64

EPS8L3
False    181
True       2
Name: EPS8L3, dtype: int64

EPS8
False    183
Name: EPS8, dtype: int64

EPSTI1
False    183
Name: EPSTI1, dtype: int64

EPT1
False    183
Name: EPT1, dtype: int64

EPX
False    135
True      48
Name: EPX, dtype: int64

EPYC
False    162
True      21
Name: EPYC, dtype: int64

ERAL1
False    183
Name: ERAL1, dtype: int64

ERAP1
False    183
Name: ERAP1, dtype: int64

ERAP2
False    183
Name: ERAP2, dtype: int64

ERAS
False    142
True      41
Name: ERAS, dtype: int64

ERBB2IP
False    183
Name: ERBB2IP, dtype: int64

ERBB2
False    183
Name: ERBB2, dtype: int64

ERBB3
False    183
Name: ERBB3, dtype: int64

ERBB4
False    180
True       3
Name: ERBB4, dtype: int64

ERC1
False    183
Name: ERC1, dtype: int64

ERC2
False    182
True       1
Name: ERC2, dtype: int64

ERCC1
False    183
Name: ERCC1, dtype: int64

ERCC2
False    183
Name: ERCC2, dtype: int64

ERCC3
False    183
Name: ERCC3, dtype: int64

ERCC4
False    183
Name: ERCC4, dtype: int64

ERCC5
False    183
Name: ERCC5, dtype: int64

ERCC6L
False    183
Name: ERCC6L, dtype: int64

ERCC6
False    183
Name: ERCC6, dtype: int64

ERCC8
False    183
Name: ERCC8, dtype: int64

EREG
False    178
True       5
Name: EREG, dtype: int64

ERF
False    183
Name: ERF, dtype: int64

ERGIC1
False    183
Name: ERGIC1, dtype: int64

ERGIC2
False    183
Name: ERGIC2, dtype: int64

ERGIC3
False    183
Name: ERGIC3, dtype: int64

ERG
False    183
Name: ERG, dtype: int64

ERH
False    183
Name: ERH, dtype: int64

ERI1
False    183
Name: ERI1, dtype: int64

ERI2
False    183
Name: ERI2, dtype: int64

ERI3
False    183
Name: ERI3, dtype: int64

ERICH1
False    183
Name: ERICH1, dtype: int64

ERLEC1
False    183
Name: ERLEC1, dtype: int64

ERLIN1
False    183
Name: ERLIN1, dtype: int64

ERLIN2
False    183
Name: ERLIN2, dtype: int64

ERMAP
False    183
Name: ERMAP, dtype: int64

ERMN
False    182
True       1
Name: ERMN, dtype: int64

ERMP1
False    183
Name: ERMP1, dtype: int64

ERN1
False    183
Name: ERN1, dtype: int64

ERN2
False    177
True       6
Name: ERN2, dtype: int64

ERO1LB
False    183
Name: ERO1LB, dtype: int64

ERO1L
False    183
Name: ERO1L, dtype: int64

ERP27
False    183
Name: ERP27, dtype: int64

ERP29
False    183
Name: ERP29, dtype: int64

ERP44

False    183
Name: ERP44, dtype: int64

ERRFI1
False    183
Name: ERRFI1, dtype: int64

ERVFRDE1
False    176
True       7
Name: ERVFRDE1, dtype: int64

ESAM
False    183
Name: ESAM, dtype: int64

ESCO1
False    183
Name: ESCO1, dtype: int64

ESCO2
False    183
Name: ESCO2, dtype: int64

ESD
False    183
Name: ESD, dtype: int64

ESF1
False    183
Name: ESF1, dtype: int64

ESM1
False    183
Name: ESM1, dtype: int64

ESPL1
False    183
Name: ESPL1, dtype: int64

ESPNL
False    183
Name: ESPNL, dtype: int64

ESPNP
False    160
True      23
Name: ESPNP, dtype: int64

ESPN
False    183
Name: ESPN, dtype: int64

ESR1
False    183
Name: ESR1, dtype: int64

ESR2
False    183
Name: ESR2, dtype: int64

ESRP1
False    183
Name: ESRP1, dtype: int64

ESRP2
False    183
Name: ESRP2, dtype: int64

ESRRA
False    183
Name: ESRRA, dtype: int64

ESRRB
False    176
True       7
Name: ESRRB, dtype: int64

ESRRG
False    183
Name: ESRRG, dtype: int64

ESYT1
False    183
Name: ESYT1, dtype: int64

ESYT2
False    183
Name: ESYT2, dtype: int64

ESYT3
False    182
True       1
Name: ESYT3, dtype: int64

ETAA1
False    183
Name: ETAA1, dtype: int64

ETF1
False    183
Name: ETF1, dtype: int64

ETFA
False    183
Name: ETFA, dtype: int64

ETFB
False    183
Name: ETFB, dtype: int64

ETFDH
False    183
Name: ETFDH, dtype: int64

ETHE1
False    183
Name: ETHE1, dtype: int64

ETNK1
False    183
Name: ETNK1, dtype: int64

ETNK2
False    183
Name: ETNK2, dtype: int64

ETS1
False    183
Name: ETS1, dtype: int64

ETS2
False    183
Name: ETS2, dtype: int64

ETV1
False    183
Name: ETV1, dtype: int64

ETV2
False    183
Name: ETV2, dtype: int64

ETV3L
False    171
True      12
Name: ETV3L, dtype: int64

ETV3
False    183
Name: ETV3, dtype: int64

ETV4
False    183
Name: ETV4, dtype: int64

ETV5
False    183
Name: ETV5, dtype: int64

ETV6
False    183
Name: ETV6, dtype: int64

ETV7
False    183
Name: ETV7, dtype: int64

EVC2
False    183
Name: EVC2, dtype: int64

EVC
False    183
Name: EVC, dtype: int64

EVI2A
False    183
Name: EVI2A, dtype: int64

EVI2B
False    183
Name: EVI2B, dtype: int64

EVI5L
False    183
Name: EVI5L, dtype: int64

EVI5
False    183
Name: EVI5, dtype: int64

EVL
False    183
Name: EVL, dtype: int64

EVPLL
False    162
True      21
Name: EVPLL, dtype: int64

EVPL
False    183
Name: EVPL, dtype: int64

EVX1
False    98
True     85
Name: EVX1, dtype: int64

EWSR1
False    183
Name: EWSR1, dtype: int64

EXD1
True     108
False     75
Name: EXD1, dtype: int64

EXD2
False    183
Name: EXD2, dtype: int64

EXD3
False    183
Name: EXD3, dtype: int64

EXO1
False    183
Name: EXO1, dtype: int64

EXOC1
False    183
Name: EXOC1, dtype: int64

EXOC2
False    183
Name: EXOC2, dtype: int64

EXOC3L2
False    183
Name: EXOC3L2, dtype: int64

EXOC3L
False    183
Name: EXOC3L, dtype: int64

EXOC3
False    183
Name: EXOC3, dtype: int64

EXOC4
False    183
Name: EXOC4, dtype: int64

EXOC5
False    183
Name: EXOC5, dtype: int64

EXOC6B
False    183
Name: EXOC6B, dtype: int64

EXOC6
False    183
Name: EXOC6, dtype: int64

EXOC7
False    183
Name: EXOC7, dtype: int64

EXOC8
False    183
Name: EXOC8, dtype: int64

EXOG
False    183
Name: EXOG, dtype: int64

EXOSC10
False    183
Name: EXOSC10, dtype: int64

EXOSC1
False    183
Name: EXOSC1, dtype: int64

EXOSC2
False    183
Name: EXOSC2, dtype: int64

EXOSC3
False    183
Name: EXOSC3, dtype: int64

EXOSC4
False    183
Name: EXOSC4, dtype: int64

EXOSC5
False    183
Name: EXOSC5, dtype: int64

EXOSC6
False    183
Name: EXOSC6, dtype: int64

EXOSC7
False    183
Name: EXOSC7, dtype: int64

EXOSC8
False    183
Name: EXOSC8, dtype: int64

EXOSC9
False    183
Name: EXOSC9, dtype: int64

EXPH5
False    183
Name: EXPH5, dtype: int64

EXT1
False    183
Name: EXT1, dtype: int64

EXT2
False    183
Name: EXT2, dtype: int64

EXTL1
False    182
True       1
Name: EXTL1, dtype: int64

EXTL2
False    183
Name: EXTL2, dtype: int64

EXTL3
False    183
Name: EXTL3, dtype: int64

EYA1
False    181
True       2
Name: EYA1, dtype: int64

EYA2
False    183
Name: EYA2, dtype: int64

EYA3
False    183
Name: EYA3, dtype: int64

EYA4
False    179
True       4
Name: EYA4, dtype: int64

EYS
False    183
Name: EYS, dtype: int64

EZH1
False    183
Name: EZH1, dtype: int64

EZH2
False    183
Name: EZH2, dtype: int64

EZR
False    183
Name: EZR, dtype: int64

F10
False    183
Name: F10, dtype: int64

F11R
False    183
Name: F11R, dtype: int64

F11
False    172
True      11
Name: F11, dtype: int64

F12
False    183
Name: F12, dtype: int64

F13A1
False    183
Name: F13A1, dtype: int64

F2RL1
False    183
Name: F2RL1, dtype: int64

F2RL2
False    183
Name: F2RL2, dtype: int64

F2RL3
False    183
Name: F2RL3, dtype: int64

F2R
False    183
Name: F2R, dtype: int64

F2
False    127
True      56
Name: F2, dtype: int64

F3
False    183
Name: F3, dtype: int64

F5
False    183
Name: F5, dtype: int64

F7
False    179
True       4
Name: F7, dtype: int64

F8A1
False    183
Name: F8A1, dtype: int64

F8
False    183
Name: F8, dtype: int64

FA2H
False    183
Name: FA2H, dtype: int64

FAAH2
False    183
Name: FAAH2, dtype: int64

FAAH
False    183
Name: FAAH, dtype: int64

FABP1
False    144
True      39
Name: FABP1, dtype: int64

FABP2
False    133
True      50
Name: FABP2, dtype: int64

FABP3
False    183
Name: FABP3, dtype: int64

FABP4
False    183
Name: FABP4, dtype: int64

FABP5L3
False    114
True      69
Name: FABP5L3, dtype: int64

FABP5
False    183
Name: FABP5, dtype: int64

FABP6
False    158
True      25
Name: FABP6, dtype: int64

FABP7
False    123
True      60
Name: FABP7, dtype: int64

FADD
False    183
Name: FADD, dtype: int64

FADS1
False    183
Name: FADS1, dtype: int64

FADS2
False    183
Name: FADS2, dtype: int64

FADS3
False    183
Name: FADS3, dtype: int64

FADS6
False    96
True     87
Name: FADS6, dtype: int64

FAF1
False    183
Name: FAF1, dtype: int64

FAF2
False    183
Name: FAF2, dtype: int64

FAHD1
False    183
Name: FAHD1, dtype: int64

FAHD2A
False    183
Name: FAHD2A, dtype: int64

FAHD2B
False    183
Name: FAHD2B, dtype: int64

FAH
False    183
Name: FAH, dtype: int64

FAIM2
False    183
Name: FAIM2, dtype: int64

FAIM3
False    183
Name: FAIM3, dtype: int64

FAIM
False    183
Name: FAIM, dtype: int64

FAM100A
False    183
Name: FAM100A, dtype: int64

FAM100B
False    183
Name: FAM100B, dtype: int64

FAM101A
False    183
Name: FAM101A, dtype: int64

FAM101B
False    183
Name: FAM101B, dtype: int64

FAM102A
False    183
Name: FAM102A, dtype: int64

FAM102B
False    183
Name: FAM102B, dtype: int64

FAM103A1
False    183
Name: FAM103A1, dtype: int64

FAM104A
False    183
Name: FAM104A, dtype: int64

FAM104B
False    183
Name: FAM104B, dtype: int64

FAM105A
False    183
Name: FAM105A, dtype: int64

FAM105B
False    183
Name: FAM105B, dtype: int64

FAM106A
False    151
True      32
Name: FAM106A, dtype: int64

FAM106C
False    166
True      17
Name: FAM106C, dtype: int64

FAM107A
False    183
Name: FAM107A, dtype: int64

FAM107B
False    183
Name: FAM107B, dtype: int64

FAM108A1
False    183
Name: FAM108A1, dtype: int64

FAM108B1
False    183
Name: FAM108B1, dtype: int64

FAM108C1
False    183
Name: FAM108C1, dtype: int64

FAM109A
False    183
Name: FAM109A, dtype: int64

FAM109B
False    183
Name: FAM109B, dtype: int64

FAM10A4
False    183
Name: FAM10A4, dtype: int64

FAM110A
False    183
Name: FAM110A, dtype: int64

FAM110B
False    183
Name: FAM110B, dtype: int64

FAM110C
False    183
Name: FAM110C, dtype: int64

FAM111A
False    183
Name: FAM111A, dtype: int64

FAM111B
False    183
Name: FAM111B, dtype: int64

FAM113A
False    183
Name: FAM113A, dtype: int64

FAM113B
False    183
Name: FAM113B, dtype: int64

FAM114A1
False    183
Name: FAM114A1, dtype: int64

FAM114A2
False    183
Name: FAM114A2, dtype: int64

FAM115A
False    183
Name: FAM115A, dtype: int64

FAM115C
False    183
Name: FAM115C, dtype: int64

FAM116A
False    183
Name: FAM116A, dtype: int64

FAM116B
False    183
Name: FAM116B, dtype: int64

FAM117A
False    183
Name: FAM117A, dtype: int64

FAM117B
False    183
Name: FAM117B, dtype: int64

FAM118A
False    183
Name: FAM118A, dtype: int64

FAM118B
False    183
Name: FAM118B, dtype: int64

FAM119A
False    183
Name: FAM119A, dtype: int64

FAM119B
False    183
Name: FAM119B, dtype: int64

FAM120AOS
False    183
Name: FAM120AOS, dtype: int64

FAM120A
False    183
Name: FAM120A, dtype: int64

FAM120B
False    183
Name: FAM120B, dtype: int64

FAM120C
False    183
Name: FAM120C, dtype: int64

FAM122A
False    183

Name: FAM122A, dtype: int64

FAM122B
False    183
Name: FAM122B, dtype: int64

FAM122C
False    183
Name: FAM122C, dtype: int64

FAM123A
False    106
True      77
Name: FAM123A, dtype: int64

FAM123B
False    183
Name: FAM123B, dtype: int64

FAM123C
False    176
True       7
Name: FAM123C, dtype: int64

FAM124A
False    183
Name: FAM124A, dtype: int64

FAM124B
False    183
Name: FAM124B, dtype: int64

FAM125A
False    183
Name: FAM125A, dtype: int64

FAM125B
False    183
Name: FAM125B, dtype: int64

FAM126A
False    183
Name: FAM126A, dtype: int64

FAM126B
False    183
Name: FAM126B, dtype: int64

FAM127A
False    183
Name: FAM127A, dtype: int64

FAM127B
False    183
Name: FAM127B, dtype: int64

FAM127C
False    183
Name: FAM127C, dtype: int64

FAM128A
False    183
Name: FAM128A, dtype: int64

FAM128B
False    183
Name: FAM128B, dtype: int64

FAM129A
False    183
Name: FAM129A, dtype: int64

FAM129B
False    183
Name: FAM129B, dtype: int64

FAM129C
False    172
True      11
Name: FAM129C, dtype: int64

FAM131A
False    183
Name: FAM131A, dtype: int64

FAM131B
False    183
Name: FAM131B, dtype: int64

FAM131C
False    183
Name: FAM131C, dtype: int64

FAM132A
False    181
True       2
Name: FAM132A, dtype: int64

FAM133A
False    180
True       3
Name: FAM133A, dtype: int64

FAM133B
False    183
Name: FAM133B, dtype: int64

FAM134A
False    183
Name: FAM134A, dtype: int64

FAM134B
False    183
Name: FAM134B, dtype: int64

FAM134C
False    183
Name: FAM134C, dtype: int64

FAM135A
False    183
Name: FAM135A, dtype: int64

FAM135B
False    174
True       9
Name: FAM135B, dtype: int64

FAM136A
False    183
Name: FAM136A, dtype: int64

FAM136B
True     114
False     69
Name: FAM136B, dtype: int64

FAM138F
False    118
True      65
Name: FAM138F, dtype: int64

FAM13AOS
False    183
Name: FAM13AOS, dtype: int64

FAM13A
False    183
Name: FAM13A, dtype: int64

FAM13B
False    183
Name: FAM13B, dtype: int64

FAM13C
False    182
True       1
Name: FAM13C, dtype: int64

FAM149A
False    183
Name: FAM149A, dtype: int64

FAM149B1
False    183
Name: FAM149B1, dtype: int64

FAM150A
False    170
True      13
Name: FAM150A, dtype: int64

FAM150B
False    181
True       2
Name: FAM150B, dtype: int64

FAM151A
False    146
True      37
Name: FAM151A, dtype: int64

FAM151B
False    183
Name: FAM151B, dtype: int64

FAM153A
False    181
True       2
Name: FAM153A, dtype: int64

FAM153B
False    170
True      13
Name: FAM153B, dtype: int64

FAM153C
False    109
True      74
Name: FAM153C, dtype: int64

FAM154A
False    92
True     91
Name: FAM154A, dtype: int64

FAM154B
False    183
Name: FAM154B, dtype: int64

FAM155A
False    183
Name: FAM155A, dtype: int64

FAM155B
False    183
Name: FAM155B, dtype: int64

FAM156A
False    183
Name: FAM156A, dtype: int64

FAM157A
False    182
True       1
Name: FAM157A, dtype: int64

FAM157B
False    145
True      38
Name: FAM157B, dtype: int64

FAM158A
False    183
Name: FAM158A, dtype: int64

FAM159A
False    180
True       3
Name: FAM159A, dtype: int64

FAM160A1
False    183
Name: FAM160A1, dtype: int64

FAM160A2
False    183
Name: FAM160A2, dtype: int64

FAM160B1
False    183
Name: FAM160B1, dtype: int64

FAM160B2
False    183
Name: FAM160B2, dtype: int64

FAM161A
False    183
Name: FAM161A, dtype: int64

FAM161B
False    183
Name: FAM161B, dtype: int64

FAM162A
False    183
Name: FAM162A, dtype: int64

FAM162B
False    182
True       1
Name: FAM162B, dtype: int64

FAM163A
False    182
True       1
Name: FAM163A, dtype: int64

FAM163B
True     108
False     75
Name: FAM163B, dtype: int64

FAM164A
False    183
Name: FAM164A, dtype: int64

FAM164C
False    183
Name: FAM164C, dtype: int64

FAM165B
False    183
Name: FAM165B, dtype: int64

FAM166A
False    115
True      68
Name: FAM166A, dtype: int64

FAM166B
False    176
True       7
Name: FAM166B, dtype: int64

FAM167A
False    183
Name: FAM167A, dtype: int64

FAM167B
False    183
Name: FAM167B, dtype: int64

FAM168A
False    183
Name: FAM168A, dtype: int64

FAM168B
False    183
Name: FAM168B, dtype: int64

FAM169A
False    183
Name: FAM169A, dtype: int64

FAM169B
False    167
True      16
Name: FAM169B, dtype: int64

FAM170A
True     112
False     71
Name: FAM170A, dtype: int64

FAM170B
True     98
False    85
Name: FAM170B, dtype: int64

FAM171A1
False    183
Name: FAM171A1, dtype: int64

FAM171A2
False    183
Name: FAM171A2, dtype: int64

FAM171B
False    183
Name: FAM171B, dtype: int64

FAM172A
False    183
Name: FAM172A, dtype: int64

FAM173A
False    183
Name: FAM173A, dtype: int64

FAM173B
False    183
Name: FAM173B, dtype: int64

FAM174A
False    183
Name: FAM174A, dtype: int64

FAM174B
False    183
Name: FAM174B, dtype: int64

FAM175A
False    183
Name: FAM175A, dtype: int64

FAM175B
False    183
Name: FAM175B, dtype: int64

FAM176A
False    183
Name: FAM176A, dtype: int64

FAM176B
False    183
Name: FAM176B, dtype: int64

FAM177A1
False    183
Name: FAM177A1, dtype: int64

FAM177B
False    182
True       1
Name: FAM177B, dtype: int64

FAM178A
False    183
Name: FAM178A, dtype: int64

FAM178B
False    178
True       5
Name: FAM178B, dtype: int64

FAM179A
False    183
Name: FAM179A, dtype: int64

FAM179B
False    183
Name: FAM179B, dtype: int64

FAM180A
False    183
Name: FAM180A, dtype: int64

FAM180B
False    161
True      22
Name: FAM180B, dtype: int64

FAM181B
False    181
True       2
Name: FAM181B, dtype: int64

FAM182A
False    134
True      49
Name: FAM182A, dtype: int64

FAM182B
False    183
Name: FAM182B, dtype: int64

FAM183A
False    116
True      67
Name: FAM183A, dtype: int64

FAM183B
False    143
True      40
Name: FAM183B, dtype: int64

FAM184A
False    183
Name: FAM184A, dtype: int64

FAM184B
False    94
True     89
Name: FAM184B, dtype: int64

FAM185A
False    183
Name: FAM185A, dtype: int64

FAM186A
False    182
True       1
Name: FAM186A, dtype: int64

FAM186B
False    183
Name: FAM186B, dtype: int64

FAM187B
False    92
True     91
Name: FAM187B, dtype: int64

FAM188A
False    183
Name: FAM188A, dtype: int64

FAM188B
False    183
Name: FAM188B, dtype: int64

FAM189A1
False    183
Name: FAM189A1, dtype: int64

FAM189A2
False    183
Name: FAM189A2, dtype: int64

FAM189B
False    183
Name: FAM189B, dtype: int64

FAM18A
False    183
Name: FAM18A, dtype: int64

FAM18B2
False    183
Name: FAM18B2, dtype: int64

FAM18B
False    183
Name: FAM18B, dtype: int64

FAM190A
False    183
Name: FAM190A, dtype: int64

FAM190B
False    183
Name: FAM190B, dtype: int64

FAM192A
False    183
Name: FAM192A, dtype: int64

FAM193A
False    183
Name: FAM193A, dtype: int64

FAM193B
False    183
Name: FAM193B, dtype: int64

FAM194A
False    149
True      34
Name: FAM194A, dtype: int64

FAM195A
False    183
Name: FAM195A, dtype: int64

FAM195B
False    183
Name: FAM195B, dtype: int64

FAM196A
False    183
Name: FAM196A, dtype: int64

FAM196B
False    165
True      18
Name: FAM196B, dtype: int64

FAM198A
False    183
Name: FAM198A, dtype: int64

FAM198B
False    183
Name: FAM198B, dtype: int64

FAM199X
False    183
Name: FAM199X, dtype: int64

FAM19A1
False    161
True      22
Name: FAM19A1, dtype: int64

FAM19A2
False    182
True       1
Name: FAM19A2, dtype: int64

FAM19A3
False    167
True      16
Name: FAM19A3, dtype: int64

FAM19A4
False    124
True      59
Name: FAM19A4, dtype: int64

FAM19A5
False    183
Name: FAM19A5, dtype: int64

FAM200A
False    183
Name: FAM200A, dtype: int64

FAM200B
False    183
Name: FAM200B, dtype: int64

FAM20A
False    183
Name: FAM20A, dtype: int64

FAM20B
False    183
Name: FAM20B, dtype: int64

FAM20C
False    183
Name: FAM20C, dtype: int64

FAM21A
False    182
True       1
Name: FAM21A, dtype: int64

FAM21B
False    183
Name: FAM21B, dtype: int64

FAM21C
False    183
Name: FAM21C, dtype: int64

FAM22A
False    183
Name: FAM22A, dtype: int64

FAM22D
False    183
Name: FAM22D, dtype: int64

FAM22F
False    183
Name: FAM22F, dtype: int64

FAM22G
False    183
Name: FAM22G, dtype: int64

FAM23A
False    183
Name: FAM23A, dtype: int64

FAM24B
False    183
Name: FAM24B, dtype: int64

FAM25A
False    105
True      78
Name: FAM25A, dtype: int64

FAM25B
False    97
True     86
Name: FAM25B, dtype: int64

FAM26E
False    183
Name: FAM26E, dtype: int64

FAM26F
False    183
Name: FAM26F, dtype: int64

FAM27A
False    183
Name: FAM27A, dtype: int64

FAM27C
False    183
Name: FAM27C, dtype: int64

FAM32A
False    183
Name: FAM32A, dtype: int64

FAM35A
False    183
Name: FAM35A, dtype: int64

FAM35B2
False    183
Name: FAM35B2, dtype: int64

FAM35B
False    183
Name: FAM35B, dtype: int64

FAM36A
False    183
Name: FAM36A, dtype: int64

FAM38A
False    183
Name: FAM38A, dtype: int64

FAM38B
False    182
True       1
Name: FAM38B, dtype: int64

FAM3A
False    183
Name: FAM3A, dtype: int64

FAM3B
False    183
Name: FAM3B, dtype: int64

FAM3C
False    183
Name: FAM3C, dtype: int64

FAM3D
False    183
Name: FAM3D, dtype: int64

FAM40A
False    183
Name: FAM40A, dtype: int64

FAM40B
False    183
Name: FAM40B, dtype: int64

FAM41C
False    183
Name: FAM41C, dtype: int64

FAM43A
False    183
Name: FAM43A, dtype: int64

FAM43B
False    183
Name: FAM43B, dtype: int64

FAM45A
False    183
Name: FAM45A, dtype: int64

FAM45B

False    183
Name: FAM45B, dtype: int64

FAM46A
False    183
Name: FAM46A, dtype: int64

FAM46B
False    183
Name: FAM46B, dtype: int64

FAM46C
False    183
Name: FAM46C, dtype: int64

FAM47C
True     107
False     76
Name: FAM47C, dtype: int64

FAM47E
False    182
True       1
Name: FAM47E, dtype: int64

FAM48A
False    183
Name: FAM48A, dtype: int64

FAM48B1
False    136
True      47
Name: FAM48B1, dtype: int64

FAM48B2
False    125
True      58
Name: FAM48B2, dtype: int64

FAM49A
False    183
Name: FAM49A, dtype: int64

FAM49B
False    183
Name: FAM49B, dtype: int64

FAM50A
False    183
Name: FAM50A, dtype: int64

FAM50B
False    183
Name: FAM50B, dtype: int64

FAM53A
False    183
Name: FAM53A, dtype: int64

FAM53B
False    183
Name: FAM53B, dtype: int64

FAM53C
False    183
Name: FAM53C, dtype: int64

FAM54A
False    183
Name: FAM54A, dtype: int64

FAM54B
False    183
Name: FAM54B, dtype: int64

FAM55B
False    134
True      49
Name: FAM55B, dtype: int64

FAM55C
False    183
Name: FAM55C, dtype: int64

FAM55D
False    121
True      62
Name: FAM55D, dtype: int64

FAM57A
False    183
Name: FAM57A, dtype: int64

FAM57B
False    180
True       3
Name: FAM57B, dtype: int64

FAM58A
False    183
Name: FAM58A, dtype: int64

FAM58B
True     113
False     70
Name: FAM58B, dtype: int64

FAM59A
False    183
Name: FAM59A, dtype: int64

FAM5B
False    162
True      21
Name: FAM5B, dtype: int64

FAM5C
False    160
True      23
Name: FAM5C, dtype: int64

FAM60A
False    183
Name: FAM60A, dtype: int64

FAM63A
False    183
Name: FAM63A, dtype: int64

FAM63B
False    183
Name: FAM63B, dtype: int64

FAM64A
False    182
True       1
Name: FAM64A, dtype: int64

FAM65A
False    183
Name: FAM65A, dtype: int64

FAM65B
False    183
Name: FAM65B, dtype: int64

FAM65C
False    183
Name: FAM65C, dtype: int64

FAM66A
False    150
True      33
Name: FAM66A, dtype: int64

FAM66C
False    183
Name: FAM66C, dtype: int64

FAM66D
False    174
True       9
Name: FAM66D, dtype: int64

FAM66E
False    135
True      48
Name: FAM66E, dtype: int64

FAM69A
False    183
Name: FAM69A, dtype: int64

FAM69B
False    183
Name: FAM69B, dtype: int64

FAM69C
False    181
True       2
Name: FAM69C, dtype: int64

FAM70A
False    183
Name: FAM70A, dtype: int64

FAM70B
False    183
Name: FAM70B, dtype: int64

FAM71A
True     103
False     80
Name: FAM71A, dtype: int64

FAM71D
False    183
Name: FAM71D, dtype: int64

FAM71E1
False    183
Name: FAM71E1, dtype: int64

FAM71E2
False    130
True      53
Name: FAM71E2, dtype: int64

FAM71F1
False    105
True      78
Name: FAM71F1, dtype: int64

FAM71F2
False    182
True       1
Name: FAM71F2, dtype: int64

FAM72A
False    179
True       4
Name: FAM72A, dtype: int64

FAM72B
False    183
Name: FAM72B, dtype: int64

FAM72D
False    183
Name: FAM72D, dtype: int64

FAM73A
False    183
Name: FAM73A, dtype: int64

FAM73B
False    183
Name: FAM73B, dtype: int64

FAM75C1
False    142
True      41
Name: FAM75C1, dtype: int64

FAM76A
False    183
Name: FAM76A, dtype: int64

FAM76B
False    183
Name: FAM76B, dtype: int64

FAM78A
False    183
Name: FAM78A, dtype: int64

FAM78B
False    183
Name: FAM78B, dtype: int64

FAM7A2
False    163
True      20
Name: FAM7A2, dtype: int64

FAM7A3
False    182
True       1
Name: FAM7A3, dtype: int64

FAM81A
False    183
Name: FAM81A, dtype: int64

FAM81B
False    177
True       6
Name: FAM81B, dtype: int64

FAM82A1
False    183
Name: FAM82A1, dtype: int64

FAM82A2
False    183
Name: FAM82A2, dtype: int64

FAM82B
False    183
Name: FAM82B, dtype: int64

FAM83A
False    178
True       5
Name: FAM83A, dtype: int64

FAM83B
False    179
True       4
Name: FAM83B, dtype: int64

FAM83C
False    127
True      56
Name: FAM83C, dtype: int64

FAM83D
False    183
Name: FAM83D, dtype: int64

FAM83E
False    183
Name: FAM83E, dtype: int64

FAM83F
False    182
True       1
Name: FAM83F, dtype: int64

FAM83G
False    183
Name: FAM83G, dtype: int64

FAM83H
False    183
Name: FAM83H, dtype: int64

FAM84A
False    183
Name: FAM84A, dtype: int64

FAM84B
False    183
Name: FAM84B, dtype: int64

FAM86A
False    183
Name: FAM86A, dtype: int64

FAM86B1
False    183
Name: FAM86B1, dtype: int64

FAM86B2
False    176
True       7
Name: FAM86B2, dtype: int64

FAM86C
False    183
Name: FAM86C, dtype: int64

FAM86D
False    183
Name: FAM86D, dtype: int64

FAM89A
False    183
Name: FAM89A, dtype: int64

FAM89B
False    183
Name: FAM89B, dtype: int64

FAM8A1
False    183
Name: FAM8A1, dtype: int64

FAM90A1
False    180
True       3
Name: FAM90A1, dtype: int64

FAM91A1
False    183
Name: FAM91A1, dtype: int64

FAM92A1
False    183
Name: FAM92A1, dtype: int64

FAM92B
False    161
True      22
Name: FAM92B, dtype: int64

FAM95B1
False    183
Name: FAM95B1, dtype: int64

FAM96A
False    183
Name: FAM96A, dtype: int64

FAM96B
False    183
Name: FAM96B, dtype: int64

FAM98A
False    183
Name: FAM98A, dtype: int64

FAM98B
False    183
Name: FAM98B, dtype: int64

FAM98C
False    183
Name: FAM98C, dtype: int64

FAM9C
True     107
False     76
Name: FAM9C, dtype: int64

FANCA
False    183
Name: FANCA, dtype: int64

FANCB
False    183
Name: FANCB, dtype: int64

FANCC
False    183
Name: FANCC, dtype: int64

FANCD2
False    183
Name: FANCD2, dtype: int64

FANCE
False    183
Name: FANCE, dtype: int64

FANCF
False    183
Name: FANCF, dtype: int64

FANCG
False    183
Name: FANCG, dtype: int64

FANCI
False    183
Name: FANCI, dtype: int64

FANCL
False    183
Name: FANCL, dtype: int64

FANCM
False    183
Name: FANCM, dtype: int64

FANK1
False    183
Name: FANK1, dtype: int64

FAP
False    183
Name: FAP, dtype: int64

FAR1
False    183
Name: FAR1, dtype: int64

FAR2
False    183
Name: FAR2, dtype: int64

FARP1
False    183
Name: FARP1, dtype: int64

FARP2
False    183
Name: FARP2, dtype: int64

FARS2
False    183
Name: FARS2, dtype: int64

FARSA
False    183
Name: FARSA, dtype: int64

FARSB
False    183
Name: FARSB, dtype: int64

FASLG
False    183
Name: FASLG, dtype: int64

FASN
False    183
Name: FASN, dtype: int64

FASTKD1
False    183
Name: FASTKD1, dtype: int64

FASTKD2
False    183
Name: FASTKD2, dtype: int64

FASTKD3
False    183
Name: FASTKD3, dtype: int64

FASTKD5
False    183
Name: FASTKD5, dtype: int64

FASTK
False    183
Name: FASTK, dtype: int64

FAS
False    183
Name: FAS, dtype: int64

FAT1
False    183
Name: FAT1, dtype: int64

FAT2
False    182
True       1
Name: FAT2, dtype: int64

FAT3
False    181
True       2
Name: FAT3, dtype: int64

FAT4
False    183
Name: FAT4, dtype: int64

FATE1
False    151
True      32
Name: FATE1, dtype: int64

FAU
False    183
Name: FAU, dtype: int64

FBF1
False    183
Name: FBF1, dtype: int64

FBLIM1
False    183
Name: FBLIM1, dtype: int64

FBLL1
False    183
Name: FBLL1, dtype: int64

FBLN1
False    183
Name: FBLN1, dtype: int64

FBLN2
False    183
Name: FBLN2, dtype: int64

FBLN5
False    183
Name: FBLN5, dtype: int64

FBLN7
False    183
Name: FBLN7, dtype: int64

FBL
False    183
Name: FBL, dtype: int64

FBN1
False    183
Name: FBN1, dtype: int64

FBN2
False    182
True       1
Name: FBN2, dtype: int64

FBN3
False    129
True      54
Name: FBN3, dtype: int64

FBP1
False    183
Name: FBP1, dtype: int64

FBP2
False    144
True      39
Name: FBP2, dtype: int64

FBRSL1
False    183
Name: FBRSL1, dtype: int64

FBRS
False    183
Name: FBRS, dtype: int64

FBXL12
False    183
Name: FBXL12, dtype: int64

FBXL13
False    183
Name: FBXL13, dtype: int64

FBXL14
False    183
Name: FBXL14, dtype: int64

FBXL15
False    183
Name: FBXL15, dtype: int64

FBXL16
False    183
Name: FBXL16, dtype: int64

FBXL17
False    183
Name: FBXL17, dtype: int64

FBXL18
False    183
Name: FBXL18, dtype: int64

FBXL19
False    183
Name: FBXL19, dtype: int64

FBXL20
False    183
Name: FBXL20, dtype: int64

FBXL22
False    183
Name: FBXL22, dtype: int64

FBXL2
False    183
Name: FBXL2, dtype: int64

FBXL3
False    183
Name: FBXL3, dtype: int64

FBXL4
False    183
Name: FBXL4, dtype: int64

FBXL5
False    183
Name: FBXL5, dtype: int64

FBXL6
False    183
Name: FBXL6, dtype: int64

FBXL7
False    183
Name: FBXL7, dtype: int64

FBXL8
False    183
Name: FBXL8, dtype: int64

FBXO10
False    183
Name: FBXO10, dtype: int64

FBXO11
False    183
Name: FBXO11, dtype: int64

FBXO15
False    182
True       1
Name: FBXO15, dtype: int64

FBXO16
False    183
Name: FBXO16, dtype: int64

FBXO17
False    183
Name: FBXO17, dtype: int64

FBXO18
False    183
Name: FBXO18, dtype: int64

FBXO21
False    183
Name: FBXO21, dtype: int64

FBXO22OS
False    183
Name: FBXO22OS, dtype: int64

FBXO22
False    183
Name: FBXO22, dtype: int64

FBXO24
False    183
Name: FBXO24, dtype: int64

FBXO25
False    183
Name: FBXO25, dtype: int64

FBXO27
False    183
Name: FBXO27, dtype: int64

FBXO28
False    183
Name: FBXO28, dtype: int64

FBXO2
False    183
Name: FBXO2, dtype: int64

FBXO30
False    183
Name: FBXO30, dtype: int64

FBXO31
False    183
Name: FBXO31, dtype: int64

FBXO32
False    183
Name: FBXO32, dtype: int64

FBXO33
False    183
Name: FBXO33, dtype: int64

FBXO34
False    183
Name: FBXO34, dtype: int64

FBXO36
False    183
Name: FBXO36, dtype: int64

FBXO38
False    183
Name: FBXO38, dtype: int64

FBXO39
False    181
True       2
Name: FBXO39, dtype: int64

FBXO3
False    183
Name: FBXO3, dtype: int64

FBXO40

False    93
True     90
Name: FBXO40, dtype: int64

FBXO41
False    183
Name: FBXO41, dtype: int64

FBXO42
False    183
Name: FBXO42, dtype: int64

FBXO43
False    183
Name: FBXO43, dtype: int64

FBXO44
False    183
Name: FBXO44, dtype: int64

FBXO45
False    183
Name: FBXO45, dtype: int64

FBXO46
False    183
Name: FBXO46, dtype: int64

FBXO48
False    183
Name: FBXO48, dtype: int64

FBXO4
False    183
Name: FBXO4, dtype: int64

FBXO5
False    183
Name: FBXO5, dtype: int64

FBXO6
False    183
Name: FBXO6, dtype: int64

FBXO7
False    183
Name: FBXO7, dtype: int64

FBXO8
False    183
Name: FBXO8, dtype: int64

FBXO9
False    183
Name: FBXO9, dtype: int64

FBXW10
False    171
True      12
Name: FBXW10, dtype: int64

FBXW11
False    183
Name: FBXW11, dtype: int64

FBXW12
True     104
False     79
Name: FBXW12, dtype: int64

FBXW2
False    183
Name: FBXW2, dtype: int64

FBXW4
False    183
Name: FBXW4, dtype: int64

FBXW5
False    183
Name: FBXW5, dtype: int64

FBXW7
False    183
Name: FBXW7, dtype: int64

FBXW8
False    183
Name: FBXW8, dtype: int64

FBXW9
False    183
Name: FBXW9, dtype: int64

FCAMR
False    172
True      11
Name: FCAMR, dtype: int64

FCAR
False    160
True      23
Name: FCAR, dtype: int64

FCER1A
False    182
True       1
Name: FCER1A, dtype: int64

FCER1G
False    183
Name: FCER1G, dtype: int64

FCER2
False    167
True      16
Name: FCER2, dtype: int64

FCF1
False    183
Name: FCF1, dtype: int64

FCGBP
False    183
Name: FCGBP, dtype: int64

FCGR1A
False    183
Name: FCGR1A, dtype: int64

FCGR1B
False    183
Name: FCGR1B, dtype: int64

FCGR1C
False    183
Name: FCGR1C, dtype: int64

FCGR2A
False    183
Name: FCGR2A, dtype: int64

FCGR2B
False    182
True       1
Name: FCGR2B, dtype: int64

FCGR2C
False    181
True       2
Name: FCGR2C, dtype: int64

FCGR3A
False    183
Name: FCGR3A, dtype: int64

FCGR3B
False    182
True       1
Name: FCGR3B, dtype: int64

FCGRT
False    183
Name: FCGRT, dtype: int64

FCHO1
False    183
Name: FCHO1, dtype: int64

FCHO2
False    183
Name: FCHO2, dtype: int64

FCHSD1
False    183
Name: FCHSD1, dtype: int64

FCHSD2
False    183
Name: FCHSD2, dtype: int64

FCN1
False    183
Name: FCN1, dtype: int64

FCN2
True     96
False    87
Name: FCN2, dtype: int64

FCN3
False    183
Name: FCN3, dtype: int64

FCRL1
False    151
True      32
Name: FCRL1, dtype: int64

FCRL2
False    173
True      10
Name: FCRL2, dtype: int64

FCRL3
False    177
True       6
Name: FCRL3, dtype: int64

FCRL4
False    148
True      35
Name: FCRL4, dtype: int64

FCRL5
False    179
True       4
Name: FCRL5, dtype: int64

FCRL6
False    181
True       2
Name: FCRL6, dtype: int64

FCRLA
False    174
True       9
Name: FCRLA, dtype: int64

FCRLB
False    183
Name: FCRLB, dtype: int64

FDFT1
False    183
Name: FDFT1, dtype: int64

FDPSL2A
False    181
True       2
Name: FDPSL2A, dtype: int64

FDPS
False    183
Name: FDPS, dtype: int64

FDX1L
False    183
Name: FDX1L, dtype: int64

FDX1
False    183
Name: FDX1, dtype: int64

FDXACB1
False    183
Name: FDXACB1, dtype: int64

FDXR
False    183
Name: FDXR, dtype: int64

FECH
False    183
Name: FECH, dtype: int64

FEM1A
False    183
Name: FEM1A, dtype: int64

FEM1B
False    183
Name: FEM1B, dtype: int64

FEM1C
False    183
Name: FEM1C, dtype: int64

FEN1
False    183
Name: FEN1, dtype: int64

FER1L4
False    183
Name: FER1L4, dtype: int64

FER1L5
False    173
True      10
Name: FER1L5, dtype: int64

FER1L6
False    179
True       4
Name: FER1L6, dtype: int64

FERMT1
False    182
True       1
Name: FERMT1, dtype: int64

FERMT2
False    183
Name: FERMT2, dtype: int64

FERMT3
False    183
Name: FERMT3, dtype: int64

FER
False    183
Name: FER, dtype: int64

FES
False    183
Name: FES, dtype: int64

FETUB
False    93
True     90
Name: FETUB, dtype: int64

FEV
False    177
True       6
Name: FEV, dtype: int64

FEZ1
False    183
Name: FEZ1, dtype: int64

FEZ2
False    183
Name: FEZ2, dtype: int64

FEZF1
False    134
True      49
Name: FEZF1, dtype: int64

FFAR1
False    156
True      27
Name: FFAR1, dtype: int64

FFAR2
False    183
Name: FFAR2, dtype: int64

FFAR3
False    180
True       3
Name: FFAR3, dtype: int64

FGA
False    180
True       3
Name: FGA, dtype: int64

FGB
False    175
True       8
Name: FGB, dtype: int64

FGD1
False    183
Name: FGD1, dtype: int64

FGD2
False    183
Name: FGD2, dtype: int64

FGD3
False    183
Name: FGD3, dtype: int64

FGD4
False    183
Name: FGD4, dtype: int64

FGD5
False    183
Name: FGD5, dtype: int64

FGD6
False    183
Name: FGD6, dtype: int64

FGF10
False    160
True      23
Name: FGF10, dtype: int64

FGF11
False    183
Name: FGF11, dtype: int64

FGF12
False    183
Name: FGF12, dtype: int64

FGF13
False    183
Name: FGF13, dtype: int64

FGF14
False    183
Name: FGF14, dtype: int64

FGF17
False    174
True       9
Name: FGF17, dtype: int64

FGF18
False    182
True       1
Name: FGF18, dtype: int64

FGF19
False    176
True       7
Name: FGF19, dtype: int64

FGF1
False    183
Name: FGF1, dtype: int64

FGF20
False    174
True       9
Name: FGF20, dtype: int64

FGF22
True     122
False     61
Name: FGF22, dtype: int64

FGF23
True     121
False     62
Name: FGF23, dtype: int64

FGF2
False    183
Name: FGF2, dtype: int64

FGF3
False    121
True      62
Name: FGF3, dtype: int64

FGF5
False    169
True      14
Name: FGF5, dtype: int64

FGF7
False    183
Name: FGF7, dtype: int64

FGF8
True     94
False    89
Name: FGF8, dtype: int64

FGF9
False    182
True       1
Name: FGF9, dtype: int64

FGFBP1
False    175
True       8
Name: FGFBP1, dtype: int64

FGFBP2
False    182
True       1
Name: FGFBP2, dtype: int64

FGFBP3
False    183
Name: FGFBP3, dtype: int64

FGFR1OP2
False    183
Name: FGFR1OP2, dtype: int64

FGFR1OP
False    183
Name: FGFR1OP, dtype: int64

FGFR1
False    183
Name: FGFR1, dtype: int64

FGFR2
False    183
Name: FGFR2, dtype: int64

FGFR3
False    183
Name: FGFR3, dtype: int64

FGFR4
False    183
Name: FGFR4, dtype: int64

FGFRL1
False    183
Name: FGFRL1, dtype: int64

FGGY
False    183
Name: FGGY, dtype: int64

FGG
False    175
True       8
Name: FGG, dtype: int64

FGL1
False    179
True       4
Name: FGL1, dtype: int64

FGL2
False    183
Name: FGL2, dtype: int64

FGR
False    183
Name: FGR, dtype: int64

FHAD1
False    183
Name: FHAD1, dtype: int64

FHDC1
False    183
Name: FHDC1, dtype: int64

FHIT
False    183
Name: FHIT, dtype: int64

FHL1
False    183
Name: FHL1, dtype: int64

FHL2
False    183
Name: FHL2, dtype: int64

FHL3
False    183
Name: FHL3, dtype: int64

FHL5
False    183
Name: FHL5, dtype: int64

FHOD1
False    183
Name: FHOD1, dtype: int64

FHOD3
False    183
Name: FHOD3, dtype: int64

FH
False    183
Name: FH, dtype: int64

FIBCD1
False    182
True       1
Name: FIBCD1, dtype: int64

FIBIN
False    183
Name: FIBIN, dtype: int64

FIBP
False    183
Name: FIBP, dtype: int64

FICD
False    183
Name: FICD, dtype: int64

FIG4
False    183
Name: FIG4, dtype: int64

FIGF
False    180
True       3
Name: FIGF, dtype: int64

FIGNL1
False    183
Name: FIGNL1, dtype: int64

FIGNL2
False    183
Name: FIGNL2, dtype: int64

FIGN
False    183
Name: FIGN, dtype: int64

FILIP1L
False    183
Name: FILIP1L, dtype: int64

FILIP1
False    183
Name: FILIP1, dtype: int64

FIP1L1
False    183
Name: FIP1L1, dtype: int64

FIS1
False    183
Name: FIS1, dtype: int64

FITM1
False    183
Name: FITM1, dtype: int64

FITM2
False    183
Name: FITM2, dtype: int64

FIZ1
False    183
Name: FIZ1, dtype: int64

FJX1
False    183
Name: FJX1, dtype: int64

FKBP10
False    183
Name: FKBP10, dtype: int64

FKBP11
False    183
Name: FKBP11, dtype: int64

FKBP14
False    183
Name: FKBP14, dtype: int64

FKBP15
False    183
Name: FKBP15, dtype: int64

FKBP1AP1
False    180
True       3
Name: FKBP1AP1, dtype: int64

FKBP1A
False    183
Name: FKBP1A, dtype: int64

FKBP1B
False    183
Name: FKBP1B, dtype: int64

FKBP2
False    183
Name: FKBP2, dtype: int64

FKBP3
False    183
Name: FKBP3, dtype: int64

FKBP4
False    183
Name: FKBP4, dtype: int64

FKBP5
False    183
Name: FKBP5, dtype: int64

FKBP6
False    107
True      76
Name: FKBP6, dtype: int64

FKBP7
False    183
Name: FKBP7, dtype: int64

FKBP8
False    183
Name: FKBP8, dtype: int64

FKBP9L
False    183
Name: FKBP9L, dtype: int64

FKBP9
False    183
Name: FKBP9, dtype: int64

FKBPL
False    183
Name: FKBPL, dtype: int64

FKRP
False    183
Name: FKRP, dtype: int64

FKSG29
True     118
False     65
Name: FKSG29, dtype: int64

FKTN
False    183
Name: FKTN, dtype: int64

FLAD1
False    183
Name: FLAD1, dtype: int64

FLCN
False    183
Name: FLCN, dtype: int64

FLG2
False    95
True     88
Name: FLG2, dtype: int64

FLG
False    181
True       2
Name: FLG, dtype: int64

FLI1
False    183
Name: FLI1, dtype: int64

FLII
False    183
Name: FLII, dtype: int64

FLJ10038
False    183
Name: FLJ10038, dtype: int64

FLJ10213

False    180
True       3
Name: FLJ10213, dtype: int64

FLJ10357
False    183
Name: FLJ10357, dtype: int64

FLJ10661
False    183
Name: FLJ10661, dtype: int64

FLJ11235
False    183
Name: FLJ11235, dtype: int64

FLJ12825
False    181
True       2
Name: FLJ12825, dtype: int64

FLJ13197
False    183
Name: FLJ13197, dtype: int64

FLJ13224
False    158
True      25
Name: FLJ13224, dtype: int64

FLJ14107
False    158
True      25
Name: FLJ14107, dtype: int64

FLJ16779
False    179
True       4
Name: FLJ16779, dtype: int64

FLJ22536
False    182
True       1
Name: FLJ22536, dtype: int64

FLJ23867
False    183
Name: FLJ23867, dtype: int64

FLJ26850
False    172
True      11
Name: FLJ26850, dtype: int64

FLJ30679
False    122
True      61
Name: FLJ30679, dtype: int64

FLJ33360
False    168
True      15
Name: FLJ33360, dtype: int64

FLJ33630
False    183
Name: FLJ33630, dtype: int64

FLJ34503
False    111
True      72
Name: FLJ34503, dtype: int64

FLJ35024
False    180
True       3
Name: FLJ35024, dtype: int64

FLJ35220
False    183
Name: FLJ35220, dtype: int64

FLJ35390
False    183
Name: FLJ35390, dtype: int64

FLJ35776
False    183
Name: FLJ35776, dtype: int64

FLJ36031
False    183
Name: FLJ36031, dtype: int64

FLJ36777
False    182
True       1
Name: FLJ36777, dtype: int64

FLJ37201
False    182
True       1
Name: FLJ37201, dtype: int64

FLJ37307
False    180
True       3
Name: FLJ37307, dtype: int64

FLJ37453
False    183
Name: FLJ37453, dtype: int64

FLJ37543
False    94
True     89
Name: FLJ37543, dtype: int64

FLJ39582
False    183
Name: FLJ39582, dtype: int64

FLJ39609
False    93
True     90
Name: FLJ39609, dtype: int64

FLJ39653
False    183
Name: FLJ39653, dtype: int64

FLJ39739
False    177
True       6
Name: FLJ39739, dtype: int64

FLJ40292
False    152
True      31
Name: FLJ40292, dtype: int64

FLJ40330
False    183
Name: FLJ40330, dtype: int64

FLJ40852
False    183
Name: FLJ40852, dtype: int64

FLJ41941
True     94
False    89
Name: FLJ41941, dtype: int64

FLJ42289
False    183
Name: FLJ42289, dtype: int64

FLJ42393
False    120
True      63
Name: FLJ42393, dtype: int64

FLJ42627
False    183
Name: FLJ42627, dtype: int64

FLJ42709
False    183
Name: FLJ42709, dtype: int64

FLJ42875
False    182
True       1
Name: FLJ42875, dtype: int64

FLJ43390
False    173
True      10
Name: FLJ43390, dtype: int64

FLJ43663
False    183
Name: FLJ43663, dtype: int64

FLJ43860
True     105
False     78
Name: FLJ43860, dtype: int64

FLJ43950
True     106
False     77
Name: FLJ43950, dtype: int64

FLJ44054
False    121
True      62
Name: FLJ44054, dtype: int64

FLJ44606
False    183
Name: FLJ44606, dtype: int64

FLJ44635
False    183
Name: FLJ44635, dtype: int64

FLJ45079
False    93
True     90
Name: FLJ45079, dtype: int64

FLJ45244
False    183
Name: FLJ45244, dtype: int64

FLJ45340
False    183
Name: FLJ45340, dtype: int64

FLJ45445
False    183
Name: FLJ45445, dtype: int64

FLJ45983
False    166
True      17
Name: FLJ45983, dtype: int64

FLJ46111
False    180
True       3
Name: FLJ46111, dtype: int64

FLJ90757
False    183
Name: FLJ90757, dtype: int64

FLNA
False    183
Name: FLNA, dtype: int64

FLNB
False    183
Name: FLNB, dtype: int64

FLNC
False    183
Name: FLNC, dtype: int64

FLOT1
False    183
Name: FLOT1, dtype: int64

FLOT2
False    183
Name: FLOT2, dtype: int64

FLRT1
False    183
Name: FLRT1, dtype: int64

FLRT2
False    183
Name: FLRT2, dtype: int64

FLRT3
False    183
Name: FLRT3, dtype: int64

FLT1
False    183
Name: FLT1, dtype: int64

FLT3LG
False    183
Name: FLT3LG, dtype: int64

FLT3
False    180
True       3
Name: FLT3, dtype: int64

FLT4
False    183
Name: FLT4, dtype: int64

FLVCR1
False    183
Name: FLVCR1, dtype: int64

FLVCR2
False    183
Name: FLVCR2, dtype: int64

FLYWCH1
False    183
Name: FLYWCH1, dtype: int64

FLYWCH2
False    183
Name: FLYWCH2, dtype: int64

FMN1
False    183
Name: FMN1, dtype: int64

FMN2
False    182
True       1
Name: FMN2, dtype: int64

FMNL1
False    183
Name: FMNL1, dtype: int64

FMNL2
False    183
Name: FMNL2, dtype: int64

FMNL3
False    183
Name: FMNL3, dtype: int64

FMO1
False    181
True       2
Name: FMO1, dtype: int64

FMO2
False    183
Name: FMO2, dtype: int64

FMO3
False    183
Name: FMO3, dtype: int64

FMO4
False    183
Name: FMO4, dtype: int64

FMO5
False    183
Name: FMO5, dtype: int64

FMO6P
True     123
False     60
Name: FMO6P, dtype: int64

FMOD
False    183
Name: FMOD, dtype: int64

FMR1
False    183
Name: FMR1, dtype: int64

FN1
False    183
Name: FN1, dtype: int64

FN3KRP
False    183
Name: FN3KRP, dtype: int64

FN3K
False    183
Name: FN3K, dtype: int64

FNBP1L
False    183
Name: FNBP1L, dtype: int64

FNBP1
False    183
Name: FNBP1, dtype: int64

FNBP4
False    183
Name: FNBP4, dtype: int64

FNDC1
False    183
Name: FNDC1, dtype: int64

FNDC3A
False    183
Name: FNDC3A, dtype: int64

FNDC3B
False    183
Name: FNDC3B, dtype: int64

FNDC4
False    183
Name: FNDC4, dtype: int64

FNDC5
False    183
Name: FNDC5, dtype: int64

FNDC7
True     104
False     79
Name: FNDC7, dtype: int64

FNDC8
False    181
True       2
Name: FNDC8, dtype: int64

FNIP1
False    183
Name: FNIP1, dtype: int64

FNIP2
False    183
Name: FNIP2, dtype: int64

FNTA
False    183
Name: FNTA, dtype: int64

FNTB
False    183
Name: FNTB, dtype: int64

FOLH1B
False    116
True      67
Name: FOLH1B, dtype: int64

FOLH1
False    183
Name: FOLH1, dtype: int64

FOLR1
False    181
True       2
Name: FOLR1, dtype: int64

FOLR2
False    183
Name: FOLR2, dtype: int64

FOLR3
False    149
True      34
Name: FOLR3, dtype: int64

FOLR4
True     106
False     77
Name: FOLR4, dtype: int64

FOSB
False    183
Name: FOSB, dtype: int64

FOSL1
False    183
Name: FOSL1, dtype: int64

FOSL2
False    183
Name: FOSL2, dtype: int64

FOS
False    183
Name: FOS, dtype: int64

FOXA1
False    181
True       2
Name: FOXA1, dtype: int64

FOXA2
False    182
True       1
Name: FOXA2, dtype: int64

FOXA3
False    183
Name: FOXA3, dtype: int64

FOXC1
False    183
Name: FOXC1, dtype: int64

FOXC2
False    183
Name: FOXC2, dtype: int64

FOXD1
False    182
True       1
Name: FOXD1, dtype: int64

FOXD2
False    183
Name: FOXD2, dtype: int64

FOXD3
False    169
True      14
Name: FOXD3, dtype: int64

FOXD4L1
False    182
True       1
Name: FOXD4L1, dtype: int64

FOXD4L2
False    175
True       8
Name: FOXD4L2, dtype: int64

FOXD4L3
True     108
False     75
Name: FOXD4L3, dtype: int64

FOXD4L5
True     116
False     67
Name: FOXD4L5, dtype: int64

FOXD4L6
False    168
True      15
Name: FOXD4L6, dtype: int64

FOXD4
False    182
True       1
Name: FOXD4, dtype: int64

FOXE1
False    151
True      32
Name: FOXE1, dtype: int64

FOXE3
False    137
True      46
Name: FOXE3, dtype: int64

FOXF1
False    183
Name: FOXF1, dtype: int64

FOXF2
False    183
Name: FOXF2, dtype: int64

FOXG1
True     122
False     61
Name: FOXG1, dtype: int64

FOXH1
False    181
True       2
Name: FOXH1, dtype: int64

FOXI1
False    162
True      21
Name: FOXI1, dtype: int64

FOXI2
False    147
True      36
Name: FOXI2, dtype: int64

FOXJ1
False    183
Name: FOXJ1, dtype: int64

FOXJ2
False    183
Name: FOXJ2, dtype: int64

FOXJ3
False    183
Name: FOXJ3, dtype: int64

FOXK1
False    183
Name: FOXK1, dtype: int64

FOXK2
False    183
Name: FOXK2, dtype: int64

FOXL1
False    183
Name: FOXL1, dtype: int64

FOXL2
False    158
True      25
Name: FOXL2, dtype: int64

FOXM1
False    183
Name: FOXM1, dtype: int64

FOXN1
False    130
True      53
Name: FOXN1, dtype: int64

FOXN2
False    183
Name: FOXN2, dtype: int64

FOXN3
False    183
Name: FOXN3, dtype: int64

FOXN4
True     121
False     62
Name: FOXN4, dtype: int64

FOXO1
False    183
Name: FOXO1, dtype: int64

FOXO3B
False    183
Name: FOXO3B, dtype: int64

FOXO3
False    183
Name: FOXO3, dtype: int64

FOXO4
False    183
Name: FOXO4, dtype: int64

FOXP1
False    183
Name: FOXP1, dtype: int64

FOXP2
False    182
True       1
Name: FOXP2, dtype: int64

FOXP3
False    183
Name: FOXP3, dtype: int64

FOXP4
False    183
Name: FOXP4, dtype: int64

FOXQ1
False    183
Name: FOXQ1, dtype: int64

FOXRED1
False    183
Name: FOXRED1, dtype: int64

FOXRED2
False    183
Name: FOXRED2, dtype: int64

FOXS1
False    183
Name: FOXS1, dtype: int64

FPGS

False    183
Name: FPGS, dtype: int64

FPGT
False    183
Name: FPGT, dtype: int64

FPR1
False    183
Name: FPR1, dtype: int64

FPR2
False    179
True       4
Name: FPR2, dtype: int64

FPR3
False    183
Name: FPR3, dtype: int64

FRAS1
False    183
Name: FRAS1, dtype: int64

FRAT1
False    183
Name: FRAT1, dtype: int64

FRAT2
False    183
Name: FRAT2, dtype: int64

FREM1
False    182
True       1
Name: FREM1, dtype: int64

FREM2
False    181
True       2
Name: FREM2, dtype: int64

FRG1B
False    183
Name: FRG1B, dtype: int64

FRG1
False    183
Name: FRG1, dtype: int64

FRG2C
True     106
False     77
Name: FRG2C, dtype: int64

FRK
False    183
Name: FRK, dtype: int64

FRMD1
False    131
True      52
Name: FRMD1, dtype: int64

FRMD3
False    183
Name: FRMD3, dtype: int64

FRMD4A
False    183
Name: FRMD4A, dtype: int64

FRMD4B
False    183
Name: FRMD4B, dtype: int64

FRMD5
False    183
Name: FRMD5, dtype: int64

FRMD6
False    183
Name: FRMD6, dtype: int64

FRMD7
False    96
True     87
Name: FRMD7, dtype: int64

FRMD8
False    183
Name: FRMD8, dtype: int64

FRMPD1
False    176
True       7
Name: FRMPD1, dtype: int64

FRMPD2
True     99
False    84
Name: FRMPD2, dtype: int64

FRMPD4
False    142
True      41
Name: FRMPD4, dtype: int64

FRRS1
False    182
True       1
Name: FRRS1, dtype: int64

FRS2
False    183
Name: FRS2, dtype: int64

FRS3
False    183
Name: FRS3, dtype: int64

FRYL
False    183
Name: FRYL, dtype: int64

FRY
False    183
Name: FRY, dtype: int64

FRZB
False    183
Name: FRZB, dtype: int64

FSCN1
False    183
Name: FSCN1, dtype: int64

FSCN2
False    183
Name: FSCN2, dtype: int64

FSCN3
False    157
True      26
Name: FSCN3, dtype: int64

FSD1L
False    183
Name: FSD1L, dtype: int64

FSD1
False    182
True       1
Name: FSD1, dtype: int64

FSD2
True     99
False    84
Name: FSD2, dtype: int64

FSIP1
False    181
True       2
Name: FSIP1, dtype: int64

FSTL1
False    183
Name: FSTL1, dtype: int64

FSTL3
False    183
Name: FSTL3, dtype: int64

FSTL4
False    182
True       1
Name: FSTL4, dtype: int64

FSTL5
False    163
True      20
Name: FSTL5, dtype: int64

FST
False    183
Name: FST, dtype: int64

FTCD
False    175
True       8
Name: FTCD, dtype: int64

FTH1
False    183
Name: FTH1, dtype: int64

FTHL3
False    183
Name: FTHL3, dtype: int64

FTL
False    183
Name: FTL, dtype: int64

FTO
False    183
Name: FTO, dtype: int64

FTSJ1
False    183
Name: FTSJ1, dtype: int64

FTSJ2
False    183
Name: FTSJ2, dtype: int64

FTSJ3
False    183
Name: FTSJ3, dtype: int64

FTSJD1
False    183
Name: FTSJD1, dtype: int64

FTSJD2
False    183
Name: FTSJD2, dtype: int64

FUBP1
False    183
Name: FUBP1, dtype: int64

FUBP3
False    183
Name: FUBP3, dtype: int64

FUCA1
False    183
Name: FUCA1, dtype: int64

FUCA2
False    183
Name: FUCA2, dtype: int64

FUK
False    183
Name: FUK, dtype: int64

FUNDC1
False    183
Name: FUNDC1, dtype: int64

FUNDC2P2
False    170
True      13
Name: FUNDC2P2, dtype: int64

FUNDC2
False    183
Name: FUNDC2, dtype: int64

FURIN
False    183
Name: FURIN, dtype: int64

FUS
False    183
Name: FUS, dtype: int64

FUT10
False    183
Name: FUT10, dtype: int64

FUT11
False    183
Name: FUT11, dtype: int64

FUT1
False    183
Name: FUT1, dtype: int64

FUT2
False    183
Name: FUT2, dtype: int64

FUT3
False    182
True       1
Name: FUT3, dtype: int64

FUT4
False    183
Name: FUT4, dtype: int64

FUT5
False    128
True      55
Name: FUT5, dtype: int64

FUT6
False    181
True       2
Name: FUT6, dtype: int64

FUT7
False    183
Name: FUT7, dtype: int64

FUT8
False    183
Name: FUT8, dtype: int64

FUT9
False    172
True      11
Name: FUT9, dtype: int64

FUZ
False    183
Name: FUZ, dtype: int64

FXC1
False    183
Name: FXC1, dtype: int64

FXN
False    183
Name: FXN, dtype: int64

FXR1
False    183
Name: FXR1, dtype: int64

FXR2
False    183
Name: FXR2, dtype: int64

FXYD1
False    183
Name: FXYD1, dtype: int64

FXYD2
False    183
Name: FXYD2, dtype: int64

FXYD3
False    183
Name: FXYD3, dtype: int64

FXYD4
False    93
True     90
Name: FXYD4, dtype: int64

FXYD5
False    183
Name: FXYD5, dtype: int64

FXYD6
False    183
Name: FXYD6, dtype: int64

FXYD7
False    173
True      10
Name: FXYD7, dtype: int64

FYB
False    183
Name: FYB, dtype: int64

FYCO1
False    183
Name: FYCO1, dtype: int64

FYN
False    183
Name: FYN, dtype: int64

FYTTD1
False    183
Name: FYTTD1, dtype: int64

FZD10
False    183
Name: FZD10, dtype: int64

FZD1
False    183
Name: FZD1, dtype: int64

FZD2
False    183
Name: FZD2, dtype: int64

FZD3
False    183
Name: FZD3, dtype: int64

FZD4
False    183
Name: FZD4, dtype: int64

FZD5
False    183
Name: FZD5, dtype: int64

FZD6
False    183
Name: FZD6, dtype: int64

FZD7
False    183
Name: FZD7, dtype: int64

FZD8
False    183
Name: FZD8, dtype: int64

FZD9
False    173
True      10
Name: FZD9, dtype: int64

FZR1
False    183
Name: FZR1, dtype: int64

G0S2
False    183
Name: G0S2, dtype: int64

G2E3
False    183
Name: G2E3, dtype: int64

G3BP1
False    183
Name: G3BP1, dtype: int64

G3BP2
False    183
Name: G3BP2, dtype: int64

G6PC2
False    174
True       9
Name: G6PC2, dtype: int64

G6PC3
False    183
Name: G6PC3, dtype: int64

G6PC
False    140
True      43
Name: G6PC, dtype: int64

G6PD
False    183
Name: G6PD, dtype: int64

GAA
False    183
Name: GAA, dtype: int64

GAB1
False    183
Name: GAB1, dtype: int64

GAB2
False    183
Name: GAB2, dtype: int64

GAB3
False    183
Name: GAB3, dtype: int64

GABARAPL1
False    183
Name: GABARAPL1, dtype: int64

GABARAPL2
False    183
Name: GABARAPL2, dtype: int64

GABARAPL3
False    172
True      11
Name: GABARAPL3, dtype: int64

GABARAP
False    183
Name: GABARAP, dtype: int64

GABBR1
False    183
Name: GABBR1, dtype: int64

GABBR2
False    176
True       7
Name: GABBR2, dtype: int64

GABPA
False    183
Name: GABPA, dtype: int64

GABPB1
False    183
Name: GABPB1, dtype: int64

GABPB2
False    183
Name: GABPB2, dtype: int64

GABRA1
False    103
True      80
Name: GABRA1, dtype: int64

GABRA2
False    156
True      27
Name: GABRA2, dtype: int64

GABRA3
False    98
True     85
Name: GABRA3, dtype: int64

GABRA4
False    147
True      36
Name: GABRA4, dtype: int64

GABRA5
False    166
True      17
Name: GABRA5, dtype: int64

GABRB1
False    110
True      73
Name: GABRB1, dtype: int64

GABRB2
False    183
Name: GABRB2, dtype: int64

GABRB3
False    183
Name: GABRB3, dtype: int64

GABRD
False    183
Name: GABRD, dtype: int64

GABRE
False    183
Name: GABRE, dtype: int64

GABRG1
False    126
True      57
Name: GABRG1, dtype: int64

GABRG2
False    155
True      28
Name: GABRG2, dtype: int64

GABRP
False    182
True       1
Name: GABRP, dtype: int64

GABRQ
False    93
True     90
Name: GABRQ, dtype: int64

GABRR1
False    149
True      34
Name: GABRR1, dtype: int64

GABRR2
False    158
True      25
Name: GABRR2, dtype: int64

GAD1
False    182
True       1
Name: GAD1, dtype: int64

GAD2
False    170
True      13
Name: GAD2, dtype: int64

GADD45A
False    183
Name: GADD45A, dtype: int64

GADD45B
False    183
Name: GADD45B, dtype: int64

GADD45GIP1
False    183
Name: GADD45GIP1, dtype: int64

GADD45G
False    183
Name: GADD45G, dtype: int64

GADL1
True     126
False     57
Name: GADL1, dtype: int64

GAK
False    183
Name: GAK, dtype: int64

GAL3ST1
False    183
Name: GAL3ST1, dtype: int64

GAL3ST2
False    145
True      38
Name: GAL3ST2, dtype: int64

GAL3ST3
False    131
True      52
Name: GAL3ST3, dtype: int64

GAL3ST4
False    183
Name: GAL3ST4, dtype: int64

GALC
False    183
Name: GALC, dtype: int64

GALE
False    183
Name: GALE, dtype: int64

GALK1
False    183
Name: GALK1, dtype: int64

GALK2
False    183
Name: GALK2, dtype: int64

GALM
False    183
Name: GALM, dtype: int64

GALNS
False    183
Name: GALNS, dtype: int64

GALNT10
False    183
Name: GALNT10, dtype: int64

GALNT11
False    183
Name: GALNT11, dtype: int64

GALNT12
False    183
Name: GALNT12, dtype: int64

GALNT13
False    183
Name: GALNT13, dtype: int64

GALNT14
False    182
True       1
Name: GALNT14, dtype: int64

GALNT1
False    183
Name: GALNT1, dtype: int64

GALNT2
False    183
Name: GALNT2, dtype: int64

GALNT3
False    183
Name: GALNT3, dtype: int64

GALNT4
False    183
Name: GALNT4, dtype: int64

GALNT5
False    179
True       4
Name: GALNT5, dtype: int64

GALNT6
False    183
Name: GALNT6, dtype: int64

GALNT7
False    183
Name: GALNT7, dtype: int64

GALNT8
False    143
True      40
Name: GALNT8, dtype: int64

GALNT9
False    176
True       7
Name: GALNT9, dtype: int64

GALNTL1
False    183
Name: GALNTL1, dtype: int64

GALNTL2
False    183
Name: GALNTL2, dtype: int64

GALNTL4
False    183
Name: GALNTL4, dtype: int64

GALNTL6
False    147
True      36
Name: GALNTL6, dtype: int64

GALR1
False    135
True      48
Name: GALR1, dtype: int64

GALR2
False    157
True      26
Name: GALR2, dtype: int64

GALR3
True     127
False     56
Name: GALR3, dtype: int64

GALT

False    183
Name: GALT, dtype: int64

GAL
False    175
True       8
Name: GAL, dtype: int64

GAMT
False    183
Name: GAMT, dtype: int64

GANAB
False    183
Name: GANAB, dtype: int64

GANC
False    183
Name: GANC, dtype: int64

GAN
False    183
Name: GAN, dtype: int64

GAP43
False    183
Name: GAP43, dtype: int64

GAPDHS
False    166
True      17
Name: GAPDHS, dtype: int64

GAPDH
False    183
Name: GAPDH, dtype: int64

GAPT
False    183
Name: GAPT, dtype: int64

GAPVD1
False    183
Name: GAPVD1, dtype: int64

GAR1
False    183
Name: GAR1, dtype: int64

GARNL3
False    183
Name: GARNL3, dtype: int64

GARS
False    183
Name: GARS, dtype: int64

GART
False    183
Name: GART, dtype: int64

GAS1
False    183
Name: GAS1, dtype: int64

GAS2L1
False    183
Name: GAS2L1, dtype: int64

GAS2L2
False    178
True       5
Name: GAS2L2, dtype: int64

GAS2L3
False    180
True       3
Name: GAS2L3, dtype: int64

GAS2
False    183
Name: GAS2, dtype: int64

GAS5
False    183
Name: GAS5, dtype: int64

GAS6
False    183
Name: GAS6, dtype: int64

GAS7
False    183
Name: GAS7, dtype: int64

GAS8
False    183
Name: GAS8, dtype: int64

GAST
False    103
True      80
Name: GAST, dtype: int64

GATA1
False    170
True      13
Name: GATA1, dtype: int64

GATA2
False    183
Name: GATA2, dtype: int64

GATA3
False    183
Name: GATA3, dtype: int64

GATA4
False    181
True       2
Name: GATA4, dtype: int64

GATA5
False    156
True      27
Name: GATA5, dtype: int64

GATA6
False    183
Name: GATA6, dtype: int64

GATAD1
False    183
Name: GATAD1, dtype: int64

GATAD2A
False    183
Name: GATAD2A, dtype: int64

GATAD2B
False    183
Name: GATAD2B, dtype: int64

GATC
False    183
Name: GATC, dtype: int64

GATM
False    183
Name: GATM, dtype: int64

GATSL1
False    181
True       2
Name: GATSL1, dtype: int64

GATSL2
False    96
True     87
Name: GATSL2, dtype: int64

GATSL3
False    183
Name: GATSL3, dtype: int64

GATS
False    183
Name: GATS, dtype: int64

GBA2
False    183
Name: GBA2, dtype: int64

GBA3
False    179
True       4
Name: GBA3, dtype: int64

GBAP1
False    183
Name: GBAP1, dtype: int64

GBAS
False    183
Name: GBAS, dtype: int64

GBA
False    183
Name: GBA, dtype: int64

GBE1
False    183
Name: GBE1, dtype: int64

GBF1
False    183
Name: GBF1, dtype: int64

GBGT1
False    183
Name: GBGT1, dtype: int64

GBP1
False    183
Name: GBP1, dtype: int64

GBP2
False    183
Name: GBP2, dtype: int64

GBP3
False    183
Name: GBP3, dtype: int64

GBP4
False    183
Name: GBP4, dtype: int64

GBP5
False    183
Name: GBP5, dtype: int64

GBP6
False    177
True       6
Name: GBP6, dtype: int64

GBP7
False    105
True      78
Name: GBP7, dtype: int64

GBX2
False    108
True      75
Name: GBX2, dtype: int64

GCAT
False    183
Name: GCAT, dtype: int64

GCA
False    183
Name: GCA, dtype: int64

GCC1
False    183
Name: GCC1, dtype: int64

GCC2
False    183
Name: GCC2, dtype: int64

GCDH
False    183
Name: GCDH, dtype: int64

GCET2
False    183
Name: GCET2, dtype: int64

GCFC1
False    183
Name: GCFC1, dtype: int64

GCGR
False    177
True       6
Name: GCGR, dtype: int64

GCG
False    173
True      10
Name: GCG, dtype: int64

GCH1
False    183
Name: GCH1, dtype: int64

GCHFR
False    183
Name: GCHFR, dtype: int64

GCKR
False    182
True       1
Name: GCKR, dtype: int64

GCK
False    182
True       1
Name: GCK, dtype: int64

GCLC
False    183
Name: GCLC, dtype: int64

GCLM
False    183
Name: GCLM, dtype: int64

GCM1
False    171
True      12
Name: GCM1, dtype: int64

GCN1L1
False    183
Name: GCN1L1, dtype: int64

GCNT1
False    183
Name: GCNT1, dtype: int64

GCNT2
False    183
Name: GCNT2, dtype: int64

GCNT3
False    183
Name: GCNT3, dtype: int64

GCNT4
False    183
Name: GCNT4, dtype: int64

GCNT7
False    124
True      59
Name: GCNT7, dtype: int64

GCOM1
False    183
Name: GCOM1, dtype: int64

GCSH
False    182
True       1
Name: GCSH, dtype: int64

GC
False    176
True       7
Name: GC, dtype: int64

GDAP1L1
False    177
True       6
Name: GDAP1L1, dtype: int64

GDAP1
False    183
Name: GDAP1, dtype: int64

GDAP2
False    183
Name: GDAP2, dtype: int64

GDA
False    181
True       2
Name: GDA, dtype: int64

GDE1
False    183
Name: GDE1, dtype: int64

GDF10
False    179
True       4
Name: GDF10, dtype: int64

GDF11
False    183
Name: GDF11, dtype: int64

GDF15
False    183
Name: GDF15, dtype: int64

GDF1
False    168
True      15
Name: GDF1, dtype: int64

GDF3
False    172
True      11
Name: GDF3, dtype: int64

GDF5
False    172
True      11
Name: GDF5, dtype: int64

GDF6
False    182
True       1
Name: GDF6, dtype: int64

GDF7
False    137
True      46
Name: GDF7, dtype: int64

GDF9
False    182
True       1
Name: GDF9, dtype: int64

GDI1
False    183
Name: GDI1, dtype: int64

GDI2
False    183
Name: GDI2, dtype: int64

GDNF
False    133
True      50
Name: GDNF, dtype: int64

GDPD1
False    183
Name: GDPD1, dtype: int64

GDPD2
False    177
True       6
Name: GDPD2, dtype: int64

GDPD3
False    183
Name: GDPD3, dtype: int64

GDPD4
False    141
True      42
Name: GDPD4, dtype: int64

GDPD5
False    183
Name: GDPD5, dtype: int64

GEFT
False    183
Name: GEFT, dtype: int64

GEMIN4
False    183
Name: GEMIN4, dtype: int64

GEMIN5
False    183
Name: GEMIN5, dtype: int64

GEMIN6
False    183
Name: GEMIN6, dtype: int64

GEMIN7
False    183
Name: GEMIN7, dtype: int64

GEMIN8P4
False    183
Name: GEMIN8P4, dtype: int64

GEMIN8
False    183
Name: GEMIN8, dtype: int64

GEM
False    183
Name: GEM, dtype: int64

GEN1
False    183
Name: GEN1, dtype: int64

GET4
False    183
Name: GET4, dtype: int64

GFAP
False    180
True       3
Name: GFAP, dtype: int64

GFER
False    183
Name: GFER, dtype: int64

GFI1B
False    173
True      10
Name: GFI1B, dtype: int64

GFI1
False    183
Name: GFI1, dtype: int64

GFM1
False    183
Name: GFM1, dtype: int64

GFM2
False    183
Name: GFM2, dtype: int64

GFOD1
False    183
Name: GFOD1, dtype: int64

GFOD2
False    183
Name: GFOD2, dtype: int64

GFPT1
False    183
Name: GFPT1, dtype: int64

GFPT2
False    183
Name: GFPT2, dtype: int64

GFRA1
False    183
Name: GFRA1, dtype: int64

GFRA2
False    183
Name: GFRA2, dtype: int64

GFRA3
False    181
True       2
Name: GFRA3, dtype: int64

GGA1
False    183
Name: GGA1, dtype: int64

GGA2
False    183
Name: GGA2, dtype: int64

GGA3
False    183
Name: GGA3, dtype: int64

GGCT
False    183
Name: GGCT, dtype: int64

GGCX
False    183
Name: GGCX, dtype: int64

GGH
False    183
Name: GGH, dtype: int64

GGNBP2
False    183
Name: GGNBP2, dtype: int64

GGN
False    183
Name: GGN, dtype: int64

GGPS1
False    183
Name: GGPS1, dtype: int64

GGT1
False    183
Name: GGT1, dtype: int64

GGT3P
False    183
Name: GGT3P, dtype: int64

GGT5
False    183
Name: GGT5, dtype: int64

GGT6
False    177
True       6
Name: GGT6, dtype: int64

GGT7
False    183
Name: GGT7, dtype: int64

GGT8P
False    163
True      20
Name: GGT8P, dtype: int64

GGTA1
False    183
Name: GGTA1, dtype: int64

GGTLC1
False    175
True       8
Name: GGTLC1, dtype: int64

GGTLC2
False    183
Name: GGTLC2, dtype: int64

GH1
True     119
False     64
Name: GH1, dtype: int64

GHDC
False    183
Name: GHDC, dtype: int64

GHITM
False    183
Name: GHITM, dtype: int64

GHRHR
False    114
True      69
Name: GHRHR, dtype: int64

GHRLOS
False    183
Name: GHRLOS, dtype: int64

GHRL
False    181
True       2
Name: GHRL, dtype: int64

GHR
False    183
Name: GHR, dtype: int64

GHSR
False    107
True      76
Name: GHSR, dtype: int64

GIF
False    146
True      37
Name: GIF, dtype: int64

GIGYF1
False    183
Name: GIGYF1, dtype: int64

GIGYF2
False    183
Name: GIGYF2, dtype: int64

GIMAP1
False    183
Name: GIMAP1, dtype: int64

GIMAP2
False    183
Name: GIMAP2, dtype: int64

GIMAP4
False    183
Name: GIMAP4, dtype: int64

GIMAP5
False    183
Name: GIMAP5, dtype: int64

GIMAP6
False    183
Name: GIMAP6, dtype: int64

GIMAP7
False    183
Name: GIMAP7, dtype: int64

GIMAP8
False    183
Name: GIMAP8, dtype: int64

GIN1
False    183
Name: GIN1, dtype: int64

GINS1
False    183
Name: GINS1, dtype: int64

GINS2
False    183
Name: GINS2, dtype: int64

GINS3
False    183
Name: GINS3, dtype: int64

GINS4
False    183
Name: GINS4, dtype: int64

GIPC1
False    183
Name: GIPC1, dtype: int64

GIPC2
False    183
Name: GIPC2, dtype: int64

GIPC3
False    183
Name: GIPC3, dtype: int64

GIPR
False    182
True       1
Name: GIPR, dtype: int64

GIP
True     101
False     82
Name: GIP, dtype: int64

GIT1
False    183
Name: GIT1, dtype: int64

GIT2
False    183
Name: GIT2, dtype: int64

GIYD2

False    183
Name: GIYD2, dtype: int64

GJA1
False    183
Name: GJA1, dtype: int64

GJA3
False    181
True       2
Name: GJA3, dtype: int64

GJA4
False    183
Name: GJA4, dtype: int64

GJA5
False    183
Name: GJA5, dtype: int64

GJA9
False    183
Name: GJA9, dtype: int64

GJB1
False    182
True       1
Name: GJB1, dtype: int64

GJB2
False    182
True       1
Name: GJB2, dtype: int64

GJB3
False    180
True       3
Name: GJB3, dtype: int64

GJB4
False    176
True       7
Name: GJB4, dtype: int64

GJB5
False    180
True       3
Name: GJB5, dtype: int64

GJB6
False    177
True       6
Name: GJB6, dtype: int64

GJB7
False    95
True     88
Name: GJB7, dtype: int64

GJC1
False    183
Name: GJC1, dtype: int64

GJC2
False    183
Name: GJC2, dtype: int64

GJC3
False    170
True      13
Name: GJC3, dtype: int64

GJD2
False    168
True      15
Name: GJD2, dtype: int64

GJD3
False    183
Name: GJD3, dtype: int64

GJD4
False    114
True      69
Name: GJD4, dtype: int64

GK3P
False    183
Name: GK3P, dtype: int64

GK5
False    183
Name: GK5, dtype: int64

GKAP1
False    183
Name: GKAP1, dtype: int64

GKN1
True     94
False    89
Name: GKN1, dtype: int64

GKN2
False    92
True     91
Name: GKN2, dtype: int64

GK
False    183
Name: GK, dtype: int64

GLA
False    183
Name: GLA, dtype: int64

GLB1L2
False    183
Name: GLB1L2, dtype: int64

GLB1L3
False    129
True      54
Name: GLB1L3, dtype: int64

GLB1L
False    183
Name: GLB1L, dtype: int64

GLB1
False    183
Name: GLB1, dtype: int64

GLCCI1
False    183
Name: GLCCI1, dtype: int64

GLCE
False    183
Name: GLCE, dtype: int64

GLDC
False    181
True       2
Name: GLDC, dtype: int64

GLDN
False    183
Name: GLDN, dtype: int64

GLE1
False    183
Name: GLE1, dtype: int64

GLG1
False    183
Name: GLG1, dtype: int64

GLI1
False    183
Name: GLI1, dtype: int64

GLI2
False    183
Name: GLI2, dtype: int64

GLI3
False    183
Name: GLI3, dtype: int64

GLI4
False    183
Name: GLI4, dtype: int64

GLIPR1L1
False    100
True      83
Name: GLIPR1L1, dtype: int64

GLIPR1L2
False    183
Name: GLIPR1L2, dtype: int64

GLIPR1
False    183
Name: GLIPR1, dtype: int64

GLIPR2
False    183
Name: GLIPR2, dtype: int64

GLIS1
False    182
True       1
Name: GLIS1, dtype: int64

GLIS2
False    183
Name: GLIS2, dtype: int64

GLIS3
False    183
Name: GLIS3, dtype: int64

GLMN
False    183
Name: GLMN, dtype: int64

GLO1
False    183
Name: GLO1, dtype: int64

GLOD4
False    183
Name: GLOD4, dtype: int64

GLOD5
False    182
True       1
Name: GLOD5, dtype: int64

GLP1R
False    175
True       8
Name: GLP1R, dtype: int64

GLP2R
False    180
True       3
Name: GLP2R, dtype: int64

GLRA1
False    119
True      64
Name: GLRA1, dtype: int64

GLRA2
True     98
False    85
Name: GLRA2, dtype: int64

GLRA3
False    143
True      40
Name: GLRA3, dtype: int64

GLRB
False    183
Name: GLRB, dtype: int64

GLRX2
False    183
Name: GLRX2, dtype: int64

GLRX3
False    183
Name: GLRX3, dtype: int64

GLRX5
False    183
Name: GLRX5, dtype: int64

GLRX
False    183
Name: GLRX, dtype: int64

GLS2
False    183
Name: GLS2, dtype: int64

GLS
False    183
Name: GLS, dtype: int64

GLT1D1
False    181
True       2
Name: GLT1D1, dtype: int64

GLT25D1
False    183
Name: GLT25D1, dtype: int64

GLT25D2
False    183
Name: GLT25D2, dtype: int64

GLT8D1
False    183
Name: GLT8D1, dtype: int64

GLT8D2
False    183
Name: GLT8D2, dtype: int64

GLTPD1
False    183
Name: GLTPD1, dtype: int64

GLTPD2
False    108
True      75
Name: GLTPD2, dtype: int64

GLTP
False    183
Name: GLTP, dtype: int64

GLTSCR1
False    183
Name: GLTSCR1, dtype: int64

GLTSCR2
False    183
Name: GLTSCR2, dtype: int64

GLUD1
False    183
Name: GLUD1, dtype: int64

GLUD2
False    183
Name: GLUD2, dtype: int64

GLUL
False    183
Name: GLUL, dtype: int64

GLYATL1
False    171
True      12
Name: GLYATL1, dtype: int64

GLYATL2
False    174
True       9
Name: GLYATL2, dtype: int64

GLYAT
True     110
False     73
Name: GLYAT, dtype: int64

GLYCTK
False    183
Name: GLYCTK, dtype: int64

GLYR1
False    183
Name: GLYR1, dtype: int64

GM2A
False    183
Name: GM2A, dtype: int64

GMCL1L
False    173
True      10
Name: GMCL1L, dtype: int64

GMCL1
False    183
Name: GMCL1, dtype: int64

GMDS
False    183
Name: GMDS, dtype: int64

GMEB1
False    183
Name: GMEB1, dtype: int64

GMEB2
False    183
Name: GMEB2, dtype: int64

GMFB
False    183
Name: GMFB, dtype: int64

GMFG
False    183
Name: GMFG, dtype: int64

GMIP
False    183
Name: GMIP, dtype: int64

GMNN
False    183
Name: GMNN, dtype: int64

GMPPA
False    183
Name: GMPPA, dtype: int64

GMPPB
False    183
Name: GMPPB, dtype: int64

GMPR2
False    183
Name: GMPR2, dtype: int64

GMPR
False    183
Name: GMPR, dtype: int64

GMPS
False    183
Name: GMPS, dtype: int64

GNA11
False    183
Name: GNA11, dtype: int64

GNA12
False    183
Name: GNA12, dtype: int64

GNA13
False    183
Name: GNA13, dtype: int64

GNA14
False    183
Name: GNA14, dtype: int64

GNA15
False    183
Name: GNA15, dtype: int64

GNAI1
False    183
Name: GNAI1, dtype: int64

GNAI2
False    183
Name: GNAI2, dtype: int64

GNAI3
False    183
Name: GNAI3, dtype: int64

GNAL
False    183
Name: GNAL, dtype: int64

GNAO1
False    183
Name: GNAO1, dtype: int64

GNAQ
False    183
Name: GNAQ, dtype: int64

GNASAS
False    165
True      18
Name: GNASAS, dtype: int64

GNAS
False    183
Name: GNAS, dtype: int64

GNAT1
True     128
False     55
Name: GNAT1, dtype: int64

GNAT2
False    153
True      30
Name: GNAT2, dtype: int64

GNAT3
False    97
True     86
Name: GNAT3, dtype: int64

GNAZ
False    183
Name: GNAZ, dtype: int64

GNB1L
False    183
Name: GNB1L, dtype: int64

GNB1
False    183
Name: GNB1, dtype: int64

GNB2L1
False    183
Name: GNB2L1, dtype: int64

GNB2
False    183
Name: GNB2, dtype: int64

GNB3
False    183
Name: GNB3, dtype: int64

GNB4
False    183
Name: GNB4, dtype: int64

GNB5
False    183
Name: GNB5, dtype: int64

GNE
False    183
Name: GNE, dtype: int64

GNG10
False    183
Name: GNG10, dtype: int64

GNG11
False    183
Name: GNG11, dtype: int64

GNG12
False    183
Name: GNG12, dtype: int64

GNG13
False    145
True      38
Name: GNG13, dtype: int64

GNG2
False    183
Name: GNG2, dtype: int64

GNG3
False    182
True       1
Name: GNG3, dtype: int64

GNG4
False    183
Name: GNG4, dtype: int64

GNG5
False    183
Name: GNG5, dtype: int64

GNG7
False    183
Name: GNG7, dtype: int64

GNG8
True     102
False     81
Name: GNG8, dtype: int64

GNGT1
True     101
False     82
Name: GNGT1, dtype: int64

GNGT2
False    183
Name: GNGT2, dtype: int64

GNL1
False    183
Name: GNL1, dtype: int64

GNL2
False    183
Name: GNL2, dtype: int64

GNL3L
False    183
Name: GNL3L, dtype: int64

GNL3
False    183
Name: GNL3, dtype: int64

GNLY
False    183
Name: GNLY, dtype: int64

GNMT
False    182
True       1
Name: GNMT, dtype: int64

GNPAT
False    183
Name: GNPAT, dtype: int64

GNPDA1
False    183
Name: GNPDA1, dtype: int64

GNPDA2
False    183
Name: GNPDA2, dtype: int64

GNPNAT1
False    183
Name: GNPNAT1, dtype: int64

GNPTAB
False    183
Name: GNPTAB, dtype: int64

GNPTG
False    183
Name: GNPTG, dtype: int64

GNRH1
False    183
Name: GNRH1, dtype: int64

GNRHR2
False    183
Name: GNRHR2, dtype: int64

GNRHR
False    161
True      22
Name: GNRHR, dtype: int64

GNS
False    183
Name: GNS, dtype: int64

GOLGA1
False    183
Name: GOLGA1, dtype: int64

GOLGA2B
False    183
Name: GOLGA2B, dtype: int64

GOLGA2
False    183
Name: GOLGA2, dtype: int64

GOLGA3
False    183
Name: GOLGA3, dtype: int64

GOLGA4
False    183
Name: GOLGA4, dtype: int64

GOLGA5
False    183
Name: GOLGA5, dtype: int64

GOLGA6A
True     120
False     63
Name: GOLGA6A, dtype: int64

GOLGA6B
False    141
True      42
Name: GOLGA6B, dtype: int64

GOLGA6L10
False    183
Name: GOLGA6L10, dtype: int64

GOLGA6L5
False    182
True       1
Name: GOLGA6L5, dtype: int64

GOLGA6L9
False    183
Name: GOLGA6L9, dtype: int64

GOLGA7B
False    183
Name: GOLGA7B, dtype: int64

GOLGA7
False    183
Name: GOLGA7, dtype: int64

GOLGA8A
False    183
Name: GOLGA8A, dtype: int64

GOLGA8B
False    183
Name: GOLGA8B, dtype: int64

GOLGA8C
False    162
True      21
Name: GOLGA8C, dtype: int64

GOLGA8DP
False    104
True      79
Name: GOLGA8DP, dtype: int64

GOLGA8G
True     92
False    91
Name: GOLGA8G, dtype: int64

GOLGA9P
False    148
True      35
Name: GOLGA9P, dtype: int64

GOLGB1
False    183
Name: GOLGB1, dtype: int64

GOLIM4
False    183
Name: GOLIM4, dtype: int64

GOLM1
False    183
Name: GOLM1, dtype: int64

GOLPH3L
False    183
Name: GOLPH3L, dtype: int64

GOLPH3
False    183
Name: GOLPH3, dtype: int64

GOLT1A
False    181
True       2
Name: GOLT1A, dtype: int64

GOLT1B
False    183
Name: GOLT1B, dtype: int64

GON4L
False    183
Name: GON4L, dtype: int64

GOPC
False    183
Name: GOPC, dtype: int64

GORAB
False    183
Name: GORAB, dtype: int64

GORASP1
False    183
Name: GORASP1, dtype: int64

GORASP2

False    183
Name: GORASP2, dtype: int64

GOSR1
False    183
Name: GOSR1, dtype: int64

GOSR2
False    183
Name: GOSR2, dtype: int64

GOT1
False    183
Name: GOT1, dtype: int64

GOT2
False    183
Name: GOT2, dtype: int64

GP1BA
False    177
True       6
Name: GP1BA, dtype: int64

GP2
False    178
True       5
Name: GP2, dtype: int64

GP5
False    175
True       8
Name: GP5, dtype: int64

GP6
False    181
True       2
Name: GP6, dtype: int64

GP9
True     125
False     58
Name: GP9, dtype: int64

GPA33
False    182
True       1
Name: GPA33, dtype: int64

GPAA1
False    183
Name: GPAA1, dtype: int64

GPAM
False    183
Name: GPAM, dtype: int64

GPAT2
False    183
Name: GPAT2, dtype: int64

GPATCH1
False    183
Name: GPATCH1, dtype: int64

GPATCH2
False    183
Name: GPATCH2, dtype: int64

GPATCH3
False    183
Name: GPATCH3, dtype: int64

GPATCH4
False    183
Name: GPATCH4, dtype: int64

GPATCH8
False    183
Name: GPATCH8, dtype: int64

GPBAR1
False    183
Name: GPBAR1, dtype: int64

GPBP1L1
False    183
Name: GPBP1L1, dtype: int64

GPBP1
False    183
Name: GPBP1, dtype: int64

GPC1
False    183
Name: GPC1, dtype: int64

GPC2
False    183
Name: GPC2, dtype: int64

GPC3
False    183
Name: GPC3, dtype: int64

GPC4
False    183
Name: GPC4, dtype: int64

GPC5
False    173
True      10
Name: GPC5, dtype: int64

GPC6
False    183
Name: GPC6, dtype: int64

GPCPD1
False    183
Name: GPCPD1, dtype: int64

GPD1L
False    183
Name: GPD1L, dtype: int64

GPD1
False    183
Name: GPD1, dtype: int64

GPD2
False    183
Name: GPD2, dtype: int64

GPER
False    183
Name: GPER, dtype: int64

GPHA2
False    137
True      46
Name: GPHA2, dtype: int64

GPHN
False    183
Name: GPHN, dtype: int64

GPIHBP1
False    183
Name: GPIHBP1, dtype: int64

GPI
False    183
Name: GPI, dtype: int64

GPKOW
False    183
Name: GPKOW, dtype: int64

GPLD1
False    183
Name: GPLD1, dtype: int64

GPM6A
False    181
True       2
Name: GPM6A, dtype: int64

GPM6B
False    183
Name: GPM6B, dtype: int64

GPN1
False    183
Name: GPN1, dtype: int64

GPN2
False    183
Name: GPN2, dtype: int64

GPN3
False    183
Name: GPN3, dtype: int64

GPNMB
False    183
Name: GPNMB, dtype: int64

GPR107
False    183
Name: GPR107, dtype: int64

GPR108
False    183
Name: GPR108, dtype: int64

GPR109A
False    181
True       2
Name: GPR109A, dtype: int64

GPR109B
False    181
True       2
Name: GPR109B, dtype: int64

GPR110
False    178
True       5
Name: GPR110, dtype: int64

GPR111
False    144
True      39
Name: GPR111, dtype: int64

GPR112
False    98
True     85
Name: GPR112, dtype: int64

GPR113
False    183
Name: GPR113, dtype: int64

GPR114
False    183
Name: GPR114, dtype: int64

GPR115
False    181
True       2
Name: GPR115, dtype: int64

GPR116
False    183
Name: GPR116, dtype: int64

GPR119
False    148
True      35
Name: GPR119, dtype: int64

GPR120
False    182
True       1
Name: GPR120, dtype: int64

GPR123
False    174
True       9
Name: GPR123, dtype: int64

GPR124
False    183
Name: GPR124, dtype: int64

GPR125
False    183
Name: GPR125, dtype: int64

GPR126
False    183
Name: GPR126, dtype: int64

GPR128
False    169
True      14
Name: GPR128, dtype: int64

GPR12
False    131
True      52
Name: GPR12, dtype: int64

GPR132
False    183
Name: GPR132, dtype: int64

GPR133
False    183
Name: GPR133, dtype: int64

GPR135
False    182
True       1
Name: GPR135, dtype: int64

GPR137B
False    183
Name: GPR137B, dtype: int64

GPR137C
False    183
Name: GPR137C, dtype: int64

GPR137
False    183
Name: GPR137, dtype: int64

GPR141
False    173
True      10
Name: GPR141, dtype: int64

GPR142
False    169
True      14
Name: GPR142, dtype: int64

GPR143
False    183
Name: GPR143, dtype: int64

GPR146
False    183
Name: GPR146, dtype: int64

GPR148
False    113
True      70
Name: GPR148, dtype: int64

GPR150
False    144
True      39
Name: GPR150, dtype: int64

GPR152
False    147
True      36
Name: GPR152, dtype: int64

GPR153
False    183
Name: GPR153, dtype: int64

GPR155
False    183
Name: GPR155, dtype: int64

GPR156
False    153
True      30
Name: GPR156, dtype: int64

GPR157
False    182
True       1
Name: GPR157, dtype: int64

GPR158
False    182
True       1
Name: GPR158, dtype: int64

GPR15
False    135
True      48
Name: GPR15, dtype: int64

GPR160
False    183
Name: GPR160, dtype: int64

GPR161
False    183
Name: GPR161, dtype: int64

GPR162
False    183
Name: GPR162, dtype: int64

GPR171
False    182
True       1
Name: GPR171, dtype: int64

GPR172A
False    183
Name: GPR172A, dtype: int64

GPR172B
False    180
True       3
Name: GPR172B, dtype: int64

GPR173
False    183
Name: GPR173, dtype: int64

GPR174
False    176
True       7
Name: GPR174, dtype: int64

GPR176
False    183
Name: GPR176, dtype: int64

GPR179
False    171
True      12
Name: GPR179, dtype: int64

GPR17
False    183
Name: GPR17, dtype: int64

GPR180
False    183
Name: GPR180, dtype: int64

GPR182
False    169
True      14
Name: GPR182, dtype: int64

GPR183
False    183
Name: GPR183, dtype: int64

GPR18
False    181
True       2
Name: GPR18, dtype: int64

GPR19
False    183
Name: GPR19, dtype: int64

GPR1
False    182
True       1
Name: GPR1, dtype: int64

GPR20
False    182
True       1
Name: GPR20, dtype: int64

GPR21
False    168
True      15
Name: GPR21, dtype: int64

GPR22
False    113
True      70
Name: GPR22, dtype: int64

GPR25
False    137
True      46
Name: GPR25, dtype: int64

GPR26
False    116
True      67
Name: GPR26, dtype: int64

GPR27
False    174
True       9
Name: GPR27, dtype: int64

GPR31
True     94
False    89
Name: GPR31, dtype: int64

GPR34
False    183
Name: GPR34, dtype: int64

GPR35
False    183
Name: GPR35, dtype: int64

GPR37L1
False    182
True       1
Name: GPR37L1, dtype: int64

GPR37
False    182
True       1
Name: GPR37, dtype: int64

GPR39
False    182
True       1
Name: GPR39, dtype: int64

GPR3
False    183
Name: GPR3, dtype: int64

GPR44
False    183
Name: GPR44, dtype: int64

GPR45
False    126
True      57
Name: GPR45, dtype: int64

GPR4
False    183
Name: GPR4, dtype: int64

GPR52
True     114
False     69
Name: GPR52, dtype: int64

GPR55
False    180
True       3
Name: GPR55, dtype: int64

GPR56
False    183
Name: GPR56, dtype: int64

GPR61
False    148
True      35
Name: GPR61, dtype: int64

GPR62
False    168
True      15
Name: GPR62, dtype: int64

GPR63
False    183
Name: GPR63, dtype: int64

GPR64
False    183
Name: GPR64, dtype: int64

GPR65
False    183
Name: GPR65, dtype: int64

GPR68
False    183
Name: GPR68, dtype: int64

GPR6
True     95
False    88
Name: GPR6, dtype: int64

GPR75
False    183
Name: GPR75, dtype: int64

GPR77
False    181
True       2
Name: GPR77, dtype: int64

GPR78
False    102
True      81
Name: GPR78, dtype: int64

GPR81
False    182
True       1
Name: GPR81, dtype: int64

GPR82
False    182
True       1
Name: GPR82, dtype: int64

GPR83
False    179
True       4
Name: GPR83, dtype: int64

GPR84
False    183
Name: GPR84, dtype: int64

GPR85
False    183
Name: GPR85, dtype: int64

GPR87
False    175
True       8
Name: GPR87, dtype: int64

GPR88
False    176
True       7
Name: GPR88, dtype: int64

GPR89A
False    183
Name: GPR89A, dtype: int64

GPR89B
False    181
True       2
Name: GPR89B, dtype: int64

GPR89C
False    183
Name: GPR89C, dtype: int64

GPR97
False    183
Name: GPR97, dtype: int64

GPR98
False    183
Name: GPR98, dtype: int64

GPRASP1
False    183
Name: GPRASP1, dtype: int64

GPRASP2
False    183
Name: GPRASP2, dtype: int64

GPRC5A
False    183
Name: GPRC5A, dtype: int64

GPRC5B
False    183
Name: GPRC5B, dtype: int64

GPRC5C
False    183
Name: GPRC5C, dtype: int64

GPRC5D
False    183
Name: GPRC5D, dtype: int64

GPRIN1
False    183
Name: GPRIN1, dtype: int64

GPRIN2
False    183
Name: GPRIN2, dtype: int64

GPRIN3
False    183
Name: GPRIN3, dtype: int64

GPS1
False    183
Name: GPS1, dtype: int64

GPS2
False    183
Name: GPS2, dtype: int64

GPSM1
False    183
Name: GPSM1, dtype: int64

GPSM2
False    183
Name: GPSM2, dtype: int64

GPSM3
False    183
Name: GPSM3, dtype: int64

GPT2
False    183
Name: GPT2, dtype: int64

GPT
False    183
Name: GPT, dtype: int64

GPX1
False    183
Name: GPX1, dtype: int64

GPX2
False    183
Name: GPX2, dtype: int64

GPX3
False    183
Name: GPX3, dtype: int64

GPX4
False    183
Name: GPX4, dtype: int64

GPX7
False    183
Name: GPX7, dtype: int64

GPX8
False    183
Name: GPX8, dtype: int64

GRAMD1A
False    183
Name: GRAMD1A, dtype: int64

GRAMD1B
False    183
Name: GRAMD1B, dtype: int64

GRAMD1C
False    183
Name: GRAMD1C, dtype: int64

GRAMD2
False    183
Name: GRAMD2, dtype: int64

GRAMD3
False    183
Name: GRAMD3, dtype: int64

GRAMD4
False    183
Name: GRAMD4, dtype: int64

GRAP2
False    183
Name: GRAP2, dtype: int64

GRAPL
False    178
True       5
Name: GRAPL, dtype: int64

GRAP
False    183
Name: GRAP, dtype: int64

GRASP
False    183
Name: GRASP, dtype: int64

GRB10

False    183
Name: GRB10, dtype: int64

GRB14
False    183
Name: GRB14, dtype: int64

GRB2
False    183
Name: GRB2, dtype: int64

GRB7
False    183
Name: GRB7, dtype: int64

GREB1L
False    180
True       3
Name: GREB1L, dtype: int64

GREB1
False    183
Name: GREB1, dtype: int64

GREM1
False    183
Name: GREM1, dtype: int64

GREM2
False    180
True       3
Name: GREM2, dtype: int64

GRHL1
False    183
Name: GRHL1, dtype: int64

GRHL2
False    182
True       1
Name: GRHL2, dtype: int64

GRHL3
False    181
True       2
Name: GRHL3, dtype: int64

GRHPR
False    183
Name: GRHPR, dtype: int64

GRIA1
False    163
True      20
Name: GRIA1, dtype: int64

GRIA2
False    177
True       6
Name: GRIA2, dtype: int64

GRIA3
False    183
Name: GRIA3, dtype: int64

GRIA4
False    182
True       1
Name: GRIA4, dtype: int64

GRID1
False    183
Name: GRID1, dtype: int64

GRID2IP
False    182
True       1
Name: GRID2IP, dtype: int64

GRID2
True     120
False     63
Name: GRID2, dtype: int64

GRIK1
False    144
True      39
Name: GRIK1, dtype: int64

GRIK2
False    183
Name: GRIK2, dtype: int64

GRIK3
False    183
Name: GRIK3, dtype: int64

GRIK4
False    165
True      18
Name: GRIK4, dtype: int64

GRIK5
False    183
Name: GRIK5, dtype: int64

GRIN1
False    182
True       1
Name: GRIN1, dtype: int64

GRIN2A
False    183
Name: GRIN2A, dtype: int64

GRIN2B
False    100
True      83
Name: GRIN2B, dtype: int64

GRIN2C
False    182
True       1
Name: GRIN2C, dtype: int64

GRIN2D
False    183
Name: GRIN2D, dtype: int64

GRIN3A
False    183
Name: GRIN3A, dtype: int64

GRIN3B
False    173
True      10
Name: GRIN3B, dtype: int64

GRINA
False    183
Name: GRINA, dtype: int64

GRINL1A
False    183
Name: GRINL1A, dtype: int64

GRIP1
False    183
Name: GRIP1, dtype: int64

GRIP2
False    180
True       3
Name: GRIP2, dtype: int64

GRIPAP1
False    183
Name: GRIPAP1, dtype: int64

GRK4
False    183
Name: GRK4, dtype: int64

GRK5
False    183
Name: GRK5, dtype: int64

GRK6
False    183
Name: GRK6, dtype: int64

GRK7
False    123
True      60
Name: GRK7, dtype: int64

GRLF1
False    183
Name: GRLF1, dtype: int64

GRM1
False    168
True      15
Name: GRM1, dtype: int64

GRM2
False    181
True       2
Name: GRM2, dtype: int64

GRM3
False    166
True      17
Name: GRM3, dtype: int64

GRM4
False    178
True       5
Name: GRM4, dtype: int64

GRM5
False    178
True       5
Name: GRM5, dtype: int64

GRM6
False    181
True       2
Name: GRM6, dtype: int64

GRM7
False    165
True      18
Name: GRM7, dtype: int64

GRM8
False    182
True       1
Name: GRM8, dtype: int64

GRN
False    183
Name: GRN, dtype: int64

GRPEL1
False    183
Name: GRPEL1, dtype: int64

GRPEL2
False    183
Name: GRPEL2, dtype: int64

GRPR
False    179
True       4
Name: GRPR, dtype: int64

GRP
False    178
True       5
Name: GRP, dtype: int64

GRRP1
False    183
Name: GRRP1, dtype: int64

GRSF1
False    183
Name: GRSF1, dtype: int64

GRTP1
False    183
Name: GRTP1, dtype: int64

GRWD1
False    183
Name: GRWD1, dtype: int64

GSC
False    183
Name: GSC, dtype: int64

GSDMA
False    180
True       3
Name: GSDMA, dtype: int64

GSDMB
False    183
Name: GSDMB, dtype: int64

GSDMC
False    181
True       2
Name: GSDMC, dtype: int64

GSDMD
False    183
Name: GSDMD, dtype: int64

GSG1L
False    148
True      35
Name: GSG1L, dtype: int64

GSG1
False    123
True      60
Name: GSG1, dtype: int64

GSG2
False    182
True       1
Name: GSG2, dtype: int64

GSK3A
False    183
Name: GSK3A, dtype: int64

GSK3B
False    183
Name: GSK3B, dtype: int64

GSN
False    183
Name: GSN, dtype: int64

GSPT1
False    183
Name: GSPT1, dtype: int64

GSPT2
False    183
Name: GSPT2, dtype: int64

GSR
False    183
Name: GSR, dtype: int64

GSS
False    183
Name: GSS, dtype: int64

GSTA1
False    180
True       3
Name: GSTA1, dtype: int64

GSTA2
False    174
True       9
Name: GSTA2, dtype: int64

GSTA4
False    183
Name: GSTA4, dtype: int64

GSTCD
False    183
Name: GSTCD, dtype: int64

GSTK1
False    183
Name: GSTK1, dtype: int64

GSTM1
False    174
True       9
Name: GSTM1, dtype: int64

GSTM2P1
False    162
True      21
Name: GSTM2P1, dtype: int64

GSTM2
False    183
Name: GSTM2, dtype: int64

GSTM3
False    183
Name: GSTM3, dtype: int64

GSTM4
False    183
Name: GSTM4, dtype: int64

GSTM5
False    183
Name: GSTM5, dtype: int64

GSTO1
False    183
Name: GSTO1, dtype: int64

GSTO2
False    183
Name: GSTO2, dtype: int64

GSTP1
False    183
Name: GSTP1, dtype: int64

GSTT1
False    172
True      11
Name: GSTT1, dtype: int64

GSTT2
False    183
Name: GSTT2, dtype: int64

GSTZ1
False    183
Name: GSTZ1, dtype: int64

GTDC1
False    183
Name: GTDC1, dtype: int64

GTF2A1L
False    158
True      25
Name: GTF2A1L, dtype: int64

GTF2A1
False    183
Name: GTF2A1, dtype: int64

GTF2A2
False    183
Name: GTF2A2, dtype: int64

GTF2B
False    183
Name: GTF2B, dtype: int64

GTF2E1
False    183
Name: GTF2E1, dtype: int64

GTF2E2
False    183
Name: GTF2E2, dtype: int64

GTF2F1
False    183
Name: GTF2F1, dtype: int64

GTF2F2
False    183
Name: GTF2F2, dtype: int64

GTF2H1
False    183
Name: GTF2H1, dtype: int64

GTF2H2B
False    182
True       1
Name: GTF2H2B, dtype: int64

GTF2H2C
False    183
Name: GTF2H2C, dtype: int64

GTF2H2
False    183
Name: GTF2H2, dtype: int64

GTF2H3
False    183
Name: GTF2H3, dtype: int64

GTF2H4
False    183
Name: GTF2H4, dtype: int64

GTF2H5
False    183
Name: GTF2H5, dtype: int64

GTF2IP1
False    183
Name: GTF2IP1, dtype: int64

GTF2IRD1
False    183
Name: GTF2IRD1, dtype: int64

GTF2IRD2B
False    183
Name: GTF2IRD2B, dtype: int64

GTF2IRD2P1
False    183
Name: GTF2IRD2P1, dtype: int64

GTF2IRD2
False    183
Name: GTF2IRD2, dtype: int64

GTF2I
False    183
Name: GTF2I, dtype: int64

GTF3A
False    183
Name: GTF3A, dtype: int64

GTF3C1
False    183
Name: GTF3C1, dtype: int64

GTF3C2
False    183
Name: GTF3C2, dtype: int64

GTF3C3
False    183
Name: GTF3C3, dtype: int64

GTF3C4
False    183
Name: GTF3C4, dtype: int64

GTF3C5
False    183
Name: GTF3C5, dtype: int64

GTF3C6
False    183
Name: GTF3C6, dtype: int64

GTPBP10
False    183
Name: GTPBP10, dtype: int64

GTPBP1
False    183
Name: GTPBP1, dtype: int64

GTPBP2
False    183
Name: GTPBP2, dtype: int64

GTPBP3
False    183
Name: GTPBP3, dtype: int64

GTPBP4
False    183
Name: GTPBP4, dtype: int64

GTPBP5
False    183
Name: GTPBP5, dtype: int64

GTPBP8
False    183
Name: GTPBP8, dtype: int64

GTSE1
False    183
Name: GTSE1, dtype: int64

GTSF1L
False    102
True      81
Name: GTSF1L, dtype: int64

GTSF1
False    156
True      27
Name: GTSF1, dtype: int64

GUCA1A
False    171
True      12
Name: GUCA1A, dtype: int64

GUCA1B
False    183
Name: GUCA1B, dtype: int64

GUCA1C
True     98
False    85
Name: GUCA1C, dtype: int64

GUCA2A
False    153
True      30
Name: GUCA2A, dtype: int64

GUCA2B
False    153
True      30
Name: GUCA2B, dtype: int64

GUCY1A2
False    182
True       1
Name: GUCY1A2, dtype: int64

GUCY1A3
False    183
Name: GUCY1A3, dtype: int64

GUCY1B2
False    170
True      13
Name: GUCY1B2, dtype: int64

GUCY1B3
False    183
Name: GUCY1B3, dtype: int64

GUCY2C
False    181
True       2
Name: GUCY2C, dtype: int64

GUCY2D
False    172
True      11
Name: GUCY2D, dtype: int64

GUCY2GP
True     99
False    84
Name: GUCY2GP, dtype: int64

GUF1
False    183
Name: GUF1, dtype: int64

GUK1
False    183
Name: GUK1, dtype: int64

GULP1
False    183
Name: GULP1, dtype: int64

GUSBL1
False    183
Name: GUSBL1, dtype: int64

GUSBL2
False    183
Name: GUSBL2, dtype: int64

GUSBP1
False    183
Name: GUSBP1, dtype: int64

GUSBP3
False    183
Name: GUSBP3, dtype: int64

GUSB
False    183
Name: GUSB, dtype: int64

GVIN1
False    183
Name: GVIN1, dtype: int64

GXYLT1
False    183
Name: GXYLT1, dtype: int64

GXYLT2
False    183
Name: GXYLT2, dtype: int64

GYG1
False    183
Name: GYG1, dtype: int64

GYG2
False    183
Name: GYG2, dtype: int64

GYLTL1B
False    183
Name: GYLTL1B, dtype: int64

GYPC
False    183
Name: GYPC, dtype: int64

GYPE
False    181
True       2
Name: GYPE, dtype: int64

GYS1
False    183
Name: GYS1, dtype: int64

GYS2
False    126
True      57
Name: GYS2, dtype: int64

GZF1
False    183
Name: GZF1, dtype: int64

GZMA
False    183
Name: GZMA, dtype: int64

GZMB
False    183
Name: GZMB, dtype: int64

GZMH
False    183
Name: GZMH, dtype: int64

GZMK
False    183
Name: GZMK, dtype: int64

GZMM
False    183
Name: GZMM, dtype: int64

H19
False    183
Name: H19, dtype: int64

H1F0
False    183
Name: H1F0, dtype: int64

H1FNT
False    102
True      81
Name: H1FNT, dtype: int64

H1FX
False    183
Name: H1FX, dtype: int64

H2AFB1
False    173
True      10
Name: H2AFB1, dtype: int64

H2AFJ
False    183
Name: H2AFJ, dtype: int64

H2AFV
False    183
Name: H2AFV, dtype: int64

H2AFX
False    183
Name: H2AFX, dtype: int64

H2AFY2

False    183
Name: H2AFY2, dtype: int64

H2AFY
False    183
Name: H2AFY, dtype: int64

H2AFZ
False    183
Name: H2AFZ, dtype: int64

H2BFXP
False    181
True       2
Name: H2BFXP, dtype: int64

H3F3A
False    183
Name: H3F3A, dtype: int64

H3F3B
False    183
Name: H3F3B, dtype: int64

H3F3C
False    183
Name: H3F3C, dtype: int64

H6PD
False    183
Name: H6PD, dtype: int64

HAAO
False    183
Name: HAAO, dtype: int64

HABP2
False    182
True       1
Name: HABP2, dtype: int64

HABP4
False    183
Name: HABP4, dtype: int64

HACE1
False    183
Name: HACE1, dtype: int64

HACL1
False    183
Name: HACL1, dtype: int64

HADHA
False    183
Name: HADHA, dtype: int64

HADHB
False    183
Name: HADHB, dtype: int64

HADH
False    183
Name: HADH, dtype: int64

HAGHL
False    183
Name: HAGHL, dtype: int64

HAGH
False    183
Name: HAGH, dtype: int64

HAL
False    183
Name: HAL, dtype: int64

HAMP
False    180
True       3
Name: HAMP, dtype: int64

HAND1
False    107
True      76
Name: HAND1, dtype: int64

HAND2
False    182
True       1
Name: HAND2, dtype: int64

HAO1
False    115
True      68
Name: HAO1, dtype: int64

HAO2
False    104
True      79
Name: HAO2, dtype: int64

HAP1
False    183
Name: HAP1, dtype: int64

HAPLN1
False    180
True       3
Name: HAPLN1, dtype: int64

HAPLN2
False    145
True      38
Name: HAPLN2, dtype: int64

HAPLN3
False    183
Name: HAPLN3, dtype: int64

HAPLN4
False    182
True       1
Name: HAPLN4, dtype: int64

HAR1A
False    182
True       1
Name: HAR1A, dtype: int64

HAR1B
False    168
True      15
Name: HAR1B, dtype: int64

HARBI1
False    183
Name: HARBI1, dtype: int64

HARS2
False    183
Name: HARS2, dtype: int64

HARS
False    183
Name: HARS, dtype: int64

HAS1
False    179
True       4
Name: HAS1, dtype: int64

HAS2AS
False    180
True       3
Name: HAS2AS, dtype: int64

HAS2
False    183
Name: HAS2, dtype: int64

HAS3
False    183
Name: HAS3, dtype: int64

HAT1
False    183
Name: HAT1, dtype: int64

HAUS1
False    183
Name: HAUS1, dtype: int64

HAUS2
False    183
Name: HAUS2, dtype: int64

HAUS3
False    183
Name: HAUS3, dtype: int64

HAUS4
False    183
Name: HAUS4, dtype: int64

HAUS5
False    183
Name: HAUS5, dtype: int64

HAUS6
False    183
Name: HAUS6, dtype: int64

HAUS7
False    183
Name: HAUS7, dtype: int64

HAUS8
False    183
Name: HAUS8, dtype: int64

HAVCR1
False    160
True      23
Name: HAVCR1, dtype: int64

HAVCR2
False    183
Name: HAVCR2, dtype: int64

HAX1
False    183
Name: HAX1, dtype: int64

HBA1
False    156
True      27
Name: HBA1, dtype: int64

HBA2
False    183
Name: HBA2, dtype: int64

HBB
False    183
Name: HBB, dtype: int64

HBD
False    97
True     86
Name: HBD, dtype: int64

HBE1
True     104
False     79
Name: HBE1, dtype: int64

HBEGF
False    183
Name: HBEGF, dtype: int64

HBG1
False    95
True     88
Name: HBG1, dtype: int64

HBG2
True     101
False     82
Name: HBG2, dtype: int64

HBP1
False    183
Name: HBP1, dtype: int64

HBS1L
False    183
Name: HBS1L, dtype: int64

HBXIP
False    183
Name: HBXIP, dtype: int64

HCCS
False    183
Name: HCCS, dtype: int64

HCFC1R1
False    183
Name: HCFC1R1, dtype: int64

HCFC1
False    183
Name: HCFC1, dtype: int64

HCFC2
False    183
Name: HCFC2, dtype: int64

HCG11
False    183
Name: HCG11, dtype: int64

HCG18
False    183
Name: HCG18, dtype: int64

HCG22
False    121
True      62
Name: HCG22, dtype: int64

HCG26
False    183
Name: HCG26, dtype: int64

HCG27
False    183
Name: HCG27, dtype: int64

HCG2P7
False    167
True      16
Name: HCG2P7, dtype: int64

HCG4P6
False    180
True       3
Name: HCG4P6, dtype: int64

HCG4
False    183
Name: HCG4, dtype: int64

HCG9
False    94
True     89
Name: HCG9, dtype: int64

HCK
False    183
Name: HCK, dtype: int64

HCLS1
False    183
Name: HCLS1, dtype: int64

HCN1
False    172
True      11
Name: HCN1, dtype: int64

HCN2
False    183
Name: HCN2, dtype: int64

HCN3
False    183
Name: HCN3, dtype: int64

HCN4
False    180
True       3
Name: HCN4, dtype: int64

HCP5
False    183
Name: HCP5, dtype: int64

HCRTR1
False    140
True      43
Name: HCRTR1, dtype: int64

HCRTR2
True     114
False     69
Name: HCRTR2, dtype: int64

HCRT
False    99
True     84
Name: HCRT, dtype: int64

HCST
False    183
Name: HCST, dtype: int64

HDAC10
False    183
Name: HDAC10, dtype: int64

HDAC11
False    183
Name: HDAC11, dtype: int64

HDAC1
False    183
Name: HDAC1, dtype: int64

HDAC2
False    183
Name: HDAC2, dtype: int64

HDAC3
False    183
Name: HDAC3, dtype: int64

HDAC4
False    183
Name: HDAC4, dtype: int64

HDAC5
False    183
Name: HDAC5, dtype: int64

HDAC6
False    183
Name: HDAC6, dtype: int64

HDAC7
False    183
Name: HDAC7, dtype: int64

HDAC8
False    183
Name: HDAC8, dtype: int64

HDAC9
False    183
Name: HDAC9, dtype: int64

HDC
False    183
Name: HDC, dtype: int64

HDDC2
False    183
Name: HDDC2, dtype: int64

HDDC3
False    183
Name: HDDC3, dtype: int64

HDGFRP2
False    183
Name: HDGFRP2, dtype: int64

HDGFRP3
False    183
Name: HDGFRP3, dtype: int64

HDGF
False    183
Name: HDGF, dtype: int64

HDHD1A
False    183
Name: HDHD1A, dtype: int64

HDHD2
False    183
Name: HDHD2, dtype: int64

HDHD3
False    183
Name: HDHD3, dtype: int64

HDLBP
False    183
Name: HDLBP, dtype: int64

HDX
False    183
Name: HDX, dtype: int64

HEATR1
False    183
Name: HEATR1, dtype: int64

HEATR2
False    183
Name: HEATR2, dtype: int64

HEATR3
False    183
Name: HEATR3, dtype: int64

HEATR4
False    176
True       7
Name: HEATR4, dtype: int64

HEATR5A
False    183
Name: HEATR5A, dtype: int64

HEATR5B
False    183
Name: HEATR5B, dtype: int64

HEATR6
False    183
Name: HEATR6, dtype: int64

HEATR7A
False    183
Name: HEATR7A, dtype: int64

HEATR7B2
True     118
False     65
Name: HEATR7B2, dtype: int64

HEBP1
False    183
Name: HEBP1, dtype: int64

HEBP2
False    183
Name: HEBP2, dtype: int64

HECA
False    183
Name: HECA, dtype: int64

HECTD1
False    183
Name: HECTD1, dtype: int64

HECTD2
False    183
Name: HECTD2, dtype: int64

HECTD3
False    183
Name: HECTD3, dtype: int64

HECW1
False    179
True       4
Name: HECW1, dtype: int64

HECW2
False    183
Name: HECW2, dtype: int64

HEG1
False    183
Name: HEG1, dtype: int64

HELB
False    183
Name: HELB, dtype: int64

HELLS
False    183
Name: HELLS, dtype: int64

HELQ
False    183
Name: HELQ, dtype: int64

HELZ
False    183
Name: HELZ, dtype: int64

HEMGN
False    121
True      62
Name: HEMGN, dtype: int64

HEMK1
False    183
Name: HEMK1, dtype: int64

HEPACAM2
False    178
True       5
Name: HEPACAM2, dtype: int64

HEPACAM
False    124
True      59
Name: HEPACAM, dtype: int64

HEPHL1
False    155
True      28
Name: HEPHL1, dtype: int64

HEPH
False    183
Name: HEPH, dtype: int64

HEPN1
False    102
True      81
Name: HEPN1, dtype: int64

HERC1
False    183
Name: HERC1, dtype: int64

HERC2P2
False    183
Name: HERC2P2, dtype: int64

HERC2P4
False    162
True      21
Name: HERC2P4, dtype: int64

HERC2
False    183
Name: HERC2, dtype: int64

HERC3
False    183
Name: HERC3, dtype: int64

HERC4
False    183
Name: HERC4, dtype: int64

HERC5
False    183
Name: HERC5, dtype: int64

HERC6
False    183
Name: HERC6, dtype: int64

HERPUD1
False    183
Name: HERPUD1, dtype: int64

HERPUD2
False    183
Name: HERPUD2, dtype: int64

HES1
False    183
Name: HES1, dtype: int64

HES2
False    181
True       2
Name: HES2, dtype: int64

HES4
False    183
Name: HES4, dtype: int64

HES5
False    145
True      38
Name: HES5, dtype: int64

HES6
False    183
Name: HES6, dtype: int64

HES7
False    161
True      22
Name: HES7, dtype: int64

HESRG
True     128
False     55
Name: HESRG, dtype: int64

HESX1
False    183
Name: HESX1, dtype: int64

HEXA
False    183
Name: HEXA, dtype: int64

HEXB
False    183
Name: HEXB, dtype: int64

HEXDC
False    183
Name: HEXDC, dtype: int64

HEXIM1
False    183
Name: HEXIM1, dtype: int64

HEXIM2
False    183
Name: HEXIM2, dtype: int64

HEY1
False    183
Name: HEY1, dtype: int64

HEY2
False    183
Name: HEY2, dtype: int64

HEYL
False    183
Name: HEYL, dtype: int64

HFE2
False    98
True     85
Name: HFE2, dtype: int64

HFE
False    183
Name: HFE, dtype: int64

HFM1
False    165
True      18
Name: HFM1, dtype: int64

HGC6.3
True     115
False     68
Name: HGC6.3, dtype: int64

HGD
False    183
Name: HGD, dtype: int64

HGFAC
False    140
True      43
Name: HGFAC, dtype: int64

HGF
False    182
True       1
Name: HGF, dtype: int64

HGSNAT
False    183
Name: HGSNAT, dtype: int64

HGS
False    183
Name: HGS, dtype: int64

HHATL
False    141
True      42
Name: HHATL, dtype: int64

HHAT
False    183
Name: HHAT, dtype: int64

HHEX
False    183
Name: HHEX, dtype: int64

HHIPL1
False    183
Name: HHIPL1, dtype: int64

HHIPL2
False    165
True      18
Name: HHIPL2, dtype: int64

HHIP
False    182
True       1
Name: HHIP, dtype: int64

HHLA2
False    182
True       1
Name: HHLA2, dtype: int64

HHLA3
False    183
Name: HHLA3, dtype: int64

HIAT1
False    183
Name: HIAT1, dtype: int64

HIATL1
False    183
Name: HIATL1, dtype: int64

HIATL2
False    183
Name: HIATL2, dtype: int64

HIBADH
False    183
Name: HIBADH, dtype: int64

HIBCH
False    183
Name: HIBCH, dtype: int64

HIC1
False    183
Name: HIC1, dtype: int64

HIC2
False    183
Name: HIC2, dtype: int64

HIF1AN
False    183
Name: HIF1AN, dtype: int64

HIF1A
False    183
Name: HIF1A, dtype: int64

HIF3A
False    183
Name: HIF3A, dtype: int64

HIGD1A
False    183
Name: HIGD1A, dtype: int64

HIGD1B
False    183
Name: HIGD1B, dtype: int64

HIGD2A
False    183
Name: HIGD2A, dtype: int64

HIGD2B
True     106
False     77
Name: HIGD2B, dtype: int64

HILS1
False    122
True      61
Name: HILS1, dtype: int64

HINFP
False    183
Name: HINFP, dtype: int64

HINT1
False    183
Name: HINT1, dtype: int64

HINT2
False    183
Name: HINT2, dtype: int64

HINT3
False    183
Name: HINT3, dtype: int64

HIP1R
False    183
Name: HIP1R, dtype: int64

HIP1
False    183
Name: HIP1, dtype: int64

HIPK1
False    183
Name: HIPK1, dtype: int64

HIPK2
False    183
Name: HIPK2, dtype: int64

HIPK3
False    183
Name: HIPK3, dtype: int64

HIPK4
False    180
True       3
Name: HIPK4, dtype: int64

HIRA
False    183
Name: HIRA, dtype: int64

HIRIP3
False    183
Name: HIRIP3, dtype: int64

HIST1H1B
False    132
True      51
Name: HIST1H1B, dtype: int64

HIST1H1C
False    183
Name: HIST1H1C, dtype: int64

HIST1H1D
False    161
True      22
Name: HIST1H1D, dtype: int64

HIST1H1E
False    180
True       3
Name: HIST1H1E, dtype: int64

HIST1H1T
True     105
False     78
Name: HIST1H1T, dtype: int64

HIST1H2AB
True     128
False     55
Name: HIST1H2AB, dtype: int64

HIST1H2AC
False    183
Name: HIST1H2AC, dtype: int64

HIST1H2AD
True     98
False    85
Name: HIST1H2AD, dtype: int64

HIST1H2AE
False    180
True       3
Name: HIST1H2AE, dtype: int64

HIST1H2AG
False    169
True      14
Name: HIST1H2AG, dtype: int64

HIST1H2AH
False    95
True     88
Name: HIST1H2AH, dtype: int64

HIST1H2AJ
False    101
True      82
Name: HIST1H2AJ, dtype: int64

HIST1H2AK
False    165
True      18
Name: HIST1H2AK, dtype: int64

HIST1H2AL
False    108
True      75
Name: HIST1H2AL, dtype: int64

HIST1H2AM
False    164
True      19
Name: HIST1H2AM, dtype: int64

HIST1H2BC
False    183
Name: HIST1H2BC, dtype: int64

HIST1H2BD
False    183
Name: HIST1H2BD, dtype: int64

HIST1H2BE
False    183
Name: HIST1H2BE, dtype: int64

HIST1H2BF
False    138
True      45
Name: HIST1H2BF, dtype: int64

HIST1H2BG
False    174
True       9
Name: HIST1H2BG, dtype: int64

HIST1H2BH
False    154
True      29
Name: HIST1H2BH, dtype: int64

HIST1H2BJ
False    183
Name: HIST1H2BJ, dtype: int64

HIST1H2BK
False    183
Name: HIST1H2BK, dtype: int64

HIST1H2BL
False    133
True      50
Name: HIST1H2BL, dtype: int64

HIST1H2BM
True     103
False     80
Name: HIST1H2BM, dtype: int64

HIST1H2BN
False    179
True       4
Name: HIST1H2BN, dtype: int64

HIST1H2BO
False    153
True      30
Name: HIST1H2BO, dtype: int64

HIST1H3A
False    100
True      83
Name: HIST1H3A, dtype: int64

HIST1H3B
False    108
True      75
Name: HIST1H3B, dtype: int64

HIST1H3C
False    114
True      69
Name: HIST1H3C, dtype: int64

HIST1H3D
False    180
True       3
Name: HIST1H3D, dtype: int64

HIST1H3E
False    182
True       1
Name: HIST1H3E, dtype: int64

HIST1H3G
False    102
True      81
Name: HIST1H3G, dtype: int64

HIST1H3H
False    176
True       7
Name: HIST1H3H, dtype: int64

HIST1H3I
True     113
False     70
Name: HIST1H3I, dtype: int64

HIST1H3J
False    93
True     90
Name: HIST1H3J, dtype: int64

HIST1H4A
True     116
False     67
Name: HIST1H4A, dtype: int64

HIST1H4B
True     94
False    89
Name: HIST1H4B, dtype: int64

HIST1H4C
False    119
True      64
Name: HIST1H4C, dtype: int64

HIST1H4D
False    110
True      73
Name: HIST1H4D, dtype: int64

HIST1H4E
False    164
True      19
Name: HIST1H4E, dtype: int64

HIST1H4H
False    183
Name: HIST1H4H, dtype: int64

HIST1H4I
False    145
True      38
Name: HIST1H4I, dtype: int64

HIST1H4J
False    183
Name: HIST1H4J, dtype: int64

HIST2H2AA3
False    183
Name: HIST2H2AA3, dtype: int64

HIST2H2AB
False    96
True     87
Name: HIST2H2AB, dtype: int64

HIST2H2AC
False    183
Name: HIST2H2AC, dtype: int64

HIST2H2BA
False    181
True       2
Name: HIST2H2BA, dtype: int64

HIST2H2BE
False    183
Name: HIST2H2BE, dtype: int64

HIST2H2BF
False    183
Name: HIST2H2BF, dtype: int64

HIST2H3C
False    169
True      14
Name: HIST2H3C, dtype: int64

HIST2H3D
False    146
True      37
Name: HIST2H3D, dtype: int64

HIST2H4A
False    183
Name: HIST2H4A, dtype: int64

HIST3H2A
False    183
Name: HIST3H2A, dtype: int64

HIST3H2BB
False    168
True      15
Name: HIST3H2BB, dtype: int64

HIST3H3
True     118
False     65
Name: HIST3H3, dtype: int64

HIST4H4
False    183
Name: HIST4H4, dtype: int64

HIVEP1
False    183
Name: HIVEP1, dtype: int64

HIVEP2
False    183
Name: HIVEP2, dtype: int64

HIVEP3
False    183
Name: HIVEP3, dtype: int64

HJURP
False    183
Name: HJURP, dtype: int64

HK1
False    183
Name: HK1, dtype: int64

HK2
False    183
Name: HK2, dtype: int64

HK3
False    183
Name: HK3, dtype: int64

HKDC1
False    183
Name: HKDC1, dtype: int64

HKR1
False    183
Name: HKR1, dtype: int64

HLA-A
False    183
Name: HLA-A, dtype: int64

HLA-B
False    183
Name: HLA-B, dtype: int64

HLA-C
False    183
Name: HLA-C, dtype: int64

HLA-DMA
False    183
Name: HLA-DMA, dtype: int64

HLA-DMB
False    183
Name: HLA-DMB, dtype: int64

HLA-DOA
False    183
Name: HLA-DOA, dtype: int64

HLA-DOB
False    183
Name: HLA-DOB, dtype: int64

HLA-DPA1
False    183
Name: HLA-DPA1, dtype: int64

HLA-DPB1
False    183
Name: HLA-DPB1, dtype: int64

HLA-DPB2
False    177
True       6
Name: HLA-DPB2, dtype: int64

HLA-DQA1
False    183
Name: HLA-DQA1, dtype: int64

HLA-DQA2
False    183
Name: HLA-DQA2, dtype: int64

HLA-DQB1
False    183
Name: HLA-DQB1, dtype: int64

HLA-DQB2
False    183
Name: HLA-DQB2, dtype: int64

HLA-DRA
False    183
Name: HLA-DRA, dtype: int64

HLA-DRB1
False    183
Name: HLA-DRB1, dtype: int64

HLA-DRB5
False    183
Name: HLA-DRB5, dtype: int64

HLA-DRB6
False    181
True       2
Name: HLA-DRB6, dtype: int64

HLA-E
False    183
Name: HLA-E, dtype: int64

HLA-F
False    183
Name: HLA-F, dtype: int64

HLA-G
False    183
Name: HLA-G, dtype: int64

HLA-H
False    183
Name: HLA-H, dtype: int64

HLA-J
False    183
Name: HLA-J, dtype: int64

HLA-L
False    183
Name: HLA-L, dtype: int64

HLCS
False    183
Name: HLCS, dtype: int64

HLF
False    183
Name: HLF, dtype: int64

HLTF
False    183
Name: HLTF, dtype: int64

HLX
False    183
Name: HLX, dtype: int64

HM13
False    183
Name: HM13, dtype: int64

HMBOX1
False    183
Name: HMBOX1, dtype: int64

HMBS
False    183
Name: HMBS, dtype: int64

HMCN1
False    183
Name: HMCN1, dtype: int64

HMG20A
False    183
Name: HMG20A, dtype: int64

HMG20B
False    183
Name: HMG20B, dtype: int64

HMGA1
False    183
Name: HMGA1, dtype: int64

HMGA2
False    183
Name: HMGA2, dtype: int64

HMGB1
False    183
Name: HMGB1, dtype: int64

HMGB2
False    183
Name: HMGB2, dtype: int64

HMGB3
False    183
Name: HMGB3, dtype: int64

HMGCLL1
False    180
True       3
Name: HMGCLL1, dtype: int64

HMGCL
False    183
Name: HMGCL, dtype: int64

HMGCR
False    183
Name: HMGCR, dtype: int64

HMGCS1
False    183
Name: HMGCS1, dtype: int64

HMGCS2
False    180
True       3
Name: HMGCS2, dtype: int64

HMGN1
False    183
Name: HMGN1, dtype: int64

HMGN2
False    183
Name: HMGN2, dtype: int64

HMGN3
False    183
Name: HMGN3, dtype: int64

HMGN4
False    183
Name: HMGN4, dtype: int64

HMGN5
False    183
Name: HMGN5, dtype: int64

HMGXB3
False    183
Name: HMGXB3, dtype: int64

HMGXB4
False    183
Name: HMGXB4, dtype: int64

HMHA1
False    183
Name: HMHA1, dtype: int64

HMHB1
True     120
False     63
Name: HMHB1, dtype: int64

HMMR
False    183
Name: HMMR, dtype: int64

HMOX1
False    183
Name: HMOX1, dtype: int64

HMOX2
False    183
Name: HMOX2, dtype: int64

HMP19
False    180
True       3
Name: HMP19, dtype: int64

HMSD
False    166
True      17
Name: HMSD, dtype: int64

HMX1
True     115
False     68
Name: HMX1, dtype: int64

HMX2
False    130
True      53
Name: HMX2, dtype: int64

HMX3
False    131
True      52
Name: HMX3, dtype: int64

HN1L
False    183
Name: HN1L, dtype: int64

HN1
False    183
Name: HN1, dtype: int64

HNF1A

False    183
Name: HNF1A, dtype: int64

HNF1B
False    182
True       1
Name: HNF1B, dtype: int64

HNF4A
False    183
Name: HNF4A, dtype: int64

HNF4G
False    183
Name: HNF4G, dtype: int64

HNMT
False    183
Name: HNMT, dtype: int64

HNRNPA0
False    183
Name: HNRNPA0, dtype: int64

HNRNPA1L2
False    183
Name: HNRNPA1L2, dtype: int64

HNRNPA1
False    183
Name: HNRNPA1, dtype: int64

HNRNPA2B1
False    183
Name: HNRNPA2B1, dtype: int64

HNRNPA3P1
False    183
Name: HNRNPA3P1, dtype: int64

HNRNPA3
False    183
Name: HNRNPA3, dtype: int64

HNRNPAB
False    183
Name: HNRNPAB, dtype: int64

HNRNPC
False    183
Name: HNRNPC, dtype: int64

HNRNPD
False    183
Name: HNRNPD, dtype: int64

HNRNPF
False    183
Name: HNRNPF, dtype: int64

HNRNPH1
False    183
Name: HNRNPH1, dtype: int64

HNRNPH2
False    183
Name: HNRNPH2, dtype: int64

HNRNPH3
False    183
Name: HNRNPH3, dtype: int64

HNRNPK
False    183
Name: HNRNPK, dtype: int64

HNRNPL
False    183
Name: HNRNPL, dtype: int64

HNRNPM
False    183
Name: HNRNPM, dtype: int64

HNRNPR
False    183
Name: HNRNPR, dtype: int64

HNRNPUL1
False    183
Name: HNRNPUL1, dtype: int64

HNRNPUL2
False    183
Name: HNRNPUL2, dtype: int64

HNRNPU
False    183
Name: HNRNPU, dtype: int64

HNRPDL
False    183
Name: HNRPDL, dtype: int64

HNRPLL
False    183
Name: HNRPLL, dtype: int64

HOMER1
False    183
Name: HOMER1, dtype: int64

HOMER2
False    183
Name: HOMER2, dtype: int64

HOMER3
False    183
Name: HOMER3, dtype: int64

HOMEZ
False    183
Name: HOMEZ, dtype: int64

HOOK1
False    183
Name: HOOK1, dtype: int64

HOOK2
False    183
Name: HOOK2, dtype: int64

HOOK3
False    183
Name: HOOK3, dtype: int64

HOPX
False    183
Name: HOPX, dtype: int64

HORMAD1
False    147
True      36
Name: HORMAD1, dtype: int64

HOTAIR
False    135
True      48
Name: HOTAIR, dtype: int64

HOXA10
False    182
True       1
Name: HOXA10, dtype: int64

HOXA11AS
False    159
True      24
Name: HOXA11AS, dtype: int64

HOXA11
False    167
True      16
Name: HOXA11, dtype: int64

HOXA13
False    158
True      25
Name: HOXA13, dtype: int64

HOXA1
False    182
True       1
Name: HOXA1, dtype: int64

HOXA2
False    183
Name: HOXA2, dtype: int64

HOXA3
False    183
Name: HOXA3, dtype: int64

HOXA4
False    183
Name: HOXA4, dtype: int64

HOXA5
False    183
Name: HOXA5, dtype: int64

HOXA6
False    165
True      18
Name: HOXA6, dtype: int64

HOXA7
False    181
True       2
Name: HOXA7, dtype: int64

HOXA9
False    182
True       1
Name: HOXA9, dtype: int64

HOXB13
False    145
True      38
Name: HOXB13, dtype: int64

HOXB2
False    183
Name: HOXB2, dtype: int64

HOXB3
False    183
Name: HOXB3, dtype: int64

HOXB4
False    183
Name: HOXB4, dtype: int64

HOXB5
False    183
Name: HOXB5, dtype: int64

HOXB6
False    183
Name: HOXB6, dtype: int64

HOXB7
False    183
Name: HOXB7, dtype: int64

HOXB8
False    182
True       1
Name: HOXB8, dtype: int64

HOXB9
False    181
True       2
Name: HOXB9, dtype: int64

HOXC10
False    170
True      13
Name: HOXC10, dtype: int64

HOXC11
False    147
True      36
Name: HOXC11, dtype: int64

HOXC13
False    95
True     88
Name: HOXC13, dtype: int64

HOXC4
False    183
Name: HOXC4, dtype: int64

HOXC5
False    180
True       3
Name: HOXC5, dtype: int64

HOXC6
False    183
Name: HOXC6, dtype: int64

HOXC8
False    181
True       2
Name: HOXC8, dtype: int64

HOXC9
False    180
True       3
Name: HOXC9, dtype: int64

HOXD10
False    149
True      34
Name: HOXD10, dtype: int64

HOXD11
True     112
False     71
Name: HOXD11, dtype: int64

HOXD1
False    182
True       1
Name: HOXD1, dtype: int64

HOXD3
False    182
True       1
Name: HOXD3, dtype: int64

HOXD4
False    180
True       3
Name: HOXD4, dtype: int64

HOXD8
False    183
Name: HOXD8, dtype: int64

HOXD9
False    183
Name: HOXD9, dtype: int64

HP1BP3
False    183
Name: HP1BP3, dtype: int64

HPCAL1
False    183
Name: HPCAL1, dtype: int64

HPCAL4
False    178
True       5
Name: HPCAL4, dtype: int64

HPCA
False    183
Name: HPCA, dtype: int64

HPDL
False    183
Name: HPDL, dtype: int64

HPD
False    175
True       8
Name: HPD, dtype: int64

HPGDS
False    182
True       1
Name: HPGDS, dtype: int64

HPGD
False    183
Name: HPGD, dtype: int64

HPN
False    182
True       1
Name: HPN, dtype: int64

HPRT1
False    183
Name: HPRT1, dtype: int64

HPR
False    162
True      21
Name: HPR, dtype: int64

HPS1
False    183
Name: HPS1, dtype: int64

HPS3
False    183
Name: HPS3, dtype: int64

HPS4
False    183
Name: HPS4, dtype: int64

HPS5
False    183
Name: HPS5, dtype: int64

HPS6
False    183
Name: HPS6, dtype: int64

HPSE2
False    120
True      63
Name: HPSE2, dtype: int64

HPSE
False    183
Name: HPSE, dtype: int64

HPX
False    183
Name: HPX, dtype: int64

HPYR1
True     128
False     55
Name: HPYR1, dtype: int64

HP
False    182
True       1
Name: HP, dtype: int64

HRASLS2
False    177
True       6
Name: HRASLS2, dtype: int64

HRASLS5
False    182
True       1
Name: HRASLS5, dtype: int64

HRASLS
False    179
True       4
Name: HRASLS, dtype: int64

HRAS
False    183
Name: HRAS, dtype: int64

HRCT1
False    183
Name: HRCT1, dtype: int64

HRC
False    183
Name: HRC, dtype: int64

HRG
True     98
False    85
Name: HRG, dtype: int64

HRH1
False    183
Name: HRH1, dtype: int64

HRH2
False    183
Name: HRH2, dtype: int64

HRH3
False    98
True     85
Name: HRH3, dtype: int64

HRH4
False    163
True      20
Name: HRH4, dtype: int64

HRK
False    119
True      64
Name: HRK, dtype: int64

HRNBP3
False    173
True      10
Name: HRNBP3, dtype: int64

HRNR
False    183
Name: HRNR, dtype: int64

HRSP12
False    183
Name: HRSP12, dtype: int64

HR
False    183
Name: HR, dtype: int64

HS1BP3
False    183
Name: HS1BP3, dtype: int64

HS2ST1
False    183
Name: HS2ST1, dtype: int64

HS3ST1
False    183
Name: HS3ST1, dtype: int64

HS3ST2
False    183
Name: HS3ST2, dtype: int64

HS3ST3A1
False    183
Name: HS3ST3A1, dtype: int64

HS3ST3B1
False    182
True       1
Name: HS3ST3B1, dtype: int64

HS3ST4
False    126
True      57
Name: HS3ST4, dtype: int64

HS3ST5
False    172
True      11
Name: HS3ST5, dtype: int64

HS3ST6
True     114
False     69
Name: HS3ST6, dtype: int64

HS6ST1
False    183
Name: HS6ST1, dtype: int64

HS6ST2
False    183
Name: HS6ST2, dtype: int64

HS6ST3
False    179
True       4
Name: HS6ST3, dtype: int64

HSBP1L1
False    183
Name: HSBP1L1, dtype: int64

HSBP1
False    183
Name: HSBP1, dtype: int64

HSCB
False    183
Name: HSCB, dtype: int64

HSD11B1L
False    183
Name: HSD11B1L, dtype: int64

HSD11B1
False    183
Name: HSD11B1, dtype: int64

HSD11B2
False    183
Name: HSD11B2, dtype: int64

HSD17B10
False    183
Name: HSD17B10, dtype: int64

HSD17B11
False    183
Name: HSD17B11, dtype: int64

HSD17B12
False    183
Name: HSD17B12, dtype: int64

HSD17B13
False    183
Name: HSD17B13, dtype: int64

HSD17B14
False    183
Name: HSD17B14, dtype: int64

HSD17B1
False    183
Name: HSD17B1, dtype: int64

HSD17B2
False    183
Name: HSD17B2, dtype: int64

HSD17B3
False    177
True       6
Name: HSD17B3, dtype: int64

HSD17B4
False    183
Name: HSD17B4, dtype: int64

HSD17B6
False    183
Name: HSD17B6, dtype: int64

HSD17B7P2
False    183
Name: HSD17B7P2, dtype: int64

HSD17B7
False    183
Name: HSD17B7, dtype: int64

HSD17B8
False    183
Name: HSD17B8, dtype: int64

HSD3B2
False    143
True      40
Name: HSD3B2, dtype: int64

HSD3B7
False    183
Name: HSD3B7, dtype: int64

HSDL1
False    183
Name: HSDL1, dtype: int64

HSDL2
False    183
Name: HSDL2, dtype: int64

HSF1
False    183
Name: HSF1, dtype: int64

HSF2BP
False    183
Name: HSF2BP, dtype: int64

HSF2
False    183
Name: HSF2, dtype: int64

HSF4
False    183
Name: HSF4, dtype: int64

HSF5
False    149
True      34
Name: HSF5, dtype: int64

HSFX2
False    183
Name: HSFX2, dtype: int64

HSH2D
False    183
Name: HSH2D, dtype: int64

HSN2
False    182
True       1
Name: HSN2, dtype: int64

HSP90AA1
False    183
Name: HSP90AA1, dtype: int64

HSP90AB1
False    183
Name: HSP90AB1, dtype: int64

HSP90AB2P
False    183
Name: HSP90AB2P, dtype: int64

HSP90AB4P
False    138
True      45
Name: HSP90AB4P, dtype: int64

HSP90B1
False    183
Name: HSP90B1, dtype: int64

HSP90B3P
False    182
True       1
Name: HSP90B3P, dtype: int64

HSPA12A
False    183
Name: HSPA12A, dtype: int64

HSPA12B
False    183
Name: HSPA12B, dtype: int64

HSPA13
False    183
Name: HSPA13, dtype: int64

HSPA14
False    183
Name: HSPA14, dtype: int64

HSPA1A
False    183
Name: HSPA1A, dtype: int64

HSPA1B
False    183
Name: HSPA1B, dtype: int64

HSPA1L
False    183
Name: HSPA1L, dtype: int64

HSPA2
False    183
Name: HSPA2, dtype: int64

HSPA4L
False    183
Name: HSPA4L, dtype: int64

HSPA4
False    183
Name: HSPA4, dtype: int64

HSPA5
False    183
Name: HSPA5, dtype: int64

HSPA6
False    183
Name: HSPA6, dtype: int64

HSPA7
False    183
Name: HSPA7, dtype: int64

HSPA8
False    183
Name: HSPA8, dtype: int64

HSPA9
False    183
Name: HSPA9, dtype: int64

HSPB11
False    183
Name: HSPB11, dtype: int64

HSPB1
False    183
Name: HSPB1, dtype: int64

HSPB2
False    183
Name: HSPB2, dtype: int64

HSPB3

False    112
True      71
Name: HSPB3, dtype: int64

HSPB6
False    183
Name: HSPB6, dtype: int64

HSPB7
False    183
Name: HSPB7, dtype: int64

HSPB8
False    183
Name: HSPB8, dtype: int64

HSPB9
False    183
Name: HSPB9, dtype: int64

HSPBAP1
False    183
Name: HSPBAP1, dtype: int64

HSPBP1
False    183
Name: HSPBP1, dtype: int64

HSPC072
False    143
True      40
Name: HSPC072, dtype: int64

HSPC157
False    183
Name: HSPC157, dtype: int64

HSPC159
False    183
Name: HSPC159, dtype: int64

HSPD1
False    183
Name: HSPD1, dtype: int64

HSPE1
False    183
Name: HSPE1, dtype: int64

HSPG2
False    183
Name: HSPG2, dtype: int64

HSPH1
False    183
Name: HSPH1, dtype: int64

HTATIP2
False    183
Name: HTATIP2, dtype: int64

HTATSF1
False    183
Name: HTATSF1, dtype: int64

HTR1A
True     122
False     61
Name: HTR1A, dtype: int64

HTR1B
False    175
True       8
Name: HTR1B, dtype: int64

HTR1D
False    183
Name: HTR1D, dtype: int64

HTR1F
False    178
True       5
Name: HTR1F, dtype: int64

HTR2A
False    173
True      10
Name: HTR2A, dtype: int64

HTR2B
False    181
True       2
Name: HTR2B, dtype: int64

HTR3A
False    180
True       3
Name: HTR3A, dtype: int64

HTR3C
False    142
True      41
Name: HTR3C, dtype: int64

HTR3E
False    151
True      32
Name: HTR3E, dtype: int64

HTR4
True     93
False    90
Name: HTR4, dtype: int64

HTR6
False    110
True      73
Name: HTR6, dtype: int64

HTR7P1
False    183
Name: HTR7P1, dtype: int64

HTR7
False    180
True       3
Name: HTR7, dtype: int64

HTRA1
False    183
Name: HTRA1, dtype: int64

HTRA2
False    183
Name: HTRA2, dtype: int64

HTRA3
False    183
Name: HTRA3, dtype: int64

HTRA4
False    180
True       3
Name: HTRA4, dtype: int64

HTT
False    183
Name: HTT, dtype: int64

HULC
True     97
False    86
Name: HULC, dtype: int64

HUNK
False    183
Name: HUNK, dtype: int64

HUS1B
False    162
True      21
Name: HUS1B, dtype: int64

HUS1
False    183
Name: HUS1, dtype: int64

HUWE1
False    183
Name: HUWE1, dtype: int64

HVCN1
False    183
Name: HVCN1, dtype: int64

HYAL1
False    183
Name: HYAL1, dtype: int64

HYAL2
False    183
Name: HYAL2, dtype: int64

HYAL3
False    183
Name: HYAL3, dtype: int64

HYAL4
False    149
True      34
Name: HYAL4, dtype: int64

HYDIN
False    182
True       1
Name: HYDIN, dtype: int64

HYI
False    183
Name: HYI, dtype: int64

HYLS1
False    183
Name: HYLS1, dtype: int64

HYMAI
False    177
True       6
Name: HYMAI, dtype: int64

HYOU1
False    183
Name: HYOU1, dtype: int64

IAH1
False    183
Name: IAH1, dtype: int64

IAPP
False    168
True      15
Name: IAPP, dtype: int64

IARS2
False    183
Name: IARS2, dtype: int64

IARS
False    183
Name: IARS, dtype: int64

IBSP
False    176
True       7
Name: IBSP, dtype: int64

IBTK
False    183
Name: IBTK, dtype: int64

ICA1L
False    183
Name: ICA1L, dtype: int64

ICA1
False    183
Name: ICA1, dtype: int64

ICAM1
False    183
Name: ICAM1, dtype: int64

ICAM2
False    183
Name: ICAM2, dtype: int64

ICAM3
False    183
Name: ICAM3, dtype: int64

ICAM4
False    183
Name: ICAM4, dtype: int64

ICAM5
False    179
True       4
Name: ICAM5, dtype: int64

ICK
False    183
Name: ICK, dtype: int64

ICMT
False    183
Name: ICMT, dtype: int64

ICOSLG
False    183
Name: ICOSLG, dtype: int64

ICOS
False    179
True       4
Name: ICOS, dtype: int64

ICT1
False    183
Name: ICT1, dtype: int64

ID1
False    183
Name: ID1, dtype: int64

ID2B
False    177
True       6
Name: ID2B, dtype: int64

ID2
False    183
Name: ID2, dtype: int64

ID3
False    183
Name: ID3, dtype: int64

ID4
False    183
Name: ID4, dtype: int64

IDE
False    183
Name: IDE, dtype: int64

IDH1
False    183
Name: IDH1, dtype: int64

IDH2
False    183
Name: IDH2, dtype: int64

IDH3A
False    183
Name: IDH3A, dtype: int64

IDH3B
False    183
Name: IDH3B, dtype: int64

IDH3G
False    183
Name: IDH3G, dtype: int64

IDI1
False    183
Name: IDI1, dtype: int64

IDI2
False    183
Name: IDI2, dtype: int64

IDO1
False    183
Name: IDO1, dtype: int64

IDO2
False    166
True      17
Name: IDO2, dtype: int64

IDS
False    183
Name: IDS, dtype: int64

IDUA
False    183
Name: IDUA, dtype: int64

IER2
False    183
Name: IER2, dtype: int64

IER3IP1
False    183
Name: IER3IP1, dtype: int64

IER3
False    183
Name: IER3, dtype: int64

IER5L
False    183
Name: IER5L, dtype: int64

IER5
False    183
Name: IER5, dtype: int64

IFFO1
False    183
Name: IFFO1, dtype: int64

IFFO2
False    183
Name: IFFO2, dtype: int64

IFI16
False    183
Name: IFI16, dtype: int64

IFI27L1
False    183
Name: IFI27L1, dtype: int64

IFI27L2
False    183
Name: IFI27L2, dtype: int64

IFI27
False    183
Name: IFI27, dtype: int64

IFI30
False    183
Name: IFI30, dtype: int64

IFI35
False    183
Name: IFI35, dtype: int64

IFI44L
False    183
Name: IFI44L, dtype: int64

IFI44
False    183
Name: IFI44, dtype: int64

IFI6
False    183
Name: IFI6, dtype: int64

IFIH1
False    183
Name: IFIH1, dtype: int64

IFIT1B
True     114
False     69
Name: IFIT1B, dtype: int64

IFIT1
False    183
Name: IFIT1, dtype: int64

IFIT2
False    183
Name: IFIT2, dtype: int64

IFIT3
False    183
Name: IFIT3, dtype: int64

IFIT5
False    183
Name: IFIT5, dtype: int64

IFITM1
False    183
Name: IFITM1, dtype: int64

IFITM2
False    183
Name: IFITM2, dtype: int64

IFITM3
False    183
Name: IFITM3, dtype: int64

IFITM4P
False    112
True      71
Name: IFITM4P, dtype: int64

IFITM5
False    95
True     88
Name: IFITM5, dtype: int64

IFLTD1
True     109
False     74
Name: IFLTD1, dtype: int64

IFNA13
True     102
False     81
Name: IFNA13, dtype: int64

IFNA1
True     114
False     69
Name: IFNA1, dtype: int64

IFNAR1
False    183
Name: IFNAR1, dtype: int64

IFNAR2
False    183
Name: IFNAR2, dtype: int64

IFNE
False    169
True      14
Name: IFNE, dtype: int64

IFNGR1
False    183
Name: IFNGR1, dtype: int64

IFNGR2
False    183
Name: IFNGR2, dtype: int64

IFNG
False    148
True      35
Name: IFNG, dtype: int64

IFRD1
False    183
Name: IFRD1, dtype: int64

IFRD2
False    183
Name: IFRD2, dtype: int64

IFT122
False    183
Name: IFT122, dtype: int64

IFT140
False    183
Name: IFT140, dtype: int64

IFT172
False    183
Name: IFT172, dtype: int64

IFT20
False    183
Name: IFT20, dtype: int64

IFT27
False    183
Name: IFT27, dtype: int64

IFT46
False    183
Name: IFT46, dtype: int64

IFT52
False    183
Name: IFT52, dtype: int64

IFT57
False    183
Name: IFT57, dtype: int64

IFT74
False    183
Name: IFT74, dtype: int64

IFT80
False    183
Name: IFT80, dtype: int64

IFT81
False    183
Name: IFT81, dtype: int64

IFT88
False    183
Name: IFT88, dtype: int64

IGBP1
False    183
Name: IGBP1, dtype: int64

IGDCC3
False    161
True      22
Name: IGDCC3, dtype: int64

IGDCC4
False    183
Name: IGDCC4, dtype: int64

IGF1R
False    183
Name: IGF1R, dtype: int64

IGF1
False    183
Name: IGF1, dtype: int64

IGF2AS
False    179
True       4
Name: IGF2AS, dtype: int64

IGF2BP1
False    176
True       7
Name: IGF2BP1, dtype: int64

IGF2BP2
False    183
Name: IGF2BP2, dtype: int64

IGF2BP3
False    183
Name: IGF2BP3, dtype: int64

IGF2R
False    183
Name: IGF2R, dtype: int64

IGF2
False    183
Name: IGF2, dtype: int64

IGFALS
False    181
True       2
Name: IGFALS, dtype: int64

IGFBP1
False    182
True       1
Name: IGFBP1, dtype: int64

IGFBP2
False    183
Name: IGFBP2, dtype: int64

IGFBP3
False    183
Name: IGFBP3, dtype: int64

IGFBP4
False    183
Name: IGFBP4, dtype: int64

IGFBP5
False    183
Name: IGFBP5, dtype: int64

IGFBP6
False    183
Name: IGFBP6, dtype: int64

IGFBP7
False    183
Name: IGFBP7, dtype: int64

IGFBPL1
False    165
True      18
Name: IGFBPL1, dtype: int64

IGFL1
False    143
True      40
Name: IGFL1, dtype: int64

IGFL2
False    180
True       3
Name: IGFL2, dtype: int64

IGFL3
False    133
True      50
Name: IGFL3, dtype: int64

IGFL4
False    98
True     85
Name: IGFL4, dtype: int64

IGFN1
False    176
True       7
Name: IGFN1, dtype: int64

IGHMBP2
False    183
Name: IGHMBP2, dtype: int64

IGJ
False    183
Name: IGJ, dtype: int64

IGLL1
True     119
False     64
Name: IGLL1, dtype: int64

IGLL3
False    137
True      46
Name: IGLL3, dtype: int64

IGLON5
False    182
True       1
Name: IGLON5, dtype: int64

IGSF10
False    183
Name: IGSF10, dtype: int64

IGSF11
False    183
Name: IGSF11, dtype: int64

IGSF1
False    183
Name: IGSF1, dtype: int64

IGSF21
False    183
Name: IGSF21, dtype: int64

IGSF22
False    183
Name: IGSF22, dtype: int64

IGSF3
False    183
Name: IGSF3, dtype: int64

IGSF5
False    182
True       1
Name: IGSF5, dtype: int64

IGSF6
False    183
Name: IGSF6, dtype: int64

IGSF8
False    183
Name: IGSF8, dtype: int64

IGSF9B
False    182
True       1
Name: IGSF9B, dtype: int64

IGSF9
False    182
True       1
Name: IGSF9, dtype: int64

IHH
False    183
Name: IHH, dtype: int64

IKBIP
False    183
Name: IKBIP, dtype: int64

IKBKAP
False    183
Name: IKBKAP, dtype: int64

IKBKB
False    183
Name: IKBKB, dtype: int64

IKBKE
False    183
Name: IKBKE, dtype: int64

IKBKG
False    183
Name: IKBKG, dtype: int64

IKZF1
False    183
Name: IKZF1, dtype: int64

IKZF2
False    183
Name: IKZF2, dtype: int64

IKZF3
False    180
True       3
Name: IKZF3, dtype: int64

IKZF4
False    183
Name: IKZF4, dtype: int64

IKZF5

False    183
Name: IKZF5, dtype: int64

IK
False    183
Name: IK, dtype: int64

IL10RA
False    183
Name: IL10RA, dtype: int64

IL10RB
False    183
Name: IL10RB, dtype: int64

IL10
False    182
True       1
Name: IL10, dtype: int64

IL11RA
False    183
Name: IL11RA, dtype: int64

IL11
False    183
Name: IL11, dtype: int64

IL12A
False    182
True       1
Name: IL12A, dtype: int64

IL12B
False    158
True      25
Name: IL12B, dtype: int64

IL12RB1
False    183
Name: IL12RB1, dtype: int64

IL12RB2
False    182
True       1
Name: IL12RB2, dtype: int64

IL13RA1
False    183
Name: IL13RA1, dtype: int64

IL13RA2
False    179
True       4
Name: IL13RA2, dtype: int64

IL13
False    105
True      78
Name: IL13, dtype: int64

IL15RA
False    183
Name: IL15RA, dtype: int64

IL15
False    183
Name: IL15, dtype: int64

IL16
False    183
Name: IL16, dtype: int64

IL17B
False    171
True      12
Name: IL17B, dtype: int64

IL17C
False    151
True      32
Name: IL17C, dtype: int64

IL17D
False    182
True       1
Name: IL17D, dtype: int64

IL17RA
False    183
Name: IL17RA, dtype: int64

IL17RB
False    183
Name: IL17RB, dtype: int64

IL17RC
False    183
Name: IL17RC, dtype: int64

IL17RD
False    183
Name: IL17RD, dtype: int64

IL17REL
False    171
True      12
Name: IL17REL, dtype: int64

IL17RE
False    183
Name: IL17RE, dtype: int64

IL18BP
False    183
Name: IL18BP, dtype: int64

IL18R1
False    183
Name: IL18R1, dtype: int64

IL18RAP
False    183
Name: IL18RAP, dtype: int64

IL18
False    183
Name: IL18, dtype: int64

IL19
False    148
True      35
Name: IL19, dtype: int64

IL1A
False    176
True       7
Name: IL1A, dtype: int64

IL1B
False    183
Name: IL1B, dtype: int64

IL1F5
False    108
True      75
Name: IL1F5, dtype: int64

IL1F7
False    140
True      43
Name: IL1F7, dtype: int64

IL1F8
True     108
False     75
Name: IL1F8, dtype: int64

IL1F9
False    123
True      60
Name: IL1F9, dtype: int64

IL1R1
False    183
Name: IL1R1, dtype: int64

IL1R2
False    183
Name: IL1R2, dtype: int64

IL1RAPL1
False    109
True      74
Name: IL1RAPL1, dtype: int64

IL1RAPL2
False    161
True      22
Name: IL1RAPL2, dtype: int64

IL1RAP
False    183
Name: IL1RAP, dtype: int64

IL1RL1
False    183
Name: IL1RL1, dtype: int64

IL1RL2
False    181
True       2
Name: IL1RL2, dtype: int64

IL1RN
False    183
Name: IL1RN, dtype: int64

IL20RA
False    183
Name: IL20RA, dtype: int64

IL20RB
False    183
Name: IL20RB, dtype: int64

IL20
True     107
False     76
Name: IL20, dtype: int64

IL21R
False    182
True       1
Name: IL21R, dtype: int64

IL22RA1
False    183
Name: IL22RA1, dtype: int64

IL22RA2
False    167
True      16
Name: IL22RA2, dtype: int64

IL23A
False    183
Name: IL23A, dtype: int64

IL23R
False    157
True      26
Name: IL23R, dtype: int64

IL24
False    172
True      11
Name: IL24, dtype: int64

IL25
True     119
False     64
Name: IL25, dtype: int64

IL26
True     108
False     75
Name: IL26, dtype: int64

IL27RA
False    183
Name: IL27RA, dtype: int64

IL27
False    142
True      41
Name: IL27, dtype: int64

IL28RA
False    183
Name: IL28RA, dtype: int64

IL29
False    102
True      81
Name: IL29, dtype: int64

IL2RA
False    183
Name: IL2RA, dtype: int64

IL2RB
False    183
Name: IL2RB, dtype: int64

IL2RG
False    183
Name: IL2RG, dtype: int64

IL2
False    94
True     89
Name: IL2, dtype: int64

IL31RA
False    167
True      16
Name: IL31RA, dtype: int64

IL32
False    183
Name: IL32, dtype: int64

IL33
False    183
Name: IL33, dtype: int64

IL34
False    183
Name: IL34, dtype: int64

IL3RA
False    183
Name: IL3RA, dtype: int64

IL4I1
False    183
Name: IL4I1, dtype: int64

IL4R
False    183
Name: IL4R, dtype: int64

IL5RA
False    148
True      35
Name: IL5RA, dtype: int64

IL5
True     122
False     61
Name: IL5, dtype: int64

IL6R
False    183
Name: IL6R, dtype: int64

IL6ST
False    183
Name: IL6ST, dtype: int64

IL6
False    183
Name: IL6, dtype: int64

IL7R
False    182
True       1
Name: IL7R, dtype: int64

IL7
False    183
Name: IL7, dtype: int64

IL8
False    183
Name: IL8, dtype: int64

IL9R
False    179
True       4
Name: IL9R, dtype: int64

ILDR1
False    183
Name: ILDR1, dtype: int64

ILDR2
False    176
True       7
Name: ILDR2, dtype: int64

ILF2
False    183
Name: ILF2, dtype: int64

ILF3
False    183
Name: ILF3, dtype: int64

ILKAP
False    183
Name: ILKAP, dtype: int64

ILK
False    183
Name: ILK, dtype: int64

ILVBL
False    183
Name: ILVBL, dtype: int64

IMMP1L
False    183
Name: IMMP1L, dtype: int64

IMMP2L
False    183
Name: IMMP2L, dtype: int64

IMMT
False    183
Name: IMMT, dtype: int64

IMP3
False    183
Name: IMP3, dtype: int64

IMP4
False    183
Name: IMP4, dtype: int64

IMPA1
False    183
Name: IMPA1, dtype: int64

IMPA2
False    183
Name: IMPA2, dtype: int64

IMPACT
False    183
Name: IMPACT, dtype: int64

IMPAD1
False    183
Name: IMPAD1, dtype: int64

IMPDH1
False    183
Name: IMPDH1, dtype: int64

IMPDH2
False    183
Name: IMPDH2, dtype: int64

IMPG1
False    179
True       4
Name: IMPG1, dtype: int64

IMPG2
False    172
True      11
Name: IMPG2, dtype: int64

INADL
False    183
Name: INADL, dtype: int64

INA
False    183
Name: INA, dtype: int64

INCA1
False    183
Name: INCA1, dtype: int64

INCENP
False    183
Name: INCENP, dtype: int64

INE1
False    183
Name: INE1, dtype: int64

INE2
False    137
True      46
Name: INE2, dtype: int64

INF2
False    183
Name: INF2, dtype: int64

ING1
False    183
Name: ING1, dtype: int64

ING2
False    183
Name: ING2, dtype: int64

ING3
False    183
Name: ING3, dtype: int64

ING4
False    183
Name: ING4, dtype: int64

ING5
False    183
Name: ING5, dtype: int64

INGX
False    102
True      81
Name: INGX, dtype: int64

INHA
False    183
Name: INHA, dtype: int64

INHBA
False    183
Name: INHBA, dtype: int64

INHBB
False    183
Name: INHBB, dtype: int64

INHBC
False    148
True      35
Name: INHBC, dtype: int64

INHBE
False    183
Name: INHBE, dtype: int64

INMT
False    183
Name: INMT, dtype: int64

INO80B
False    183
Name: INO80B, dtype: int64

INO80C
False    183
Name: INO80C, dtype: int64

INO80D
False    183
Name: INO80D, dtype: int64

INO80E
False    183
Name: INO80E, dtype: int64

INO80
False    183
Name: INO80, dtype: int64

INPP1
False    183
Name: INPP1, dtype: int64

INPP4A
False    183
Name: INPP4A, dtype: int64

INPP4B
False    183
Name: INPP4B, dtype: int64

INPP5A
False    183
Name: INPP5A, dtype: int64

INPP5B
False    183
Name: INPP5B, dtype: int64

INPP5D
False    183
Name: INPP5D, dtype: int64

INPP5E
False    183
Name: INPP5E, dtype: int64

INPP5F
False    183
Name: INPP5F, dtype: int64

INPP5J
False    183
Name: INPP5J, dtype: int64

INPP5K
False    183
Name: INPP5K, dtype: int64

INPPL1
False    183
Name: INPPL1, dtype: int64

INS-IGF2
False    153
True      30
Name: INS-IGF2, dtype: int64

INSC
False    183
Name: INSC, dtype: int64

INSIG1
False    183
Name: INSIG1, dtype: int64

INSIG2
False    183
Name: INSIG2, dtype: int64

INSL3
False    182
True       1
Name: INSL3, dtype: int64

INSL4
True     125
False     58
Name: INSL4, dtype: int64

INSL5
True     122
False     61
Name: INSL5, dtype: int64

INSM1
False    179
True       4
Name: INSM1, dtype: int64

INSM2
False    127
True      56
Name: INSM2, dtype: int64

INSRR
False    173
True      10
Name: INSRR, dtype: int64

INSR
False    183
Name: INSR, dtype: int64

INS
False    178
True       5
Name: INS, dtype: int64

INTS10
False    183
Name: INTS10, dtype: int64

INTS12
False    183
Name: INTS12, dtype: int64

INTS1
False    183
Name: INTS1, dtype: int64

INTS2
False    183
Name: INTS2, dtype: int64

INTS3
False    183
Name: INTS3, dtype: int64

INTS4L1
False    183
Name: INTS4L1, dtype: int64

INTS4L2
False    182
True       1
Name: INTS4L2, dtype: int64

INTS4
False    183
Name: INTS4, dtype: int64

INTS5
False    183
Name: INTS5, dtype: int64

INTS6
False    183
Name: INTS6, dtype: int64

INTS7
False    183
Name: INTS7, dtype: int64

INTS8
False    183
Name: INTS8, dtype: int64

INTS9
False    183
Name: INTS9, dtype: int64

INTU
False    183
Name: INTU, dtype: int64

INVS
False    183
Name: INVS, dtype: int64

IP6K1
False    183
Name: IP6K1, dtype: int64

IP6K2
False    183
Name: IP6K2, dtype: int64

IP6K3
False    169
True      14
Name: IP6K3, dtype: int64

IPCEF1
False    183
Name: IPCEF1, dtype: int64

IPMK
False    182
True       1
Name: IPMK, dtype: int64

IPO11
False    183
Name: IPO11, dtype: int64

IPO13
False    183
Name: IPO13, dtype: int64

IPO4
False    183
Name: IPO4, dtype: int64

IPO5
False    183
Name: IPO5, dtype: int64

IPO7
False    183
Name: IPO7, dtype: int64

IPO8
False    183
Name: IPO8, dtype: int64

IPO9
False    183
Name: IPO9, dtype: int64

IPPK
False    183
Name: IPPK, dtype: int64

IPP
False    183
Name: IPP, dtype: int64

IPW
False    183
Name: IPW, dtype: int64

IQCA1
False    183
Name: IQCA1, dtype: int64

IQCB1
False    183
Name: IQCB1, dtype: int64

IQCC
False    183
Name: IQCC, dtype: int64

IQCD

False    183
Name: IQCD, dtype: int64

IQCE
False    183
Name: IQCE, dtype: int64

IQCF1
False    112
True      71
Name: IQCF1, dtype: int64

IQCG
False    183
Name: IQCG, dtype: int64

IQCH
False    183
Name: IQCH, dtype: int64

IQCK
False    183
Name: IQCK, dtype: int64

IQGAP1
False    183
Name: IQGAP1, dtype: int64

IQGAP2
False    183
Name: IQGAP2, dtype: int64

IQGAP3
False    183
Name: IQGAP3, dtype: int64

IQSEC1
False    183
Name: IQSEC1, dtype: int64

IQSEC2
False    183
Name: IQSEC2, dtype: int64

IQSEC3
False    183
Name: IQSEC3, dtype: int64

IQUB
False    183
Name: IQUB, dtype: int64

IRAK1BP1
False    183
Name: IRAK1BP1, dtype: int64

IRAK1
False    183
Name: IRAK1, dtype: int64

IRAK2
False    183
Name: IRAK2, dtype: int64

IRAK3
False    183
Name: IRAK3, dtype: int64

IRAK4
False    183
Name: IRAK4, dtype: int64

IREB2
False    183
Name: IREB2, dtype: int64

IRF1
False    183
Name: IRF1, dtype: int64

IRF2BP1
False    183
Name: IRF2BP1, dtype: int64

IRF2BP2
False    183
Name: IRF2BP2, dtype: int64

IRF2
False    183
Name: IRF2, dtype: int64

IRF3
False    183
Name: IRF3, dtype: int64

IRF4
False    183
Name: IRF4, dtype: int64

IRF5
False    183
Name: IRF5, dtype: int64

IRF6
False    183
Name: IRF6, dtype: int64

IRF7
False    183
Name: IRF7, dtype: int64

IRF8
False    183
Name: IRF8, dtype: int64

IRF9
False    183
Name: IRF9, dtype: int64

IRGC
True     114
False     69
Name: IRGC, dtype: int64

IRGM
False    121
True      62
Name: IRGM, dtype: int64

IRGQ
False    183
Name: IRGQ, dtype: int64

IRS1
False    183
Name: IRS1, dtype: int64

IRS2
False    183
Name: IRS2, dtype: int64

IRS4
False    108
True      75
Name: IRS4, dtype: int64

IRX1
False    144
True      39
Name: IRX1, dtype: int64

IRX2
False    181
True       2
Name: IRX2, dtype: int64

IRX3
False    183
Name: IRX3, dtype: int64

IRX4
False    108
True      75
Name: IRX4, dtype: int64

IRX5
False    182
True       1
Name: IRX5, dtype: int64

IRX6
False    150
True      33
Name: IRX6, dtype: int64

ISCA1P1
False    183
Name: ISCA1P1, dtype: int64

ISCA1
False    183
Name: ISCA1, dtype: int64

ISCA2
False    183
Name: ISCA2, dtype: int64

ISCU
False    183
Name: ISCU, dtype: int64

ISG15
False    183
Name: ISG15, dtype: int64

ISG20L2
False    183
Name: ISG20L2, dtype: int64

ISG20
False    183
Name: ISG20, dtype: int64

ISL1
False    183
Name: ISL1, dtype: int64

ISL2
False    181
True       2
Name: ISL2, dtype: int64

ISLR2
False    183
Name: ISLR2, dtype: int64

ISLR
False    183
Name: ISLR, dtype: int64

ISM1
False    183
Name: ISM1, dtype: int64

ISM2
False    141
True      42
Name: ISM2, dtype: int64

ISOC1
False    183
Name: ISOC1, dtype: int64

ISOC2
False    183
Name: ISOC2, dtype: int64

ISPD
False    183
Name: ISPD, dtype: int64

ISX
False    127
True      56
Name: ISX, dtype: int64

ISY1
False    183
Name: ISY1, dtype: int64

ISYNA1
False    183
Name: ISYNA1, dtype: int64

ITCH
False    183
Name: ITCH, dtype: int64

ITFG1
False    183
Name: ITFG1, dtype: int64

ITFG2
False    183
Name: ITFG2, dtype: int64

ITFG3
False    183
Name: ITFG3, dtype: int64

ITGA10
False    183
Name: ITGA10, dtype: int64

ITGA11
False    183
Name: ITGA11, dtype: int64

ITGA1
False    183
Name: ITGA1, dtype: int64

ITGA2B
False    182
True       1
Name: ITGA2B, dtype: int64

ITGA2
False    183
Name: ITGA2, dtype: int64

ITGA3
False    183
Name: ITGA3, dtype: int64

ITGA4
False    183
Name: ITGA4, dtype: int64

ITGA5
False    183
Name: ITGA5, dtype: int64

ITGA6
False    183
Name: ITGA6, dtype: int64

ITGA7
False    183
Name: ITGA7, dtype: int64

ITGA8
False    180
True       3
Name: ITGA8, dtype: int64

ITGA9
False    183
Name: ITGA9, dtype: int64

ITGAD
False    165
True      18
Name: ITGAD, dtype: int64

ITGAE
False    183
Name: ITGAE, dtype: int64

ITGAL
False    183
Name: ITGAL, dtype: int64

ITGAM
False    183
Name: ITGAM, dtype: int64

ITGAV
False    183
Name: ITGAV, dtype: int64

ITGAX
False    183
Name: ITGAX, dtype: int64

ITGB1BP1
False    183
Name: ITGB1BP1, dtype: int64

ITGB1BP2
False    181
True       2
Name: ITGB1BP2, dtype: int64

ITGB1
False    183
Name: ITGB1, dtype: int64

ITGB2
False    183
Name: ITGB2, dtype: int64

ITGB3BP
False    183
Name: ITGB3BP, dtype: int64

ITGB3
False    183
Name: ITGB3, dtype: int64

ITGB4
False    183
Name: ITGB4, dtype: int64

ITGB5
False    183
Name: ITGB5, dtype: int64

ITGB6
False    180
True       3
Name: ITGB6, dtype: int64

ITGB7
False    183
Name: ITGB7, dtype: int64

ITGB8
False    183
Name: ITGB8, dtype: int64

ITGBL1
False    183
Name: ITGBL1, dtype: int64

ITIH1
False    169
True      14
Name: ITIH1, dtype: int64

ITIH2
False    178
True       5
Name: ITIH2, dtype: int64

ITIH3
False    183
Name: ITIH3, dtype: int64

ITIH4
False    183
Name: ITIH4, dtype: int64

ITIH5L
False    106
True      77
Name: ITIH5L, dtype: int64

ITIH5
False    183
Name: ITIH5, dtype: int64

ITK
False    182
True       1
Name: ITK, dtype: int64

ITLN1
False    165
True      18
Name: ITLN1, dtype: int64

ITLN2
True     98
False    85
Name: ITLN2, dtype: int64

ITM2A
False    183
Name: ITM2A, dtype: int64

ITM2B
False    183
Name: ITM2B, dtype: int64

ITM2C
False    183
Name: ITM2C, dtype: int64

ITPA
False    183
Name: ITPA, dtype: int64

ITPK1
False    183
Name: ITPK1, dtype: int64

ITPKA
False    182
True       1
Name: ITPKA, dtype: int64

ITPKB
False    183
Name: ITPKB, dtype: int64

ITPKC
False    183
Name: ITPKC, dtype: int64

ITPR1
False    183
Name: ITPR1, dtype: int64

ITPR2
False    183
Name: ITPR2, dtype: int64

ITPR3
False    183
Name: ITPR3, dtype: int64

ITPRIPL1
False    182
True       1
Name: ITPRIPL1, dtype: int64

ITPRIPL2
False    183
Name: ITPRIPL2, dtype: int64

ITPRIP
False    183
Name: ITPRIP, dtype: int64

ITSN1
False    183
Name: ITSN1, dtype: int64

ITSN2
False    183
Name: ITSN2, dtype: int64

IVD
False    183
Name: IVD, dtype: int64

IVL
False    132
True      51
Name: IVL, dtype: int64

IVNS1ABP
False    183
Name: IVNS1ABP, dtype: int64

IWS1
False    183
Name: IWS1, dtype: int64

IYD
False    180
True       3
Name: IYD, dtype: int64

IZUMO1
False    119
True      64
Name: IZUMO1, dtype: int64

JAG1
False    183
Name: JAG1, dtype: int64

JAG2
False    183
Name: JAG2, dtype: int64

JAGN1
False    183
Name: JAGN1, dtype: int64

JAK1
False    183
Name: JAK1, dtype: int64

JAK2
False    183
Name: JAK2, dtype: int64

JAK3
False    183
Name: JAK3, dtype: int64

JAKMIP1
False    179
True       4
Name: JAKMIP1, dtype: int64

JAKMIP2
False    183
Name: JAKMIP2, dtype: int64

JAKMIP3
False    183
Name: JAKMIP3, dtype: int64

JAM2
False    183
Name: JAM2, dtype: int64

JAM3
False    183
Name: JAM3, dtype: int64

JARID2
False    183
Name: JARID2, dtype: int64

JAZF1
False    183
Name: JAZF1, dtype: int64

JDP2
False    183
Name: JDP2, dtype: int64

JHDM1D
False    183
Name: JHDM1D, dtype: int64

JKAMP
False    183
Name: JKAMP, dtype: int64

JMJD1C
False    183
Name: JMJD1C, dtype: int64

JMJD4
False    183
Name: JMJD4, dtype: int64

JMJD5
False    183
Name: JMJD5, dtype: int64

JMJD6
False    183
Name: JMJD6, dtype: int64

JMJD7-PLA2G4B
False    183
Name: JMJD7-PLA2G4B, dtype: int64

JMJD8
False    183
Name: JMJD8, dtype: int64

JMY
False    183
Name: JMY, dtype: int64

JOSD1
False    183
Name: JOSD1, dtype: int64

JOSD2
False    183
Name: JOSD2, dtype: int64

JPH1
False    183
Name: JPH1, dtype: int64

JPH2
False    183
Name: JPH2, dtype: int64

JPH3
False    183
Name: JPH3, dtype: int64

JPH4
False    182
True       1
Name: JPH4, dtype: int64

JRKL
False    183
Name: JRKL, dtype: int64

JRK
False    183
Name: JRK, dtype: int64

JSRP1
False    182
True       1
Name: JSRP1, dtype: int64

JTB
False    183
Name: JTB, dtype: int64

JUB
False    183
Name: JUB, dtype: int64

JUNB
False    183
Name: JUNB, dtype: int64

JUND
False    183
Name: JUND, dtype: int64

JUN
False    183
Name: JUN, dtype: int64

JUP
False    183
Name: JUP, dtype: int64

KAAG1
False    169
True      14
Name: KAAG1, dtype: int64

KAL1
False    183
Name: KAL1, dtype: int64

KALRN
False    183
Name: KALRN, dtype: int64

KANK1
False    183
Name: KANK1, dtype: int64

KANK2
False    183
Name: KANK2, dtype: int64

KANK3
False    183
Name: KANK3, dtype: int64

KANK4
False    183
Name: KANK4, dtype: int64

KARS
False    183
Name: KARS, dtype: int64

KAT2A
False    183
Name: KAT2A, dtype: int64

KAT2B
False    183
Name: KAT2B, dtype: int64

KAT5
False    183
Name: KAT5, dtype: int64

KATNA1
False    183
Name: KATNA1, dtype: int64

KATNAL1
False    183
Name: KATNAL1, dtype: int64

KATNAL2
False    183
Name: KATNAL2, dtype: int64

KATNB1
False    183
Name: KATNB1, dtype: int64

KAZALD1
False    183
Name: KAZALD1, dtype: int64

KAZ

False    183
Name: KAZ, dtype: int64

KBTBD10
False    183
Name: KBTBD10, dtype: int64

KBTBD11
False    183
Name: KBTBD11, dtype: int64

KBTBD12
False    179
True       4
Name: KBTBD12, dtype: int64

KBTBD2
False    183
Name: KBTBD2, dtype: int64

KBTBD3
False    183
Name: KBTBD3, dtype: int64

KBTBD4
False    183
Name: KBTBD4, dtype: int64

KBTBD6
False    183
Name: KBTBD6, dtype: int64

KBTBD7
False    183
Name: KBTBD7, dtype: int64

KBTBD8
False    183
Name: KBTBD8, dtype: int64

KC6
True     99
False    84
Name: KC6, dtype: int64

KCMF1
False    183
Name: KCMF1, dtype: int64

KCNA10
True     95
False    88
Name: KCNA10, dtype: int64

KCNA1
False    166
True      17
Name: KCNA1, dtype: int64

KCNA2
False    144
True      39
Name: KCNA2, dtype: int64

KCNA3
False    182
True       1
Name: KCNA3, dtype: int64

KCNA4
True     100
False     83
Name: KCNA4, dtype: int64

KCNA5
False    183
Name: KCNA5, dtype: int64

KCNA6
False    183
Name: KCNA6, dtype: int64

KCNA7
False    149
True      34
Name: KCNA7, dtype: int64

KCNAB1
False    183
Name: KCNAB1, dtype: int64

KCNAB2
False    183
Name: KCNAB2, dtype: int64

KCNAB3
False    183
Name: KCNAB3, dtype: int64

KCNB1
False    172
True      11
Name: KCNB1, dtype: int64

KCNB2
False    178
True       5
Name: KCNB2, dtype: int64

KCNC1
False    177
True       6
Name: KCNC1, dtype: int64

KCNC2
False    140
True      43
Name: KCNC2, dtype: int64

KCNC3
False    183
Name: KCNC3, dtype: int64

KCNC4
False    183
Name: KCNC4, dtype: int64

KCND1
False    183
Name: KCND1, dtype: int64

KCND2
False    183
Name: KCND2, dtype: int64

KCND3
False    181
True       2
Name: KCND3, dtype: int64

KCNE1L
False    183
Name: KCNE1L, dtype: int64

KCNE1
False    177
True       6
Name: KCNE1, dtype: int64

KCNE2
False    182
True       1
Name: KCNE2, dtype: int64

KCNE3
False    183
Name: KCNE3, dtype: int64

KCNE4
False    183
Name: KCNE4, dtype: int64

KCNF1
False    183
Name: KCNF1, dtype: int64

KCNG1
False    181
True       2
Name: KCNG1, dtype: int64

KCNG2
False    161
True      22
Name: KCNG2, dtype: int64

KCNG3
False    178
True       5
Name: KCNG3, dtype: int64

KCNH1
False    183
Name: KCNH1, dtype: int64

KCNH2
False    183
Name: KCNH2, dtype: int64

KCNH3
False    183
Name: KCNH3, dtype: int64

KCNH4
False    180
True       3
Name: KCNH4, dtype: int64

KCNH6
False    175
True       8
Name: KCNH6, dtype: int64

KCNH7
False    161
True      22
Name: KCNH7, dtype: int64

KCNH8
False    182
True       1
Name: KCNH8, dtype: int64

KCNIP1
False    180
True       3
Name: KCNIP1, dtype: int64

KCNIP2
False    183
Name: KCNIP2, dtype: int64

KCNIP3
False    183
Name: KCNIP3, dtype: int64

KCNIP4
False    183
Name: KCNIP4, dtype: int64

KCNJ10
False    182
True       1
Name: KCNJ10, dtype: int64

KCNJ11
False    183
Name: KCNJ11, dtype: int64

KCNJ12
False    183
Name: KCNJ12, dtype: int64

KCNJ13
False    166
True      17
Name: KCNJ13, dtype: int64

KCNJ14
False    183
Name: KCNJ14, dtype: int64

KCNJ15
False    183
Name: KCNJ15, dtype: int64

KCNJ16
False    181
True       2
Name: KCNJ16, dtype: int64

KCNJ1
False    170
True      13
Name: KCNJ1, dtype: int64

KCNJ2
False    183
Name: KCNJ2, dtype: int64

KCNJ3
False    176
True       7
Name: KCNJ3, dtype: int64

KCNJ4
False    154
True      29
Name: KCNJ4, dtype: int64

KCNJ5
False    183
Name: KCNJ5, dtype: int64

KCNJ6
False    177
True       6
Name: KCNJ6, dtype: int64

KCNJ8
False    183
Name: KCNJ8, dtype: int64

KCNJ9
False    131
True      52
Name: KCNJ9, dtype: int64

KCNK10
False    181
True       2
Name: KCNK10, dtype: int64

KCNK12
False    178
True       5
Name: KCNK12, dtype: int64

KCNK13
False    183
Name: KCNK13, dtype: int64

KCNK15
False    182
True       1
Name: KCNK15, dtype: int64

KCNK16
False    170
True      13
Name: KCNK16, dtype: int64

KCNK17
False    182
True       1
Name: KCNK17, dtype: int64

KCNK1
False    183
Name: KCNK1, dtype: int64

KCNK2
False    181
True       2
Name: KCNK2, dtype: int64

KCNK3
False    183
Name: KCNK3, dtype: int64

KCNK4
False    143
True      40
Name: KCNK4, dtype: int64

KCNK5
False    183
Name: KCNK5, dtype: int64

KCNK6
False    183
Name: KCNK6, dtype: int64

KCNK7
False    183
Name: KCNK7, dtype: int64

KCNK9
False    178
True       5
Name: KCNK9, dtype: int64

KCNMA1
False    183
Name: KCNMA1, dtype: int64

KCNMB1
False    183
Name: KCNMB1, dtype: int64

KCNMB2
False    182
True       1
Name: KCNMB2, dtype: int64

KCNMB3
False    183
Name: KCNMB3, dtype: int64

KCNMB4
False    183
Name: KCNMB4, dtype: int64

KCNN1
False    180
True       3
Name: KCNN1, dtype: int64

KCNN2
False    183
Name: KCNN2, dtype: int64

KCNN3
False    183
Name: KCNN3, dtype: int64

KCNN4
False    183
Name: KCNN4, dtype: int64

KCNQ1OT1
False    183
Name: KCNQ1OT1, dtype: int64

KCNQ1
False    183
Name: KCNQ1, dtype: int64

KCNQ2
False    168
True      15
Name: KCNQ2, dtype: int64

KCNQ3
False    180
True       3
Name: KCNQ3, dtype: int64

KCNQ4
False    177
True       6
Name: KCNQ4, dtype: int64

KCNQ5
False    182
True       1
Name: KCNQ5, dtype: int64

KCNRG
False    182
True       1
Name: KCNRG, dtype: int64

KCNS1
False    180
True       3
Name: KCNS1, dtype: int64

KCNS2
False    175
True       8
Name: KCNS2, dtype: int64

KCNS3
False    183
Name: KCNS3, dtype: int64

KCNT1
False    175
True       8
Name: KCNT1, dtype: int64

KCNT2
False    182
True       1
Name: KCNT2, dtype: int64

KCNU1
True     126
False     57
Name: KCNU1, dtype: int64

KCNV1
True     96
False    87
Name: KCNV1, dtype: int64

KCNV2
False    111
True      72
Name: KCNV2, dtype: int64

KCP
False    183
Name: KCP, dtype: int64

KCTD10
False    183
Name: KCTD10, dtype: int64

KCTD11
False    183
Name: KCTD11, dtype: int64

KCTD12
False    183
Name: KCTD12, dtype: int64

KCTD13
False    183
Name: KCTD13, dtype: int64

KCTD14
False    183
Name: KCTD14, dtype: int64

KCTD15
False    183
Name: KCTD15, dtype: int64

KCTD16
False    183
Name: KCTD16, dtype: int64

KCTD17
False    183
Name: KCTD17, dtype: int64

KCTD18
False    183
Name: KCTD18, dtype: int64

KCTD19
False    169
True      14
Name: KCTD19, dtype: int64

KCTD1
False    183
Name: KCTD1, dtype: int64

KCTD20
False    183
Name: KCTD20, dtype: int64

KCTD21
False    183
Name: KCTD21, dtype: int64

KCTD2
False    183
Name: KCTD2, dtype: int64

KCTD3
False    183
Name: KCTD3, dtype: int64

KCTD4
False    134
True      49
Name: KCTD4, dtype: int64

KCTD5
False    183
Name: KCTD5, dtype: int64

KCTD6
False    183
Name: KCTD6, dtype: int64

KCTD7
False    183
Name: KCTD7, dtype: int64

KCTD8
False    159
True      24
Name: KCTD8, dtype: int64

KCTD9
False    183
Name: KCTD9, dtype: int64

KDELC1
False    183
Name: KDELC1, dtype: int64

KDELC2
False    183
Name: KDELC2, dtype: int64

KDELR1
False    183
Name: KDELR1, dtype: int64

KDELR2
False    183
Name: KDELR2, dtype: int64

KDELR3
False    183
Name: KDELR3, dtype: int64

KDM1A
False    183
Name: KDM1A, dtype: int64

KDM1B
False    183
Name: KDM1B, dtype: int64

KDM2A
False    183
Name: KDM2A, dtype: int64

KDM2B
False    183
Name: KDM2B, dtype: int64

KDM3A
False    183
Name: KDM3A, dtype: int64

KDM3B
False    183
Name: KDM3B, dtype: int64

KDM4A
False    183
Name: KDM4A, dtype: int64

KDM4B
False    183
Name: KDM4B, dtype: int64

KDM4C
False    183
Name: KDM4C, dtype: int64

KDM4DL
False    99
True     84
Name: KDM4DL, dtype: int64

KDM4D
False    183
Name: KDM4D, dtype: int64

KDM5A
False    183
Name: KDM5A, dtype: int64

KDM5B
False    183
Name: KDM5B, dtype: int64

KDM5C
False    183
Name: KDM5C, dtype: int64

KDM5D
False    134
True      49
Name: KDM5D, dtype: int64

KDM6A
False    183
Name: KDM6A, dtype: int64

KDM6B
False    183
Name: KDM6B, dtype: int64

KDR
False    183
Name: KDR, dtype: int64

KDSR
False    183
Name: KDSR, dtype: int64

KEAP1
False    183
Name: KEAP1, dtype: int64

KEL
False    178
True       5
Name: KEL, dtype: int64

KERA
False    172
True      11
Name: KERA, dtype: int64

KGFLP1
False    107
True      76
Name: KGFLP1, dtype: int64

KGFLP2
False    183
Name: KGFLP2, dtype: int64

KHDC1L
False    101
True      82
Name: KHDC1L, dtype: int64

KHDC1
False    183
Name: KHDC1, dtype: int64

KHDRBS1
False    183
Name: KHDRBS1, dtype: int64

KHDRBS2
False    138
True      45
Name: KHDRBS2, dtype: int64

KHDRBS3
False    183
Name: KHDRBS3, dtype: int64

KHK
False    183
Name: KHK, dtype: int64

KHNYN
False    183
Name: KHNYN, dtype: int64

KHSRP
False    183
Name: KHSRP, dtype: int64

KIAA0020
False    183
Name: KIAA0020, dtype: int64

KIAA0040
False    183
Name: KIAA0040, dtype: int64

KIAA0087
False    161
True      22
Name: KIAA0087, dtype: int64

KIAA0090
False    183

Name: KIAA0090, dtype: int64

KIAA0100
False    183
Name: KIAA0100, dtype: int64

KIAA0101
False    183
Name: KIAA0101, dtype: int64

KIAA0114
False    183
Name: KIAA0114, dtype: int64

KIAA0125
False    175
True       8
Name: KIAA0125, dtype: int64

KIAA0141
False    183
Name: KIAA0141, dtype: int64

KIAA0146
False    183
Name: KIAA0146, dtype: int64

KIAA0174
False    183
Name: KIAA0174, dtype: int64

KIAA0182
False    183
Name: KIAA0182, dtype: int64

KIAA0195
False    183
Name: KIAA0195, dtype: int64

KIAA0196
False    183
Name: KIAA0196, dtype: int64

KIAA0226
False    183
Name: KIAA0226, dtype: int64

KIAA0232
False    183
Name: KIAA0232, dtype: int64

KIAA0240
False    183
Name: KIAA0240, dtype: int64

KIAA0247
False    183
Name: KIAA0247, dtype: int64

KIAA0284
False    183
Name: KIAA0284, dtype: int64

KIAA0317
False    183
Name: KIAA0317, dtype: int64

KIAA0319L
False    183
Name: KIAA0319L, dtype: int64

KIAA0319
False    183
Name: KIAA0319, dtype: int64

KIAA0355
False    183
Name: KIAA0355, dtype: int64

KIAA0368
False    183
Name: KIAA0368, dtype: int64

KIAA0391
False    183
Name: KIAA0391, dtype: int64

KIAA0406
False    183
Name: KIAA0406, dtype: int64

KIAA0408
True     92
False    91
Name: KIAA0408, dtype: int64

KIAA0415
False    183
Name: KIAA0415, dtype: int64

KIAA0427
False    183
Name: KIAA0427, dtype: int64

KIAA0430
False    183
Name: KIAA0430, dtype: int64

KIAA0467
False    183
Name: KIAA0467, dtype: int64

KIAA0494
False    183
Name: KIAA0494, dtype: int64

KIAA0495
False    183
Name: KIAA0495, dtype: int64

KIAA0513
False    183
Name: KIAA0513, dtype: int64

KIAA0528
False    183
Name: KIAA0528, dtype: int64

KIAA0556
False    183
Name: KIAA0556, dtype: int64

KIAA0562
False    183
Name: KIAA0562, dtype: int64

KIAA0564
False    183
Name: KIAA0564, dtype: int64

KIAA0586
False    183
Name: KIAA0586, dtype: int64

KIAA0649
False    183
Name: KIAA0649, dtype: int64

KIAA0652
False    183
Name: KIAA0652, dtype: int64

KIAA0664P3
False    183
Name: KIAA0664P3, dtype: int64

KIAA0664
False    183
Name: KIAA0664, dtype: int64

KIAA0748
False    182
True       1
Name: KIAA0748, dtype: int64

KIAA0753
False    183
Name: KIAA0753, dtype: int64

KIAA0754
False    183
Name: KIAA0754, dtype: int64

KIAA0776
False    183
Name: KIAA0776, dtype: int64

KIAA0802
False    183
Name: KIAA0802, dtype: int64

KIAA0831
False    183
Name: KIAA0831, dtype: int64

KIAA0892
False    183
Name: KIAA0892, dtype: int64

KIAA0895L
False    183
Name: KIAA0895L, dtype: int64

KIAA0895
False    183
Name: KIAA0895, dtype: int64

KIAA0907
False    183
Name: KIAA0907, dtype: int64

KIAA0913
False    183
Name: KIAA0913, dtype: int64

KIAA0922
False    183
Name: KIAA0922, dtype: int64

KIAA0947
False    183
Name: KIAA0947, dtype: int64

KIAA1009
False    183
Name: KIAA1009, dtype: int64

KIAA1012
False    183
Name: KIAA1012, dtype: int64

KIAA1024
False    183
Name: KIAA1024, dtype: int64

KIAA1033
False    183
Name: KIAA1033, dtype: int64

KIAA1045
False    180
True       3
Name: KIAA1045, dtype: int64

KIAA1107
False    183
Name: KIAA1107, dtype: int64

KIAA1109
False    183
Name: KIAA1109, dtype: int64

KIAA1143
False    183
Name: KIAA1143, dtype: int64

KIAA1147
False    183
Name: KIAA1147, dtype: int64

KIAA1161
False    183
Name: KIAA1161, dtype: int64

KIAA1191
False    183
Name: KIAA1191, dtype: int64

KIAA1199
False    183
Name: KIAA1199, dtype: int64

KIAA1210
False    147
True      36
Name: KIAA1210, dtype: int64

KIAA1211
False    183
Name: KIAA1211, dtype: int64

KIAA1217
False    183
Name: KIAA1217, dtype: int64

KIAA1239
False    177
True       6
Name: KIAA1239, dtype: int64

KIAA1244
False    183
Name: KIAA1244, dtype: int64

KIAA1257
False    183
Name: KIAA1257, dtype: int64

KIAA1267
False    183
Name: KIAA1267, dtype: int64

KIAA1274
False    183
Name: KIAA1274, dtype: int64

KIAA1279
False    183
Name: KIAA1279, dtype: int64

KIAA1310
False    183
Name: KIAA1310, dtype: int64

KIAA1324L
False    183
Name: KIAA1324L, dtype: int64

KIAA1324
False    183
Name: KIAA1324, dtype: int64

KIAA1328
False    183
Name: KIAA1328, dtype: int64

KIAA1370
False    183
Name: KIAA1370, dtype: int64

KIAA1377
False    183
Name: KIAA1377, dtype: int64

KIAA1383
False    183
Name: KIAA1383, dtype: int64

KIAA1407
False    183
Name: KIAA1407, dtype: int64

KIAA1409
False    183
Name: KIAA1409, dtype: int64

KIAA1429
False    183
Name: KIAA1429, dtype: int64

KIAA1430
False    183
Name: KIAA1430, dtype: int64

KIAA1432
False    183
Name: KIAA1432, dtype: int64

KIAA1462
False    183
Name: KIAA1462, dtype: int64

KIAA1467
False    183
Name: KIAA1467, dtype: int64

KIAA1468
False    183
Name: KIAA1468, dtype: int64

KIAA1486
False    154
True      29
Name: KIAA1486, dtype: int64

KIAA1522
False    183
Name: KIAA1522, dtype: int64

KIAA1524
False    183
Name: KIAA1524, dtype: int64

KIAA1529
False    183
Name: KIAA1529, dtype: int64

KIAA1530
False    183
Name: KIAA1530, dtype: int64

KIAA1539
False    183
Name: KIAA1539, dtype: int64

KIAA1543
False    183
Name: KIAA1543, dtype: int64

KIAA1549
False    183
Name: KIAA1549, dtype: int64

KIAA1586
False    183
Name: KIAA1586, dtype: int64

KIAA1598
False    183
Name: KIAA1598, dtype: int64

KIAA1609
False    183
Name: KIAA1609, dtype: int64

KIAA1614
False    183
Name: KIAA1614, dtype: int64

KIAA1632
False    183
Name: KIAA1632, dtype: int64

KIAA1644
False    183
Name: KIAA1644, dtype: int64

KIAA1671
False    183
Name: KIAA1671, dtype: int64

KIAA1683
False    183
Name: KIAA1683, dtype: int64

KIAA1704
False    183
Name: KIAA1704, dtype: int64

KIAA1712
False    183
Name: KIAA1712, dtype: int64

KIAA1715
False    183
Name: KIAA1715, dtype: int64

KIAA1731
False    183
Name: KIAA1731, dtype: int64

KIAA1737
False    183
Name: KIAA1737, dtype: int64

KIAA1751
False    147
True      36
Name: KIAA1751, dtype: int64

KIAA1755
False    183
Name: KIAA1755, dtype: int64

KIAA1797
False    183
Name: KIAA1797, dtype: int64

KIAA1804
False    183
Name: KIAA1804, dtype: int64

KIAA1826
False    183
Name: KIAA1826, dtype: int64

KIAA1841
False    183
Name: KIAA1841, dtype: int64

KIAA1875
False    183
Name: KIAA1875, dtype: int64

KIAA1908
False    183
Name: KIAA1908, dtype: int64

KIAA1919
False    183
Name: KIAA1919, dtype: int64

KIAA1949
False    183
Name: KIAA1949, dtype: int64

KIAA1958
False    183
Name: KIAA1958, dtype: int64

KIAA1967
False    183
Name: KIAA1967, dtype: int64

KIAA1984
False    182
True       1
Name: KIAA1984, dtype: int64

KIAA2013
False    183
Name: KIAA2013, dtype: int64

KIAA2018
False    183
Name: KIAA2018, dtype: int64

KIAA2022
False    181
True       2
Name: KIAA2022, dtype: int64

KIAA2026
False    183
Name: KIAA2026, dtype: int64

KIDINS220
False    183
Name: KIDINS220, dtype: int64

KIF11
False    183
Name: KIF11, dtype: int64

KIF12
False    183
Name: KIF12, dtype: int64

KIF13A
False    183
Name: KIF13A, dtype: int64

KIF13B
False    183
Name: KIF13B, dtype: int64

KIF14
False    182
True       1
Name: KIF14, dtype: int64

KIF15
False    183
Name: KIF15, dtype: int64

KIF16B
False    183
Name: KIF16B, dtype: int64

KIF17
False    183
Name: KIF17, dtype: int64

KIF18A
False    183
Name: KIF18A, dtype: int64

KIF18B
False    183
Name: KIF18B, dtype: int64

KIF19
False    182
True       1
Name: KIF19, dtype: int64

KIF1A
False    183
Name: KIF1A, dtype: int64

KIF1B
False    183
Name: KIF1B, dtype: int64

KIF1C
False    183
Name: KIF1C, dtype: int64

KIF20A
False    183
Name: KIF20A, dtype: int64

KIF20B
False    183
Name: KIF20B, dtype: int64

KIF21A
False    183
Name: KIF21A, dtype: int64

KIF21B
False    183
Name: KIF21B, dtype: int64

KIF22
False    183
Name: KIF22, dtype: int64

KIF23
False    183
Name: KIF23, dtype: int64

KIF24
False    183
Name: KIF24, dtype: int64

KIF25
False    150
True      33
Name: KIF25, dtype: int64

KIF26A
False    183
Name: KIF26A, dtype: int64

KIF26B
False    183
Name: KIF26B, dtype: int64

KIF27
False    183
Name: KIF27, dtype: int64

KIF2A
False    183
Name: KIF2A, dtype: int64

KIF2C
False    183
Name: KIF2C, dtype: int64

KIF3A
False    183
Name: KIF3A, dtype: int64

KIF3B
False    183
Name: KIF3B, dtype: int64

KIF3C
False    183
Name: KIF3C, dtype: int64

KIF4A
False    183
Name: KIF4A, dtype: int64

KIF4B
False    182
True       1
Name: KIF4B, dtype: int64

KIF5A

False    183
Name: KIF5A, dtype: int64

KIF5B
False    183
Name: KIF5B, dtype: int64

KIF5C
False    183
Name: KIF5C, dtype: int64

KIF6
False    181
True       2
Name: KIF6, dtype: int64

KIF7
False    183
Name: KIF7, dtype: int64

KIF9
False    183
Name: KIF9, dtype: int64

KIFAP3
False    183
Name: KIFAP3, dtype: int64

KIFC1
False    183
Name: KIFC1, dtype: int64

KIFC2
False    183
Name: KIFC2, dtype: int64

KIFC3
False    183
Name: KIFC3, dtype: int64

KILLIN
False    183
Name: KILLIN, dtype: int64

KIN
False    183
Name: KIN, dtype: int64

KIR2DL1
False    95
True     88
Name: KIR2DL1, dtype: int64

KIR2DL3
False    109
True      74
Name: KIR2DL3, dtype: int64

KIR2DL4
False    157
True      26
Name: KIR2DL4, dtype: int64

KIR2DS4
False    105
True      78
Name: KIR2DS4, dtype: int64

KIR3DL1
False    102
True      81
Name: KIR3DL1, dtype: int64

KIR3DL2
False    115
True      68
Name: KIR3DL2, dtype: int64

KIRREL2
False    181
True       2
Name: KIRREL2, dtype: int64

KIRREL3
False    183
Name: KIRREL3, dtype: int64

KIRREL
False    183
Name: KIRREL, dtype: int64

KISS1R
False    165
True      18
Name: KISS1R, dtype: int64

KISS1
False    176
True       7
Name: KISS1, dtype: int64

KITLG
False    183
Name: KITLG, dtype: int64

KIT
False    183
Name: KIT, dtype: int64

KLB
False    180
True       3
Name: KLB, dtype: int64

KLC1
False    183
Name: KLC1, dtype: int64

KLC2
False    183
Name: KLC2, dtype: int64

KLC3
False    183
Name: KLC3, dtype: int64

KLC4
False    183
Name: KLC4, dtype: int64

KLF10
False    183
Name: KLF10, dtype: int64

KLF11
False    183
Name: KLF11, dtype: int64

KLF12
False    183
Name: KLF12, dtype: int64

KLF13
False    183
Name: KLF13, dtype: int64

KLF14
False    171
True      12
Name: KLF14, dtype: int64

KLF15
False    183
Name: KLF15, dtype: int64

KLF16
False    183
Name: KLF16, dtype: int64

KLF17
False    165
True      18
Name: KLF17, dtype: int64

KLF1
False    136
True      47
Name: KLF1, dtype: int64

KLF2
False    183
Name: KLF2, dtype: int64

KLF3
False    183
Name: KLF3, dtype: int64

KLF4
False    183
Name: KLF4, dtype: int64

KLF5
False    183
Name: KLF5, dtype: int64

KLF6
False    183
Name: KLF6, dtype: int64

KLF7
False    183
Name: KLF7, dtype: int64

KLF8
False    183
Name: KLF8, dtype: int64

KLF9
False    183
Name: KLF9, dtype: int64

KLHDC10
False    183
Name: KLHDC10, dtype: int64

KLHDC1
False    183
Name: KLHDC1, dtype: int64

KLHDC2
False    183
Name: KLHDC2, dtype: int64

KLHDC3
False    183
Name: KLHDC3, dtype: int64

KLHDC4
False    183
Name: KLHDC4, dtype: int64

KLHDC5
False    183
Name: KLHDC5, dtype: int64

KLHDC7A
False    182
True       1
Name: KLHDC7A, dtype: int64

KLHDC7B
False    182
True       1
Name: KLHDC7B, dtype: int64

KLHDC8A
False    183
Name: KLHDC8A, dtype: int64

KLHDC8B
False    183
Name: KLHDC8B, dtype: int64

KLHDC9
False    183
Name: KLHDC9, dtype: int64

KLHL10
False    147
True      36
Name: KLHL10, dtype: int64

KLHL11
False    183
Name: KLHL11, dtype: int64

KLHL12
False    183
Name: KLHL12, dtype: int64

KLHL13
False    183
Name: KLHL13, dtype: int64

KLHL14
False    173
True      10
Name: KLHL14, dtype: int64

KLHL15
False    183
Name: KLHL15, dtype: int64

KLHL17
False    183
Name: KLHL17, dtype: int64

KLHL18
False    183
Name: KLHL18, dtype: int64

KLHL1
False    118
True      65
Name: KLHL1, dtype: int64

KLHL20
False    183
Name: KLHL20, dtype: int64

KLHL21
False    183
Name: KLHL21, dtype: int64

KLHL22
False    183
Name: KLHL22, dtype: int64

KLHL23
False    183
Name: KLHL23, dtype: int64

KLHL24
False    183
Name: KLHL24, dtype: int64

KLHL25
False    183
Name: KLHL25, dtype: int64

KLHL26
False    183
Name: KLHL26, dtype: int64

KLHL28
False    183
Name: KLHL28, dtype: int64

KLHL29
False    183
Name: KLHL29, dtype: int64

KLHL2
False    183
Name: KLHL2, dtype: int64

KLHL30
False    183
Name: KLHL30, dtype: int64

KLHL31
False    183
Name: KLHL31, dtype: int64

KLHL32
False    182
True       1
Name: KLHL32, dtype: int64

KLHL33
False    161
True      22
Name: KLHL33, dtype: int64

KLHL34
False    156
True      27
Name: KLHL34, dtype: int64

KLHL35
False    183
Name: KLHL35, dtype: int64

KLHL36
False    183
Name: KLHL36, dtype: int64

KLHL38
False    176
True       7
Name: KLHL38, dtype: int64

KLHL3
False    183
Name: KLHL3, dtype: int64

KLHL4
False    182
True       1
Name: KLHL4, dtype: int64

KLHL5
False    183
Name: KLHL5, dtype: int64

KLHL6
False    183
Name: KLHL6, dtype: int64

KLHL7
False    183
Name: KLHL7, dtype: int64

KLHL8
False    183
Name: KLHL8, dtype: int64

KLHL9
False    183
Name: KLHL9, dtype: int64

KLK10
False    181
True       2
Name: KLK10, dtype: int64

KLK11
False    178
True       5
Name: KLK11, dtype: int64

KLK12
False    107
True      76
Name: KLK12, dtype: int64

KLK13
False    173
True      10
Name: KLK13, dtype: int64

KLK14
False    163
True      20
Name: KLK14, dtype: int64

KLK15
True     118
False     65
Name: KLK15, dtype: int64

KLK1
False    180
True       3
Name: KLK1, dtype: int64

KLK2
False    125
True      58
Name: KLK2, dtype: int64

KLK3
False    114
True      69
Name: KLK3, dtype: int64

KLK4
False    171
True      12
Name: KLK4, dtype: int64

KLK5
False    133
True      50
Name: KLK5, dtype: int64

KLK6
False    177
True       6
Name: KLK6, dtype: int64

KLK7
False    176
True       7
Name: KLK7, dtype: int64

KLK8
False    170
True      13
Name: KLK8, dtype: int64

KLK9
False    124
True      59
Name: KLK9, dtype: int64

KLKB1
False    182
True       1
Name: KLKB1, dtype: int64

KLKP1
False    113
True      70
Name: KLKP1, dtype: int64

KLRA1
False    183
Name: KLRA1, dtype: int64

KLRAQ1
False    183
Name: KLRAQ1, dtype: int64

KLRB1
False    183
Name: KLRB1, dtype: int64

KLRC1
False    181
True       2
Name: KLRC1, dtype: int64

KLRC2
False    174
True       9
Name: KLRC2, dtype: int64

KLRC3
False    173
True      10
Name: KLRC3, dtype: int64

KLRC4
False    115
True      68
Name: KLRC4, dtype: int64

KLRD1
False    182
True       1
Name: KLRD1, dtype: int64

KLRF1
False    183
Name: KLRF1, dtype: int64

KLRG1
False    183
Name: KLRG1, dtype: int64

KLRG2
False    92
True     91
Name: KLRG2, dtype: int64

KLRK1
False    183
Name: KLRK1, dtype: int64

KL
False    183
Name: KL, dtype: int64

KMO
False    183
Name: KMO, dtype: int64

KNDC1
False    182
True       1
Name: KNDC1, dtype: int64

KNG1
False    111
True      72
Name: KNG1, dtype: int64

KNTC1
False    183
Name: KNTC1, dtype: int64

KPNA1
False    183
Name: KPNA1, dtype: int64

KPNA2
False    183
Name: KPNA2, dtype: int64

KPNA3
False    183
Name: KPNA3, dtype: int64

KPNA4
False    183
Name: KPNA4, dtype: int64

KPNA5
False    183
Name: KPNA5, dtype: int64

KPNA6
False    183
Name: KPNA6, dtype: int64

KPNA7
False    177
True       6
Name: KPNA7, dtype: int64

KPNB1
False    183
Name: KPNB1, dtype: int64

KPTN
False    183
Name: KPTN, dtype: int64

KRAS
False    183
Name: KRAS, dtype: int64

KRBA1
False    183
Name: KRBA1, dtype: int64

KRBA2
False    183
Name: KRBA2, dtype: int64

KRCC1
False    183
Name: KRCC1, dtype: int64

KREMEN1
False    183
Name: KREMEN1, dtype: int64

KREMEN2
False    181
True       2
Name: KREMEN2, dtype: int64

KRI1
False    183
Name: KRI1, dtype: int64

KRIT1
False    183
Name: KRIT1, dtype: int64

KRR1
False    183
Name: KRR1, dtype: int64

KRT10
False    183
Name: KRT10, dtype: int64

KRT12
False    125
True      58
Name: KRT12, dtype: int64

KRT13
False    175
True       8
Name: KRT13, dtype: int64

KRT14
False    179
True       4
Name: KRT14, dtype: int64

KRT15
False    182
True       1
Name: KRT15, dtype: int64

KRT16
False    178
True       5
Name: KRT16, dtype: int64

KRT17
False    183
Name: KRT17, dtype: int64

KRT18
False    183
Name: KRT18, dtype: int64

KRT19
False    183
Name: KRT19, dtype: int64

KRT1
False    144
True      39
Name: KRT1, dtype: int64

KRT20
False    160
True      23
Name: KRT20, dtype: int64

KRT222
False    183
Name: KRT222, dtype: int64

KRT23
False    182
True       1
Name: KRT23, dtype: int64

KRT27
False    127
True      56
Name: KRT27, dtype: int64

KRT2
False    147
True      36
Name: KRT2, dtype: int64

KRT32
True     109
False     74
Name: KRT32, dtype: int64

KRT34
False    101
True      82
Name: KRT34, dtype: int64

KRT36
False    137
True      46
Name: KRT36, dtype: int64

KRT39
False    126
True      57
Name: KRT39, dtype: int64

KRT3
False    100
True      83
Name: KRT3, dtype: int64

KRT40
False    147
True      36
Name: KRT40, dtype: int64

KRT4
False    169
True      14
Name: KRT4, dtype: int64

KRT5
False    178
True       5
Name: KRT5, dtype: int64

KRT6A
False    175
True       8
Name: KRT6A, dtype: int64

KRT6B
False    177
True       6
Name: KRT6B, dtype: int64

KRT6C
False    171
True      12
Name: KRT6C, dtype: int64

KRT71
True     108
False     75
Name: KRT71, dtype: int64

KRT72
True     93
False    90
Name: KRT72, dtype: int64

KRT73
True     103
False     80
Name: KRT73, dtype: int64

KRT75
False    109
True      74
Name: KRT75, dtype: int64

KRT78
False    134
True      49
Name: KRT78, dtype: int64

KRT79

False    172
True      11
Name: KRT79, dtype: int64

KRT7
False    182
True       1
Name: KRT7, dtype: int64

KRT80
False    181
True       2
Name: KRT80, dtype: int64

KRT81
False    182
True       1
Name: KRT81, dtype: int64

KRT83
False    123
True      60
Name: KRT83, dtype: int64

KRT86
False    181
True       2
Name: KRT86, dtype: int64

KRT8
False    183
Name: KRT8, dtype: int64

KRT9
False    117
True      66
Name: KRT9, dtype: int64

KRTAP1-1
False    108
True      75
Name: KRTAP1-1, dtype: int64

KRTAP1-5
True     108
False     75
Name: KRTAP1-5, dtype: int64

KRTAP2-1
True     128
False     55
Name: KRTAP2-1, dtype: int64

KRTAP4-1
True     94
False    89
Name: KRTAP4-1, dtype: int64

KRTAP5-10
False    124
True      59
Name: KRTAP5-10, dtype: int64

KRTAP5-1
False    182
True       1
Name: KRTAP5-1, dtype: int64

KRTAP5-2
False    138
True      45
Name: KRTAP5-2, dtype: int64

KRTAP5-4
True     96
False    87
Name: KRTAP5-4, dtype: int64

KRTAP5-5
False    132
True      51
Name: KRTAP5-5, dtype: int64

KRTAP5-7
True     98
False    85
Name: KRTAP5-7, dtype: int64

KRTAP5-8
False    138
True      45
Name: KRTAP5-8, dtype: int64

KRTAP5-9
False    175
True       8
Name: KRTAP5-9, dtype: int64

KRTCAP2
False    183
Name: KRTCAP2, dtype: int64

KRTCAP3
False    183
Name: KRTCAP3, dtype: int64

KSR1
False    183
Name: KSR1, dtype: int64

KSR2
False    183
Name: KSR2, dtype: int64

KTELC1
False    183
Name: KTELC1, dtype: int64

KTI12
False    183
Name: KTI12, dtype: int64

KTN1
False    183
Name: KTN1, dtype: int64

KYNU
False    183
Name: KYNU, dtype: int64

KY
False    182
True       1
Name: KY, dtype: int64

L1CAM
False    183
Name: L1CAM, dtype: int64

L1TD1
False    176
True       7
Name: L1TD1, dtype: int64

L2HGDH
False    183
Name: L2HGDH, dtype: int64

L3MBTL2
False    183
Name: L3MBTL2, dtype: int64

L3MBTL3
False    183
Name: L3MBTL3, dtype: int64

L3MBTL4
False    183
Name: L3MBTL4, dtype: int64

L3MBTL
False    183
Name: L3MBTL, dtype: int64

LACE1
False    183
Name: LACE1, dtype: int64

LACTB2
False    183
Name: LACTB2, dtype: int64

LACTB
False    183
Name: LACTB, dtype: int64

LAD1
False    183
Name: LAD1, dtype: int64

LAG3
False    183
Name: LAG3, dtype: int64

LAGE3
False    183
Name: LAGE3, dtype: int64

LAIR1
False    183
Name: LAIR1, dtype: int64

LAIR2
False    158
True      25
Name: LAIR2, dtype: int64

LAMA1
False    183
Name: LAMA1, dtype: int64

LAMA2
False    183
Name: LAMA2, dtype: int64

LAMA3
False    183
Name: LAMA3, dtype: int64

LAMA4
False    183
Name: LAMA4, dtype: int64

LAMA5
False    183
Name: LAMA5, dtype: int64

LAMB1
False    183
Name: LAMB1, dtype: int64

LAMB2L
False    183
Name: LAMB2L, dtype: int64

LAMB2
False    183
Name: LAMB2, dtype: int64

LAMB3
False    183
Name: LAMB3, dtype: int64

LAMB4
False    175
True       8
Name: LAMB4, dtype: int64

LAMC1
False    183
Name: LAMC1, dtype: int64

LAMC2
False    183
Name: LAMC2, dtype: int64

LAMC3
False    183
Name: LAMC3, dtype: int64

LAMP1
False    183
Name: LAMP1, dtype: int64

LAMP2
False    183
Name: LAMP2, dtype: int64

LAMP3
False    183
Name: LAMP3, dtype: int64

LANCL1
False    183
Name: LANCL1, dtype: int64

LANCL2
False    183
Name: LANCL2, dtype: int64

LANCL3
False    181
True       2
Name: LANCL3, dtype: int64

LAP3
False    183
Name: LAP3, dtype: int64

LAPTM4A
False    183
Name: LAPTM4A, dtype: int64

LAPTM4B
False    183
Name: LAPTM4B, dtype: int64

LAPTM5
False    183
Name: LAPTM5, dtype: int64

LARGE
False    183
Name: LARGE, dtype: int64

LARP1B
False    183
Name: LARP1B, dtype: int64

LARP1
False    183
Name: LARP1, dtype: int64

LARP4B
False    183
Name: LARP4B, dtype: int64

LARP4
False    183
Name: LARP4, dtype: int64

LARP6
False    183
Name: LARP6, dtype: int64

LARP7
False    183
Name: LARP7, dtype: int64

LARS2
False    183
Name: LARS2, dtype: int64

LARS
False    183
Name: LARS, dtype: int64

LAS1L
False    183
Name: LAS1L, dtype: int64

LASP1
False    183
Name: LASP1, dtype: int64

LASS1
False    183
Name: LASS1, dtype: int64

LASS2
False    183
Name: LASS2, dtype: int64

LASS3
False    123
True      60
Name: LASS3, dtype: int64

LASS4
False    183
Name: LASS4, dtype: int64

LASS5
False    183
Name: LASS5, dtype: int64

LASS6
False    183
Name: LASS6, dtype: int64

LAT2
False    183
Name: LAT2, dtype: int64

LATS1
False    183
Name: LATS1, dtype: int64

LATS2
False    183
Name: LATS2, dtype: int64

LAT
False    183
Name: LAT, dtype: int64

LAX1
False    183
Name: LAX1, dtype: int64

LAYN
False    183
Name: LAYN, dtype: int64

LBH
False    183
Name: LBH, dtype: int64

LBP
False    168
True      15
Name: LBP, dtype: int64

LBR
False    183
Name: LBR, dtype: int64

LBX2
False    182
True       1
Name: LBX2, dtype: int64

LBXCOR1
False    182
True       1
Name: LBXCOR1, dtype: int64

LCA5L
False    183
Name: LCA5L, dtype: int64

LCA5
False    183
Name: LCA5, dtype: int64

LCAT
False    183
Name: LCAT, dtype: int64

LCE1E
True     128
False     55
Name: LCE1E, dtype: int64

LCK
False    183
Name: LCK, dtype: int64

LCLAT1
False    183
Name: LCLAT1, dtype: int64

LCMT1
False    183
Name: LCMT1, dtype: int64

LCMT2
False    183
Name: LCMT2, dtype: int64

LCN10
False    182
True       1
Name: LCN10, dtype: int64

LCN12
False    183
Name: LCN12, dtype: int64

LCN1
False    112
True      71
Name: LCN1, dtype: int64

LCN2
False    179
True       4
Name: LCN2, dtype: int64

LCN6
False    136
True      47
Name: LCN6, dtype: int64

LCNL1
False    168
True      15
Name: LCNL1, dtype: int64

LCORL
False    183
Name: LCORL, dtype: int64

LCOR
False    183
Name: LCOR, dtype: int64

LCP1
False    183
Name: LCP1, dtype: int64

LCP2
False    183
Name: LCP2, dtype: int64

LCTL
False    151
True      32
Name: LCTL, dtype: int64

LCT
False    133
True      50
Name: LCT, dtype: int64

LDB1
False    183
Name: LDB1, dtype: int64

LDB2
False    183
Name: LDB2, dtype: int64

LDB3
False    183
Name: LDB3, dtype: int64

LDHAL6A
False    111
True      72
Name: LDHAL6A, dtype: int64

LDHAL6B
False    170
True      13
Name: LDHAL6B, dtype: int64

LDHA
False    183
Name: LDHA, dtype: int64

LDHB
False    183
Name: LDHB, dtype: int64

LDHC
False    124
True      59
Name: LDHC, dtype: int64

LDHD
False    183
Name: LDHD, dtype: int64

LDLRAD1
False    154
True      29
Name: LDLRAD1, dtype: int64

LDLRAD2
False    183
Name: LDLRAD2, dtype: int64

LDLRAD3
False    183
Name: LDLRAD3, dtype: int64

LDLRAP1
False    183
Name: LDLRAP1, dtype: int64

LDLR
False    183
Name: LDLR, dtype: int64

LDOC1L
False    183
Name: LDOC1L, dtype: int64

LDOC1
False    183
Name: LDOC1, dtype: int64

LEAP2
False    183
Name: LEAP2, dtype: int64

LECT1
False    147
True      36
Name: LECT1, dtype: int64

LEF1
False    183
Name: LEF1, dtype: int64

LEFTY1
False    182
True       1
Name: LEFTY1, dtype: int64

LEFTY2
False    176
True       7
Name: LEFTY2, dtype: int64

LEKR1
False    183
Name: LEKR1, dtype: int64

LEMD1
False    175
True       8
Name: LEMD1, dtype: int64

LEMD2
False    183
Name: LEMD2, dtype: int64

LEMD3
False    183
Name: LEMD3, dtype: int64

LENEP
True     116
False     67
Name: LENEP, dtype: int64

LENG1
False    183
Name: LENG1, dtype: int64

LENG8
False    183
Name: LENG8, dtype: int64

LENG9
False    183
Name: LENG9, dtype: int64

LEO1
False    183
Name: LEO1, dtype: int64

LEPRE1
False    183
Name: LEPRE1, dtype: int64

LEPREL1
False    183
Name: LEPREL1, dtype: int64

LEPREL2
False    183
Name: LEPREL2, dtype: int64

LEPROTL1
False    183
Name: LEPROTL1, dtype: int64

LEPROT
False    183
Name: LEPROT, dtype: int64

LEPR
False    183
Name: LEPR, dtype: int64

LEP
False    161
True      22
Name: LEP, dtype: int64

LETM1
False    183
Name: LETM1, dtype: int64

LETM2
False    183
Name: LETM2, dtype: int64

LETMD1
False    183
Name: LETMD1, dtype: int64

LFNG
False    183
Name: LFNG, dtype: int64

LGALS12
False    173
True      10
Name: LGALS12, dtype: int64

LGALS1
False    183
Name: LGALS1, dtype: int64

LGALS2
False    183
Name: LGALS2, dtype: int64

LGALS3BP
False    183
Name: LGALS3BP, dtype: int64

LGALS3
False    183
Name: LGALS3, dtype: int64

LGALS4
False    183
Name: LGALS4, dtype: int64

LGALS7B
False    151
True      32
Name: LGALS7B, dtype: int64

LGALS7
False    163
True      20
Name: LGALS7, dtype: int64

LGALS8
False    183
Name: LGALS8, dtype: int64

LGALS9B
False    155
True      28
Name: LGALS9B, dtype: int64

LGALS9C
False    183
Name: LGALS9C, dtype: int64

LGALS9
False    183
Name: LGALS9, dtype: int64

LGI1
False    160
True      23
Name: LGI1, dtype: int64

LGI2
False    183
Name: LGI2, dtype: int64

LGI3
False    178
True       5
Name: LGI3, dtype: int64

LGI4
False    183
Name: LGI4, dtype: int64

LGMN
False    183
Name: LGMN, dtype: int64

LGR4
False    183
Name: LGR4, dtype: int64

LGR5
False    183
Name: LGR5, dtype: int64

LGR6

False    182
True       1
Name: LGR6, dtype: int64

LGSN
False    153
True      30
Name: LGSN, dtype: int64

LGTN
False    183
Name: LGTN, dtype: int64

LHB
False    174
True       9
Name: LHB, dtype: int64

LHCGR
True     127
False     56
Name: LHCGR, dtype: int64

LHFPL1
False    121
True      62
Name: LHFPL1, dtype: int64

LHFPL2
False    183
Name: LHFPL2, dtype: int64

LHFPL3
False    170
True      13
Name: LHFPL3, dtype: int64

LHFPL4
False    183
Name: LHFPL4, dtype: int64

LHFPL5
False    171
True      12
Name: LHFPL5, dtype: int64

LHFP
False    183
Name: LHFP, dtype: int64

LHPP
False    183
Name: LHPP, dtype: int64

LHX1
False    104
True      79
Name: LHX1, dtype: int64

LHX2
False    143
True      40
Name: LHX2, dtype: int64

LHX4
False    177
True       6
Name: LHX4, dtype: int64

LHX5
True     93
False    90
Name: LHX5, dtype: int64

LHX6
False    183
Name: LHX6, dtype: int64

LHX9
False    125
True      58
Name: LHX9, dtype: int64

LIAS
False    183
Name: LIAS, dtype: int64

LIFR
False    183
Name: LIFR, dtype: int64

LIF
False    183
Name: LIF, dtype: int64

LIG1
False    183
Name: LIG1, dtype: int64

LIG3
False    183
Name: LIG3, dtype: int64

LIG4
False    183
Name: LIG4, dtype: int64

LILRA1
False    169
True      14
Name: LILRA1, dtype: int64

LILRA2
False    183
Name: LILRA2, dtype: int64

LILRA3
False    162
True      21
Name: LILRA3, dtype: int64

LILRA4
False    173
True      10
Name: LILRA4, dtype: int64

LILRA5
False    183
Name: LILRA5, dtype: int64

LILRA6
False    183
Name: LILRA6, dtype: int64

LILRB1
False    183
Name: LILRB1, dtype: int64

LILRB2
False    183
Name: LILRB2, dtype: int64

LILRB3
False    183
Name: LILRB3, dtype: int64

LILRB4
False    183
Name: LILRB4, dtype: int64

LILRB5
False    182
True       1
Name: LILRB5, dtype: int64

LILRP2
False    110
True      73
Name: LILRP2, dtype: int64

LIMA1
False    183
Name: LIMA1, dtype: int64

LIMCH1
False    183
Name: LIMCH1, dtype: int64

LIMD1
False    183
Name: LIMD1, dtype: int64

LIMD2
False    183
Name: LIMD2, dtype: int64

LIME1
False    183
Name: LIME1, dtype: int64

LIMK1
False    183
Name: LIMK1, dtype: int64

LIMK2
False    183
Name: LIMK2, dtype: int64

LIMS1
False    183
Name: LIMS1, dtype: int64

LIMS2
False    183
Name: LIMS2, dtype: int64

LIMS3-LOC440895
False    183
Name: LIMS3-LOC440895, dtype: int64

LIMS3
False    182
True       1
Name: LIMS3, dtype: int64

LIN37
False    183
Name: LIN37, dtype: int64

LIN52
False    183
Name: LIN52, dtype: int64

LIN54
False    183
Name: LIN54, dtype: int64

LIN7A
False    183
Name: LIN7A, dtype: int64

LIN7B
False    183
Name: LIN7B, dtype: int64

LIN7C
False    183
Name: LIN7C, dtype: int64

LIN9
False    183
Name: LIN9, dtype: int64

LINGO1
False    183
Name: LINGO1, dtype: int64

LINGO2
False    163
True      20
Name: LINGO2, dtype: int64

LINGO3
False    135
True      48
Name: LINGO3, dtype: int64

LINGO4
False    177
True       6
Name: LINGO4, dtype: int64

LINS1
False    183
Name: LINS1, dtype: int64

LIPA
False    183
Name: LIPA, dtype: int64

LIPC
False    183
Name: LIPC, dtype: int64

LIPE
False    183
Name: LIPE, dtype: int64

LIPF
True     126
False     57
Name: LIPF, dtype: int64

LIPG
False    183
Name: LIPG, dtype: int64

LIPH
False    183
Name: LIPH, dtype: int64

LIPI
True     125
False     58
Name: LIPI, dtype: int64

LIPJ
False    94
True     89
Name: LIPJ, dtype: int64

LIPK
True     127
False     56
Name: LIPK, dtype: int64

LIPN
False    101
True      82
Name: LIPN, dtype: int64

LIPT1
False    183
Name: LIPT1, dtype: int64

LIPT2
False    183
Name: LIPT2, dtype: int64

LITAF
False    183
Name: LITAF, dtype: int64

LIX1L
False    183
Name: LIX1L, dtype: int64

LIX1
False    162
True      21
Name: LIX1, dtype: int64

LLGL1
False    183
Name: LLGL1, dtype: int64

LLGL2
False    183
Name: LLGL2, dtype: int64

LLPH
False    183
Name: LLPH, dtype: int64

LMAN1L
False    94
True     89
Name: LMAN1L, dtype: int64

LMAN1
False    183
Name: LMAN1, dtype: int64

LMAN2L
False    183
Name: LMAN2L, dtype: int64

LMAN2
False    183
Name: LMAN2, dtype: int64

LMBR1L
False    183
Name: LMBR1L, dtype: int64

LMBR1
False    183
Name: LMBR1, dtype: int64

LMBRD1
False    183
Name: LMBRD1, dtype: int64

LMBRD2
False    183
Name: LMBRD2, dtype: int64

LMCD1
False    183
Name: LMCD1, dtype: int64

LMF1
False    183
Name: LMF1, dtype: int64

LMF2
False    183
Name: LMF2, dtype: int64

LMLN
False    183
Name: LMLN, dtype: int64

LMNA
False    183
Name: LMNA, dtype: int64

LMNB1
False    183
Name: LMNB1, dtype: int64

LMNB2
False    183
Name: LMNB2, dtype: int64

LMO1
False    171
True      12
Name: LMO1, dtype: int64

LMO2
False    183
Name: LMO2, dtype: int64

LMO3
False    183
Name: LMO3, dtype: int64

LMO4
False    183
Name: LMO4, dtype: int64

LMO7
False    183
Name: LMO7, dtype: int64

LMOD1
False    183
Name: LMOD1, dtype: int64

LMOD3
False    182
True       1
Name: LMOD3, dtype: int64

LMTK2
False    183
Name: LMTK2, dtype: int64

LMTK3
False    183
Name: LMTK3, dtype: int64

LMX1A
True     99
False    84
Name: LMX1A, dtype: int64

LMX1B
False    180
True       3
Name: LMX1B, dtype: int64

LNP1
False    183
Name: LNP1, dtype: int64

LNPEP
False    183
Name: LNPEP, dtype: int64

LNX1
False    183
Name: LNX1, dtype: int64

LNX2
False    183
Name: LNX2, dtype: int64

LOC100009676
False    183
Name: LOC100009676, dtype: int64

LOC100101266
False    181
True       2
Name: LOC100101266, dtype: int64

LOC100124692
False    178
True       5
Name: LOC100124692, dtype: int64

LOC100125556
False    183
Name: LOC100125556, dtype: int64

LOC100126784
False    182
True       1
Name: LOC100126784, dtype: int64

LOC100127888
False    181
True       2
Name: LOC100127888, dtype: int64

LOC100128076
False    97
True     86
Name: LOC100128076, dtype: int64

LOC100128164
False    159
True      24
Name: LOC100128164, dtype: int64

LOC100128191
False    183
Name: LOC100128191, dtype: int64

LOC100128239
False    178
True       5
Name: LOC100128239, dtype: int64

LOC100128288
False    183
Name: LOC100128288, dtype: int64

LOC100128292
False    183
Name: LOC100128292, dtype: int64

LOC100128542
False    154
True      29
Name: LOC100128542, dtype: int64

LOC100128554
False    97
True     86
Name: LOC100128554, dtype: int64

LOC100128573
False    155
True      28
Name: LOC100128573, dtype: int64

LOC100128640
False    183
Name: LOC100128640, dtype: int64

LOC100128675
False    155
True      28
Name: LOC100128675, dtype: int64

LOC100128788
False    183
Name: LOC100128788, dtype: int64

LOC100128811
True     126
False     57
Name: LOC100128811, dtype: int64

LOC100128822
False    183
Name: LOC100128822, dtype: int64

LOC100128842
False    183
Name: LOC100128842, dtype: int64

LOC100129034
False    183
Name: LOC100129034, dtype: int64

LOC100129055
False    100
True      83
Name: LOC100129055, dtype: int64

LOC100129066
False    173
True      10
Name: LOC100129066, dtype: int64

LOC100129387
False    183
Name: LOC100129387, dtype: int64

LOC100129534
False    183
Name: LOC100129534, dtype: int64

LOC100129550
False    183
Name: LOC100129550, dtype: int64

LOC100129637
False    183
Name: LOC100129637, dtype: int64

LOC100129716
False    182
True       1
Name: LOC100129716, dtype: int64

LOC100129726
False    182
True       1
Name: LOC100129726, dtype: int64

LOC100130015
False    183
Name: LOC100130015, dtype: int64

LOC100130093
False    183
Name: LOC100130093, dtype: int64

LOC100130148
False    99
True     84
Name: LOC100130148, dtype: int64

LOC100130238
False    146
True      37
Name: LOC100130238, dtype: int64

LOC100130331
False    178
True       5
Name: LOC100130331, dtype: int64

LOC100130386
False    93
True     90
Name: LOC100130386, dtype: int64

LOC100130522
False    182
True       1
Name: LOC100130522, dtype: int64

LOC100130557
False    183
Name: LOC100130557, dtype: int64

LOC100130581
False    183
Name: LOC100130581, dtype: int64

LOC100130691
False    183
Name: LOC100130691, dtype: int64

LOC100130776
False    183
Name: LOC100130776, dtype: int64

LOC100130872
False    183
Name: LOC100130872, dtype: int64

LOC100130932
False    183
Name: LOC100130932, dtype: int64

LOC100130933
False    183
Name: LOC100130933, dtype: int64

LOC100130987
False    183
Name: LOC100130987, dtype: int64

LOC100131193
False    183
Name: LOC100131193, dtype: int64

LOC100131434
False    183
Name: LOC100131434, dtype: int64

LOC100131496
False    179
True       4
Name: LOC100131496, dtype: int64

LOC100131551

False    181
True       2
Name: LOC100131551, dtype: int64

LOC100131691
False    183
Name: LOC100131691, dtype: int64

LOC100131726
False    156
True      27
Name: LOC100131726, dtype: int64

LOC100132111
False    174
True       9
Name: LOC100132111, dtype: int64

LOC100132215
False    183
Name: LOC100132215, dtype: int64

LOC100132247
False    183
Name: LOC100132247, dtype: int64

LOC100132287
False    183
Name: LOC100132287, dtype: int64

LOC100132288
False    183
Name: LOC100132288, dtype: int64

LOC100132354
False    167
True      16
Name: LOC100132354, dtype: int64

LOC100132707
False    183
Name: LOC100132707, dtype: int64

LOC100132724
False    178
True       5
Name: LOC100132724, dtype: int64

LOC100132831
False    101
True      82
Name: LOC100132831, dtype: int64

LOC100132832
False    182
True       1
Name: LOC100132832, dtype: int64

LOC100133161
False    183
Name: LOC100133161, dtype: int64

LOC100133331
False    183
Name: LOC100133331, dtype: int64

LOC100133545
False    178
True       5
Name: LOC100133545, dtype: int64

LOC100133612
False    182
True       1
Name: LOC100133612, dtype: int64

LOC100133669
False    174
True       9
Name: LOC100133669, dtype: int64

LOC100133893
False    123
True      60
Name: LOC100133893, dtype: int64

LOC100133957
False    183
Name: LOC100133957, dtype: int64

LOC100133985
False    180
True       3
Name: LOC100133985, dtype: int64

LOC100133991
False    183
Name: LOC100133991, dtype: int64

LOC100134229
False    183
Name: LOC100134229, dtype: int64

LOC100134259
False    183
Name: LOC100134259, dtype: int64

LOC100134368
False    181
True       2
Name: LOC100134368, dtype: int64

LOC100134713
False    183
Name: LOC100134713, dtype: int64

LOC100134868
False    173
True      10
Name: LOC100134868, dtype: int64

LOC100144603
False    183
Name: LOC100144603, dtype: int64

LOC100144604
False    175
True       8
Name: LOC100144604, dtype: int64

LOC100170939
False    183
Name: LOC100170939, dtype: int64

LOC100188947
False    167
True      16
Name: LOC100188947, dtype: int64

LOC100188949
False    182
True       1
Name: LOC100188949, dtype: int64

LOC100189589
False    136
True      47
Name: LOC100189589, dtype: int64

LOC100190938
False    183
Name: LOC100190938, dtype: int64

LOC100190939
False    183
Name: LOC100190939, dtype: int64

LOC100190940
True     109
False     74
Name: LOC100190940, dtype: int64

LOC100190986
False    183
Name: LOC100190986, dtype: int64

LOC100192378
False    170
True      13
Name: LOC100192378, dtype: int64

LOC100192426
False    104
True      79
Name: LOC100192426, dtype: int64

LOC100216001
False    176
True       7
Name: LOC100216001, dtype: int64

LOC100216545
False    183
Name: LOC100216545, dtype: int64

LOC100233209
False    183
Name: LOC100233209, dtype: int64

LOC100240726
False    162
True      21
Name: LOC100240726, dtype: int64

LOC100240734
False    120
True      63
Name: LOC100240734, dtype: int64

LOC100240735
False    175
True       8
Name: LOC100240735, dtype: int64

LOC100268168
False    182
True       1
Name: LOC100268168, dtype: int64

LOC100270710
False    183
Name: LOC100270710, dtype: int64

LOC100270746
False    183
Name: LOC100270746, dtype: int64

LOC100270804
False    183
Name: LOC100270804, dtype: int64

LOC100271722
False    183
Name: LOC100271722, dtype: int64

LOC100271831
False    174
True       9
Name: LOC100271831, dtype: int64

LOC100271836
False    183
Name: LOC100271836, dtype: int64

LOC100272146
False    183
Name: LOC100272146, dtype: int64

LOC100272216
False    179
True       4
Name: LOC100272216, dtype: int64

LOC100272217
False    183
Name: LOC100272217, dtype: int64

LOC100272228
False    183
Name: LOC100272228, dtype: int64

LOC100286793
False    183
Name: LOC100286793, dtype: int64

LOC100286844
False    183
Name: LOC100286844, dtype: int64

LOC100287227
False    182
True       1
Name: LOC100287227, dtype: int64

LOC100288778
False    183
Name: LOC100288778, dtype: int64

LOC100289341
False    183
Name: LOC100289341, dtype: int64

LOC100302401
False    183
Name: LOC100302401, dtype: int64

LOC100302640
False    179
True       4
Name: LOC100302640, dtype: int64

LOC100302650
False    183
Name: LOC100302650, dtype: int64

LOC100303728
False    183
Name: LOC100303728, dtype: int64

LOC113230
False    183
Name: LOC113230, dtype: int64

LOC115110
False    183
Name: LOC115110, dtype: int64

LOC116437
True     103
False     80
Name: LOC116437, dtype: int64

LOC121838
False    147
True      36
Name: LOC121838, dtype: int64

LOC121952
False    165
True      18
Name: LOC121952, dtype: int64

LOC126536
False    145
True      38
Name: LOC126536, dtype: int64

LOC127841
False    164
True      19
Name: LOC127841, dtype: int64

LOC134466
False    182
True       1
Name: LOC134466, dtype: int64

LOC143188
False    183
Name: LOC143188, dtype: int64

LOC143666
False    183
Name: LOC143666, dtype: int64

LOC144438
False    183
Name: LOC144438, dtype: int64

LOC144486
False    183
Name: LOC144486, dtype: int64

LOC144571
False    183
Name: LOC144571, dtype: int64

LOC145474
True     125
False     58
Name: LOC145474, dtype: int64

LOC145783
False    183
Name: LOC145783, dtype: int64

LOC145820
False    182
True       1
Name: LOC145820, dtype: int64

LOC145837
False    180
True       3
Name: LOC145837, dtype: int64

LOC146336
False    181
True       2
Name: LOC146336, dtype: int64

LOC146880
False    183
Name: LOC146880, dtype: int64

LOC147727
False    183
Name: LOC147727, dtype: int64

LOC147804
False    183
Name: LOC147804, dtype: int64

LOC148145
True     123
False     60
Name: LOC148145, dtype: int64

LOC148189
False    183
Name: LOC148189, dtype: int64

LOC148413
False    183
Name: LOC148413, dtype: int64

LOC148696
False    166
True      17
Name: LOC148696, dtype: int64

LOC148709
False    179
True       4
Name: LOC148709, dtype: int64

LOC148824
False    126
True      57
Name: LOC148824, dtype: int64

LOC149134
False    183
Name: LOC149134, dtype: int64

LOC149837
False    183
Name: LOC149837, dtype: int64

LOC150197
False    180
True       3
Name: LOC150197, dtype: int64

LOC150381
False    183
Name: LOC150381, dtype: int64

LOC150622
False    171
True      12
Name: LOC150622, dtype: int64

LOC150776
False    183
Name: LOC150776, dtype: int64

LOC150786
False    183
Name: LOC150786, dtype: int64

LOC151009
False    183
Name: LOC151009, dtype: int64

LOC151162
False    183
Name: LOC151162, dtype: int64

LOC151174
False    180
True       3
Name: LOC151174, dtype: int64

LOC151534
False    183
Name: LOC151534, dtype: int64

LOC152024
True     122
False     61
Name: LOC152024, dtype: int64

LOC152217
False    183
Name: LOC152217, dtype: int64

LOC152225
False    165
True      18
Name: LOC152225, dtype: int64

LOC153328
False    153
True      30
Name: LOC153328, dtype: int64

LOC153684
False    183
Name: LOC153684, dtype: int64

LOC153910
True     117
False     66
Name: LOC153910, dtype: int64

LOC154761
False    183
Name: LOC154761, dtype: int64

LOC154822
False    153
True      30
Name: LOC154822, dtype: int64

LOC157381
False    124
True      59
Name: LOC157381, dtype: int64

LOC157627
True     118
False     65
Name: LOC157627, dtype: int64

LOC158376
False    183
Name: LOC158376, dtype: int64

LOC158572
False    183
Name: LOC158572, dtype: int64

LOC158696
False    153
True      30
Name: LOC158696, dtype: int64

LOC162632
False    183
Name: LOC162632, dtype: int64

LOC168474
False    173
True      10
Name: LOC168474, dtype: int64

LOC200030
False    183
Name: LOC200030, dtype: int64

LOC201651
False    180
True       3
Name: LOC201651, dtype: int64

LOC202181
False    183
Name: LOC202181, dtype: int64

LOC202781
False    183
Name: LOC202781, dtype: int64

LOC219347
False    183
Name: LOC219347, dtype: int64

LOC220429
False    182
True       1
Name: LOC220429, dtype: int64

LOC220594
False    183
Name: LOC220594, dtype: int64

LOC220729
False    183
Name: LOC220729, dtype: int64

LOC220930
False    183
Name: LOC220930, dtype: int64

LOC221442
False    183
Name: LOC221442, dtype: int64

LOC221710
False    183
Name: LOC221710, dtype: int64

LOC222699
False    183
Name: LOC222699, dtype: int64

LOC253039
False    183
Name: LOC253039, dtype: int64

LOC253724
False    181
True       2
Name: LOC253724, dtype: int64

LOC254559
False    182
True       1
Name: LOC254559, dtype: int64

LOC255167
False    180
True       3
Name: LOC255167, dtype: int64

LOC256880
False    180
True       3
Name: LOC256880, dtype: int64

LOC257358
False    176
True       7
Name: LOC257358, dtype: int64

LOC25845
False    183
Name: LOC25845, dtype: int64

LOC26102
False    163
True      20
Name: LOC26102, dtype: int64

LOC282997
False    183
Name: LOC282997, dtype: int64

LOC283050
False    183
Name: LOC283050, dtype: int64

LOC283070
False    183
Name: LOC283070, dtype: int64

LOC283174
False    183
Name: LOC283174, dtype: int64

LOC283267
False    183
Name: LOC283267, dtype: int64

LOC283314
False    183
Name: LOC283314, dtype: int64

LOC283392
False    168
True      15
Name: LOC283392, dtype: int64

LOC283404
False    133
True      50
Name: LOC283404, dtype: int64

LOC283663

False    183
Name: LOC283663, dtype: int64

LOC283731
False    179
True       4
Name: LOC283731, dtype: int64

LOC283856
False    162
True      21
Name: LOC283856, dtype: int64

LOC283867
False    171
True      12
Name: LOC283867, dtype: int64

LOC283922
False    183
Name: LOC283922, dtype: int64

LOC284009
False    128
True      55
Name: LOC284009, dtype: int64

LOC284023
False    183
Name: LOC284023, dtype: int64

LOC284100
False    151
True      32
Name: LOC284100, dtype: int64

LOC284232
False    183
Name: LOC284232, dtype: int64

LOC284233
False    180
True       3
Name: LOC284233, dtype: int64

LOC284276
False    180
True       3
Name: LOC284276, dtype: int64

LOC284440
False    183
Name: LOC284440, dtype: int64

LOC284441
False    183
Name: LOC284441, dtype: int64

LOC284551
False    128
True      55
Name: LOC284551, dtype: int64

LOC284578
False    178
True       5
Name: LOC284578, dtype: int64

LOC284688
False    101
True      82
Name: LOC284688, dtype: int64

LOC284749
False    175
True       8
Name: LOC284749, dtype: int64

LOC284798
False    136
True      47
Name: LOC284798, dtype: int64

LOC284837
False    183
Name: LOC284837, dtype: int64

LOC284900
False    183
Name: LOC284900, dtype: int64

LOC285033
False    183
Name: LOC285033, dtype: int64

LOC285074
False    183
Name: LOC285074, dtype: int64

LOC285205
True     94
False    89
Name: LOC285205, dtype: int64

LOC285359
False    183
Name: LOC285359, dtype: int64

LOC285401
True     116
False     67
Name: LOC285401, dtype: int64

LOC285419
False    183
Name: LOC285419, dtype: int64

LOC285456
False    151
True      32
Name: LOC285456, dtype: int64

LOC285548
False    174
True       9
Name: LOC285548, dtype: int64

LOC285593
False    178
True       5
Name: LOC285593, dtype: int64

LOC285629
False    155
True      28
Name: LOC285629, dtype: int64

LOC285696
False    150
True      33
Name: LOC285696, dtype: int64

LOC285733
False    145
True      38
Name: LOC285733, dtype: int64

LOC285740
False    98
True     85
Name: LOC285740, dtype: int64

LOC285768
False    154
True      29
Name: LOC285768, dtype: int64

LOC285780
True     112
False     71
Name: LOC285780, dtype: int64

LOC285796
False    103
True      80
Name: LOC285796, dtype: int64

LOC285830
False    183
Name: LOC285830, dtype: int64

LOC285847
False    92
True     91
Name: LOC285847, dtype: int64

LOC285954
False    177
True       6
Name: LOC285954, dtype: int64

LOC286002
False    129
True      54
Name: LOC286002, dtype: int64

LOC286367
False    183
Name: LOC286367, dtype: int64

LOC286467
False    179
True       4
Name: LOC286467, dtype: int64

LOC338651
False    180
True       3
Name: LOC338651, dtype: int64

LOC338758
False    183
Name: LOC338758, dtype: int64

LOC338799
False    183
Name: LOC338799, dtype: int64

LOC339047
False    183
Name: LOC339047, dtype: int64

LOC339240
True     105
False     78
Name: LOC339240, dtype: int64

LOC339290
False    183
Name: LOC339290, dtype: int64

LOC339524
False    183
Name: LOC339524, dtype: int64

LOC339535
False    138
True      45
Name: LOC339535, dtype: int64

LOC339674
False    155
True      28
Name: LOC339674, dtype: int64

LOC340508
True     95
False    88
Name: LOC340508, dtype: int64

LOC341056
False    183
Name: LOC341056, dtype: int64

LOC342346
False    161
True      22
Name: LOC342346, dtype: int64

LOC344595
False    183
Name: LOC344595, dtype: int64

LOC344967
False    178
True       5
Name: LOC344967, dtype: int64

LOC347376
True     107
False     76
Name: LOC347376, dtype: int64

LOC348840
True     94
False    89
Name: LOC348840, dtype: int64

LOC348926
False    183
Name: LOC348926, dtype: int64

LOC349114
False    183
Name: LOC349114, dtype: int64

LOC349196
False    182
True       1
Name: LOC349196, dtype: int64

LOC374443
False    183
Name: LOC374443, dtype: int64

LOC374491
False    171
True      12
Name: LOC374491, dtype: int64

LOC375190
False    183
Name: LOC375190, dtype: int64

LOC387646
False    183
Name: LOC387646, dtype: int64

LOC387647
False    183
Name: LOC387647, dtype: int64

LOC388152
False    183
Name: LOC388152, dtype: int64

LOC388242
False    183
Name: LOC388242, dtype: int64

LOC388387
False    148
True      35
Name: LOC388387, dtype: int64

LOC388588
False    182
True       1
Name: LOC388588, dtype: int64

LOC388692
False    183
Name: LOC388692, dtype: int64

LOC388789
False    183
Name: LOC388789, dtype: int64

LOC388796
False    183
Name: LOC388796, dtype: int64

LOC388955
False    183
Name: LOC388955, dtype: int64

LOC389332
False    180
True       3
Name: LOC389332, dtype: int64

LOC389333
False    183
Name: LOC389333, dtype: int64

LOC389458
False    174
True       9
Name: LOC389458, dtype: int64

LOC389493
False    163
True      20
Name: LOC389493, dtype: int64

LOC389634
False    181
True       2
Name: LOC389634, dtype: int64

LOC389705
False    177
True       6
Name: LOC389705, dtype: int64

LOC389791
False    183
Name: LOC389791, dtype: int64

LOC390595
False    181
True       2
Name: LOC390595, dtype: int64

LOC391322
False    158
True      25
Name: LOC391322, dtype: int64

LOC399744
False    183
Name: LOC399744, dtype: int64

LOC399815
False    183
Name: LOC399815, dtype: int64

LOC399959
False    183
Name: LOC399959, dtype: int64

LOC400027
False    183
Name: LOC400027, dtype: int64

LOC400043
False    183
Name: LOC400043, dtype: int64

LOC400657
False    183
Name: LOC400657, dtype: int64

LOC400696
False    128
True      55
Name: LOC400696, dtype: int64

LOC400752
False    183
Name: LOC400752, dtype: int64

LOC400759
False    180
True       3
Name: LOC400759, dtype: int64

LOC400804
False    114
True      69
Name: LOC400804, dtype: int64

LOC400891
True     107
False     76
Name: LOC400891, dtype: int64

LOC400927
False    183
Name: LOC400927, dtype: int64

LOC400931
False    183
Name: LOC400931, dtype: int64

LOC400940
False    126
True      57
Name: LOC400940, dtype: int64

LOC401010
False    183
Name: LOC401010, dtype: int64

LOC401052
False    183
Name: LOC401052, dtype: int64

LOC401093
False    183
Name: LOC401093, dtype: int64

LOC401127
False    182
True       1
Name: LOC401127, dtype: int64

LOC401387
False    143
True      40
Name: LOC401387, dtype: int64

LOC401397
False    183
Name: LOC401397, dtype: int64

LOC401431
False    183
Name: LOC401431, dtype: int64

LOC401463
False    170
True      13
Name: LOC401463, dtype: int64

LOC401588
False    183
Name: LOC401588, dtype: int64

LOC402377
False    179
True       4
Name: LOC402377, dtype: int64

LOC407835
False    183
Name: LOC407835, dtype: int64

LOC440173
False    151
True      32
Name: LOC440173, dtype: int64

LOC440354
False    183
Name: LOC440354, dtype: int64

LOC440356
False    128
True      55
Name: LOC440356, dtype: int64

LOC440461
False    181
True       2
Name: LOC440461, dtype: int64

LOC440563
False    113
True      70
Name: LOC440563, dtype: int64

LOC440896
False    121
True      62
Name: LOC440896, dtype: int64

LOC440905
False    182
True       1
Name: LOC440905, dtype: int64

LOC440925
False    183
Name: LOC440925, dtype: int64

LOC440944
False    183
Name: LOC440944, dtype: int64

LOC440957
False    183
Name: LOC440957, dtype: int64

LOC441046
False    183
Name: LOC441046, dtype: int64

LOC441089
False    183
Name: LOC441089, dtype: int64

LOC441177
False    106
True      77
Name: LOC441177, dtype: int64

LOC441204
False    183
Name: LOC441204, dtype: int64

LOC441208
False    183
Name: LOC441208, dtype: int64

LOC441294
False    183
Name: LOC441294, dtype: int64

LOC441454
False    174
True       9
Name: LOC441454, dtype: int64

LOC441455
False    181
True       2
Name: LOC441455, dtype: int64

LOC441601
False    113
True      70
Name: LOC441601, dtype: int64

LOC441666
False    182
True       1
Name: LOC441666, dtype: int64

LOC441869
False    183
Name: LOC441869, dtype: int64

LOC442308
False    108
True      75
Name: LOC442308, dtype: int64

LOC442421
False    178
True       5
Name: LOC442421, dtype: int64

LOC442454
False    183
Name: LOC442454, dtype: int64

LOC442459
False    161
True      22
Name: LOC442459, dtype: int64

LOC493754
False    183
Name: LOC493754, dtype: int64

LOC541471
False    183
Name: LOC541471, dtype: int64

LOC541473
False    178
True       5
Name: LOC541473, dtype: int64

LOC550112
False    183
Name: LOC550112, dtype: int64

LOC550643
False    183
Name: LOC550643, dtype: int64

LOC554202
False    180
True       3
Name: LOC554202, dtype: int64

LOC55908
False    149
True      34
Name: LOC55908, dtype: int64

LOC572558
False    125
True      58
Name: LOC572558, dtype: int64

LOC595101
False    183
Name: LOC595101, dtype: int64

LOC606724
False    183
Name: LOC606724, dtype: int64

LOC613037
False    175
True       8
Name: LOC613037, dtype: int64

LOC619207
False    183
Name: LOC619207, dtype: int64

LOC641298
False    180
True       3
Name: LOC641298, dtype: int64

LOC641367

False    181
True       2
Name: LOC641367, dtype: int64

LOC642587
False    124
True      59
Name: LOC642587, dtype: int64

LOC642597
False    159
True      24
Name: LOC642597, dtype: int64

LOC642826
False    183
Name: LOC642826, dtype: int64

LOC642846
False    183
Name: LOC642846, dtype: int64

LOC642852
False    183
Name: LOC642852, dtype: int64

LOC643008
False    183
Name: LOC643008, dtype: int64

LOC643387
False    183
Name: LOC643387, dtype: int64

LOC643677
False    158
True      25
Name: LOC643677, dtype: int64

LOC643719
False    181
True       2
Name: LOC643719, dtype: int64

LOC643763
False    177
True       6
Name: LOC643763, dtype: int64

LOC643837
False    183
Name: LOC643837, dtype: int64

LOC644165
False    183
Name: LOC644165, dtype: int64

LOC644172
False    183
Name: LOC644172, dtype: int64

LOC644538
False    183
Name: LOC644538, dtype: int64

LOC644936
False    183
Name: LOC644936, dtype: int64

LOC645166
False    183
Name: LOC645166, dtype: int64

LOC645323
False    147
True      36
Name: LOC645323, dtype: int64

LOC645332
False    183
Name: LOC645332, dtype: int64

LOC645431
False    183
Name: LOC645431, dtype: int64

LOC645676
False    183
Name: LOC645676, dtype: int64

LOC645752
False    108
True      75
Name: LOC645752, dtype: int64

LOC646214
False    183
Name: LOC646214, dtype: int64

LOC646471
False    183
Name: LOC646471, dtype: int64

LOC646627
True     125
False     58
Name: LOC646627, dtype: int64

LOC646762
False    183
Name: LOC646762, dtype: int64

LOC646851
False    183
Name: LOC646851, dtype: int64

LOC646982
False    166
True      17
Name: LOC646982, dtype: int64

LOC646999
False    183
Name: LOC646999, dtype: int64

LOC647121
False    183
Name: LOC647121, dtype: int64

LOC647288
False    183
Name: LOC647288, dtype: int64

LOC647309
False    134
True      49
Name: LOC647309, dtype: int64

LOC647859
False    116
True      67
Name: LOC647859, dtype: int64

LOC647946
False    172
True      11
Name: LOC647946, dtype: int64

LOC647979
False    183
Name: LOC647979, dtype: int64

LOC648740
False    182
True       1
Name: LOC648740, dtype: int64

LOC649330
False    183
Name: LOC649330, dtype: int64

LOC650368
False    183
Name: LOC650368, dtype: int64

LOC650623
False    183
Name: LOC650623, dtype: int64

LOC651250
False    183
Name: LOC651250, dtype: int64

LOC652276
False    183
Name: LOC652276, dtype: int64

LOC653113
False    183
Name: LOC653113, dtype: int64

LOC653501
False    183
Name: LOC653501, dtype: int64

LOC653566
False    183
Name: LOC653566, dtype: int64

LOC653653
False    183
Name: LOC653653, dtype: int64

LOC653786
False    180
True       3
Name: LOC653786, dtype: int64

LOC654342
False    183
Name: LOC654342, dtype: int64

LOC654433
False    183
Name: LOC654433, dtype: int64

LOC678655
False    183
Name: LOC678655, dtype: int64

LOC723809
False    175
True       8
Name: LOC723809, dtype: int64

LOC723972
False    183
Name: LOC723972, dtype: int64

LOC727896
False    183
Name: LOC727896, dtype: int64

LOC728024
False    183
Name: LOC728024, dtype: int64

LOC728190
False    183
Name: LOC728190, dtype: int64

LOC728264
False    183
Name: LOC728264, dtype: int64

LOC728323
False    183
Name: LOC728323, dtype: int64

LOC728392
False    183
Name: LOC728392, dtype: int64

LOC728554
False    183
Name: LOC728554, dtype: int64

LOC728606
False    160
True      23
Name: LOC728606, dtype: int64

LOC728613
False    183
Name: LOC728613, dtype: int64

LOC728640
False    183
Name: LOC728640, dtype: int64

LOC728643
False    183
Name: LOC728643, dtype: int64

LOC728723
False    183
Name: LOC728723, dtype: int64

LOC728743
False    183
Name: LOC728743, dtype: int64

LOC728758
False    183
Name: LOC728758, dtype: int64

LOC728819
False    181
True       2
Name: LOC728819, dtype: int64

LOC728855
False    183
Name: LOC728855, dtype: int64

LOC728875
False    183
Name: LOC728875, dtype: int64

LOC728989
False    176
True       7
Name: LOC728989, dtype: int64

LOC729020
False    183
Name: LOC729020, dtype: int64

LOC729082
False    183
Name: LOC729082, dtype: int64

LOC729156
False    145
True      38
Name: LOC729156, dtype: int64

LOC729176
False    183
Name: LOC729176, dtype: int64

LOC729234
False    183
Name: LOC729234, dtype: int64

LOC729375
False    183
Name: LOC729375, dtype: int64

LOC729467
True     105
False     78
Name: LOC729467, dtype: int64

LOC729603
False    183
Name: LOC729603, dtype: int64

LOC729668
True     110
False     73
Name: LOC729668, dtype: int64

LOC729678
False    183
Name: LOC729678, dtype: int64

LOC729799
False    183
Name: LOC729799, dtype: int64

LOC729991-MEF2B
False    182
True       1
Name: LOC729991-MEF2B, dtype: int64

LOC729991
False    183
Name: LOC729991, dtype: int64

LOC730101
False    183
Name: LOC730101, dtype: int64

LOC730668
False    173
True      10
Name: LOC730668, dtype: int64

LOC731779
False    106
True      77
Name: LOC731779, dtype: int64

LOC731789
True     115
False     68
Name: LOC731789, dtype: int64

LOC80054
False    183
Name: LOC80054, dtype: int64

LOC80154
False    183
Name: LOC80154, dtype: int64

LOC81691
False    183
Name: LOC81691, dtype: int64

LOC84740
False    183
Name: LOC84740, dtype: int64

LOC84856
False    183
Name: LOC84856, dtype: int64

LOC84931
True     92
False    91
Name: LOC84931, dtype: int64

LOC84989
False    183
Name: LOC84989, dtype: int64

LOC90110
False    183
Name: LOC90110, dtype: int64

LOC90246
False    182
True       1
Name: LOC90246, dtype: int64

LOC90586
False    173
True      10
Name: LOC90586, dtype: int64

LOC90784
False    183
Name: LOC90784, dtype: int64

LOC90834
False    183
Name: LOC90834, dtype: int64

LOC91149
True     101
False     82
Name: LOC91149, dtype: int64

LOC91316
False    183
Name: LOC91316, dtype: int64

LOC91450
False    182
True       1
Name: LOC91450, dtype: int64

LOC91948
False    105
True      78
Name: LOC91948, dtype: int64

LOC92249
False    183
Name: LOC92249, dtype: int64

LOC92659
False    183
Name: LOC92659, dtype: int64

LOC92973
False    183
Name: LOC92973, dtype: int64

LOC93432
False    164
True      19
Name: LOC93432, dtype: int64

LOC93622
False    183
Name: LOC93622, dtype: int64

LOC96610
False    183
Name: LOC96610, dtype: int64

LOH12CR1
False    183
Name: LOH12CR1, dtype: int64

LOH12CR2
False    183
Name: LOH12CR2, dtype: int64

LOH3CR2A
False    183
Name: LOH3CR2A, dtype: int64

LONP1
False    183
Name: LONP1, dtype: int64

LONP2
False    183
Name: LONP2, dtype: int64

LONRF1
False    183
Name: LONRF1, dtype: int64

LONRF2
False    183
Name: LONRF2, dtype: int64

LONRF3
False    183
Name: LONRF3, dtype: int64

LOR
True     96
False    87
Name: LOR, dtype: int64

LOXHD1
False    176
True       7
Name: LOXHD1, dtype: int64

LOXL1
False    183
Name: LOXL1, dtype: int64

LOXL2
False    183
Name: LOXL2, dtype: int64

LOXL3
False    183
Name: LOXL3, dtype: int64

LOXL4
False    183
Name: LOXL4, dtype: int64

LOX
False    183
Name: LOX, dtype: int64

LPAL2
False    179
True       4
Name: LPAL2, dtype: int64

LPAR1
False    183
Name: LPAR1, dtype: int64

LPAR2
False    183
Name: LPAR2, dtype: int64

LPAR3
False    170
True      13
Name: LPAR3, dtype: int64

LPAR4
False    179
True       4
Name: LPAR4, dtype: int64

LPAR5
False    183
Name: LPAR5, dtype: int64

LPAR6
False    183
Name: LPAR6, dtype: int64

LPA
False    127
True      56
Name: LPA, dtype: int64

LPCAT1
False    183
Name: LPCAT1, dtype: int64

LPCAT2
False    183
Name: LPCAT2, dtype: int64

LPCAT3
False    183
Name: LPCAT3, dtype: int64

LPCAT4
False    183
Name: LPCAT4, dtype: int64

LPGAT1
False    183
Name: LPGAT1, dtype: int64

LPHN1
False    183
Name: LPHN1, dtype: int64

LPHN2
False    183
Name: LPHN2, dtype: int64

LPHN3
False    183
Name: LPHN3, dtype: int64

LPIN1
False    183
Name: LPIN1, dtype: int64

LPIN2
False    183
Name: LPIN2, dtype: int64

LPIN3
False    183
Name: LPIN3, dtype: int64

LPL
False    183
Name: LPL, dtype: int64

LPO
False    158
True      25
Name: LPO, dtype: int64

LPPR1
False    175
True       8
Name: LPPR1, dtype: int64

LPPR2
False    183
Name: LPPR2, dtype: int64

LPPR3
False    166
True      17
Name: LPPR3, dtype: int64

LPPR4
False    183
Name: LPPR4, dtype: int64

LPPR5
False    174
True       9
Name: LPPR5, dtype: int64

LPP
False    183
Name: LPP, dtype: int64

LPXN

False    183
Name: LPXN, dtype: int64

LQK1
False    183
Name: LQK1, dtype: int64

LRAT
False    181
True       2
Name: LRAT, dtype: int64

LRBA
False    183
Name: LRBA, dtype: int64

LRCH1
False    183
Name: LRCH1, dtype: int64

LRCH2
False    183
Name: LRCH2, dtype: int64

LRCH3
False    183
Name: LRCH3, dtype: int64

LRCH4
False    183
Name: LRCH4, dtype: int64

LRDD
False    183
Name: LRDD, dtype: int64

LRFN1
False    183
Name: LRFN1, dtype: int64

LRFN2
False    165
True      18
Name: LRFN2, dtype: int64

LRFN3
False    183
Name: LRFN3, dtype: int64

LRFN4
False    183
Name: LRFN4, dtype: int64

LRFN5
False    182
True       1
Name: LRFN5, dtype: int64

LRG1
False    183
Name: LRG1, dtype: int64

LRGUK
False    182
True       1
Name: LRGUK, dtype: int64

LRIG1
False    183
Name: LRIG1, dtype: int64

LRIG2
False    183
Name: LRIG2, dtype: int64

LRIG3
False    183
Name: LRIG3, dtype: int64

LRIT3
False    182
True       1
Name: LRIT3, dtype: int64

LRMP
False    183
Name: LRMP, dtype: int64

LRP10
False    183
Name: LRP10, dtype: int64

LRP11
False    183
Name: LRP11, dtype: int64

LRP12
False    183
Name: LRP12, dtype: int64

LRP1B
False    174
True       9
Name: LRP1B, dtype: int64

LRP1
False    183
Name: LRP1, dtype: int64

LRP2BP
False    183
Name: LRP2BP, dtype: int64

LRP2
False    142
True      41
Name: LRP2, dtype: int64

LRP3
False    183
Name: LRP3, dtype: int64

LRP4
False    183
Name: LRP4, dtype: int64

LRP5L
False    183
Name: LRP5L, dtype: int64

LRP5
False    183
Name: LRP5, dtype: int64

LRP6
False    183
Name: LRP6, dtype: int64

LRP8
False    183
Name: LRP8, dtype: int64

LRPAP1
False    183
Name: LRPAP1, dtype: int64

LRPPRC
False    183
Name: LRPPRC, dtype: int64

LRRC10B
False    183
Name: LRRC10B, dtype: int64

LRRC14B
True     111
False     72
Name: LRRC14B, dtype: int64

LRRC14
False    183
Name: LRRC14, dtype: int64

LRRC15
False    181
True       2
Name: LRRC15, dtype: int64

LRRC16A
False    183
Name: LRRC16A, dtype: int64

LRRC16B
False    183
Name: LRRC16B, dtype: int64

LRRC17
False    183
Name: LRRC17, dtype: int64

LRRC18
False    149
True      34
Name: LRRC18, dtype: int64

LRRC19
False    179
True       4
Name: LRRC19, dtype: int64

LRRC1
False    183
Name: LRRC1, dtype: int64

LRRC20
False    183
Name: LRRC20, dtype: int64

LRRC23
False    183
Name: LRRC23, dtype: int64

LRRC24
False    176
True       7
Name: LRRC24, dtype: int64

LRRC25
False    183
Name: LRRC25, dtype: int64

LRRC26
False    144
True      39
Name: LRRC26, dtype: int64

LRRC27
False    183
Name: LRRC27, dtype: int64

LRRC28
False    183
Name: LRRC28, dtype: int64

LRRC29
False    183
Name: LRRC29, dtype: int64

LRRC2
False    183
Name: LRRC2, dtype: int64

LRRC31
False    168
True      15
Name: LRRC31, dtype: int64

LRRC32
False    183
Name: LRRC32, dtype: int64

LRRC33
False    183
Name: LRRC33, dtype: int64

LRRC34
False    183
Name: LRRC34, dtype: int64

LRRC36
False    183
Name: LRRC36, dtype: int64

LRRC37A2
False    183
Name: LRRC37A2, dtype: int64

LRRC37A3
False    183
Name: LRRC37A3, dtype: int64

LRRC37A4
False    183
Name: LRRC37A4, dtype: int64

LRRC37A
False    183
Name: LRRC37A, dtype: int64

LRRC37B2
False    183
Name: LRRC37B2, dtype: int64

LRRC37B
False    183
Name: LRRC37B, dtype: int64

LRRC39
False    180
True       3
Name: LRRC39, dtype: int64

LRRC3B
False    114
True      69
Name: LRRC3B, dtype: int64

LRRC3
False    183
Name: LRRC3, dtype: int64

LRRC40
False    183
Name: LRRC40, dtype: int64

LRRC41
False    183
Name: LRRC41, dtype: int64

LRRC42
False    183
Name: LRRC42, dtype: int64

LRRC43
False    180
True       3
Name: LRRC43, dtype: int64

LRRC45
False    183
Name: LRRC45, dtype: int64

LRRC46
False    183
Name: LRRC46, dtype: int64

LRRC47
False    183
Name: LRRC47, dtype: int64

LRRC48
False    183
Name: LRRC48, dtype: int64

LRRC49
False    183
Name: LRRC49, dtype: int64

LRRC4B
False    183
Name: LRRC4B, dtype: int64

LRRC4C
False    182
True       1
Name: LRRC4C, dtype: int64

LRRC4
False    183
Name: LRRC4, dtype: int64

LRRC50
False    177
True       6
Name: LRRC50, dtype: int64

LRRC55
False    181
True       2
Name: LRRC55, dtype: int64

LRRC56
False    183
Name: LRRC56, dtype: int64

LRRC57
False    183
Name: LRRC57, dtype: int64

LRRC58
False    183
Name: LRRC58, dtype: int64

LRRC59
False    183
Name: LRRC59, dtype: int64

LRRC61
False    183
Name: LRRC61, dtype: int64

LRRC66
False    183
Name: LRRC66, dtype: int64

LRRC67
False    93
True     90
Name: LRRC67, dtype: int64

LRRC69
False    178
True       5
Name: LRRC69, dtype: int64

LRRC6
False    183
Name: LRRC6, dtype: int64

LRRC70
False    183
Name: LRRC70, dtype: int64

LRRC7
False    157
True      26
Name: LRRC7, dtype: int64

LRRC8A
False    183
Name: LRRC8A, dtype: int64

LRRC8B
False    183
Name: LRRC8B, dtype: int64

LRRC8C
False    183
Name: LRRC8C, dtype: int64

LRRC8D
False    183
Name: LRRC8D, dtype: int64

LRRC8E
False    183
Name: LRRC8E, dtype: int64

LRRCC1
False    183
Name: LRRCC1, dtype: int64

LRRFIP1
False    183
Name: LRRFIP1, dtype: int64

LRRFIP2
False    183
Name: LRRFIP2, dtype: int64

LRRIQ1
False    178
True       5
Name: LRRIQ1, dtype: int64

LRRIQ3
False    180
True       3
Name: LRRIQ3, dtype: int64

LRRIQ4
False    162
True      21
Name: LRRIQ4, dtype: int64

LRRK1
False    183
Name: LRRK1, dtype: int64

LRRK2
False    183
Name: LRRK2, dtype: int64

LRRN1
False    183
Name: LRRN1, dtype: int64

LRRN2
False    183
Name: LRRN2, dtype: int64

LRRN3
False    183
Name: LRRN3, dtype: int64

LRRN4CL
False    183
Name: LRRN4CL, dtype: int64

LRRN4
False    182
True       1
Name: LRRN4, dtype: int64

LRRTM1
False    172
True      11
Name: LRRTM1, dtype: int64

LRRTM2
False    181
True       2
Name: LRRTM2, dtype: int64

LRRTM3
False    164
True      19
Name: LRRTM3, dtype: int64

LRRTM4
False    176
True       7
Name: LRRTM4, dtype: int64

LRSAM1
False    183
Name: LRSAM1, dtype: int64

LRTM2
True     97
False    86
Name: LRTM2, dtype: int64

LRTOMT
False    183
Name: LRTOMT, dtype: int64

LRWD1
False    183
Name: LRWD1, dtype: int64

LSAMP
False    183
Name: LSAMP, dtype: int64

LSG1
False    183
Name: LSG1, dtype: int64

LSM10
False    183
Name: LSM10, dtype: int64

LSM11
False    183
Name: LSM11, dtype: int64

LSM12
False    183
Name: LSM12, dtype: int64

LSM14A
False    183
Name: LSM14A, dtype: int64

LSM14B
False    183
Name: LSM14B, dtype: int64

LSM1
False    183
Name: LSM1, dtype: int64

LSM2
False    183
Name: LSM2, dtype: int64

LSM3
False    183
Name: LSM3, dtype: int64

LSM4
False    183
Name: LSM4, dtype: int64

LSM5
False    183
Name: LSM5, dtype: int64

LSM6
False    183
Name: LSM6, dtype: int64

LSM7
False    183
Name: LSM7, dtype: int64

LSMD1
False    183
Name: LSMD1, dtype: int64

LSP1
False    183
Name: LSP1, dtype: int64

LSR
False    183
Name: LSR, dtype: int64

LSS
False    183
Name: LSS, dtype: int64

LST-3TM12
False    92
True     91
Name: LST-3TM12, dtype: int64

LST1
False    183
Name: LST1, dtype: int64

LTA4H
False    183
Name: LTA4H, dtype: int64

LTA
False    183
Name: LTA, dtype: int64

LTB4R2
False    183
Name: LTB4R2, dtype: int64

LTB4R
False    183
Name: LTB4R, dtype: int64

LTBP1
False    183
Name: LTBP1, dtype: int64

LTBP2
False    183
Name: LTBP2, dtype: int64

LTBP3
False    183
Name: LTBP3, dtype: int64

LTBP4
False    183
Name: LTBP4, dtype: int64

LTBR
False    183
Name: LTBR, dtype: int64

LTB
False    183
Name: LTB, dtype: int64

LTC4S
False    183
Name: LTC4S, dtype: int64

LTF
False    182
True       1
Name: LTF, dtype: int64

LTK
False    182
True       1
Name: LTK, dtype: int64

LTV1
False    183
Name: LTV1, dtype: int64

LUC7L2
False    183
Name: LUC7L2, dtype: int64

LUC7L3
False    183
Name: LUC7L3, dtype: int64

LUC7L
False    183
Name: LUC7L, dtype: int64

LUM
False    183
Name: LUM, dtype: int64

LUZP1
False    183
Name: LUZP1, dtype: int64

LUZP2
False    180
True       3
Name: LUZP2, dtype: int64

LUZP6
False    183
Name: LUZP6, dtype: int64

LXN
False    183
Name: LXN, dtype: int64

LY6D
False    172
True      11
Name: LY6D, dtype: int64

LY6E
False    183
Name: LY6E, dtype: int64

LY6G5B
False    183
Name: LY6G5B, dtype: int64

LY6G5C
False    183
Name: LY6G5C, dtype: int64

LY6G6C
False    164
True      19
Name: LY6G6C, dtype: int64

LY6H
False    182
True       1
Name: LY6H, dtype: int64

LY6K

False    178
True       5
Name: LY6K, dtype: int64

LY75
False    183
Name: LY75, dtype: int64

LY86
False    183
Name: LY86, dtype: int64

LY96
False    182
True       1
Name: LY96, dtype: int64

LY9
False    182
True       1
Name: LY9, dtype: int64

LYAR
False    183
Name: LYAR, dtype: int64

LYG1
False    181
True       2
Name: LYG1, dtype: int64

LYG2
True     112
False     71
Name: LYG2, dtype: int64

LYL1
False    183
Name: LYL1, dtype: int64

LYNX1
False    183
Name: LYNX1, dtype: int64

LYN
False    183
Name: LYN, dtype: int64

LYPD1
False    183
Name: LYPD1, dtype: int64

LYPD2
False    146
True      37
Name: LYPD2, dtype: int64

LYPD3
False    183
Name: LYPD3, dtype: int64

LYPD5
False    183
Name: LYPD5, dtype: int64

LYPD6B
False    183
Name: LYPD6B, dtype: int64

LYPD6
False    182
True       1
Name: LYPD6, dtype: int64

LYPLA1
False    183
Name: LYPLA1, dtype: int64

LYPLA2P1
False    183
Name: LYPLA2P1, dtype: int64

LYPLA2
False    183
Name: LYPLA2, dtype: int64

LYPLAL1
False    183
Name: LYPLAL1, dtype: int64

LYRM1
False    183
Name: LYRM1, dtype: int64

LYRM2
False    183
Name: LYRM2, dtype: int64

LYRM4
False    183
Name: LYRM4, dtype: int64

LYRM5
False    183
Name: LYRM5, dtype: int64

LYRM7
False    183
Name: LYRM7, dtype: int64

LYSMD1
False    183
Name: LYSMD1, dtype: int64

LYSMD2
False    183
Name: LYSMD2, dtype: int64

LYSMD3
False    183
Name: LYSMD3, dtype: int64

LYSMD4
False    183
Name: LYSMD4, dtype: int64

LYST
False    183
Name: LYST, dtype: int64

LYVE1
False    183
Name: LYVE1, dtype: int64

LYZ
False    183
Name: LYZ, dtype: int64

LZIC
False    183
Name: LZIC, dtype: int64

LZTFL1
False    183
Name: LZTFL1, dtype: int64

LZTR1
False    183
Name: LZTR1, dtype: int64

LZTS1
False    183
Name: LZTS1, dtype: int64

LZTS2
False    183
Name: LZTS2, dtype: int64

M6PR
False    183
Name: M6PR, dtype: int64

MAB21L1
False    180
True       3
Name: MAB21L1, dtype: int64

MAB21L2
False    179
True       4
Name: MAB21L2, dtype: int64

MACC1
False    183
Name: MACC1, dtype: int64

MACF1
False    183
Name: MACF1, dtype: int64

MACROD1
False    183
Name: MACROD1, dtype: int64

MACROD2
False    183
Name: MACROD2, dtype: int64

MAD1L1
False    183
Name: MAD1L1, dtype: int64

MAD2L1BP
False    183
Name: MAD2L1BP, dtype: int64

MAD2L1
False    183
Name: MAD2L1, dtype: int64

MAD2L2
False    183
Name: MAD2L2, dtype: int64

MADCAM1
False    182
True       1
Name: MADCAM1, dtype: int64

MADD
False    183
Name: MADD, dtype: int64

MAEA
False    183
Name: MAEA, dtype: int64

MAEL
False    178
True       5
Name: MAEL, dtype: int64

MAF1
False    183
Name: MAF1, dtype: int64

MAFA
False    146
True      37
Name: MAFA, dtype: int64

MAFB
False    183
Name: MAFB, dtype: int64

MAFF
False    183
Name: MAFF, dtype: int64

MAFG
False    183
Name: MAFG, dtype: int64

MAFK
False    183
Name: MAFK, dtype: int64

MAF
False    183
Name: MAF, dtype: int64

MAGEA12
True     99
False    84
Name: MAGEA12, dtype: int64

MAGEA5
False    108
True      75
Name: MAGEA5, dtype: int64

MAGEA8
True     110
False     73
Name: MAGEA8, dtype: int64

MAGEC3
True     115
False     68
Name: MAGEC3, dtype: int64

MAGED1
False    183
Name: MAGED1, dtype: int64

MAGED2
False    183
Name: MAGED2, dtype: int64

MAGED4B
False    183
Name: MAGED4B, dtype: int64

MAGED4
False    183
Name: MAGED4, dtype: int64

MAGEE1
False    183
Name: MAGEE1, dtype: int64

MAGEE2
False    166
True      17
Name: MAGEE2, dtype: int64

MAGEF1
False    183
Name: MAGEF1, dtype: int64

MAGEH1
False    183
Name: MAGEH1, dtype: int64

MAGEL2
False    183
Name: MAGEL2, dtype: int64

MAGI1
False    183
Name: MAGI1, dtype: int64

MAGI2
False    183
Name: MAGI2, dtype: int64

MAGI3
False    183
Name: MAGI3, dtype: int64

MAGIX
False    183
Name: MAGIX, dtype: int64

MAGOHB
False    183
Name: MAGOHB, dtype: int64

MAGOH
False    183
Name: MAGOH, dtype: int64

MAGT1
False    183
Name: MAGT1, dtype: int64

MAG
False    124
True      59
Name: MAG, dtype: int64

MAK16
False    183
Name: MAK16, dtype: int64

MAK
False    183
Name: MAK, dtype: int64

MAL2
False    183
Name: MAL2, dtype: int64

MALAT1
False    183
Name: MALAT1, dtype: int64

MALL
False    183
Name: MALL, dtype: int64

MALT1
False    183
Name: MALT1, dtype: int64

MAL
False    181
True       2
Name: MAL, dtype: int64

MAMDC2
False    183
Name: MAMDC2, dtype: int64

MAMDC4
False    183
Name: MAMDC4, dtype: int64

MAML1
False    183
Name: MAML1, dtype: int64

MAML2
False    183
Name: MAML2, dtype: int64

MAML3
False    183
Name: MAML3, dtype: int64

MAMLD1
False    183
Name: MAMLD1, dtype: int64

MAMSTR
False    183
Name: MAMSTR, dtype: int64

MAN1A1
False    183
Name: MAN1A1, dtype: int64

MAN1A2
False    183
Name: MAN1A2, dtype: int64

MAN1B1
False    183
Name: MAN1B1, dtype: int64

MAN1C1
False    183
Name: MAN1C1, dtype: int64

MAN2A1
False    183
Name: MAN2A1, dtype: int64

MAN2A2
False    183
Name: MAN2A2, dtype: int64

MAN2B1
False    183
Name: MAN2B1, dtype: int64

MAN2B2
False    183
Name: MAN2B2, dtype: int64

MAN2C1
False    183
Name: MAN2C1, dtype: int64

MANBAL
False    183
Name: MANBAL, dtype: int64

MANBA
False    183
Name: MANBA, dtype: int64

MANEAL
False    183
Name: MANEAL, dtype: int64

MANEA
False    183
Name: MANEA, dtype: int64

MANF
False    183
Name: MANF, dtype: int64

MANSC1
False    183
Name: MANSC1, dtype: int64

MAOA
False    183
Name: MAOA, dtype: int64

MAOB
False    183
Name: MAOB, dtype: int64

MAP1A
False    183
Name: MAP1A, dtype: int64

MAP1B
False    183
Name: MAP1B, dtype: int64

MAP1D
False    183
Name: MAP1D, dtype: int64

MAP1LC3A
False    183
Name: MAP1LC3A, dtype: int64

MAP1LC3B2
False    183
Name: MAP1LC3B2, dtype: int64

MAP1LC3B
False    183
Name: MAP1LC3B, dtype: int64

MAP1LC3C
False    174
True       9
Name: MAP1LC3C, dtype: int64

MAP1S
False    183
Name: MAP1S, dtype: int64

MAP2K1
False    183
Name: MAP2K1, dtype: int64

MAP2K2
False    183
Name: MAP2K2, dtype: int64

MAP2K3
False    183
Name: MAP2K3, dtype: int64

MAP2K4
False    183
Name: MAP2K4, dtype: int64

MAP2K5
False    183
Name: MAP2K5, dtype: int64

MAP2K6
False    183
Name: MAP2K6, dtype: int64

MAP2K7
False    183
Name: MAP2K7, dtype: int64

MAP2
False    183
Name: MAP2, dtype: int64

MAP3K10
False    183
Name: MAP3K10, dtype: int64

MAP3K11
False    183
Name: MAP3K11, dtype: int64

MAP3K12
False    183
Name: MAP3K12, dtype: int64

MAP3K13
False    183
Name: MAP3K13, dtype: int64

MAP3K14
False    183
Name: MAP3K14, dtype: int64

MAP3K15
False    164
True      19
Name: MAP3K15, dtype: int64

MAP3K1
False    183
Name: MAP3K1, dtype: int64

MAP3K2
False    183
Name: MAP3K2, dtype: int64

MAP3K3
False    183
Name: MAP3K3, dtype: int64

MAP3K4
False    183
Name: MAP3K4, dtype: int64

MAP3K5
False    183
Name: MAP3K5, dtype: int64

MAP3K6
False    183
Name: MAP3K6, dtype: int64

MAP3K7
False    183
Name: MAP3K7, dtype: int64

MAP3K8
False    183
Name: MAP3K8, dtype: int64

MAP3K9
False    183
Name: MAP3K9, dtype: int64

MAP4K1
False    183
Name: MAP4K1, dtype: int64

MAP4K2
False    183
Name: MAP4K2, dtype: int64

MAP4K3
False    183
Name: MAP4K3, dtype: int64

MAP4K4
False    183
Name: MAP4K4, dtype: int64

MAP4K5
False    183
Name: MAP4K5, dtype: int64

MAP4
False    183
Name: MAP4, dtype: int64

MAP6D1
False    183
Name: MAP6D1, dtype: int64

MAP6
False    183
Name: MAP6, dtype: int64

MAP7D1
False    183
Name: MAP7D1, dtype: int64

MAP7D2
False    183
Name: MAP7D2, dtype: int64

MAP7D3
False    183
Name: MAP7D3, dtype: int64

MAP7
False    183
Name: MAP7, dtype: int64

MAP9
False    183
Name: MAP9, dtype: int64

MAPK10
False    183
Name: MAPK10, dtype: int64

MAPK11
False    183
Name: MAPK11, dtype: int64

MAPK12
False    183
Name: MAPK12, dtype: int64

MAPK13
False    183
Name: MAPK13, dtype: int64

MAPK14
False    183
Name: MAPK14, dtype: int64

MAPK15
False    183
Name: MAPK15, dtype: int64

MAPK1IP1L
False    183
Name: MAPK1IP1L, dtype: int64

MAPK1
False    183
Name: MAPK1, dtype: int64

MAPK3
False    183
Name: MAPK3, dtype: int64

MAPK4
False    182
True       1
Name: MAPK4, dtype: int64

MAPK6
False    183
Name: MAPK6, dtype: int64

MAPK7
False    183
Name: MAPK7, dtype: int64

MAPK8IP1
False    183
Name: MAPK8IP1, dtype: int64

MAPK8IP2
False    183
Name: MAPK8IP2, dtype: int64

MAPK8IP3
False    183
Name: MAPK8IP3, dtype: int64

MAPK8
False    183
Name: MAPK8, dtype: int64

MAPK9
False    183
Name: MAPK9, dtype: int64

MAPKAP1
False    183
Name: MAPKAP1, dtype: int64

MAPKAPK2
False    183
Name: MAPKAPK2, dtype: int64

MAPKAPK3
False    183
Name: MAPKAPK3, dtype: int64

MAPKAPK5
False    183
Name: MAPKAPK5, dtype: int64

MAPKBP1
False    183
Name: MAPKBP1, dtype: int64

MAPKSP1
False    183
Name: MAPKSP1, dtype: int64

MAPRE1
False    183
Name: MAPRE1, dtype: int64

MAPRE2

False    183
Name: MAPRE2, dtype: int64

MAPRE3
False    183
Name: MAPRE3, dtype: int64

MAPT
False    183
Name: MAPT, dtype: int64

MARCH10
False    170
True      13
Name: MARCH10, dtype: int64

MARCH11
False    96
True     87
Name: MARCH11, dtype: int64

MARCH1
False    183
Name: MARCH1, dtype: int64

MARCH2
False    183
Name: MARCH2, dtype: int64

MARCH3
False    183
Name: MARCH3, dtype: int64

MARCH4
False    183
Name: MARCH4, dtype: int64

MARCH5
False    183
Name: MARCH5, dtype: int64

MARCH6
False    183
Name: MARCH6, dtype: int64

MARCH7
False    183
Name: MARCH7, dtype: int64

MARCH8
False    183
Name: MARCH8, dtype: int64

MARCH9
False    183
Name: MARCH9, dtype: int64

MARCKSL1
False    183
Name: MARCKSL1, dtype: int64

MARCKS
False    183
Name: MARCKS, dtype: int64

MARCO
False    183
Name: MARCO, dtype: int64

MARK1
False    183
Name: MARK1, dtype: int64

MARK2
False    183
Name: MARK2, dtype: int64

MARK3
False    183
Name: MARK3, dtype: int64

MARK4
False    183
Name: MARK4, dtype: int64

MARS2
False    183
Name: MARS2, dtype: int64

MARS
False    183
Name: MARS, dtype: int64

MARVELD1
False    183
Name: MARVELD1, dtype: int64

MARVELD2
False    183
Name: MARVELD2, dtype: int64

MARVELD3
False    183
Name: MARVELD3, dtype: int64

MAS1L
False    102
True      81
Name: MAS1L, dtype: int64

MASP1
False    182
True       1
Name: MASP1, dtype: int64

MASP2
False    183
Name: MASP2, dtype: int64

MAST1
False    183
Name: MAST1, dtype: int64

MAST2
False    183
Name: MAST2, dtype: int64

MAST3
False    183
Name: MAST3, dtype: int64

MAST4
False    183
Name: MAST4, dtype: int64

MASTL
False    183
Name: MASTL, dtype: int64

MAT1A
False    179
True       4
Name: MAT1A, dtype: int64

MAT2A
False    183
Name: MAT2A, dtype: int64

MAT2B
False    183
Name: MAT2B, dtype: int64

MATK
False    183
Name: MATK, dtype: int64

MATN1
False    175
True       8
Name: MATN1, dtype: int64

MATN2
False    183
Name: MATN2, dtype: int64

MATN3
False    183
Name: MATN3, dtype: int64

MATN4
False    170
True      13
Name: MATN4, dtype: int64

MATR3
False    183
Name: MATR3, dtype: int64

MAVS
False    183
Name: MAVS, dtype: int64

MAX
False    183
Name: MAX, dtype: int64

MAZ
False    183
Name: MAZ, dtype: int64

MBD1
False    183
Name: MBD1, dtype: int64

MBD2
False    183
Name: MBD2, dtype: int64

MBD3L1
True     126
False     57
Name: MBD3L1, dtype: int64

MBD3
False    183
Name: MBD3, dtype: int64

MBD4
False    183
Name: MBD4, dtype: int64

MBD5
False    183
Name: MBD5, dtype: int64

MBD6
False    183
Name: MBD6, dtype: int64

MBIP
False    183
Name: MBIP, dtype: int64

MBL1P
False    181
True       2
Name: MBL1P, dtype: int64

MBLAC1
False    183
Name: MBLAC1, dtype: int64

MBLAC2
False    183
Name: MBLAC2, dtype: int64

MBNL1
False    183
Name: MBNL1, dtype: int64

MBNL2
False    183
Name: MBNL2, dtype: int64

MBNL3
False    183
Name: MBNL3, dtype: int64

MBOAT1
False    183
Name: MBOAT1, dtype: int64

MBOAT2
False    183
Name: MBOAT2, dtype: int64

MBOAT4
False    183
Name: MBOAT4, dtype: int64

MBOAT7
False    183
Name: MBOAT7, dtype: int64

MBP
False    183
Name: MBP, dtype: int64

MBTD1
False    183
Name: MBTD1, dtype: int64

MBTPS1
False    183
Name: MBTPS1, dtype: int64

MBTPS2
False    183
Name: MBTPS2, dtype: int64

MB
False    180
True       3
Name: MB, dtype: int64

MC1R
False    183
Name: MC1R, dtype: int64

MC2R
False    147
True      36
Name: MC2R, dtype: int64

MC4R
False    112
True      71
Name: MC4R, dtype: int64

MC5R
False    129
True      54
Name: MC5R, dtype: int64

MCAM
False    183
Name: MCAM, dtype: int64

MCART1
False    183
Name: MCART1, dtype: int64

MCART2
False    182
True       1
Name: MCART2, dtype: int64

MCART3P
False    101
True      82
Name: MCART3P, dtype: int64

MCART6
False    183
Name: MCART6, dtype: int64

MCAT
False    183
Name: MCAT, dtype: int64

MCCC1
False    183
Name: MCCC1, dtype: int64

MCCC2
False    183
Name: MCCC2, dtype: int64

MCC
False    183
Name: MCC, dtype: int64

MCEE
False    183
Name: MCEE, dtype: int64

MCF2L2
False    183
Name: MCF2L2, dtype: int64

MCF2L
False    183
Name: MCF2L, dtype: int64

MCF2
False    161
True      22
Name: MCF2, dtype: int64

MCFD2
False    183
Name: MCFD2, dtype: int64

MCHR1
False    178
True       5
Name: MCHR1, dtype: int64

MCL1
False    183
Name: MCL1, dtype: int64

MCM10
False    183
Name: MCM10, dtype: int64

MCM2
False    183
Name: MCM2, dtype: int64

MCM3APAS
False    183
Name: MCM3APAS, dtype: int64

MCM3AP
False    183
Name: MCM3AP, dtype: int64

MCM3
False    183
Name: MCM3, dtype: int64

MCM4
False    183
Name: MCM4, dtype: int64

MCM5
False    183
Name: MCM5, dtype: int64

MCM6
False    183
Name: MCM6, dtype: int64

MCM7
False    183
Name: MCM7, dtype: int64

MCM8
False    183
Name: MCM8, dtype: int64

MCM9
False    183
Name: MCM9, dtype: int64

MCOLN1
False    183
Name: MCOLN1, dtype: int64

MCOLN2
False    183
Name: MCOLN2, dtype: int64

MCOLN3
False    183
Name: MCOLN3, dtype: int64

MCPH1
False    183
Name: MCPH1, dtype: int64

MCRS1
False    183
Name: MCRS1, dtype: int64

MCTP1
False    183
Name: MCTP1, dtype: int64

MCTP2
False    183
Name: MCTP2, dtype: int64

MCTS1
False    183
Name: MCTS1, dtype: int64

MDC1
False    183
Name: MDC1, dtype: int64

MDFIC
False    183
Name: MDFIC, dtype: int64

MDFI
False    183
Name: MDFI, dtype: int64

MDGA1
False    183
Name: MDGA1, dtype: int64

MDGA2
True     93
False    90
Name: MDGA2, dtype: int64

MDH1B
False    183
Name: MDH1B, dtype: int64

MDH1
False    183
Name: MDH1, dtype: int64

MDH2
False    183
Name: MDH2, dtype: int64

MDK
False    183
Name: MDK, dtype: int64

MDM1
False    183
Name: MDM1, dtype: int64

MDM2
False    183
Name: MDM2, dtype: int64

MDM4
False    183
Name: MDM4, dtype: int64

MDN1
False    183
Name: MDN1, dtype: int64

MDP1
False    183
Name: MDP1, dtype: int64

MDS2
False    132
True      51
Name: MDS2, dtype: int64

ME1
False    183
Name: ME1, dtype: int64

ME2
False    183
Name: ME2, dtype: int64

ME3
False    183
Name: ME3, dtype: int64

MEA1
False    183
Name: MEA1, dtype: int64

MEAF6
False    183
Name: MEAF6, dtype: int64

MECOM
False    183
Name: MECOM, dtype: int64

MECP2
False    183
Name: MECP2, dtype: int64

MECR
False    183
Name: MECR, dtype: int64

MED10
False    183
Name: MED10, dtype: int64

MED11
False    183
Name: MED11, dtype: int64

MED12L
False    180
True       3
Name: MED12L, dtype: int64

MED12
False    183
Name: MED12, dtype: int64

MED13L
False    183
Name: MED13L, dtype: int64

MED13
False    183
Name: MED13, dtype: int64

MED14
False    183
Name: MED14, dtype: int64

MED15
False    183
Name: MED15, dtype: int64

MED16
False    183
Name: MED16, dtype: int64

MED17
False    183
Name: MED17, dtype: int64

MED18
False    183
Name: MED18, dtype: int64

MED19
False    183
Name: MED19, dtype: int64

MED1
False    183
Name: MED1, dtype: int64

MED20
False    183
Name: MED20, dtype: int64

MED21
False    183
Name: MED21, dtype: int64

MED22
False    183
Name: MED22, dtype: int64

MED23
False    183
Name: MED23, dtype: int64

MED24
False    183
Name: MED24, dtype: int64

MED25
False    183
Name: MED25, dtype: int64

MED26
False    183
Name: MED26, dtype: int64

MED27
False    183
Name: MED27, dtype: int64

MED28
False    183
Name: MED28, dtype: int64

MED29
False    183
Name: MED29, dtype: int64

MED30
False    183
Name: MED30, dtype: int64

MED31
False    183
Name: MED31, dtype: int64

MED4
False    183
Name: MED4, dtype: int64

MED6
False    183
Name: MED6, dtype: int64

MED7
False    183
Name: MED7, dtype: int64

MED8
False    183
Name: MED8, dtype: int64

MED9
False    183
Name: MED9, dtype: int64

MEF2A
False    183
Name: MEF2A, dtype: int64

MEF2B
False    182
True       1
Name: MEF2B, dtype: int64

MEF2C
False    183
Name: MEF2C, dtype: int64

MEF2D
False    183
Name: MEF2D, dtype: int64

MEFV
False    181
True       2
Name: MEFV, dtype: int64

MEG3
False    183
Name: MEG3, dtype: int64

MEG8
False    94
True     89
Name: MEG8, dtype: int64

MEGF10
False    182
True       1
Name: MEGF10, dtype: int64

MEGF11
False    182
True       1
Name: MEGF11, dtype: int64

MEGF6
False    183
Name: MEGF6, dtype: int64

MEGF8
False    183
Name: MEGF8, dtype: int64

MEGF9
False    183
Name: MEGF9, dtype: int64

MEI1

False    183
Name: MEI1, dtype: int64

MEIG1
False    142
True      41
Name: MEIG1, dtype: int64

MEIS1
False    183
Name: MEIS1, dtype: int64

MEIS2
False    183
Name: MEIS2, dtype: int64

MEIS3P1
False    183
Name: MEIS3P1, dtype: int64

MEIS3
False    183
Name: MEIS3, dtype: int64

MELK
False    183
Name: MELK, dtype: int64

MEMO1
False    183
Name: MEMO1, dtype: int64

MEN1
False    183
Name: MEN1, dtype: int64

MEOX1
False    183
Name: MEOX1, dtype: int64

MEOX2
False    180
True       3
Name: MEOX2, dtype: int64

MEP1A
False    169
True      14
Name: MEP1A, dtype: int64

MEP1B
False    134
True      49
Name: MEP1B, dtype: int64

MEPCE
False    183
Name: MEPCE, dtype: int64

MEPE
False    101
True      82
Name: MEPE, dtype: int64

MERTK
False    183
Name: MERTK, dtype: int64

MESDC1
False    183
Name: MESDC1, dtype: int64

MESDC2
False    183
Name: MESDC2, dtype: int64

MESP1
False    183
Name: MESP1, dtype: int64

MESP2
False    182
True       1
Name: MESP2, dtype: int64

MESTIT1
False    170
True      13
Name: MESTIT1, dtype: int64

MEST
False    183
Name: MEST, dtype: int64

METAP1
False    183
Name: METAP1, dtype: int64

METAP2
False    183
Name: METAP2, dtype: int64

METRNL
False    183
Name: METRNL, dtype: int64

METRN
False    183
Name: METRN, dtype: int64

METT10D
False    183
Name: METT10D, dtype: int64

METT11D1
False    183
Name: METT11D1, dtype: int64

METT5D1
False    183
Name: METT5D1, dtype: int64

METTL10
False    183
Name: METTL10, dtype: int64

METTL11A
False    183
Name: METTL11A, dtype: int64

METTL11B
False    134
True      49
Name: METTL11B, dtype: int64

METTL12
False    183
Name: METTL12, dtype: int64

METTL13
False    183
Name: METTL13, dtype: int64

METTL14
False    183
Name: METTL14, dtype: int64

METTL1
False    183
Name: METTL1, dtype: int64

METTL2A
False    183
Name: METTL2A, dtype: int64

METTL2B
False    183
Name: METTL2B, dtype: int64

METTL3
False    183
Name: METTL3, dtype: int64

METTL4
False    183
Name: METTL4, dtype: int64

METTL5
False    183
Name: METTL5, dtype: int64

METTL6
False    183
Name: METTL6, dtype: int64

METTL7A
False    183
Name: METTL7A, dtype: int64

METTL7B
False    183
Name: METTL7B, dtype: int64

METTL8
False    183
Name: METTL8, dtype: int64

METTL9
False    183
Name: METTL9, dtype: int64

MET
False    183
Name: MET, dtype: int64

MEX3A
False    183
Name: MEX3A, dtype: int64

MEX3B
False    183
Name: MEX3B, dtype: int64

MEX3C
False    183
Name: MEX3C, dtype: int64

MEX3D
False    183
Name: MEX3D, dtype: int64

MFAP1
False    183
Name: MFAP1, dtype: int64

MFAP2
False    183
Name: MFAP2, dtype: int64

MFAP3L
False    183
Name: MFAP3L, dtype: int64

MFAP3
False    183
Name: MFAP3, dtype: int64

MFAP4
False    183
Name: MFAP4, dtype: int64

MFAP5
False    182
True       1
Name: MFAP5, dtype: int64

MFF
False    183
Name: MFF, dtype: int64

MFGE8
False    183
Name: MFGE8, dtype: int64

MFHAS1
False    183
Name: MFHAS1, dtype: int64

MFI2
False    183
Name: MFI2, dtype: int64

MFN1
False    183
Name: MFN1, dtype: int64

MFN2
False    183
Name: MFN2, dtype: int64

MFNG
False    183
Name: MFNG, dtype: int64

MFRP
False    183
Name: MFRP, dtype: int64

MFSD10
False    183
Name: MFSD10, dtype: int64

MFSD11
False    183
Name: MFSD11, dtype: int64

MFSD1
False    183
Name: MFSD1, dtype: int64

MFSD2A
False    183
Name: MFSD2A, dtype: int64

MFSD2B
False    183
Name: MFSD2B, dtype: int64

MFSD3
False    183
Name: MFSD3, dtype: int64

MFSD4
False    183
Name: MFSD4, dtype: int64

MFSD5
False    183
Name: MFSD5, dtype: int64

MFSD6L
False    182
True       1
Name: MFSD6L, dtype: int64

MFSD6
False    183
Name: MFSD6, dtype: int64

MFSD7
False    183
Name: MFSD7, dtype: int64

MFSD8
False    183
Name: MFSD8, dtype: int64

MFSD9
False    183
Name: MFSD9, dtype: int64

MGAM
False    183
Name: MGAM, dtype: int64

MGAT1
False    183
Name: MGAT1, dtype: int64

MGAT2
False    183
Name: MGAT2, dtype: int64

MGAT3
False    183
Name: MGAT3, dtype: int64

MGAT4A
False    183
Name: MGAT4A, dtype: int64

MGAT4B
False    183
Name: MGAT4B, dtype: int64

MGAT4C
False    153
True      30
Name: MGAT4C, dtype: int64

MGAT5B
False    183
Name: MGAT5B, dtype: int64

MGAT5
False    183
Name: MGAT5, dtype: int64

MGA
False    183
Name: MGA, dtype: int64

MGC12916
False    182
True       1
Name: MGC12916, dtype: int64

MGC12982
False    183
Name: MGC12982, dtype: int64

MGC14436
False    160
True      23
Name: MGC14436, dtype: int64

MGC16025
False    152
True      31
Name: MGC16025, dtype: int64

MGC16121
False    183
Name: MGC16121, dtype: int64

MGC16142
False    183
Name: MGC16142, dtype: int64

MGC16275
False    183
Name: MGC16275, dtype: int64

MGC16384
False    181
True       2
Name: MGC16384, dtype: int64

MGC16703
False    180
True       3
Name: MGC16703, dtype: int64

MGC21881
False    183
Name: MGC21881, dtype: int64

MGC23270
False    183
Name: MGC23270, dtype: int64

MGC23284
False    183
Name: MGC23284, dtype: int64

MGC27382
False    104
True      79
Name: MGC27382, dtype: int64

MGC2752
False    183
Name: MGC2752, dtype: int64

MGC2889
False    119
True      64
Name: MGC2889, dtype: int64

MGC29506
False    183
Name: MGC29506, dtype: int64

MGC3771
False    183
Name: MGC3771, dtype: int64

MGC42105
False    183
Name: MGC42105, dtype: int64

MGC4473
True     95
False    88
Name: MGC4473, dtype: int64

MGC45800
False    179
True       4
Name: MGC45800, dtype: int64

MGC57346
False    183
Name: MGC57346, dtype: int64

MGC70857
False    183
Name: MGC70857, dtype: int64

MGC72080
False    183
Name: MGC72080, dtype: int64

MGC87042
False    183
Name: MGC87042, dtype: int64

MGEA5
False    183
Name: MGEA5, dtype: int64

MGLL
False    183
Name: MGLL, dtype: int64

MGMT
False    183
Name: MGMT, dtype: int64

MGP
False    183
Name: MGP, dtype: int64

MGRN1
False    183
Name: MGRN1, dtype: int64

MGST1
False    183
Name: MGST1, dtype: int64

MGST2
False    183
Name: MGST2, dtype: int64

MGST3
False    183
Name: MGST3, dtype: int64

MIA2
False    179
True       4
Name: MIA2, dtype: int64

MIA3
False    183
Name: MIA3, dtype: int64

MIAT
False    183
Name: MIAT, dtype: int64

MIA
False    183
Name: MIA, dtype: int64

MIB1
False    183
Name: MIB1, dtype: int64

MIB2
False    183
Name: MIB2, dtype: int64

MICAL1
False    183
Name: MICAL1, dtype: int64

MICAL2
False    183
Name: MICAL2, dtype: int64

MICAL3
False    183
Name: MICAL3, dtype: int64

MICALCL
False    182
True       1
Name: MICALCL, dtype: int64

MICALL1
False    183
Name: MICALL1, dtype: int64

MICALL2
False    183
Name: MICALL2, dtype: int64

MICA
False    183
Name: MICA, dtype: int64

MICB
False    183
Name: MICB, dtype: int64

MID1IP1
False    183
Name: MID1IP1, dtype: int64

MID1
False    183
Name: MID1, dtype: int64

MID2
False    183
Name: MID2, dtype: int64

MIDN
False    183
Name: MIDN, dtype: int64

MIER1
False    183
Name: MIER1, dtype: int64

MIER2
False    183
Name: MIER2, dtype: int64

MIER3
False    183
Name: MIER3, dtype: int64

MIF4GD
False    183
Name: MIF4GD, dtype: int64

MIF
False    183
Name: MIF, dtype: int64

MIIP
False    183
Name: MIIP, dtype: int64

MIMT1
False    104
True      79
Name: MIMT1, dtype: int64

MINA
False    183
Name: MINA, dtype: int64

MINK1
False    183
Name: MINK1, dtype: int64

MINPP1
False    183
Name: MINPP1, dtype: int64

MIOS
False    183
Name: MIOS, dtype: int64

MIOX
False    178
True       5
Name: MIOX, dtype: int64

MIPEP
False    183
Name: MIPEP, dtype: int64

MIPOL1
False    183
Name: MIPOL1, dtype: int64

MIP
False    138
True      45
Name: MIP, dtype: int64

MIR155HG
False    183
Name: MIR155HG, dtype: int64

MIR17HG
False    183
Name: MIR17HG, dtype: int64

MIS12
False    183
Name: MIS12, dtype: int64

MITD1
False    183
Name: MITD1, dtype: int64

MITF
False    183
Name: MITF, dtype: int64

MIXL1
False    99
True     84
Name: MIXL1, dtype: int64

MKI67IP
False    183
Name: MKI67IP, dtype: int64

MKI67
False    183
Name: MKI67, dtype: int64

MKKS
False    183
Name: MKKS, dtype: int64

MKL1
False    183
Name: MKL1, dtype: int64

MKL2
False    183
Name: MKL2, dtype: int64

MKLN1
False    183
Name: MKLN1, dtype: int64

MKNK1
False    183
Name: MKNK1, dtype: int64

MKNK2
False    183
Name: MKNK2, dtype: int64

MKRN1
False    183
Name: MKRN1, dtype: int64

MKRN2
False    183
Name: MKRN2, dtype: int64

MKRN3
False    147
True      36
Name: MKRN3, dtype: int64

MKS1
False    183
Name: MKS1, dtype: int64

MKX
False    181
True       2
Name: MKX, dtype: int64

MLANA
False    150
True      33
Name: MLANA, dtype: int64

MLC1

False    182
True       1
Name: MLC1, dtype: int64

MLEC
False    183
Name: MLEC, dtype: int64

MLF1IP
False    183
Name: MLF1IP, dtype: int64

MLF1
False    183
Name: MLF1, dtype: int64

MLF2
False    183
Name: MLF2, dtype: int64

MLH1
False    183
Name: MLH1, dtype: int64

MLH3
False    183
Name: MLH3, dtype: int64

MLKL
False    183
Name: MLKL, dtype: int64

MLL2
False    183
Name: MLL2, dtype: int64

MLL3
False    183
Name: MLL3, dtype: int64

MLL4
False    183
Name: MLL4, dtype: int64

MLL5
False    183
Name: MLL5, dtype: int64

MLLT10
False    183
Name: MLLT10, dtype: int64

MLLT11
False    183
Name: MLLT11, dtype: int64

MLLT1
False    183
Name: MLLT1, dtype: int64

MLLT3
False    183
Name: MLLT3, dtype: int64

MLLT4
False    183
Name: MLLT4, dtype: int64

MLLT6
False    183
Name: MLLT6, dtype: int64

MLL
False    183
Name: MLL, dtype: int64

MLNR
True     114
False     69
Name: MLNR, dtype: int64

MLPH
False    183
Name: MLPH, dtype: int64

MLST8
False    183
Name: MLST8, dtype: int64

MLXIPL
False    183
Name: MLXIPL, dtype: int64

MLXIP
False    183
Name: MLXIP, dtype: int64

MLX
False    183
Name: MLX, dtype: int64

MLYCD
False    183
Name: MLYCD, dtype: int64

MMAA
False    183
Name: MMAA, dtype: int64

MMAB
False    183
Name: MMAB, dtype: int64

MMACHC
False    183
Name: MMACHC, dtype: int64

MMADHC
False    183
Name: MMADHC, dtype: int64

MMD2
True     118
False     65
Name: MMD2, dtype: int64

MMD
False    183
Name: MMD, dtype: int64

MMEL1
False    181
True       2
Name: MMEL1, dtype: int64

MME
False    183
Name: MME, dtype: int64

MMGT1
False    183
Name: MMGT1, dtype: int64

MMP10
False    181
True       2
Name: MMP10, dtype: int64

MMP11
False    183
Name: MMP11, dtype: int64

MMP12
False    183
Name: MMP12, dtype: int64

MMP13
False    175
True       8
Name: MMP13, dtype: int64

MMP14
False    183
Name: MMP14, dtype: int64

MMP15
False    183
Name: MMP15, dtype: int64

MMP16
False    183
Name: MMP16, dtype: int64

MMP17
False    183
Name: MMP17, dtype: int64

MMP19
False    183
Name: MMP19, dtype: int64

MMP1
False    183
Name: MMP1, dtype: int64

MMP21
False    152
True      31
Name: MMP21, dtype: int64

MMP23A
True     120
False     63
Name: MMP23A, dtype: int64

MMP23B
False    183
Name: MMP23B, dtype: int64

MMP24
False    183
Name: MMP24, dtype: int64

MMP25
False    183
Name: MMP25, dtype: int64

MMP28
False    183
Name: MMP28, dtype: int64

MMP2
False    183
Name: MMP2, dtype: int64

MMP3
False    178
True       5
Name: MMP3, dtype: int64

MMP7
False    181
True       2
Name: MMP7, dtype: int64

MMP8
False    158
True      25
Name: MMP8, dtype: int64

MMP9
False    183
Name: MMP9, dtype: int64

MMRN1
False    183
Name: MMRN1, dtype: int64

MMRN2
False    183
Name: MMRN2, dtype: int64

MMS19
False    183
Name: MMS19, dtype: int64

MN1
False    183
Name: MN1, dtype: int64

MNAT1
False    183
Name: MNAT1, dtype: int64

MND1
False    183
Name: MND1, dtype: int64

MNDA
False    183
Name: MNDA, dtype: int64

MNS1
False    183
Name: MNS1, dtype: int64

MNT
False    183
Name: MNT, dtype: int64

MNX1
False    182
True       1
Name: MNX1, dtype: int64

MOAP1
False    183
Name: MOAP1, dtype: int64

MOB2
False    183
Name: MOB2, dtype: int64

MOBKL1A
False    183
Name: MOBKL1A, dtype: int64

MOBKL1B
False    183
Name: MOBKL1B, dtype: int64

MOBKL2A
False    183
Name: MOBKL2A, dtype: int64

MOBKL2B
False    183
Name: MOBKL2B, dtype: int64

MOBKL2C
False    183
Name: MOBKL2C, dtype: int64

MOBKL3
False    183
Name: MOBKL3, dtype: int64

MOBP
False    154
True      29
Name: MOBP, dtype: int64

MOCOS
False    183
Name: MOCOS, dtype: int64

MOCS1
False    183
Name: MOCS1, dtype: int64

MOCS2
False    183
Name: MOCS2, dtype: int64

MOCS3
False    183
Name: MOCS3, dtype: int64

MOGAT1
False    150
True      33
Name: MOGAT1, dtype: int64

MOGAT2
False    163
True      20
Name: MOGAT2, dtype: int64

MOGAT3
False    151
True      32
Name: MOGAT3, dtype: int64

MOGS
False    183
Name: MOGS, dtype: int64

MOG
True     114
False     69
Name: MOG, dtype: int64

MON1A
False    183
Name: MON1A, dtype: int64

MON1B
False    183
Name: MON1B, dtype: int64

MON2
False    183
Name: MON2, dtype: int64

MORC2
False    183
Name: MORC2, dtype: int64

MORC3
False    183
Name: MORC3, dtype: int64

MORC4
False    183
Name: MORC4, dtype: int64

MORF4L1
False    183
Name: MORF4L1, dtype: int64

MORF4L2
False    183
Name: MORF4L2, dtype: int64

MORF4
False    177
True       6
Name: MORF4, dtype: int64

MORN1
False    183
Name: MORN1, dtype: int64

MORN2
False    183
Name: MORN2, dtype: int64

MORN3
False    183
Name: MORN3, dtype: int64

MORN4
False    183
Name: MORN4, dtype: int64

MORN5
False    152
True      31
Name: MORN5, dtype: int64

MOSC1
False    183
Name: MOSC1, dtype: int64

MOSC2
False    183
Name: MOSC2, dtype: int64

MOSPD1
False    183
Name: MOSPD1, dtype: int64

MOSPD2
False    183
Name: MOSPD2, dtype: int64

MOSPD3
False    183
Name: MOSPD3, dtype: int64

MOV10L1
False    182
True       1
Name: MOV10L1, dtype: int64

MOV10
False    183
Name: MOV10, dtype: int64

MOXD1
False    183
Name: MOXD1, dtype: int64

MPDU1
False    183
Name: MPDU1, dtype: int64

MPDZ
False    183
Name: MPDZ, dtype: int64

MPEG1
False    183
Name: MPEG1, dtype: int64

MPG
False    183
Name: MPG, dtype: int64

MPHOSPH10
False    183
Name: MPHOSPH10, dtype: int64

MPHOSPH6
False    183
Name: MPHOSPH6, dtype: int64

MPHOSPH8
False    183
Name: MPHOSPH8, dtype: int64

MPHOSPH9
False    183
Name: MPHOSPH9, dtype: int64

MPI
False    183
Name: MPI, dtype: int64

MPL
False    183
Name: MPL, dtype: int64

MPND
False    183
Name: MPND, dtype: int64

MPO
False    179
True       4
Name: MPO, dtype: int64

MPP1
False    183
Name: MPP1, dtype: int64

MPP2
False    183
Name: MPP2, dtype: int64

MPP3
False    183
Name: MPP3, dtype: int64

MPP4
False    163
True      20
Name: MPP4, dtype: int64

MPP5
False    183
Name: MPP5, dtype: int64

MPP6
False    182
True       1
Name: MPP6, dtype: int64

MPP7
False    183
Name: MPP7, dtype: int64

MPPE1
False    183
Name: MPPE1, dtype: int64

MPPED1
False    112
True      71
Name: MPPED1, dtype: int64

MPPED2
False    183
Name: MPPED2, dtype: int64

MPRIP
False    183
Name: MPRIP, dtype: int64

MPST
False    183
Name: MPST, dtype: int64

MPV17L2
False    183
Name: MPV17L2, dtype: int64

MPV17L
False    183
Name: MPV17L, dtype: int64

MPV17
False    183
Name: MPV17, dtype: int64

MPZL1
False    183
Name: MPZL1, dtype: int64

MPZL2
False    183
Name: MPZL2, dtype: int64

MPZL3
False    182
True       1
Name: MPZL3, dtype: int64

MPZ
False    183
Name: MPZ, dtype: int64

MR1
False    183
Name: MR1, dtype: int64

MRAP2
False    183
Name: MRAP2, dtype: int64

MRAP
True     121
False     62
Name: MRAP, dtype: int64

MRAS
False    183
Name: MRAS, dtype: int64

MRC1
False    183
Name: MRC1, dtype: int64

MRC2
False    183
Name: MRC2, dtype: int64

MRE11A
False    183
Name: MRE11A, dtype: int64

MREG
False    183
Name: MREG, dtype: int64

MRFAP1L1
False    183
Name: MRFAP1L1, dtype: int64

MRFAP1
False    183
Name: MRFAP1, dtype: int64

MRGPRE
False    141
True      42
Name: MRGPRE, dtype: int64

MRGPRF
False    183
Name: MRGPRF, dtype: int64

MRI1
False    183
Name: MRI1, dtype: int64

MRM1
False    183
Name: MRM1, dtype: int64

MRO
False    183
Name: MRO, dtype: int64

MRP63
False    183
Name: MRP63, dtype: int64

MRPL10
False    183
Name: MRPL10, dtype: int64

MRPL11
False    183
Name: MRPL11, dtype: int64

MRPL12
False    183
Name: MRPL12, dtype: int64

MRPL13
False    183
Name: MRPL13, dtype: int64

MRPL14
False    183
Name: MRPL14, dtype: int64

MRPL15
False    183
Name: MRPL15, dtype: int64

MRPL16
False    183
Name: MRPL16, dtype: int64

MRPL17
False    183
Name: MRPL17, dtype: int64

MRPL18
False    183
Name: MRPL18, dtype: int64

MRPL19
False    183
Name: MRPL19, dtype: int64

MRPL1
False    183
Name: MRPL1, dtype: int64

MRPL20
False    183
Name: MRPL20, dtype: int64

MRPL21
False    183
Name: MRPL21, dtype: int64

MRPL22
False    183
Name: MRPL22, dtype: int64

MRPL23
False    183
Name: MRPL23, dtype: int64

MRPL24
False    183
Name: MRPL24, dtype: int64

MRPL27
False    183
Name: MRPL27, dtype: int64

MRPL28
False    183
Name: MRPL28, dtype: int64

MRPL2
False    183
Name: MRPL2, dtype: int64

MRPL30
False    183
Name: MRPL30, dtype: int64

MRPL32
False    183
Name: MRPL32, dtype: int64

MRPL33
False    183
Name: MRPL33, dtype: int64

MRPL34
False    183
Name: MRPL34, dtype: int64

MRPL35
False    183
Name: MRPL35, dtype: int64

MRPL36
False    183
Name: MRPL36, dtype: int64

MRPL37
False    183
Name: MRPL37, dtype: int64

MRPL38
False    183
Name: MRPL38, dtype: int64

MRPL39
False    183
Name: MRPL39, dtype: int64

MRPL3
False    183
Name: MRPL3, dtype: int64

MRPL40
False    183
Name: MRPL40, dtype: int64

MRPL41
False    183
Name: MRPL41, dtype: int64

MRPL42P5
False    181
True       2
Name: MRPL42P5, dtype: int64

MRPL42
False    183
Name: MRPL42, dtype: int64

MRPL43
False    183
Name: MRPL43, dtype: int64

MRPL44
False    183
Name: MRPL44, dtype: int64

MRPL45
False    183
Name: MRPL45, dtype: int64

MRPL46
False    183
Name: MRPL46, dtype: int64

MRPL47
False    183
Name: MRPL47, dtype: int64

MRPL48
False    183
Name: MRPL48, dtype: int64

MRPL49

False    183
Name: MRPL49, dtype: int64

MRPL4
False    183
Name: MRPL4, dtype: int64

MRPL50
False    183
Name: MRPL50, dtype: int64

MRPL51
False    183
Name: MRPL51, dtype: int64

MRPL52
False    183
Name: MRPL52, dtype: int64

MRPL53
False    183
Name: MRPL53, dtype: int64

MRPL54
False    183
Name: MRPL54, dtype: int64

MRPL55
False    183
Name: MRPL55, dtype: int64

MRPL9
False    183
Name: MRPL9, dtype: int64

MRPS10
False    183
Name: MRPS10, dtype: int64

MRPS11
False    183
Name: MRPS11, dtype: int64

MRPS12
False    183
Name: MRPS12, dtype: int64

MRPS14
False    183
Name: MRPS14, dtype: int64

MRPS15
False    183
Name: MRPS15, dtype: int64

MRPS16
False    183
Name: MRPS16, dtype: int64

MRPS17
False    183
Name: MRPS17, dtype: int64

MRPS18A
False    183
Name: MRPS18A, dtype: int64

MRPS18B
False    183
Name: MRPS18B, dtype: int64

MRPS18C
False    183
Name: MRPS18C, dtype: int64

MRPS21
False    183
Name: MRPS21, dtype: int64

MRPS22
False    183
Name: MRPS22, dtype: int64

MRPS23
False    183
Name: MRPS23, dtype: int64

MRPS24
False    183
Name: MRPS24, dtype: int64

MRPS25
False    183
Name: MRPS25, dtype: int64

MRPS26
False    183
Name: MRPS26, dtype: int64

MRPS27
False    183
Name: MRPS27, dtype: int64

MRPS28
False    183
Name: MRPS28, dtype: int64

MRPS2
False    183
Name: MRPS2, dtype: int64

MRPS30
False    183
Name: MRPS30, dtype: int64

MRPS31
False    183
Name: MRPS31, dtype: int64

MRPS33
False    183
Name: MRPS33, dtype: int64

MRPS34
False    183
Name: MRPS34, dtype: int64

MRPS35
False    183
Name: MRPS35, dtype: int64

MRPS36
False    183
Name: MRPS36, dtype: int64

MRPS5
False    183
Name: MRPS5, dtype: int64

MRPS6
False    183
Name: MRPS6, dtype: int64

MRPS7
False    183
Name: MRPS7, dtype: int64

MRPS9
False    183
Name: MRPS9, dtype: int64

MRRF
False    183
Name: MRRF, dtype: int64

MRS2P2
False    168
True      15
Name: MRS2P2, dtype: int64

MRS2
False    183
Name: MRS2, dtype: int64

MRTO4
False    183
Name: MRTO4, dtype: int64

MRVI1
False    183
Name: MRVI1, dtype: int64

MS4A10
True     118
False     65
Name: MS4A10, dtype: int64

MS4A14
False    182
True       1
Name: MS4A14, dtype: int64

MS4A15
False    124
True      59
Name: MS4A15, dtype: int64

MS4A1
False    179
True       4
Name: MS4A1, dtype: int64

MS4A2
False    182
True       1
Name: MS4A2, dtype: int64

MS4A3
True     111
False     72
Name: MS4A3, dtype: int64

MS4A4A
False    183
Name: MS4A4A, dtype: int64

MS4A6A
False    183
Name: MS4A6A, dtype: int64

MS4A6E
True     123
False     60
Name: MS4A6E, dtype: int64

MS4A7
False    183
Name: MS4A7, dtype: int64

MS4A8B
False    180
True       3
Name: MS4A8B, dtype: int64

MSC
False    183
Name: MSC, dtype: int64

MSH2
False    183
Name: MSH2, dtype: int64

MSH3
False    183
Name: MSH3, dtype: int64

MSH4
False    143
True      40
Name: MSH4, dtype: int64

MSH5
False    183
Name: MSH5, dtype: int64

MSH6
False    183
Name: MSH6, dtype: int64

MSI1
False    182
True       1
Name: MSI1, dtype: int64

MSI2
False    183
Name: MSI2, dtype: int64

MSL1
False    183
Name: MSL1, dtype: int64

MSL2
False    183
Name: MSL2, dtype: int64

MSL3L2
False    183
Name: MSL3L2, dtype: int64

MSL3
False    183
Name: MSL3, dtype: int64

MSLNL
False    140
True      43
Name: MSLNL, dtype: int64

MSLN
False    182
True       1
Name: MSLN, dtype: int64

MSMB
False    159
True      24
Name: MSMB, dtype: int64

MSMP
False    183
Name: MSMP, dtype: int64

MSN
False    183
Name: MSN, dtype: int64

MSR1
False    183
Name: MSR1, dtype: int64

MSRA
False    183
Name: MSRA, dtype: int64

MSRB2
False    183
Name: MSRB2, dtype: int64

MSRB3
False    183
Name: MSRB3, dtype: int64

MST1P2
False    183
Name: MST1P2, dtype: int64

MST1P9
False    183
Name: MST1P9, dtype: int64

MST1R
False    183
Name: MST1R, dtype: int64

MST1
False    183
Name: MST1, dtype: int64

MST4
False    183
Name: MST4, dtype: int64

MSTN
False    176
True       7
Name: MSTN, dtype: int64

MSTO1
False    183
Name: MSTO1, dtype: int64

MSTO2P
False    183
Name: MSTO2P, dtype: int64

MSX1
False    183
Name: MSX1, dtype: int64

MSX2P1
False    173
True      10
Name: MSX2P1, dtype: int64

MSX2
False    183
Name: MSX2, dtype: int64

MT1A
False    182
True       1
Name: MT1A, dtype: int64

MT1DP
False    166
True      17
Name: MT1DP, dtype: int64

MT1E
False    183
Name: MT1E, dtype: int64

MT1F
False    183
Name: MT1F, dtype: int64

MT1G
False    183
Name: MT1G, dtype: int64

MT1H
False    177
True       6
Name: MT1H, dtype: int64

MT1L
False    183
Name: MT1L, dtype: int64

MT1M
False    183
Name: MT1M, dtype: int64

MT1X
False    183
Name: MT1X, dtype: int64

MT2A
False    183
Name: MT2A, dtype: int64

MT3
False    167
True      16
Name: MT3, dtype: int64

MTA1
False    183
Name: MTA1, dtype: int64

MTA2
False    183
Name: MTA2, dtype: int64

MTA3
False    183
Name: MTA3, dtype: int64

MTAP
False    183
Name: MTAP, dtype: int64

MTBP
False    183
Name: MTBP, dtype: int64

MTCH1
False    183
Name: MTCH1, dtype: int64

MTCH2
False    183
Name: MTCH2, dtype: int64

MTCP1NB
False    183
Name: MTCP1NB, dtype: int64

MTCP1
False    183
Name: MTCP1, dtype: int64

MTDH
False    183
Name: MTDH, dtype: int64

MTERFD1
False    183
Name: MTERFD1, dtype: int64

MTERFD2
False    183
Name: MTERFD2, dtype: int64

MTERFD3
False    183
Name: MTERFD3, dtype: int64

MTERF
False    183
Name: MTERF, dtype: int64

MTF1
False    183
Name: MTF1, dtype: int64

MTF2
False    183
Name: MTF2, dtype: int64

MTFMT
False    183
Name: MTFMT, dtype: int64

MTFR1
False    183
Name: MTFR1, dtype: int64

MTG1
False    183
Name: MTG1, dtype: int64

MTHFD1L
False    183
Name: MTHFD1L, dtype: int64

MTHFD1
False    183
Name: MTHFD1, dtype: int64

MTHFD2L
False    183
Name: MTHFD2L, dtype: int64

MTHFD2
False    183
Name: MTHFD2, dtype: int64

MTHFR
False    183
Name: MTHFR, dtype: int64

MTHFSD
False    183
Name: MTHFSD, dtype: int64

MTHFS
False    183
Name: MTHFS, dtype: int64

MTIF2
False    183
Name: MTIF2, dtype: int64

MTIF3
False    183
Name: MTIF3, dtype: int64

MTL5
False    183
Name: MTL5, dtype: int64

MTM1
False    183
Name: MTM1, dtype: int64

MTMR10
False    183
Name: MTMR10, dtype: int64

MTMR11
False    183
Name: MTMR11, dtype: int64

MTMR12
False    183
Name: MTMR12, dtype: int64

MTMR14
False    183
Name: MTMR14, dtype: int64

MTMR15
False    183
Name: MTMR15, dtype: int64

MTMR1
False    183
Name: MTMR1, dtype: int64

MTMR2
False    183
Name: MTMR2, dtype: int64

MTMR3
False    183
Name: MTMR3, dtype: int64

MTMR4
False    183
Name: MTMR4, dtype: int64

MTMR6
False    183
Name: MTMR6, dtype: int64

MTMR7
False    183
Name: MTMR7, dtype: int64

MTMR8
False    182
True       1
Name: MTMR8, dtype: int64

MTMR9L
False    183
Name: MTMR9L, dtype: int64

MTMR9
False    183
Name: MTMR9, dtype: int64

MTNR1A
False    136
True      47
Name: MTNR1A, dtype: int64

MTO1
False    183
Name: MTO1, dtype: int64

MTOR
False    183
Name: MTOR, dtype: int64

MTP18
False    183
Name: MTP18, dtype: int64

MTPAP
False    183
Name: MTPAP, dtype: int64

MTRF1L
False    183
Name: MTRF1L, dtype: int64

MTRF1
False    183
Name: MTRF1, dtype: int64

MTRR
False    183
Name: MTRR, dtype: int64

MTR
False    183
Name: MTR, dtype: int64

MTSS1L
False    183
Name: MTSS1L, dtype: int64

MTSS1
False    183
Name: MTSS1, dtype: int64

MTTP
False    158
True      25
Name: MTTP, dtype: int64

MTUS1
False    183
Name: MTUS1, dtype: int64

MTUS2
False    183
Name: MTUS2, dtype: int64

MTVR2
True     103
False     80
Name: MTVR2, dtype: int64

MTX1
False    183
Name: MTX1, dtype: int64

MTX2
False    183
Name: MTX2, dtype: int64

MTX3
False    183
Name: MTX3, dtype: int64

MUC12
False    183
Name: MUC12, dtype: int64

MUC13
False    183
Name: MUC13, dtype: int64

MUC15
False    167
True      16
Name: MUC15, dtype: int64

MUC16
False    174
True       9
Name: MUC16, dtype: int64

MUC17
False    170
True      13
Name: MUC17, dtype: int64

MUC1
False    183
Name: MUC1, dtype: int64

MUC20
False    183
Name: MUC20, dtype: int64

MUC21
False    153
True      30
Name: MUC21, dtype: int64

MUC2
False    161
True      22
Name: MUC2, dtype: int64

MUC4
False    183
Name: MUC4, dtype: int64

MUC5B
False    182
True       1
Name: MUC5B, dtype: int64

MUC6
False    182
True       1
Name: MUC6, dtype: int64

MUCL1
True     101
False     82
Name: MUCL1, dtype: int64

MUDENG
False    183
Name: MUDENG, dtype: int64

MUL1
False    183
Name: MUL1, dtype: int64

MUM1L1
False    177
True       6
Name: MUM1L1, dtype: int64

MUM1
False    183
Name: MUM1, dtype: int64

MURC
False    183
Name: MURC, dtype: int64

MUS81
False    183
Name: MUS81, dtype: int64

MUSK
False    147
True      36
Name: MUSK, dtype: int64

MUSTN1
False    183
Name: MUSTN1, dtype: int64

MUTED
False    183
Name: MUTED, dtype: int64

MUTYH

False    183
Name: MUTYH, dtype: int64

MUT
False    183
Name: MUT, dtype: int64

MVD
False    183
Name: MVD, dtype: int64

MVK
False    183
Name: MVK, dtype: int64

MVP
False    183
Name: MVP, dtype: int64

MX1
False    183
Name: MX1, dtype: int64

MX2
False    183
Name: MX2, dtype: int64

MXD1
False    183
Name: MXD1, dtype: int64

MXD3
False    183
Name: MXD3, dtype: int64

MXD4
False    183
Name: MXD4, dtype: int64

MXI1
False    183
Name: MXI1, dtype: int64

MXRA5
False    183
Name: MXRA5, dtype: int64

MXRA7
False    183
Name: MXRA7, dtype: int64

MXRA8
False    183
Name: MXRA8, dtype: int64

MYADML2
False    160
True      23
Name: MYADML2, dtype: int64

MYADM
False    183
Name: MYADM, dtype: int64

MYBBP1A
False    183
Name: MYBBP1A, dtype: int64

MYBL1
False    183
Name: MYBL1, dtype: int64

MYBL2
False    183
Name: MYBL2, dtype: int64

MYBPC1
False    167
True      16
Name: MYBPC1, dtype: int64

MYBPC2
False    169
True      14
Name: MYBPC2, dtype: int64

MYBPC3
False    165
True      18
Name: MYBPC3, dtype: int64

MYBPHL
False    134
True      49
Name: MYBPHL, dtype: int64

MYBPH
False    131
True      52
Name: MYBPH, dtype: int64

MYB
False    183
Name: MYB, dtype: int64

MYCBP2
False    183
Name: MYCBP2, dtype: int64

MYCBPAP
False    181
True       2
Name: MYCBPAP, dtype: int64

MYCBP
False    183
Name: MYCBP, dtype: int64

MYCL1
False    183
Name: MYCL1, dtype: int64

MYCNOS
True     112
False     71
Name: MYCNOS, dtype: int64

MYCN
False    183
Name: MYCN, dtype: int64

MYCT1
False    183
Name: MYCT1, dtype: int64

MYC
False    183
Name: MYC, dtype: int64

MYD88
False    183
Name: MYD88, dtype: int64

MYEF2
False    183
Name: MYEF2, dtype: int64

MYEOV2
False    183
Name: MYEOV2, dtype: int64

MYEOV
False    181
True       2
Name: MYEOV, dtype: int64

MYH10
False    183
Name: MYH10, dtype: int64

MYH11
False    183
Name: MYH11, dtype: int64

MYH13
False    136
True      47
Name: MYH13, dtype: int64

MYH14
False    183
Name: MYH14, dtype: int64

MYH15
False    181
True       2
Name: MYH15, dtype: int64

MYH16
False    172
True      11
Name: MYH16, dtype: int64

MYH1
False    130
True      53
Name: MYH1, dtype: int64

MYH2
False    101
True      82
Name: MYH2, dtype: int64

MYH3
False    183
Name: MYH3, dtype: int64

MYH4
True     102
False     81
Name: MYH4, dtype: int64

MYH6
False    117
True      66
Name: MYH6, dtype: int64

MYH7B
False    183
Name: MYH7B, dtype: int64

MYH7
False    136
True      47
Name: MYH7, dtype: int64

MYH8
True     97
False    86
Name: MYH8, dtype: int64

MYH9
False    183
Name: MYH9, dtype: int64

MYL10
False    103
True      80
Name: MYL10, dtype: int64

MYL12A
False    183
Name: MYL12A, dtype: int64

MYL12B
False    183
Name: MYL12B, dtype: int64

MYL2
True     92
False    91
Name: MYL2, dtype: int64

MYL3
False    169
True      14
Name: MYL3, dtype: int64

MYL4
False    180
True       3
Name: MYL4, dtype: int64

MYL5
False    183
Name: MYL5, dtype: int64

MYL6B
False    183
Name: MYL6B, dtype: int64

MYL6
False    183
Name: MYL6, dtype: int64

MYL9
False    183
Name: MYL9, dtype: int64

MYLIP
False    183
Name: MYLIP, dtype: int64

MYLK2
False    180
True       3
Name: MYLK2, dtype: int64

MYLK3
False    183
Name: MYLK3, dtype: int64

MYLK4
False    183
Name: MYLK4, dtype: int64

MYLK
False    183
Name: MYLK, dtype: int64

MYLPF
False    155
True      28
Name: MYLPF, dtype: int64

MYNN
False    183
Name: MYNN, dtype: int64

MYO10
False    183
Name: MYO10, dtype: int64

MYO15A
False    183
Name: MYO15A, dtype: int64

MYO15B
False    183
Name: MYO15B, dtype: int64

MYO16
False    182
True       1
Name: MYO16, dtype: int64

MYO18A
False    183
Name: MYO18A, dtype: int64

MYO18B
False    177
True       6
Name: MYO18B, dtype: int64

MYO19
False    183
Name: MYO19, dtype: int64

MYO1A
False    183
Name: MYO1A, dtype: int64

MYO1B
False    183
Name: MYO1B, dtype: int64

MYO1C
False    183
Name: MYO1C, dtype: int64

MYO1D
False    183
Name: MYO1D, dtype: int64

MYO1E
False    183
Name: MYO1E, dtype: int64

MYO1F
False    183
Name: MYO1F, dtype: int64

MYO1G
False    183
Name: MYO1G, dtype: int64

MYO1H
False    164
True      19
Name: MYO1H, dtype: int64

MYO3A
False    179
True       4
Name: MYO3A, dtype: int64

MYO3B
False    179
True       4
Name: MYO3B, dtype: int64

MYO5A
False    183
Name: MYO5A, dtype: int64

MYO5B
False    183
Name: MYO5B, dtype: int64

MYO5C
False    183
Name: MYO5C, dtype: int64

MYO6
False    183
Name: MYO6, dtype: int64

MYO7A
False    183
Name: MYO7A, dtype: int64

MYO7B
False    183
Name: MYO7B, dtype: int64

MYO9A
False    183
Name: MYO9A, dtype: int64

MYO9B
False    183
Name: MYO9B, dtype: int64

MYOCD
False    180
True       3
Name: MYOCD, dtype: int64

MYOC
False    143
True      40
Name: MYOC, dtype: int64

MYOF
False    183
Name: MYOF, dtype: int64

MYOM1
False    183
Name: MYOM1, dtype: int64

MYOM2
False    183
Name: MYOM2, dtype: int64

MYOM3
False    183
Name: MYOM3, dtype: int64

MYOT
False    173
True      10
Name: MYOT, dtype: int64

MYOZ1
False    183
Name: MYOZ1, dtype: int64

MYOZ2
False    171
True      12
Name: MYOZ2, dtype: int64

MYOZ3
False    183
Name: MYOZ3, dtype: int64

MYPN
False    169
True      14
Name: MYPN, dtype: int64

MYPOP
False    183
Name: MYPOP, dtype: int64

MYRIP
False    183
Name: MYRIP, dtype: int64

MYSM1
False    183
Name: MYSM1, dtype: int64

MYST1
False    183
Name: MYST1, dtype: int64

MYST2
False    183
Name: MYST2, dtype: int64

MYST3
False    183
Name: MYST3, dtype: int64

MYST4
False    183
Name: MYST4, dtype: int64

MYT1L
False    167
True      16
Name: MYT1L, dtype: int64

MYT1
False    174
True       9
Name: MYT1, dtype: int64

MZF1
False    183
Name: MZF1, dtype: int64

N4BP1
False    183
Name: N4BP1, dtype: int64

N4BP2L1
False    183
Name: N4BP2L1, dtype: int64

N4BP2L2
False    183
Name: N4BP2L2, dtype: int64

N4BP2
False    183
Name: N4BP2, dtype: int64

N4BP3
False    183
Name: N4BP3, dtype: int64

N6AMT1
False    183
Name: N6AMT1, dtype: int64

N6AMT2
False    183
Name: N6AMT2, dtype: int64

NAA10
False    183
Name: NAA10, dtype: int64

NAA15
False    183
Name: NAA15, dtype: int64

NAA16
False    183
Name: NAA16, dtype: int64

NAA20
False    183
Name: NAA20, dtype: int64

NAA25
False    183
Name: NAA25, dtype: int64

NAA30
False    183
Name: NAA30, dtype: int64

NAA35
False    183
Name: NAA35, dtype: int64

NAA38
False    183
Name: NAA38, dtype: int64

NAA40
False    183
Name: NAA40, dtype: int64

NAA50
False    183
Name: NAA50, dtype: int64

NAAA
False    183
Name: NAAA, dtype: int64

NAALAD2
False    183
Name: NAALAD2, dtype: int64

NAALADL1
False    183
Name: NAALADL1, dtype: int64

NAALADL2
False    183
Name: NAALADL2, dtype: int64

NAB1
False    183
Name: NAB1, dtype: int64

NAB2
False    183
Name: NAB2, dtype: int64

NACA2
False    183
Name: NACA2, dtype: int64

NACAD
False    183
Name: NACAD, dtype: int64

NACAP1
False    183
Name: NACAP1, dtype: int64

NACA
False    183
Name: NACA, dtype: int64

NACC1
False    183
Name: NACC1, dtype: int64

NACC2
False    183
Name: NACC2, dtype: int64

NADK
False    183
Name: NADK, dtype: int64

NADSYN1
False    183
Name: NADSYN1, dtype: int64

NAE1
False    183
Name: NAE1, dtype: int64

NAF1
False    183
Name: NAF1, dtype: int64

NAGA
False    183
Name: NAGA, dtype: int64

NAGK
False    183
Name: NAGK, dtype: int64

NAGLU
False    183
Name: NAGLU, dtype: int64

NAGPA
False    183
Name: NAGPA, dtype: int64

NAGS
False    183
Name: NAGS, dtype: int64

NAIF1
False    183
Name: NAIF1, dtype: int64

NAIP
False    183
Name: NAIP, dtype: int64

NALCN
False    183
Name: NALCN, dtype: int64

NAMPT
False    183
Name: NAMPT, dtype: int64

NANOG
False    163
True      20
Name: NANOG, dtype: int64

NANOS1
False    183
Name: NANOS1, dtype: int64

NANOS3
False    182
True       1
Name: NANOS3, dtype: int64

NANP
False    183
Name: NANP, dtype: int64

NANS
False    183
Name: NANS, dtype: int64

NAP1L1
False    183
Name: NAP1L1, dtype: int64

NAP1L2
False    183
Name: NAP1L2, dtype: int64

NAP1L3
False    183
Name: NAP1L3, dtype: int64

NAP1L4
False    183
Name: NAP1L4, dtype: int64

NAP1L5
False    183
Name: NAP1L5, dtype: int64

NAP1L6
False    170
True      13
Name: NAP1L6, dtype: int64

NAPA
False    183
Name: NAPA, dtype: int64

NAPB
False    183
Name: NAPB, dtype: int64

NAPEPLD
False    183
Name: NAPEPLD, dtype: int64

NAPG
False    183
Name: NAPG, dtype: int64

NAPRT1
False    183
Name: NAPRT1, dtype: int64

NAPSA
False    183
Name: NAPSA, dtype: int64

NAPSB
False    183
Name: NAPSB, dtype: int64

NARFL
False    183
Name: NARFL, dtype: int64

NARF
False    183
Name: NARF, dtype: int64

NARG2
False    183
Name: NARG2, dtype: int64

NARS2
False    183
Name: NARS2, dtype: int64

NARS
False    183
Name: NARS, dtype: int64

NASP
False    183
Name: NASP, dtype: int64

NAT10

False    183
Name: NAT10, dtype: int64

NAT14
False    183
Name: NAT14, dtype: int64

NAT15
False    183
Name: NAT15, dtype: int64

NAT1
False    183
Name: NAT1, dtype: int64

NAT2
False    172
True      11
Name: NAT2, dtype: int64

NAT6
False    183
Name: NAT6, dtype: int64

NAT8B
False    175
True       8
Name: NAT8B, dtype: int64

NAT8L
False    180
True       3
Name: NAT8L, dtype: int64

NAT8
False    149
True      34
Name: NAT8, dtype: int64

NAT9
False    183
Name: NAT9, dtype: int64

NAV1
False    183
Name: NAV1, dtype: int64

NAV2
False    183
Name: NAV2, dtype: int64

NAV3
False    183
Name: NAV3, dtype: int64

NBAS
False    183
Name: NBAS, dtype: int64

NBEAL1
False    183
Name: NBEAL1, dtype: int64

NBEAL2
False    183
Name: NBEAL2, dtype: int64

NBEA
False    183
Name: NBEA, dtype: int64

NBL1
False    183
Name: NBL1, dtype: int64

NBLA00301
False    182
True       1
Name: NBLA00301, dtype: int64

NBN
False    183
Name: NBN, dtype: int64

NBPF10
False    183
Name: NBPF10, dtype: int64

NBPF14
False    183
Name: NBPF14, dtype: int64

NBPF15
False    183
Name: NBPF15, dtype: int64

NBPF16
False    181
True       2
Name: NBPF16, dtype: int64

NBPF1
False    183
Name: NBPF1, dtype: int64

NBPF3
False    183
Name: NBPF3, dtype: int64

NBPF4
False    109
True      74
Name: NBPF4, dtype: int64

NBPF7
False    157
True      26
Name: NBPF7, dtype: int64

NBPF9
False    183
Name: NBPF9, dtype: int64

NBR1
False    183
Name: NBR1, dtype: int64

NBR2
False    183
Name: NBR2, dtype: int64

NCALD
False    183
Name: NCALD, dtype: int64

NCAM1
False    183
Name: NCAM1, dtype: int64

NCAM2
False    182
True       1
Name: NCAM2, dtype: int64

NCAN
False    143
True      40
Name: NCAN, dtype: int64

NCAPD2
False    183
Name: NCAPD2, dtype: int64

NCAPD3
False    183
Name: NCAPD3, dtype: int64

NCAPG2
False    183
Name: NCAPG2, dtype: int64

NCAPG
False    183
Name: NCAPG, dtype: int64

NCAPH2
False    183
Name: NCAPH2, dtype: int64

NCAPH
False    183
Name: NCAPH, dtype: int64

NCBP1
False    183
Name: NCBP1, dtype: int64

NCBP2
False    183
Name: NCBP2, dtype: int64

NCCRP1
False    180
True       3
Name: NCCRP1, dtype: int64

NCDN
False    183
Name: NCDN, dtype: int64

NCEH1
False    183
Name: NCEH1, dtype: int64

NCF1B
False    182
True       1
Name: NCF1B, dtype: int64

NCF1C
False    182
True       1
Name: NCF1C, dtype: int64

NCF1
False    183
Name: NCF1, dtype: int64

NCF2
False    183
Name: NCF2, dtype: int64

NCF4
False    183
Name: NCF4, dtype: int64

NCK1
False    183
Name: NCK1, dtype: int64

NCK2
False    183
Name: NCK2, dtype: int64

NCKAP1L
False    183
Name: NCKAP1L, dtype: int64

NCKAP1
False    183
Name: NCKAP1, dtype: int64

NCKAP5L
False    183
Name: NCKAP5L, dtype: int64

NCKAP5
False    183
Name: NCKAP5, dtype: int64

NCKIPSD
False    183
Name: NCKIPSD, dtype: int64

NCLN
False    183
Name: NCLN, dtype: int64

NCL
False    183
Name: NCL, dtype: int64

NCOA1
False    183
Name: NCOA1, dtype: int64

NCOA2
False    183
Name: NCOA2, dtype: int64

NCOA3
False    183
Name: NCOA3, dtype: int64

NCOA4
False    183
Name: NCOA4, dtype: int64

NCOA5
False    183
Name: NCOA5, dtype: int64

NCOA6
False    183
Name: NCOA6, dtype: int64

NCOA7
False    183
Name: NCOA7, dtype: int64

NCOR1
False    183
Name: NCOR1, dtype: int64

NCOR2
False    183
Name: NCOR2, dtype: int64

NCR1
False    130
True      53
Name: NCR1, dtype: int64

NCR3
False    182
True       1
Name: NCR3, dtype: int64

NCRNA00028
True     127
False     56
Name: NCRNA00028, dtype: int64

NCRNA00032
True     97
False    86
Name: NCRNA00032, dtype: int64

NCRNA00081
False    183
Name: NCRNA00081, dtype: int64

NCRNA00085
False    183
Name: NCRNA00085, dtype: int64

NCRNA00086
False    183
Name: NCRNA00086, dtype: int64

NCRNA00087
False    183
Name: NCRNA00087, dtype: int64

NCRNA00092
False    183
Name: NCRNA00092, dtype: int64

NCRNA00093
False    177
True       6
Name: NCRNA00093, dtype: int64

NCRNA00094
False    183
Name: NCRNA00094, dtype: int64

NCRNA00095
False    183
Name: NCRNA00095, dtype: int64

NCRNA00105
False    183
Name: NCRNA00105, dtype: int64

NCRNA00107
False    183
Name: NCRNA00107, dtype: int64

NCRNA00110
False    156
True      27
Name: NCRNA00110, dtype: int64

NCRNA00113
True     127
False     56
Name: NCRNA00113, dtype: int64

NCRNA00114
True     128
False     55
Name: NCRNA00114, dtype: int64

NCRNA00115
False    183
Name: NCRNA00115, dtype: int64

NCRNA00116
False    183
Name: NCRNA00116, dtype: int64

NCRNA00119
False    104
True      79
Name: NCRNA00119, dtype: int64

NCRNA00120
False    183
Name: NCRNA00120, dtype: int64

NCRNA00152
False    183
Name: NCRNA00152, dtype: int64

NCRNA00158
True     92
False    91
Name: NCRNA00158, dtype: int64

NCRNA00162
False    128
True      55
Name: NCRNA00162, dtype: int64

NCRNA00164
True     110
False     73
Name: NCRNA00164, dtype: int64

NCRNA00167
False    160
True      23
Name: NCRNA00167, dtype: int64

NCRNA00169
False    174
True       9
Name: NCRNA00169, dtype: int64

NCRNA00171
False    183
Name: NCRNA00171, dtype: int64

NCRNA00173
False    163
True      20
Name: NCRNA00173, dtype: int64

NCRNA00174
False    183
Name: NCRNA00174, dtype: int64

NCRNA00175
False    132
True      51
Name: NCRNA00175, dtype: int64

NCRNA00176
False    183
Name: NCRNA00176, dtype: int64

NCRNA00181
False    182
True       1
Name: NCRNA00181, dtype: int64

NCRNA00182
False    183
Name: NCRNA00182, dtype: int64

NCRNA00183
False    183
Name: NCRNA00183, dtype: int64

NCRNA00185
False    104
True      79
Name: NCRNA00185, dtype: int64

NCRNA00188
False    183
Name: NCRNA00188, dtype: int64

NCRNA00189
False    156
True      27
Name: NCRNA00189, dtype: int64

NCRNA00201
False    183
Name: NCRNA00201, dtype: int64

NCRNA00202
False    180
True       3
Name: NCRNA00202, dtype: int64

NCRNA00203
False    123
True      60
Name: NCRNA00203, dtype: int64

NCRNA00204B
False    181
True       2
Name: NCRNA00204B, dtype: int64

NCRNA00219
False    183
Name: NCRNA00219, dtype: int64

NCRNA00230B
True     102
False     81
Name: NCRNA00230B, dtype: int64

NCRNA00235
False    146
True      37
Name: NCRNA00235, dtype: int64

NCS1
False    183
Name: NCS1, dtype: int64

NCSTN
False    183
Name: NCSTN, dtype: int64

NDC80
False    183
Name: NDC80, dtype: int64

NDE1
False    183
Name: NDE1, dtype: int64

NDEL1
False    183
Name: NDEL1, dtype: int64

NDFIP1
False    183
Name: NDFIP1, dtype: int64

NDFIP2
False    183
Name: NDFIP2, dtype: int64

NDNL2
False    183
Name: NDNL2, dtype: int64

NDN
False    183
Name: NDN, dtype: int64

NDOR1
False    183
Name: NDOR1, dtype: int64

NDP
False    181
True       2
Name: NDP, dtype: int64

NDRG1
False    183
Name: NDRG1, dtype: int64

NDRG2
False    183
Name: NDRG2, dtype: int64

NDRG3
False    183
Name: NDRG3, dtype: int64

NDRG4
False    183
Name: NDRG4, dtype: int64

NDST1
False    183
Name: NDST1, dtype: int64

NDST2
False    183
Name: NDST2, dtype: int64

NDST3
False    171
True      12
Name: NDST3, dtype: int64

NDUFA10
False    183
Name: NDUFA10, dtype: int64

NDUFA11
False    183
Name: NDUFA11, dtype: int64

NDUFA12
False    183
Name: NDUFA12, dtype: int64

NDUFA13
False    183
Name: NDUFA13, dtype: int64

NDUFA1
False    183
Name: NDUFA1, dtype: int64

NDUFA2
False    183
Name: NDUFA2, dtype: int64

NDUFA3
False    183
Name: NDUFA3, dtype: int64

NDUFA4L2
False    183
Name: NDUFA4L2, dtype: int64

NDUFA4
False    183
Name: NDUFA4, dtype: int64

NDUFA5
False    183
Name: NDUFA5, dtype: int64

NDUFA6
False    183
Name: NDUFA6, dtype: int64

NDUFA7
False    183
Name: NDUFA7, dtype: int64

NDUFA8
False    183
Name: NDUFA8, dtype: int64

NDUFA9
False    183
Name: NDUFA9, dtype: int64

NDUFAB1
False    183
Name: NDUFAB1, dtype: int64

NDUFAF1
False    183
Name: NDUFAF1, dtype: int64

NDUFAF2
False    183
Name: NDUFAF2, dtype: int64

NDUFAF3
False    183
Name: NDUFAF3, dtype: int64

NDUFAF4
False    183
Name: NDUFAF4, dtype: int64

NDUFB10
False    183
Name: NDUFB10, dtype: int64

NDUFB11
False    183
Name: NDUFB11, dtype: int64

NDUFB1
False    183
Name: NDUFB1, dtype: int64

NDUFB2
False    183
Name: NDUFB2, dtype: int64

NDUFB3
False    183
Name: NDUFB3, dtype: int64

NDUFB4
False    183
Name: NDUFB4, dtype: int64

NDUFB5
False    183
Name: NDUFB5, dtype: int64

NDUFB6
False    183
Name: NDUFB6, dtype: int64

NDUFB7
False    183
Name: NDUFB7, dtype: int64

NDUFB8
False    183
Name: NDUFB8, dtype: int64

NDUFB9
False    183
Name: NDUFB9, dtype: int64

NDUFC1
False    183
Name: NDUFC1, dtype: int64

NDUFC2
False    183
Name: NDUFC2, dtype: int64

NDUFS1
False    183
Name: NDUFS1, dtype: int64

NDUFS2
False    183
Name: NDUFS2, dtype: int64

NDUFS3
False    183
Name: NDUFS3, dtype: int64

NDUFS4

False    183
Name: NDUFS4, dtype: int64

NDUFS5
False    183
Name: NDUFS5, dtype: int64

NDUFS6
False    183
Name: NDUFS6, dtype: int64

NDUFS7
False    183
Name: NDUFS7, dtype: int64

NDUFS8
False    183
Name: NDUFS8, dtype: int64

NDUFV1
False    183
Name: NDUFV1, dtype: int64

NDUFV2
False    183
Name: NDUFV2, dtype: int64

NDUFV3
False    183
Name: NDUFV3, dtype: int64

NEAT1
False    183
Name: NEAT1, dtype: int64

NEBL
False    183
Name: NEBL, dtype: int64

NEB
False    183
Name: NEB, dtype: int64

NECAB1
False    183
Name: NECAB1, dtype: int64

NECAB2
False    182
True       1
Name: NECAB2, dtype: int64

NECAB3
False    183
Name: NECAB3, dtype: int64

NECAP1
False    183
Name: NECAP1, dtype: int64

NECAP2
False    183
Name: NECAP2, dtype: int64

NEDD1
False    183
Name: NEDD1, dtype: int64

NEDD4L
False    183
Name: NEDD4L, dtype: int64

NEDD4
False    183
Name: NEDD4, dtype: int64

NEDD8
False    183
Name: NEDD8, dtype: int64

NEDD9
False    183
Name: NEDD9, dtype: int64

NEFH
False    183
Name: NEFH, dtype: int64

NEFL
False    182
True       1
Name: NEFL, dtype: int64

NEFM
False    183
Name: NEFM, dtype: int64

NEGR1
False    183
Name: NEGR1, dtype: int64

NEIL1
False    183
Name: NEIL1, dtype: int64

NEIL2
False    183
Name: NEIL2, dtype: int64

NEIL3
False    183
Name: NEIL3, dtype: int64

NEK10
False    178
True       5
Name: NEK10, dtype: int64

NEK11
False    183
Name: NEK11, dtype: int64

NEK1
False    183
Name: NEK1, dtype: int64

NEK2
False    183
Name: NEK2, dtype: int64

NEK3
False    183
Name: NEK3, dtype: int64

NEK4
False    183
Name: NEK4, dtype: int64

NEK5
False    165
True      18
Name: NEK5, dtype: int64

NEK6
False    183
Name: NEK6, dtype: int64

NEK7
False    183
Name: NEK7, dtype: int64

NEK8
False    183
Name: NEK8, dtype: int64

NEK9
False    183
Name: NEK9, dtype: int64

NELF
False    183
Name: NELF, dtype: int64

NELL1
True     97
False    86
Name: NELL1, dtype: int64

NELL2
False    182
True       1
Name: NELL2, dtype: int64

NENF
False    183
Name: NENF, dtype: int64

NEO1
False    183
Name: NEO1, dtype: int64

NES
False    183
Name: NES, dtype: int64

NET1
False    183
Name: NET1, dtype: int64

NETO1
False    168
True      15
Name: NETO1, dtype: int64

NETO2
False    183
Name: NETO2, dtype: int64

NEU1
False    183
Name: NEU1, dtype: int64

NEU3
False    183
Name: NEU3, dtype: int64

NEU4
False    178
True       5
Name: NEU4, dtype: int64

NEURL1B
False    183
Name: NEURL1B, dtype: int64

NEURL2
False    183
Name: NEURL2, dtype: int64

NEURL3
False    183
Name: NEURL3, dtype: int64

NEURL4
False    183
Name: NEURL4, dtype: int64

NEURL
False    183
Name: NEURL, dtype: int64

NEUROD1
False    177
True       6
Name: NEUROD1, dtype: int64

NEUROD2
True     103
False     80
Name: NEUROD2, dtype: int64

NEUROG3
False    96
True     87
Name: NEUROG3, dtype: int64

NEXN
False    183
Name: NEXN, dtype: int64

NF1
False    183
Name: NF1, dtype: int64

NF2
False    183
Name: NF2, dtype: int64

NFAM1
False    183
Name: NFAM1, dtype: int64

NFASC
False    183
Name: NFASC, dtype: int64

NFAT5
False    183
Name: NFAT5, dtype: int64

NFATC1
False    183
Name: NFATC1, dtype: int64

NFATC2IP
False    183
Name: NFATC2IP, dtype: int64

NFATC2
False    183
Name: NFATC2, dtype: int64

NFATC3
False    183
Name: NFATC3, dtype: int64

NFATC4
False    183
Name: NFATC4, dtype: int64

NFE2L1
False    183
Name: NFE2L1, dtype: int64

NFE2L2
False    183
Name: NFE2L2, dtype: int64

NFE2L3
False    183
Name: NFE2L3, dtype: int64

NFE2
False    183
Name: NFE2, dtype: int64

NFIA
False    183
Name: NFIA, dtype: int64

NFIB
False    183
Name: NFIB, dtype: int64

NFIC
False    183
Name: NFIC, dtype: int64

NFIL3
False    183
Name: NFIL3, dtype: int64

NFIX
False    183
Name: NFIX, dtype: int64

NFKB1
False    183
Name: NFKB1, dtype: int64

NFKB2
False    183
Name: NFKB2, dtype: int64

NFKBIA
False    183
Name: NFKBIA, dtype: int64

NFKBIB
False    183
Name: NFKBIB, dtype: int64

NFKBID
False    183
Name: NFKBID, dtype: int64

NFKBIE
False    183
Name: NFKBIE, dtype: int64

NFKBIL1
False    183
Name: NFKBIL1, dtype: int64

NFKBIL2
False    183
Name: NFKBIL2, dtype: int64

NFKBIZ
False    183
Name: NFKBIZ, dtype: int64

NFRKB
False    183
Name: NFRKB, dtype: int64

NFS1
False    183
Name: NFS1, dtype: int64

NFU1
False    183
Name: NFU1, dtype: int64

NFX1
False    183
Name: NFX1, dtype: int64

NFXL1
False    183
Name: NFXL1, dtype: int64

NFYA
False    183
Name: NFYA, dtype: int64

NFYB
False    183
Name: NFYB, dtype: int64

NFYC
False    183
Name: NFYC, dtype: int64

NGB
False    128
True      55
Name: NGB, dtype: int64

NGDN
False    183
Name: NGDN, dtype: int64

NGEF
False    183
Name: NGEF, dtype: int64

NGFRAP1
False    183
Name: NGFRAP1, dtype: int64

NGFR
False    183
Name: NGFR, dtype: int64

NGF
False    182
True       1
Name: NGF, dtype: int64

NGLY1
False    183
Name: NGLY1, dtype: int64

NGRN
False    183
Name: NGRN, dtype: int64

NHEDC1
False    177
True       6
Name: NHEDC1, dtype: int64

NHEDC2
False    183
Name: NHEDC2, dtype: int64

NHEJ1
False    183
Name: NHEJ1, dtype: int64

NHLH1
False    181
True       2
Name: NHLH1, dtype: int64

NHLH2
False    113
True      70
Name: NHLH2, dtype: int64

NHLRC1
False    183
Name: NHLRC1, dtype: int64

NHLRC2
False    183
Name: NHLRC2, dtype: int64

NHLRC3
False    183
Name: NHLRC3, dtype: int64

NHLRC4
False    183
Name: NHLRC4, dtype: int64

NHP2L1
False    183
Name: NHP2L1, dtype: int64

NHP2
False    183
Name: NHP2, dtype: int64

NHSL1
False    183
Name: NHSL1, dtype: int64

NHSL2
False    183
Name: NHSL2, dtype: int64

NHS
False    183
Name: NHS, dtype: int64

NICN1
False    183
Name: NICN1, dtype: int64

NID1
False    183
Name: NID1, dtype: int64

NID2
False    183
Name: NID2, dtype: int64

NIF3L1
False    183
Name: NIF3L1, dtype: int64

NINJ1
False    183
Name: NINJ1, dtype: int64

NINJ2
False    183
Name: NINJ2, dtype: int64

NINL
False    183
Name: NINL, dtype: int64

NIN
False    183
Name: NIN, dtype: int64

NIP7
False    183
Name: NIP7, dtype: int64

NIPA1
False    183
Name: NIPA1, dtype: int64

NIPA2
False    183
Name: NIPA2, dtype: int64

NIPAL1
False    182
True       1
Name: NIPAL1, dtype: int64

NIPAL2
False    183
Name: NIPAL2, dtype: int64

NIPAL3
False    183
Name: NIPAL3, dtype: int64

NIPAL4
False    178
True       5
Name: NIPAL4, dtype: int64

NIPBL
False    183
Name: NIPBL, dtype: int64

NIPSNAP1
False    183
Name: NIPSNAP1, dtype: int64

NIPSNAP3A
False    183
Name: NIPSNAP3A, dtype: int64

NIPSNAP3B
False    183
Name: NIPSNAP3B, dtype: int64

NISCH
False    183
Name: NISCH, dtype: int64

NIT1
False    183
Name: NIT1, dtype: int64

NIT2
False    183
Name: NIT2, dtype: int64

NKAIN1
False    181
True       2
Name: NKAIN1, dtype: int64

NKAIN2
False    171
True      12
Name: NKAIN2, dtype: int64

NKAIN3
True     103
False     80
Name: NKAIN3, dtype: int64

NKAIN4
False    176
True       7
Name: NKAIN4, dtype: int64

NKAPL
False    181
True       2
Name: NKAPL, dtype: int64

NKAP
False    183
Name: NKAP, dtype: int64

NKD1
False    182
True       1
Name: NKD1, dtype: int64

NKD2
False    183
Name: NKD2, dtype: int64

NKG7
False    183
Name: NKG7, dtype: int64

NKIRAS1
False    183
Name: NKIRAS1, dtype: int64

NKIRAS2
False    183
Name: NKIRAS2, dtype: int64

NKPD1
False    182
True       1
Name: NKPD1, dtype: int64

NKRF
False    183
Name: NKRF, dtype: int64

NKTR
False    183
Name: NKTR, dtype: int64

NKX2-1
True     104
False     79
Name: NKX2-1, dtype: int64

NKX2-2
False    177
True       6
Name: NKX2-2, dtype: int64

NKX2-3
False    182
True       1
Name: NKX2-3, dtype: int64

NKX2-5
False    134
True      49
Name: NKX2-5, dtype: int64

NKX2-8
False    96
True     87
Name: NKX2-8, dtype: int64

NKX3-1
False    183
Name: NKX3-1, dtype: int64

NKX3-2
False    182
True       1
Name: NKX3-2, dtype: int64

NKX6-1
False    178
True       5
Name: NKX6-1, dtype: int64

NKX6-2
False    120
True      63
Name: NKX6-2, dtype: int64

NKX6-3
True     93
False    90
Name: NKX6-3, dtype: int64

NLE1
False    183
Name: NLE1, dtype: int64

NLGN1
False    182
True       1
Name: NLGN1, dtype: int64

NLGN2
False    183
Name: NLGN2, dtype: int64

NLGN3
False    183
Name: NLGN3, dtype: int64

NLGN4X
False    183
Name: NLGN4X, dtype: int64

NLGN4Y
False    142
True      41
Name: NLGN4Y, dtype: int64

NLK
False    183
Name: NLK, dtype: int64

NLN
False    183
Name: NLN, dtype: int64

NLRC3

False    183
Name: NLRC3, dtype: int64

NLRC4
False    183
Name: NLRC4, dtype: int64

NLRC5
False    183
Name: NLRC5, dtype: int64

NLRP11
False    158
True      25
Name: NLRP11, dtype: int64

NLRP12
False    182
True       1
Name: NLRP12, dtype: int64

NLRP14
False    139
True      44
Name: NLRP14, dtype: int64

NLRP1
False    183
Name: NLRP1, dtype: int64

NLRP2
False    181
True       2
Name: NLRP2, dtype: int64

NLRP3
False    183
Name: NLRP3, dtype: int64

NLRP4
True     93
False    90
Name: NLRP4, dtype: int64

NLRP6
False    177
True       6
Name: NLRP6, dtype: int64

NLRP7
False    161
True      22
Name: NLRP7, dtype: int64

NLRP9
False    177
True       6
Name: NLRP9, dtype: int64

NLRX1
False    183
Name: NLRX1, dtype: int64

NMBR
False    100
True      83
Name: NMBR, dtype: int64

NMB
False    183
Name: NMB, dtype: int64

NMD3
False    183
Name: NMD3, dtype: int64

NME1-NME2
False    183
Name: NME1-NME2, dtype: int64

NME1
False    183
Name: NME1, dtype: int64

NME2P1
False    183
Name: NME2P1, dtype: int64

NME2
False    183
Name: NME2, dtype: int64

NME3
False    183
Name: NME3, dtype: int64

NME4
False    183
Name: NME4, dtype: int64

NME5
False    183
Name: NME5, dtype: int64

NME6
False    183
Name: NME6, dtype: int64

NME7
False    183
Name: NME7, dtype: int64

NMI
False    183
Name: NMI, dtype: int64

NMNAT1
False    183
Name: NMNAT1, dtype: int64

NMNAT2
False    183
Name: NMNAT2, dtype: int64

NMNAT3
False    183
Name: NMNAT3, dtype: int64

NMRAL1
False    183
Name: NMRAL1, dtype: int64

NMT1
False    183
Name: NMT1, dtype: int64

NMT2
False    183
Name: NMT2, dtype: int64

NMUR1
False    183
Name: NMUR1, dtype: int64

NMUR2
False    169
True      14
Name: NMUR2, dtype: int64

NMU
False    173
True      10
Name: NMU, dtype: int64

NNAT
False    183
Name: NNAT, dtype: int64

NNMT
False    183
Name: NNMT, dtype: int64

NNT
False    183
Name: NNT, dtype: int64

NOB1
False    183
Name: NOB1, dtype: int64

NOC2L
False    183
Name: NOC2L, dtype: int64

NOC3L
False    183
Name: NOC3L, dtype: int64

NOC4L
False    183
Name: NOC4L, dtype: int64

NOD1
False    183
Name: NOD1, dtype: int64

NOD2
False    183
Name: NOD2, dtype: int64

NODAL
False    175
True       8
Name: NODAL, dtype: int64

NOG
False    182
True       1
Name: NOG, dtype: int64

NOL10
False    183
Name: NOL10, dtype: int64

NOL11
False    183
Name: NOL11, dtype: int64

NOL12
False    183
Name: NOL12, dtype: int64

NOL3
False    183
Name: NOL3, dtype: int64

NOL4
False    175
True       8
Name: NOL4, dtype: int64

NOL6
False    183
Name: NOL6, dtype: int64

NOL7
False    183
Name: NOL7, dtype: int64

NOL8
False    183
Name: NOL8, dtype: int64

NOL9
False    183
Name: NOL9, dtype: int64

NOLC1
False    183
Name: NOLC1, dtype: int64

NOM1
False    183
Name: NOM1, dtype: int64

NOMO1
False    183
Name: NOMO1, dtype: int64

NOMO2
False    183
Name: NOMO2, dtype: int64

NOMO3
False    183
Name: NOMO3, dtype: int64

NONO
False    183
Name: NONO, dtype: int64

NOP10
False    183
Name: NOP10, dtype: int64

NOP14
False    183
Name: NOP14, dtype: int64

NOP16
False    183
Name: NOP16, dtype: int64

NOP2
False    183
Name: NOP2, dtype: int64

NOP56
False    183
Name: NOP56, dtype: int64

NOP58
False    183
Name: NOP58, dtype: int64

NOS1AP
False    183
Name: NOS1AP, dtype: int64

NOS1
False    160
True      23
Name: NOS1, dtype: int64

NOS2
False    183
Name: NOS2, dtype: int64

NOS3
False    183
Name: NOS3, dtype: int64

NOSIP
False    183
Name: NOSIP, dtype: int64

NOSTRIN
False    183
Name: NOSTRIN, dtype: int64

NOTCH1
False    183
Name: NOTCH1, dtype: int64

NOTCH2NL
False    183
Name: NOTCH2NL, dtype: int64

NOTCH2
False    183
Name: NOTCH2, dtype: int64

NOTCH3
False    183
Name: NOTCH3, dtype: int64

NOTCH4
False    183
Name: NOTCH4, dtype: int64

NOTUM
False    183
Name: NOTUM, dtype: int64

NOVA1
False    183
Name: NOVA1, dtype: int64

NOVA2
False    183
Name: NOVA2, dtype: int64

NOV
False    183
Name: NOV, dtype: int64

NOX1
False    176
True       7
Name: NOX1, dtype: int64

NOX4
False    183
Name: NOX4, dtype: int64

NOX5
False    176
True       7
Name: NOX5, dtype: int64

NOXA1
False    183
Name: NOXA1, dtype: int64

NOXO1
False    183
Name: NOXO1, dtype: int64

NPAS1
False    183
Name: NPAS1, dtype: int64

NPAS2
False    183
Name: NPAS2, dtype: int64

NPAS3
False    183
Name: NPAS3, dtype: int64

NPAS4
False    172
True      11
Name: NPAS4, dtype: int64

NPAT
False    183
Name: NPAT, dtype: int64

NPBWR1
False    107
True      76
Name: NPBWR1, dtype: int64

NPB
False    160
True      23
Name: NPB, dtype: int64

NPC1L1
False    183
Name: NPC1L1, dtype: int64

NPC1
False    183
Name: NPC1, dtype: int64

NPC2
False    183
Name: NPC2, dtype: int64

NPDC1
False    183
Name: NPDC1, dtype: int64

NPEPL1
False    183
Name: NPEPL1, dtype: int64

NPEPPS
False    183
Name: NPEPPS, dtype: int64

NPFFR1
False    125
True      58
Name: NPFFR1, dtype: int64

NPFFR2
False    143
True      40
Name: NPFFR2, dtype: int64

NPFF
False    183
Name: NPFF, dtype: int64

NPHP1
False    183
Name: NPHP1, dtype: int64

NPHP3
False    183
Name: NPHP3, dtype: int64

NPHP4
False    183
Name: NPHP4, dtype: int64

NPHS1
False    172
True      11
Name: NPHS1, dtype: int64

NPHS2
True     113
False     70
Name: NPHS2, dtype: int64

NPIPL3
False    183
Name: NPIPL3, dtype: int64

NPIP
False    183
Name: NPIP, dtype: int64

NPLOC4
False    183
Name: NPLOC4, dtype: int64

NPL
False    183
Name: NPL, dtype: int64

NPM1
False    183
Name: NPM1, dtype: int64

NPM2
False    183
Name: NPM2, dtype: int64

NPM3
False    183
Name: NPM3, dtype: int64

NPNT
False    183
Name: NPNT, dtype: int64

NPPA
False    166
True      17
Name: NPPA, dtype: int64

NPPB
True     98
False    85
Name: NPPB, dtype: int64

NPPC
True     100
False     83
Name: NPPC, dtype: int64

NPR1
False    183
Name: NPR1, dtype: int64

NPR2
False    183
Name: NPR2, dtype: int64

NPR3
False    181
True       2
Name: NPR3, dtype: int64

NPRL2
False    183
Name: NPRL2, dtype: int64

NPRL3
False    183
Name: NPRL3, dtype: int64

NPSR1
False    140
True      43
Name: NPSR1, dtype: int64

NPTN
False    183
Name: NPTN, dtype: int64

NPTX1
False    183
Name: NPTX1, dtype: int64

NPTX2
False    183
Name: NPTX2, dtype: int64

NPTXR
False    183
Name: NPTXR, dtype: int64

NPW
False    167
True      16
Name: NPW, dtype: int64

NPY1R
False    183
Name: NPY1R, dtype: int64

NPY2R
True     99
False    84
Name: NPY2R, dtype: int64

NPY5R
False    148
True      35
Name: NPY5R, dtype: int64

NPY6R
False    145
True      38
Name: NPY6R, dtype: int64

NPY
False    166
True      17
Name: NPY, dtype: int64

NQO1
False    183
Name: NQO1, dtype: int64

NQO2
False    183
Name: NQO2, dtype: int64

NR0B1
False    170
True      13
Name: NR0B1, dtype: int64

NR0B2
False    180
True       3
Name: NR0B2, dtype: int64

NR1D1
False    183
Name: NR1D1, dtype: int64

NR1D2
False    183
Name: NR1D2, dtype: int64

NR1H2
False    183
Name: NR1H2, dtype: int64

NR1H3
False    183
Name: NR1H3, dtype: int64

NR1H4
False    180
True       3
Name: NR1H4, dtype: int64

NR1I2
False    182
True       1
Name: NR1I2, dtype: int64

NR1I3
False    182
True       1
Name: NR1I3, dtype: int64

NR2C1
False    183
Name: NR2C1, dtype: int64

NR2C2AP
False    183
Name: NR2C2AP, dtype: int64

NR2C2
False    183
Name: NR2C2, dtype: int64

NR2E1
False    96
True     87
Name: NR2E1, dtype: int64

NR2E3
False    176
True       7
Name: NR2E3, dtype: int64

NR2F1
False    183
Name: NR2F1, dtype: int64

NR2F2
False    183
Name: NR2F2, dtype: int64

NR2F6
False    183
Name: NR2F6, dtype: int64

NR3C1
False    183
Name: NR3C1, dtype: int64

NR3C2
False    183
Name: NR3C2, dtype: int64

NR4A1
False    183
Name: NR4A1, dtype: int64

NR4A2
False    183
Name: NR4A2, dtype: int64

NR4A3
False    183
Name: NR4A3, dtype: int64

NR5A1
True     92
False    91
Name: NR5A1, dtype: int64

NR5A2
False    183
Name: NR5A2, dtype: int64

NR6A1
False    179
True       4
Name: NR6A1, dtype: int64

NRADDP
False    179
True       4
Name: NRADDP, dtype: int64

NRAP
False    146
True      37
Name: NRAP, dtype: int64

NRARP
False    183
Name: NRARP, dtype: int64

NRAS
False    183
Name: NRAS, dtype: int64

NRBF2
False    183
Name: NRBF2, dtype: int64

NRBP1
False    183
Name: NRBP1, dtype: int64

NRBP2
False    183
Name: NRBP2, dtype: int64

NRCAM
False    183
Name: NRCAM, dtype: int64

NRD1
False    183
Name: NRD1, dtype: int64

NRF1
False    183
Name: NRF1, dtype: int64

NRG1

False    183
Name: NRG1, dtype: int64

NRG2
False    178
True       5
Name: NRG2, dtype: int64

NRG3
False    181
True       2
Name: NRG3, dtype: int64

NRG4
False    179
True       4
Name: NRG4, dtype: int64

NRGN
False    183
Name: NRGN, dtype: int64

NRIP1
False    183
Name: NRIP1, dtype: int64

NRIP2
False    183
Name: NRIP2, dtype: int64

NRIP3
False    183
Name: NRIP3, dtype: int64

NRK
False    181
True       2
Name: NRK, dtype: int64

NRL
False    183
Name: NRL, dtype: int64

NRM
False    183
Name: NRM, dtype: int64

NRN1L
False    170
True      13
Name: NRN1L, dtype: int64

NRN1
False    183
Name: NRN1, dtype: int64

NRP1
False    183
Name: NRP1, dtype: int64

NRP2
False    183
Name: NRP2, dtype: int64

NRSN1
False    167
True      16
Name: NRSN1, dtype: int64

NRSN2
False    183
Name: NRSN2, dtype: int64

NRTN
False    183
Name: NRTN, dtype: int64

NRXN1
False    183
Name: NRXN1, dtype: int64

NRXN2
False    183
Name: NRXN2, dtype: int64

NRXN3
False    183
Name: NRXN3, dtype: int64

NSA2
False    183
Name: NSA2, dtype: int64

NSD1
False    183
Name: NSD1, dtype: int64

NSDHL
False    183
Name: NSDHL, dtype: int64

NSFL1C
False    183
Name: NSFL1C, dtype: int64

NSF
False    183
Name: NSF, dtype: int64

NSL1
False    183
Name: NSL1, dtype: int64

NSMAF
False    183
Name: NSMAF, dtype: int64

NSMCE1
False    183
Name: NSMCE1, dtype: int64

NSMCE2
False    183
Name: NSMCE2, dtype: int64

NSMCE4A
False    183
Name: NSMCE4A, dtype: int64

NSUN2
False    183
Name: NSUN2, dtype: int64

NSUN3
False    183
Name: NSUN3, dtype: int64

NSUN4
False    183
Name: NSUN4, dtype: int64

NSUN5P1
False    183
Name: NSUN5P1, dtype: int64

NSUN5P2
False    183
Name: NSUN5P2, dtype: int64

NSUN5
False    183
Name: NSUN5, dtype: int64

NSUN6
False    183
Name: NSUN6, dtype: int64

NSUN7
False    183
Name: NSUN7, dtype: int64

NT5C1A
True     103
False     80
Name: NT5C1A, dtype: int64

NT5C1B
False    161
True      22
Name: NT5C1B, dtype: int64

NT5C2
False    183
Name: NT5C2, dtype: int64

NT5C3L
False    183
Name: NT5C3L, dtype: int64

NT5C3
False    183
Name: NT5C3, dtype: int64

NT5C
False    183
Name: NT5C, dtype: int64

NT5DC1
False    183
Name: NT5DC1, dtype: int64

NT5DC2
False    183
Name: NT5DC2, dtype: int64

NT5DC3
False    183
Name: NT5DC3, dtype: int64

NT5E
False    183
Name: NT5E, dtype: int64

NT5M
False    183
Name: NT5M, dtype: int64

NTAN1
False    183
Name: NTAN1, dtype: int64

NTF3
False    182
True       1
Name: NTF3, dtype: int64

NTF4
False    169
True      14
Name: NTF4, dtype: int64

NTHL1
False    183
Name: NTHL1, dtype: int64

NTM
False    183
Name: NTM, dtype: int64

NTN1
False    183
Name: NTN1, dtype: int64

NTN3
False    121
True      62
Name: NTN3, dtype: int64

NTN4
False    183
Name: NTN4, dtype: int64

NTN5
False    181
True       2
Name: NTN5, dtype: int64

NTNG1
False    180
True       3
Name: NTNG1, dtype: int64

NTNG2
False    182
True       1
Name: NTNG2, dtype: int64

NTRK1
False    181
True       2
Name: NTRK1, dtype: int64

NTRK2
False    183
Name: NTRK2, dtype: int64

NTRK3
False    183
Name: NTRK3, dtype: int64

NTSR1
False    182
True       1
Name: NTSR1, dtype: int64

NTSR2
True     122
False     61
Name: NTSR2, dtype: int64

NTS
False    170
True      13
Name: NTS, dtype: int64

NUAK1
False    183
Name: NUAK1, dtype: int64

NUAK2
False    183
Name: NUAK2, dtype: int64

NUB1
False    183
Name: NUB1, dtype: int64

NUBP1
False    183
Name: NUBP1, dtype: int64

NUBP2
False    183
Name: NUBP2, dtype: int64

NUBPL
False    183
Name: NUBPL, dtype: int64

NUCB1
False    183
Name: NUCB1, dtype: int64

NUCB2
False    183
Name: NUCB2, dtype: int64

NUCKS1
False    183
Name: NUCKS1, dtype: int64

NUDCD1
False    183
Name: NUDCD1, dtype: int64

NUDCD2
False    183
Name: NUDCD2, dtype: int64

NUDCD3
False    183
Name: NUDCD3, dtype: int64

NUDC
False    183
Name: NUDC, dtype: int64

NUDT10
False    182
True       1
Name: NUDT10, dtype: int64

NUDT11
False    183
Name: NUDT11, dtype: int64

NUDT12
False    183
Name: NUDT12, dtype: int64

NUDT13
False    183
Name: NUDT13, dtype: int64

NUDT14
False    183
Name: NUDT14, dtype: int64

NUDT15
False    183
Name: NUDT15, dtype: int64

NUDT16L1
False    183
Name: NUDT16L1, dtype: int64

NUDT16P1
False    183
Name: NUDT16P1, dtype: int64

NUDT16
False    183
Name: NUDT16, dtype: int64

NUDT17
False    183
Name: NUDT17, dtype: int64

NUDT18
False    183
Name: NUDT18, dtype: int64

NUDT19
False    183
Name: NUDT19, dtype: int64

NUDT1
False    183
Name: NUDT1, dtype: int64

NUDT21
False    183
Name: NUDT21, dtype: int64

NUDT22
False    183
Name: NUDT22, dtype: int64

NUDT2
False    183
Name: NUDT2, dtype: int64

NUDT3
False    183
Name: NUDT3, dtype: int64

NUDT4
False    183
Name: NUDT4, dtype: int64

NUDT5
False    183
Name: NUDT5, dtype: int64

NUDT6
False    183
Name: NUDT6, dtype: int64

NUDT7
False    183
Name: NUDT7, dtype: int64

NUDT8
False    183
Name: NUDT8, dtype: int64

NUDT9P1
False    180
True       3
Name: NUDT9P1, dtype: int64

NUDT9
False    183
Name: NUDT9, dtype: int64

NUF2
False    183
Name: NUF2, dtype: int64

NUFIP1
False    183
Name: NUFIP1, dtype: int64

NUFIP2
False    183
Name: NUFIP2, dtype: int64

NUMA1
False    183
Name: NUMA1, dtype: int64

NUMBL
False    183
Name: NUMBL, dtype: int64

NUMB
False    183
Name: NUMB, dtype: int64

NUP107
False    183
Name: NUP107, dtype: int64

NUP133
False    183
Name: NUP133, dtype: int64

NUP153
False    183
Name: NUP153, dtype: int64

NUP155
False    183
Name: NUP155, dtype: int64

NUP160
False    183
Name: NUP160, dtype: int64

NUP188
False    183
Name: NUP188, dtype: int64

NUP205
False    183
Name: NUP205, dtype: int64

NUP210L
False    115
True      68
Name: NUP210L, dtype: int64

NUP210
False    183
Name: NUP210, dtype: int64

NUP214
False    183
Name: NUP214, dtype: int64

NUP35
False    183
Name: NUP35, dtype: int64

NUP37
False    183
Name: NUP37, dtype: int64

NUP43
False    183
Name: NUP43, dtype: int64

NUP50
False    183
Name: NUP50, dtype: int64

NUP54
False    183
Name: NUP54, dtype: int64

NUP62CL
False    183
Name: NUP62CL, dtype: int64

NUP62
False    183
Name: NUP62, dtype: int64

NUP85
False    183
Name: NUP85, dtype: int64

NUP88
False    183
Name: NUP88, dtype: int64

NUP93
False    183
Name: NUP93, dtype: int64

NUP98
False    183
Name: NUP98, dtype: int64

NUPL1
False    183
Name: NUPL1, dtype: int64

NUPL2
False    183
Name: NUPL2, dtype: int64

NUPR1
False    183
Name: NUPR1, dtype: int64

NUS1
False    183
Name: NUS1, dtype: int64

NUSAP1
False    183
Name: NUSAP1, dtype: int64

NUTF2
False    183
Name: NUTF2, dtype: int64

NVL
False    183
Name: NVL, dtype: int64

NWD1
False    183
Name: NWD1, dtype: int64

NXF1
False    183
Name: NXF1, dtype: int64

NXF2
True     96
False    87
Name: NXF2, dtype: int64

NXF3
False    176
True       7
Name: NXF3, dtype: int64

NXNL2
False    174
True       9
Name: NXNL2, dtype: int64

NXN
False    183
Name: NXN, dtype: int64

NXPH1
False    113
True      70
Name: NXPH1, dtype: int64

NXPH2
False    149
True      34
Name: NXPH2, dtype: int64

NXPH3
False    183
Name: NXPH3, dtype: int64

NXPH4
False    183
Name: NXPH4, dtype: int64

NXT1
False    183
Name: NXT1, dtype: int64

NXT2
False    183
Name: NXT2, dtype: int64

NYNRIN
False    183
Name: NYNRIN, dtype: int64

OAF
False    183
Name: OAF, dtype: int64

OAS1
False    183
Name: OAS1, dtype: int64

OAS2
False    183
Name: OAS2, dtype: int64

OAS3
False    183
Name: OAS3, dtype: int64

OASL
False    183
Name: OASL, dtype: int64

OAT
False    183
Name: OAT, dtype: int64

OAZ1
False    183
Name: OAZ1, dtype: int64

OAZ2
False    183
Name: OAZ2, dtype: int64

OAZ3
False    183
Name: OAZ3, dtype: int64

OBFC1
False    183
Name: OBFC1, dtype: int64

OBFC2A
False    183
Name: OBFC2A, dtype: int64

OBFC2B
False    183
Name: OBFC2B, dtype: int64

OBP2A
False    148
True      35
Name: OBP2A, dtype: int64

OBP2B
True     101
False     82
Name: OBP2B, dtype: int64

OBSCN
False    183
Name: OBSCN, dtype: int64

OBSL1
False    183
Name: OBSL1, dtype: int64

OCA2
False    173
True      10
Name: OCA2, dtype: int64

OCEL1
False    183
Name: OCEL1, dtype: int64

OCIAD1
False    183
Name: OCIAD1, dtype: int64

OCIAD2
False    183
Name: OCIAD2, dtype: int64

OCLM
False    169
True      14
Name: OCLM, dtype: int64

OCLN
False    183
Name: OCLN, dtype: int64

OCM
False    147
True      36
Name: OCM, dtype: int64

OCRL
False    183
Name: OCRL, dtype: int64

ODAM
False    173
True      10
Name: ODAM, dtype: int64

ODC1
False    183
Name: ODC1, dtype: int64

ODF2L
False    183
Name: ODF2L, dtype: int64

ODF2
False    183
Name: ODF2, dtype: int64

ODF3B
False    183
Name: ODF3B, dtype: int64

ODF3L1
False    182
True       1
Name: ODF3L1, dtype: int64

ODF3L2
False    165
True      18
Name: ODF3L2, dtype: int64

ODZ1
False    180
True       3
Name: ODZ1, dtype: int64

ODZ2

False    182
True       1
Name: ODZ2, dtype: int64

ODZ3
False    183
Name: ODZ3, dtype: int64

ODZ4
False    183
Name: ODZ4, dtype: int64

OFD1
False    183
Name: OFD1, dtype: int64

OGDHL
False    183
Name: OGDHL, dtype: int64

OGDH
False    183
Name: OGDH, dtype: int64

OGFOD1
False    183
Name: OGFOD1, dtype: int64

OGFOD2
False    183
Name: OGFOD2, dtype: int64

OGFRL1
False    183
Name: OGFRL1, dtype: int64

OGFR
False    183
Name: OGFR, dtype: int64

OGG1
False    183
Name: OGG1, dtype: int64

OGN
False    181
True       2
Name: OGN, dtype: int64

OGT
False    183
Name: OGT, dtype: int64

OIP5
False    183
Name: OIP5, dtype: int64

OIT3
False    171
True      12
Name: OIT3, dtype: int64

OLA1
False    183
Name: OLA1, dtype: int64

OLAH
False    162
True      21
Name: OLAH, dtype: int64

OLFM1
False    183
Name: OLFM1, dtype: int64

OLFM2
False    183
Name: OLFM2, dtype: int64

OLFM3
False    113
True      70
Name: OLFM3, dtype: int64

OLFM4
False    181
True       2
Name: OLFM4, dtype: int64

OLFML1
False    183
Name: OLFML1, dtype: int64

OLFML2A
False    183
Name: OLFML2A, dtype: int64

OLFML2B
False    183
Name: OLFML2B, dtype: int64

OLFML3
False    183
Name: OLFML3, dtype: int64

OLIG1
False    160
True      23
Name: OLIG1, dtype: int64

OLIG2
False    104
True      79
Name: OLIG2, dtype: int64

OLIG3
False    111
True      72
Name: OLIG3, dtype: int64

OLR1
False    183
Name: OLR1, dtype: int64

OMA1
False    183
Name: OMA1, dtype: int64

OMD
False    181
True       2
Name: OMD, dtype: int64

OMG
False    175
True       8
Name: OMG, dtype: int64

OMP
False    152
True      31
Name: OMP, dtype: int64

ONECUT1
False    167
True      16
Name: ONECUT1, dtype: int64

ONECUT2
False    183
Name: ONECUT2, dtype: int64

ONECUT3
False    155
True      28
Name: ONECUT3, dtype: int64

OOEP
False    136
True      47
Name: OOEP, dtype: int64

OPA1
False    183
Name: OPA1, dtype: int64

OPA3
False    183
Name: OPA3, dtype: int64

OPCML
False    180
True       3
Name: OPCML, dtype: int64

OPHN1
False    183
Name: OPHN1, dtype: int64

OPLAH
False    183
Name: OPLAH, dtype: int64

OPN1SW
False    169
True      14
Name: OPN1SW, dtype: int64

OPN3
False    183
Name: OPN3, dtype: int64

OPN4
False    115
True      68
Name: OPN4, dtype: int64

OPRD1
True     103
False     80
Name: OPRD1, dtype: int64

OPRK1
False    108
True      75
Name: OPRK1, dtype: int64

OPRL1
False    183
Name: OPRL1, dtype: int64

OPRM1
True     106
False     77
Name: OPRM1, dtype: int64

OPTN
False    183
Name: OPTN, dtype: int64

OR10AD1
False    119
True      64
Name: OR10AD1, dtype: int64

OR10H1
False    93
True     90
Name: OR10H1, dtype: int64

OR10H5
True     121
False     62
Name: OR10H5, dtype: int64

OR10Q1
True     107
False     76
Name: OR10Q1, dtype: int64

OR13A1
False    177
True       6
Name: OR13A1, dtype: int64

OR13J1
True     101
False     82
Name: OR13J1, dtype: int64

OR1J1
True     117
False     66
Name: OR1J1, dtype: int64

OR1J2
True     94
False    89
Name: OR1J2, dtype: int64

OR1L8
False    128
True      55
Name: OR1L8, dtype: int64

OR1Q1
True     125
False     58
Name: OR1Q1, dtype: int64

OR2A1
False    178
True       5
Name: OR2A1, dtype: int64

OR2A25
False    114
True      69
Name: OR2A25, dtype: int64

OR2A4
False    183
Name: OR2A4, dtype: int64

OR2A7
False    183
Name: OR2A7, dtype: int64

OR2A9P
False    183
Name: OR2A9P, dtype: int64

OR2AG2
True     117
False     66
Name: OR2AG2, dtype: int64

OR2B6
False    120
True      63
Name: OR2B6, dtype: int64

OR2C1
False    117
True      66
Name: OR2C1, dtype: int64

OR2H2
True     92
False    91
Name: OR2H2, dtype: int64

OR2L13
True     100
False     83
Name: OR2L13, dtype: int64

OR2W3
False    141
True      42
Name: OR2W3, dtype: int64

OR3A2
False    99
True     84
Name: OR3A2, dtype: int64

OR4F29
False    101
True      82
Name: OR4F29, dtype: int64

OR51E1
False    182
True       1
Name: OR51E1, dtype: int64

OR51E2
False    182
True       1
Name: OR51E2, dtype: int64

OR52N2
False    128
True      55
Name: OR52N2, dtype: int64

OR52N4
False    137
True      46
Name: OR52N4, dtype: int64

OR56B1
True     110
False     73
Name: OR56B1, dtype: int64

OR56B4
False    105
True      78
Name: OR56B4, dtype: int64

OR5K2
False    127
True      56
Name: OR5K2, dtype: int64

OR7A5
True     109
False     74
Name: OR7A5, dtype: int64

OR7C1
True     128
False     55
Name: OR7C1, dtype: int64

OR7D2
False    160
True      23
Name: OR7D2, dtype: int64

OR7E37P
True     118
False     65
Name: OR7E37P, dtype: int64

OR7E91P
False    164
True      19
Name: OR7E91P, dtype: int64

ORAI1
False    183
Name: ORAI1, dtype: int64

ORAI2
False    183
Name: ORAI2, dtype: int64

ORAI3
False    183
Name: ORAI3, dtype: int64

ORAOV1
False    183
Name: ORAOV1, dtype: int64

ORC1L
False    183
Name: ORC1L, dtype: int64

ORC2L
False    183
Name: ORC2L, dtype: int64

ORC3L
False    183
Name: ORC3L, dtype: int64

ORC4L
False    183
Name: ORC4L, dtype: int64

ORC5L
False    183
Name: ORC5L, dtype: int64

ORC6L
False    183
Name: ORC6L, dtype: int64

ORM1
False    168
True      15
Name: ORM1, dtype: int64

ORM2
False    125
True      58
Name: ORM2, dtype: int64

ORMDL1
False    183
Name: ORMDL1, dtype: int64

ORMDL2
False    183
Name: ORMDL2, dtype: int64

ORMDL3
False    183
Name: ORMDL3, dtype: int64

OS9
False    183
Name: OS9, dtype: int64

OSBP2
False    183
Name: OSBP2, dtype: int64

OSBPL10
False    183
Name: OSBPL10, dtype: int64

OSBPL11
False    183
Name: OSBPL11, dtype: int64

OSBPL1A
False    183
Name: OSBPL1A, dtype: int64

OSBPL2
False    183
Name: OSBPL2, dtype: int64

OSBPL3
False    183
Name: OSBPL3, dtype: int64

OSBPL5
False    183
Name: OSBPL5, dtype: int64

OSBPL6
False    183
Name: OSBPL6, dtype: int64

OSBPL7
False    183
Name: OSBPL7, dtype: int64

OSBPL8
False    183
Name: OSBPL8, dtype: int64

OSBPL9
False    183
Name: OSBPL9, dtype: int64

OSBP
False    183
Name: OSBP, dtype: int64

OSCAR
False    183
Name: OSCAR, dtype: int64

OSCP1
False    183
Name: OSCP1, dtype: int64

OSGEPL1
False    183
Name: OSGEPL1, dtype: int64

OSGEP
False    183
Name: OSGEP, dtype: int64

OSGIN1
False    183
Name: OSGIN1, dtype: int64

OSGIN2
False    183
Name: OSGIN2, dtype: int64

OSMR
False    183
Name: OSMR, dtype: int64

OSM
False    183
Name: OSM, dtype: int64

OSR1
False    182
True       1
Name: OSR1, dtype: int64

OSR2
False    182
True       1
Name: OSR2, dtype: int64

OST4
False    183
Name: OST4, dtype: int64

OSTBETA
False    145
True      38
Name: OSTBETA, dtype: int64

OSTCL
False    183
Name: OSTCL, dtype: int64

OSTC
False    183
Name: OSTC, dtype: int64

OSTF1
False    183
Name: OSTF1, dtype: int64

OSTM1
False    183
Name: OSTM1, dtype: int64

OSTalpha
False    183
Name: OSTalpha, dtype: int64

OTC
False    151
True      32
Name: OTC, dtype: int64

OTOA
False    183
Name: OTOA, dtype: int64

OTOF
False    182
True       1
Name: OTOF, dtype: int64

OTOP3
False    123
True      60
Name: OTOP3, dtype: int64

OTOR
False    108
True      75
Name: OTOR, dtype: int64

OTP
True     99
False    84
Name: OTP, dtype: int64

OTUB1
False    183
Name: OTUB1, dtype: int64

OTUB2
False    183
Name: OTUB2, dtype: int64

OTUD1
False    183
Name: OTUD1, dtype: int64

OTUD3
False    183
Name: OTUD3, dtype: int64

OTUD4
False    183
Name: OTUD4, dtype: int64

OTUD5
False    183
Name: OTUD5, dtype: int64

OTUD6B
False    183
Name: OTUD6B, dtype: int64

OTUD7A
False    183
Name: OTUD7A, dtype: int64

OTUD7B
False    183
Name: OTUD7B, dtype: int64

OTX1
False    183
Name: OTX1, dtype: int64

OVCA2
False    183
Name: OVCA2, dtype: int64

OVCH1
True     93
False    90
Name: OVCH1, dtype: int64

OVCH2
True     122
False     61
Name: OVCH2, dtype: int64

OVGP1
False    183
Name: OVGP1, dtype: int64

OVOL1
False    181
True       2
Name: OVOL1, dtype: int64

OVOL2
False    183
Name: OVOL2, dtype: int64

OXA1L
False    183
Name: OXA1L, dtype: int64

OXCT1
False    183
Name: OXCT1, dtype: int64

OXCT2
False    183
Name: OXCT2, dtype: int64

OXER1
False    183
Name: OXER1, dtype: int64

OXGR1
False    168
True      15
Name: OXGR1, dtype: int64

OXNAD1
False    183
Name: OXNAD1, dtype: int64

OXR1
False    183
Name: OXR1, dtype: int64

OXSM
False    183
Name: OXSM, dtype: int64

OXSR1
False    183
Name: OXSR1, dtype: int64

OXTR
False    183
Name: OXTR, dtype: int64

OXT
False    131
True      52
Name: OXT, dtype: int64

P2RX1
False    183
Name: P2RX1, dtype: int64

P2RX2
False    158
True      25
Name: P2RX2, dtype: int64

P2RX3
False    122
True      61
Name: P2RX3, dtype: int64

P2RX4
False    183
Name: P2RX4, dtype: int64

P2RX5
False    183
Name: P2RX5, dtype: int64

P2RX6

False    183
Name: P2RX6, dtype: int64

P2RX7
False    182
True       1
Name: P2RX7, dtype: int64

P2RY10
False    183
Name: P2RY10, dtype: int64

P2RY11
False    182
True       1
Name: P2RY11, dtype: int64

P2RY12
False    180
True       3
Name: P2RY12, dtype: int64

P2RY13
False    183
Name: P2RY13, dtype: int64

P2RY14
False    182
True       1
Name: P2RY14, dtype: int64

P2RY1
False    183
Name: P2RY1, dtype: int64

P2RY2
False    182
True       1
Name: P2RY2, dtype: int64

P2RY4
False    140
True      43
Name: P2RY4, dtype: int64

P2RY6
False    183
Name: P2RY6, dtype: int64

P2RY8
False    183
Name: P2RY8, dtype: int64

P4HA1
False    183
Name: P4HA1, dtype: int64

P4HA2
False    183
Name: P4HA2, dtype: int64

P4HA3
False    183
Name: P4HA3, dtype: int64

P4HB
False    183
Name: P4HB, dtype: int64

P4HTM
False    183
Name: P4HTM, dtype: int64

P704P
False    183
Name: P704P, dtype: int64

PA2G4P4
False    183
Name: PA2G4P4, dtype: int64

PA2G4
False    183
Name: PA2G4, dtype: int64

PAAF1
False    183
Name: PAAF1, dtype: int64

PABPC1L2B
True     106
False     77
Name: PABPC1L2B, dtype: int64

PABPC1L
False    183
Name: PABPC1L, dtype: int64

PABPC1P2
False    95
True     88
Name: PABPC1P2, dtype: int64

PABPC1
False    183
Name: PABPC1, dtype: int64

PABPC3
False    183
Name: PABPC3, dtype: int64

PABPC4L
False    182
True       1
Name: PABPC4L, dtype: int64

PABPC4
False    183
Name: PABPC4, dtype: int64

PABPC5
False    182
True       1
Name: PABPC5, dtype: int64

PABPN1L
True     123
False     60
Name: PABPN1L, dtype: int64

PABPN1
False    183
Name: PABPN1, dtype: int64

PACRGL
False    183
Name: PACRGL, dtype: int64

PACRG
False    183
Name: PACRG, dtype: int64

PACS1
False    183
Name: PACS1, dtype: int64

PACS2
False    183
Name: PACS2, dtype: int64

PACSIN1
False    183
Name: PACSIN1, dtype: int64

PACSIN2
False    183
Name: PACSIN2, dtype: int64

PACSIN3
False    183
Name: PACSIN3, dtype: int64

PADI1
False    180
True       3
Name: PADI1, dtype: int64

PADI2
False    183
Name: PADI2, dtype: int64

PADI3
False    164
True      19
Name: PADI3, dtype: int64

PADI4
False    164
True      19
Name: PADI4, dtype: int64

PAEP
False    170
True      13
Name: PAEP, dtype: int64

PAF1
False    183
Name: PAF1, dtype: int64

PAFAH1B1
False    183
Name: PAFAH1B1, dtype: int64

PAFAH1B2
False    183
Name: PAFAH1B2, dtype: int64

PAFAH1B3
False    183
Name: PAFAH1B3, dtype: int64

PAFAH2
False    183
Name: PAFAH2, dtype: int64

PAG1
False    183
Name: PAG1, dtype: int64

PAGE2B
True     102
False     81
Name: PAGE2B, dtype: int64

PAH
False    170
True      13
Name: PAH, dtype: int64

PAICS
False    183
Name: PAICS, dtype: int64

PAIP1
False    183
Name: PAIP1, dtype: int64

PAIP2B
False    183
Name: PAIP2B, dtype: int64

PAIP2
False    183
Name: PAIP2, dtype: int64

PAK1IP1
False    183
Name: PAK1IP1, dtype: int64

PAK1
False    183
Name: PAK1, dtype: int64

PAK2
False    183
Name: PAK2, dtype: int64

PAK3
False    183
Name: PAK3, dtype: int64

PAK4
False    183
Name: PAK4, dtype: int64

PAK6
False    183
Name: PAK6, dtype: int64

PAK7
False    173
True      10
Name: PAK7, dtype: int64

PALB2
False    183
Name: PALB2, dtype: int64

PALLD
False    183
Name: PALLD, dtype: int64

PALM2-AKAP2
False    183
Name: PALM2-AKAP2, dtype: int64

PALM2
False    183
Name: PALM2, dtype: int64

PALM3
False    183
Name: PALM3, dtype: int64

PALMD
False    183
Name: PALMD, dtype: int64

PALM
False    183
Name: PALM, dtype: int64

PAMR1
False    183
Name: PAMR1, dtype: int64

PAM
False    183
Name: PAM, dtype: int64

PAN2
False    183
Name: PAN2, dtype: int64

PAN3
False    183
Name: PAN3, dtype: int64

PANK1
False    183
Name: PANK1, dtype: int64

PANK2
False    183
Name: PANK2, dtype: int64

PANK3
False    183
Name: PANK3, dtype: int64

PANK4
False    183
Name: PANK4, dtype: int64

PANX1
False    183
Name: PANX1, dtype: int64

PANX2
False    183
Name: PANX2, dtype: int64

PAOX
False    183
Name: PAOX, dtype: int64

PAPD4
False    183
Name: PAPD4, dtype: int64

PAPD5
False    183
Name: PAPD5, dtype: int64

PAPD7
False    183
Name: PAPD7, dtype: int64

PAPLN
False    183
Name: PAPLN, dtype: int64

PAPL
False    160
True      23
Name: PAPL, dtype: int64

PAPOLA
False    183
Name: PAPOLA, dtype: int64

PAPOLB
True     114
False     69
Name: PAPOLB, dtype: int64

PAPOLG
False    183
Name: PAPOLG, dtype: int64

PAPPA2
False    176
True       7
Name: PAPPA2, dtype: int64

PAPPA
False    183
Name: PAPPA, dtype: int64

PAPSS1
False    183
Name: PAPSS1, dtype: int64

PAPSS2
False    183
Name: PAPSS2, dtype: int64

PAQR3
False    183
Name: PAQR3, dtype: int64

PAQR4
False    183
Name: PAQR4, dtype: int64

PAQR5
False    183
Name: PAQR5, dtype: int64

PAQR6
False    183
Name: PAQR6, dtype: int64

PAQR7
False    183
Name: PAQR7, dtype: int64

PAQR8
False    183
Name: PAQR8, dtype: int64

PAQR9
False    108
True      75
Name: PAQR9, dtype: int64

PAR-SN
False    183
Name: PAR-SN, dtype: int64

PAR1
False    136
True      47
Name: PAR1, dtype: int64

PAR5
False    175
True       8
Name: PAR5, dtype: int64

PARD3B
False    183
Name: PARD3B, dtype: int64

PARD3
False    183
Name: PARD3, dtype: int64

PARD6A
False    183
Name: PARD6A, dtype: int64

PARD6B
False    183
Name: PARD6B, dtype: int64

PARD6G
False    183
Name: PARD6G, dtype: int64

PARG
False    183
Name: PARG, dtype: int64

PARK2
False    183
Name: PARK2, dtype: int64

PARK7
False    183
Name: PARK7, dtype: int64

PARL
False    183
Name: PARL, dtype: int64

PARM1
False    183
Name: PARM1, dtype: int64

PARN
False    183
Name: PARN, dtype: int64

PARP10
False    183
Name: PARP10, dtype: int64

PARP11
False    183
Name: PARP11, dtype: int64

PARP12
False    183
Name: PARP12, dtype: int64

PARP14
False    183
Name: PARP14, dtype: int64

PARP15
False    183
Name: PARP15, dtype: int64

PARP16
False    183
Name: PARP16, dtype: int64

PARP1
False    183
Name: PARP1, dtype: int64

PARP2
False    183
Name: PARP2, dtype: int64

PARP3
False    183
Name: PARP3, dtype: int64

PARP4
False    183
Name: PARP4, dtype: int64

PARP6
False    183
Name: PARP6, dtype: int64

PARP8
False    183
Name: PARP8, dtype: int64

PARP9
False    183
Name: PARP9, dtype: int64

PARS2
False    183
Name: PARS2, dtype: int64

PART1
False    170
True      13
Name: PART1, dtype: int64

PARVA
False    183
Name: PARVA, dtype: int64

PARVB
False    183
Name: PARVB, dtype: int64

PARVG
False    183
Name: PARVG, dtype: int64

PASK
False    183
Name: PASK, dtype: int64

PATE2
True     126
False     57
Name: PATE2, dtype: int64

PATL1
False    183
Name: PATL1, dtype: int64

PATL2
False    181
True       2
Name: PATL2, dtype: int64

PATZ1
False    183
Name: PATZ1, dtype: int64

PAWR
False    183
Name: PAWR, dtype: int64

PAX1
True     101
False     82
Name: PAX1, dtype: int64

PAX2
False    143
True      40
Name: PAX2, dtype: int64

PAX3
True     123
False     60
Name: PAX3, dtype: int64

PAX4
False    132
True      51
Name: PAX4, dtype: int64

PAX5
False    163
True      20
Name: PAX5, dtype: int64

PAX6
False    183
Name: PAX6, dtype: int64

PAX7
True     111
False     72
Name: PAX7, dtype: int64

PAX8
False    183
Name: PAX8, dtype: int64

PAX9
False    179
True       4
Name: PAX9, dtype: int64

PAXIP1
False    183
Name: PAXIP1, dtype: int64

PBK
False    183
Name: PBK, dtype: int64

PBLD
False    183
Name: PBLD, dtype: int64

PBOV1
True     110
False     73
Name: PBOV1, dtype: int64

PBRM1
False    183
Name: PBRM1, dtype: int64

PBX1
False    183
Name: PBX1, dtype: int64

PBX2
False    183
Name: PBX2, dtype: int64

PBX3
False    183
Name: PBX3, dtype: int64

PBX4
False    182
True       1
Name: PBX4, dtype: int64

PBXIP1
False    183
Name: PBXIP1, dtype: int64

PCA3
True     125
False     58
Name: PCA3, dtype: int64

PCBD1
False    183
Name: PCBD1, dtype: int64

PCBD2
False    183
Name: PCBD2, dtype: int64

PCBP1
False    183
Name: PCBP1, dtype: int64

PCBP2
False    183
Name: PCBP2, dtype: int64

PCBP3
False    183
Name: PCBP3, dtype: int64

PCBP4
False    183
Name: PCBP4, dtype: int64

PCCA
False    183
Name: PCCA, dtype: int64

PCCB
False    183
Name: PCCB, dtype: int64

PCDH10
False    183
Name: PCDH10, dtype: int64

PCDH11X
False    129
True      54
Name: PCDH11X, dtype: int64

PCDH11Y
True     128
False     55
Name: PCDH11Y, dtype: int64

PCDH12
False    183
Name: PCDH12, dtype: int64

PCDH15
True     97
False    86
Name: PCDH15, dtype: int64

PCDH17
False    183
Name: PCDH17, dtype: int64

PCDH18
False    183
Name: PCDH18, dtype: int64

PCDH19
False    183
Name: PCDH19, dtype: int64

PCDH1
False    183
Name: PCDH1, dtype: int64

PCDH20

False    179
True       4
Name: PCDH20, dtype: int64

PCDH7
False    183
Name: PCDH7, dtype: int64

PCDH8
False    157
True      26
Name: PCDH8, dtype: int64

PCDH9
False    183
Name: PCDH9, dtype: int64

PCDHA10
False    174
True       9
Name: PCDHA10, dtype: int64

PCDHA11
False    179
True       4
Name: PCDHA11, dtype: int64

PCDHA12
False    179
True       4
Name: PCDHA12, dtype: int64

PCDHA13
False    169
True      14
Name: PCDHA13, dtype: int64

PCDHA1
False    170
True      13
Name: PCDHA1, dtype: int64

PCDHA2
False    179
True       4
Name: PCDHA2, dtype: int64

PCDHA3
False    181
True       2
Name: PCDHA3, dtype: int64

PCDHA4
False    181
True       2
Name: PCDHA4, dtype: int64

PCDHA5
False    174
True       9
Name: PCDHA5, dtype: int64

PCDHA6
False    178
True       5
Name: PCDHA6, dtype: int64

PCDHA7
False    180
True       3
Name: PCDHA7, dtype: int64

PCDHA8
False    160
True      23
Name: PCDHA8, dtype: int64

PCDHA9
False    150
True      33
Name: PCDHA9, dtype: int64

PCDHAC1
False    177
True       6
Name: PCDHAC1, dtype: int64

PCDHAC2
False    182
True       1
Name: PCDHAC2, dtype: int64

PCDHB10
False    183
Name: PCDHB10, dtype: int64

PCDHB11
False    183
Name: PCDHB11, dtype: int64

PCDHB12
False    183
Name: PCDHB12, dtype: int64

PCDHB13
False    183
Name: PCDHB13, dtype: int64

PCDHB14
False    183
Name: PCDHB14, dtype: int64

PCDHB15
False    183
Name: PCDHB15, dtype: int64

PCDHB16
False    183
Name: PCDHB16, dtype: int64

PCDHB17
False    181
True       2
Name: PCDHB17, dtype: int64

PCDHB18
False    182
True       1
Name: PCDHB18, dtype: int64

PCDHB19P
False    183
Name: PCDHB19P, dtype: int64

PCDHB1
False    119
True      64
Name: PCDHB1, dtype: int64

PCDHB2
False    183
Name: PCDHB2, dtype: int64

PCDHB3
False    183
Name: PCDHB3, dtype: int64

PCDHB4
False    183
Name: PCDHB4, dtype: int64

PCDHB5
False    183
Name: PCDHB5, dtype: int64

PCDHB6
False    183
Name: PCDHB6, dtype: int64

PCDHB7
False    183
Name: PCDHB7, dtype: int64

PCDHB8
False    183
Name: PCDHB8, dtype: int64

PCDHB9
False    183
Name: PCDHB9, dtype: int64

PCDHGA10
False    183
Name: PCDHGA10, dtype: int64

PCDHGA11
False    182
True       1
Name: PCDHGA11, dtype: int64

PCDHGA12
False    183
Name: PCDHGA12, dtype: int64

PCDHGA1
False    182
True       1
Name: PCDHGA1, dtype: int64

PCDHGA2
False    182
True       1
Name: PCDHGA2, dtype: int64

PCDHGA3
False    181
True       2
Name: PCDHGA3, dtype: int64

PCDHGA4
False    182
True       1
Name: PCDHGA4, dtype: int64

PCDHGA5
False    182
True       1
Name: PCDHGA5, dtype: int64

PCDHGA6
False    182
True       1
Name: PCDHGA6, dtype: int64

PCDHGA7
False    182
True       1
Name: PCDHGA7, dtype: int64

PCDHGA8
False    182
True       1
Name: PCDHGA8, dtype: int64

PCDHGA9
False    182
True       1
Name: PCDHGA9, dtype: int64

PCDHGB1
False    182
True       1
Name: PCDHGB1, dtype: int64

PCDHGB2
False    183
Name: PCDHGB2, dtype: int64

PCDHGB3
False    181
True       2
Name: PCDHGB3, dtype: int64

PCDHGB4
False    183
Name: PCDHGB4, dtype: int64

PCDHGB5
False    183
Name: PCDHGB5, dtype: int64

PCDHGB6
False    183
Name: PCDHGB6, dtype: int64

PCDHGB7
False    183
Name: PCDHGB7, dtype: int64

PCDHGB8P
False    167
True      16
Name: PCDHGB8P, dtype: int64

PCDHGC3
False    183
Name: PCDHGC3, dtype: int64

PCDHGC4
False    174
True       9
Name: PCDHGC4, dtype: int64

PCDHGC5
False    181
True       2
Name: PCDHGC5, dtype: int64

PCDP1
False    180
True       3
Name: PCDP1, dtype: int64

PCF11
False    183
Name: PCF11, dtype: int64

PCGF1
False    183
Name: PCGF1, dtype: int64

PCGF2
False    183
Name: PCGF2, dtype: int64

PCGF3
False    183
Name: PCGF3, dtype: int64

PCGF5
False    183
Name: PCGF5, dtype: int64

PCGF6
False    183
Name: PCGF6, dtype: int64

PCID2
False    183
Name: PCID2, dtype: int64

PCIF1
False    183
Name: PCIF1, dtype: int64

PCK1
False    182
True       1
Name: PCK1, dtype: int64

PCK2
False    183
Name: PCK2, dtype: int64

PCLO
False    183
Name: PCLO, dtype: int64

PCM1
False    183
Name: PCM1, dtype: int64

PCMT1
False    183
Name: PCMT1, dtype: int64

PCMTD1
False    183
Name: PCMTD1, dtype: int64

PCMTD2
False    183
Name: PCMTD2, dtype: int64

PCNA
False    183
Name: PCNA, dtype: int64

PCNP
False    183
Name: PCNP, dtype: int64

PCNT
False    183
Name: PCNT, dtype: int64

PCNXL2
False    183
Name: PCNXL2, dtype: int64

PCNXL3
False    183
Name: PCNXL3, dtype: int64

PCNX
False    183
Name: PCNX, dtype: int64

PCOLCE2
False    183
Name: PCOLCE2, dtype: int64

PCOLCE
False    183
Name: PCOLCE, dtype: int64

PCOTH
False    183
Name: PCOTH, dtype: int64

PCP2
False    173
True      10
Name: PCP2, dtype: int64

PCP4L1
False    176
True       7
Name: PCP4L1, dtype: int64

PCP4
False    179
True       4
Name: PCP4, dtype: int64

PCSK1N
False    183
Name: PCSK1N, dtype: int64

PCSK1
False    183
Name: PCSK1, dtype: int64

PCSK2
False    177
True       6
Name: PCSK2, dtype: int64

PCSK4
False    183
Name: PCSK4, dtype: int64

PCSK5
False    183
Name: PCSK5, dtype: int64

PCSK6
False    183
Name: PCSK6, dtype: int64

PCSK7
False    183
Name: PCSK7, dtype: int64

PCSK9
False    183
Name: PCSK9, dtype: int64

PCTP
False    183
Name: PCTP, dtype: int64

PCYOX1L
False    183
Name: PCYOX1L, dtype: int64

PCYOX1
False    183
Name: PCYOX1, dtype: int64

PCYT1A
False    183
Name: PCYT1A, dtype: int64

PCYT1B
False    182
True       1
Name: PCYT1B, dtype: int64

PCYT2
False    183
Name: PCYT2, dtype: int64

PC
False    183
Name: PC, dtype: int64

PDAP1
False    183
Name: PDAP1, dtype: int64

PDCD10
False    183
Name: PDCD10, dtype: int64

PDCD11
False    183
Name: PDCD11, dtype: int64

PDCD1LG2
False    183
Name: PDCD1LG2, dtype: int64

PDCD1
False    183
Name: PDCD1, dtype: int64

PDCD2L
False    183
Name: PDCD2L, dtype: int64

PDCD2
False    183
Name: PDCD2, dtype: int64

PDCD4
False    183
Name: PDCD4, dtype: int64

PDCD5
False    183
Name: PDCD5, dtype: int64

PDCD6IP
False    183
Name: PDCD6IP, dtype: int64

PDCD6
False    183
Name: PDCD6, dtype: int64

PDCD7
False    183
Name: PDCD7, dtype: int64

PDCL3
False    183
Name: PDCL3, dtype: int64

PDCL
False    183
Name: PDCL, dtype: int64

PDC
False    109
True      74
Name: PDC, dtype: int64

PDDC1
False    183
Name: PDDC1, dtype: int64

PDE10A
False    183
Name: PDE10A, dtype: int64

PDE11A
False    183
Name: PDE11A, dtype: int64

PDE12
False    183
Name: PDE12, dtype: int64

PDE1A
False    183
Name: PDE1A, dtype: int64

PDE1B
False    183
Name: PDE1B, dtype: int64

PDE1C
False    180
True       3
Name: PDE1C, dtype: int64

PDE2A
False    183
Name: PDE2A, dtype: int64

PDE3A
False    183
Name: PDE3A, dtype: int64

PDE3B
False    183
Name: PDE3B, dtype: int64

PDE4A
False    183
Name: PDE4A, dtype: int64

PDE4B
False    183
Name: PDE4B, dtype: int64

PDE4C
False    183
Name: PDE4C, dtype: int64

PDE4DIP
False    183
Name: PDE4DIP, dtype: int64

PDE4D
False    183
Name: PDE4D, dtype: int64

PDE5A
False    183
Name: PDE5A, dtype: int64

PDE6A
False    179
True       4
Name: PDE6A, dtype: int64

PDE6B
False    182
True       1
Name: PDE6B, dtype: int64

PDE6C
True     110
False     73
Name: PDE6C, dtype: int64

PDE6D
False    183
Name: PDE6D, dtype: int64

PDE6G
False    183
Name: PDE6G, dtype: int64

PDE7A
False    183
Name: PDE7A, dtype: int64

PDE7B
False    183
Name: PDE7B, dtype: int64

PDE8A
False    183
Name: PDE8A, dtype: int64

PDE8B
False    183
Name: PDE8B, dtype: int64

PDE9A
False    183
Name: PDE9A, dtype: int64

PDF
False    183
Name: PDF, dtype: int64

PDGFA
False    183
Name: PDGFA, dtype: int64

PDGFB
False    183
Name: PDGFB, dtype: int64

PDGFC
False    183
Name: PDGFC, dtype: int64

PDGFD
False    183
Name: PDGFD, dtype: int64

PDGFRA
False    183
Name: PDGFRA, dtype: int64

PDGFRB
False    183
Name: PDGFRB, dtype: int64

PDGFRL
False    183
Name: PDGFRL, dtype: int64

PDHA1
False    183
Name: PDHA1, dtype: int64

PDHB
False    183
Name: PDHB, dtype: int64

PDHX
False    183
Name: PDHX, dtype: int64

PDIA2
False    182
True       1
Name: PDIA2, dtype: int64

PDIA3P
False    183
Name: PDIA3P, dtype: int64

PDIA3
False    183
Name: PDIA3, dtype: int64

PDIA4
False    183
Name: PDIA4, dtype: int64

PDIA5
False    183
Name: PDIA5, dtype: int64

PDIA6
False    183
Name: PDIA6, dtype: int64

PDIK1L
False    183
Name: PDIK1L, dtype: int64

PDK1
False    183
Name: PDK1, dtype: int64

PDK2
False    183
Name: PDK2, dtype: int64

PDK3
False    183
Name: PDK3, dtype: int64

PDK4
False    183
Name: PDK4, dtype: int64

PDLIM1
False    183
Name: PDLIM1, dtype: int64

PDLIM2
False    183
Name: PDLIM2, dtype: int64

PDLIM3
False    183
Name: PDLIM3, dtype: int64

PDLIM4
False    183
Name: PDLIM4, dtype: int64

PDLIM5
False    183
Name: PDLIM5, dtype: int64

PDLIM7
False    183
Name: PDLIM7, dtype: int64

PDP1

False    183
Name: PDP1, dtype: int64

PDP2
False    183
Name: PDP2, dtype: int64

PDPK1
False    183
Name: PDPK1, dtype: int64

PDPN
False    183
Name: PDPN, dtype: int64

PDPR
False    183
Name: PDPR, dtype: int64

PDRG1
False    183
Name: PDRG1, dtype: int64

PDS5A
False    183
Name: PDS5A, dtype: int64

PDS5B
False    183
Name: PDS5B, dtype: int64

PDSS1
False    183
Name: PDSS1, dtype: int64

PDSS2
False    183
Name: PDSS2, dtype: int64

PDX1
False    182
True       1
Name: PDX1, dtype: int64

PDXDC1
False    183
Name: PDXDC1, dtype: int64

PDXDC2
False    183
Name: PDXDC2, dtype: int64

PDXK
False    183
Name: PDXK, dtype: int64

PDXP
False    183
Name: PDXP, dtype: int64

PDZD11
False    183
Name: PDZD11, dtype: int64

PDZD2
False    183
Name: PDZD2, dtype: int64

PDZD3
False    179
True       4
Name: PDZD3, dtype: int64

PDZD4
False    183
Name: PDZD4, dtype: int64

PDZD7
False    183
Name: PDZD7, dtype: int64

PDZD8
False    183
Name: PDZD8, dtype: int64

PDZD9
False    120
True      63
Name: PDZD9, dtype: int64

PDZK1IP1
False    183
Name: PDZK1IP1, dtype: int64

PDZK1P1
False    181
True       2
Name: PDZK1P1, dtype: int64

PDZK1
False    183
Name: PDZK1, dtype: int64

PDZRN3
False    183
Name: PDZRN3, dtype: int64

PDZRN4
False    180
True       3
Name: PDZRN4, dtype: int64

PEA15
False    183
Name: PEA15, dtype: int64

PEAR1
False    183
Name: PEAR1, dtype: int64

PEBP1
False    183
Name: PEBP1, dtype: int64

PEBP4
False    169
True      14
Name: PEBP4, dtype: int64

PECAM1
False    183
Name: PECAM1, dtype: int64

PECI
False    183
Name: PECI, dtype: int64

PECR
False    183
Name: PECR, dtype: int64

PEF1
False    183
Name: PEF1, dtype: int64

PEG10
False    183
Name: PEG10, dtype: int64

PEG3
False    183
Name: PEG3, dtype: int64

PELI1
False    183
Name: PELI1, dtype: int64

PELI2
False    183
Name: PELI2, dtype: int64

PELI3
False    183
Name: PELI3, dtype: int64

PELO
False    183
Name: PELO, dtype: int64

PELP1
False    183
Name: PELP1, dtype: int64

PEMT
False    183
Name: PEMT, dtype: int64

PENK
False    180
True       3
Name: PENK, dtype: int64

PEPD
False    183
Name: PEPD, dtype: int64

PER1
False    183
Name: PER1, dtype: int64

PER2
False    183
Name: PER2, dtype: int64

PER3
False    183
Name: PER3, dtype: int64

PERP
False    183
Name: PERP, dtype: int64

PES1
False    183
Name: PES1, dtype: int64

PET112L
False    183
Name: PET112L, dtype: int64

PEX10
False    183
Name: PEX10, dtype: int64

PEX11A
False    183
Name: PEX11A, dtype: int64

PEX11B
False    183
Name: PEX11B, dtype: int64

PEX11G
False    183
Name: PEX11G, dtype: int64

PEX12
False    183
Name: PEX12, dtype: int64

PEX13
False    183
Name: PEX13, dtype: int64

PEX14
False    183
Name: PEX14, dtype: int64

PEX16
False    183
Name: PEX16, dtype: int64

PEX19
False    183
Name: PEX19, dtype: int64

PEX1
False    183
Name: PEX1, dtype: int64

PEX26
False    183
Name: PEX26, dtype: int64

PEX2
False    183
Name: PEX2, dtype: int64

PEX3
False    183
Name: PEX3, dtype: int64

PEX5L
False    157
True      26
Name: PEX5L, dtype: int64

PEX5
False    183
Name: PEX5, dtype: int64

PEX6
False    183
Name: PEX6, dtype: int64

PEX7
False    183
Name: PEX7, dtype: int64

PF4V1
False    148
True      35
Name: PF4V1, dtype: int64

PF4
False    173
True      10
Name: PF4, dtype: int64

PFAS
False    183
Name: PFAS, dtype: int64

PFDN1
False    183
Name: PFDN1, dtype: int64

PFDN2
False    183
Name: PFDN2, dtype: int64

PFDN4
False    183
Name: PFDN4, dtype: int64

PFDN5
False    183
Name: PFDN5, dtype: int64

PFDN6
False    183
Name: PFDN6, dtype: int64

PFKFB1
False    177
True       6
Name: PFKFB1, dtype: int64

PFKFB2
False    183
Name: PFKFB2, dtype: int64

PFKFB3
False    183
Name: PFKFB3, dtype: int64

PFKFB4
False    183
Name: PFKFB4, dtype: int64

PFKL
False    183
Name: PFKL, dtype: int64

PFKM
False    183
Name: PFKM, dtype: int64

PFKP
False    183
Name: PFKP, dtype: int64

PFN1
False    183
Name: PFN1, dtype: int64

PFN2
False    183
Name: PFN2, dtype: int64

PFN4
False    183
Name: PFN4, dtype: int64

PGA3
False    149
True      34
Name: PGA3, dtype: int64

PGA4
True     105
False     78
Name: PGA4, dtype: int64

PGA5
False    92
True     91
Name: PGA5, dtype: int64

PGAM1
False    183
Name: PGAM1, dtype: int64

PGAM2
False    183
Name: PGAM2, dtype: int64

PGAM4
False    183
Name: PGAM4, dtype: int64

PGAM5
False    183
Name: PGAM5, dtype: int64

PGAP1
False    183
Name: PGAP1, dtype: int64

PGAP2
False    183
Name: PGAP2, dtype: int64

PGAP3
False    183
Name: PGAP3, dtype: int64

PGBD1
False    183
Name: PGBD1, dtype: int64

PGBD2
False    183
Name: PGBD2, dtype: int64

PGBD3
False    183
Name: PGBD3, dtype: int64

PGBD4
False    183
Name: PGBD4, dtype: int64

PGBD5
False    183
Name: PGBD5, dtype: int64

PGCP
False    183
Name: PGCP, dtype: int64

PGC
False    173
True      10
Name: PGC, dtype: int64

PGD
False    183
Name: PGD, dtype: int64

PGF
False    183
Name: PGF, dtype: int64

PGGT1B
False    183
Name: PGGT1B, dtype: int64

PGK1
False    183
Name: PGK1, dtype: int64

PGLS
False    183
Name: PGLS, dtype: int64

PGLYRP1
False    111
True      72
Name: PGLYRP1, dtype: int64

PGLYRP2
False    104
True      79
Name: PGLYRP2, dtype: int64

PGLYRP3
True     92
False    91
Name: PGLYRP3, dtype: int64

PGLYRP4
False    151
True      32
Name: PGLYRP4, dtype: int64

PGM1
False    183
Name: PGM1, dtype: int64

PGM2L1
False    183
Name: PGM2L1, dtype: int64

PGM2
False    183
Name: PGM2, dtype: int64

PGM3
False    183
Name: PGM3, dtype: int64

PGM5P2
False    175
True       8
Name: PGM5P2, dtype: int64

PGM5
False    183
Name: PGM5, dtype: int64

PGPEP1L
True     110
False     73
Name: PGPEP1L, dtype: int64

PGPEP1
False    183
Name: PGPEP1, dtype: int64

PGP
False    183
Name: PGP, dtype: int64

PGRMC1
False    183
Name: PGRMC1, dtype: int64

PGRMC2
False    183
Name: PGRMC2, dtype: int64

PGR
False    182
True       1
Name: PGR, dtype: int64

PGS1
False    183
Name: PGS1, dtype: int64

PHACTR1
False    182
True       1
Name: PHACTR1, dtype: int64

PHACTR2
False    183
Name: PHACTR2, dtype: int64

PHACTR3
False    180
True       3
Name: PHACTR3, dtype: int64

PHACTR4
False    183
Name: PHACTR4, dtype: int64

PHAX
False    183
Name: PHAX, dtype: int64

PHB2
False    183
Name: PHB2, dtype: int64

PHB
False    183
Name: PHB, dtype: int64

PHC1
False    183
Name: PHC1, dtype: int64

PHC2
False    183
Name: PHC2, dtype: int64

PHC3
False    183
Name: PHC3, dtype: int64

PHEX
False    167
True      16
Name: PHEX, dtype: int64

PHF10
False    183
Name: PHF10, dtype: int64

PHF11
False    183
Name: PHF11, dtype: int64

PHF12
False    183
Name: PHF12, dtype: int64

PHF13
False    183
Name: PHF13, dtype: int64

PHF14
False    183
Name: PHF14, dtype: int64

PHF15
False    183
Name: PHF15, dtype: int64

PHF16
False    183
Name: PHF16, dtype: int64

PHF17
False    183
Name: PHF17, dtype: int64

PHF19
False    183
Name: PHF19, dtype: int64

PHF1
False    183
Name: PHF1, dtype: int64

PHF20L1
False    183
Name: PHF20L1, dtype: int64

PHF20
False    183
Name: PHF20, dtype: int64

PHF21A
False    183
Name: PHF21A, dtype: int64

PHF21B
False    178
True       5
Name: PHF21B, dtype: int64

PHF23
False    183
Name: PHF23, dtype: int64

PHF2
False    183
Name: PHF2, dtype: int64

PHF3
False    183
Name: PHF3, dtype: int64

PHF5A
False    183
Name: PHF5A, dtype: int64

PHF6
False    183
Name: PHF6, dtype: int64

PHF7
False    183
Name: PHF7, dtype: int64

PHF8
False    183
Name: PHF8, dtype: int64

PHGDH
False    183
Name: PHGDH, dtype: int64

PHGR1
False    172
True      11
Name: PHGR1, dtype: int64

PHIP
False    183
Name: PHIP, dtype: int64

PHKA1
False    183
Name: PHKA1, dtype: int64

PHKA2
False    183
Name: PHKA2, dtype: int64

PHKB
False    183
Name: PHKB, dtype: int64

PHKG1
False    183
Name: PHKG1, dtype: int64

PHKG2
False    183
Name: PHKG2, dtype: int64

PHLDA1
False    183
Name: PHLDA1, dtype: int64

PHLDA2
False    183
Name: PHLDA2, dtype: int64

PHLDA3
False    183
Name: PHLDA3, dtype: int64

PHLDB1
False    183
Name: PHLDB1, dtype: int64

PHLDB2
False    183
Name: PHLDB2, dtype: int64

PHLDB3
False    183
Name: PHLDB3, dtype: int64

PHLPP1
False    183
Name: PHLPP1, dtype: int64

PHLPP2

False    183
Name: PHLPP2, dtype: int64

PHOSPHO1
False    181
True       2
Name: PHOSPHO1, dtype: int64

PHOSPHO2
False    183
Name: PHOSPHO2, dtype: int64

PHOX2A
False    130
True      53
Name: PHOX2A, dtype: int64

PHOX2B
False    121
True      62
Name: PHOX2B, dtype: int64

PHPT1
False    183
Name: PHPT1, dtype: int64

PHRF1
False    183
Name: PHRF1, dtype: int64

PHTF1
False    183
Name: PHTF1, dtype: int64

PHTF2
False    183
Name: PHTF2, dtype: int64

PHYHD1
False    183
Name: PHYHD1, dtype: int64

PHYHIPL
False    181
True       2
Name: PHYHIPL, dtype: int64

PHYHIP
False    183
Name: PHYHIP, dtype: int64

PHYH
False    183
Name: PHYH, dtype: int64

PI15
False    183
Name: PI15, dtype: int64

PI16
False    180
True       3
Name: PI16, dtype: int64

PI3
False    181
True       2
Name: PI3, dtype: int64

PI4K2A
False    183
Name: PI4K2A, dtype: int64

PI4K2B
False    183
Name: PI4K2B, dtype: int64

PI4KAP1
False    183
Name: PI4KAP1, dtype: int64

PI4KAP2
False    183
Name: PI4KAP2, dtype: int64

PI4KA
False    183
Name: PI4KA, dtype: int64

PI4KB
False    183
Name: PI4KB, dtype: int64

PIAS1
False    183
Name: PIAS1, dtype: int64

PIAS2
False    183
Name: PIAS2, dtype: int64

PIAS3
False    183
Name: PIAS3, dtype: int64

PIAS4
False    183
Name: PIAS4, dtype: int64

PIBF1
False    183
Name: PIBF1, dtype: int64

PICALM
False    183
Name: PICALM, dtype: int64

PICK1
False    183
Name: PICK1, dtype: int64

PID1
False    183
Name: PID1, dtype: int64

PIF1
False    183
Name: PIF1, dtype: int64

PIGA
False    183
Name: PIGA, dtype: int64

PIGB
False    183
Name: PIGB, dtype: int64

PIGC
False    183
Name: PIGC, dtype: int64

PIGF
False    183
Name: PIGF, dtype: int64

PIGG
False    183
Name: PIGG, dtype: int64

PIGH
False    183
Name: PIGH, dtype: int64

PIGK
False    183
Name: PIGK, dtype: int64

PIGL
False    183
Name: PIGL, dtype: int64

PIGM
False    183
Name: PIGM, dtype: int64

PIGN
False    183
Name: PIGN, dtype: int64

PIGO
False    183
Name: PIGO, dtype: int64

PIGP
False    183
Name: PIGP, dtype: int64

PIGQ
False    183
Name: PIGQ, dtype: int64

PIGR
False    183
Name: PIGR, dtype: int64

PIGS
False    183
Name: PIGS, dtype: int64

PIGT
False    183
Name: PIGT, dtype: int64

PIGU
False    183
Name: PIGU, dtype: int64

PIGV
False    183
Name: PIGV, dtype: int64

PIGW
False    183
Name: PIGW, dtype: int64

PIGX
False    183
Name: PIGX, dtype: int64

PIGY
False    183
Name: PIGY, dtype: int64

PIGZ
False    183
Name: PIGZ, dtype: int64

PIH1D1
False    183
Name: PIH1D1, dtype: int64

PIH1D2
False    183
Name: PIH1D2, dtype: int64

PIK3AP1
False    183
Name: PIK3AP1, dtype: int64

PIK3C2A
False    183
Name: PIK3C2A, dtype: int64

PIK3C2B
False    183
Name: PIK3C2B, dtype: int64

PIK3C2G
False    174
True       9
Name: PIK3C2G, dtype: int64

PIK3C3
False    183
Name: PIK3C3, dtype: int64

PIK3CA
False    183
Name: PIK3CA, dtype: int64

PIK3CB
False    183
Name: PIK3CB, dtype: int64

PIK3CD
False    183
Name: PIK3CD, dtype: int64

PIK3CG
False    183
Name: PIK3CG, dtype: int64

PIK3IP1
False    183
Name: PIK3IP1, dtype: int64

PIK3R1
False    183
Name: PIK3R1, dtype: int64

PIK3R2
False    183
Name: PIK3R2, dtype: int64

PIK3R3
False    183
Name: PIK3R3, dtype: int64

PIK3R4
False    183
Name: PIK3R4, dtype: int64

PIK3R5
False    183
Name: PIK3R5, dtype: int64

PIK3R6
False    183
Name: PIK3R6, dtype: int64

PIKFYVE
False    183
Name: PIKFYVE, dtype: int64

PILRA
False    183
Name: PILRA, dtype: int64

PILRB
False    183
Name: PILRB, dtype: int64

PIM1
False    183
Name: PIM1, dtype: int64

PIM2
False    183
Name: PIM2, dtype: int64

PIM3
False    183
Name: PIM3, dtype: int64

PIN1L
False    110
True      73
Name: PIN1L, dtype: int64

PIN1
False    183
Name: PIN1, dtype: int64

PIN4
False    183
Name: PIN4, dtype: int64

PINK1
False    183
Name: PINK1, dtype: int64

PINX1
False    183
Name: PINX1, dtype: int64

PION
False    183
Name: PION, dtype: int64

PIP4K2A
False    183
Name: PIP4K2A, dtype: int64

PIP4K2B
False    183
Name: PIP4K2B, dtype: int64

PIP4K2C
False    183
Name: PIP4K2C, dtype: int64

PIP5K1A
False    183
Name: PIP5K1A, dtype: int64

PIP5K1B
False    183
Name: PIP5K1B, dtype: int64

PIP5K1C
False    183
Name: PIP5K1C, dtype: int64

PIP5K1P1
False    133
True      50
Name: PIP5K1P1, dtype: int64

PIP5KL1
False    183
Name: PIP5KL1, dtype: int64

PIPOX
False    183
Name: PIPOX, dtype: int64

PIPSL
False    183
Name: PIPSL, dtype: int64

PIP
False    136
True      47
Name: PIP, dtype: int64

PIRT
False    160
True      23
Name: PIRT, dtype: int64

PIR
False    183
Name: PIR, dtype: int64

PISD
False    183
Name: PISD, dtype: int64

PITPNA
False    183
Name: PITPNA, dtype: int64

PITPNB
False    183
Name: PITPNB, dtype: int64

PITPNC1
False    183
Name: PITPNC1, dtype: int64

PITPNM1
False    183
Name: PITPNM1, dtype: int64

PITPNM2
False    183
Name: PITPNM2, dtype: int64

PITPNM3
False    183
Name: PITPNM3, dtype: int64

PITRM1
False    183
Name: PITRM1, dtype: int64

PITX1
False    181
True       2
Name: PITX1, dtype: int64

PITX2
False    172
True      11
Name: PITX2, dtype: int64

PITX3
False    112
True      71
Name: PITX3, dtype: int64

PIWIL1
False    156
True      27
Name: PIWIL1, dtype: int64

PIWIL2
False    182
True       1
Name: PIWIL2, dtype: int64

PIWIL4
False    183
Name: PIWIL4, dtype: int64

PJA1
False    183
Name: PJA1, dtype: int64

PJA2
False    183
Name: PJA2, dtype: int64

PKD1L1
False    180
True       3
Name: PKD1L1, dtype: int64

PKD1L2
False    180
True       3
Name: PKD1L2, dtype: int64

PKD1L3
False    157
True      26
Name: PKD1L3, dtype: int64

PKD1
False    183
Name: PKD1, dtype: int64

PKD2L1
False    174
True       9
Name: PKD2L1, dtype: int64

PKD2L2
False    122
True      61
Name: PKD2L2, dtype: int64

PKD2
False    183
Name: PKD2, dtype: int64

PKDCC
False    183
Name: PKDCC, dtype: int64

PKDREJ
False    183
Name: PKDREJ, dtype: int64

PKHD1L1
False    159
True      24
Name: PKHD1L1, dtype: int64

PKHD1
False    180
True       3
Name: PKHD1, dtype: int64

PKIA
False    183
Name: PKIA, dtype: int64

PKIB
False    183
Name: PKIB, dtype: int64

PKIG
False    183
Name: PKIG, dtype: int64

PKLR
False    131
True      52
Name: PKLR, dtype: int64

PKM2
False    183
Name: PKM2, dtype: int64

PKMYT1
False    183
Name: PKMYT1, dtype: int64

PKN1
False    183
Name: PKN1, dtype: int64

PKN2
False    183
Name: PKN2, dtype: int64

PKN3
False    183
Name: PKN3, dtype: int64

PKNOX1
False    183
Name: PKNOX1, dtype: int64

PKNOX2
False    183
Name: PKNOX2, dtype: int64

PKP1
False    182
True       1
Name: PKP1, dtype: int64

PKP2
False    183
Name: PKP2, dtype: int64

PKP3
False    183
Name: PKP3, dtype: int64

PKP4
False    183
Name: PKP4, dtype: int64

PL-5283
False    183
Name: PL-5283, dtype: int64

PLA1A
False    183
Name: PLA1A, dtype: int64

PLA2G10
False    180
True       3
Name: PLA2G10, dtype: int64

PLA2G12A
False    183
Name: PLA2G12A, dtype: int64

PLA2G12B
True     122
False     61
Name: PLA2G12B, dtype: int64

PLA2G15
False    183
Name: PLA2G15, dtype: int64

PLA2G16
False    183
Name: PLA2G16, dtype: int64

PLA2G1B
False    175
True       8
Name: PLA2G1B, dtype: int64

PLA2G2A
False    181
True       2
Name: PLA2G2A, dtype: int64

PLA2G2D
False    180
True       3
Name: PLA2G2D, dtype: int64

PLA2G2F
False    142
True      41
Name: PLA2G2F, dtype: int64

PLA2G3
False    136
True      47
Name: PLA2G3, dtype: int64

PLA2G4A
False    183
Name: PLA2G4A, dtype: int64

PLA2G4C
False    183
Name: PLA2G4C, dtype: int64

PLA2G4D
False    172
True      11
Name: PLA2G4D, dtype: int64

PLA2G4E
False    100
True      83
Name: PLA2G4E, dtype: int64

PLA2G4F
False    182
True       1
Name: PLA2G4F, dtype: int64

PLA2G5
False    183
Name: PLA2G5, dtype: int64

PLA2G6
False    183
Name: PLA2G6, dtype: int64

PLA2G7
False    183
Name: PLA2G7, dtype: int64

PLA2R1
False    183
Name: PLA2R1, dtype: int64

PLAA
False    183
Name: PLAA, dtype: int64

PLAC1
False    153
True      30
Name: PLAC1, dtype: int64

PLAC2
False    183
Name: PLAC2, dtype: int64

PLAC4
False    179
True       4
Name: PLAC4, dtype: int64

PLAC8L1
False    169
True      14
Name: PLAC8L1, dtype: int64

PLAC8
False    183
Name: PLAC8, dtype: int64

PLAC9

False    183
Name: PLAC9, dtype: int64

PLAG1
False    183
Name: PLAG1, dtype: int64

PLAGL1
False    183
Name: PLAGL1, dtype: int64

PLAGL2
False    183
Name: PLAGL2, dtype: int64

PLAT
False    183
Name: PLAT, dtype: int64

PLAUR
False    183
Name: PLAUR, dtype: int64

PLAU
False    183
Name: PLAU, dtype: int64

PLB1
False    183
Name: PLB1, dtype: int64

PLBD1
False    183
Name: PLBD1, dtype: int64

PLBD2
False    183
Name: PLBD2, dtype: int64

PLCB1
False    183
Name: PLCB1, dtype: int64

PLCB2
False    183
Name: PLCB2, dtype: int64

PLCB3
False    183
Name: PLCB3, dtype: int64

PLCB4
False    183
Name: PLCB4, dtype: int64

PLCD1
False    183
Name: PLCD1, dtype: int64

PLCD3
False    183
Name: PLCD3, dtype: int64

PLCD4
False    183
Name: PLCD4, dtype: int64

PLCE1
False    183
Name: PLCE1, dtype: int64

PLCG1
False    183
Name: PLCG1, dtype: int64

PLCG2
False    183
Name: PLCG2, dtype: int64

PLCH1
False    183
Name: PLCH1, dtype: int64

PLCH2
False    183
Name: PLCH2, dtype: int64

PLCL1
False    183
Name: PLCL1, dtype: int64

PLCL2
False    183
Name: PLCL2, dtype: int64

PLCXD1
False    183
Name: PLCXD1, dtype: int64

PLCXD2
False    183
Name: PLCXD2, dtype: int64

PLCXD3
False    183
Name: PLCXD3, dtype: int64

PLD1
False    183
Name: PLD1, dtype: int64

PLD2
False    183
Name: PLD2, dtype: int64

PLD3
False    183
Name: PLD3, dtype: int64

PLD4
False    183
Name: PLD4, dtype: int64

PLD5
False    163
True      20
Name: PLD5, dtype: int64

PLD6
False    183
Name: PLD6, dtype: int64

PLDN
False    183
Name: PLDN, dtype: int64

PLEC
False    183
Name: PLEC, dtype: int64

PLEK2
False    183
Name: PLEK2, dtype: int64

PLEKHA1
False    183
Name: PLEKHA1, dtype: int64

PLEKHA2
False    183
Name: PLEKHA2, dtype: int64

PLEKHA3
False    183
Name: PLEKHA3, dtype: int64

PLEKHA4
False    183
Name: PLEKHA4, dtype: int64

PLEKHA5
False    183
Name: PLEKHA5, dtype: int64

PLEKHA6
False    183
Name: PLEKHA6, dtype: int64

PLEKHA7
False    183
Name: PLEKHA7, dtype: int64

PLEKHA8
False    183
Name: PLEKHA8, dtype: int64

PLEKHA9
False    183
Name: PLEKHA9, dtype: int64

PLEKHB1
False    183
Name: PLEKHB1, dtype: int64

PLEKHB2
False    183
Name: PLEKHB2, dtype: int64

PLEKHF1
False    183
Name: PLEKHF1, dtype: int64

PLEKHF2
False    183
Name: PLEKHF2, dtype: int64

PLEKHG1
False    183
Name: PLEKHG1, dtype: int64

PLEKHG2
False    183
Name: PLEKHG2, dtype: int64

PLEKHG3
False    183
Name: PLEKHG3, dtype: int64

PLEKHG4B
False    183
Name: PLEKHG4B, dtype: int64

PLEKHG4
False    183
Name: PLEKHG4, dtype: int64

PLEKHG5
False    183
Name: PLEKHG5, dtype: int64

PLEKHG6
False    183
Name: PLEKHG6, dtype: int64

PLEKHG7
False    182
True       1
Name: PLEKHG7, dtype: int64

PLEKHH1
False    183
Name: PLEKHH1, dtype: int64

PLEKHH2
False    183
Name: PLEKHH2, dtype: int64

PLEKHH3
False    183
Name: PLEKHH3, dtype: int64

PLEKHJ1
False    183
Name: PLEKHJ1, dtype: int64

PLEKHM1P
False    183
Name: PLEKHM1P, dtype: int64

PLEKHM1
False    183
Name: PLEKHM1, dtype: int64

PLEKHM2
False    183
Name: PLEKHM2, dtype: int64

PLEKHM3
False    183
Name: PLEKHM3, dtype: int64

PLEKHN1
False    182
True       1
Name: PLEKHN1, dtype: int64

PLEKHO1
False    183
Name: PLEKHO1, dtype: int64

PLEKHO2
False    183
Name: PLEKHO2, dtype: int64

PLEK
False    183
Name: PLEK, dtype: int64

PLGLB2
False    183
Name: PLGLB2, dtype: int64

PLG
False    119
True      64
Name: PLG, dtype: int64

PLIN1
False    183
Name: PLIN1, dtype: int64

PLIN2
False    183
Name: PLIN2, dtype: int64

PLIN3
False    183
Name: PLIN3, dtype: int64

PLIN4
False    183
Name: PLIN4, dtype: int64

PLIN5
False    183
Name: PLIN5, dtype: int64

PLK1S1
False    183
Name: PLK1S1, dtype: int64

PLK1
False    183
Name: PLK1, dtype: int64

PLK2
False    183
Name: PLK2, dtype: int64

PLK3
False    183
Name: PLK3, dtype: int64

PLK4
False    183
Name: PLK4, dtype: int64

PLK5P
False    122
True      61
Name: PLK5P, dtype: int64

PLLP
False    183
Name: PLLP, dtype: int64

PLN
False    183
Name: PLN, dtype: int64

PLOD1
False    183
Name: PLOD1, dtype: int64

PLOD2
False    183
Name: PLOD2, dtype: int64

PLOD3
False    183
Name: PLOD3, dtype: int64

PLP1
False    180
True       3
Name: PLP1, dtype: int64

PLP2
False    183
Name: PLP2, dtype: int64

PLRG1
False    183
Name: PLRG1, dtype: int64

PLS1
False    183
Name: PLS1, dtype: int64

PLS3
False    183
Name: PLS3, dtype: int64

PLSCR1
False    183
Name: PLSCR1, dtype: int64

PLSCR2
False    160
True      23
Name: PLSCR2, dtype: int64

PLSCR3
False    183
Name: PLSCR3, dtype: int64

PLSCR4
False    183
Name: PLSCR4, dtype: int64

PLTP
False    183
Name: PLTP, dtype: int64

PLVAP
False    183
Name: PLVAP, dtype: int64

PLXDC1
False    183
Name: PLXDC1, dtype: int64

PLXDC2
False    183
Name: PLXDC2, dtype: int64

PLXNA1
False    183
Name: PLXNA1, dtype: int64

PLXNA2
False    183
Name: PLXNA2, dtype: int64

PLXNA3
False    183
Name: PLXNA3, dtype: int64

PLXNA4
False    183
Name: PLXNA4, dtype: int64

PLXNB1
False    183
Name: PLXNB1, dtype: int64

PLXNB2
False    183
Name: PLXNB2, dtype: int64

PLXNB3
False    183
Name: PLXNB3, dtype: int64

PLXNC1
False    183
Name: PLXNC1, dtype: int64

PLXND1
False    183
Name: PLXND1, dtype: int64

PM20D1
False    175
True       8
Name: PM20D1, dtype: int64

PM20D2
False    183
Name: PM20D2, dtype: int64

PMAIP1
False    183
Name: PMAIP1, dtype: int64

PMCH
False    172
True      11
Name: PMCH, dtype: int64

PMEPA1
False    183
Name: PMEPA1, dtype: int64

PMF1
False    183
Name: PMF1, dtype: int64

PMFBP1
False    181
True       2
Name: PMFBP1, dtype: int64

PML
False    183
Name: PML, dtype: int64

PMM1
False    183
Name: PMM1, dtype: int64

PMM2
False    183
Name: PMM2, dtype: int64

PMP22
False    183
Name: PMP22, dtype: int64

PMP2
False    167
True      16
Name: PMP2, dtype: int64

PMPCA
False    183
Name: PMPCA, dtype: int64

PMPCB
False    183
Name: PMPCB, dtype: int64

PMS1
False    183
Name: PMS1, dtype: int64

PMS2CL
False    183
Name: PMS2CL, dtype: int64

PMS2L11
False    183
Name: PMS2L11, dtype: int64

PMS2L1
False    183
Name: PMS2L1, dtype: int64

PMS2L2
False    183
Name: PMS2L2, dtype: int64

PMS2L3
False    183
Name: PMS2L3, dtype: int64

PMS2L4
False    183
Name: PMS2L4, dtype: int64

PMS2L5
False    183
Name: PMS2L5, dtype: int64

PMS2
False    183
Name: PMS2, dtype: int64

PMVK
False    183
Name: PMVK, dtype: int64

PNCK
False    172
True      11
Name: PNCK, dtype: int64

PNKD
False    183
Name: PNKD, dtype: int64

PNKP
False    183
Name: PNKP, dtype: int64

PNLDC1
False    157
True      26
Name: PNLDC1, dtype: int64

PNLIPRP1
False    147
True      36
Name: PNLIPRP1, dtype: int64

PNLIPRP2
False    154
True      29
Name: PNLIPRP2, dtype: int64

PNLIP
False    165
True      18
Name: PNLIP, dtype: int64

PNMA1
False    183
Name: PNMA1, dtype: int64

PNMA2
False    183
Name: PNMA2, dtype: int64

PNMA3
False    180
True       3
Name: PNMA3, dtype: int64

PNMA5
False    155
True      28
Name: PNMA5, dtype: int64

PNMA6A
False    182
True       1
Name: PNMA6A, dtype: int64

PNMAL1
False    183
Name: PNMAL1, dtype: int64

PNMAL2
False    183
Name: PNMAL2, dtype: int64

PNMT
False    182
True       1
Name: PNMT, dtype: int64

PNN
False    183
Name: PNN, dtype: int64

PNO1
False    183
Name: PNO1, dtype: int64

PNOC
False    181
True       2
Name: PNOC, dtype: int64

PNPLA1
False    165
True      18
Name: PNPLA1, dtype: int64

PNPLA2
False    183
Name: PNPLA2, dtype: int64

PNPLA3
False    179
True       4
Name: PNPLA3, dtype: int64

PNPLA4
False    183
Name: PNPLA4, dtype: int64

PNPLA5
True     119
False     64
Name: PNPLA5, dtype: int64

PNPLA6
False    183
Name: PNPLA6, dtype: int64

PNPLA7
False    183
Name: PNPLA7, dtype: int64

PNPLA8
False    183
Name: PNPLA8, dtype: int64

PNPO
False    183
Name: PNPO, dtype: int64

PNPT1
False    183
Name: PNPT1, dtype: int64

PNP
False    183
Name: PNP, dtype: int64

PNRC1
False    183
Name: PNRC1, dtype: int64

PNRC2
False    183
Name: PNRC2, dtype: int64

POC1A
False    183
Name: POC1A, dtype: int64

POC1B
False    183
Name: POC1B, dtype: int64

POC5
False    183
Name: POC5, dtype: int64

PODNL1
False    183
Name: PODNL1, dtype: int64

PODN
False    183
Name: PODN, dtype: int64

PODXL2
False    183
Name: PODXL2, dtype: int64

PODXL
False    183
Name: PODXL, dtype: int64

POF1B
False    183
Name: POF1B, dtype: int64

POFUT1
False    183
Name: POFUT1, dtype: int64

POFUT2
False    183
Name: POFUT2, dtype: int64

POGK
False    183
Name: POGK, dtype: int64

POGZ
False    183
Name: POGZ, dtype: int64

POLA1
False    183
Name: POLA1, dtype: int64

POLA2
False    183
Name: POLA2, dtype: int64

POLB
False    183
Name: POLB, dtype: int64

POLD1
False    183
Name: POLD1, dtype: int64

POLD2
False    183
Name: POLD2, dtype: int64

POLD3
False    183
Name: POLD3, dtype: int64

POLD4
False    183
Name: POLD4, dtype: int64

POLDIP2
False    183
Name: POLDIP2, dtype: int64

POLDIP3
False    183
Name: POLDIP3, dtype: int64

POLE2
False    183
Name: POLE2, dtype: int64

POLE3
False    183
Name: POLE3, dtype: int64

POLE4
False    183
Name: POLE4, dtype: int64

POLE

False    183
Name: POLE, dtype: int64

POLG2
False    183
Name: POLG2, dtype: int64

POLG
False    183
Name: POLG, dtype: int64

POLH
False    183
Name: POLH, dtype: int64

POLI
False    183
Name: POLI, dtype: int64

POLK
False    183
Name: POLK, dtype: int64

POLL
False    183
Name: POLL, dtype: int64

POLM
False    183
Name: POLM, dtype: int64

POLN
False    183
Name: POLN, dtype: int64

POLQ
False    183
Name: POLQ, dtype: int64

POLR1A
False    183
Name: POLR1A, dtype: int64

POLR1B
False    183
Name: POLR1B, dtype: int64

POLR1C
False    183
Name: POLR1C, dtype: int64

POLR1D
False    183
Name: POLR1D, dtype: int64

POLR1E
False    183
Name: POLR1E, dtype: int64

POLR2A
False    183
Name: POLR2A, dtype: int64

POLR2B
False    183
Name: POLR2B, dtype: int64

POLR2C
False    183
Name: POLR2C, dtype: int64

POLR2D
False    183
Name: POLR2D, dtype: int64

POLR2E
False    183
Name: POLR2E, dtype: int64

POLR2F
False    183
Name: POLR2F, dtype: int64

POLR2G
False    183
Name: POLR2G, dtype: int64

POLR2H
False    183
Name: POLR2H, dtype: int64

POLR2I
False    183
Name: POLR2I, dtype: int64

POLR2J2
False    183
Name: POLR2J2, dtype: int64

POLR2J3
False    183
Name: POLR2J3, dtype: int64

POLR2J4
False    183
Name: POLR2J4, dtype: int64

POLR2J
False    183
Name: POLR2J, dtype: int64

POLR2K
False    183
Name: POLR2K, dtype: int64

POLR2L
False    183
Name: POLR2L, dtype: int64

POLR3A
False    183
Name: POLR3A, dtype: int64

POLR3B
False    183
Name: POLR3B, dtype: int64

POLR3C
False    183
Name: POLR3C, dtype: int64

POLR3D
False    183
Name: POLR3D, dtype: int64

POLR3E
False    183
Name: POLR3E, dtype: int64

POLR3F
False    183
Name: POLR3F, dtype: int64

POLR3GL
False    183
Name: POLR3GL, dtype: int64

POLR3G
False    183
Name: POLR3G, dtype: int64

POLR3H
False    183
Name: POLR3H, dtype: int64

POLR3K
False    183
Name: POLR3K, dtype: int64

POLRMT
False    183
Name: POLRMT, dtype: int64

POM121C
False    183
Name: POM121C, dtype: int64

POM121L10P
False    182
True       1
Name: POM121L10P, dtype: int64

POM121L1P
False    171
True      12
Name: POM121L1P, dtype: int64

POM121L2
True     109
False     74
Name: POM121L2, dtype: int64

POM121L4P
True     122
False     61
Name: POM121L4P, dtype: int64

POM121L8P
False    165
True      18
Name: POM121L8P, dtype: int64

POM121L9P
False    183
Name: POM121L9P, dtype: int64

POM121
False    183
Name: POM121, dtype: int64

POMC
False    183
Name: POMC, dtype: int64

POMGNT1
False    183
Name: POMGNT1, dtype: int64

POMP
False    183
Name: POMP, dtype: int64

POMT1
False    183
Name: POMT1, dtype: int64

POMT2
False    183
Name: POMT2, dtype: int64

POMZP3
False    183
Name: POMZP3, dtype: int64

PON1
False    168
True      15
Name: PON1, dtype: int64

PON2
False    183
Name: PON2, dtype: int64

PON3
False    182
True       1
Name: PON3, dtype: int64

POP1
False    183
Name: POP1, dtype: int64

POP4
False    183
Name: POP4, dtype: int64

POP5
False    183
Name: POP5, dtype: int64

POP7
False    183
Name: POP7, dtype: int64

POPDC2
False    183
Name: POPDC2, dtype: int64

POPDC3
False    180
True       3
Name: POPDC3, dtype: int64

PORCN
False    183
Name: PORCN, dtype: int64

POR
False    183
Name: POR, dtype: int64

POSTN
False    183
Name: POSTN, dtype: int64

POT1
False    183
Name: POT1, dtype: int64

POTEE
False    178
True       5
Name: POTEE, dtype: int64

POTEF
False    181
True       2
Name: POTEF, dtype: int64

POU1F1
True     118
False     65
Name: POU1F1, dtype: int64

POU2AF1
False    182
True       1
Name: POU2AF1, dtype: int64

POU2F1
False    183
Name: POU2F1, dtype: int64

POU2F2
False    183
Name: POU2F2, dtype: int64

POU2F3
False    181
True       2
Name: POU2F3, dtype: int64

POU3F1
False    178
True       5
Name: POU3F1, dtype: int64

POU3F2
False    107
True      76
Name: POU3F2, dtype: int64

POU4F1
False    108
True      75
Name: POU4F1, dtype: int64

POU4F3
False    138
True      45
Name: POU4F3, dtype: int64

POU5F1B
False    183
Name: POU5F1B, dtype: int64

POU5F1
False    182
True       1
Name: POU5F1, dtype: int64

POU5F2
False    92
True     91
Name: POU5F2, dtype: int64

POU6F1
False    183
Name: POU6F1, dtype: int64

POU6F2
False    160
True      23
Name: POU6F2, dtype: int64

PP14571
False    167
True      16
Name: PP14571, dtype: int64

PPA1
False    183
Name: PPA1, dtype: int64

PPA2
False    183
Name: PPA2, dtype: int64

PPAN-P2RY11
True     92
False    91
Name: PPAN-P2RY11, dtype: int64

PPAN
False    183
Name: PPAN, dtype: int64

PPAP2A
False    183
Name: PPAP2A, dtype: int64

PPAP2B
False    183
Name: PPAP2B, dtype: int64

PPAP2C
False    183
Name: PPAP2C, dtype: int64

PPAPDC1A
False    182
True       1
Name: PPAPDC1A, dtype: int64

PPAPDC1B
False    183
Name: PPAPDC1B, dtype: int64

PPAPDC2
False    183
Name: PPAPDC2, dtype: int64

PPAPDC3
False    183
Name: PPAPDC3, dtype: int64

PPARA
False    183
Name: PPARA, dtype: int64

PPARD
False    183
Name: PPARD, dtype: int64

PPARGC1A
False    183
Name: PPARGC1A, dtype: int64

PPARGC1B
False    183
Name: PPARGC1B, dtype: int64

PPARG
False    183
Name: PPARG, dtype: int64

PPAT
False    183
Name: PPAT, dtype: int64

PPBP
False    161
True      22
Name: PPBP, dtype: int64

PPCDC
False    183
Name: PPCDC, dtype: int64

PPCS
False    183
Name: PPCS, dtype: int64

PPDPF
False    183
Name: PPDPF, dtype: int64

PPEF1
False    182
True       1
Name: PPEF1, dtype: int64

PPEF2
False    107
True      76
Name: PPEF2, dtype: int64

PPFIA1
False    183
Name: PPFIA1, dtype: int64

PPFIA2
False    181
True       2
Name: PPFIA2, dtype: int64

PPFIA3
False    183
Name: PPFIA3, dtype: int64

PPFIA4
False    182
True       1
Name: PPFIA4, dtype: int64

PPFIBP1
False    183
Name: PPFIBP1, dtype: int64

PPFIBP2
False    183
Name: PPFIBP2, dtype: int64

PPHLN1
False    183
Name: PPHLN1, dtype: int64

PPIAL4C
False    183
Name: PPIAL4C, dtype: int64

PPIAL4D
False    164
True      19
Name: PPIAL4D, dtype: int64

PPIAL4G
False    183
Name: PPIAL4G, dtype: int64

PPIA
False    183
Name: PPIA, dtype: int64

PPIB
False    183
Name: PPIB, dtype: int64

PPIC
False    183
Name: PPIC, dtype: int64

PPID
False    183
Name: PPID, dtype: int64

PPIEL
False    183
Name: PPIEL, dtype: int64

PPIE
False    183
Name: PPIE, dtype: int64

PPIF
False    183
Name: PPIF, dtype: int64

PPIG
False    183
Name: PPIG, dtype: int64

PPIH
False    183
Name: PPIH, dtype: int64

PPIL1
False    183
Name: PPIL1, dtype: int64

PPIL2
False    183
Name: PPIL2, dtype: int64

PPIL3
False    183
Name: PPIL3, dtype: int64

PPIL4
False    183
Name: PPIL4, dtype: int64

PPIL5
False    183
Name: PPIL5, dtype: int64

PPIL6
False    183
Name: PPIL6, dtype: int64

PPIP5K1
False    183
Name: PPIP5K1, dtype: int64

PPIP5K2
False    183
Name: PPIP5K2, dtype: int64

PPL
False    183
Name: PPL, dtype: int64

PPM1A
False    183
Name: PPM1A, dtype: int64

PPM1B
False    183
Name: PPM1B, dtype: int64

PPM1D
False    183
Name: PPM1D, dtype: int64

PPM1E
False    183
Name: PPM1E, dtype: int64

PPM1F
False    183
Name: PPM1F, dtype: int64

PPM1G
False    183
Name: PPM1G, dtype: int64

PPM1H
False    183
Name: PPM1H, dtype: int64

PPM1J
False    183
Name: PPM1J, dtype: int64

PPM1K
False    183
Name: PPM1K, dtype: int64

PPM1L
False    183
Name: PPM1L, dtype: int64

PPM1M
False    183
Name: PPM1M, dtype: int64

PPM1N
False    183
Name: PPM1N, dtype: int64

PPME1
False    183
Name: PPME1, dtype: int64

PPOX
False    183
Name: PPOX, dtype: int64

PPP1CA
False    183
Name: PPP1CA, dtype: int64

PPP1CB
False    183
Name: PPP1CB, dtype: int64

PPP1CC
False    183
Name: PPP1CC, dtype: int64

PPP1R10
False    183
Name: PPP1R10, dtype: int64

PPP1R11
False    183
Name: PPP1R11, dtype: int64

PPP1R12A
False    183
Name: PPP1R12A, dtype: int64

PPP1R12B
False    183
Name: PPP1R12B, dtype: int64

PPP1R12C
False    183
Name: PPP1R12C, dtype: int64

PPP1R13B
False    183
Name: PPP1R13B, dtype: int64

PPP1R13L
False    183
Name: PPP1R13L, dtype: int64

PPP1R14A
False    183
Name: PPP1R14A, dtype: int64

PPP1R14B
False    183
Name: PPP1R14B, dtype: int64

PPP1R14C
False    183
Name: PPP1R14C, dtype: int64

PPP1R14D
False    181
True       2
Name: PPP1R14D, dtype: int64

PPP1R15A
False    183
Name: PPP1R15A, dtype: int64

PPP1R15B
False    183
Name: PPP1R15B, dtype: int64

PPP1R16A
False    183
Name: PPP1R16A, dtype: int64

PPP1R16B

False    183
Name: PPP1R16B, dtype: int64

PPP1R1A
False    181
True       2
Name: PPP1R1A, dtype: int64

PPP1R1B
False    183
Name: PPP1R1B, dtype: int64

PPP1R1C
False    182
True       1
Name: PPP1R1C, dtype: int64

PPP1R2P1
False    177
True       6
Name: PPP1R2P1, dtype: int64

PPP1R2P3
False    183
Name: PPP1R2P3, dtype: int64

PPP1R2
False    183
Name: PPP1R2, dtype: int64

PPP1R3B
False    183
Name: PPP1R3B, dtype: int64

PPP1R3C
False    183
Name: PPP1R3C, dtype: int64

PPP1R3D
False    183
Name: PPP1R3D, dtype: int64

PPP1R3E
False    183
Name: PPP1R3E, dtype: int64

PPP1R3F
False    183
Name: PPP1R3F, dtype: int64

PPP1R3G
False    183
Name: PPP1R3G, dtype: int64

PPP1R7
False    183
Name: PPP1R7, dtype: int64

PPP1R8
False    183
Name: PPP1R8, dtype: int64

PPP1R9A
False    183
Name: PPP1R9A, dtype: int64

PPP1R9B
False    183
Name: PPP1R9B, dtype: int64

PPP2CA
False    183
Name: PPP2CA, dtype: int64

PPP2CB
False    183
Name: PPP2CB, dtype: int64

PPP2R1A
False    183
Name: PPP2R1A, dtype: int64

PPP2R1B
False    183
Name: PPP2R1B, dtype: int64

PPP2R2A
False    183
Name: PPP2R2A, dtype: int64

PPP2R2B
False    183
Name: PPP2R2B, dtype: int64

PPP2R2C
False    183
Name: PPP2R2C, dtype: int64

PPP2R2D
False    183
Name: PPP2R2D, dtype: int64

PPP2R3A
False    183
Name: PPP2R3A, dtype: int64

PPP2R3B
False    183
Name: PPP2R3B, dtype: int64

PPP2R3C
False    183
Name: PPP2R3C, dtype: int64

PPP2R4
False    183
Name: PPP2R4, dtype: int64

PPP2R5A
False    183
Name: PPP2R5A, dtype: int64

PPP2R5B
False    183
Name: PPP2R5B, dtype: int64

PPP2R5C
False    183
Name: PPP2R5C, dtype: int64

PPP2R5D
False    183
Name: PPP2R5D, dtype: int64

PPP2R5E
False    183
Name: PPP2R5E, dtype: int64

PPP3CA
False    183
Name: PPP3CA, dtype: int64

PPP3CB
False    183
Name: PPP3CB, dtype: int64

PPP3CC
False    183
Name: PPP3CC, dtype: int64

PPP3R1
False    183
Name: PPP3R1, dtype: int64

PPP3R2
True     125
False     58
Name: PPP3R2, dtype: int64

PPP4C
False    183
Name: PPP4C, dtype: int64

PPP4R1L
False    183
Name: PPP4R1L, dtype: int64

PPP4R1
False    183
Name: PPP4R1, dtype: int64

PPP4R2
False    183
Name: PPP4R2, dtype: int64

PPP4R4
False    179
True       4
Name: PPP4R4, dtype: int64

PPP5C
False    183
Name: PPP5C, dtype: int64

PPP6C
False    183
Name: PPP6C, dtype: int64

PPPDE1
False    183
Name: PPPDE1, dtype: int64

PPPDE2
False    183
Name: PPPDE2, dtype: int64

PPRC1
False    183
Name: PPRC1, dtype: int64

PPT1
False    183
Name: PPT1, dtype: int64

PPT2
False    183
Name: PPT2, dtype: int64

PPTC7
False    183
Name: PPTC7, dtype: int64

PPWD1
False    183
Name: PPWD1, dtype: int64

PPYR1
False    178
True       5
Name: PPYR1, dtype: int64

PPY
False    170
True      13
Name: PPY, dtype: int64

PQBP1
False    183
Name: PQBP1, dtype: int64

PQLC1
False    183
Name: PQLC1, dtype: int64

PQLC2
False    183
Name: PQLC2, dtype: int64

PQLC3
False    183
Name: PQLC3, dtype: int64

PRAF2
False    183
Name: PRAF2, dtype: int64

PRAM1
False    183
Name: PRAM1, dtype: int64

PRAME
False    161
True      22
Name: PRAME, dtype: int64

PRAP1
False    172
True      11
Name: PRAP1, dtype: int64

PRB1
False    92
True     91
Name: PRB1, dtype: int64

PRB2
False    108
True      75
Name: PRB2, dtype: int64

PRB3
False    108
True      75
Name: PRB3, dtype: int64

PRC1
False    183
Name: PRC1, dtype: int64

PRCC
False    183
Name: PRCC, dtype: int64

PRCD
False    183
Name: PRCD, dtype: int64

PRCP
False    183
Name: PRCP, dtype: int64

PRDM10
False    183
Name: PRDM10, dtype: int64

PRDM11
False    183
Name: PRDM11, dtype: int64

PRDM12
False    163
True      20
Name: PRDM12, dtype: int64

PRDM15
False    183
Name: PRDM15, dtype: int64

PRDM16
False    183
Name: PRDM16, dtype: int64

PRDM1
False    183
Name: PRDM1, dtype: int64

PRDM2
False    183
Name: PRDM2, dtype: int64

PRDM4
False    183
Name: PRDM4, dtype: int64

PRDM5
False    183
Name: PRDM5, dtype: int64

PRDM6
False    183
Name: PRDM6, dtype: int64

PRDM8
False    183
Name: PRDM8, dtype: int64

PRDX1
False    183
Name: PRDX1, dtype: int64

PRDX2
False    183
Name: PRDX2, dtype: int64

PRDX3
False    183
Name: PRDX3, dtype: int64

PRDX4
False    183
Name: PRDX4, dtype: int64

PRDX5
False    183
Name: PRDX5, dtype: int64

PRDX6
False    183
Name: PRDX6, dtype: int64

PRDXDD1P
False    183
Name: PRDXDD1P, dtype: int64

PREB
False    183
Name: PREB, dtype: int64

PRELID1
False    183
Name: PRELID1, dtype: int64

PRELID2
False    183
Name: PRELID2, dtype: int64

PRELP
False    183
Name: PRELP, dtype: int64

PREPL
False    183
Name: PREPL, dtype: int64

PREP
False    183
Name: PREP, dtype: int64

PREX1
False    183
Name: PREX1, dtype: int64

PREX2
False    183
Name: PREX2, dtype: int64

PRF1
False    183
Name: PRF1, dtype: int64

PRG2
False    180
True       3
Name: PRG2, dtype: int64

PRG4
False    183
Name: PRG4, dtype: int64

PRH1
False    183
Name: PRH1, dtype: int64

PRH2
False    183
Name: PRH2, dtype: int64

PRIC285
False    183
Name: PRIC285, dtype: int64

PRICKLE1
False    183
Name: PRICKLE1, dtype: int64

PRICKLE2
False    183
Name: PRICKLE2, dtype: int64

PRICKLE3
False    183
Name: PRICKLE3, dtype: int64

PRICKLE4
False    183
Name: PRICKLE4, dtype: int64

PRIM1
False    183
Name: PRIM1, dtype: int64

PRIM2
False    183
Name: PRIM2, dtype: int64

PRIMA1
False    183
Name: PRIMA1, dtype: int64

PRINS
False    143
True      40
Name: PRINS, dtype: int64

PRKAA1
False    183
Name: PRKAA1, dtype: int64

PRKAA2
False    182
True       1
Name: PRKAA2, dtype: int64

PRKAB1
False    183
Name: PRKAB1, dtype: int64

PRKAB2
False    183
Name: PRKAB2, dtype: int64

PRKACA
False    183
Name: PRKACA, dtype: int64

PRKACB
False    183
Name: PRKACB, dtype: int64

PRKAG1
False    183
Name: PRKAG1, dtype: int64

PRKAG2
False    183
Name: PRKAG2, dtype: int64

PRKAR1A
False    183
Name: PRKAR1A, dtype: int64

PRKAR1B
False    183
Name: PRKAR1B, dtype: int64

PRKAR2A
False    183
Name: PRKAR2A, dtype: int64

PRKAR2B
False    183
Name: PRKAR2B, dtype: int64

PRKCA
False    183
Name: PRKCA, dtype: int64

PRKCB
False    183
Name: PRKCB, dtype: int64

PRKCDBP
False    183
Name: PRKCDBP, dtype: int64

PRKCD
False    183
Name: PRKCD, dtype: int64

PRKCE
False    183
Name: PRKCE, dtype: int64

PRKCG
False    180
True       3
Name: PRKCG, dtype: int64

PRKCH
False    183
Name: PRKCH, dtype: int64

PRKCI
False    183
Name: PRKCI, dtype: int64

PRKCQ
False    182
True       1
Name: PRKCQ, dtype: int64

PRKCSH
False    183
Name: PRKCSH, dtype: int64

PRKCZ
False    183
Name: PRKCZ, dtype: int64

PRKD1
False    183
Name: PRKD1, dtype: int64

PRKD2
False    183
Name: PRKD2, dtype: int64

PRKD3
False    183
Name: PRKD3, dtype: int64

PRKDC
False    183
Name: PRKDC, dtype: int64

PRKG1
False    183
Name: PRKG1, dtype: int64

PRKG2
False    182
True       1
Name: PRKG2, dtype: int64

PRKRA
False    183
Name: PRKRA, dtype: int64

PRKRIP1
False    183
Name: PRKRIP1, dtype: int64

PRKRIR
False    183
Name: PRKRIR, dtype: int64

PRKX
False    183
Name: PRKX, dtype: int64

PRKY
False    167
True      16
Name: PRKY, dtype: int64

PRLHR
False    141
True      42
Name: PRLHR, dtype: int64

PRLR
False    183
Name: PRLR, dtype: int64

PRL
False    113
True      70
Name: PRL, dtype: int64

PRMT10
False    183
Name: PRMT10, dtype: int64

PRMT1
False    183
Name: PRMT1, dtype: int64

PRMT2
False    183
Name: PRMT2, dtype: int64

PRMT3
False    183
Name: PRMT3, dtype: int64

PRMT5
False    183
Name: PRMT5, dtype: int64

PRMT6
False    183
Name: PRMT6, dtype: int64

PRMT7
False    183
Name: PRMT7, dtype: int64

PRMT8
False    123
True      60
Name: PRMT8, dtype: int64

PRND
False    182
True       1
Name: PRND, dtype: int64

PRNP
False    183
Name: PRNP, dtype: int64

PRO0611
False    121
True      62
Name: PRO0611, dtype: int64

PRO0628
False    127
True      56
Name: PRO0628, dtype: int64

PROCA1
False    183
Name: PROCA1, dtype: int64

PROCR
False    183
Name: PROCR, dtype: int64

PROC
False    183
Name: PROC, dtype: int64

PRODH2
False    119
True      64
Name: PRODH2, dtype: int64

PRODH
False    183
Name: PRODH, dtype: int64

PROK1
False    159
True      24
Name: PROK1, dtype: int64

PROK2
False    149
True      34
Name: PROK2, dtype: int64

PROKR1

True     117
False     66
Name: PROKR1, dtype: int64

PROM1
False    181
True       2
Name: PROM1, dtype: int64

PROM2
False    183
Name: PROM2, dtype: int64

PROS1
False    183
Name: PROS1, dtype: int64

PROSC
False    183
Name: PROSC, dtype: int64

PROX1
False    183
Name: PROX1, dtype: int64

PROX2
False    151
True      32
Name: PROX2, dtype: int64

PROZ
False    163
True      20
Name: PROZ, dtype: int64

PRPF18
False    183
Name: PRPF18, dtype: int64

PRPF19
False    183
Name: PRPF19, dtype: int64

PRPF31
False    183
Name: PRPF31, dtype: int64

PRPF38A
False    183
Name: PRPF38A, dtype: int64

PRPF38B
False    183
Name: PRPF38B, dtype: int64

PRPF39
False    183
Name: PRPF39, dtype: int64

PRPF3
False    183
Name: PRPF3, dtype: int64

PRPF40A
False    183
Name: PRPF40A, dtype: int64

PRPF40B
False    183
Name: PRPF40B, dtype: int64

PRPF4B
False    183
Name: PRPF4B, dtype: int64

PRPF4
False    183
Name: PRPF4, dtype: int64

PRPF6
False    183
Name: PRPF6, dtype: int64

PRPF8
False    183
Name: PRPF8, dtype: int64

PRPH2
False    183
Name: PRPH2, dtype: int64

PRPH
False    183
Name: PRPH, dtype: int64

PRPS1L1
True     127
False     56
Name: PRPS1L1, dtype: int64

PRPS1
False    183
Name: PRPS1, dtype: int64

PRPS2
False    183
Name: PRPS2, dtype: int64

PRPSAP1
False    183
Name: PRPSAP1, dtype: int64

PRPSAP2
False    183
Name: PRPSAP2, dtype: int64

PRR11
False    179
True       4
Name: PRR11, dtype: int64

PRR12
False    183
Name: PRR12, dtype: int64

PRR13
False    183
Name: PRR13, dtype: int64

PRR14
False    183
Name: PRR14, dtype: int64

PRR15L
False    183
Name: PRR15L, dtype: int64

PRR15
False    183
Name: PRR15, dtype: int64

PRR16
False    183
Name: PRR16, dtype: int64

PRR18
False    170
True      13
Name: PRR18, dtype: int64

PRR19
False    183
Name: PRR19, dtype: int64

PRR22
False    183
Name: PRR22, dtype: int64

PRR24
False    183
Name: PRR24, dtype: int64

PRR3
False    183
Name: PRR3, dtype: int64

PRR4
False    183
Name: PRR4, dtype: int64

PRR5-ARHGAP8
False    179
True       4
Name: PRR5-ARHGAP8, dtype: int64

PRR5L
False    183
Name: PRR5L, dtype: int64

PRR5
False    183
Name: PRR5, dtype: int64

PRR7
False    183
Name: PRR7, dtype: int64

PRRC1
False    183
Name: PRRC1, dtype: int64

PRRG1
False    183
Name: PRRG1, dtype: int64

PRRG2
False    183
Name: PRRG2, dtype: int64

PRRG3
False    157
True      26
Name: PRRG3, dtype: int64

PRRG4
False    183
Name: PRRG4, dtype: int64

PRRT1
False    183
Name: PRRT1, dtype: int64

PRRT2
False    183
Name: PRRT2, dtype: int64

PRRT3
False    183
Name: PRRT3, dtype: int64

PRRT4
False    174
True       9
Name: PRRT4, dtype: int64

PRRX1
False    183
Name: PRRX1, dtype: int64

PRRX2
False    183
Name: PRRX2, dtype: int64

PRSS12
False    183
Name: PRSS12, dtype: int64

PRSS16
False    182
True       1
Name: PRSS16, dtype: int64

PRSS1
False    182
True       1
Name: PRSS1, dtype: int64

PRSS21
False    175
True       8
Name: PRSS21, dtype: int64

PRSS22
False    182
True       1
Name: PRSS22, dtype: int64

PRSS23
False    183
Name: PRSS23, dtype: int64

PRSS27
False    183
Name: PRSS27, dtype: int64

PRSS30P
False    182
True       1
Name: PRSS30P, dtype: int64

PRSS33
False    168
True      15
Name: PRSS33, dtype: int64

PRSS35
False    183
Name: PRSS35, dtype: int64

PRSS36
False    183
Name: PRSS36, dtype: int64

PRSS37
False    95
True     88
Name: PRSS37, dtype: int64

PRSS3
False    183
Name: PRSS3, dtype: int64

PRSS41
False    107
True      76
Name: PRSS41, dtype: int64

PRSS45
False    152
True      31
Name: PRSS45, dtype: int64

PRSS50
False    179
True       4
Name: PRSS50, dtype: int64

PRSS53
False    183
Name: PRSS53, dtype: int64

PRSS55
True     103
False     80
Name: PRSS55, dtype: int64

PRSS8
False    183
Name: PRSS8, dtype: int64

PRSSL1
True     106
False     77
Name: PRSSL1, dtype: int64

PRTFDC1
False    183
Name: PRTFDC1, dtype: int64

PRTG
False    183
Name: PRTG, dtype: int64

PRTN3
False    115
True      68
Name: PRTN3, dtype: int64

PRUNE2
False    183
Name: PRUNE2, dtype: int64

PRUNE
False    183
Name: PRUNE, dtype: int64

PRX
False    183
Name: PRX, dtype: int64

PSAPL1
False    159
True      24
Name: PSAPL1, dtype: int64

PSAP
False    183
Name: PSAP, dtype: int64

PSAT1
False    183
Name: PSAT1, dtype: int64

PSCA
False    181
True       2
Name: PSCA, dtype: int64

PSD2
False    180
True       3
Name: PSD2, dtype: int64

PSD3
False    183
Name: PSD3, dtype: int64

PSD4
False    183
Name: PSD4, dtype: int64

PSD
False    183
Name: PSD, dtype: int64

PSEN1
False    183
Name: PSEN1, dtype: int64

PSEN2
False    183
Name: PSEN2, dtype: int64

PSENEN
False    183
Name: PSENEN, dtype: int64

PSG4
False    100
True      83
Name: PSG4, dtype: int64

PSG5
True     93
False    90
Name: PSG5, dtype: int64

PSG9
True     114
False     69
Name: PSG9, dtype: int64

PSIMCT-1
False    179
True       4
Name: PSIMCT-1, dtype: int64

PSIP1
False    183
Name: PSIP1, dtype: int64

PSKH1
False    183
Name: PSKH1, dtype: int64

PSMA1
False    183
Name: PSMA1, dtype: int64

PSMA2
False    183
Name: PSMA2, dtype: int64

PSMA3
False    183
Name: PSMA3, dtype: int64

PSMA4
False    183
Name: PSMA4, dtype: int64

PSMA5
False    183
Name: PSMA5, dtype: int64

PSMA6
False    183
Name: PSMA6, dtype: int64

PSMA7
False    183
Name: PSMA7, dtype: int64

PSMA8
False    95
True     88
Name: PSMA8, dtype: int64

PSMB10
False    183
Name: PSMB10, dtype: int64

PSMB1
False    183
Name: PSMB1, dtype: int64

PSMB2
False    183
Name: PSMB2, dtype: int64

PSMB3
False    183
Name: PSMB3, dtype: int64

PSMB4
False    183
Name: PSMB4, dtype: int64

PSMB5
False    183
Name: PSMB5, dtype: int64

PSMB6
False    183
Name: PSMB6, dtype: int64

PSMB7
False    183
Name: PSMB7, dtype: int64

PSMB8
False    183
Name: PSMB8, dtype: int64

PSMB9
False    183
Name: PSMB9, dtype: int64

PSMC1
False    183
Name: PSMC1, dtype: int64

PSMC2
False    183
Name: PSMC2, dtype: int64

PSMC3IP
False    183
Name: PSMC3IP, dtype: int64

PSMC3
False    183
Name: PSMC3, dtype: int64

PSMC4
False    183
Name: PSMC4, dtype: int64

PSMC5
False    183
Name: PSMC5, dtype: int64

PSMC6
False    183
Name: PSMC6, dtype: int64

PSMD10
False    183
Name: PSMD10, dtype: int64

PSMD11
False    183
Name: PSMD11, dtype: int64

PSMD12
False    183
Name: PSMD12, dtype: int64

PSMD13
False    183
Name: PSMD13, dtype: int64

PSMD14
False    183
Name: PSMD14, dtype: int64

PSMD1
False    183
Name: PSMD1, dtype: int64

PSMD2
False    183
Name: PSMD2, dtype: int64

PSMD3
False    183
Name: PSMD3, dtype: int64

PSMD4
False    183
Name: PSMD4, dtype: int64

PSMD5
False    183
Name: PSMD5, dtype: int64

PSMD6
False    183
Name: PSMD6, dtype: int64

PSMD7
False    183
Name: PSMD7, dtype: int64

PSMD8
False    183
Name: PSMD8, dtype: int64

PSMD9
False    183
Name: PSMD9, dtype: int64

PSME1
False    183
Name: PSME1, dtype: int64

PSME2
False    183
Name: PSME2, dtype: int64

PSME3
False    183
Name: PSME3, dtype: int64

PSME4
False    183
Name: PSME4, dtype: int64

PSMF1
False    183
Name: PSMF1, dtype: int64

PSMG1
False    183
Name: PSMG1, dtype: int64

PSMG2
False    183
Name: PSMG2, dtype: int64

PSMG3
False    183
Name: PSMG3, dtype: int64

PSMG4
False    183
Name: PSMG4, dtype: int64

PSORS1C1
False    181
True       2
Name: PSORS1C1, dtype: int64

PSORS1C2
False    175
True       8
Name: PSORS1C2, dtype: int64

PSORS1C3
False    173
True      10
Name: PSORS1C3, dtype: int64

PSPC1
False    183
Name: PSPC1, dtype: int64

PSPH
False    183
Name: PSPH, dtype: int64

PSPN
False    137
True      46
Name: PSPN, dtype: int64

PSRC1
False    183
Name: PSRC1, dtype: int64

PSTK
False    183
Name: PSTK, dtype: int64

PSTPIP1
False    183
Name: PSTPIP1, dtype: int64

PSTPIP2
False    183
Name: PSTPIP2, dtype: int64

PTAFR
False    183
Name: PTAFR, dtype: int64

PTAR1
False    183
Name: PTAR1, dtype: int64

PTBP1
False    183
Name: PTBP1, dtype: int64

PTBP2
False    183
Name: PTBP2, dtype: int64

PTCD1
False    183
Name: PTCD1, dtype: int64

PTCD2
False    183
Name: PTCD2, dtype: int64

PTCD3
False    183
Name: PTCD3, dtype: int64

PTCH1
False    183
Name: PTCH1, dtype: int64

PTCH2
False    183
Name: PTCH2, dtype: int64

PTCHD1
False    172
True      11
Name: PTCHD1, dtype: int64

PTCHD2

False    180
True       3
Name: PTCHD2, dtype: int64

PTCHD3
False    145
True      38
Name: PTCHD3, dtype: int64

PTCRA
False    168
True      15
Name: PTCRA, dtype: int64

PTDSS1
False    183
Name: PTDSS1, dtype: int64

PTDSS2
False    183
Name: PTDSS2, dtype: int64

PTENP1
False    183
Name: PTENP1, dtype: int64

PTEN
False    183
Name: PTEN, dtype: int64

PTER
False    183
Name: PTER, dtype: int64

PTF1A
False    117
True      66
Name: PTF1A, dtype: int64

PTGDR
False    181
True       2
Name: PTGDR, dtype: int64

PTGDS
False    183
Name: PTGDS, dtype: int64

PTGER1
False    178
True       5
Name: PTGER1, dtype: int64

PTGER2
False    183
Name: PTGER2, dtype: int64

PTGER3
False    183
Name: PTGER3, dtype: int64

PTGER4
False    183
Name: PTGER4, dtype: int64

PTGES2
False    183
Name: PTGES2, dtype: int64

PTGES3
False    183
Name: PTGES3, dtype: int64

PTGES
False    183
Name: PTGES, dtype: int64

PTGFRN
False    183
Name: PTGFRN, dtype: int64

PTGFR
False    183
Name: PTGFR, dtype: int64

PTGIR
False    183
Name: PTGIR, dtype: int64

PTGIS
False    183
Name: PTGIS, dtype: int64

PTGR1
False    183
Name: PTGR1, dtype: int64

PTGR2
False    183
Name: PTGR2, dtype: int64

PTGS1
False    183
Name: PTGS1, dtype: int64

PTGS2
False    183
Name: PTGS2, dtype: int64

PTH1R
False    183
Name: PTH1R, dtype: int64

PTH2R
False    170
True      13
Name: PTH2R, dtype: int64

PTHLH
False    183
Name: PTHLH, dtype: int64

PTK2B
False    183
Name: PTK2B, dtype: int64

PTK2
False    183
Name: PTK2, dtype: int64

PTK6
False    183
Name: PTK6, dtype: int64

PTK7
False    183
Name: PTK7, dtype: int64

PTMA
False    183
Name: PTMA, dtype: int64

PTMS
False    183
Name: PTMS, dtype: int64

PTN
False    183
Name: PTN, dtype: int64

PTOV1
False    183
Name: PTOV1, dtype: int64

PTP4A1
False    183
Name: PTP4A1, dtype: int64

PTP4A2
False    183
Name: PTP4A2, dtype: int64

PTP4A3
False    183
Name: PTP4A3, dtype: int64

PTPDC1
False    183
Name: PTPDC1, dtype: int64

PTPLAD1
False    183
Name: PTPLAD1, dtype: int64

PTPLAD2
False    183
Name: PTPLAD2, dtype: int64

PTPLA
False    183
Name: PTPLA, dtype: int64

PTPLB
False    183
Name: PTPLB, dtype: int64

PTPMT1
False    183
Name: PTPMT1, dtype: int64

PTPN11
False    183
Name: PTPN11, dtype: int64

PTPN12
False    183
Name: PTPN12, dtype: int64

PTPN13
False    183
Name: PTPN13, dtype: int64

PTPN14
False    183
Name: PTPN14, dtype: int64

PTPN18
False    183
Name: PTPN18, dtype: int64

PTPN1
False    183
Name: PTPN1, dtype: int64

PTPN20B
False    181
True       2
Name: PTPN20B, dtype: int64

PTPN21
False    183
Name: PTPN21, dtype: int64

PTPN22
False    183
Name: PTPN22, dtype: int64

PTPN23
False    183
Name: PTPN23, dtype: int64

PTPN2
False    183
Name: PTPN2, dtype: int64

PTPN3
False    183
Name: PTPN3, dtype: int64

PTPN4
False    183
Name: PTPN4, dtype: int64

PTPN5
False    179
True       4
Name: PTPN5, dtype: int64

PTPN6
False    183
Name: PTPN6, dtype: int64

PTPN7
False    183
Name: PTPN7, dtype: int64

PTPN9
False    183
Name: PTPN9, dtype: int64

PTPRA
False    183
Name: PTPRA, dtype: int64

PTPRB
False    183
Name: PTPRB, dtype: int64

PTPRCAP
False    183
Name: PTPRCAP, dtype: int64

PTPRC
False    183
Name: PTPRC, dtype: int64

PTPRD
False    183
Name: PTPRD, dtype: int64

PTPRE
False    183
Name: PTPRE, dtype: int64

PTPRF
False    183
Name: PTPRF, dtype: int64

PTPRG
False    183
Name: PTPRG, dtype: int64

PTPRH
False    183
Name: PTPRH, dtype: int64

PTPRJ
False    183
Name: PTPRJ, dtype: int64

PTPRK
False    183
Name: PTPRK, dtype: int64

PTPRM
False    183
Name: PTPRM, dtype: int64

PTPRN2
False    183
Name: PTPRN2, dtype: int64

PTPRN
False    183
Name: PTPRN, dtype: int64

PTPRO
False    183
Name: PTPRO, dtype: int64

PTPRQ
False    149
True      34
Name: PTPRQ, dtype: int64

PTPRR
False    183
Name: PTPRR, dtype: int64

PTPRS
False    183
Name: PTPRS, dtype: int64

PTPRT
False    181
True       2
Name: PTPRT, dtype: int64

PTPRU
False    183
Name: PTPRU, dtype: int64

PTPRVP
False    156
True      27
Name: PTPRVP, dtype: int64

PTPRZ1
False    183
Name: PTPRZ1, dtype: int64

PTRF
False    183
Name: PTRF, dtype: int64

PTRH1
False    183
Name: PTRH1, dtype: int64

PTRH2
False    183
Name: PTRH2, dtype: int64

PTS
False    183
Name: PTS, dtype: int64

PTTG1IP
False    183
Name: PTTG1IP, dtype: int64

PTTG1
False    183
Name: PTTG1, dtype: int64

PTTG2
False    130
True      53
Name: PTTG2, dtype: int64

PTTG3P
False    161
True      22
Name: PTTG3P, dtype: int64

PTX3
False    182
True       1
Name: PTX3, dtype: int64

PTX4
False    105
True      78
Name: PTX4, dtype: int64

PUF60
False    183
Name: PUF60, dtype: int64

PUM1
False    183
Name: PUM1, dtype: int64

PUM2
False    183
Name: PUM2, dtype: int64

PURA
False    183
Name: PURA, dtype: int64

PURB
False    183
Name: PURB, dtype: int64

PURG
False    182
True       1
Name: PURG, dtype: int64

PUS10
False    183
Name: PUS10, dtype: int64

PUS1
False    183
Name: PUS1, dtype: int64

PUS3
False    183
Name: PUS3, dtype: int64

PUS7L
False    183
Name: PUS7L, dtype: int64

PUS7
False    183
Name: PUS7, dtype: int64

PUSL1
False    183
Name: PUSL1, dtype: int64

PVALB
False    153
True      30
Name: PVALB, dtype: int64

PVRIG
False    183
Name: PVRIG, dtype: int64

PVRL1
False    183
Name: PVRL1, dtype: int64

PVRL2
False    183
Name: PVRL2, dtype: int64

PVRL3
False    183
Name: PVRL3, dtype: int64

PVRL4
False    181
True       2
Name: PVRL4, dtype: int64

PVR
False    183
Name: PVR, dtype: int64

PVT1
False    183
Name: PVT1, dtype: int64

PWP1
False    183
Name: PWP1, dtype: int64

PWP2
False    183
Name: PWP2, dtype: int64

PWRN1
True     100
False     83
Name: PWRN1, dtype: int64

PWWP2A
False    183
Name: PWWP2A, dtype: int64

PWWP2B
False    183
Name: PWWP2B, dtype: int64

PXDNL
False    182
True       1
Name: PXDNL, dtype: int64

PXDN
False    183
Name: PXDN, dtype: int64

PXK
False    183
Name: PXK, dtype: int64

PXMP2
False    183
Name: PXMP2, dtype: int64

PXMP4
False    183
Name: PXMP4, dtype: int64

PXN
False    183
Name: PXN, dtype: int64

PXT1
False    136
True      47
Name: PXT1, dtype: int64

PYCARD
False    183
Name: PYCARD, dtype: int64

PYCR1
False    183
Name: PYCR1, dtype: int64

PYCR2
False    183
Name: PYCR2, dtype: int64

PYCRL
False    183
Name: PYCRL, dtype: int64

PYDC1
False    93
True     90
Name: PYDC1, dtype: int64

PYGB
False    183
Name: PYGB, dtype: int64

PYGL
False    183
Name: PYGL, dtype: int64

PYGM
False    183
Name: PYGM, dtype: int64

PYGO1
False    180
True       3
Name: PYGO1, dtype: int64

PYGO2
False    183
Name: PYGO2, dtype: int64

PYHIN1
False    182
True       1
Name: PYHIN1, dtype: int64

PYROXD1
False    183
Name: PYROXD1, dtype: int64

PYROXD2
False    183
Name: PYROXD2, dtype: int64

PYY2
False    178
True       5
Name: PYY2, dtype: int64

PYY
False    157
True      26
Name: PYY, dtype: int64

PZP
False    139
True      44
Name: PZP, dtype: int64

ProSAPiP1
False    183
Name: ProSAPiP1, dtype: int64

QARS
False    183
Name: QARS, dtype: int64

QDPR
False    183
Name: QDPR, dtype: int64

QKI
False    183
Name: QKI, dtype: int64

QPCTL
False    183
Name: QPCTL, dtype: int64

QPCT
False    183
Name: QPCT, dtype: int64

QPRT
False    183
Name: QPRT, dtype: int64

QRFPR
True     97
False    86
Name: QRFPR, dtype: int64

QRFP
False    152
True      31
Name: QRFP, dtype: int64

QRICH1
False    183
Name: QRICH1, dtype: int64

QRICH2
False    183
Name: QRICH2, dtype: int64

QRSL1
False    183
Name: QRSL1, dtype: int64

QSER1
False    183
Name: QSER1, dtype: int64

QSOX1
False    183
Name: QSOX1, dtype: int64

QSOX2
False    183
Name: QSOX2, dtype: int64

QTRT1
False    183
Name: QTRT1, dtype: int64

QTRTD1
False    183
Name: QTRTD1, dtype: int64

R3HCC1
False    183
Name: R3HCC1, dtype: int64

R3HDM1
False    183
Name: R3HDM1, dtype: int64

R3HDM2
False    183
Name: R3HDM2, dtype: int64

R3HDML
False    115
True      68
Name: R3HDML, dtype: int64

RAB10
False    183
Name: RAB10, dtype: int64

RAB11A
False    183
Name: RAB11A, dtype: int64

RAB11B
False    183
Name: RAB11B, dtype: int64

RAB11FIP1
False    183
Name: RAB11FIP1, dtype: int64

RAB11FIP2
False    183
Name: RAB11FIP2, dtype: int64

RAB11FIP3
False    183
Name: RAB11FIP3, dtype: int64

RAB11FIP4
False    183
Name: RAB11FIP4, dtype: int64

RAB11FIP5
False    183
Name: RAB11FIP5, dtype: int64

RAB12
False    183
Name: RAB12, dtype: int64

RAB13
False    183
Name: RAB13, dtype: int64

RAB14
False    183
Name: RAB14, dtype: int64

RAB15

False    183
Name: RAB15, dtype: int64

RAB17
False    183
Name: RAB17, dtype: int64

RAB18
False    183
Name: RAB18, dtype: int64

RAB19
False    181
True       2
Name: RAB19, dtype: int64

RAB1A
False    183
Name: RAB1A, dtype: int64

RAB1B
False    183
Name: RAB1B, dtype: int64

RAB20
False    183
Name: RAB20, dtype: int64

RAB21
False    183
Name: RAB21, dtype: int64

RAB22A
False    183
Name: RAB22A, dtype: int64

RAB23
False    183
Name: RAB23, dtype: int64

RAB24
False    183
Name: RAB24, dtype: int64

RAB25
False    183
Name: RAB25, dtype: int64

RAB26
False    183
Name: RAB26, dtype: int64

RAB27A
False    183
Name: RAB27A, dtype: int64

RAB27B
False    183
Name: RAB27B, dtype: int64

RAB28
False    183
Name: RAB28, dtype: int64

RAB2A
False    183
Name: RAB2A, dtype: int64

RAB2B
False    183
Name: RAB2B, dtype: int64

RAB30
False    183
Name: RAB30, dtype: int64

RAB31
False    183
Name: RAB31, dtype: int64

RAB32
False    183
Name: RAB32, dtype: int64

RAB33A
False    183
Name: RAB33A, dtype: int64

RAB33B
False    183
Name: RAB33B, dtype: int64

RAB34
False    183
Name: RAB34, dtype: int64

RAB35
False    183
Name: RAB35, dtype: int64

RAB36
False    183
Name: RAB36, dtype: int64

RAB37
False    183
Name: RAB37, dtype: int64

RAB38
False    183
Name: RAB38, dtype: int64

RAB39B
False    182
True       1
Name: RAB39B, dtype: int64

RAB39
False    175
True       8
Name: RAB39, dtype: int64

RAB3A
False    183
Name: RAB3A, dtype: int64

RAB3B
False    181
True       2
Name: RAB3B, dtype: int64

RAB3C
False    181
True       2
Name: RAB3C, dtype: int64

RAB3D
False    183
Name: RAB3D, dtype: int64

RAB3GAP1
False    183
Name: RAB3GAP1, dtype: int64

RAB3GAP2
False    183
Name: RAB3GAP2, dtype: int64

RAB3IL1
False    183
Name: RAB3IL1, dtype: int64

RAB3IP
False    183
Name: RAB3IP, dtype: int64

RAB40AL
False    182
True       1
Name: RAB40AL, dtype: int64

RAB40A
False    183
Name: RAB40A, dtype: int64

RAB40B
False    183
Name: RAB40B, dtype: int64

RAB40C
False    183
Name: RAB40C, dtype: int64

RAB41
False    172
True      11
Name: RAB41, dtype: int64

RAB42
False    183
Name: RAB42, dtype: int64

RAB43
False    183
Name: RAB43, dtype: int64

RAB4A
False    183
Name: RAB4A, dtype: int64

RAB4B
False    183
Name: RAB4B, dtype: int64

RAB5A
False    183
Name: RAB5A, dtype: int64

RAB5B
False    183
Name: RAB5B, dtype: int64

RAB5C
False    183
Name: RAB5C, dtype: int64

RAB6A
False    183
Name: RAB6A, dtype: int64

RAB6B
False    183
Name: RAB6B, dtype: int64

RAB6C
False    183
Name: RAB6C, dtype: int64

RAB7A
False    183
Name: RAB7A, dtype: int64

RAB7L1
False    183
Name: RAB7L1, dtype: int64

RAB8A
False    183
Name: RAB8A, dtype: int64

RAB8B
False    183
Name: RAB8B, dtype: int64

RAB9A
False    183
Name: RAB9A, dtype: int64

RAB9B
False    181
True       2
Name: RAB9B, dtype: int64

RABAC1
False    183
Name: RABAC1, dtype: int64

RABEP1
False    183
Name: RABEP1, dtype: int64

RABEP2
False    183
Name: RABEP2, dtype: int64

RABEPK
False    183
Name: RABEPK, dtype: int64

RABGAP1L
False    183
Name: RABGAP1L, dtype: int64

RABGAP1
False    183
Name: RABGAP1, dtype: int64

RABGEF1
False    183
Name: RABGEF1, dtype: int64

RABGGTA
False    183
Name: RABGGTA, dtype: int64

RABGGTB
False    183
Name: RABGGTB, dtype: int64

RABIF
False    183
Name: RABIF, dtype: int64

RABL2A
False    183
Name: RABL2A, dtype: int64

RABL2B
False    183
Name: RABL2B, dtype: int64

RABL3
False    183
Name: RABL3, dtype: int64

RABL5
False    183
Name: RABL5, dtype: int64

RAC1
False    183
Name: RAC1, dtype: int64

RAC2
False    183
Name: RAC2, dtype: int64

RAC3
False    183
Name: RAC3, dtype: int64

RACGAP1P
False    168
True      15
Name: RACGAP1P, dtype: int64

RACGAP1
False    183
Name: RACGAP1, dtype: int64

RAD17
False    183
Name: RAD17, dtype: int64

RAD18
False    183
Name: RAD18, dtype: int64

RAD1
False    183
Name: RAD1, dtype: int64

RAD21
False    183
Name: RAD21, dtype: int64

RAD23A
False    183
Name: RAD23A, dtype: int64

RAD23B
False    183
Name: RAD23B, dtype: int64

RAD50
False    183
Name: RAD50, dtype: int64

RAD51AP1
False    183
Name: RAD51AP1, dtype: int64

RAD51AP2
False    166
True      17
Name: RAD51AP2, dtype: int64

RAD51C
False    183
Name: RAD51C, dtype: int64

RAD51L1
False    183
Name: RAD51L1, dtype: int64

RAD51L3
False    183
Name: RAD51L3, dtype: int64

RAD51
False    183
Name: RAD51, dtype: int64

RAD52
False    183
Name: RAD52, dtype: int64

RAD54B
False    183
Name: RAD54B, dtype: int64

RAD54L2
False    183
Name: RAD54L2, dtype: int64

RAD54L
False    183
Name: RAD54L, dtype: int64

RAD9A
False    183
Name: RAD9A, dtype: int64

RAD9B
False    183
Name: RAD9B, dtype: int64

RADIL
False    183
Name: RADIL, dtype: int64

RAE1
False    183
Name: RAE1, dtype: int64

RAET1E
False    180
True       3
Name: RAET1E, dtype: int64

RAET1G
False    182
True       1
Name: RAET1G, dtype: int64

RAET1K
False    171
True      12
Name: RAET1K, dtype: int64

RAET1L
False    169
True      14
Name: RAET1L, dtype: int64

RAF1
False    183
Name: RAF1, dtype: int64

RAG1AP1
False    183
Name: RAG1AP1, dtype: int64

RAG1
False    183
Name: RAG1, dtype: int64

RAGE
False    183
Name: RAGE, dtype: int64

RAI14
False    183
Name: RAI14, dtype: int64

RAI1
False    183
Name: RAI1, dtype: int64

RAI2
False    183
Name: RAI2, dtype: int64

RALA
False    183
Name: RALA, dtype: int64

RALBP1
False    183
Name: RALBP1, dtype: int64

RALB
False    183
Name: RALB, dtype: int64

RALGAPA1
False    183
Name: RALGAPA1, dtype: int64

RALGAPA2
False    183
Name: RALGAPA2, dtype: int64

RALGAPB
False    183
Name: RALGAPB, dtype: int64

RALGDS
False    183
Name: RALGDS, dtype: int64

RALGPS1
False    183
Name: RALGPS1, dtype: int64

RALGPS2
False    183
Name: RALGPS2, dtype: int64

RALYL
False    169
True      14
Name: RALYL, dtype: int64

RALY
False    183
Name: RALY, dtype: int64

RAMP1
False    183
Name: RAMP1, dtype: int64

RAMP2
False    183
Name: RAMP2, dtype: int64

RAMP3
False    183
Name: RAMP3, dtype: int64

RANBP10
False    183
Name: RANBP10, dtype: int64

RANBP17
False    183
Name: RANBP17, dtype: int64

RANBP1
False    183
Name: RANBP1, dtype: int64

RANBP2
False    183
Name: RANBP2, dtype: int64

RANBP3L
False    163
True      20
Name: RANBP3L, dtype: int64

RANBP3
False    183
Name: RANBP3, dtype: int64

RANBP6
False    183
Name: RANBP6, dtype: int64

RANBP9
False    183
Name: RANBP9, dtype: int64

RANGAP1
False    183
Name: RANGAP1, dtype: int64

RANGRF
False    183
Name: RANGRF, dtype: int64

RAN
False    183
Name: RAN, dtype: int64

RAP1A
False    183
Name: RAP1A, dtype: int64

RAP1B
False    183
Name: RAP1B, dtype: int64

RAP1GAP2
False    183
Name: RAP1GAP2, dtype: int64

RAP1GAP
False    183
Name: RAP1GAP, dtype: int64

RAP1GDS1
False    183
Name: RAP1GDS1, dtype: int64

RAP2A
False    183
Name: RAP2A, dtype: int64

RAP2B
False    183
Name: RAP2B, dtype: int64

RAP2C
False    183
Name: RAP2C, dtype: int64

RAPGEF1
False    183
Name: RAPGEF1, dtype: int64

RAPGEF2
False    183
Name: RAPGEF2, dtype: int64

RAPGEF3
False    183
Name: RAPGEF3, dtype: int64

RAPGEF4
False    183
Name: RAPGEF4, dtype: int64

RAPGEF5
False    183
Name: RAPGEF5, dtype: int64

RAPGEF6
False    183
Name: RAPGEF6, dtype: int64

RAPGEFL1
False    183
Name: RAPGEFL1, dtype: int64

RAPH1
False    183
Name: RAPH1, dtype: int64

RAPSN
False    170
True      13
Name: RAPSN, dtype: int64

RARA
False    183
Name: RARA, dtype: int64

RARB
False    183
Name: RARB, dtype: int64

RARG
False    183
Name: RARG, dtype: int64

RARRES1
False    183
Name: RARRES1, dtype: int64

RARRES2
False    183
Name: RARRES2, dtype: int64

RARRES3
False    183
Name: RARRES3, dtype: int64

RARS2
False    183
Name: RARS2, dtype: int64

RARS
False    183
Name: RARS, dtype: int64

RASA1
False    183
Name: RASA1, dtype: int64

RASA2
False    183
Name: RASA2, dtype: int64

RASA3
False    183
Name: RASA3, dtype: int64

RASA4P
False    183
Name: RASA4P, dtype: int64

RASA4
False    183
Name: RASA4, dtype: int64

RASAL1
False    182
True       1
Name: RASAL1, dtype: int64

RASAL2
False    183
Name: RASAL2, dtype: int64

RASAL3
False    183
Name: RASAL3, dtype: int64

RASD1
False    183
Name: RASD1, dtype: int64

RASD2
False    183
Name: RASD2, dtype: int64

RASEF
False    181
True       2
Name: RASEF, dtype: int64

RASGEF1A
False    182
True       1
Name: RASGEF1A, dtype: int64

RASGEF1B
False    183
Name: RASGEF1B, dtype: int64

RASGEF1C
False    159
True      24
Name: RASGEF1C, dtype: int64

RASGRF1
False    182
True       1
Name: RASGRF1, dtype: int64

RASGRF2
False    183
Name: RASGRF2, dtype: int64

RASGRP1
False    183
Name: RASGRP1, dtype: int64

RASGRP2
False    183
Name: RASGRP2, dtype: int64

RASGRP3
False    183
Name: RASGRP3, dtype: int64

RASGRP4
False    183
Name: RASGRP4, dtype: int64

RASIP1
False    183
Name: RASIP1, dtype: int64

RASL10A
False    183
Name: RASL10A, dtype: int64

RASL10B
False    183
Name: RASL10B, dtype: int64

RASL11A
False    183
Name: RASL11A, dtype: int64

RASL11B
False    183
Name: RASL11B, dtype: int64

RASL12
False    183
Name: RASL12, dtype: int64

RASSF10

False    169
True      14
Name: RASSF10, dtype: int64

RASSF1
False    183
Name: RASSF1, dtype: int64

RASSF2
False    183
Name: RASSF2, dtype: int64

RASSF3
False    183
Name: RASSF3, dtype: int64

RASSF4
False    183
Name: RASSF4, dtype: int64

RASSF5
False    183
Name: RASSF5, dtype: int64

RASSF6
False    183
Name: RASSF6, dtype: int64

RASSF7
False    183
Name: RASSF7, dtype: int64

RASSF8
False    183
Name: RASSF8, dtype: int64

RASSF9
False    182
True       1
Name: RASSF9, dtype: int64

RAVER1
False    183
Name: RAVER1, dtype: int64

RAVER2
False    183
Name: RAVER2, dtype: int64

RAX
True     121
False     62
Name: RAX, dtype: int64

RB1CC1
False    183
Name: RB1CC1, dtype: int64

RB1
False    183
Name: RB1, dtype: int64

RBAK
False    183
Name: RBAK, dtype: int64

RBBP4
False    183
Name: RBBP4, dtype: int64

RBBP5
False    183
Name: RBBP5, dtype: int64

RBBP6
False    183
Name: RBBP6, dtype: int64

RBBP7
False    183
Name: RBBP7, dtype: int64

RBBP8
False    183
Name: RBBP8, dtype: int64

RBBP9
False    183
Name: RBBP9, dtype: int64

RBCK1
False    183
Name: RBCK1, dtype: int64

RBKS
False    183
Name: RBKS, dtype: int64

RBL1
False    183
Name: RBL1, dtype: int64

RBL2
False    183
Name: RBL2, dtype: int64

RBM10
False    183
Name: RBM10, dtype: int64

RBM11
False    182
True       1
Name: RBM11, dtype: int64

RBM12B
False    183
Name: RBM12B, dtype: int64

RBM12
False    183
Name: RBM12, dtype: int64

RBM14
False    183
Name: RBM14, dtype: int64

RBM15B
False    183
Name: RBM15B, dtype: int64

RBM15
False    183
Name: RBM15, dtype: int64

RBM16
False    183
Name: RBM16, dtype: int64

RBM17
False    183
Name: RBM17, dtype: int64

RBM18
False    183
Name: RBM18, dtype: int64

RBM19
False    183
Name: RBM19, dtype: int64

RBM20
False    183
Name: RBM20, dtype: int64

RBM22
False    183
Name: RBM22, dtype: int64

RBM23
False    183
Name: RBM23, dtype: int64

RBM24
False    182
True       1
Name: RBM24, dtype: int64

RBM25
False    183
Name: RBM25, dtype: int64

RBM26
False    183
Name: RBM26, dtype: int64

RBM27
False    183
Name: RBM27, dtype: int64

RBM28
False    183
Name: RBM28, dtype: int64

RBM33
False    183
Name: RBM33, dtype: int64

RBM34
False    183
Name: RBM34, dtype: int64

RBM38
False    183
Name: RBM38, dtype: int64

RBM39
False    183
Name: RBM39, dtype: int64

RBM3
False    183
Name: RBM3, dtype: int64

RBM41
False    183
Name: RBM41, dtype: int64

RBM42
False    183
Name: RBM42, dtype: int64

RBM43
False    183
Name: RBM43, dtype: int64

RBM44
False    181
True       2
Name: RBM44, dtype: int64

RBM45
False    183
Name: RBM45, dtype: int64

RBM46
False    130
True      53
Name: RBM46, dtype: int64

RBM47
False    183
Name: RBM47, dtype: int64

RBM4B
False    183
Name: RBM4B, dtype: int64

RBM4
False    183
Name: RBM4, dtype: int64

RBM5
False    183
Name: RBM5, dtype: int64

RBM6
False    183
Name: RBM6, dtype: int64

RBM7
False    183
Name: RBM7, dtype: int64

RBM8A
False    183
Name: RBM8A, dtype: int64

RBM9
False    183
Name: RBM9, dtype: int64

RBMS1
False    183
Name: RBMS1, dtype: int64

RBMS2
False    183
Name: RBMS2, dtype: int64

RBMS3
False    183
Name: RBMS3, dtype: int64

RBMX2
False    183
Name: RBMX2, dtype: int64

RBMXL1
False    183
Name: RBMXL1, dtype: int64

RBMXL2
True     104
False     79
Name: RBMXL2, dtype: int64

RBMX
False    183
Name: RBMX, dtype: int64

RBP1
False    183
Name: RBP1, dtype: int64

RBP2
False    156
True      27
Name: RBP2, dtype: int64

RBP3
False    126
True      57
Name: RBP3, dtype: int64

RBP4
False    183
Name: RBP4, dtype: int64

RBP5
False    183
Name: RBP5, dtype: int64

RBP7
False    183
Name: RBP7, dtype: int64

RBPJL
False    129
True      54
Name: RBPJL, dtype: int64

RBPJ
False    183
Name: RBPJ, dtype: int64

RBPMS2
False    183
Name: RBPMS2, dtype: int64

RBPMS
False    183
Name: RBPMS, dtype: int64

RBX1
False    183
Name: RBX1, dtype: int64

RC3H1
False    183
Name: RC3H1, dtype: int64

RC3H2
False    183
Name: RC3H2, dtype: int64

RCAN1
False    183
Name: RCAN1, dtype: int64

RCAN2
False    183
Name: RCAN2, dtype: int64

RCAN3
False    183
Name: RCAN3, dtype: int64

RCBTB1
False    183
Name: RCBTB1, dtype: int64

RCBTB2
False    183
Name: RCBTB2, dtype: int64

RCC1
False    183
Name: RCC1, dtype: int64

RCC2
False    183
Name: RCC2, dtype: int64

RCCD1
False    183
Name: RCCD1, dtype: int64

RCE1
False    183
Name: RCE1, dtype: int64

RCHY1
False    183
Name: RCHY1, dtype: int64

RCL1
False    183
Name: RCL1, dtype: int64

RCN1
False    183
Name: RCN1, dtype: int64

RCN2
False    183
Name: RCN2, dtype: int64

RCN3
False    183
Name: RCN3, dtype: int64

RCOR1
False    183
Name: RCOR1, dtype: int64

RCOR2
False    183
Name: RCOR2, dtype: int64

RCOR3
False    183
Name: RCOR3, dtype: int64

RCSD1
False    183
Name: RCSD1, dtype: int64

RCVRN
False    177
True       6
Name: RCVRN, dtype: int64

RD3
False    162
True      21
Name: RD3, dtype: int64

RDBP
False    183
Name: RDBP, dtype: int64

RDH10
False    183
Name: RDH10, dtype: int64

RDH11
False    183
Name: RDH11, dtype: int64

RDH12
False    183
Name: RDH12, dtype: int64

RDH13
False    183
Name: RDH13, dtype: int64

RDH14
False    183
Name: RDH14, dtype: int64

RDH16
False    183
Name: RDH16, dtype: int64

RDH5
False    183
Name: RDH5, dtype: int64

RDH8
True     109
False     74
Name: RDH8, dtype: int64

RDM1
False    181
True       2
Name: RDM1, dtype: int64

RDX
False    183
Name: RDX, dtype: int64

REC8
False    183
Name: REC8, dtype: int64

RECK
False    183
Name: RECK, dtype: int64

RECQL4
False    183
Name: RECQL4, dtype: int64

RECQL5
False    183
Name: RECQL5, dtype: int64

RECQL
False    183
Name: RECQL, dtype: int64

REEP1
False    183
Name: REEP1, dtype: int64

REEP2
False    183
Name: REEP2, dtype: int64

REEP3
False    183
Name: REEP3, dtype: int64

REEP4
False    183
Name: REEP4, dtype: int64

REEP5
False    183
Name: REEP5, dtype: int64

REEP6
False    183
Name: REEP6, dtype: int64

REG1A
False    178
True       5
Name: REG1A, dtype: int64

REG1B
False    161
True      22
Name: REG1B, dtype: int64

REG1P
False    120
True      63
Name: REG1P, dtype: int64

REG3A
False    173
True      10
Name: REG3A, dtype: int64

REG3G
False    149
True      34
Name: REG3G, dtype: int64

REG4
False    181
True       2
Name: REG4, dtype: int64

RELA
False    183
Name: RELA, dtype: int64

RELB
False    183
Name: RELB, dtype: int64

RELL1
False    183
Name: RELL1, dtype: int64

RELL2
False    183
Name: RELL2, dtype: int64

RELN
False    183
Name: RELN, dtype: int64

RELT
False    183
Name: RELT, dtype: int64

REL
False    183
Name: REL, dtype: int64

REM1
False    183
Name: REM1, dtype: int64

REM2
False    183
Name: REM2, dtype: int64

RENBP
False    183
Name: RENBP, dtype: int64

REN
False    167
True      16
Name: REN, dtype: int64

REP15
False    183
Name: REP15, dtype: int64

REPIN1
False    183
Name: REPIN1, dtype: int64

REPS1
False    183
Name: REPS1, dtype: int64

REPS2
False    183
Name: REPS2, dtype: int64

RER1
False    183
Name: RER1, dtype: int64

RERE
False    183
Name: RERE, dtype: int64

RERGL
False    176
True       7
Name: RERGL, dtype: int64

RERG
False    183
Name: RERG, dtype: int64

REST
False    183
Name: REST, dtype: int64

RETN
False    172
True      11
Name: RETN, dtype: int64

RETSAT
False    183
Name: RETSAT, dtype: int64

RET
False    183
Name: RET, dtype: int64

REV1
False    183
Name: REV1, dtype: int64

REV3L
False    183
Name: REV3L, dtype: int64

REXO1
False    183
Name: REXO1, dtype: int64

REXO2
False    183
Name: REXO2, dtype: int64

REXO4
False    183
Name: REXO4, dtype: int64

RFC1
False    183
Name: RFC1, dtype: int64

RFC2
False    183
Name: RFC2, dtype: int64

RFC3
False    183
Name: RFC3, dtype: int64

RFC4
False    183
Name: RFC4, dtype: int64

RFC5
False    183
Name: RFC5, dtype: int64

RFESD
False    183
Name: RFESD, dtype: int64

RFFL
False    183
Name: RFFL, dtype: int64

RFK
False    183
Name: RFK, dtype: int64

RFNG
False    183
Name: RFNG, dtype: int64

RFPL1S
False    182
True       1
Name: RFPL1S, dtype: int64

RFPL1
False    120
True      63
Name: RFPL1, dtype: int64

RFPL2
False    167
True      16
Name: RFPL2, dtype: int64

RFPL3S
False    181
True       2
Name: RFPL3S, dtype: int64

RFPL3
True     128
False     55
Name: RFPL3, dtype: int64

RFPL4A
False    111
True      72
Name: RFPL4A, dtype: int64

RFPL4B
False    110
True      73
Name: RFPL4B, dtype: int64

RFT1
False    183
Name: RFT1, dtype: int64

RFTN1
False    183
Name: RFTN1, dtype: int64

RFTN2
False    183
Name: RFTN2, dtype: int64

RFWD2
False    183
Name: RFWD2, dtype: int64

RFWD3
False    183
Name: RFWD3, dtype: int64

RFX1

False    183
Name: RFX1, dtype: int64

RFX2
False    183
Name: RFX2, dtype: int64

RFX3
False    183
Name: RFX3, dtype: int64

RFX4
False    122
True      61
Name: RFX4, dtype: int64

RFX5
False    183
Name: RFX5, dtype: int64

RFX6
False    171
True      12
Name: RFX6, dtype: int64

RFX7
False    183
Name: RFX7, dtype: int64

RFX8
False    182
True       1
Name: RFX8, dtype: int64

RFXANK
False    183
Name: RFXANK, dtype: int64

RFXAP
False    183
Name: RFXAP, dtype: int64

RG9MTD1
False    183
Name: RG9MTD1, dtype: int64

RG9MTD2
False    183
Name: RG9MTD2, dtype: int64

RG9MTD3
False    183
Name: RG9MTD3, dtype: int64

RGAG1
False    166
True      17
Name: RGAG1, dtype: int64

RGAG4
False    183
Name: RGAG4, dtype: int64

RGL1
False    183
Name: RGL1, dtype: int64

RGL2
False    183
Name: RGL2, dtype: int64

RGL3
False    183
Name: RGL3, dtype: int64

RGL4
False    182
True       1
Name: RGL4, dtype: int64

RGMA
False    183
Name: RGMA, dtype: int64

RGMB
False    183
Name: RGMB, dtype: int64

RGNEF
False    183
Name: RGNEF, dtype: int64

RGN
False    182
True       1
Name: RGN, dtype: int64

RGP1
False    183
Name: RGP1, dtype: int64

RGPD1
False    183
Name: RGPD1, dtype: int64

RGPD3
False    183
Name: RGPD3, dtype: int64

RGPD4
False    183
Name: RGPD4, dtype: int64

RGPD5
False    182
True       1
Name: RGPD5, dtype: int64

RGPD6
False    183
Name: RGPD6, dtype: int64

RGS10
False    183
Name: RGS10, dtype: int64

RGS11
False    183
Name: RGS11, dtype: int64

RGS12
False    183
Name: RGS12, dtype: int64

RGS13
False    179
True       4
Name: RGS13, dtype: int64

RGS14
False    183
Name: RGS14, dtype: int64

RGS16
False    183
Name: RGS16, dtype: int64

RGS17
False    183
Name: RGS17, dtype: int64

RGS18
False    182
True       1
Name: RGS18, dtype: int64

RGS19
False    183
Name: RGS19, dtype: int64

RGS1
False    183
Name: RGS1, dtype: int64

RGS20
False    175
True       8
Name: RGS20, dtype: int64

RGS22
False    179
True       4
Name: RGS22, dtype: int64

RGS2
False    183
Name: RGS2, dtype: int64

RGS3
False    183
Name: RGS3, dtype: int64

RGS4
False    183
Name: RGS4, dtype: int64

RGS5
False    183
Name: RGS5, dtype: int64

RGS6
False    179
True       4
Name: RGS6, dtype: int64

RGS7BP
False    182
True       1
Name: RGS7BP, dtype: int64

RGS7
False    180
True       3
Name: RGS7, dtype: int64

RGS9BP
False    163
True      20
Name: RGS9BP, dtype: int64

RGS9
False    183
Name: RGS9, dtype: int64

RHAG
True     96
False    87
Name: RHAG, dtype: int64

RHBDD1
False    183
Name: RHBDD1, dtype: int64

RHBDD2
False    183
Name: RHBDD2, dtype: int64

RHBDD3
False    183
Name: RHBDD3, dtype: int64

RHBDF1
False    183
Name: RHBDF1, dtype: int64

RHBDF2
False    183
Name: RHBDF2, dtype: int64

RHBDL1
False    183
Name: RHBDL1, dtype: int64

RHBDL2
False    183
Name: RHBDL2, dtype: int64

RHBDL3
False    183
Name: RHBDL3, dtype: int64

RHBG
False    131
True      52
Name: RHBG, dtype: int64

RHCE
False    181
True       2
Name: RHCE, dtype: int64

RHCG
False    176
True       7
Name: RHCG, dtype: int64

RHD
False    168
True      15
Name: RHD, dtype: int64

RHEBL1
False    182
True       1
Name: RHEBL1, dtype: int64

RHEB
False    183
Name: RHEB, dtype: int64

RHOA
False    183
Name: RHOA, dtype: int64

RHOBTB1
False    183
Name: RHOBTB1, dtype: int64

RHOBTB2
False    183
Name: RHOBTB2, dtype: int64

RHOBTB3
False    183
Name: RHOBTB3, dtype: int64

RHOB
False    183
Name: RHOB, dtype: int64

RHOC
False    183
Name: RHOC, dtype: int64

RHOD
False    183
Name: RHOD, dtype: int64

RHOF
False    183
Name: RHOF, dtype: int64

RHOG
False    183
Name: RHOG, dtype: int64

RHOH
False    183
Name: RHOH, dtype: int64

RHOJ
False    183
Name: RHOJ, dtype: int64

RHOQ
False    183
Name: RHOQ, dtype: int64

RHOT1
False    183
Name: RHOT1, dtype: int64

RHOT2
False    183
Name: RHOT2, dtype: int64

RHOU
False    183
Name: RHOU, dtype: int64

RHOV
False    183
Name: RHOV, dtype: int64

RHOXF1
False    144
True      39
Name: RHOXF1, dtype: int64

RHO
True     121
False     62
Name: RHO, dtype: int64

RHPN1
False    183
Name: RHPN1, dtype: int64

RHPN2
False    183
Name: RHPN2, dtype: int64

RIBC1
False    183
Name: RIBC1, dtype: int64

RIBC2
False    183
Name: RIBC2, dtype: int64

RIC3
False    182
True       1
Name: RIC3, dtype: int64

RIC8A
False    183
Name: RIC8A, dtype: int64

RIC8B
False    183
Name: RIC8B, dtype: int64

RICH2
False    183
Name: RICH2, dtype: int64

RICTOR
False    183
Name: RICTOR, dtype: int64

RIF1
False    183
Name: RIF1, dtype: int64

RILPL1
False    183
Name: RILPL1, dtype: int64

RILPL2
False    183
Name: RILPL2, dtype: int64

RILP
False    183
Name: RILP, dtype: int64

RIMBP2
False    181
True       2
Name: RIMBP2, dtype: int64

RIMBP3C
False    178
True       5
Name: RIMBP3C, dtype: int64

RIMBP3
False    183
Name: RIMBP3, dtype: int64

RIMKLA
False    183
Name: RIMKLA, dtype: int64

RIMKLB
False    183
Name: RIMKLB, dtype: int64

RIMS1
False    164
True      19
Name: RIMS1, dtype: int64

RIMS2
False    179
True       4
Name: RIMS2, dtype: int64

RIMS3
False    183
Name: RIMS3, dtype: int64

RIMS4
False    181
True       2
Name: RIMS4, dtype: int64

RIN1
False    183
Name: RIN1, dtype: int64

RIN2
False    183
Name: RIN2, dtype: int64

RIN3
False    183
Name: RIN3, dtype: int64

RING1
False    183
Name: RING1, dtype: int64

RINL
False    183
Name: RINL, dtype: int64

RINT1
False    183
Name: RINT1, dtype: int64

RIOK1
False    183
Name: RIOK1, dtype: int64

RIOK2
False    183
Name: RIOK2, dtype: int64

RIOK3
False    183
Name: RIOK3, dtype: int64

RIPK1
False    183
Name: RIPK1, dtype: int64

RIPK2
False    183
Name: RIPK2, dtype: int64

RIPK3
False    183
Name: RIPK3, dtype: int64

RIPK4
False    183
Name: RIPK4, dtype: int64

RIPPLY1
False    130
True      53
Name: RIPPLY1, dtype: int64

RIPPLY2
False    134
True      49
Name: RIPPLY2, dtype: int64

RIT1
False    183
Name: RIT1, dtype: int64

RLBP1
True     100
False     83
Name: RLBP1, dtype: int64

RLF
False    183
Name: RLF, dtype: int64

RLIM
False    183
Name: RLIM, dtype: int64

RLN1
False    136
True      47
Name: RLN1, dtype: int64

RLN2
False    177
True       6
Name: RLN2, dtype: int64

RLTPR
False    183
Name: RLTPR, dtype: int64

RMI1
False    183
Name: RMI1, dtype: int64

RMND1
False    183
Name: RMND1, dtype: int64

RMND5A
False    183
Name: RMND5A, dtype: int64

RMND5B
False    183
Name: RMND5B, dtype: int64

RMRP
False    182
True       1
Name: RMRP, dtype: int64

RMST
False    165
True      18
Name: RMST, dtype: int64

RNASE10
False    122
True      61
Name: RNASE10, dtype: int64

RNASE13
False    157
True      26
Name: RNASE13, dtype: int64

RNASE1
False    183
Name: RNASE1, dtype: int64

RNASE2
False    183
Name: RNASE2, dtype: int64

RNASE3
False    158
True      25
Name: RNASE3, dtype: int64

RNASE4
False    183
Name: RNASE4, dtype: int64

RNASE6
False    183
Name: RNASE6, dtype: int64

RNASE7
False    174
True       9
Name: RNASE7, dtype: int64

RNASEH1
False    183
Name: RNASEH1, dtype: int64

RNASEH2A
False    183
Name: RNASEH2A, dtype: int64

RNASEH2B
False    183
Name: RNASEH2B, dtype: int64

RNASEH2C
False    183
Name: RNASEH2C, dtype: int64

RNASEK
False    183
Name: RNASEK, dtype: int64

RNASEL
False    183
Name: RNASEL, dtype: int64

RNASEN
False    183
Name: RNASEN, dtype: int64

RNASET2
False    183
Name: RNASET2, dtype: int64

RND1
False    183
Name: RND1, dtype: int64

RND2
False    183
Name: RND2, dtype: int64

RND3
False    183
Name: RND3, dtype: int64

RNF103
False    183
Name: RNF103, dtype: int64

RNF10
False    183
Name: RNF10, dtype: int64

RNF111
False    183
Name: RNF111, dtype: int64

RNF112
False    183
Name: RNF112, dtype: int64

RNF113A
False    183
Name: RNF113A, dtype: int64

RNF114
False    183
Name: RNF114, dtype: int64

RNF115
False    183
Name: RNF115, dtype: int64

RNF11
False    183
Name: RNF11, dtype: int64

RNF121
False    183
Name: RNF121, dtype: int64

RNF122
False    183
Name: RNF122, dtype: int64

RNF123
False    183
Name: RNF123, dtype: int64

RNF125
False    183
Name: RNF125, dtype: int64

RNF126P1
False    154
True      29
Name: RNF126P1, dtype: int64

RNF126
False    183
Name: RNF126, dtype: int64

RNF128
False    183
Name: RNF128, dtype: int64

RNF130
False    183
Name: RNF130, dtype: int64

RNF133
False    143
True      40
Name: RNF133, dtype: int64

RNF135
False    183
Name: RNF135, dtype: int64

RNF138P1
False    182
True       1
Name: RNF138P1, dtype: int64

RNF138
False    183
Name: RNF138, dtype: int64

RNF139
False    183
Name: RNF139, dtype: int64

RNF13
False    183
Name: RNF13, dtype: int64

RNF141
False    183
Name: RNF141, dtype: int64

RNF144A
False    183
Name: RNF144A, dtype: int64

RNF144B
False    183
Name: RNF144B, dtype: int64

RNF145
False    183
Name: RNF145, dtype: int64

RNF146
False    183
Name: RNF146, dtype: int64

RNF148
False    166
True      17
Name: RNF148, dtype: int64

RNF149

False    183
Name: RNF149, dtype: int64

RNF14
False    183
Name: RNF14, dtype: int64

RNF150
False    182
True       1
Name: RNF150, dtype: int64

RNF152
False    183
Name: RNF152, dtype: int64

RNF157
False    183
Name: RNF157, dtype: int64

RNF160
False    183
Name: RNF160, dtype: int64

RNF165
False    181
True       2
Name: RNF165, dtype: int64

RNF166
False    183
Name: RNF166, dtype: int64

RNF167
False    183
Name: RNF167, dtype: int64

RNF168
False    183
Name: RNF168, dtype: int64

RNF169
False    183
Name: RNF169, dtype: int64

RNF170
False    183
Name: RNF170, dtype: int64

RNF175
False    182
True       1
Name: RNF175, dtype: int64

RNF180
False    183
Name: RNF180, dtype: int64

RNF181
False    183
Name: RNF181, dtype: int64

RNF182
False    182
True       1
Name: RNF182, dtype: int64

RNF183
False    183
Name: RNF183, dtype: int64

RNF185
False    183
Name: RNF185, dtype: int64

RNF186
False    181
True       2
Name: RNF186, dtype: int64

RNF187
False    183
Name: RNF187, dtype: int64

RNF19A
False    183
Name: RNF19A, dtype: int64

RNF19B
False    183
Name: RNF19B, dtype: int64

RNF207
False    183
Name: RNF207, dtype: int64

RNF208
False    183
Name: RNF208, dtype: int64

RNF20
False    183
Name: RNF20, dtype: int64

RNF212
False    183
Name: RNF212, dtype: int64

RNF213
False    183
Name: RNF213, dtype: int64

RNF214
False    183
Name: RNF214, dtype: int64

RNF215
False    183
Name: RNF215, dtype: int64

RNF216L
False    183
Name: RNF216L, dtype: int64

RNF216
False    183
Name: RNF216, dtype: int64

RNF217
False    182
True       1
Name: RNF217, dtype: int64

RNF219
False    183
Name: RNF219, dtype: int64

RNF220
False    183
Name: RNF220, dtype: int64

RNF222
False    128
True      55
Name: RNF222, dtype: int64

RNF24
False    183
Name: RNF24, dtype: int64

RNF25
False    183
Name: RNF25, dtype: int64

RNF26
False    183
Name: RNF26, dtype: int64

RNF2
False    183
Name: RNF2, dtype: int64

RNF31
False    183
Name: RNF31, dtype: int64

RNF32
False    183
Name: RNF32, dtype: int64

RNF34
False    183
Name: RNF34, dtype: int64

RNF38
False    183
Name: RNF38, dtype: int64

RNF39
False    183
Name: RNF39, dtype: int64

RNF40
False    183
Name: RNF40, dtype: int64

RNF41
False    183
Name: RNF41, dtype: int64

RNF43
False    183
Name: RNF43, dtype: int64

RNF44
False    183
Name: RNF44, dtype: int64

RNF4
False    183
Name: RNF4, dtype: int64

RNF5P1
False    183
Name: RNF5P1, dtype: int64

RNF5
False    183
Name: RNF5, dtype: int64

RNF6
False    183
Name: RNF6, dtype: int64

RNF7
False    183
Name: RNF7, dtype: int64

RNF8
False    183
Name: RNF8, dtype: int64

RNFT1
False    183
Name: RNFT1, dtype: int64

RNFT2
False    183
Name: RNFT2, dtype: int64

RNGTT
False    183
Name: RNGTT, dtype: int64

RNH1
False    183
Name: RNH1, dtype: int64

RNLS
False    183
Name: RNLS, dtype: int64

RNMTL1
False    183
Name: RNMTL1, dtype: int64

RNMT
False    183
Name: RNMT, dtype: int64

RNPC3
False    183
Name: RNPC3, dtype: int64

RNPEPL1
False    183
Name: RNPEPL1, dtype: int64

RNPEP
False    183
Name: RNPEP, dtype: int64

RNPS1
False    183
Name: RNPS1, dtype: int64

ROBLD3
False    183
Name: ROBLD3, dtype: int64

ROBO1
False    183
Name: ROBO1, dtype: int64

ROBO2
False    182
True       1
Name: ROBO2, dtype: int64

ROBO3
False    183
Name: ROBO3, dtype: int64

ROBO4
False    183
Name: ROBO4, dtype: int64

ROCK1
False    183
Name: ROCK1, dtype: int64

ROCK2
False    183
Name: ROCK2, dtype: int64

ROD1
False    183
Name: ROD1, dtype: int64

ROGDI
False    183
Name: ROGDI, dtype: int64

ROM1
False    183
Name: ROM1, dtype: int64

ROMO1
False    183
Name: ROMO1, dtype: int64

ROPN1B
False    153
True      30
Name: ROPN1B, dtype: int64

ROPN1L
False    177
True       6
Name: ROPN1L, dtype: int64

ROPN1
False    143
True      40
Name: ROPN1, dtype: int64

ROR1
False    182
True       1
Name: ROR1, dtype: int64

ROR2
False    183
Name: ROR2, dtype: int64

RORA
False    183
Name: RORA, dtype: int64

RORB
False    181
True       2
Name: RORB, dtype: int64

RORC
False    183
Name: RORC, dtype: int64

ROS1
False    163
True      20
Name: ROS1, dtype: int64

RP1-177G6.2
True     115
False     68
Name: RP1-177G6.2, dtype: int64

RP1L1
False    181
True       2
Name: RP1L1, dtype: int64

RP1
False    166
True      17
Name: RP1, dtype: int64

RP2
False    183
Name: RP2, dtype: int64

RP9P
False    183
Name: RP9P, dtype: int64

RP9
False    183
Name: RP9, dtype: int64

RPA1
False    183
Name: RPA1, dtype: int64

RPA2
False    183
Name: RPA2, dtype: int64

RPA3
False    183
Name: RPA3, dtype: int64

RPA4
False    157
True      26
Name: RPA4, dtype: int64

RPAIN
False    183
Name: RPAIN, dtype: int64

RPAP1
False    183
Name: RPAP1, dtype: int64

RPAP2
False    183
Name: RPAP2, dtype: int64

RPAP3
False    183
Name: RPAP3, dtype: int64

RPE65
False    99
True     84
Name: RPE65, dtype: int64

RPE
False    183
Name: RPE, dtype: int64

RPF1
False    183
Name: RPF1, dtype: int64

RPF2
False    183
Name: RPF2, dtype: int64

RPGRIP1L
False    183
Name: RPGRIP1L, dtype: int64

RPGRIP1
False    181
True       2
Name: RPGRIP1, dtype: int64

RPGR
False    183
Name: RPGR, dtype: int64

RPH3AL
False    183
Name: RPH3AL, dtype: int64

RPH3A
False    161
True      22
Name: RPH3A, dtype: int64

RPIA
False    183
Name: RPIA, dtype: int64

RPL10A
False    183
Name: RPL10A, dtype: int64

RPL10
False    183
Name: RPL10, dtype: int64

RPL11
False    183
Name: RPL11, dtype: int64

RPL12
False    183
Name: RPL12, dtype: int64

RPL13AP17
True     118
False     65
Name: RPL13AP17, dtype: int64

RPL13AP20
False    183
Name: RPL13AP20, dtype: int64

RPL13AP3
False    183
Name: RPL13AP3, dtype: int64

RPL13AP6
False    183
Name: RPL13AP6, dtype: int64

RPL13A
False    183
Name: RPL13A, dtype: int64

RPL13P5
False    183
Name: RPL13P5, dtype: int64

RPL13
False    183
Name: RPL13, dtype: int64

RPL14
False    183
Name: RPL14, dtype: int64

RPL15
False    183
Name: RPL15, dtype: int64

RPL17
False    183
Name: RPL17, dtype: int64

RPL18A
False    183
Name: RPL18A, dtype: int64

RPL18
False    183
Name: RPL18, dtype: int64

RPL19P12
False    183
Name: RPL19P12, dtype: int64

RPL19
False    183
Name: RPL19, dtype: int64

RPL21P44
False    175
True       8
Name: RPL21P44, dtype: int64

RPL21
False    176
True       7
Name: RPL21, dtype: int64

RPL22L1
False    183
Name: RPL22L1, dtype: int64

RPL22
False    183
Name: RPL22, dtype: int64

RPL23AP32
False    124
True      59
Name: RPL23AP32, dtype: int64

RPL23AP53
False    183
Name: RPL23AP53, dtype: int64

RPL23AP64
False    178
True       5
Name: RPL23AP64, dtype: int64

RPL23AP7
False    183
Name: RPL23AP7, dtype: int64

RPL23AP82
False    183
Name: RPL23AP82, dtype: int64

RPL23A
False    183
Name: RPL23A, dtype: int64

RPL23P8
False    183
Name: RPL23P8, dtype: int64

RPL23
False    183
Name: RPL23, dtype: int64

RPL24
False    183
Name: RPL24, dtype: int64

RPL26L1
False    183
Name: RPL26L1, dtype: int64

RPL26
False    183
Name: RPL26, dtype: int64

RPL27A
False    183
Name: RPL27A, dtype: int64

RPL27
False    183
Name: RPL27, dtype: int64

RPL28
False    183
Name: RPL28, dtype: int64

RPL29P2
True     108
False     75
Name: RPL29P2, dtype: int64

RPL29
False    183
Name: RPL29, dtype: int64

RPL30
False    183
Name: RPL30, dtype: int64

RPL31P11
False    180
True       3
Name: RPL31P11, dtype: int64

RPL31
False    183
Name: RPL31, dtype: int64

RPL32P3
False    183
Name: RPL32P3, dtype: int64

RPL32
False    183
Name: RPL32, dtype: int64

RPL34
False    183
Name: RPL34, dtype: int64

RPL35A
False    183
Name: RPL35A, dtype: int64

RPL35
False    183
Name: RPL35, dtype: int64

RPL36AL
False    183
Name: RPL36AL, dtype: int64

RPL36A
False    183
Name: RPL36A, dtype: int64

RPL36
False    183
Name: RPL36, dtype: int64

RPL37A
False    183
Name: RPL37A, dtype: int64

RPL37
False    183
Name: RPL37, dtype: int64

RPL38
False    183
Name: RPL38, dtype: int64

RPL39L
False    183
Name: RPL39L, dtype: int64

RPL39
False    183
Name: RPL39, dtype: int64

RPL3L
True     116
False     67
Name: RPL3L, dtype: int64

RPL3
False    183
Name: RPL3, dtype: int64

RPL41
False    183
Name: RPL41, dtype: int64

RPL4
False    183
Name: RPL4, dtype: int64

RPL5
False    183
Name: RPL5, dtype: int64

RPL6

False    183
Name: RPL6, dtype: int64

RPL7A
False    183
Name: RPL7A, dtype: int64

RPL7L1
False    183
Name: RPL7L1, dtype: int64

RPL7
False    183
Name: RPL7, dtype: int64

RPL8
False    183
Name: RPL8, dtype: int64

RPL9
False    183
Name: RPL9, dtype: int64

RPLP0P2
False    183
Name: RPLP0P2, dtype: int64

RPLP0
False    183
Name: RPLP0, dtype: int64

RPLP1
False    183
Name: RPLP1, dtype: int64

RPLP2
False    183
Name: RPLP2, dtype: int64

RPN1
False    183
Name: RPN1, dtype: int64

RPN2
False    183
Name: RPN2, dtype: int64

RPP14
False    183
Name: RPP14, dtype: int64

RPP21
False    183
Name: RPP21, dtype: int64

RPP25
False    183
Name: RPP25, dtype: int64

RPP30
False    183
Name: RPP30, dtype: int64

RPP38
False    183
Name: RPP38, dtype: int64

RPP40
False    183
Name: RPP40, dtype: int64

RPPH1
False    183
Name: RPPH1, dtype: int64

RPRD1A
False    183
Name: RPRD1A, dtype: int64

RPRD1B
False    183
Name: RPRD1B, dtype: int64

RPRD2
False    183
Name: RPRD2, dtype: int64

RPRML
False    105
True      78
Name: RPRML, dtype: int64

RPRM
False    162
True      21
Name: RPRM, dtype: int64

RPS10P7
False    183
Name: RPS10P7, dtype: int64

RPS10
False    183
Name: RPS10, dtype: int64

RPS11
False    183
Name: RPS11, dtype: int64

RPS12
False    183
Name: RPS12, dtype: int64

RPS13
False    183
Name: RPS13, dtype: int64

RPS14
False    183
Name: RPS14, dtype: int64

RPS15AP10
False    175
True       8
Name: RPS15AP10, dtype: int64

RPS15A
False    183
Name: RPS15A, dtype: int64

RPS15
False    183
Name: RPS15, dtype: int64

RPS16
False    183
Name: RPS16, dtype: int64

RPS17
False    183
Name: RPS17, dtype: int64

RPS18
False    183
Name: RPS18, dtype: int64

RPS19BP1
False    183
Name: RPS19BP1, dtype: int64

RPS19
False    183
Name: RPS19, dtype: int64

RPS20
False    183
Name: RPS20, dtype: int64

RPS21
False    183
Name: RPS21, dtype: int64

RPS23
False    183
Name: RPS23, dtype: int64

RPS24
False    183
Name: RPS24, dtype: int64

RPS25
False    183
Name: RPS25, dtype: int64

RPS26P11
False    142
True      41
Name: RPS26P11, dtype: int64

RPS26
False    183
Name: RPS26, dtype: int64

RPS27A
False    183
Name: RPS27A, dtype: int64

RPS27L
False    183
Name: RPS27L, dtype: int64

RPS27
False    183
Name: RPS27, dtype: int64

RPS28
False    183
Name: RPS28, dtype: int64

RPS29
False    183
Name: RPS29, dtype: int64

RPS2P32
False    183
Name: RPS2P32, dtype: int64

RPS2
False    183
Name: RPS2, dtype: int64

RPS3A
False    183
Name: RPS3A, dtype: int64

RPS3
False    183
Name: RPS3, dtype: int64

RPS4X
False    183
Name: RPS4X, dtype: int64

RPS4Y1
False    159
True      24
Name: RPS4Y1, dtype: int64

RPS5
False    183
Name: RPS5, dtype: int64

RPS6KA1
False    183
Name: RPS6KA1, dtype: int64

RPS6KA2
False    183
Name: RPS6KA2, dtype: int64

RPS6KA3
False    183
Name: RPS6KA3, dtype: int64

RPS6KA4
False    183
Name: RPS6KA4, dtype: int64

RPS6KA5
False    183
Name: RPS6KA5, dtype: int64

RPS6KA6
False    177
True       6
Name: RPS6KA6, dtype: int64

RPS6KB1
False    183
Name: RPS6KB1, dtype: int64

RPS6KB2
False    183
Name: RPS6KB2, dtype: int64

RPS6KC1
False    183
Name: RPS6KC1, dtype: int64

RPS6KL1
False    183
Name: RPS6KL1, dtype: int64

RPS6
False    183
Name: RPS6, dtype: int64

RPS7
False    183
Name: RPS7, dtype: int64

RPS8
False    183
Name: RPS8, dtype: int64

RPS9
False    183
Name: RPS9, dtype: int64

RPSAP52
False    178
True       5
Name: RPSAP52, dtype: int64

RPSAP58
False    183
Name: RPSAP58, dtype: int64

RPSAP9
False    183
Name: RPSAP9, dtype: int64

RPSA
False    183
Name: RPSA, dtype: int64

RPTN
False    97
True     86
Name: RPTN, dtype: int64

RPTOR
False    183
Name: RPTOR, dtype: int64

RPUSD1
False    183
Name: RPUSD1, dtype: int64

RPUSD2
False    183
Name: RPUSD2, dtype: int64

RPUSD3
False    183
Name: RPUSD3, dtype: int64

RPUSD4
False    183
Name: RPUSD4, dtype: int64

RQCD1
False    183
Name: RQCD1, dtype: int64

RRAD
False    183
Name: RRAD, dtype: int64

RRAGA
False    183
Name: RRAGA, dtype: int64

RRAGB
False    183
Name: RRAGB, dtype: int64

RRAGC
False    183
Name: RRAGC, dtype: int64

RRAGD
False    183
Name: RRAGD, dtype: int64

RRAS2
False    183
Name: RRAS2, dtype: int64

RRAS
False    183
Name: RRAS, dtype: int64

RRBP1
False    183
Name: RRBP1, dtype: int64

RREB1
False    183
Name: RREB1, dtype: int64

RRH
False    165
True      18
Name: RRH, dtype: int64

RRM1
False    183
Name: RRM1, dtype: int64

RRM2B
False    183
Name: RRM2B, dtype: int64

RRM2
False    183
Name: RRM2, dtype: int64

RRN3P1
False    183
Name: RRN3P1, dtype: int64

RRN3P2
False    183
Name: RRN3P2, dtype: int64

RRN3P3
False    183
Name: RRN3P3, dtype: int64

RRN3
False    183
Name: RRN3, dtype: int64

RRP12
False    183
Name: RRP12, dtype: int64

RRP15
False    183
Name: RRP15, dtype: int64

RRP1B
False    183
Name: RRP1B, dtype: int64

RRP1
False    183
Name: RRP1, dtype: int64

RRP7A
False    183
Name: RRP7A, dtype: int64

RRP7B
False    183
Name: RRP7B, dtype: int64

RRP8
False    183
Name: RRP8, dtype: int64

RRP9
False    183
Name: RRP9, dtype: int64

RRS1
False    183
Name: RRS1, dtype: int64

RS1
False    174
True       9
Name: RS1, dtype: int64

RSAD1
False    183
Name: RSAD1, dtype: int64

RSAD2
False    183
Name: RSAD2, dtype: int64

RSBN1L
False    183
Name: RSBN1L, dtype: int64

RSBN1
False    183
Name: RSBN1, dtype: int64

RSC1A1
False    183
Name: RSC1A1, dtype: int64

RSF1
False    183
Name: RSF1, dtype: int64

RSL1D1
False    183
Name: RSL1D1, dtype: int64

RSL24D1
False    183
Name: RSL24D1, dtype: int64

RSPH10B2
False    173
True      10
Name: RSPH10B2, dtype: int64

RSPH1
False    182
True       1
Name: RSPH1, dtype: int64

RSPH3
False    183
Name: RSPH3, dtype: int64

RSPH4A
False    181
True       2
Name: RSPH4A, dtype: int64

RSPH6A
True     126
False     57
Name: RSPH6A, dtype: int64

RSPH9
False    182
True       1
Name: RSPH9, dtype: int64

RSPO1
False    178
True       5
Name: RSPO1, dtype: int64

RSPO2
False    167
True      16
Name: RSPO2, dtype: int64

RSPO3
False    183
Name: RSPO3, dtype: int64

RSPO4
False    177
True       6
Name: RSPO4, dtype: int64

RSPRY1
False    183
Name: RSPRY1, dtype: int64

RSRC1
False    183
Name: RSRC1, dtype: int64

RSRC2
False    183
Name: RSRC2, dtype: int64

RSU1
False    183
Name: RSU1, dtype: int64

RTBDN
False    173
True      10
Name: RTBDN, dtype: int64

RTCD1
False    183
Name: RTCD1, dtype: int64

RTDR1
False    183
Name: RTDR1, dtype: int64

RTEL1
False    183
Name: RTEL1, dtype: int64

RTF1
False    183
Name: RTF1, dtype: int64

RTKN2
False    183
Name: RTKN2, dtype: int64

RTKN
False    183
Name: RTKN, dtype: int64

RTL1
False    143
True      40
Name: RTL1, dtype: int64

RTN1
False    183
Name: RTN1, dtype: int64

RTN2
False    183
Name: RTN2, dtype: int64

RTN3
False    183
Name: RTN3, dtype: int64

RTN4IP1
False    183
Name: RTN4IP1, dtype: int64

RTN4RL1
False    183
Name: RTN4RL1, dtype: int64

RTN4RL2
False    183
Name: RTN4RL2, dtype: int64

RTN4R
False    183
Name: RTN4R, dtype: int64

RTN4
False    183
Name: RTN4, dtype: int64

RTP1
True     120
False     63
Name: RTP1, dtype: int64

RTP2
True     92
False    91
Name: RTP2, dtype: int64

RTP4
False    183
Name: RTP4, dtype: int64

RTTN
False    183
Name: RTTN, dtype: int64

RUFY1
False    183
Name: RUFY1, dtype: int64

RUFY2
False    183
Name: RUFY2, dtype: int64

RUFY3
False    183
Name: RUFY3, dtype: int64

RUFY4
False    181
True       2
Name: RUFY4, dtype: int64

RUNDC1
False    183
Name: RUNDC1, dtype: int64

RUNDC2A
False    183
Name: RUNDC2A, dtype: int64

RUNDC2C
False    183
Name: RUNDC2C, dtype: int64

RUNDC3A
False    183
Name: RUNDC3A, dtype: int64

RUNDC3B
False    183
Name: RUNDC3B, dtype: int64

RUNX1T1
False    182
True       1
Name: RUNX1T1, dtype: int64

RUNX1
False    183
Name: RUNX1, dtype: int64

RUNX2
False    183
Name: RUNX2, dtype: int64

RUNX3
False    183
Name: RUNX3, dtype: int64

RUSC1
False    183
Name: RUSC1, dtype: int64

RUSC2
False    183
Name: RUSC2, dtype: int64

RUVBL1
False    183
Name: RUVBL1, dtype: int64

RUVBL2
False    183
Name: RUVBL2, dtype: int64

RWDD1
False    183
Name: RWDD1, dtype: int64

RWDD2A
False    183
Name: RWDD2A, dtype: int64

RWDD2B
False    183
Name: RWDD2B, dtype: int64

RWDD3
False    183
Name: RWDD3, dtype: int64

RWDD4A
False    183
Name: RWDD4A, dtype: int64

RXFP1
False    173
True      10
Name: RXFP1, dtype: int64

RXFP3
False    136
True      47
Name: RXFP3, dtype: int64

RXFP4
False    174
True       9
Name: RXFP4, dtype: int64

RXRA
False    183
Name: RXRA, dtype: int64

RXRB

False    183
Name: RXRB, dtype: int64

RXRG
False    171
True      12
Name: RXRG, dtype: int64

RYBP
False    183
Name: RYBP, dtype: int64

RYK
False    183
Name: RYK, dtype: int64

RYR1
False    183
Name: RYR1, dtype: int64

RYR2
False    183
Name: RYR2, dtype: int64

RYR3
False    182
True       1
Name: RYR3, dtype: int64

S100A10
False    183
Name: S100A10, dtype: int64

S100A11
False    183
Name: S100A11, dtype: int64

S100A12
False    168
True      15
Name: S100A12, dtype: int64

S100A13
False    183
Name: S100A13, dtype: int64

S100A14
False    181
True       2
Name: S100A14, dtype: int64

S100A16
False    183
Name: S100A16, dtype: int64

S100A1
False    183
Name: S100A1, dtype: int64

S100A2
False    182
True       1
Name: S100A2, dtype: int64

S100A3
False    183
Name: S100A3, dtype: int64

S100A4
False    183
Name: S100A4, dtype: int64

S100A5
False    178
True       5
Name: S100A5, dtype: int64

S100A6
False    183
Name: S100A6, dtype: int64

S100A7
True     110
False     73
Name: S100A7, dtype: int64

S100A8
False    183
Name: S100A8, dtype: int64

S100A9
False    183
Name: S100A9, dtype: int64

S100B
False    183
Name: S100B, dtype: int64

S100PBP
False    183
Name: S100PBP, dtype: int64

S100P
False    182
True       1
Name: S100P, dtype: int64

S100Z
False    172
True      11
Name: S100Z, dtype: int64

S1PR1
False    183
Name: S1PR1, dtype: int64

S1PR2
False    183
Name: S1PR2, dtype: int64

S1PR3
False    183
Name: S1PR3, dtype: int64

S1PR4
False    183
Name: S1PR4, dtype: int64

S1PR5
False    183
Name: S1PR5, dtype: int64

SAA1
False    181
True       2
Name: SAA1, dtype: int64

SAA2
False    179
True       4
Name: SAA2, dtype: int64

SAA4
False    174
True       9
Name: SAA4, dtype: int64

SAAL1
False    183
Name: SAAL1, dtype: int64

SAC3D1
False    183
Name: SAC3D1, dtype: int64

SACM1L
False    183
Name: SACM1L, dtype: int64

SACS
False    183
Name: SACS, dtype: int64

SAE1
False    183
Name: SAE1, dtype: int64

SAFB2
False    183
Name: SAFB2, dtype: int64

SAFB
False    183
Name: SAFB, dtype: int64

SAGE1
False    94
True     89
Name: SAGE1, dtype: int64

SALL1
False    181
True       2
Name: SALL1, dtype: int64

SALL2
False    183
Name: SALL2, dtype: int64

SALL4
False    183
Name: SALL4, dtype: int64

SAMD10
False    183
Name: SAMD10, dtype: int64

SAMD11
False    183
Name: SAMD11, dtype: int64

SAMD12
False    183
Name: SAMD12, dtype: int64

SAMD13
False    183
Name: SAMD13, dtype: int64

SAMD14
False    183
Name: SAMD14, dtype: int64

SAMD1
False    183
Name: SAMD1, dtype: int64

SAMD3
False    183
Name: SAMD3, dtype: int64

SAMD4A
False    183
Name: SAMD4A, dtype: int64

SAMD4B
False    183
Name: SAMD4B, dtype: int64

SAMD5
False    183
Name: SAMD5, dtype: int64

SAMD8
False    183
Name: SAMD8, dtype: int64

SAMD9L
False    183
Name: SAMD9L, dtype: int64

SAMD9
False    183
Name: SAMD9, dtype: int64

SAMHD1
False    183
Name: SAMHD1, dtype: int64

SAMM50
False    183
Name: SAMM50, dtype: int64

SAMSN1
False    183
Name: SAMSN1, dtype: int64

SAP130
False    183
Name: SAP130, dtype: int64

SAP18
False    183
Name: SAP18, dtype: int64

SAP30BP
False    183
Name: SAP30BP, dtype: int64

SAP30L
False    183
Name: SAP30L, dtype: int64

SAP30
False    183
Name: SAP30, dtype: int64

SAPS1
False    183
Name: SAPS1, dtype: int64

SAPS2
False    183
Name: SAPS2, dtype: int64

SAPS3
False    183
Name: SAPS3, dtype: int64

SAR1A
False    183
Name: SAR1A, dtype: int64

SAR1B
False    183
Name: SAR1B, dtype: int64

SARDH
False    183
Name: SARDH, dtype: int64

SARM1
False    183
Name: SARM1, dtype: int64

SARNP
False    183
Name: SARNP, dtype: int64

SARS2
False    183
Name: SARS2, dtype: int64

SARS
False    183
Name: SARS, dtype: int64

SART1
False    183
Name: SART1, dtype: int64

SART3
False    183
Name: SART3, dtype: int64

SASH1
False    183
Name: SASH1, dtype: int64

SASH3
False    183
Name: SASH3, dtype: int64

SASS6
False    183
Name: SASS6, dtype: int64

SAT1
False    183
Name: SAT1, dtype: int64

SAT2
False    183
Name: SAT2, dtype: int64

SATB1
False    183
Name: SATB1, dtype: int64

SATB2
False    183
Name: SATB2, dtype: int64

SATL1
False    182
True       1
Name: SATL1, dtype: int64

SAV1
False    183
Name: SAV1, dtype: int64

SBDSP1
False    183
Name: SBDSP1, dtype: int64

SBDS
False    183
Name: SBDS, dtype: int64

SBF1P1
False    137
True      46
Name: SBF1P1, dtype: int64

SBF1
False    183
Name: SBF1, dtype: int64

SBF2
False    183
Name: SBF2, dtype: int64

SBK1
False    183
Name: SBK1, dtype: int64

SBK2
False    123
True      60
Name: SBK2, dtype: int64

SBNO1
False    183
Name: SBNO1, dtype: int64

SBNO2
False    183
Name: SBNO2, dtype: int64

SBSN
False    154
True      29
Name: SBSN, dtype: int64

SC4MOL
False    183
Name: SC4MOL, dtype: int64

SC5DL
False    183
Name: SC5DL, dtype: int64

SC65
False    183
Name: SC65, dtype: int64

SCAF1
False    183
Name: SCAF1, dtype: int64

SCAI
False    183
Name: SCAI, dtype: int64

SCAMP1
False    183
Name: SCAMP1, dtype: int64

SCAMP2
False    183
Name: SCAMP2, dtype: int64

SCAMP3
False    183
Name: SCAMP3, dtype: int64

SCAMP4
False    183
Name: SCAMP4, dtype: int64

SCAMP5
False    183
Name: SCAMP5, dtype: int64

SCAND1
False    183
Name: SCAND1, dtype: int64

SCAND2
False    183
Name: SCAND2, dtype: int64

SCAND3
False    180
True       3
Name: SCAND3, dtype: int64

SCAPER
False    183
Name: SCAPER, dtype: int64

SCAP
False    183
Name: SCAP, dtype: int64

SCARA3
False    183
Name: SCARA3, dtype: int64

SCARA5
False    177
True       6
Name: SCARA5, dtype: int64

SCARB1
False    183
Name: SCARB1, dtype: int64

SCARB2
False    183
Name: SCARB2, dtype: int64

SCARF1
False    183
Name: SCARF1, dtype: int64

SCARF2
False    183
Name: SCARF2, dtype: int64

SCARNA10
False    154
True      29
Name: SCARNA10, dtype: int64

SCARNA12
False    180
True       3
Name: SCARNA12, dtype: int64

SCARNA16
False    140
True      43
Name: SCARNA16, dtype: int64

SCARNA17
False    181
True       2
Name: SCARNA17, dtype: int64

SCARNA2
False    181
True       2
Name: SCARNA2, dtype: int64

SCARNA5
False    118
True      65
Name: SCARNA5, dtype: int64

SCARNA6
False    123
True      60
Name: SCARNA6, dtype: int64

SCARNA7
False    170
True      13
Name: SCARNA7, dtype: int64

SCARNA9L
True     125
False     58
Name: SCARNA9L, dtype: int64

SCARNA9
False    181
True       2
Name: SCARNA9, dtype: int64

SCCPDH
False    183
Name: SCCPDH, dtype: int64

SCD5
False    183
Name: SCD5, dtype: int64

SCD
False    183
Name: SCD, dtype: int64

SCEL
False    178
True       5
Name: SCEL, dtype: int64

SCFD1
False    183
Name: SCFD1, dtype: int64

SCFD2
False    183
Name: SCFD2, dtype: int64

SCG2
False    183
Name: SCG2, dtype: int64

SCG3
False    181
True       2
Name: SCG3, dtype: int64

SCG5
False    183
Name: SCG5, dtype: int64

SCGB1A1
True     125
False     58
Name: SCGB1A1, dtype: int64

SCGB1D2
False    92
True     91
Name: SCGB1D2, dtype: int64

SCGB2A1
False    179
True       4
Name: SCGB2A1, dtype: int64

SCGB3A1
False    176
True       7
Name: SCGB3A1, dtype: int64

SCGB3A2
True     121
False     62
Name: SCGB3A2, dtype: int64

SCGBL
False    92
True     91
Name: SCGBL, dtype: int64

SCGN
False    178
True       5
Name: SCGN, dtype: int64

SCHIP1
False    183
Name: SCHIP1, dtype: int64

SCIN
False    183
Name: SCIN, dtype: int64

SCLT1
False    183
Name: SCLT1, dtype: int64

SCLY
False    183
Name: SCLY, dtype: int64

SCMH1
False    183
Name: SCMH1, dtype: int64

SCML1
False    183
Name: SCML1, dtype: int64

SCML2
False    182
True       1
Name: SCML2, dtype: int64

SCML4
False    183
Name: SCML4, dtype: int64

SCN10A
True     114
False     69
Name: SCN10A, dtype: int64

SCN11A
False    181
True       2
Name: SCN11A, dtype: int64

SCN1A
False    97
True     86
Name: SCN1A, dtype: int64

SCN1B
False    183
Name: SCN1B, dtype: int64

SCN2A
False    182
True       1
Name: SCN2A, dtype: int64

SCN2B
False    182
True       1
Name: SCN2B, dtype: int64

SCN3A
False    182
True       1
Name: SCN3A, dtype: int64

SCN3B
False    183
Name: SCN3B, dtype: int64

SCN4A
False    176
True       7
Name: SCN4A, dtype: int64

SCN4B
False    183
Name: SCN4B, dtype: int64

SCN5A
False    182
True       1
Name: SCN5A, dtype: int64

SCN7A
False    181
True       2
Name: SCN7A, dtype: int64

SCN8A
False    183
Name: SCN8A, dtype: int64

SCN9A
False    183
Name: SCN9A, dtype: int64

SCNM1
False    183
Name: SCNM1, dtype: int64

SCNN1A
False    183
Name: SCNN1A, dtype: int64

SCNN1B
False    181
True       2
Name: SCNN1B, dtype: int64

SCNN1D
False    183
Name: SCNN1D, dtype: int64

SCNN1G
False    175
True       8
Name: SCNN1G, dtype: int64

SCO1
False    183
Name: SCO1, dtype: int64

SCO2
False    183
Name: SCO2, dtype: int64

SCOC
False    183
Name: SCOC, dtype: int64

SCP2
False    183
Name: SCP2, dtype: int64

SCPEP1
False    183
Name: SCPEP1, dtype: int64

SCRG1

False    181
True       2
Name: SCRG1, dtype: int64

SCRIB
False    183
Name: SCRIB, dtype: int64

SCRN1
False    183
Name: SCRN1, dtype: int64

SCRN2
False    183
Name: SCRN2, dtype: int64

SCRN3
False    183
Name: SCRN3, dtype: int64

SCRT1
False    165
True      18
Name: SCRT1, dtype: int64

SCRT2
False    130
True      53
Name: SCRT2, dtype: int64

SCTR
False    178
True       5
Name: SCTR, dtype: int64

SCT
False    182
True       1
Name: SCT, dtype: int64

SCUBE1
False    183
Name: SCUBE1, dtype: int64

SCUBE2
False    183
Name: SCUBE2, dtype: int64

SCUBE3
False    183
Name: SCUBE3, dtype: int64

SCXB
False    170
True      13
Name: SCXB, dtype: int64

SCYL1
False    183
Name: SCYL1, dtype: int64

SCYL2
False    183
Name: SCYL2, dtype: int64

SCYL3
False    183
Name: SCYL3, dtype: int64

SDAD1
False    183
Name: SDAD1, dtype: int64

SDC1
False    183
Name: SDC1, dtype: int64

SDC2
False    183
Name: SDC2, dtype: int64

SDC3
False    183
Name: SDC3, dtype: int64

SDC4
False    183
Name: SDC4, dtype: int64

SDCBP2
False    183
Name: SDCBP2, dtype: int64

SDCBP
False    183
Name: SDCBP, dtype: int64

SDCCAG1
False    183
Name: SDCCAG1, dtype: int64

SDCCAG3
False    183
Name: SDCCAG3, dtype: int64

SDCCAG8
False    183
Name: SDCCAG8, dtype: int64

SDF2L1
False    183
Name: SDF2L1, dtype: int64

SDF2
False    183
Name: SDF2, dtype: int64

SDF4
False    183
Name: SDF4, dtype: int64

SDHAF1
False    183
Name: SDHAF1, dtype: int64

SDHAF2
False    183
Name: SDHAF2, dtype: int64

SDHAP1
False    183
Name: SDHAP1, dtype: int64

SDHAP2
False    183
Name: SDHAP2, dtype: int64

SDHAP3
False    183
Name: SDHAP3, dtype: int64

SDHA
False    183
Name: SDHA, dtype: int64

SDHB
False    183
Name: SDHB, dtype: int64

SDHC
False    183
Name: SDHC, dtype: int64

SDHD
False    183
Name: SDHD, dtype: int64

SDK1
False    183
Name: SDK1, dtype: int64

SDK2
False    183
Name: SDK2, dtype: int64

SDPR
False    183
Name: SDPR, dtype: int64

SDR16C5
False    180
True       3
Name: SDR16C5, dtype: int64

SDR39U1
False    183
Name: SDR39U1, dtype: int64

SDR42E1
False    182
True       1
Name: SDR42E1, dtype: int64

SDSL
False    183
Name: SDSL, dtype: int64

SDS
False    183
Name: SDS, dtype: int64

SEC11A
False    183
Name: SEC11A, dtype: int64

SEC11C
False    183
Name: SEC11C, dtype: int64

SEC13
False    183
Name: SEC13, dtype: int64

SEC14L1
False    183
Name: SEC14L1, dtype: int64

SEC14L2
False    183
Name: SEC14L2, dtype: int64

SEC14L4
False    179
True       4
Name: SEC14L4, dtype: int64

SEC14L5
False    182
True       1
Name: SEC14L5, dtype: int64

SEC16A
False    183
Name: SEC16A, dtype: int64

SEC16B
False    183
Name: SEC16B, dtype: int64

SEC1
False    183
Name: SEC1, dtype: int64

SEC22A
False    183
Name: SEC22A, dtype: int64

SEC22B
False    183
Name: SEC22B, dtype: int64

SEC22C
False    183
Name: SEC22C, dtype: int64

SEC23A
False    183
Name: SEC23A, dtype: int64

SEC23B
False    183
Name: SEC23B, dtype: int64

SEC23IP
False    183
Name: SEC23IP, dtype: int64

SEC24A
False    183
Name: SEC24A, dtype: int64

SEC24B
False    183
Name: SEC24B, dtype: int64

SEC24C
False    183
Name: SEC24C, dtype: int64

SEC24D
False    183
Name: SEC24D, dtype: int64

SEC31A
False    183
Name: SEC31A, dtype: int64

SEC31B
False    183
Name: SEC31B, dtype: int64

SEC61A1
False    183
Name: SEC61A1, dtype: int64

SEC61A2
False    183
Name: SEC61A2, dtype: int64

SEC61B
False    183
Name: SEC61B, dtype: int64

SEC61G
False    183
Name: SEC61G, dtype: int64

SEC62
False    183
Name: SEC62, dtype: int64

SEC63
False    183
Name: SEC63, dtype: int64

SECISBP2L
False    183
Name: SECISBP2L, dtype: int64

SECISBP2
False    183
Name: SECISBP2, dtype: int64

SECTM1
False    183
Name: SECTM1, dtype: int64

SEH1L
False    183
Name: SEH1L, dtype: int64

SEL1L2
True     117
False     66
Name: SEL1L2, dtype: int64

SEL1L3
False    183
Name: SEL1L3, dtype: int64

SEL1L
False    183
Name: SEL1L, dtype: int64

SELENBP1
False    183
Name: SELENBP1, dtype: int64

SELE
False    183
Name: SELE, dtype: int64

SELK
False    183
Name: SELK, dtype: int64

SELL
False    183
Name: SELL, dtype: int64

SELM
False    183
Name: SELM, dtype: int64

SELO
False    183
Name: SELO, dtype: int64

SELPLG
False    183
Name: SELPLG, dtype: int64

SELP
False    183
Name: SELP, dtype: int64

SELS
False    183
Name: SELS, dtype: int64

SELT
False    183
Name: SELT, dtype: int64

SEMA3A
False    183
Name: SEMA3A, dtype: int64

SEMA3B
False    183
Name: SEMA3B, dtype: int64

SEMA3C
False    183
Name: SEMA3C, dtype: int64

SEMA3D
False    182
True       1
Name: SEMA3D, dtype: int64

SEMA3E
False    182
True       1
Name: SEMA3E, dtype: int64

SEMA3F
False    183
Name: SEMA3F, dtype: int64

SEMA3G
False    183
Name: SEMA3G, dtype: int64

SEMA4A
False    183
Name: SEMA4A, dtype: int64

SEMA4B
False    183
Name: SEMA4B, dtype: int64

SEMA4C
False    183
Name: SEMA4C, dtype: int64

SEMA4D
False    183
Name: SEMA4D, dtype: int64

SEMA4F
False    183
Name: SEMA4F, dtype: int64

SEMA4G
False    183
Name: SEMA4G, dtype: int64

SEMA5A
False    183
Name: SEMA5A, dtype: int64

SEMA5B
False    183
Name: SEMA5B, dtype: int64

SEMA6A
False    183
Name: SEMA6A, dtype: int64

SEMA6B
False    183
Name: SEMA6B, dtype: int64

SEMA6C
False    183
Name: SEMA6C, dtype: int64

SEMA6D
False    183
Name: SEMA6D, dtype: int64

SEMA7A
False    183
Name: SEMA7A, dtype: int64

SEMG1
False    143
True      40
Name: SEMG1, dtype: int64

SENP1
False    183
Name: SENP1, dtype: int64

SENP2
False    183
Name: SENP2, dtype: int64

SENP3
False    183
Name: SENP3, dtype: int64

SENP5
False    183
Name: SENP5, dtype: int64

SENP6
False    183
Name: SENP6, dtype: int64

SENP7
False    183
Name: SENP7, dtype: int64

SENP8
False    183
Name: SENP8, dtype: int64

SEP15
False    183
Name: SEP15, dtype: int64

SEPHS1
False    183
Name: SEPHS1, dtype: int64

SEPHS2
False    183
Name: SEPHS2, dtype: int64

SEPN1
False    183
Name: SEPN1, dtype: int64

SEPP1
False    183
Name: SEPP1, dtype: int64

SEPSECS
False    183
Name: SEPSECS, dtype: int64

SEPT10
False    183
Name: SEPT10, dtype: int64

SEPT11
False    183
Name: SEPT11, dtype: int64

SEPT12
True     107
False     76
Name: SEPT12, dtype: int64

SEPT1
False    183
Name: SEPT1, dtype: int64

SEPT2
False    183
Name: SEPT2, dtype: int64

SEPT3
False    183
Name: SEPT3, dtype: int64

SEPT4
False    183
Name: SEPT4, dtype: int64

SEPT5
False    183
Name: SEPT5, dtype: int64

SEPT6
False    183
Name: SEPT6, dtype: int64

SEPT7L
False    104
True      79
Name: SEPT7L, dtype: int64

SEPT7P2
False    183
Name: SEPT7P2, dtype: int64

SEPT7
False    183
Name: SEPT7, dtype: int64

SEPT8
False    183
Name: SEPT8, dtype: int64

SEPT9
False    183
Name: SEPT9, dtype: int64

SEPW1
False    183
Name: SEPW1, dtype: int64

SEPX1
False    183
Name: SEPX1, dtype: int64

SERAC1
False    183
Name: SERAC1, dtype: int64

SERBP1
False    183
Name: SERBP1, dtype: int64

SERF1A
False    183
Name: SERF1A, dtype: int64

SERF2
False    183
Name: SERF2, dtype: int64

SERGEF
False    183
Name: SERGEF, dtype: int64

SERHL2
False    183
Name: SERHL2, dtype: int64

SERHL
False    183
Name: SERHL, dtype: int64

SERINC1
False    183
Name: SERINC1, dtype: int64

SERINC2
False    183
Name: SERINC2, dtype: int64

SERINC3
False    183
Name: SERINC3, dtype: int64

SERINC4
False    181
True       2
Name: SERINC4, dtype: int64

SERINC5
False    183
Name: SERINC5, dtype: int64

SERP1
False    183
Name: SERP1, dtype: int64

SERP2
False    183
Name: SERP2, dtype: int64

SERPINA10
False    164
True      19
Name: SERPINA10, dtype: int64

SERPINA11
False    151
True      32
Name: SERPINA11, dtype: int64

SERPINA12
True     99
False    84
Name: SERPINA12, dtype: int64

SERPINA1
False    183
Name: SERPINA1, dtype: int64

SERPINA3
False    183
Name: SERPINA3, dtype: int64

SERPINA4
False    180
True       3
Name: SERPINA4, dtype: int64

SERPINA5
False    183
Name: SERPINA5, dtype: int64

SERPINA6
False    180
True       3
Name: SERPINA6, dtype: int64

SERPINA7
False    107
True      76
Name: SERPINA7, dtype: int64

SERPINA9
False    136
True      47
Name: SERPINA9, dtype: int64

SERPINB10
True     123
False     60
Name: SERPINB10, dtype: int64

SERPINB11
True     115
False     68
Name: SERPINB11, dtype: int64

SERPINB13
True     119
False     64
Name: SERPINB13, dtype: int64

SERPINB1
False    183
Name: SERPINB1, dtype: int64

SERPINB2
False    177
True       6
Name: SERPINB2, dtype: int64

SERPINB3
False    169
True      14
Name: SERPINB3, dtype: int64

SERPINB4
False    167
True      16
Name: SERPINB4, dtype: int64

SERPINB5
False    179
True       4
Name: SERPINB5, dtype: int64

SERPINB6
False    183
Name: SERPINB6, dtype: int64

SERPINB7
False    171
True      12
Name: SERPINB7, dtype: int64

SERPINB8
False    183
Name: SERPINB8, dtype: int64

SERPINB9
False    183
Name: SERPINB9, dtype: int64

SERPINC1
False    166
True      17
Name: SERPINC1, dtype: int64

SERPIND1
False    181
True       2
Name: SERPIND1, dtype: int64

SERPINE1
False    183
Name: SERPINE1, dtype: int64

SERPINE2
False    183
Name: SERPINE2, dtype: int64

SERPINE3
True     98
False    85
Name: SERPINE3, dtype: int64

SERPINF1
False    183
Name: SERPINF1, dtype: int64

SERPINF2
False    183
Name: SERPINF2, dtype: int64

SERPING1

False    183
Name: SERPING1, dtype: int64

SERPINH1
False    183
Name: SERPINH1, dtype: int64

SERPINI1
False    183
Name: SERPINI1, dtype: int64

SERPINI2
False    151
True      32
Name: SERPINI2, dtype: int64

SERTAD1
False    183
Name: SERTAD1, dtype: int64

SERTAD2
False    183
Name: SERTAD2, dtype: int64

SERTAD3
False    183
Name: SERTAD3, dtype: int64

SERTAD4
False    183
Name: SERTAD4, dtype: int64

SESN1
False    183
Name: SESN1, dtype: int64

SESN2
False    183
Name: SESN2, dtype: int64

SESN3
False    183
Name: SESN3, dtype: int64

SESTD1
False    183
Name: SESTD1, dtype: int64

SETBP1
False    183
Name: SETBP1, dtype: int64

SETD1A
False    183
Name: SETD1A, dtype: int64

SETD1B
False    183
Name: SETD1B, dtype: int64

SETD2
False    183
Name: SETD2, dtype: int64

SETD3
False    183
Name: SETD3, dtype: int64

SETD4
False    183
Name: SETD4, dtype: int64

SETD5
False    183
Name: SETD5, dtype: int64

SETD6
False    183
Name: SETD6, dtype: int64

SETD7
False    183
Name: SETD7, dtype: int64

SETD8
False    183
Name: SETD8, dtype: int64

SETDB1
False    183
Name: SETDB1, dtype: int64

SETDB2
False    183
Name: SETDB2, dtype: int64

SETMAR
False    183
Name: SETMAR, dtype: int64

SETX
False    183
Name: SETX, dtype: int64

SET
False    183
Name: SET, dtype: int64

SEZ6L2
False    183
Name: SEZ6L2, dtype: int64

SEZ6L
False    179
True       4
Name: SEZ6L, dtype: int64

SEZ6
False    175
True       8
Name: SEZ6, dtype: int64

SF1
False    183
Name: SF1, dtype: int64

SF3A1
False    183
Name: SF3A1, dtype: int64

SF3A2
False    183
Name: SF3A2, dtype: int64

SF3A3
False    183
Name: SF3A3, dtype: int64

SF3B14
False    183
Name: SF3B14, dtype: int64

SF3B1
False    183
Name: SF3B1, dtype: int64

SF3B2
False    183
Name: SF3B2, dtype: int64

SF3B3
False    183
Name: SF3B3, dtype: int64

SF3B4
False    183
Name: SF3B4, dtype: int64

SF3B5
False    183
Name: SF3B5, dtype: int64

SF4
False    183
Name: SF4, dtype: int64

SFI1
False    183
Name: SFI1, dtype: int64

SFMBT1
False    183
Name: SFMBT1, dtype: int64

SFMBT2
False    182
True       1
Name: SFMBT2, dtype: int64

SFN
False    181
True       2
Name: SFN, dtype: int64

SFPQ
False    183
Name: SFPQ, dtype: int64

SFRP1
False    183
Name: SFRP1, dtype: int64

SFRP2
False    183
Name: SFRP2, dtype: int64

SFRP4
False    183
Name: SFRP4, dtype: int64

SFRP5
False    181
True       2
Name: SFRP5, dtype: int64

SFRS11
False    183
Name: SFRS11, dtype: int64

SFRS12IP1
False    183
Name: SFRS12IP1, dtype: int64

SFRS12
False    183
Name: SFRS12, dtype: int64

SFRS13A
False    183
Name: SFRS13A, dtype: int64

SFRS13B
False    182
True       1
Name: SFRS13B, dtype: int64

SFRS14
False    183
Name: SFRS14, dtype: int64

SFRS15
False    183
Name: SFRS15, dtype: int64

SFRS16
False    183
Name: SFRS16, dtype: int64

SFRS17A
False    183
Name: SFRS17A, dtype: int64

SFRS18
False    183
Name: SFRS18, dtype: int64

SFRS1
False    183
Name: SFRS1, dtype: int64

SFRS2B
False    183
Name: SFRS2B, dtype: int64

SFRS2IP
False    183
Name: SFRS2IP, dtype: int64

SFRS2
False    183
Name: SFRS2, dtype: int64

SFRS3
False    183
Name: SFRS3, dtype: int64

SFRS4
False    183
Name: SFRS4, dtype: int64

SFRS5
False    183
Name: SFRS5, dtype: int64

SFRS6
False    183
Name: SFRS6, dtype: int64

SFRS7
False    183
Name: SFRS7, dtype: int64

SFRS8
False    183
Name: SFRS8, dtype: int64

SFRS9
False    183
Name: SFRS9, dtype: int64

SFT2D1
False    183
Name: SFT2D1, dtype: int64

SFT2D2
False    183
Name: SFT2D2, dtype: int64

SFT2D3
False    183
Name: SFT2D3, dtype: int64

SFTA1P
False    146
True      37
Name: SFTA1P, dtype: int64

SFTA2
False    175
True       8
Name: SFTA2, dtype: int64

SFTPA1
False    152
True      31
Name: SFTPA1, dtype: int64

SFTPA2
False    180
True       3
Name: SFTPA2, dtype: int64

SFTPB
False    138
True      45
Name: SFTPB, dtype: int64

SFTPD
False    182
True       1
Name: SFTPD, dtype: int64

SFXN1
False    183
Name: SFXN1, dtype: int64

SFXN2
False    183
Name: SFXN2, dtype: int64

SFXN3
False    183
Name: SFXN3, dtype: int64

SFXN4
False    183
Name: SFXN4, dtype: int64

SFXN5
False    183
Name: SFXN5, dtype: int64

SGCA
False    183
Name: SGCA, dtype: int64

SGCB
False    183
Name: SGCB, dtype: int64

SGCD
False    183
Name: SGCD, dtype: int64

SGCE
False    183
Name: SGCE, dtype: int64

SGCG
False    165
True      18
Name: SGCG, dtype: int64

SGCZ
False    95
True     88
Name: SGCZ, dtype: int64

SGEF
False    183
Name: SGEF, dtype: int64

SGIP1
False    183
Name: SGIP1, dtype: int64

SGK196
False    180
True       3
Name: SGK196, dtype: int64

SGK1
False    183
Name: SGK1, dtype: int64

SGK223
False    183
Name: SGK223, dtype: int64

SGK269
False    183
Name: SGK269, dtype: int64

SGK2
False    183
Name: SGK2, dtype: int64

SGK3
False    183
Name: SGK3, dtype: int64

SGK494
False    183
Name: SGK494, dtype: int64

SGMS1
False    183
Name: SGMS1, dtype: int64

SGMS2
False    183
Name: SGMS2, dtype: int64

SGOL1
False    182
True       1
Name: SGOL1, dtype: int64

SGOL2
False    183
Name: SGOL2, dtype: int64

SGPL1
False    183
Name: SGPL1, dtype: int64

SGPP1
False    183
Name: SGPP1, dtype: int64

SGPP2
False    183
Name: SGPP2, dtype: int64

SGSH
False    183
Name: SGSH, dtype: int64

SGSM1
False    183
Name: SGSM1, dtype: int64

SGSM2
False    183
Name: SGSM2, dtype: int64

SGSM3
False    183
Name: SGSM3, dtype: int64

SGTA
False    183
Name: SGTA, dtype: int64

SGTB
False    183
Name: SGTB, dtype: int64

SH2B1
False    183
Name: SH2B1, dtype: int64

SH2B2
False    183
Name: SH2B2, dtype: int64

SH2B3
False    183
Name: SH2B3, dtype: int64

SH2D1A
False    180
True       3
Name: SH2D1A, dtype: int64

SH2D1B
False    183
Name: SH2D1B, dtype: int64

SH2D2A
False    183
Name: SH2D2A, dtype: int64

SH2D3A
False    183
Name: SH2D3A, dtype: int64

SH2D3C
False    183
Name: SH2D3C, dtype: int64

SH2D4A
False    183
Name: SH2D4A, dtype: int64

SH2D4B
False    160
True      23
Name: SH2D4B, dtype: int64

SH2D5
False    179
True       4
Name: SH2D5, dtype: int64

SH2D6
False    174
True       9
Name: SH2D6, dtype: int64

SH2D7
False    171
True      12
Name: SH2D7, dtype: int64

SH3BGRL2
False    183
Name: SH3BGRL2, dtype: int64

SH3BGRL3
False    183
Name: SH3BGRL3, dtype: int64

SH3BGRL
False    183
Name: SH3BGRL, dtype: int64

SH3BGR
False    183
Name: SH3BGR, dtype: int64

SH3BP1
False    183
Name: SH3BP1, dtype: int64

SH3BP2
False    183
Name: SH3BP2, dtype: int64

SH3BP4
False    183
Name: SH3BP4, dtype: int64

SH3BP5L
False    183
Name: SH3BP5L, dtype: int64

SH3BP5
False    183
Name: SH3BP5, dtype: int64

SH3D19
False    183
Name: SH3D19, dtype: int64

SH3D20
False    182
True       1
Name: SH3D20, dtype: int64

SH3GL1
False    183
Name: SH3GL1, dtype: int64

SH3GL2
False    178
True       5
Name: SH3GL2, dtype: int64

SH3GL3
False    137
True      46
Name: SH3GL3, dtype: int64

SH3GLB1
False    183
Name: SH3GLB1, dtype: int64

SH3GLB2
False    183
Name: SH3GLB2, dtype: int64

SH3KBP1
False    183
Name: SH3KBP1, dtype: int64

SH3PXD2A
False    183
Name: SH3PXD2A, dtype: int64

SH3PXD2B
False    183
Name: SH3PXD2B, dtype: int64

SH3RF1
False    183
Name: SH3RF1, dtype: int64

SH3RF2
False    181
True       2
Name: SH3RF2, dtype: int64

SH3RF3
False    183
Name: SH3RF3, dtype: int64

SH3TC1
False    183
Name: SH3TC1, dtype: int64

SH3TC2
False    183
Name: SH3TC2, dtype: int64

SH3YL1
False    183
Name: SH3YL1, dtype: int64

SHANK1
False    181
True       2
Name: SHANK1, dtype: int64

SHANK2
False    183
Name: SHANK2, dtype: int64

SHANK3
False    183
Name: SHANK3, dtype: int64

SHARPIN
False    183
Name: SHARPIN, dtype: int64

SHBG
False    171
True      12
Name: SHBG, dtype: int64

SHB
False    183
Name: SHB, dtype: int64

SHC1
False    183
Name: SHC1, dtype: int64

SHC2
False    183
Name: SHC2, dtype: int64

SHC3
False    182
True       1
Name: SHC3, dtype: int64

SHC4
False    183
Name: SHC4, dtype: int64

SHCBP1
False    183
Name: SHCBP1, dtype: int64

SHD
False    145
True      38
Name: SHD, dtype: int64

SHE
False    183
Name: SHE, dtype: int64

SHFM1
False    183
Name: SHFM1, dtype: int64

SHF
False    183
Name: SHF, dtype: int64

SHH
False    179
True       4
Name: SHH, dtype: int64

SHISA2
False    183
Name: SHISA2, dtype: int64

SHISA3
False    183
Name: SHISA3, dtype: int64

SHISA4
False    183
Name: SHISA4, dtype: int64

SHISA5
False    183
Name: SHISA5, dtype: int64

SHISA6
False    170
True      13
Name: SHISA6, dtype: int64

SHISA7
False    166
True      17
Name: SHISA7, dtype: int64

SHISA9
False    181
True       2
Name: SHISA9, dtype: int64

SHKBP1
False    183
Name: SHKBP1, dtype: int64

SHMT1
False    183
Name: SHMT1, dtype: int64

SHMT2
False    183
Name: SHMT2, dtype: int64

SHOC2

False    183
Name: SHOC2, dtype: int64

SHOX2
False    182
True       1
Name: SHOX2, dtype: int64

SHOX
True     93
False    90
Name: SHOX, dtype: int64

SHPK
False    183
Name: SHPK, dtype: int64

SHPRH
False    183
Name: SHPRH, dtype: int64

SHQ1
False    183
Name: SHQ1, dtype: int64

SHROOM1
False    183
Name: SHROOM1, dtype: int64

SHROOM2
False    183
Name: SHROOM2, dtype: int64

SHROOM3
False    183
Name: SHROOM3, dtype: int64

SHROOM4
False    183
Name: SHROOM4, dtype: int64

SIAE
False    183
Name: SIAE, dtype: int64

SIAH1
False    183
Name: SIAH1, dtype: int64

SIAH2
False    183
Name: SIAH2, dtype: int64

SIAH3
False    145
True      38
Name: SIAH3, dtype: int64

SIDT1
False    183
Name: SIDT1, dtype: int64

SIDT2
False    183
Name: SIDT2, dtype: int64

SIGIRR
False    183
Name: SIGIRR, dtype: int64

SIGLEC10
False    183
Name: SIGLEC10, dtype: int64

SIGLEC11
False    181
True       2
Name: SIGLEC11, dtype: int64

SIGLEC12
False    182
True       1
Name: SIGLEC12, dtype: int64

SIGLEC14
False    170
True      13
Name: SIGLEC14, dtype: int64

SIGLEC15
False    179
True       4
Name: SIGLEC15, dtype: int64

SIGLEC16
False    182
True       1
Name: SIGLEC16, dtype: int64

SIGLEC1
False    183
Name: SIGLEC1, dtype: int64

SIGLEC5
False    182
True       1
Name: SIGLEC5, dtype: int64

SIGLEC6
False    172
True      11
Name: SIGLEC6, dtype: int64

SIGLEC7
False    183
Name: SIGLEC7, dtype: int64

SIGLEC8
False    182
True       1
Name: SIGLEC8, dtype: int64

SIGLEC9
False    183
Name: SIGLEC9, dtype: int64

SIGLECP3
False    182
True       1
Name: SIGLECP3, dtype: int64

SIGMAR1
False    183
Name: SIGMAR1, dtype: int64

SIK1
False    183
Name: SIK1, dtype: int64

SIK2
False    183
Name: SIK2, dtype: int64

SIK3
False    183
Name: SIK3, dtype: int64

SIKE1
False    183
Name: SIKE1, dtype: int64

SIL1
False    183
Name: SIL1, dtype: int64

SILV
False    183
Name: SILV, dtype: int64

SIM1
False    139
True      44
Name: SIM1, dtype: int64

SIM2
False    183
Name: SIM2, dtype: int64

SIN3A
False    183
Name: SIN3A, dtype: int64

SIN3B
False    183
Name: SIN3B, dtype: int64

SIP1
False    183
Name: SIP1, dtype: int64

SIPA1L1
False    183
Name: SIPA1L1, dtype: int64

SIPA1L2
False    183
Name: SIPA1L2, dtype: int64

SIPA1L3
False    183
Name: SIPA1L3, dtype: int64

SIPA1
False    183
Name: SIPA1, dtype: int64

SIRPA
False    183
Name: SIRPA, dtype: int64

SIRPB1
False    183
Name: SIRPB1, dtype: int64

SIRPB2
False    183
Name: SIRPB2, dtype: int64

SIRPD
False    111
True      72
Name: SIRPD, dtype: int64

SIRPG
False    183
Name: SIRPG, dtype: int64

SIRT1
False    183
Name: SIRT1, dtype: int64

SIRT2
False    183
Name: SIRT2, dtype: int64

SIRT3
False    183
Name: SIRT3, dtype: int64

SIRT4
False    183
Name: SIRT4, dtype: int64

SIRT5
False    183
Name: SIRT5, dtype: int64

SIRT6
False    183
Name: SIRT6, dtype: int64

SIRT7
False    183
Name: SIRT7, dtype: int64

SIT1
False    183
Name: SIT1, dtype: int64

SIVA1
False    183
Name: SIVA1, dtype: int64

SIX1
False    181
True       2
Name: SIX1, dtype: int64

SIX2
False    181
True       2
Name: SIX2, dtype: int64

SIX3
False    153
True      30
Name: SIX3, dtype: int64

SIX4
False    182
True       1
Name: SIX4, dtype: int64

SIX5
False    183
Name: SIX5, dtype: int64

SI
False    104
True      79
Name: SI, dtype: int64

SKA1
False    183
Name: SKA1, dtype: int64

SKA2
False    183
Name: SKA2, dtype: int64

SKA3
False    183
Name: SKA3, dtype: int64

SKAP1
False    183
Name: SKAP1, dtype: int64

SKAP2
False    183
Name: SKAP2, dtype: int64

SKIL
False    183
Name: SKIL, dtype: int64

SKINTL
False    148
True      35
Name: SKINTL, dtype: int64

SKIV2L2
False    183
Name: SKIV2L2, dtype: int64

SKIV2L
False    183
Name: SKIV2L, dtype: int64

SKI
False    183
Name: SKI, dtype: int64

SKP1
False    183
Name: SKP1, dtype: int64

SKP2
False    183
Name: SKP2, dtype: int64

SLA2
False    183
Name: SLA2, dtype: int64

SLAIN1
False    183
Name: SLAIN1, dtype: int64

SLAIN2
False    183
Name: SLAIN2, dtype: int64

SLAMF1
False    182
True       1
Name: SLAMF1, dtype: int64

SLAMF6
False    183
Name: SLAMF6, dtype: int64

SLAMF7
False    183
Name: SLAMF7, dtype: int64

SLAMF8
False    183
Name: SLAMF8, dtype: int64

SLAMF9
False    179
True       4
Name: SLAMF9, dtype: int64

SLA
False    183
Name: SLA, dtype: int64

SLBP
False    183
Name: SLBP, dtype: int64

SLC10A1
False    130
True      53
Name: SLC10A1, dtype: int64

SLC10A2
False    94
True     89
Name: SLC10A2, dtype: int64

SLC10A3
False    183
Name: SLC10A3, dtype: int64

SLC10A4
False    180
True       3
Name: SLC10A4, dtype: int64

SLC10A5
False    183
Name: SLC10A5, dtype: int64

SLC10A6
False    179
True       4
Name: SLC10A6, dtype: int64

SLC10A7
False    183
Name: SLC10A7, dtype: int64

SLC11A1
False    183
Name: SLC11A1, dtype: int64

SLC11A2
False    183
Name: SLC11A2, dtype: int64

SLC12A1
False    138
True      45
Name: SLC12A1, dtype: int64

SLC12A2
False    183
Name: SLC12A2, dtype: int64

SLC12A3
False    169
True      14
Name: SLC12A3, dtype: int64

SLC12A4
False    183
Name: SLC12A4, dtype: int64

SLC12A5
False    181
True       2
Name: SLC12A5, dtype: int64

SLC12A6
False    183
Name: SLC12A6, dtype: int64

SLC12A7
False    183
Name: SLC12A7, dtype: int64

SLC12A8
False    183
Name: SLC12A8, dtype: int64

SLC12A9
False    183
Name: SLC12A9, dtype: int64

SLC13A1
True     108
False     75
Name: SLC13A1, dtype: int64

SLC13A2
False    171
True      12
Name: SLC13A2, dtype: int64

SLC13A3
False    183
Name: SLC13A3, dtype: int64

SLC13A4
False    182
True       1
Name: SLC13A4, dtype: int64

SLC13A5
False    183
Name: SLC13A5, dtype: int64

SLC14A1
False    183
Name: SLC14A1, dtype: int64

SLC14A2
False    132
True      51
Name: SLC14A2, dtype: int64

SLC15A1
False    180
True       3
Name: SLC15A1, dtype: int64

SLC15A2
False    183
Name: SLC15A2, dtype: int64

SLC15A3
False    183
Name: SLC15A3, dtype: int64

SLC15A4
False    183
Name: SLC15A4, dtype: int64

SLC16A10
False    183
Name: SLC16A10, dtype: int64

SLC16A11
False    183
Name: SLC16A11, dtype: int64

SLC16A12
False    182
True       1
Name: SLC16A12, dtype: int64

SLC16A13
False    183
Name: SLC16A13, dtype: int64

SLC16A14
False    183
Name: SLC16A14, dtype: int64

SLC16A1
False    183
Name: SLC16A1, dtype: int64

SLC16A2
False    183
Name: SLC16A2, dtype: int64

SLC16A3
False    183
Name: SLC16A3, dtype: int64

SLC16A4
False    183
Name: SLC16A4, dtype: int64

SLC16A5
False    183
Name: SLC16A5, dtype: int64

SLC16A6
False    183
Name: SLC16A6, dtype: int64

SLC16A7
False    182
True       1
Name: SLC16A7, dtype: int64

SLC16A8
False    183
Name: SLC16A8, dtype: int64

SLC16A9
False    183
Name: SLC16A9, dtype: int64

SLC17A1
False    100
True      83
Name: SLC17A1, dtype: int64

SLC17A3
True     112
False     71
Name: SLC17A3, dtype: int64

SLC17A4
False    173
True      10
Name: SLC17A4, dtype: int64

SLC17A5
False    183
Name: SLC17A5, dtype: int64

SLC17A6
False    141
True      42
Name: SLC17A6, dtype: int64

SLC17A7
False    182
True       1
Name: SLC17A7, dtype: int64

SLC17A8
False    109
True      74
Name: SLC17A8, dtype: int64

SLC17A9
False    183
Name: SLC17A9, dtype: int64

SLC18A1
False    137
True      46
Name: SLC18A1, dtype: int64

SLC18A2
False    183
Name: SLC18A2, dtype: int64

SLC18A3
False    154
True      29
Name: SLC18A3, dtype: int64

SLC19A1
False    183
Name: SLC19A1, dtype: int64

SLC19A2
False    183
Name: SLC19A2, dtype: int64

SLC19A3
False    182
True       1
Name: SLC19A3, dtype: int64

SLC1A1
False    183
Name: SLC1A1, dtype: int64

SLC1A2
False    182
True       1
Name: SLC1A2, dtype: int64

SLC1A3
False    183
Name: SLC1A3, dtype: int64

SLC1A4
False    183
Name: SLC1A4, dtype: int64

SLC1A5
False    183
Name: SLC1A5, dtype: int64

SLC1A6
True     107
False     76
Name: SLC1A6, dtype: int64

SLC1A7
False    183
Name: SLC1A7, dtype: int64

SLC20A1
False    183
Name: SLC20A1, dtype: int64

SLC20A2
False    183
Name: SLC20A2, dtype: int64

SLC22A10
True     117
False     66
Name: SLC22A10, dtype: int64

SLC22A11
False    178
True       5
Name: SLC22A11, dtype: int64

SLC22A13
False    146
True      37
Name: SLC22A13, dtype: int64

SLC22A14
False    149
True      34
Name: SLC22A14, dtype: int64

SLC22A15
False    183
Name: SLC22A15, dtype: int64

SLC22A16
False    170
True      13
Name: SLC22A16, dtype: int64

SLC22A17
False    183
Name: SLC22A17, dtype: int64

SLC22A18AS
False    183
Name: SLC22A18AS, dtype: int64

SLC22A18
False    183
Name: SLC22A18, dtype: int64

SLC22A1
False    175
True       8
Name: SLC22A1, dtype: int64

SLC22A20
False    182
True       1
Name: SLC22A20, dtype: int64

SLC22A23
False    183
Name: SLC22A23, dtype: int64

SLC22A2
False    147
True      36
Name: SLC22A2, dtype: int64

SLC22A3
False    183
Name: SLC22A3, dtype: int64

SLC22A4
False    183
Name: SLC22A4, dtype: int64

SLC22A5
False    183
Name: SLC22A5, dtype: int64

SLC22A7
True     116
False     67
Name: SLC22A7, dtype: int64

SLC22A9
False    146
True      37
Name: SLC22A9, dtype: int64

SLC23A1
False    182
True       1
Name: SLC23A1, dtype: int64

SLC23A2

False    183
Name: SLC23A2, dtype: int64

SLC23A3
False    183
Name: SLC23A3, dtype: int64

SLC24A1
False    183
Name: SLC24A1, dtype: int64

SLC24A2
False    161
True      22
Name: SLC24A2, dtype: int64

SLC24A3
False    183
Name: SLC24A3, dtype: int64

SLC24A4
False    181
True       2
Name: SLC24A4, dtype: int64

SLC24A5
False    172
True      11
Name: SLC24A5, dtype: int64

SLC24A6
False    183
Name: SLC24A6, dtype: int64

SLC25A10
False    183
Name: SLC25A10, dtype: int64

SLC25A11
False    183
Name: SLC25A11, dtype: int64

SLC25A12
False    183
Name: SLC25A12, dtype: int64

SLC25A13
False    183
Name: SLC25A13, dtype: int64

SLC25A14
False    183
Name: SLC25A14, dtype: int64

SLC25A15
False    183
Name: SLC25A15, dtype: int64

SLC25A16
False    183
Name: SLC25A16, dtype: int64

SLC25A17
False    183
Name: SLC25A17, dtype: int64

SLC25A18
False    182
True       1
Name: SLC25A18, dtype: int64

SLC25A19
False    183
Name: SLC25A19, dtype: int64

SLC25A1
False    183
Name: SLC25A1, dtype: int64

SLC25A20
False    183
Name: SLC25A20, dtype: int64

SLC25A21
False    179
True       4
Name: SLC25A21, dtype: int64

SLC25A22
False    183
Name: SLC25A22, dtype: int64

SLC25A23
False    183
Name: SLC25A23, dtype: int64

SLC25A24
False    183
Name: SLC25A24, dtype: int64

SLC25A25
False    183
Name: SLC25A25, dtype: int64

SLC25A26
False    183
Name: SLC25A26, dtype: int64

SLC25A27
False    183
Name: SLC25A27, dtype: int64

SLC25A28
False    183
Name: SLC25A28, dtype: int64

SLC25A29
False    183
Name: SLC25A29, dtype: int64

SLC25A2
False    149
True      34
Name: SLC25A2, dtype: int64

SLC25A30
False    183
Name: SLC25A30, dtype: int64

SLC25A32
False    183
Name: SLC25A32, dtype: int64

SLC25A33
False    183
Name: SLC25A33, dtype: int64

SLC25A34
False    183
Name: SLC25A34, dtype: int64

SLC25A35
False    183
Name: SLC25A35, dtype: int64

SLC25A36
False    183
Name: SLC25A36, dtype: int64

SLC25A37
False    183
Name: SLC25A37, dtype: int64

SLC25A38
False    183
Name: SLC25A38, dtype: int64

SLC25A39
False    183
Name: SLC25A39, dtype: int64

SLC25A3
False    183
Name: SLC25A3, dtype: int64

SLC25A40
False    183
Name: SLC25A40, dtype: int64

SLC25A41
False    167
True      16
Name: SLC25A41, dtype: int64

SLC25A42
False    183
Name: SLC25A42, dtype: int64

SLC25A43
False    183
Name: SLC25A43, dtype: int64

SLC25A44
False    183
Name: SLC25A44, dtype: int64

SLC25A45
False    183
Name: SLC25A45, dtype: int64

SLC25A46
False    183
Name: SLC25A46, dtype: int64

SLC25A4
False    183
Name: SLC25A4, dtype: int64

SLC25A5
False    183
Name: SLC25A5, dtype: int64

SLC25A6
False    183
Name: SLC25A6, dtype: int64

SLC26A10
False    183
Name: SLC26A10, dtype: int64

SLC26A11
False    183
Name: SLC26A11, dtype: int64

SLC26A1
False    183
Name: SLC26A1, dtype: int64

SLC26A2
False    183
Name: SLC26A2, dtype: int64

SLC26A3
False    107
True      76
Name: SLC26A3, dtype: int64

SLC26A4
False    182
True       1
Name: SLC26A4, dtype: int64

SLC26A5
False    152
True      31
Name: SLC26A5, dtype: int64

SLC26A6
False    183
Name: SLC26A6, dtype: int64

SLC26A7
False    183
Name: SLC26A7, dtype: int64

SLC26A8
False    170
True      13
Name: SLC26A8, dtype: int64

SLC26A9
False    182
True       1
Name: SLC26A9, dtype: int64

SLC27A1
False    183
Name: SLC27A1, dtype: int64

SLC27A2
False    183
Name: SLC27A2, dtype: int64

SLC27A3
False    183
Name: SLC27A3, dtype: int64

SLC27A4
False    183
Name: SLC27A4, dtype: int64

SLC27A5
False    183
Name: SLC27A5, dtype: int64

SLC27A6
False    166
True      17
Name: SLC27A6, dtype: int64

SLC28A1
False    166
True      17
Name: SLC28A1, dtype: int64

SLC28A2
False    128
True      55
Name: SLC28A2, dtype: int64

SLC28A3
False    179
True       4
Name: SLC28A3, dtype: int64

SLC29A1
False    183
Name: SLC29A1, dtype: int64

SLC29A2
False    183
Name: SLC29A2, dtype: int64

SLC29A3
False    183
Name: SLC29A3, dtype: int64

SLC29A4
False    183
Name: SLC29A4, dtype: int64

SLC2A10
False    183
Name: SLC2A10, dtype: int64

SLC2A11
False    183
Name: SLC2A11, dtype: int64

SLC2A12
False    183
Name: SLC2A12, dtype: int64

SLC2A13
False    183
Name: SLC2A13, dtype: int64

SLC2A14
False    182
True       1
Name: SLC2A14, dtype: int64

SLC2A1
False    183
Name: SLC2A1, dtype: int64

SLC2A2
False    170
True      13
Name: SLC2A2, dtype: int64

SLC2A3
False    183
Name: SLC2A3, dtype: int64

SLC2A4RG
False    183
Name: SLC2A4RG, dtype: int64

SLC2A4
False    183
Name: SLC2A4, dtype: int64

SLC2A5
False    183
Name: SLC2A5, dtype: int64

SLC2A6
False    183
Name: SLC2A6, dtype: int64

SLC2A8
False    183
Name: SLC2A8, dtype: int64

SLC2A9
False    183
Name: SLC2A9, dtype: int64

SLC30A10
False    175
True       8
Name: SLC30A10, dtype: int64

SLC30A1
False    183
Name: SLC30A1, dtype: int64

SLC30A2
False    179
True       4
Name: SLC30A2, dtype: int64

SLC30A3
False    170
True      13
Name: SLC30A3, dtype: int64

SLC30A4
False    183
Name: SLC30A4, dtype: int64

SLC30A5
False    183
Name: SLC30A5, dtype: int64

SLC30A6
False    183
Name: SLC30A6, dtype: int64

SLC30A7
False    183
Name: SLC30A7, dtype: int64

SLC30A8
False    176
True       7
Name: SLC30A8, dtype: int64

SLC30A9
False    183
Name: SLC30A9, dtype: int64

SLC31A1
False    183
Name: SLC31A1, dtype: int64

SLC31A2
False    183
Name: SLC31A2, dtype: int64

SLC32A1
True     107
False     76
Name: SLC32A1, dtype: int64

SLC33A1
False    183
Name: SLC33A1, dtype: int64

SLC34A1
True     106
False     77
Name: SLC34A1, dtype: int64

SLC34A2
False    180
True       3
Name: SLC34A2, dtype: int64

SLC34A3
False    182
True       1
Name: SLC34A3, dtype: int64

SLC35A1
False    183
Name: SLC35A1, dtype: int64

SLC35A2
False    183
Name: SLC35A2, dtype: int64

SLC35A3
False    183
Name: SLC35A3, dtype: int64

SLC35A4
False    183
Name: SLC35A4, dtype: int64

SLC35A5
False    183
Name: SLC35A5, dtype: int64

SLC35B1
False    183
Name: SLC35B1, dtype: int64

SLC35B2
False    183
Name: SLC35B2, dtype: int64

SLC35B3
False    183
Name: SLC35B3, dtype: int64

SLC35B4
False    183
Name: SLC35B4, dtype: int64

SLC35C1
False    183
Name: SLC35C1, dtype: int64

SLC35C2
False    183
Name: SLC35C2, dtype: int64

SLC35D1
False    183
Name: SLC35D1, dtype: int64

SLC35D2
False    183
Name: SLC35D2, dtype: int64

SLC35D3
False    178
True       5
Name: SLC35D3, dtype: int64

SLC35E1
False    183
Name: SLC35E1, dtype: int64

SLC35E3
False    183
Name: SLC35E3, dtype: int64

SLC35E4
False    183
Name: SLC35E4, dtype: int64

SLC35F1
False    183
Name: SLC35F1, dtype: int64

SLC35F2
False    183
Name: SLC35F2, dtype: int64

SLC35F3
False    181
True       2
Name: SLC35F3, dtype: int64

SLC35F4
False    158
True      25
Name: SLC35F4, dtype: int64

SLC35F5
False    183
Name: SLC35F5, dtype: int64

SLC36A1
False    183
Name: SLC36A1, dtype: int64

SLC36A4
False    183
Name: SLC36A4, dtype: int64

SLC37A1
False    183
Name: SLC37A1, dtype: int64

SLC37A2
False    183
Name: SLC37A2, dtype: int64

SLC37A3
False    183
Name: SLC37A3, dtype: int64

SLC37A4
False    183
Name: SLC37A4, dtype: int64

SLC38A10
False    183
Name: SLC38A10, dtype: int64

SLC38A11
False    181
True       2
Name: SLC38A11, dtype: int64

SLC38A1
False    183
Name: SLC38A1, dtype: int64

SLC38A2
False    183
Name: SLC38A2, dtype: int64

SLC38A3
False    181
True       2
Name: SLC38A3, dtype: int64

SLC38A4
False    183
Name: SLC38A4, dtype: int64

SLC38A5
False    183
Name: SLC38A5, dtype: int64

SLC38A6
False    183
Name: SLC38A6, dtype: int64

SLC38A7
False    183
Name: SLC38A7, dtype: int64

SLC38A8
False    96
True     87
Name: SLC38A8, dtype: int64

SLC38A9
False    183
Name: SLC38A9, dtype: int64

SLC39A10
False    183
Name: SLC39A10, dtype: int64

SLC39A11
False    183
Name: SLC39A11, dtype: int64

SLC39A12
False    98
True     85
Name: SLC39A12, dtype: int64

SLC39A13
False    183
Name: SLC39A13, dtype: int64

SLC39A14
False    183
Name: SLC39A14, dtype: int64

SLC39A1
False    183
Name: SLC39A1, dtype: int64

SLC39A2
False    143
True      40
Name: SLC39A2, dtype: int64

SLC39A3
False    183
Name: SLC39A3, dtype: int64

SLC39A4
False    183
Name: SLC39A4, dtype: int64

SLC39A5
False    181
True       2
Name: SLC39A5, dtype: int64

SLC39A6
False    183
Name: SLC39A6, dtype: int64

SLC39A7
False    183
Name: SLC39A7, dtype: int64

SLC39A8
False    183
Name: SLC39A8, dtype: int64

SLC39A9
False    183
Name: SLC39A9, dtype: int64

SLC3A1
False    183
Name: SLC3A1, dtype: int64

SLC3A2
False    183
Name: SLC3A2, dtype: int64

SLC40A1
False    183
Name: SLC40A1, dtype: int64

SLC41A1
False    183
Name: SLC41A1, dtype: int64

SLC41A2
False    183
Name: SLC41A2, dtype: int64

SLC41A3
False    183
Name: SLC41A3, dtype: int64

SLC43A1
False    183
Name: SLC43A1, dtype: int64

SLC43A2
False    183
Name: SLC43A2, dtype: int64

SLC43A3
False    183
Name: SLC43A3, dtype: int64

SLC44A1

False    183
Name: SLC44A1, dtype: int64

SLC44A2
False    183
Name: SLC44A2, dtype: int64

SLC44A3
False    183
Name: SLC44A3, dtype: int64

SLC44A4
False    183
Name: SLC44A4, dtype: int64

SLC44A5
False    182
True       1
Name: SLC44A5, dtype: int64

SLC45A1
False    183
Name: SLC45A1, dtype: int64

SLC45A2
False    165
True      18
Name: SLC45A2, dtype: int64

SLC45A3
False    183
Name: SLC45A3, dtype: int64

SLC45A4
False    183
Name: SLC45A4, dtype: int64

SLC46A1
False    183
Name: SLC46A1, dtype: int64

SLC46A2
False    181
True       2
Name: SLC46A2, dtype: int64

SLC46A3
False    183
Name: SLC46A3, dtype: int64

SLC47A1
False    183
Name: SLC47A1, dtype: int64

SLC47A2
False    150
True      33
Name: SLC47A2, dtype: int64

SLC48A1
False    183
Name: SLC48A1, dtype: int64

SLC4A10
False    180
True       3
Name: SLC4A10, dtype: int64

SLC4A11
False    183
Name: SLC4A11, dtype: int64

SLC4A1AP
False    183
Name: SLC4A1AP, dtype: int64

SLC4A1
True     93
False    90
Name: SLC4A1, dtype: int64

SLC4A2
False    183
Name: SLC4A2, dtype: int64

SLC4A3
False    183
Name: SLC4A3, dtype: int64

SLC4A4
False    183
Name: SLC4A4, dtype: int64

SLC4A5
False    183
Name: SLC4A5, dtype: int64

SLC4A7
False    183
Name: SLC4A7, dtype: int64

SLC4A8
False    183
Name: SLC4A8, dtype: int64

SLC4A9
False    149
True      34
Name: SLC4A9, dtype: int64

SLC5A10
False    177
True       6
Name: SLC5A10, dtype: int64

SLC5A11
False    142
True      41
Name: SLC5A11, dtype: int64

SLC5A12
False    153
True      30
Name: SLC5A12, dtype: int64

SLC5A1
False    181
True       2
Name: SLC5A1, dtype: int64

SLC5A2
False    169
True      14
Name: SLC5A2, dtype: int64

SLC5A3
False    183
Name: SLC5A3, dtype: int64

SLC5A4
False    172
True      11
Name: SLC5A4, dtype: int64

SLC5A5
False    168
True      15
Name: SLC5A5, dtype: int64

SLC5A6
False    183
Name: SLC5A6, dtype: int64

SLC5A7
False    148
True      35
Name: SLC5A7, dtype: int64

SLC5A8
True     93
False    90
Name: SLC5A8, dtype: int64

SLC5A9
False    183
Name: SLC5A9, dtype: int64

SLC6A10P
False    180
True       3
Name: SLC6A10P, dtype: int64

SLC6A11
False    109
True      74
Name: SLC6A11, dtype: int64

SLC6A12
False    182
True       1
Name: SLC6A12, dtype: int64

SLC6A13
False    146
True      37
Name: SLC6A13, dtype: int64

SLC6A14
False    177
True       6
Name: SLC6A14, dtype: int64

SLC6A15
False    159
True      24
Name: SLC6A15, dtype: int64

SLC6A16
False    182
True       1
Name: SLC6A16, dtype: int64

SLC6A17
False    183
Name: SLC6A17, dtype: int64

SLC6A19
False    173
True      10
Name: SLC6A19, dtype: int64

SLC6A1
False    182
True       1
Name: SLC6A1, dtype: int64

SLC6A20
False    181
True       2
Name: SLC6A20, dtype: int64

SLC6A2
False    117
True      66
Name: SLC6A2, dtype: int64

SLC6A3
False    157
True      26
Name: SLC6A3, dtype: int64

SLC6A4
False    176
True       7
Name: SLC6A4, dtype: int64

SLC6A6
False    183
Name: SLC6A6, dtype: int64

SLC6A7
False    174
True       9
Name: SLC6A7, dtype: int64

SLC6A8
False    183
Name: SLC6A8, dtype: int64

SLC6A9
False    183
Name: SLC6A9, dtype: int64

SLC7A10
False    118
True      65
Name: SLC7A10, dtype: int64

SLC7A11
False    183
Name: SLC7A11, dtype: int64

SLC7A14
False    176
True       7
Name: SLC7A14, dtype: int64

SLC7A1
False    183
Name: SLC7A1, dtype: int64

SLC7A2
False    183
Name: SLC7A2, dtype: int64

SLC7A3
False    167
True      16
Name: SLC7A3, dtype: int64

SLC7A4
False    183
Name: SLC7A4, dtype: int64

SLC7A5P1
False    130
True      53
Name: SLC7A5P1, dtype: int64

SLC7A5P2
False    179
True       4
Name: SLC7A5P2, dtype: int64

SLC7A5
False    183
Name: SLC7A5, dtype: int64

SLC7A6OS
False    183
Name: SLC7A6OS, dtype: int64

SLC7A6
False    183
Name: SLC7A6, dtype: int64

SLC7A7
False    183
Name: SLC7A7, dtype: int64

SLC7A8
False    183
Name: SLC7A8, dtype: int64

SLC7A9
False    180
True       3
Name: SLC7A9, dtype: int64

SLC8A1
False    183
Name: SLC8A1, dtype: int64

SLC8A2
False    181
True       2
Name: SLC8A2, dtype: int64

SLC8A3
False    180
True       3
Name: SLC8A3, dtype: int64

SLC9A10
False    155
True      28
Name: SLC9A10, dtype: int64

SLC9A11
False    142
True      41
Name: SLC9A11, dtype: int64

SLC9A1
False    183
Name: SLC9A1, dtype: int64

SLC9A2
False    181
True       2
Name: SLC9A2, dtype: int64

SLC9A3R1
False    183
Name: SLC9A3R1, dtype: int64

SLC9A3R2
False    183
Name: SLC9A3R2, dtype: int64

SLC9A3
False    181
True       2
Name: SLC9A3, dtype: int64

SLC9A4
False    166
True      17
Name: SLC9A4, dtype: int64

SLC9A5
False    183
Name: SLC9A5, dtype: int64

SLC9A6
False    183
Name: SLC9A6, dtype: int64

SLC9A7
False    183
Name: SLC9A7, dtype: int64

SLC9A8
False    183
Name: SLC9A8, dtype: int64

SLC9A9
False    183
Name: SLC9A9, dtype: int64

SLCO1A2
False    144
True      39
Name: SLCO1A2, dtype: int64

SLCO1B1
False    100
True      83
Name: SLCO1B1, dtype: int64

SLCO1B3
False    158
True      25
Name: SLCO1B3, dtype: int64

SLCO1C1
False    176
True       7
Name: SLCO1C1, dtype: int64

SLCO2A1
False    183
Name: SLCO2A1, dtype: int64

SLCO2B1
False    183
Name: SLCO2B1, dtype: int64

SLCO3A1
False    183
Name: SLCO3A1, dtype: int64

SLCO4A1
False    183
Name: SLCO4A1, dtype: int64

SLCO4C1
False    181
True       2
Name: SLCO4C1, dtype: int64

SLCO5A1
False    182
True       1
Name: SLCO5A1, dtype: int64

SLED1
False    151
True      32
Name: SLED1, dtype: int64

SLFN11
False    183
Name: SLFN11, dtype: int64

SLFN12L
False    182
True       1
Name: SLFN12L, dtype: int64

SLFN12
False    183
Name: SLFN12, dtype: int64

SLFN13
False    183
Name: SLFN13, dtype: int64

SLFN14
False    137
True      46
Name: SLFN14, dtype: int64

SLFN5
False    183
Name: SLFN5, dtype: int64

SLFNL1
False    183
Name: SLFNL1, dtype: int64

SLIT1
False    183
Name: SLIT1, dtype: int64

SLIT2
False    183
Name: SLIT2, dtype: int64

SLIT3
False    183
Name: SLIT3, dtype: int64

SLITRK1
False    160
True      23
Name: SLITRK1, dtype: int64

SLITRK2
False    179
True       4
Name: SLITRK2, dtype: int64

SLITRK3
False    178
True       5
Name: SLITRK3, dtype: int64

SLITRK4
False    182
True       1
Name: SLITRK4, dtype: int64

SLITRK5
False    182
True       1
Name: SLITRK5, dtype: int64

SLITRK6
False    183
Name: SLITRK6, dtype: int64

SLK
False    183
Name: SLK, dtype: int64

SLMAP
False    183
Name: SLMAP, dtype: int64

SLMO1
False    183
Name: SLMO1, dtype: int64

SLMO2
False    183
Name: SLMO2, dtype: int64

SLN
False    161
True      22
Name: SLN, dtype: int64

SLPI
False    183
Name: SLPI, dtype: int64

SLTM
False    183
Name: SLTM, dtype: int64

SLU7
False    183
Name: SLU7, dtype: int64

SLURP1
False    96
True     87
Name: SLURP1, dtype: int64

SMAD1
False    183
Name: SMAD1, dtype: int64

SMAD2
False    183
Name: SMAD2, dtype: int64

SMAD3
False    183
Name: SMAD3, dtype: int64

SMAD4
False    183
Name: SMAD4, dtype: int64

SMAD5OS
False    181
True       2
Name: SMAD5OS, dtype: int64

SMAD5
False    183
Name: SMAD5, dtype: int64

SMAD6
False    183
Name: SMAD6, dtype: int64

SMAD7
False    183
Name: SMAD7, dtype: int64

SMAD9
False    183
Name: SMAD9, dtype: int64

SMAGP
False    183
Name: SMAGP, dtype: int64

SMAP1
False    183
Name: SMAP1, dtype: int64

SMAP2
False    183
Name: SMAP2, dtype: int64

SMARCA1
False    183
Name: SMARCA1, dtype: int64

SMARCA2
False    183
Name: SMARCA2, dtype: int64

SMARCA4
False    183
Name: SMARCA4, dtype: int64

SMARCA5
False    183
Name: SMARCA5, dtype: int64

SMARCAD1
False    183
Name: SMARCAD1, dtype: int64

SMARCAL1
False    183
Name: SMARCAL1, dtype: int64

SMARCB1
False    183
Name: SMARCB1, dtype: int64

SMARCC1
False    183
Name: SMARCC1, dtype: int64

SMARCC2
False    183
Name: SMARCC2, dtype: int64

SMARCD1
False    183
Name: SMARCD1, dtype: int64

SMARCD2
False    183
Name: SMARCD2, dtype: int64

SMARCD3
False    183
Name: SMARCD3, dtype: int64

SMARCE1
False    183
Name: SMARCE1, dtype: int64

SMC1A
False    183
Name: SMC1A, dtype: int64

SMC1B
False    159
True      24
Name: SMC1B, dtype: int64

SMC2
False    183
Name: SMC2, dtype: int64

SMC3
False    183
Name: SMC3, dtype: int64

SMC4
False    183
Name: SMC4, dtype: int64

SMC5
False    183
Name: SMC5, dtype: int64

SMC6
False    183
Name: SMC6, dtype: int64

SMCHD1
False    183
Name: SMCHD1, dtype: int64

SMCR5
False    132
True      51
Name: SMCR5, dtype: int64

SMCR7L
False    183
Name: SMCR7L, dtype: int64

SMCR7
False    183
Name: SMCR7, dtype: int64

SMCR8
False    183
Name: SMCR8, dtype: int64

SMEK1
False    183
Name: SMEK1, dtype: int64

SMEK2
False    183
Name: SMEK2, dtype: int64

SMG1
False    183
Name: SMG1, dtype: int64

SMG5
False    183
Name: SMG5, dtype: int64

SMG6

False    183
Name: SMG6, dtype: int64

SMG7
False    183
Name: SMG7, dtype: int64

SMN1
False    158
True      25
Name: SMN1, dtype: int64

SMN2
False    183
Name: SMN2, dtype: int64

SMNDC1
False    183
Name: SMNDC1, dtype: int64

SMOC1
False    183
Name: SMOC1, dtype: int64

SMOC2
False    183
Name: SMOC2, dtype: int64

SMOX
False    183
Name: SMOX, dtype: int64

SMO
False    183
Name: SMO, dtype: int64

SMPD1
False    183
Name: SMPD1, dtype: int64

SMPD2
False    183
Name: SMPD2, dtype: int64

SMPD3
False    183
Name: SMPD3, dtype: int64

SMPD4
False    183
Name: SMPD4, dtype: int64

SMPDL3A
False    183
Name: SMPDL3A, dtype: int64

SMPDL3B
False    183
Name: SMPDL3B, dtype: int64

SMPX
False    158
True      25
Name: SMPX, dtype: int64

SMS
False    183
Name: SMS, dtype: int64

SMTNL1
False    176
True       7
Name: SMTNL1, dtype: int64

SMTNL2
False    179
True       4
Name: SMTNL2, dtype: int64

SMTN
False    183
Name: SMTN, dtype: int64

SMU1
False    183
Name: SMU1, dtype: int64

SMUG1
False    183
Name: SMUG1, dtype: int64

SMURF1
False    183
Name: SMURF1, dtype: int64

SMURF2
False    183
Name: SMURF2, dtype: int64

SMYD1
True     98
False    85
Name: SMYD1, dtype: int64

SMYD2
False    183
Name: SMYD2, dtype: int64

SMYD3
False    183
Name: SMYD3, dtype: int64

SMYD4
False    183
Name: SMYD4, dtype: int64

SMYD5
False    183
Name: SMYD5, dtype: int64

SNAI1
False    183
Name: SNAI1, dtype: int64

SNAI2
False    183
Name: SNAI2, dtype: int64

SNAI3
False    183
Name: SNAI3, dtype: int64

SNAP23
False    183
Name: SNAP23, dtype: int64

SNAP25
False    183
Name: SNAP25, dtype: int64

SNAP29
False    183
Name: SNAP29, dtype: int64

SNAP47
False    183
Name: SNAP47, dtype: int64

SNAP91
False    181
True       2
Name: SNAP91, dtype: int64

SNAPC1
False    183
Name: SNAPC1, dtype: int64

SNAPC2
False    183
Name: SNAPC2, dtype: int64

SNAPC3
False    183
Name: SNAPC3, dtype: int64

SNAPC4
False    183
Name: SNAPC4, dtype: int64

SNAPC5
False    183
Name: SNAPC5, dtype: int64

SNAPIN
False    183
Name: SNAPIN, dtype: int64

SNCAIP
False    183
Name: SNCAIP, dtype: int64

SNCA
False    183
Name: SNCA, dtype: int64

SNCB
False    174
True       9
Name: SNCB, dtype: int64

SNCG
False    183
Name: SNCG, dtype: int64

SND1
False    183
Name: SND1, dtype: int64

SNED1
False    183
Name: SNED1, dtype: int64

SNF8
False    183
Name: SNF8, dtype: int64

SNHG10
False    183
Name: SNHG10, dtype: int64

SNHG11
False    183
Name: SNHG11, dtype: int64

SNHG12
False    183
Name: SNHG12, dtype: int64

SNHG1
False    183
Name: SNHG1, dtype: int64

SNHG3-RCC1
False    182
True       1
Name: SNHG3-RCC1, dtype: int64

SNHG3
False    183
Name: SNHG3, dtype: int64

SNHG4
False    180
True       3
Name: SNHG4, dtype: int64

SNHG5
False    183
Name: SNHG5, dtype: int64

SNHG6
False    183
Name: SNHG6, dtype: int64

SNHG7
False    183
Name: SNHG7, dtype: int64

SNHG8
False    183
Name: SNHG8, dtype: int64

SNHG9
False    183
Name: SNHG9, dtype: int64

SNIP1
False    183
Name: SNIP1, dtype: int64

SNN
False    183
Name: SNN, dtype: int64

SNORA18
True     112
False     71
Name: SNORA18, dtype: int64

SNORA21
True     128
False     55
Name: SNORA21, dtype: int64

SNORA23
True     121
False     62
Name: SNORA23, dtype: int64

SNORA24
True     117
False     66
Name: SNORA24, dtype: int64

SNORA31
True     93
False    90
Name: SNORA31, dtype: int64

SNORA39
False    181
True       2
Name: SNORA39, dtype: int64

SNORA40
True     116
False     67
Name: SNORA40, dtype: int64

SNORA48
True     118
False     65
Name: SNORA48, dtype: int64

SNORA53
False    152
True      31
Name: SNORA53, dtype: int64

SNORA57
False    108
True      75
Name: SNORA57, dtype: int64

SNORA59B
True     118
False     65
Name: SNORA59B, dtype: int64

SNORA61
True     115
False     68
Name: SNORA61, dtype: int64

SNORA63
False    131
True      52
Name: SNORA63, dtype: int64

SNORA65
True     128
False     55
Name: SNORA65, dtype: int64

SNORA67
False    136
True      47
Name: SNORA67, dtype: int64

SNORA72
True     93
False    90
Name: SNORA72, dtype: int64

SNORA74A
True     118
False     65
Name: SNORA74A, dtype: int64

SNORA7B
False    176
True       7
Name: SNORA7B, dtype: int64

SNORA81
False    126
True      57
Name: SNORA81, dtype: int64

SNORA8
False    183
Name: SNORA8, dtype: int64

SNORD10
False    137
True      46
Name: SNORD10, dtype: int64

SNORD116-20
False    169
True      14
Name: SNORD116-20, dtype: int64

SNORD116-28
False    182
True       1
Name: SNORD116-28, dtype: int64

SNORD116-4
False    167
True      16
Name: SNORD116-4, dtype: int64

SNORD15B
True     102
False     81
Name: SNORD15B, dtype: int64

SNORD17
False    164
True      19
Name: SNORD17, dtype: int64

SNORD1C
False    183
Name: SNORD1C, dtype: int64

SNORD22
True     96
False    87
Name: SNORD22, dtype: int64

SNORD94
True     111
False     72
Name: SNORD94, dtype: int64

SNORD97
True     110
False     73
Name: SNORD97, dtype: int64

SNPH
False    183
Name: SNPH, dtype: int64

SNRK
False    183
Name: SNRK, dtype: int64

SNRNP200
False    183
Name: SNRNP200, dtype: int64

SNRNP25
False    183
Name: SNRNP25, dtype: int64

SNRNP27
False    183
Name: SNRNP27, dtype: int64

SNRNP35
False    183
Name: SNRNP35, dtype: int64

SNRNP40
False    183
Name: SNRNP40, dtype: int64

SNRNP48
False    183
Name: SNRNP48, dtype: int64

SNRNP70
False    183
Name: SNRNP70, dtype: int64

SNRPA1
False    183
Name: SNRPA1, dtype: int64

SNRPA
False    183
Name: SNRPA, dtype: int64

SNRPB2
False    183
Name: SNRPB2, dtype: int64

SNRPB
False    183
Name: SNRPB, dtype: int64

SNRPC
False    183
Name: SNRPC, dtype: int64

SNRPD1
False    183
Name: SNRPD1, dtype: int64

SNRPD2
False    183
Name: SNRPD2, dtype: int64

SNRPD3
False    183
Name: SNRPD3, dtype: int64

SNRPE
False    183
Name: SNRPE, dtype: int64

SNRPF
False    183
Name: SNRPF, dtype: int64

SNRPG
False    183
Name: SNRPG, dtype: int64

SNRPN
False    183
Name: SNRPN, dtype: int64

SNTA1
False    183
Name: SNTA1, dtype: int64

SNTB1
False    183
Name: SNTB1, dtype: int64

SNTB2
False    183
Name: SNTB2, dtype: int64

SNTG1
False    101
True      82
Name: SNTG1, dtype: int64

SNTG2
False    162
True      21
Name: SNTG2, dtype: int64

SNTN
False    158
True      25
Name: SNTN, dtype: int64

SNUPN
False    183
Name: SNUPN, dtype: int64

SNURF
False    181
True       2
Name: SNURF, dtype: int64

SNW1
False    183
Name: SNW1, dtype: int64

SNX10
False    183
Name: SNX10, dtype: int64

SNX11
False    183
Name: SNX11, dtype: int64

SNX12
False    183
Name: SNX12, dtype: int64

SNX13
False    183
Name: SNX13, dtype: int64

SNX14
False    183
Name: SNX14, dtype: int64

SNX15
False    183
Name: SNX15, dtype: int64

SNX16
False    183
Name: SNX16, dtype: int64

SNX17
False    183
Name: SNX17, dtype: int64

SNX18
False    183
Name: SNX18, dtype: int64

SNX19
False    183
Name: SNX19, dtype: int64

SNX1
False    183
Name: SNX1, dtype: int64

SNX20
False    183
Name: SNX20, dtype: int64

SNX21
False    183
Name: SNX21, dtype: int64

SNX22
False    183
Name: SNX22, dtype: int64

SNX24
False    183
Name: SNX24, dtype: int64

SNX25
False    183
Name: SNX25, dtype: int64

SNX27
False    183
Name: SNX27, dtype: int64

SNX29
False    183
Name: SNX29, dtype: int64

SNX2
False    183
Name: SNX2, dtype: int64

SNX30
False    183
Name: SNX30, dtype: int64

SNX31
False    147
True      36
Name: SNX31, dtype: int64

SNX32
False    178
True       5
Name: SNX32, dtype: int64

SNX33
False    183
Name: SNX33, dtype: int64

SNX3
False    183
Name: SNX3, dtype: int64

SNX4
False    183
Name: SNX4, dtype: int64

SNX5
False    183
Name: SNX5, dtype: int64

SNX6
False    183
Name: SNX6, dtype: int64

SNX7
False    183
Name: SNX7, dtype: int64

SNX8
False    183
Name: SNX8, dtype: int64

SNX9
False    183
Name: SNX9, dtype: int64

SOAT1
False    183
Name: SOAT1, dtype: int64

SOAT2
False    171
True      12
Name: SOAT2, dtype: int64

SOBP
False    183
Name: SOBP, dtype: int64

SOCS1
False    183
Name: SOCS1, dtype: int64

SOCS2
False    183
Name: SOCS2, dtype: int64

SOCS3
False    183
Name: SOCS3, dtype: int64

SOCS4
False    183
Name: SOCS4, dtype: int64

SOCS5
False    183
Name: SOCS5, dtype: int64

SOCS6
False    183
Name: SOCS6, dtype: int64

SOCS7
False    183
Name: SOCS7, dtype: int64

SOD1
False    183
Name: SOD1, dtype: int64

SOD2
False    183
Name: SOD2, dtype: int64

SOD3
False    183
Name: SOD3, dtype: int64

SOHLH2
False    168
True      15
Name: SOHLH2, dtype: int64

SOLH
False    183
Name: SOLH, dtype: int64

SON
False    183
Name: SON, dtype: int64

SORBS1
False    183
Name: SORBS1, dtype: int64

SORBS2
False    183
Name: SORBS2, dtype: int64

SORBS3
False    183
Name: SORBS3, dtype: int64

SORCS1
False    182
True       1
Name: SORCS1, dtype: int64

SORCS2
False    183
Name: SORCS2, dtype: int64

SORCS3
False    149
True      34
Name: SORCS3, dtype: int64

SORD
False    183
Name: SORD, dtype: int64

SORL1

False    183
Name: SORL1, dtype: int64

SORT1
False    183
Name: SORT1, dtype: int64

SOS1
False    183
Name: SOS1, dtype: int64

SOS2
False    183
Name: SOS2, dtype: int64

SOSTDC1
False    180
True       3
Name: SOSTDC1, dtype: int64

SOST
False    127
True      56
Name: SOST, dtype: int64

SOX10
False    179
True       4
Name: SOX10, dtype: int64

SOX11
False    181
True       2
Name: SOX11, dtype: int64

SOX12
False    183
Name: SOX12, dtype: int64

SOX13
False    183
Name: SOX13, dtype: int64

SOX15
False    183
Name: SOX15, dtype: int64

SOX17
False    183
Name: SOX17, dtype: int64

SOX18
False    183
Name: SOX18, dtype: int64

SOX1
True     114
False     69
Name: SOX1, dtype: int64

SOX21
False    171
True      12
Name: SOX21, dtype: int64

SOX2OT
False    174
True       9
Name: SOX2OT, dtype: int64

SOX2
False    180
True       3
Name: SOX2, dtype: int64

SOX30
False    180
True       3
Name: SOX30, dtype: int64

SOX3
True     128
False     55
Name: SOX3, dtype: int64

SOX4
False    183
Name: SOX4, dtype: int64

SOX5
False    183
Name: SOX5, dtype: int64

SOX6
False    183
Name: SOX6, dtype: int64

SOX7
False    183
Name: SOX7, dtype: int64

SOX8
False    183
Name: SOX8, dtype: int64

SOX9
False    183
Name: SOX9, dtype: int64

SP100
False    183
Name: SP100, dtype: int64

SP110
False    183
Name: SP110, dtype: int64

SP140L
False    183
Name: SP140L, dtype: int64

SP140
False    183
Name: SP140, dtype: int64

SP1
False    183
Name: SP1, dtype: int64

SP2
False    183
Name: SP2, dtype: int64

SP3
False    183
Name: SP3, dtype: int64

SP4
False    183
Name: SP4, dtype: int64

SP5
False    183
Name: SP5, dtype: int64

SP6
False    183
Name: SP6, dtype: int64

SP7
False    122
True      61
Name: SP7, dtype: int64

SPA17
False    183
Name: SPA17, dtype: int64

SPACA3
False    128
True      55
Name: SPACA3, dtype: int64

SPACA4
False    181
True       2
Name: SPACA4, dtype: int64

SPACA5
True     122
False     61
Name: SPACA5, dtype: int64

SPAG16
False    183
Name: SPAG16, dtype: int64

SPAG17
False    181
True       2
Name: SPAG17, dtype: int64

SPAG1
False    183
Name: SPAG1, dtype: int64

SPAG4
False    183
Name: SPAG4, dtype: int64

SPAG5
False    183
Name: SPAG5, dtype: int64

SPAG6
False    166
True      17
Name: SPAG6, dtype: int64

SPAG7
False    183
Name: SPAG7, dtype: int64

SPAG8
False    183
Name: SPAG8, dtype: int64

SPAG9
False    183
Name: SPAG9, dtype: int64

SPANXN3
True     126
False     57
Name: SPANXN3, dtype: int64

SPARCL1
False    183
Name: SPARCL1, dtype: int64

SPARC
False    183
Name: SPARC, dtype: int64

SPAST
False    183
Name: SPAST, dtype: int64

SPATA12
False    178
True       5
Name: SPATA12, dtype: int64

SPATA13
False    183
Name: SPATA13, dtype: int64

SPATA17
False    181
True       2
Name: SPATA17, dtype: int64

SPATA18
False    183
Name: SPATA18, dtype: int64

SPATA1
False    178
True       5
Name: SPATA1, dtype: int64

SPATA20
False    183
Name: SPATA20, dtype: int64

SPATA21
False    102
True      81
Name: SPATA21, dtype: int64

SPATA22
False    102
True      81
Name: SPATA22, dtype: int64

SPATA24
False    183
Name: SPATA24, dtype: int64

SPATA2L
False    183
Name: SPATA2L, dtype: int64

SPATA2
False    183
Name: SPATA2, dtype: int64

SPATA4
False    135
True      48
Name: SPATA4, dtype: int64

SPATA5L1
False    183
Name: SPATA5L1, dtype: int64

SPATA5
False    183
Name: SPATA5, dtype: int64

SPATA6
False    183
Name: SPATA6, dtype: int64

SPATA7
False    183
Name: SPATA7, dtype: int64

SPATA8
True     114
False     69
Name: SPATA8, dtype: int64

SPATA9
False    183
Name: SPATA9, dtype: int64

SPATC1
False    177
True       6
Name: SPATC1, dtype: int64

SPATS1
True     108
False     75
Name: SPATS1, dtype: int64

SPATS2L
False    183
Name: SPATS2L, dtype: int64

SPATS2
False    183
Name: SPATS2, dtype: int64

SPC24
False    182
True       1
Name: SPC24, dtype: int64

SPC25
False    183
Name: SPC25, dtype: int64

SPCS1
False    183
Name: SPCS1, dtype: int64

SPCS2
False    183
Name: SPCS2, dtype: int64

SPCS3
False    183
Name: SPCS3, dtype: int64

SPDEF
False    183
Name: SPDEF, dtype: int64

SPDYA
False    183
Name: SPDYA, dtype: int64

SPDYC
False    125
True      58
Name: SPDYC, dtype: int64

SPDYE1
False    183
Name: SPDYE1, dtype: int64

SPDYE2
False    116
True      67
Name: SPDYE2, dtype: int64

SPDYE3
False    183
Name: SPDYE3, dtype: int64

SPDYE5
False    182
True       1
Name: SPDYE5, dtype: int64

SPDYE6
False    183
Name: SPDYE6, dtype: int64

SPDYE7P
False    183
Name: SPDYE7P, dtype: int64

SPDYE8P
False    183
Name: SPDYE8P, dtype: int64

SPEF1
False    182
True       1
Name: SPEF1, dtype: int64

SPEF2
False    183
Name: SPEF2, dtype: int64

SPEG
False    183
Name: SPEG, dtype: int64

SPEN
False    183
Name: SPEN, dtype: int64

SPERT
False    124
True      59
Name: SPERT, dtype: int64

SPESP1
False    182
True       1
Name: SPESP1, dtype: int64

SPG11
False    183
Name: SPG11, dtype: int64

SPG20
False    183
Name: SPG20, dtype: int64

SPG21
False    183
Name: SPG21, dtype: int64

SPG7
False    183
Name: SPG7, dtype: int64

SPHAR
False    183
Name: SPHAR, dtype: int64

SPHK1
False    183
Name: SPHK1, dtype: int64

SPHK2
False    183
Name: SPHK2, dtype: int64

SPHKAP
False    143
True      40
Name: SPHKAP, dtype: int64

SPI1
False    183
Name: SPI1, dtype: int64

SPIB
False    181
True       2
Name: SPIB, dtype: int64

SPIC
True     114
False     69
Name: SPIC, dtype: int64

SPIN1
False    183
Name: SPIN1, dtype: int64

SPIN2A
False    172
True      11
Name: SPIN2A, dtype: int64

SPIN2B
False    183
Name: SPIN2B, dtype: int64

SPIN3
False    183
Name: SPIN3, dtype: int64

SPIN4
False    183
Name: SPIN4, dtype: int64

SPINK13
False    138
True      45
Name: SPINK13, dtype: int64

SPINK1
False    182
True       1
Name: SPINK1, dtype: int64

SPINK2
False    156
True      27
Name: SPINK2, dtype: int64

SPINK4
False    155
True      28
Name: SPINK4, dtype: int64

SPINK5
False    182
True       1
Name: SPINK5, dtype: int64

SPINK6
True     117
False     66
Name: SPINK6, dtype: int64

SPINK7
True     92
False    91
Name: SPINK7, dtype: int64

SPINLW1
True     124
False     59
Name: SPINLW1, dtype: int64

SPINT1
False    183
Name: SPINT1, dtype: int64

SPINT2
False    183
Name: SPINT2, dtype: int64

SPIRE1
False    183
Name: SPIRE1, dtype: int64

SPIRE2
False    183
Name: SPIRE2, dtype: int64

SPNS1
False    183
Name: SPNS1, dtype: int64

SPNS2
False    183
Name: SPNS2, dtype: int64

SPNS3
False    183
Name: SPNS3, dtype: int64

SPN
False    183
Name: SPN, dtype: int64

SPOCD1
False    183
Name: SPOCD1, dtype: int64

SPOCK1
False    183
Name: SPOCK1, dtype: int64

SPOCK2
False    183
Name: SPOCK2, dtype: int64

SPOCK3
False    175
True       8
Name: SPOCK3, dtype: int64

SPON1
False    183
Name: SPON1, dtype: int64

SPON2
False    183
Name: SPON2, dtype: int64

SPOPL
False    183
Name: SPOPL, dtype: int64

SPOP
False    183
Name: SPOP, dtype: int64

SPP1
False    183
Name: SPP1, dtype: int64

SPPL2A
False    183
Name: SPPL2A, dtype: int64

SPPL2B
False    183
Name: SPPL2B, dtype: int64

SPPL3
False    183
Name: SPPL3, dtype: int64

SPRED1
False    183
Name: SPRED1, dtype: int64

SPRED2
False    183
Name: SPRED2, dtype: int64

SPRED3
False    174
True       9
Name: SPRED3, dtype: int64

SPRN
False    183
Name: SPRN, dtype: int64

SPRR1A
False    165
True      18
Name: SPRR1A, dtype: int64

SPRR1B
False    166
True      17
Name: SPRR1B, dtype: int64

SPRR2A
False    154
True      29
Name: SPRR2A, dtype: int64

SPRR2D
False    116
True      67
Name: SPRR2D, dtype: int64

SPRR3
False    167
True      16
Name: SPRR3, dtype: int64

SPRY1
False    183
Name: SPRY1, dtype: int64

SPRY2
False    183
Name: SPRY2, dtype: int64

SPRY3
False    183
Name: SPRY3, dtype: int64

SPRY4
False    183
Name: SPRY4, dtype: int64

SPRYD3
False    183
Name: SPRYD3, dtype: int64

SPRYD4
False    183
Name: SPRYD4, dtype: int64

SPR
False    183
Name: SPR, dtype: int64

SPSB1
False    183
Name: SPSB1, dtype: int64

SPSB2
False    183
Name: SPSB2, dtype: int64

SPSB3
False    183
Name: SPSB3, dtype: int64

SPSB4
False    179
True       4
Name: SPSB4, dtype: int64

SPTA1
False    148
True      35
Name: SPTA1, dtype: int64

SPTAN1
False    183
Name: SPTAN1, dtype: int64

SPTBN1
False    183
Name: SPTBN1, dtype: int64

SPTBN2
False    183
Name: SPTBN2, dtype: int64

SPTBN4
False    183
Name: SPTBN4, dtype: int64

SPTBN5
False    183
Name: SPTBN5, dtype: int64

SPTB
False    183
Name: SPTB, dtype: int64

SPTLC1
False    183
Name: SPTLC1, dtype: int64

SPTLC2
False    183
Name: SPTLC2, dtype: int64

SPTLC3
False    183
Name: SPTLC3, dtype: int64

SPTY2D1

False    183
Name: SPTY2D1, dtype: int64

SQLE
False    183
Name: SQLE, dtype: int64

SQRDL
False    183
Name: SQRDL, dtype: int64

SQSTM1
False    183
Name: SQSTM1, dtype: int64

SR140
False    183
Name: SR140, dtype: int64

SRA1
False    183
Name: SRA1, dtype: int64

SRBD1
False    183
Name: SRBD1, dtype: int64

SRCAP
False    183
Name: SRCAP, dtype: int64

SRCIN1
False    183
Name: SRCIN1, dtype: int64

SRCRB4D
False    183
Name: SRCRB4D, dtype: int64

SRC
False    183
Name: SRC, dtype: int64

SRD5A1
False    183
Name: SRD5A1, dtype: int64

SRD5A2
False    151
True      32
Name: SRD5A2, dtype: int64

SRD5A3
False    183
Name: SRD5A3, dtype: int64

SREBF1
False    183
Name: SREBF1, dtype: int64

SREBF2
False    183
Name: SREBF2, dtype: int64

SRFBP1
False    183
Name: SRFBP1, dtype: int64

SRF
False    183
Name: SRF, dtype: int64

SRGAP1
False    183
Name: SRGAP1, dtype: int64

SRGAP2
False    183
Name: SRGAP2, dtype: int64

SRGAP3
False    183
Name: SRGAP3, dtype: int64

SRGN
False    183
Name: SRGN, dtype: int64

SRI
False    183
Name: SRI, dtype: int64

SRL
False    183
Name: SRL, dtype: int64

SRMS
False    173
True      10
Name: SRMS, dtype: int64

SRM
False    183
Name: SRM, dtype: int64

SRP14
False    183
Name: SRP14, dtype: int64

SRP19
False    183
Name: SRP19, dtype: int64

SRP54
False    183
Name: SRP54, dtype: int64

SRP68
False    183
Name: SRP68, dtype: int64

SRP72
False    183
Name: SRP72, dtype: int64

SRP9
False    183
Name: SRP9, dtype: int64

SRPK1
False    183
Name: SRPK1, dtype: int64

SRPK2
False    183
Name: SRPK2, dtype: int64

SRPK3
False    183
Name: SRPK3, dtype: int64

SRPRB
False    183
Name: SRPRB, dtype: int64

SRPR
False    183
Name: SRPR, dtype: int64

SRPX2
False    183
Name: SRPX2, dtype: int64

SRPX
False    183
Name: SRPX, dtype: int64

SRRD
False    183
Name: SRRD, dtype: int64

SRRM1
False    183
Name: SRRM1, dtype: int64

SRRM2
False    183
Name: SRRM2, dtype: int64

SRRM3
False    183
Name: SRRM3, dtype: int64

SRRM4
False    148
True      35
Name: SRRM4, dtype: int64

SRRM5
False    183
Name: SRRM5, dtype: int64

SRRT
False    183
Name: SRRT, dtype: int64

SRR
False    183
Name: SRR, dtype: int64

SRXN1
False    183
Name: SRXN1, dtype: int64

SRY
True     121
False     62
Name: SRY, dtype: int64

SS18L1
False    183
Name: SS18L1, dtype: int64

SS18L2
False    183
Name: SS18L2, dtype: int64

SS18
False    183
Name: SS18, dtype: int64

SSBP1
False    183
Name: SSBP1, dtype: int64

SSBP2
False    183
Name: SSBP2, dtype: int64

SSBP3
False    183
Name: SSBP3, dtype: int64

SSBP4
False    183
Name: SSBP4, dtype: int64

SSB
False    183
Name: SSB, dtype: int64

SSC5D
False    183
Name: SSC5D, dtype: int64

SSFA2
False    183
Name: SSFA2, dtype: int64

SSH1
False    183
Name: SSH1, dtype: int64

SSH2
False    183
Name: SSH2, dtype: int64

SSH3
False    183
Name: SSH3, dtype: int64

SSNA1
False    183
Name: SSNA1, dtype: int64

SSPN
False    183
Name: SSPN, dtype: int64

SSPO
False    181
True       2
Name: SSPO, dtype: int64

SSR1
False    183
Name: SSR1, dtype: int64

SSR2
False    183
Name: SSR2, dtype: int64

SSR3
False    183
Name: SSR3, dtype: int64

SSR4
False    183
Name: SSR4, dtype: int64

SSRP1
False    183
Name: SSRP1, dtype: int64

SSSCA1
False    183
Name: SSSCA1, dtype: int64

SSTR1
False    183
Name: SSTR1, dtype: int64

SSTR2
False    183
Name: SSTR2, dtype: int64

SSTR3
False    170
True      13
Name: SSTR3, dtype: int64

SSTR5
False    168
True      15
Name: SSTR5, dtype: int64

SST
False    181
True       2
Name: SST, dtype: int64

SSU72
False    183
Name: SSU72, dtype: int64

SSX2IP
False    183
Name: SSX2IP, dtype: int64

ST13
False    183
Name: ST13, dtype: int64

ST14
False    183
Name: ST14, dtype: int64

ST18
False    182
True       1
Name: ST18, dtype: int64

ST20
False    183
Name: ST20, dtype: int64

ST3GAL1
False    183
Name: ST3GAL1, dtype: int64

ST3GAL2
False    183
Name: ST3GAL2, dtype: int64

ST3GAL3
False    183
Name: ST3GAL3, dtype: int64

ST3GAL4
False    183
Name: ST3GAL4, dtype: int64

ST3GAL5
False    183
Name: ST3GAL5, dtype: int64

ST3GAL6
False    183
Name: ST3GAL6, dtype: int64

ST5
False    183
Name: ST5, dtype: int64

ST6GAL1
False    183
Name: ST6GAL1, dtype: int64

ST6GAL2
False    182
True       1
Name: ST6GAL2, dtype: int64

ST6GALNAC1
False    183
Name: ST6GALNAC1, dtype: int64

ST6GALNAC2
False    183
Name: ST6GALNAC2, dtype: int64

ST6GALNAC3
False    183
Name: ST6GALNAC3, dtype: int64

ST6GALNAC4
False    183
Name: ST6GALNAC4, dtype: int64

ST6GALNAC5
False    183
Name: ST6GALNAC5, dtype: int64

ST6GALNAC6
False    183
Name: ST6GALNAC6, dtype: int64

ST7L
False    183
Name: ST7L, dtype: int64

ST7OT1
False    183
Name: ST7OT1, dtype: int64

ST7OT3
False    157
True      26
Name: ST7OT3, dtype: int64

ST7OT4
False    126
True      57
Name: ST7OT4, dtype: int64

ST7
False    183
Name: ST7, dtype: int64

ST8SIA1
False    183
Name: ST8SIA1, dtype: int64

ST8SIA2
False    178
True       5
Name: ST8SIA2, dtype: int64

ST8SIA3
False    176
True       7
Name: ST8SIA3, dtype: int64

ST8SIA4
False    183
Name: ST8SIA4, dtype: int64

ST8SIA5
False    175
True       8
Name: ST8SIA5, dtype: int64

ST8SIA6
False    142
True      41
Name: ST8SIA6, dtype: int64

STAB1
False    183
Name: STAB1, dtype: int64

STAB2
False    170
True      13
Name: STAB2, dtype: int64

STAC2
False    182
True       1
Name: STAC2, dtype: int64

STAC3
False    183
Name: STAC3, dtype: int64

STAC
False    182
True       1
Name: STAC, dtype: int64

STAG1
False    183
Name: STAG1, dtype: int64

STAG2
False    183
Name: STAG2, dtype: int64

STAG3L1
False    183
Name: STAG3L1, dtype: int64

STAG3L2
False    183
Name: STAG3L2, dtype: int64

STAG3L3
False    183
Name: STAG3L3, dtype: int64

STAG3L4
False    183
Name: STAG3L4, dtype: int64

STAG3
False    183
Name: STAG3, dtype: int64

STAM2
False    183
Name: STAM2, dtype: int64

STAMBPL1
False    183
Name: STAMBPL1, dtype: int64

STAMBP
False    183
Name: STAMBP, dtype: int64

STAM
False    183
Name: STAM, dtype: int64

STAP1
False    179
True       4
Name: STAP1, dtype: int64

STAP2
False    183
Name: STAP2, dtype: int64

STARD10
False    183
Name: STARD10, dtype: int64

STARD13
False    183
Name: STARD13, dtype: int64

STARD3NL
False    183
Name: STARD3NL, dtype: int64

STARD3
False    183
Name: STARD3, dtype: int64

STARD4
False    183
Name: STARD4, dtype: int64

STARD5
False    183
Name: STARD5, dtype: int64

STARD7
False    183
Name: STARD7, dtype: int64

STARD8
False    183
Name: STARD8, dtype: int64

STAR
False    183
Name: STAR, dtype: int64

STAT1
False    183
Name: STAT1, dtype: int64

STAT2
False    183
Name: STAT2, dtype: int64

STAT3
False    183
Name: STAT3, dtype: int64

STAT4
False    183
Name: STAT4, dtype: int64

STAT5A
False    183
Name: STAT5A, dtype: int64

STAT5B
False    183
Name: STAT5B, dtype: int64

STAT6
False    183
Name: STAT6, dtype: int64

STAU1
False    183
Name: STAU1, dtype: int64

STAU2
False    183
Name: STAU2, dtype: int64

STBD1
False    183
Name: STBD1, dtype: int64

STC1
False    183
Name: STC1, dtype: int64

STC2
False    183
Name: STC2, dtype: int64

STEAP1
False    183
Name: STEAP1, dtype: int64

STEAP2
False    183
Name: STEAP2, dtype: int64

STEAP3
False    183
Name: STEAP3, dtype: int64

STEAP4
False    183
Name: STEAP4, dtype: int64

STIL
False    183
Name: STIL, dtype: int64

STIM1
False    183
Name: STIM1, dtype: int64

STIM2
False    183
Name: STIM2, dtype: int64

STIP1
False    183
Name: STIP1, dtype: int64

STK10
False    183
Name: STK10, dtype: int64

STK11IP
False    183
Name: STK11IP, dtype: int64

STK11
False    183
Name: STK11, dtype: int64

STK16
False    183
Name: STK16, dtype: int64

STK17A
False    183
Name: STK17A, dtype: int64

STK17B
False    183
Name: STK17B, dtype: int64

STK19
False    183
Name: STK19, dtype: int64

STK24
False    183
Name: STK24, dtype: int64

STK25
False    183
Name: STK25, dtype: int64

STK31
False    182
True       1
Name: STK31, dtype: int64

STK32A
False    178
True       5
Name: STK32A, dtype: int64

STK32B
False    183
Name: STK32B, dtype: int64

STK32C
False    183
Name: STK32C, dtype: int64

STK33
False    182
True       1
Name: STK33, dtype: int64

STK35
False    183
Name: STK35, dtype: int64

STK36
False    183
Name: STK36, dtype: int64

STK38L
False    183
Name: STK38L, dtype: int64

STK38

False    183
Name: STK38, dtype: int64

STK39
False    183
Name: STK39, dtype: int64

STK3
False    183
Name: STK3, dtype: int64

STK40
False    183
Name: STK40, dtype: int64

STK4
False    183
Name: STK4, dtype: int64

STL
False    175
True       8
Name: STL, dtype: int64

STMN1
False    183
Name: STMN1, dtype: int64

STMN2
False    182
True       1
Name: STMN2, dtype: int64

STMN3
False    183
Name: STMN3, dtype: int64

STMN4
False    155
True      28
Name: STMN4, dtype: int64

STOML1
False    183
Name: STOML1, dtype: int64

STOML2
False    183
Name: STOML2, dtype: int64

STOML3
False    105
True      78
Name: STOML3, dtype: int64

STOM
False    183
Name: STOM, dtype: int64

STON1-GTF2A1L
False    118
True      65
Name: STON1-GTF2A1L, dtype: int64

STON1
False    183
Name: STON1, dtype: int64

STON2
False    183
Name: STON2, dtype: int64

STOX1
False    183
Name: STOX1, dtype: int64

STOX2
False    183
Name: STOX2, dtype: int64

STRA13
False    183
Name: STRA13, dtype: int64

STRA6
False    183
Name: STRA6, dtype: int64

STRADA
False    183
Name: STRADA, dtype: int64

STRADB
False    183
Name: STRADB, dtype: int64

STRAP
False    183
Name: STRAP, dtype: int64

STRBP
False    183
Name: STRBP, dtype: int64

STRC
False    183
Name: STRC, dtype: int64

STRN3
False    183
Name: STRN3, dtype: int64

STRN4
False    183
Name: STRN4, dtype: int64

STRN
False    183
Name: STRN, dtype: int64

STS
False    183
Name: STS, dtype: int64

STT3A
False    183
Name: STT3A, dtype: int64

STT3B
False    183
Name: STT3B, dtype: int64

STUB1
False    183
Name: STUB1, dtype: int64

STX10
False    183
Name: STX10, dtype: int64

STX11
False    183
Name: STX11, dtype: int64

STX12
False    183
Name: STX12, dtype: int64

STX16
False    183
Name: STX16, dtype: int64

STX17
False    183
Name: STX17, dtype: int64

STX18
False    183
Name: STX18, dtype: int64

STX19
False    181
True       2
Name: STX19, dtype: int64

STX1A
False    183
Name: STX1A, dtype: int64

STX1B
False    183
Name: STX1B, dtype: int64

STX2
False    183
Name: STX2, dtype: int64

STX3
False    183
Name: STX3, dtype: int64

STX4
False    183
Name: STX4, dtype: int64

STX5
False    183
Name: STX5, dtype: int64

STX6
False    183
Name: STX6, dtype: int64

STX7
False    183
Name: STX7, dtype: int64

STX8
False    183
Name: STX8, dtype: int64

STXBP1
False    183
Name: STXBP1, dtype: int64

STXBP2
False    183
Name: STXBP2, dtype: int64

STXBP3
False    183
Name: STXBP3, dtype: int64

STXBP4
False    183
Name: STXBP4, dtype: int64

STXBP5L
False    176
True       7
Name: STXBP5L, dtype: int64

STXBP5
False    183
Name: STXBP5, dtype: int64

STXBP6
False    183
Name: STXBP6, dtype: int64

STYK1
False    181
True       2
Name: STYK1, dtype: int64

STYXL1
False    183
Name: STYXL1, dtype: int64

STYX
False    183
Name: STYX, dtype: int64

SUB1
False    183
Name: SUB1, dtype: int64

SUCLA2
False    183
Name: SUCLA2, dtype: int64

SUCLG1
False    183
Name: SUCLG1, dtype: int64

SUCLG2
False    183
Name: SUCLG2, dtype: int64

SUCNR1
False    180
True       3
Name: SUCNR1, dtype: int64

SUDS3
False    183
Name: SUDS3, dtype: int64

SUFU
False    183
Name: SUFU, dtype: int64

SUGT1L1
False    183
Name: SUGT1L1, dtype: int64

SUGT1P1
False    179
True       4
Name: SUGT1P1, dtype: int64

SUGT1
False    183
Name: SUGT1, dtype: int64

SULF1
False    183
Name: SULF1, dtype: int64

SULF2
False    183
Name: SULF2, dtype: int64

SULT1A1
False    183
Name: SULT1A1, dtype: int64

SULT1A2
False    183
Name: SULT1A2, dtype: int64

SULT1A3
False    183
Name: SULT1A3, dtype: int64

SULT1B1
False    181
True       2
Name: SULT1B1, dtype: int64

SULT1C2
False    181
True       2
Name: SULT1C2, dtype: int64

SULT1C4
False    183
Name: SULT1C4, dtype: int64

SULT1E1
False    175
True       8
Name: SULT1E1, dtype: int64

SULT2A1
True     126
False     57
Name: SULT2A1, dtype: int64

SULT2B1
False    182
True       1
Name: SULT2B1, dtype: int64

SULT4A1
False    180
True       3
Name: SULT4A1, dtype: int64

SUMF1
False    183
Name: SUMF1, dtype: int64

SUMF2
False    183
Name: SUMF2, dtype: int64

SUMO1P1
False    137
True      46
Name: SUMO1P1, dtype: int64

SUMO1P3
False    183
Name: SUMO1P3, dtype: int64

SUMO1
False    183
Name: SUMO1, dtype: int64

SUMO2
False    183
Name: SUMO2, dtype: int64

SUMO3
False    183
Name: SUMO3, dtype: int64

SUMO4
False    159
True      24
Name: SUMO4, dtype: int64

SUN1
False    183
Name: SUN1, dtype: int64

SUN2
False    183
Name: SUN2, dtype: int64

SUN3
True     100
False     83
Name: SUN3, dtype: int64

SUOX
False    183
Name: SUOX, dtype: int64

SUPT16H
False    183
Name: SUPT16H, dtype: int64

SUPT3H
False    183
Name: SUPT3H, dtype: int64

SUPT4H1
False    183
Name: SUPT4H1, dtype: int64

SUPT5H
False    183
Name: SUPT5H, dtype: int64

SUPT6H
False    183
Name: SUPT6H, dtype: int64

SUPT7L
False    183
Name: SUPT7L, dtype: int64

SUPV3L1
False    183
Name: SUPV3L1, dtype: int64

SURF1
False    183
Name: SURF1, dtype: int64

SURF2
False    183
Name: SURF2, dtype: int64

SURF4
False    183
Name: SURF4, dtype: int64

SURF6
False    183
Name: SURF6, dtype: int64

SUSD1
False    183
Name: SUSD1, dtype: int64

SUSD2
False    183
Name: SUSD2, dtype: int64

SUSD3
False    183
Name: SUSD3, dtype: int64

SUSD4
False    183
Name: SUSD4, dtype: int64

SUSD5
False    183
Name: SUSD5, dtype: int64

SUV39H1
False    183
Name: SUV39H1, dtype: int64

SUV39H2
False    183
Name: SUV39H2, dtype: int64

SUV420H1
False    183
Name: SUV420H1, dtype: int64

SUV420H2
False    183
Name: SUV420H2, dtype: int64

SUZ12P
False    183
Name: SUZ12P, dtype: int64

SUZ12
False    183
Name: SUZ12, dtype: int64

SV2A
False    183
Name: SV2A, dtype: int64

SV2B
False    183
Name: SV2B, dtype: int64

SV2C
False    151
True      32
Name: SV2C, dtype: int64

SVEP1
False    183
Name: SVEP1, dtype: int64

SVIL
False    183
Name: SVIL, dtype: int64

SVIP
False    183
Name: SVIP, dtype: int64

SVOPL
False    153
True      30
Name: SVOPL, dtype: int64

SVOP
False    178
True       5
Name: SVOP, dtype: int64

SWAP70
False    183
Name: SWAP70, dtype: int64

SYAP1
False    183
Name: SYAP1, dtype: int64

SYBU
False    183
Name: SYBU, dtype: int64

SYCE1L
False    175
True       8
Name: SYCE1L, dtype: int64

SYCE1
False    164
True      19
Name: SYCE1, dtype: int64

SYCE2
False    181
True       2
Name: SYCE2, dtype: int64

SYCN
False    144
True      39
Name: SYCN, dtype: int64

SYCP2L
False    167
True      16
Name: SYCP2L, dtype: int64

SYCP2
False    182
True       1
Name: SYCP2, dtype: int64

SYDE1
False    183
Name: SYDE1, dtype: int64

SYDE2
False    183
Name: SYDE2, dtype: int64

SYF2
False    183
Name: SYF2, dtype: int64

SYK
False    183
Name: SYK, dtype: int64

SYMPK
False    183
Name: SYMPK, dtype: int64

SYN1
False    183
Name: SYN1, dtype: int64

SYN2
False    183
Name: SYN2, dtype: int64

SYN3
False    176
True       7
Name: SYN3, dtype: int64

SYNCRIP
False    183
Name: SYNCRIP, dtype: int64

SYNC
False    183
Name: SYNC, dtype: int64

SYNE1
False    183
Name: SYNE1, dtype: int64

SYNE2
False    183
Name: SYNE2, dtype: int64

SYNGAP1
False    183
Name: SYNGAP1, dtype: int64

SYNGR1
False    183
Name: SYNGR1, dtype: int64

SYNGR2
False    183
Name: SYNGR2, dtype: int64

SYNGR3
False    183
Name: SYNGR3, dtype: int64

SYNGR4
False    173
True      10
Name: SYNGR4, dtype: int64

SYNJ1
False    183
Name: SYNJ1, dtype: int64

SYNJ2BP
False    183
Name: SYNJ2BP, dtype: int64

SYNJ2
False    183
Name: SYNJ2, dtype: int64

SYNM
False    183
Name: SYNM, dtype: int64

SYNPO2L
False    172
True      11
Name: SYNPO2L, dtype: int64

SYNPO2
False    183
Name: SYNPO2, dtype: int64

SYNPO
False    183
Name: SYNPO, dtype: int64

SYNPR
False    159
True      24
Name: SYNPR, dtype: int64

SYNRG
False    183
Name: SYNRG, dtype: int64

SYPL1
False    183
Name: SYPL1, dtype: int64

SYPL2
False    183
Name: SYPL2, dtype: int64

SYP
False    183
Name: SYP, dtype: int64

SYS1-DBNDD2
False    178
True       5
Name: SYS1-DBNDD2, dtype: int64

SYS1
False    183
Name: SYS1, dtype: int64

SYT10
False    104
True      79
Name: SYT10, dtype: int64

SYT11
False    183
Name: SYT11, dtype: int64

SYT12
False    183
Name: SYT12, dtype: int64

SYT13
False    183
Name: SYT13, dtype: int64

SYT14
False    171
True      12
Name: SYT14, dtype: int64

SYT15
False    183
Name: SYT15, dtype: int64

SYT16
False    171
True      12
Name: SYT16, dtype: int64

SYT17
False    183
Name: SYT17, dtype: int64

SYT1
False    183
Name: SYT1, dtype: int64

SYT2
False    182
True       1
Name: SYT2, dtype: int64

SYT3
False    181
True       2
Name: SYT3, dtype: int64

SYT4

False    176
True       7
Name: SYT4, dtype: int64

SYT5
False    183
Name: SYT5, dtype: int64

SYT6
False    170
True      13
Name: SYT6, dtype: int64

SYT7
False    183
Name: SYT7, dtype: int64

SYT8
False    176
True       7
Name: SYT8, dtype: int64

SYT9
False    182
True       1
Name: SYT9, dtype: int64

SYTL1
False    183
Name: SYTL1, dtype: int64

SYTL2
False    183
Name: SYTL2, dtype: int64

SYTL3
False    183
Name: SYTL3, dtype: int64

SYTL4
False    183
Name: SYTL4, dtype: int64

SYTL5
False    183
Name: SYTL5, dtype: int64

SYVN1
False    183
Name: SYVN1, dtype: int64

TAAR1
True     92
False    91
Name: TAAR1, dtype: int64

TAB1
False    183
Name: TAB1, dtype: int64

TAB2
False    183
Name: TAB2, dtype: int64

TAB3
False    183
Name: TAB3, dtype: int64

TAC1
False    168
True      15
Name: TAC1, dtype: int64

TAC3
False    151
True      32
Name: TAC3, dtype: int64

TAC4
False    100
True      83
Name: TAC4, dtype: int64

TACC1
False    183
Name: TACC1, dtype: int64

TACC2
False    183
Name: TACC2, dtype: int64

TACC3
False    183
Name: TACC3, dtype: int64

TACO1
False    183
Name: TACO1, dtype: int64

TACR1
False    181
True       2
Name: TACR1, dtype: int64

TACR2
False    183
Name: TACR2, dtype: int64

TACSTD2
False    183
Name: TACSTD2, dtype: int64

TADA1
False    183
Name: TADA1, dtype: int64

TADA2A
False    183
Name: TADA2A, dtype: int64

TADA2B
False    183
Name: TADA2B, dtype: int64

TADA3
False    183
Name: TADA3, dtype: int64

TAF10
False    183
Name: TAF10, dtype: int64

TAF11
False    183
Name: TAF11, dtype: int64

TAF12
False    183
Name: TAF12, dtype: int64

TAF13
False    182
True       1
Name: TAF13, dtype: int64

TAF15
False    183
Name: TAF15, dtype: int64

TAF1A
False    183
Name: TAF1A, dtype: int64

TAF1B
False    183
Name: TAF1B, dtype: int64

TAF1C
False    183
Name: TAF1C, dtype: int64

TAF1D
False    183
Name: TAF1D, dtype: int64

TAF1L
False    182
True       1
Name: TAF1L, dtype: int64

TAF1
False    183
Name: TAF1, dtype: int64

TAF2
False    183
Name: TAF2, dtype: int64

TAF3
False    183
Name: TAF3, dtype: int64

TAF4B
False    183
Name: TAF4B, dtype: int64

TAF4
False    183
Name: TAF4, dtype: int64

TAF5L
False    183
Name: TAF5L, dtype: int64

TAF5
False    183
Name: TAF5, dtype: int64

TAF6L
False    183
Name: TAF6L, dtype: int64

TAF6
False    183
Name: TAF6, dtype: int64

TAF7L
False    171
True      12
Name: TAF7L, dtype: int64

TAF7
False    183
Name: TAF7, dtype: int64

TAF8
False    183
Name: TAF8, dtype: int64

TAF9B
False    183
Name: TAF9B, dtype: int64

TAF9
False    183
Name: TAF9, dtype: int64

TAGAP
False    183
Name: TAGAP, dtype: int64

TAGLN2
False    183
Name: TAGLN2, dtype: int64

TAGLN3
False    180
True       3
Name: TAGLN3, dtype: int64

TAGLN
False    183
Name: TAGLN, dtype: int64

TAL1
False    183
Name: TAL1, dtype: int64

TAL2
False    135
True      48
Name: TAL2, dtype: int64

TALDO1
False    183
Name: TALDO1, dtype: int64

TANC1
False    183
Name: TANC1, dtype: int64

TANC2
False    183
Name: TANC2, dtype: int64

TANK
False    183
Name: TANK, dtype: int64

TAOK1
False    183
Name: TAOK1, dtype: int64

TAOK2
False    183
Name: TAOK2, dtype: int64

TAOK3
False    183
Name: TAOK3, dtype: int64

TAP1
False    183
Name: TAP1, dtype: int64

TAP2
False    183
Name: TAP2, dtype: int64

TAPBPL
False    183
Name: TAPBPL, dtype: int64

TAPBP
False    183
Name: TAPBP, dtype: int64

TAPT1
False    183
Name: TAPT1, dtype: int64

TARBP1
False    183
Name: TARBP1, dtype: int64

TARBP2
False    183
Name: TARBP2, dtype: int64

TARDBP
False    183
Name: TARDBP, dtype: int64

TARP
False    179
True       4
Name: TARP, dtype: int64

TARS2
False    183
Name: TARS2, dtype: int64

TARSL2
False    183
Name: TARSL2, dtype: int64

TARS
False    183
Name: TARS, dtype: int64

TAS1R1
False    167
True      16
Name: TAS1R1, dtype: int64

TAS1R3
False    181
True       2
Name: TAS1R3, dtype: int64

TAS2R10
False    144
True      39
Name: TAS2R10, dtype: int64

TAS2R13
True     107
False     76
Name: TAS2R13, dtype: int64

TAS2R14
False    178
True       5
Name: TAS2R14, dtype: int64

TAS2R19
False    156
True      27
Name: TAS2R19, dtype: int64

TAS2R20
False    183
Name: TAS2R20, dtype: int64

TAS2R31
False    162
True      21
Name: TAS2R31, dtype: int64

TAS2R38
False    95
True     88
Name: TAS2R38, dtype: int64

TAS2R3
True     92
False    91
Name: TAS2R3, dtype: int64

TAS2R43
True     97
False    86
Name: TAS2R43, dtype: int64

TAS2R4
False    173
True      10
Name: TAS2R4, dtype: int64

TAS2R50
True     118
False     65
Name: TAS2R50, dtype: int64

TAS2R5
False    178
True       5
Name: TAS2R5, dtype: int64

TAS2R60
True     124
False     59
Name: TAS2R60, dtype: int64

TASP1
False    183
Name: TASP1, dtype: int64

TATDN1
False    183
Name: TATDN1, dtype: int64

TATDN2
False    183
Name: TATDN2, dtype: int64

TATDN3
False    183
Name: TATDN3, dtype: int64

TAT
False    172
True      11
Name: TAT, dtype: int64

TAX1BP1
False    183
Name: TAX1BP1, dtype: int64

TAX1BP3
False    183
Name: TAX1BP3, dtype: int64

TAZ
False    183
Name: TAZ, dtype: int64

TBC1D10A
False    183
Name: TBC1D10A, dtype: int64

TBC1D10B
False    183
Name: TBC1D10B, dtype: int64

TBC1D10C
False    183
Name: TBC1D10C, dtype: int64

TBC1D12
False    183
Name: TBC1D12, dtype: int64

TBC1D13
False    183
Name: TBC1D13, dtype: int64

TBC1D14
False    183
Name: TBC1D14, dtype: int64

TBC1D15
False    183
Name: TBC1D15, dtype: int64

TBC1D16
False    183
Name: TBC1D16, dtype: int64

TBC1D17
False    183
Name: TBC1D17, dtype: int64

TBC1D19
False    183
Name: TBC1D19, dtype: int64

TBC1D1
False    183
Name: TBC1D1, dtype: int64

TBC1D20
False    183
Name: TBC1D20, dtype: int64

TBC1D22A
False    183
Name: TBC1D22A, dtype: int64

TBC1D22B
False    183
Name: TBC1D22B, dtype: int64

TBC1D23
False    183
Name: TBC1D23, dtype: int64

TBC1D24
False    183
Name: TBC1D24, dtype: int64

TBC1D25
False    183
Name: TBC1D25, dtype: int64

TBC1D26
True     92
False    91
Name: TBC1D26, dtype: int64

TBC1D29
True     107
False     76
Name: TBC1D29, dtype: int64

TBC1D2B
False    183
Name: TBC1D2B, dtype: int64

TBC1D2
False    183
Name: TBC1D2, dtype: int64

TBC1D3B
False    183
Name: TBC1D3B, dtype: int64

TBC1D3C
False    170
True      13
Name: TBC1D3C, dtype: int64

TBC1D3G
False    112
True      71
Name: TBC1D3G, dtype: int64

TBC1D3H
False    183
Name: TBC1D3H, dtype: int64

TBC1D3
False    183
Name: TBC1D3, dtype: int64

TBC1D4
False    183
Name: TBC1D4, dtype: int64

TBC1D5
False    183
Name: TBC1D5, dtype: int64

TBC1D7
False    183
Name: TBC1D7, dtype: int64

TBC1D8B
False    183
Name: TBC1D8B, dtype: int64

TBC1D8
False    183
Name: TBC1D8, dtype: int64

TBC1D9B
False    183
Name: TBC1D9B, dtype: int64

TBC1D9
False    183
Name: TBC1D9, dtype: int64

TBCA
False    183
Name: TBCA, dtype: int64

TBCB
False    183
Name: TBCB, dtype: int64

TBCCD1
False    183
Name: TBCCD1, dtype: int64

TBCC
False    183
Name: TBCC, dtype: int64

TBCD
False    183
Name: TBCD, dtype: int64

TBCEL
False    183
Name: TBCEL, dtype: int64

TBCE
False    183
Name: TBCE, dtype: int64

TBCK
False    183
Name: TBCK, dtype: int64

TBK1
False    183
Name: TBK1, dtype: int64

TBKBP1
False    183
Name: TBKBP1, dtype: int64

TBL1XR1
False    183
Name: TBL1XR1, dtype: int64

TBL1X
False    183
Name: TBL1X, dtype: int64

TBL1Y
True     105
False     78
Name: TBL1Y, dtype: int64

TBL2
False    183
Name: TBL2, dtype: int64

TBL3
False    183
Name: TBL3, dtype: int64

TBPL1
False    183
Name: TBPL1, dtype: int64

TBP
False    183
Name: TBP, dtype: int64

TBRG1
False    183
Name: TBRG1, dtype: int64

TBRG4
False    183
Name: TBRG4, dtype: int64

TBX10
False    125
True      58
Name: TBX10, dtype: int64

TBX15
False    183
Name: TBX15, dtype: int64

TBX18
False    181
True       2
Name: TBX18, dtype: int64

TBX19
False    183
Name: TBX19, dtype: int64

TBX1
False    180
True       3
Name: TBX1, dtype: int64

TBX21
False    183
Name: TBX21, dtype: int64

TBX2
False    183
Name: TBX2, dtype: int64

TBX3
False    183
Name: TBX3, dtype: int64

TBX4
False    165
True      18
Name: TBX4, dtype: int64

TBX5
False    127
True      56
Name: TBX5, dtype: int64

TBX6
False    183
Name: TBX6, dtype: int64

TBXA2R
False    183
Name: TBXA2R, dtype: int64

TBXAS1
False    183
Name: TBXAS1, dtype: int64

TC2N
False    183
Name: TC2N, dtype: int64

TCAM1P
False    155
True      28
Name: TCAM1P, dtype: int64

TCAP
False    182
True       1
Name: TCAP, dtype: int64

TCEA1
False    183
Name: TCEA1, dtype: int64

TCEA2
False    183
Name: TCEA2, dtype: int64

TCEA3
False    183
Name: TCEA3, dtype: int64

TCEAL1
False    183
Name: TCEAL1, dtype: int64

TCEAL2
False    182
True       1
Name: TCEAL2, dtype: int64

TCEAL3
False    183
Name: TCEAL3, dtype: int64

TCEAL4
False    183
Name: TCEAL4, dtype: int64

TCEAL5
False    183
Name: TCEAL5, dtype: int64

TCEAL6
False    183
Name: TCEAL6, dtype: int64

TCEAL7
False    183
Name: TCEAL7, dtype: int64

TCEAL8

False    183
Name: TCEAL8, dtype: int64

TCEANC
False    183
Name: TCEANC, dtype: int64

TCEB1
False    183
Name: TCEB1, dtype: int64

TCEB2
False    183
Name: TCEB2, dtype: int64

TCEB3B
True     113
False     70
Name: TCEB3B, dtype: int64

TCEB3
False    183
Name: TCEB3, dtype: int64

TCERG1L
False    160
True      23
Name: TCERG1L, dtype: int64

TCERG1
False    183
Name: TCERG1, dtype: int64

TCF12
False    183
Name: TCF12, dtype: int64

TCF15
False    182
True       1
Name: TCF15, dtype: int64

TCF19
False    183
Name: TCF19, dtype: int64

TCF20
False    183
Name: TCF20, dtype: int64

TCF21
False    183
Name: TCF21, dtype: int64

TCF23
True     106
False     77
Name: TCF23, dtype: int64

TCF25
False    183
Name: TCF25, dtype: int64

TCF3
False    183
Name: TCF3, dtype: int64

TCF4
False    183
Name: TCF4, dtype: int64

TCF7L1
False    183
Name: TCF7L1, dtype: int64

TCF7L2
False    183
Name: TCF7L2, dtype: int64

TCF7
False    183
Name: TCF7, dtype: int64

TCFL5
False    183
Name: TCFL5, dtype: int64

TCHH
False    183
Name: TCHH, dtype: int64

TCHP
False    183
Name: TCHP, dtype: int64

TCIRG1
False    183
Name: TCIRG1, dtype: int64

TCL1A
False    159
True      24
Name: TCL1A, dtype: int64

TCL1B
False    106
True      77
Name: TCL1B, dtype: int64

TCL6
False    157
True      26
Name: TCL6, dtype: int64

TCN1
False    179
True       4
Name: TCN1, dtype: int64

TCN2
False    183
Name: TCN2, dtype: int64

TCOF1
False    183
Name: TCOF1, dtype: int64

TCP10L
False    183
Name: TCP10L, dtype: int64

TCP11L1
False    183
Name: TCP11L1, dtype: int64

TCP11L2
False    183
Name: TCP11L2, dtype: int64

TCP11
False    163
True      20
Name: TCP11, dtype: int64

TCP1
False    183
Name: TCP1, dtype: int64

TCTA
False    183
Name: TCTA, dtype: int64

TCTE1
False    129
True      54
Name: TCTE1, dtype: int64

TCTE3
False    183
Name: TCTE3, dtype: int64

TCTEX1D1
False    183
Name: TCTEX1D1, dtype: int64

TCTEX1D2
False    183
Name: TCTEX1D2, dtype: int64

TCTEX1D4
False    183
Name: TCTEX1D4, dtype: int64

TCTN1
False    183
Name: TCTN1, dtype: int64

TCTN2
False    183
Name: TCTN2, dtype: int64

TCTN3
False    183
Name: TCTN3, dtype: int64

TDGF1
False    178
True       5
Name: TDGF1, dtype: int64

TDGF3
False    136
True      47
Name: TDGF3, dtype: int64

TDG
False    183
Name: TDG, dtype: int64

TDH
False    159
True      24
Name: TDH, dtype: int64

TDO2
False    182
True       1
Name: TDO2, dtype: int64

TDP1
False    183
Name: TDP1, dtype: int64

TDP2
False    183
Name: TDP2, dtype: int64

TDRD10
False    183
Name: TDRD10, dtype: int64

TDRD12
False    96
True     87
Name: TDRD12, dtype: int64

TDRD1
False    174
True       9
Name: TDRD1, dtype: int64

TDRD3
False    183
Name: TDRD3, dtype: int64

TDRD5
False    177
True       6
Name: TDRD5, dtype: int64

TDRD6
False    182
True       1
Name: TDRD6, dtype: int64

TDRD7
False    183
Name: TDRD7, dtype: int64

TDRD9
False    181
True       2
Name: TDRD9, dtype: int64

TDRG1
True     115
False     68
Name: TDRG1, dtype: int64

TDRKH
False    183
Name: TDRKH, dtype: int64

TEAD1
False    183
Name: TEAD1, dtype: int64

TEAD2
False    183
Name: TEAD2, dtype: int64

TEAD3
False    183
Name: TEAD3, dtype: int64

TEAD4
False    183
Name: TEAD4, dtype: int64

TECPR1
False    183
Name: TECPR1, dtype: int64

TECPR2
False    183
Name: TECPR2, dtype: int64

TECR
False    183
Name: TECR, dtype: int64

TECTA
False    182
True       1
Name: TECTA, dtype: int64

TEC
False    183
Name: TEC, dtype: int64

TEDDM1
False    114
True      69
Name: TEDDM1, dtype: int64

TEF
False    183
Name: TEF, dtype: int64

TEKT1
True     117
False     66
Name: TEKT1, dtype: int64

TEKT2
False    181
True       2
Name: TEKT2, dtype: int64

TEKT3
False    182
True       1
Name: TEKT3, dtype: int64

TEKT4
False    182
True       1
Name: TEKT4, dtype: int64

TEKT5
False    171
True      12
Name: TEKT5, dtype: int64

TEK
False    183
Name: TEK, dtype: int64

TELO2
False    183
Name: TELO2, dtype: int64

TENC1
False    183
Name: TENC1, dtype: int64

TEP1
False    183
Name: TEP1, dtype: int64

TEPP
False    101
True      82
Name: TEPP, dtype: int64

TERC
False    97
True     86
Name: TERC, dtype: int64

TERF1
False    183
Name: TERF1, dtype: int64

TERF2IP
False    183
Name: TERF2IP, dtype: int64

TERF2
False    183
Name: TERF2, dtype: int64

TERT
False    147
True      36
Name: TERT, dtype: int64

TESC
False    183
Name: TESC, dtype: int64

TESK1
False    183
Name: TESK1, dtype: int64

TESK2
False    183
Name: TESK2, dtype: int64

TES
False    183
Name: TES, dtype: int64

TET1
False    183
Name: TET1, dtype: int64

TET2
False    183
Name: TET2, dtype: int64

TET3
False    183
Name: TET3, dtype: int64

TEX10
False    183
Name: TEX10, dtype: int64

TEX11
False    174
True       9
Name: TEX11, dtype: int64

TEX12
False    136
True      47
Name: TEX12, dtype: int64

TEX14
False    181
True       2
Name: TEX14, dtype: int64

TEX15
False    146
True      37
Name: TEX15, dtype: int64

TEX19
False    97
True     86
Name: TEX19, dtype: int64

TEX261
False    183
Name: TEX261, dtype: int64

TEX264
False    183
Name: TEX264, dtype: int64

TEX2
False    183
Name: TEX2, dtype: int64

TEX9
False    183
Name: TEX9, dtype: int64

TFAMP1
True     102
False     81
Name: TFAMP1, dtype: int64

TFAM
False    183
Name: TFAM, dtype: int64

TFAP2A
False    182
True       1
Name: TFAP2A, dtype: int64

TFAP2C
False    182
True       1
Name: TFAP2C, dtype: int64

TFAP2E
False    183
Name: TFAP2E, dtype: int64

TFAP4
False    183
Name: TFAP4, dtype: int64

TFB1M
False    183
Name: TFB1M, dtype: int64

TFB2M
False    183
Name: TFB2M, dtype: int64

TFCP2L1
False    183
Name: TFCP2L1, dtype: int64

TFCP2
False    183
Name: TFCP2, dtype: int64

TFDP1
False    183
Name: TFDP1, dtype: int64

TFDP2
False    183
Name: TFDP2, dtype: int64

TFE3
False    183
Name: TFE3, dtype: int64

TFEB
False    183
Name: TFEB, dtype: int64

TFEC
False    183
Name: TFEC, dtype: int64

TFF1
False    180
True       3
Name: TFF1, dtype: int64

TFF2
False    176
True       7
Name: TFF2, dtype: int64

TFF3
False    183
Name: TFF3, dtype: int64

TFG
False    183
Name: TFG, dtype: int64

TFIP11
False    183
Name: TFIP11, dtype: int64

TFPI2
False    182
True       1
Name: TFPI2, dtype: int64

TFPI
False    183
Name: TFPI, dtype: int64

TFPT
False    183
Name: TFPT, dtype: int64

TFR2
False    183
Name: TFR2, dtype: int64

TFRC
False    183
Name: TFRC, dtype: int64

TF
False    182
True       1
Name: TF, dtype: int64

TGDS
False    183
Name: TGDS, dtype: int64

TGFA
False    183
Name: TGFA, dtype: int64

TGFB1I1
False    183
Name: TGFB1I1, dtype: int64

TGFB1
False    183
Name: TGFB1, dtype: int64

TGFB2
False    183
Name: TGFB2, dtype: int64

TGFB3
False    183
Name: TGFB3, dtype: int64

TGFBI
False    183
Name: TGFBI, dtype: int64

TGFBR1
False    183
Name: TGFBR1, dtype: int64

TGFBR2
False    183
Name: TGFBR2, dtype: int64

TGFBR3
False    183
Name: TGFBR3, dtype: int64

TGFBRAP1
False    183
Name: TGFBRAP1, dtype: int64

TGIF1
False    183
Name: TGIF1, dtype: int64

TGIF2
False    183
Name: TGIF2, dtype: int64

TGM1
False    183
Name: TGM1, dtype: int64

TGM2
False    183
Name: TGM2, dtype: int64

TGM3
False    164
True      19
Name: TGM3, dtype: int64

TGM4
False    127
True      56
Name: TGM4, dtype: int64

TGM5
False    159
True      24
Name: TGM5, dtype: int64

TGOLN2
False    183
Name: TGOLN2, dtype: int64

TGS1
False    183
Name: TGS1, dtype: int64

TG
False    183
Name: TG, dtype: int64

TH1L
False    183
Name: TH1L, dtype: int64

THADA
False    183
Name: THADA, dtype: int64

THAP10
False    183
Name: THAP10, dtype: int64

THAP11
False    183
Name: THAP11, dtype: int64

THAP1
False    183
Name: THAP1, dtype: int64

THAP2
False    183
Name: THAP2, dtype: int64

THAP3
False    183
Name: THAP3, dtype: int64

THAP4
False    183
Name: THAP4, dtype: int64

THAP5
False    183
Name: THAP5, dtype: int64

THAP6
False    183
Name: THAP6, dtype: int64

THAP7
False    183
Name: THAP7, dtype: int64

THAP8
False    183
Name: THAP8, dtype: int64

THAP9
False    183
Name: THAP9, dtype: int64

THBD
False    183
Name: THBD, dtype: int64

THBS1
False    183
Name: THBS1, dtype: int64

THBS2
False    183
Name: THBS2, dtype: int64

THBS3
False    183
Name: THBS3, dtype: int64

THBS4
False    183
Name: THBS4, dtype: int64

THEM4
False    183
Name: THEM4, dtype: int64

THEM5
False    165
True      18
Name: THEM5, dtype: int64

THEMIS
False    182
True       1
Name: THEMIS, dtype: int64

THG1L
False    183
Name: THG1L, dtype: int64

THNSL1
False    183
Name: THNSL1, dtype: int64

THNSL2
False    183
Name: THNSL2, dtype: int64

THOC1
False    183
Name: THOC1, dtype: int64

THOC2
False    183
Name: THOC2, dtype: int64

THOC3
False    183
Name: THOC3, dtype: int64

THOC4
False    183
Name: THOC4, dtype: int64

THOC5
False    183
Name: THOC5, dtype: int64

THOC6
False    183
Name: THOC6, dtype: int64

THOC7
False    183
Name: THOC7, dtype: int64

THOP1

False    183
Name: THOP1, dtype: int64

THPO
False    180
True       3
Name: THPO, dtype: int64

THRAP3
False    183
Name: THRAP3, dtype: int64

THRA
False    183
Name: THRA, dtype: int64

THRB
False    183
Name: THRB, dtype: int64

THRSP
False    133
True      50
Name: THRSP, dtype: int64

THSD1P1
False    183
Name: THSD1P1, dtype: int64

THSD1
False    183
Name: THSD1, dtype: int64

THSD4
False    183
Name: THSD4, dtype: int64

THSD7A
False    183
Name: THSD7A, dtype: int64

THSD7B
False    181
True       2
Name: THSD7B, dtype: int64

THTPA
False    183
Name: THTPA, dtype: int64

THUMPD1
False    183
Name: THUMPD1, dtype: int64

THUMPD2
False    183
Name: THUMPD2, dtype: int64

THUMPD3
False    183
Name: THUMPD3, dtype: int64

THY1
False    183
Name: THY1, dtype: int64

THYN1
False    183
Name: THYN1, dtype: int64

TH
False    160
True      23
Name: TH, dtype: int64

TIA1
False    183
Name: TIA1, dtype: int64

TIAF1
False    183
Name: TIAF1, dtype: int64

TIAL1
False    183
Name: TIAL1, dtype: int64

TIAM1
False    183
Name: TIAM1, dtype: int64

TIAM2
False    183
Name: TIAM2, dtype: int64

TICAM1
False    183
Name: TICAM1, dtype: int64

TICAM2
False    183
Name: TICAM2, dtype: int64

TIE1
False    183
Name: TIE1, dtype: int64

TIFAB
False    172
True      11
Name: TIFAB, dtype: int64

TIFA
False    183
Name: TIFA, dtype: int64

TIGD1
False    183
Name: TIGD1, dtype: int64

TIGD2
False    183
Name: TIGD2, dtype: int64

TIGD3
False    183
Name: TIGD3, dtype: int64

TIGD4
False    182
True       1
Name: TIGD4, dtype: int64

TIGD5
False    183
Name: TIGD5, dtype: int64

TIGD6
False    183
Name: TIGD6, dtype: int64

TIGD7
False    183
Name: TIGD7, dtype: int64

TIGIT
False    183
Name: TIGIT, dtype: int64

TIMD4
False    170
True      13
Name: TIMD4, dtype: int64

TIMELESS
False    183
Name: TIMELESS, dtype: int64

TIMM10
False    183
Name: TIMM10, dtype: int64

TIMM13
False    183
Name: TIMM13, dtype: int64

TIMM16
False    183
Name: TIMM16, dtype: int64

TIMM17A
False    183
Name: TIMM17A, dtype: int64

TIMM17B
False    183
Name: TIMM17B, dtype: int64

TIMM22
False    183
Name: TIMM22, dtype: int64

TIMM44
False    183
Name: TIMM44, dtype: int64

TIMM50
False    183
Name: TIMM50, dtype: int64

TIMM8A
False    183
Name: TIMM8A, dtype: int64

TIMM8B
False    183
Name: TIMM8B, dtype: int64

TIMM9
False    183
Name: TIMM9, dtype: int64

TIMP1
False    183
Name: TIMP1, dtype: int64

TIMP2
False    183
Name: TIMP2, dtype: int64

TIMP3
False    183
Name: TIMP3, dtype: int64

TIMP4
False    183
Name: TIMP4, dtype: int64

TINAGL1
False    183
Name: TINAGL1, dtype: int64

TINAG
False    161
True      22
Name: TINAG, dtype: int64

TINF2
False    183
Name: TINF2, dtype: int64

TIPARP
False    183
Name: TIPARP, dtype: int64

TIPIN
False    183
Name: TIPIN, dtype: int64

TIPRL
False    183
Name: TIPRL, dtype: int64

TIRAP
False    183
Name: TIRAP, dtype: int64

TJAP1
False    183
Name: TJAP1, dtype: int64

TJP1
False    183
Name: TJP1, dtype: int64

TJP2
False    183
Name: TJP2, dtype: int64

TJP3
False    183
Name: TJP3, dtype: int64

TK1
False    183
Name: TK1, dtype: int64

TK2
False    183
Name: TK2, dtype: int64

TKTL1
False    155
True      28
Name: TKTL1, dtype: int64

TKTL2
False    100
True      83
Name: TKTL2, dtype: int64

TKT
False    183
Name: TKT, dtype: int64

TLCD1
False    183
Name: TLCD1, dtype: int64

TLE1
False    183
Name: TLE1, dtype: int64

TLE2
False    183
Name: TLE2, dtype: int64

TLE3
False    183
Name: TLE3, dtype: int64

TLE4
False    183
Name: TLE4, dtype: int64

TLE6
False    183
Name: TLE6, dtype: int64

TLK1
False    183
Name: TLK1, dtype: int64

TLK2
False    183
Name: TLK2, dtype: int64

TLL1
False    183
Name: TLL1, dtype: int64

TLL2
False    183
Name: TLL2, dtype: int64

TLN1
False    183
Name: TLN1, dtype: int64

TLN2
False    183
Name: TLN2, dtype: int64

TLR10
False    182
True       1
Name: TLR10, dtype: int64

TLR1
False    183
Name: TLR1, dtype: int64

TLR2
False    183
Name: TLR2, dtype: int64

TLR3
False    183
Name: TLR3, dtype: int64

TLR4
False    183
Name: TLR4, dtype: int64

TLR5
False    183
Name: TLR5, dtype: int64

TLR6
False    183
Name: TLR6, dtype: int64

TLR7
False    183
Name: TLR7, dtype: int64

TLR8
False    183
Name: TLR8, dtype: int64

TLR9
False    183
Name: TLR9, dtype: int64

TLX1NB
True     99
False    84
Name: TLX1NB, dtype: int64

TLX1
False    170
True      13
Name: TLX1, dtype: int64

TLX2
False    148
True      35
Name: TLX2, dtype: int64

TM2D1
False    183
Name: TM2D1, dtype: int64

TM2D2
False    183
Name: TM2D2, dtype: int64

TM2D3
False    183
Name: TM2D3, dtype: int64

TM4SF18
False    183
Name: TM4SF18, dtype: int64

TM4SF19
False    181
True       2
Name: TM4SF19, dtype: int64

TM4SF1
False    183
Name: TM4SF1, dtype: int64

TM4SF20
False    169
True      14
Name: TM4SF20, dtype: int64

TM4SF4
False    183
Name: TM4SF4, dtype: int64

TM4SF5
False    179
True       4
Name: TM4SF5, dtype: int64

TM6SF1
False    183
Name: TM6SF1, dtype: int64

TM6SF2
False    181
True       2
Name: TM6SF2, dtype: int64

TM7SF2
False    183
Name: TM7SF2, dtype: int64

TM7SF3
False    183
Name: TM7SF3, dtype: int64

TM7SF4
False    182
True       1
Name: TM7SF4, dtype: int64

TM9SF1
False    183
Name: TM9SF1, dtype: int64

TM9SF2
False    183
Name: TM9SF2, dtype: int64

TM9SF3
False    183
Name: TM9SF3, dtype: int64

TM9SF4
False    183
Name: TM9SF4, dtype: int64

TMBIM1
False    183
Name: TMBIM1, dtype: int64

TMBIM4
False    183
Name: TMBIM4, dtype: int64

TMBIM6
False    183
Name: TMBIM6, dtype: int64

TMC1
False    114
True      69
Name: TMC1, dtype: int64

TMC2
False    165
True      18
Name: TMC2, dtype: int64

TMC3
False    143
True      40
Name: TMC3, dtype: int64

TMC4
False    183
Name: TMC4, dtype: int64

TMC5
False    183
Name: TMC5, dtype: int64

TMC6
False    183
Name: TMC6, dtype: int64

TMC7
False    183
Name: TMC7, dtype: int64

TMC8
False    183
Name: TMC8, dtype: int64

TMCC1
False    183
Name: TMCC1, dtype: int64

TMCC2
False    183
Name: TMCC2, dtype: int64

TMCC3
False    183
Name: TMCC3, dtype: int64

TMCO1
False    183
Name: TMCO1, dtype: int64

TMCO3
False    183
Name: TMCO3, dtype: int64

TMCO4
False    183
Name: TMCO4, dtype: int64

TMCO5A
True     117
False     66
Name: TMCO5A, dtype: int64

TMCO6
False    183
Name: TMCO6, dtype: int64

TMCO7
False    183
Name: TMCO7, dtype: int64

TMED10P1
False    183
Name: TMED10P1, dtype: int64

TMED10
False    183
Name: TMED10, dtype: int64

TMED1
False    183
Name: TMED1, dtype: int64

TMED2
False    183
Name: TMED2, dtype: int64

TMED3
False    183
Name: TMED3, dtype: int64

TMED4
False    183
Name: TMED4, dtype: int64

TMED5
False    183
Name: TMED5, dtype: int64

TMED6
False    183
Name: TMED6, dtype: int64

TMED7-TICAM2
False    176
True       7
Name: TMED7-TICAM2, dtype: int64

TMED7
False    183
Name: TMED7, dtype: int64

TMED8
False    183
Name: TMED8, dtype: int64

TMED9
False    183
Name: TMED9, dtype: int64

TMEFF1
False    183
Name: TMEFF1, dtype: int64

TMEFF2
False    160
True      23
Name: TMEFF2, dtype: int64

TMEM100
False    183
Name: TMEM100, dtype: int64

TMEM101
False    183
Name: TMEM101, dtype: int64

TMEM102
False    183
Name: TMEM102, dtype: int64

TMEM104
False    183
Name: TMEM104, dtype: int64

TMEM105
False    177
True       6
Name: TMEM105, dtype: int64

TMEM106A
False    183
Name: TMEM106A, dtype: int64

TMEM106B
False    183
Name: TMEM106B, dtype: int64

TMEM106C
False    183
Name: TMEM106C, dtype: int64

TMEM107
False    183
Name: TMEM107, dtype: int64

TMEM108
False    183
Name: TMEM108, dtype: int64

TMEM109
False    183
Name: TMEM109, dtype: int64

TMEM110
False    183
Name: TMEM110, dtype: int64

TMEM111
False    183
Name: TMEM111, dtype: int64

TMEM114
False    125
True      58
Name: TMEM114, dtype: int64

TMEM115
False    183
Name: TMEM115, dtype: int64

TMEM116
False    183
Name: TMEM116, dtype: int64

TMEM117
False    183
Name: TMEM117, dtype: int64

TMEM119
False    183
Name: TMEM119, dtype: int64

TMEM11
False    183
Name: TMEM11, dtype: int64

TMEM120A
False    183
Name: TMEM120A, dtype: int64

TMEM120B
False    183
Name: TMEM120B, dtype: int64

TMEM121
False    183
Name: TMEM121, dtype: int64

TMEM123
False    183
Name: TMEM123, dtype: int64

TMEM125
False    183
Name: TMEM125, dtype: int64

TMEM126A
False    183
Name: TMEM126A, dtype: int64

TMEM126B
False    183
Name: TMEM126B, dtype: int64

TMEM127
False    183
Name: TMEM127, dtype: int64

TMEM128
False    183
Name: TMEM128, dtype: int64

TMEM129

False    183
Name: TMEM129, dtype: int64

TMEM130
False    182
True       1
Name: TMEM130, dtype: int64

TMEM131
False    183
Name: TMEM131, dtype: int64

TMEM132A
False    183
Name: TMEM132A, dtype: int64

TMEM132B
False    183
Name: TMEM132B, dtype: int64

TMEM132C
False    182
True       1
Name: TMEM132C, dtype: int64

TMEM132D
False    174
True       9
Name: TMEM132D, dtype: int64

TMEM132E
False    183
Name: TMEM132E, dtype: int64

TMEM133
False    183
Name: TMEM133, dtype: int64

TMEM134
False    183
Name: TMEM134, dtype: int64

TMEM135
False    183
Name: TMEM135, dtype: int64

TMEM136
False    183
Name: TMEM136, dtype: int64

TMEM138
False    183
Name: TMEM138, dtype: int64

TMEM139
False    183
Name: TMEM139, dtype: int64

TMEM140
False    183
Name: TMEM140, dtype: int64

TMEM141
False    183
Name: TMEM141, dtype: int64

TMEM143
False    183
Name: TMEM143, dtype: int64

TMEM144
False    183
Name: TMEM144, dtype: int64

TMEM145
False    181
True       2
Name: TMEM145, dtype: int64

TMEM147
False    183
Name: TMEM147, dtype: int64

TMEM149
False    183
Name: TMEM149, dtype: int64

TMEM14A
False    183
Name: TMEM14A, dtype: int64

TMEM14B
False    183
Name: TMEM14B, dtype: int64

TMEM14C
False    183
Name: TMEM14C, dtype: int64

TMEM14E
False    100
True      83
Name: TMEM14E, dtype: int64

TMEM150A
False    183
Name: TMEM150A, dtype: int64

TMEM150B
False    182
True       1
Name: TMEM150B, dtype: int64

TMEM150C
False    183
Name: TMEM150C, dtype: int64

TMEM151A
False    182
True       1
Name: TMEM151A, dtype: int64

TMEM151B
False    183
Name: TMEM151B, dtype: int64

TMEM154
False    183
Name: TMEM154, dtype: int64

TMEM155
False    157
True      26
Name: TMEM155, dtype: int64

TMEM156
False    183
Name: TMEM156, dtype: int64

TMEM158
False    183
Name: TMEM158, dtype: int64

TMEM159
False    183
Name: TMEM159, dtype: int64

TMEM160
False    183
Name: TMEM160, dtype: int64

TMEM161A
False    183
Name: TMEM161A, dtype: int64

TMEM161B
False    183
Name: TMEM161B, dtype: int64

TMEM163
False    183
Name: TMEM163, dtype: int64

TMEM164
False    183
Name: TMEM164, dtype: int64

TMEM165
False    183
Name: TMEM165, dtype: int64

TMEM167A
False    183
Name: TMEM167A, dtype: int64

TMEM167B
False    183
Name: TMEM167B, dtype: int64

TMEM168
False    183
Name: TMEM168, dtype: int64

TMEM169
False    183
Name: TMEM169, dtype: int64

TMEM170A
False    183
Name: TMEM170A, dtype: int64

TMEM170B
False    183
Name: TMEM170B, dtype: int64

TMEM171
False    181
True       2
Name: TMEM171, dtype: int64

TMEM173
False    183
Name: TMEM173, dtype: int64

TMEM175
False    183
Name: TMEM175, dtype: int64

TMEM176A
False    183
Name: TMEM176A, dtype: int64

TMEM176B
False    183
Name: TMEM176B, dtype: int64

TMEM177
False    183
Name: TMEM177, dtype: int64

TMEM178
False    183
Name: TMEM178, dtype: int64

TMEM179B
False    183
Name: TMEM179B, dtype: int64

TMEM179
False    153
True      30
Name: TMEM179, dtype: int64

TMEM17
False    183
Name: TMEM17, dtype: int64

TMEM180
False    183
Name: TMEM180, dtype: int64

TMEM181
False    183
Name: TMEM181, dtype: int64

TMEM182
False    183
Name: TMEM182, dtype: int64

TMEM183A
False    183
Name: TMEM183A, dtype: int64

TMEM184A
False    183
Name: TMEM184A, dtype: int64

TMEM184B
False    183
Name: TMEM184B, dtype: int64

TMEM184C
False    183
Name: TMEM184C, dtype: int64

TMEM185A
False    183
Name: TMEM185A, dtype: int64

TMEM185B
False    183
Name: TMEM185B, dtype: int64

TMEM186
False    183
Name: TMEM186, dtype: int64

TMEM187
False    183
Name: TMEM187, dtype: int64

TMEM188
False    183
Name: TMEM188, dtype: int64

TMEM189-UBE2V1
True     119
False     64
Name: TMEM189-UBE2V1, dtype: int64

TMEM189
False    183
Name: TMEM189, dtype: int64

TMEM18
False    183
Name: TMEM18, dtype: int64

TMEM190
False    150
True      33
Name: TMEM190, dtype: int64

TMEM191A
False    183
Name: TMEM191A, dtype: int64

TMEM192
False    183
Name: TMEM192, dtype: int64

TMEM194A
False    183
Name: TMEM194A, dtype: int64

TMEM194B
False    183
Name: TMEM194B, dtype: int64

TMEM195
False    175
True       8
Name: TMEM195, dtype: int64

TMEM196
False    165
True      18
Name: TMEM196, dtype: int64

TMEM198
False    183
Name: TMEM198, dtype: int64

TMEM199
False    183
Name: TMEM199, dtype: int64

TMEM19
False    183
Name: TMEM19, dtype: int64

TMEM200A
False    183
Name: TMEM200A, dtype: int64

TMEM200B
False    183
Name: TMEM200B, dtype: int64

TMEM200C
False    183
Name: TMEM200C, dtype: int64

TMEM201
False    183
Name: TMEM201, dtype: int64

TMEM203
False    183
Name: TMEM203, dtype: int64

TMEM204
False    183
Name: TMEM204, dtype: int64

TMEM205
False    183
Name: TMEM205, dtype: int64

TMEM206
False    183
Name: TMEM206, dtype: int64

TMEM208
False    183
Name: TMEM208, dtype: int64

TMEM209
False    183
Name: TMEM209, dtype: int64

TMEM20
False    183
Name: TMEM20, dtype: int64

TMEM211
False    125
True      58
Name: TMEM211, dtype: int64

TMEM212
True     125
False     58
Name: TMEM212, dtype: int64

TMEM213
False    166
True      17
Name: TMEM213, dtype: int64

TMEM214
False    183
Name: TMEM214, dtype: int64

TMEM215
False    157
True      26
Name: TMEM215, dtype: int64

TMEM216
False    183
Name: TMEM216, dtype: int64

TMEM217
False    183
Name: TMEM217, dtype: int64

TMEM218
False    183
Name: TMEM218, dtype: int64

TMEM219
False    183
Name: TMEM219, dtype: int64

TMEM220
False    183
Name: TMEM220, dtype: int64

TMEM222
False    183
Name: TMEM222, dtype: int64

TMEM223
False    183
Name: TMEM223, dtype: int64

TMEM229A
False    162
True      21
Name: TMEM229A, dtype: int64

TMEM229B
False    183
Name: TMEM229B, dtype: int64

TMEM22
False    183
Name: TMEM22, dtype: int64

TMEM231
False    183
Name: TMEM231, dtype: int64

TMEM232
False    182
True       1
Name: TMEM232, dtype: int64

TMEM233
False    182
True       1
Name: TMEM233, dtype: int64

TMEM25
False    183
Name: TMEM25, dtype: int64

TMEM26
False    183
Name: TMEM26, dtype: int64

TMEM27
False    183
Name: TMEM27, dtype: int64

TMEM2
False    183
Name: TMEM2, dtype: int64

TMEM30A
False    183
Name: TMEM30A, dtype: int64

TMEM30B
False    183
Name: TMEM30B, dtype: int64

TMEM31
False    142
True      41
Name: TMEM31, dtype: int64

TMEM33
False    183
Name: TMEM33, dtype: int64

TMEM35
False    182
True       1
Name: TMEM35, dtype: int64

TMEM37
False    183
Name: TMEM37, dtype: int64

TMEM38A
False    183
Name: TMEM38A, dtype: int64

TMEM38B
False    183
Name: TMEM38B, dtype: int64

TMEM39A
False    183
Name: TMEM39A, dtype: int64

TMEM39B
False    183
Name: TMEM39B, dtype: int64

TMEM40
False    161
True      22
Name: TMEM40, dtype: int64

TMEM41A
False    183
Name: TMEM41A, dtype: int64

TMEM41B
False    183
Name: TMEM41B, dtype: int64

TMEM42
False    183
Name: TMEM42, dtype: int64

TMEM43
False    183
Name: TMEM43, dtype: int64

TMEM44
False    183
Name: TMEM44, dtype: int64

TMEM45A
False    183
Name: TMEM45A, dtype: int64

TMEM45B
False    183
Name: TMEM45B, dtype: int64

TMEM47
False    183
Name: TMEM47, dtype: int64

TMEM48
False    183
Name: TMEM48, dtype: int64

TMEM49
False    183
Name: TMEM49, dtype: int64

TMEM50A
False    183
Name: TMEM50A, dtype: int64

TMEM50B
False    183
Name: TMEM50B, dtype: int64

TMEM51
False    183
Name: TMEM51, dtype: int64

TMEM52
False    183
Name: TMEM52, dtype: int64

TMEM53
False    183
Name: TMEM53, dtype: int64

TMEM54
False    183
Name: TMEM54, dtype: int64

TMEM55A
False    183
Name: TMEM55A, dtype: int64

TMEM55B
False    183
Name: TMEM55B, dtype: int64

TMEM56
False    183
Name: TMEM56, dtype: int64

TMEM57
False    183
Name: TMEM57, dtype: int64

TMEM59L
False    183
Name: TMEM59L, dtype: int64

TMEM59
False    183
Name: TMEM59, dtype: int64

TMEM5
False    183
Name: TMEM5, dtype: int64

TMEM60
False    183
Name: TMEM60, dtype: int64

TMEM61
False    183
Name: TMEM61, dtype: int64

TMEM62
False    183
Name: TMEM62, dtype: int64

TMEM63A
False    183
Name: TMEM63A, dtype: int64

TMEM63B
False    183
Name: TMEM63B, dtype: int64

TMEM63C
False    182
True       1
Name: TMEM63C, dtype: int64

TMEM64
False    183
Name: TMEM64, dtype: int64

TMEM65
False    183
Name: TMEM65, dtype: int64

TMEM66
False    183
Name: TMEM66, dtype: int64

TMEM67
False    183
Name: TMEM67, dtype: int64

TMEM68
False    183
Name: TMEM68, dtype: int64

TMEM69
False    183
Name: TMEM69, dtype: int64

TMEM70
False    183
Name: TMEM70, dtype: int64

TMEM71
False    183
Name: TMEM71, dtype: int64

TMEM72
False    124
True      59
Name: TMEM72, dtype: int64

TMEM74
False    169
True      14
Name: TMEM74, dtype: int64

TMEM79
False    183
Name: TMEM79, dtype: int64

TMEM80

False    183
Name: TMEM80, dtype: int64

TMEM81
False    183
Name: TMEM81, dtype: int64

TMEM82
False    156
True      27
Name: TMEM82, dtype: int64

TMEM84
False    164
True      19
Name: TMEM84, dtype: int64

TMEM85
False    183
Name: TMEM85, dtype: int64

TMEM86A
False    183
Name: TMEM86A, dtype: int64

TMEM86B
False    183
Name: TMEM86B, dtype: int64

TMEM87A
False    183
Name: TMEM87A, dtype: int64

TMEM87B
False    183
Name: TMEM87B, dtype: int64

TMEM88
False    183
Name: TMEM88, dtype: int64

TMEM89
True     120
False     63
Name: TMEM89, dtype: int64

TMEM8A
False    183
Name: TMEM8A, dtype: int64

TMEM8B
False    183
Name: TMEM8B, dtype: int64

TMEM90A
False    176
True       7
Name: TMEM90A, dtype: int64

TMEM90B
False    183
Name: TMEM90B, dtype: int64

TMEM91
False    183
Name: TMEM91, dtype: int64

TMEM92
False    182
True       1
Name: TMEM92, dtype: int64

TMEM93
False    183
Name: TMEM93, dtype: int64

TMEM97
False    183
Name: TMEM97, dtype: int64

TMEM98
False    183
Name: TMEM98, dtype: int64

TMEM99
False    183
Name: TMEM99, dtype: int64

TMEM9B
False    183
Name: TMEM9B, dtype: int64

TMEM9
False    183
Name: TMEM9, dtype: int64

TMF1
False    183
Name: TMF1, dtype: int64

TMIE
False    181
True       2
Name: TMIE, dtype: int64

TMIGD2
False    181
True       2
Name: TMIGD2, dtype: int64

TMLHE
False    183
Name: TMLHE, dtype: int64

TMOD1
False    183
Name: TMOD1, dtype: int64

TMOD2
False    183
Name: TMOD2, dtype: int64

TMOD3
False    183
Name: TMOD3, dtype: int64

TMOD4
False    167
True      16
Name: TMOD4, dtype: int64

TMPO
False    183
Name: TMPO, dtype: int64

TMPPE
False    183
Name: TMPPE, dtype: int64

TMPRSS11D
False    106
True      77
Name: TMPRSS11D, dtype: int64

TMPRSS12
True     124
False     59
Name: TMPRSS12, dtype: int64

TMPRSS13
False    183
Name: TMPRSS13, dtype: int64

TMPRSS15
False    104
True      79
Name: TMPRSS15, dtype: int64

TMPRSS2
False    182
True       1
Name: TMPRSS2, dtype: int64

TMPRSS3
False    182
True       1
Name: TMPRSS3, dtype: int64

TMPRSS4
False    180
True       3
Name: TMPRSS4, dtype: int64

TMPRSS5
False    183
Name: TMPRSS5, dtype: int64

TMPRSS6
False    182
True       1
Name: TMPRSS6, dtype: int64

TMPRSS7
False    144
True      39
Name: TMPRSS7, dtype: int64

TMPRSS9
False    166
True      17
Name: TMPRSS9, dtype: int64

TMSB10
False    183
Name: TMSB10, dtype: int64

TMSB15A
False    183
Name: TMSB15A, dtype: int64

TMSB15B
False    182
True       1
Name: TMSB15B, dtype: int64

TMSB4Y
False    110
True      73
Name: TMSB4Y, dtype: int64

TMSL3
False    183
Name: TMSL3, dtype: int64

TMTC1
False    183
Name: TMTC1, dtype: int64

TMTC2
False    183
Name: TMTC2, dtype: int64

TMTC3
False    183
Name: TMTC3, dtype: int64

TMTC4
False    183
Name: TMTC4, dtype: int64

TMUB1
False    183
Name: TMUB1, dtype: int64

TMUB2
False    183
Name: TMUB2, dtype: int64

TMX1
False    183
Name: TMX1, dtype: int64

TMX2
False    183
Name: TMX2, dtype: int64

TMX3
False    183
Name: TMX3, dtype: int64

TMX4
False    183
Name: TMX4, dtype: int64

TNC
False    183
Name: TNC, dtype: int64

TNFAIP1
False    183
Name: TNFAIP1, dtype: int64

TNFAIP2
False    183
Name: TNFAIP2, dtype: int64

TNFAIP3
False    183
Name: TNFAIP3, dtype: int64

TNFAIP6
False    182
True       1
Name: TNFAIP6, dtype: int64

TNFAIP8L1
False    183
Name: TNFAIP8L1, dtype: int64

TNFAIP8L2
False    183
Name: TNFAIP8L2, dtype: int64

TNFAIP8L3
False    183
Name: TNFAIP8L3, dtype: int64

TNFAIP8
False    183
Name: TNFAIP8, dtype: int64

TNFRSF10A
False    183
Name: TNFRSF10A, dtype: int64

TNFRSF10B
False    183
Name: TNFRSF10B, dtype: int64

TNFRSF10C
False    183
Name: TNFRSF10C, dtype: int64

TNFRSF10D
False    183
Name: TNFRSF10D, dtype: int64

TNFRSF11A
False    183
Name: TNFRSF11A, dtype: int64

TNFRSF11B
False    183
Name: TNFRSF11B, dtype: int64

TNFRSF12A
False    183
Name: TNFRSF12A, dtype: int64

TNFRSF13B
False    166
True      17
Name: TNFRSF13B, dtype: int64

TNFRSF13C
False    175
True       8
Name: TNFRSF13C, dtype: int64

TNFRSF14
False    183
Name: TNFRSF14, dtype: int64

TNFRSF17
False    172
True      11
Name: TNFRSF17, dtype: int64

TNFRSF18
False    183
Name: TNFRSF18, dtype: int64

TNFRSF19
False    183
Name: TNFRSF19, dtype: int64

TNFRSF1A
False    183
Name: TNFRSF1A, dtype: int64

TNFRSF1B
False    183
Name: TNFRSF1B, dtype: int64

TNFRSF21
False    183
Name: TNFRSF21, dtype: int64

TNFRSF25
False    183
Name: TNFRSF25, dtype: int64

TNFRSF4
False    183
Name: TNFRSF4, dtype: int64

TNFRSF6B
False    183
Name: TNFRSF6B, dtype: int64

TNFRSF8
False    183
Name: TNFRSF8, dtype: int64

TNFRSF9
False    180
True       3
Name: TNFRSF9, dtype: int64

TNFSF10
False    183
Name: TNFSF10, dtype: int64

TNFSF11
False    182
True       1
Name: TNFSF11, dtype: int64

TNFSF12-TNFSF13
False    180
True       3
Name: TNFSF12-TNFSF13, dtype: int64

TNFSF12
False    183
Name: TNFSF12, dtype: int64

TNFSF13B
False    183
Name: TNFSF13B, dtype: int64

TNFSF13
False    183
Name: TNFSF13, dtype: int64

TNFSF14
False    177
True       6
Name: TNFSF14, dtype: int64

TNFSF15
False    179
True       4
Name: TNFSF15, dtype: int64

TNFSF18
False    162
True      21
Name: TNFSF18, dtype: int64

TNFSF4
False    183
Name: TNFSF4, dtype: int64

TNFSF8
False    183
Name: TNFSF8, dtype: int64

TNFSF9
False    183
Name: TNFSF9, dtype: int64

TNF
False    182
True       1
Name: TNF, dtype: int64

TNIK
False    183
Name: TNIK, dtype: int64

TNIP1
False    183
Name: TNIP1, dtype: int64

TNIP2
False    183
Name: TNIP2, dtype: int64

TNIP3
False    177
True       6
Name: TNIP3, dtype: int64

TNK1
False    183
Name: TNK1, dtype: int64

TNK2
False    183
Name: TNK2, dtype: int64

TNKS1BP1
False    183
Name: TNKS1BP1, dtype: int64

TNKS2
False    183
Name: TNKS2, dtype: int64

TNKS
False    183
Name: TNKS, dtype: int64

TNMD
False    106
True      77
Name: TNMD, dtype: int64

TNNC1
False    183
Name: TNNC1, dtype: int64

TNNC2
False    182
True       1
Name: TNNC2, dtype: int64

TNNI1
False    183
Name: TNNI1, dtype: int64

TNNI2
False    179
True       4
Name: TNNI2, dtype: int64

TNNI3K
False    183
Name: TNNI3K, dtype: int64

TNNI3
False    155
True      28
Name: TNNI3, dtype: int64

TNNT1
False    176
True       7
Name: TNNT1, dtype: int64

TNNT2
False    176
True       7
Name: TNNT2, dtype: int64

TNNT3
False    159
True      24
Name: TNNT3, dtype: int64

TNN
False    183
Name: TNN, dtype: int64

TNPO1
False    183
Name: TNPO1, dtype: int64

TNPO2
False    183
Name: TNPO2, dtype: int64

TNPO3
False    183
Name: TNPO3, dtype: int64

TNRC18
False    183
Name: TNRC18, dtype: int64

TNRC6A
False    183
Name: TNRC6A, dtype: int64

TNRC6B
False    183
Name: TNRC6B, dtype: int64

TNRC6C
False    183
Name: TNRC6C, dtype: int64

TNR
False    157
True      26
Name: TNR, dtype: int64

TNS1
False    183
Name: TNS1, dtype: int64

TNS3
False    183
Name: TNS3, dtype: int64

TNS4
False    179
True       4
Name: TNS4, dtype: int64

TNXB
False    183
Name: TNXB, dtype: int64

TOB1
False    183
Name: TOB1, dtype: int64

TOB2
False    183
Name: TOB2, dtype: int64

TOE1
False    183
Name: TOE1, dtype: int64

TOLLIP
False    183
Name: TOLLIP, dtype: int64

TOM1L1
False    183
Name: TOM1L1, dtype: int64

TOM1L2
False    183
Name: TOM1L2, dtype: int64

TOM1
False    183
Name: TOM1, dtype: int64

TOMM20L
False    161
True      22
Name: TOMM20L, dtype: int64

TOMM20
False    183
Name: TOMM20, dtype: int64

TOMM22
False    183
Name: TOMM22, dtype: int64

TOMM34
False    183
Name: TOMM34, dtype: int64

TOMM40L
False    183
Name: TOMM40L, dtype: int64

TOMM40
False    183
Name: TOMM40, dtype: int64

TOMM5
False    183
Name: TOMM5, dtype: int64

TOMM6
False    183
Name: TOMM6, dtype: int64

TOMM70A
False    183
Name: TOMM70A, dtype: int64

TOMM7
False    183
Name: TOMM7, dtype: int64

TOP1MT
False    183
Name: TOP1MT, dtype: int64

TOP1P1
False    183
Name: TOP1P1, dtype: int64

TOP1P2
False    183
Name: TOP1P2, dtype: int64

TOP1
False    183
Name: TOP1, dtype: int64

TOP2A
False    183
Name: TOP2A, dtype: int64

TOP2B
False    183
Name: TOP2B, dtype: int64

TOP3A
False    183
Name: TOP3A, dtype: int64

TOP3B
False    183
Name: TOP3B, dtype: int64

TOPBP1
False    183
Name: TOPBP1, dtype: int64

TOPORS
False    183
Name: TOPORS, dtype: int64

TOR1AIP1
False    183
Name: TOR1AIP1, dtype: int64

TOR1AIP2
False    183
Name: TOR1AIP2, dtype: int64

TOR1A
False    183
Name: TOR1A, dtype: int64

TOR1B
False    183
Name: TOR1B, dtype: int64

TOR2A
False    183
Name: TOR2A, dtype: int64

TOR3A
False    183
Name: TOR3A, dtype: int64

TOX2
False    183
Name: TOX2, dtype: int64

TOX3
False    183
Name: TOX3, dtype: int64

TOX4

False    183
Name: TOX4, dtype: int64

TOX
False    183
Name: TOX, dtype: int64

TP53AIP1
False    175
True       8
Name: TP53AIP1, dtype: int64

TP53BP1
False    183
Name: TP53BP1, dtype: int64

TP53BP2
False    183
Name: TP53BP2, dtype: int64

TP53I11
False    183
Name: TP53I11, dtype: int64

TP53I13
False    183
Name: TP53I13, dtype: int64

TP53I3
False    183
Name: TP53I3, dtype: int64

TP53INP1
False    183
Name: TP53INP1, dtype: int64

TP53INP2
False    183
Name: TP53INP2, dtype: int64

TP53RK
False    183
Name: TP53RK, dtype: int64

TP53TG1
False    183
Name: TP53TG1, dtype: int64

TP53TG3B
False    127
True      56
Name: TP53TG3B, dtype: int64

TP53
False    183
Name: TP53, dtype: int64

TP63
False    183
Name: TP63, dtype: int64

TP73
False    183
Name: TP73, dtype: int64

TPBG
False    183
Name: TPBG, dtype: int64

TPCN1
False    183
Name: TPCN1, dtype: int64

TPCN2
False    183
Name: TPCN2, dtype: int64

TPD52L1
False    183
Name: TPD52L1, dtype: int64

TPD52L2
False    183
Name: TPD52L2, dtype: int64

TPD52
False    183
Name: TPD52, dtype: int64

TPH1
False    154
True      29
Name: TPH1, dtype: int64

TPH2
True     95
False    88
Name: TPH2, dtype: int64

TPI1P2
False    183
Name: TPI1P2, dtype: int64

TPI1P3
False    102
True      81
Name: TPI1P3, dtype: int64

TPI1
False    183
Name: TPI1, dtype: int64

TPK1
False    183
Name: TPK1, dtype: int64

TPM1
False    183
Name: TPM1, dtype: int64

TPM2
False    183
Name: TPM2, dtype: int64

TPM3
False    183
Name: TPM3, dtype: int64

TPM4
False    183
Name: TPM4, dtype: int64

TPMT
False    183
Name: TPMT, dtype: int64

TPO
False    156
True      27
Name: TPO, dtype: int64

TPP1
False    183
Name: TPP1, dtype: int64

TPP2
False    183
Name: TPP2, dtype: int64

TPPP3
False    183
Name: TPPP3, dtype: int64

TPPP
False    183
Name: TPPP, dtype: int64

TPRA1
False    183
Name: TPRA1, dtype: int64

TPRG1L
False    183
Name: TPRG1L, dtype: int64

TPRG1
False    183
Name: TPRG1, dtype: int64

TPRKB
False    183
Name: TPRKB, dtype: int64

TPRN
False    183
Name: TPRN, dtype: int64

TPRXL
False    180
True       3
Name: TPRXL, dtype: int64

TPR
False    183
Name: TPR, dtype: int64

TPSAB1
False    183
Name: TPSAB1, dtype: int64

TPSB2
False    183
Name: TPSB2, dtype: int64

TPSD1
False    166
True      17
Name: TPSD1, dtype: int64

TPSG1
False    179
True       4
Name: TPSG1, dtype: int64

TPST1
False    183
Name: TPST1, dtype: int64

TPST2
False    183
Name: TPST2, dtype: int64

TPT1
False    183
Name: TPT1, dtype: int64

TPTE2P1
False    183
Name: TPTE2P1, dtype: int64

TPTE2P3
True     114
False     69
Name: TPTE2P3, dtype: int64

TPTE2
False    126
True      57
Name: TPTE2, dtype: int64

TPTE
False    123
True      60
Name: TPTE, dtype: int64

TPX2
False    183
Name: TPX2, dtype: int64

TRA2A
False    183
Name: TRA2A, dtype: int64

TRA2B
False    183
Name: TRA2B, dtype: int64

TRABD
False    183
Name: TRABD, dtype: int64

TRADD
False    183
Name: TRADD, dtype: int64

TRAF1
False    183
Name: TRAF1, dtype: int64

TRAF2
False    183
Name: TRAF2, dtype: int64

TRAF3IP1
False    183
Name: TRAF3IP1, dtype: int64

TRAF3IP2
False    183
Name: TRAF3IP2, dtype: int64

TRAF3IP3
False    183
Name: TRAF3IP3, dtype: int64

TRAF3
False    183
Name: TRAF3, dtype: int64

TRAF4
False    183
Name: TRAF4, dtype: int64

TRAF5
False    183
Name: TRAF5, dtype: int64

TRAF6
False    183
Name: TRAF6, dtype: int64

TRAF7
False    183
Name: TRAF7, dtype: int64

TRAFD1
False    183
Name: TRAFD1, dtype: int64

TRAIP
False    183
Name: TRAIP, dtype: int64

TRAK1
False    183
Name: TRAK1, dtype: int64

TRAK2
False    183
Name: TRAK2, dtype: int64

TRAM1L1
False    183
Name: TRAM1L1, dtype: int64

TRAM1
False    183
Name: TRAM1, dtype: int64

TRAM2
False    183
Name: TRAM2, dtype: int64

TRANK1
False    183
Name: TRANK1, dtype: int64

TRAP1
False    183
Name: TRAP1, dtype: int64

TRAPPC10
False    183
Name: TRAPPC10, dtype: int64

TRAPPC1
False    183
Name: TRAPPC1, dtype: int64

TRAPPC2L
False    183
Name: TRAPPC2L, dtype: int64

TRAPPC2P1
False    183
Name: TRAPPC2P1, dtype: int64

TRAPPC2
False    183
Name: TRAPPC2, dtype: int64

TRAPPC3
False    183
Name: TRAPPC3, dtype: int64

TRAPPC4
False    183
Name: TRAPPC4, dtype: int64

TRAPPC5
False    183
Name: TRAPPC5, dtype: int64

TRAPPC6A
False    183
Name: TRAPPC6A, dtype: int64

TRAPPC6B
False    183
Name: TRAPPC6B, dtype: int64

TRAPPC9
False    183
Name: TRAPPC9, dtype: int64

TRAT1
False    180
True       3
Name: TRAT1, dtype: int64

TRDMT1
False    183
Name: TRDMT1, dtype: int64

TRDN
True     102
False     81
Name: TRDN, dtype: int64

TREH
False    177
True       6
Name: TREH, dtype: int64

TREM1
False    181
True       2
Name: TREM1, dtype: int64

TREM2
False    183
Name: TREM2, dtype: int64

TREML1
False    170
True      13
Name: TREML1, dtype: int64

TREML2
False    180
True       3
Name: TREML2, dtype: int64

TREML3
False    164
True      19
Name: TREML3, dtype: int64

TREML4
False    102
True      81
Name: TREML4, dtype: int64

TRERF1
False    183
Name: TRERF1, dtype: int64

TREX1
False    183
Name: TREX1, dtype: int64

TREX2
False    179
True       4
Name: TREX2, dtype: int64

TRHDE
False    179
True       4
Name: TRHDE, dtype: int64

TRH
False    146
True      37
Name: TRH, dtype: int64

TRIAP1
False    183
Name: TRIAP1, dtype: int64

TRIB1
False    183
Name: TRIB1, dtype: int64

TRIB2
False    183
Name: TRIB2, dtype: int64

TRIB3
False    183
Name: TRIB3, dtype: int64

TRIL
False    183
Name: TRIL, dtype: int64

TRIM10
False    177
True       6
Name: TRIM10, dtype: int64

TRIM11
False    183
Name: TRIM11, dtype: int64

TRIM13
False    183
Name: TRIM13, dtype: int64

TRIM14
False    183
Name: TRIM14, dtype: int64

TRIM15
False    178
True       5
Name: TRIM15, dtype: int64

TRIM16L
False    183
Name: TRIM16L, dtype: int64

TRIM16
False    183
Name: TRIM16, dtype: int64

TRIM17
False    181
True       2
Name: TRIM17, dtype: int64

TRIM21
False    183
Name: TRIM21, dtype: int64

TRIM22
False    183
Name: TRIM22, dtype: int64

TRIM23
False    183
Name: TRIM23, dtype: int64

TRIM24
False    183
Name: TRIM24, dtype: int64

TRIM25
False    183
Name: TRIM25, dtype: int64

TRIM26
False    183
Name: TRIM26, dtype: int64

TRIM27
False    183
Name: TRIM27, dtype: int64

TRIM28
False    183
Name: TRIM28, dtype: int64

TRIM29
False    181
True       2
Name: TRIM29, dtype: int64

TRIM2
False    183
Name: TRIM2, dtype: int64

TRIM31
False    181
True       2
Name: TRIM31, dtype: int64

TRIM32
False    183
Name: TRIM32, dtype: int64

TRIM33
False    183
Name: TRIM33, dtype: int64

TRIM34
False    183
Name: TRIM34, dtype: int64

TRIM35
False    183
Name: TRIM35, dtype: int64

TRIM36
False    183
Name: TRIM36, dtype: int64

TRIM37
False    183
Name: TRIM37, dtype: int64

TRIM38
False    183
Name: TRIM38, dtype: int64

TRIM39
False    183
Name: TRIM39, dtype: int64

TRIM3
False    183
Name: TRIM3, dtype: int64

TRIM40
False    141
True      42
Name: TRIM40, dtype: int64

TRIM41
False    183
Name: TRIM41, dtype: int64

TRIM44
False    183
Name: TRIM44, dtype: int64

TRIM45
False    183
Name: TRIM45, dtype: int64

TRIM46
False    183
Name: TRIM46, dtype: int64

TRIM47
False    183
Name: TRIM47, dtype: int64

TRIM4
False    183
Name: TRIM4, dtype: int64

TRIM50
False    168
True      15
Name: TRIM50, dtype: int64

TRIM52
False    183
Name: TRIM52, dtype: int64

TRIM54
False    180
True       3
Name: TRIM54, dtype: int64

TRIM55
False    143
True      40
Name: TRIM55, dtype: int64

TRIM56
False    183
Name: TRIM56, dtype: int64

TRIM58
False    180
True       3
Name: TRIM58, dtype: int64

TRIM59
False    183
Name: TRIM59, dtype: int64

TRIM5
False    183
Name: TRIM5, dtype: int64

TRIM61
False    178
True       5
Name: TRIM61, dtype: int64

TRIM62
False    183
Name: TRIM62, dtype: int64

TRIM63
False    172
True      11
Name: TRIM63, dtype: int64

TRIM65
False    183
Name: TRIM65, dtype: int64

TRIM66
False    183
Name: TRIM66, dtype: int64

TRIM67
False    183
Name: TRIM67, dtype: int64

TRIM68
False    183
Name: TRIM68, dtype: int64

TRIM69
False    183
Name: TRIM69, dtype: int64

TRIM6
False    183
Name: TRIM6, dtype: int64

TRIM72
True     93
False    90
Name: TRIM72, dtype: int64

TRIM74
False    162
True      21
Name: TRIM74, dtype: int64

TRIM78P
False    179
True       4
Name: TRIM78P, dtype: int64

TRIM7
False    183
Name: TRIM7, dtype: int64

TRIM8
False    183
Name: TRIM8, dtype: int64

TRIM9
False    183
Name: TRIM9, dtype: int64

TRIML2
True     118
False     65
Name: TRIML2, dtype: int64

TRIOBP
False    183
Name: TRIOBP, dtype: int64

TRIO

False    183
Name: TRIO, dtype: int64

TRIP10
False    183
Name: TRIP10, dtype: int64

TRIP11
False    183
Name: TRIP11, dtype: int64

TRIP12
False    183
Name: TRIP12, dtype: int64

TRIP13
False    183
Name: TRIP13, dtype: int64

TRIP4
False    183
Name: TRIP4, dtype: int64

TRIP6
False    183
Name: TRIP6, dtype: int64

TRIT1
False    183
Name: TRIT1, dtype: int64

TRMT112
False    183
Name: TRMT112, dtype: int64

TRMT11
False    183
Name: TRMT11, dtype: int64

TRMT12
False    183
Name: TRMT12, dtype: int64

TRMT1
False    183
Name: TRMT1, dtype: int64

TRMT2A
False    183
Name: TRMT2A, dtype: int64

TRMT2B
False    183
Name: TRMT2B, dtype: int64

TRMT5
False    183
Name: TRMT5, dtype: int64

TRMT61A
False    183
Name: TRMT61A, dtype: int64

TRMT61B
False    183
Name: TRMT61B, dtype: int64

TRMT6
False    183
Name: TRMT6, dtype: int64

TRMU
False    183
Name: TRMU, dtype: int64

TRNAU1AP
False    183
Name: TRNAU1AP, dtype: int64

TRNP1
False    183
Name: TRNP1, dtype: int64

TRNT1
False    183
Name: TRNT1, dtype: int64

TROAP
False    183
Name: TROAP, dtype: int64

TROVE2
False    183
Name: TROVE2, dtype: int64

TRO
False    183
Name: TRO, dtype: int64

TRPA1
False    181
True       2
Name: TRPA1, dtype: int64

TRPC1
False    183
Name: TRPC1, dtype: int64

TRPC2
False    159
True      24
Name: TRPC2, dtype: int64

TRPC3
False    180
True       3
Name: TRPC3, dtype: int64

TRPC4AP
False    183
Name: TRPC4AP, dtype: int64

TRPC4
False    183
Name: TRPC4, dtype: int64

TRPC5
False    93
True     90
Name: TRPC5, dtype: int64

TRPC6
False    183
Name: TRPC6, dtype: int64

TRPM2
False    183
Name: TRPM2, dtype: int64

TRPM3
False    167
True      16
Name: TRPM3, dtype: int64

TRPM4
False    183
Name: TRPM4, dtype: int64

TRPM5
False    178
True       5
Name: TRPM5, dtype: int64

TRPM6
False    180
True       3
Name: TRPM6, dtype: int64

TRPM7
False    183
Name: TRPM7, dtype: int64

TRPM8
False    179
True       4
Name: TRPM8, dtype: int64

TRPS1
False    183
Name: TRPS1, dtype: int64

TRPT1
False    183
Name: TRPT1, dtype: int64

TRPV1
False    183
Name: TRPV1, dtype: int64

TRPV2
False    183
Name: TRPV2, dtype: int64

TRPV3
False    181
True       2
Name: TRPV3, dtype: int64

TRPV4
False    183
Name: TRPV4, dtype: int64

TRPV5
False    92
True     91
Name: TRPV5, dtype: int64

TRPV6
False    179
True       4
Name: TRPV6, dtype: int64

TRRAP
False    183
Name: TRRAP, dtype: int64

TRUB1
False    183
Name: TRUB1, dtype: int64

TRUB2
False    183
Name: TRUB2, dtype: int64

TRY6
False    178
True       5
Name: TRY6, dtype: int64

TSC1
False    183
Name: TSC1, dtype: int64

TSC22D1
False    183
Name: TSC22D1, dtype: int64

TSC22D2
False    183
Name: TSC22D2, dtype: int64

TSC22D3
False    183
Name: TSC22D3, dtype: int64

TSC22D4
False    183
Name: TSC22D4, dtype: int64

TSC2
False    183
Name: TSC2, dtype: int64

TSEN15
False    183
Name: TSEN15, dtype: int64

TSEN2
False    183
Name: TSEN2, dtype: int64

TSEN34
False    183
Name: TSEN34, dtype: int64

TSEN54
False    183
Name: TSEN54, dtype: int64

TSFM
False    183
Name: TSFM, dtype: int64

TSG101
False    183
Name: TSG101, dtype: int64

TSGA10IP
False    131
True      52
Name: TSGA10IP, dtype: int64

TSGA10
False    183
Name: TSGA10, dtype: int64

TSGA14
False    183
Name: TSGA14, dtype: int64

TSHR
False    163
True      20
Name: TSHR, dtype: int64

TSHZ1
False    183
Name: TSHZ1, dtype: int64

TSHZ2
False    183
Name: TSHZ2, dtype: int64

TSHZ3
False    183
Name: TSHZ3, dtype: int64

TSIX
False    136
True      47
Name: TSIX, dtype: int64

TSKS
False    176
True       7
Name: TSKS, dtype: int64

TSKU
False    183
Name: TSKU, dtype: int64

TSLP
False    183
Name: TSLP, dtype: int64

TSNARE1
False    183
Name: TSNARE1, dtype: int64

TSNAX-DISC1
True     120
False     63
Name: TSNAX-DISC1, dtype: int64

TSNAXIP1
False    183
Name: TSNAXIP1, dtype: int64

TSNAX
False    183
Name: TSNAX, dtype: int64

TSN
False    183
Name: TSN, dtype: int64

TSPAN10
False    182
True       1
Name: TSPAN10, dtype: int64

TSPAN11
False    183
Name: TSPAN11, dtype: int64

TSPAN12
False    183
Name: TSPAN12, dtype: int64

TSPAN13
False    183
Name: TSPAN13, dtype: int64

TSPAN14
False    183
Name: TSPAN14, dtype: int64

TSPAN15
False    183
Name: TSPAN15, dtype: int64

TSPAN17
False    183
Name: TSPAN17, dtype: int64

TSPAN18
False    183
Name: TSPAN18, dtype: int64

TSPAN19
True     124
False     59
Name: TSPAN19, dtype: int64

TSPAN1
False    183
Name: TSPAN1, dtype: int64

TSPAN2
False    183
Name: TSPAN2, dtype: int64

TSPAN31
False    183
Name: TSPAN31, dtype: int64

TSPAN32
False    182
True       1
Name: TSPAN32, dtype: int64

TSPAN33
False    183
Name: TSPAN33, dtype: int64

TSPAN3
False    183
Name: TSPAN3, dtype: int64

TSPAN4
False    183
Name: TSPAN4, dtype: int64

TSPAN5
False    183
Name: TSPAN5, dtype: int64

TSPAN6
False    183
Name: TSPAN6, dtype: int64

TSPAN7
False    183
Name: TSPAN7, dtype: int64

TSPAN8
False    182
True       1
Name: TSPAN8, dtype: int64

TSPAN9
False    183
Name: TSPAN9, dtype: int64

TSPO2
False    171
True      12
Name: TSPO2, dtype: int64

TSPO
False    183
Name: TSPO, dtype: int64

TSPYL1
False    183
Name: TSPYL1, dtype: int64

TSPYL2
False    183
Name: TSPYL2, dtype: int64

TSPYL3
False    183
Name: TSPYL3, dtype: int64

TSPYL4
False    183
Name: TSPYL4, dtype: int64

TSPYL5
False    183
Name: TSPYL5, dtype: int64

TSPYL6
True     105
False     78
Name: TSPYL6, dtype: int64

TSR1
False    183
Name: TSR1, dtype: int64

TSR2
False    183
Name: TSR2, dtype: int64

TSSC1
False    183
Name: TSSC1, dtype: int64

TSSC4
False    183
Name: TSSC4, dtype: int64

TSSK1B
False    141
True      42
Name: TSSK1B, dtype: int64

TSSK3
False    182
True       1
Name: TSSK3, dtype: int64

TSSK4
False    182
True       1
Name: TSSK4, dtype: int64

TSSK6
False    183
Name: TSSK6, dtype: int64

TSTA3
False    183
Name: TSTA3, dtype: int64

TSTD1
False    183
Name: TSTD1, dtype: int64

TSTD2
False    183
Name: TSTD2, dtype: int64

TST
False    183
Name: TST, dtype: int64

TTBK1
False    183
Name: TTBK1, dtype: int64

TTBK2
False    183
Name: TTBK2, dtype: int64

TTC12
False    183
Name: TTC12, dtype: int64

TTC13
False    183
Name: TTC13, dtype: int64

TTC14
False    183
Name: TTC14, dtype: int64

TTC15
False    183
Name: TTC15, dtype: int64

TTC16
False    178
True       5
Name: TTC16, dtype: int64

TTC17
False    183
Name: TTC17, dtype: int64

TTC18
False    183
Name: TTC18, dtype: int64

TTC19
False    183
Name: TTC19, dtype: int64

TTC1
False    183
Name: TTC1, dtype: int64

TTC21A
False    183
Name: TTC21A, dtype: int64

TTC21B
False    183
Name: TTC21B, dtype: int64

TTC22
False    183
Name: TTC22, dtype: int64

TTC23L
False    181
True       2
Name: TTC23L, dtype: int64

TTC23
False    183
Name: TTC23, dtype: int64

TTC24
False    145
True      38
Name: TTC24, dtype: int64

TTC25
False    183
Name: TTC25, dtype: int64

TTC26
False    183
Name: TTC26, dtype: int64

TTC27
False    183
Name: TTC27, dtype: int64

TTC28
False    183
Name: TTC28, dtype: int64

TTC29
True     109
False     74
Name: TTC29, dtype: int64

TTC30A
False    183
Name: TTC30A, dtype: int64

TTC30B
False    183
Name: TTC30B, dtype: int64

TTC31
False    183
Name: TTC31, dtype: int64

TTC32
False    183
Name: TTC32, dtype: int64

TTC33
False    183
Name: TTC33, dtype: int64

TTC35
False    183
Name: TTC35, dtype: int64

TTC36
False    126
True      57
Name: TTC36, dtype: int64

TTC37
False    183
Name: TTC37, dtype: int64

TTC38
False    183
Name: TTC38, dtype: int64

TTC39A
False    183
Name: TTC39A, dtype: int64

TTC39B
False    183
Name: TTC39B, dtype: int64

TTC39C
False    183
Name: TTC39C, dtype: int64

TTC3
False    183
Name: TTC3, dtype: int64

TTC4
False    183
Name: TTC4, dtype: int64

TTC5
False    183
Name: TTC5, dtype: int64

TTC7A
False    183
Name: TTC7A, dtype: int64

TTC7B
False    183
Name: TTC7B, dtype: int64

TTC8
False    183
Name: TTC8, dtype: int64

TTC9B
False    130
True      53
Name: TTC9B, dtype: int64

TTC9C
False    183
Name: TTC9C, dtype: int64

TTC9
False    183
Name: TTC9, dtype: int64

TTF1
False    183
Name: TTF1, dtype: int64

TTF2
False    183
Name: TTF2, dtype: int64

TTK
False    183
Name: TTK, dtype: int64

TTLL10
False    181
True       2
Name: TTLL10, dtype: int64

TTLL11
False    183
Name: TTLL11, dtype: int64

TTLL12
False    183
Name: TTLL12, dtype: int64

TTLL13
False    183
Name: TTLL13, dtype: int64

TTLL1
False    183
Name: TTLL1, dtype: int64

TTLL2
False    177
True       6
Name: TTLL2, dtype: int64

TTLL3
False    183
Name: TTLL3, dtype: int64

TTLL4
False    183
Name: TTLL4, dtype: int64

TTLL5
False    183
Name: TTLL5, dtype: int64

TTLL6
False    181
True       2
Name: TTLL6, dtype: int64

TTLL7

False    183
Name: TTLL7, dtype: int64

TTLL9
False    183
Name: TTLL9, dtype: int64

TTL
False    183
Name: TTL, dtype: int64

TTN
False    183
Name: TTN, dtype: int64

TTPAL
False    183
Name: TTPAL, dtype: int64

TTPA
False    151
True      32
Name: TTPA, dtype: int64

TTR
False    179
True       4
Name: TTR, dtype: int64

TTTY10
True     113
False     70
Name: TTTY10, dtype: int64

TTTY14
False    103
True      80
Name: TTTY14, dtype: int64

TTTY15
False    116
True      67
Name: TTTY15, dtype: int64

TTTY2
True     98
False    85
Name: TTTY2, dtype: int64

TTYH1
False    183
Name: TTYH1, dtype: int64

TTYH2
False    183
Name: TTYH2, dtype: int64

TTYH3
False    183
Name: TTYH3, dtype: int64

TUBA1A
False    183
Name: TUBA1A, dtype: int64

TUBA1B
False    183
Name: TUBA1B, dtype: int64

TUBA1C
False    183
Name: TUBA1C, dtype: int64

TUBA3C
True     101
False     82
Name: TUBA3C, dtype: int64

TUBA3D
False    167
True      16
Name: TUBA3D, dtype: int64

TUBA3E
False    139
True      44
Name: TUBA3E, dtype: int64

TUBA4A
False    183
Name: TUBA4A, dtype: int64

TUBA4B
False    138
True      45
Name: TUBA4B, dtype: int64

TUBA8
False    183
Name: TUBA8, dtype: int64

TUBAL3
False    172
True      11
Name: TUBAL3, dtype: int64

TUBB1
False    183
Name: TUBB1, dtype: int64

TUBB2A
False    183
Name: TUBB2A, dtype: int64

TUBB2B
False    183
Name: TUBB2B, dtype: int64

TUBB2C
False    183
Name: TUBB2C, dtype: int64

TUBB3
False    183
Name: TUBB3, dtype: int64

TUBB4Q
False    144
True      39
Name: TUBB4Q, dtype: int64

TUBB4
False    183
Name: TUBB4, dtype: int64

TUBB6
False    183
Name: TUBB6, dtype: int64

TUBB8
False    182
True       1
Name: TUBB8, dtype: int64

TUBBP5
False    176
True       7
Name: TUBBP5, dtype: int64

TUBB
False    183
Name: TUBB, dtype: int64

TUBD1
False    183
Name: TUBD1, dtype: int64

TUBE1
False    183
Name: TUBE1, dtype: int64

TUBG1
False    183
Name: TUBG1, dtype: int64

TUBG2
False    183
Name: TUBG2, dtype: int64

TUBGCP2
False    183
Name: TUBGCP2, dtype: int64

TUBGCP3
False    183
Name: TUBGCP3, dtype: int64

TUBGCP4
False    183
Name: TUBGCP4, dtype: int64

TUBGCP5
False    183
Name: TUBGCP5, dtype: int64

TUBGCP6
False    183
Name: TUBGCP6, dtype: int64

TUB
False    183
Name: TUB, dtype: int64

TUFM
False    183
Name: TUFM, dtype: int64

TUFT1
False    183
Name: TUFT1, dtype: int64

TUG1
False    183
Name: TUG1, dtype: int64

TULP1
False    146
True      37
Name: TULP1, dtype: int64

TULP2
False    109
True      74
Name: TULP2, dtype: int64

TULP3
False    183
Name: TULP3, dtype: int64

TULP4
False    183
Name: TULP4, dtype: int64

TUSC1
False    183
Name: TUSC1, dtype: int64

TUSC2
False    183
Name: TUSC2, dtype: int64

TUSC3
False    183
Name: TUSC3, dtype: int64

TUSC5
False    148
True      35
Name: TUSC5, dtype: int64

TUT1
False    183
Name: TUT1, dtype: int64

TWF1
False    183
Name: TWF1, dtype: int64

TWF2
False    183
Name: TWF2, dtype: int64

TWIST1
False    182
True       1
Name: TWIST1, dtype: int64

TWIST2
False    182
True       1
Name: TWIST2, dtype: int64

TWISTNB
False    183
Name: TWISTNB, dtype: int64

TWSG1
False    183
Name: TWSG1, dtype: int64

TXK
False    183
Name: TXK, dtype: int64

TXLNA
False    183
Name: TXLNA, dtype: int64

TXLNB
False    182
True       1
Name: TXLNB, dtype: int64

TXLNG
False    183
Name: TXLNG, dtype: int64

TXN2
False    183
Name: TXN2, dtype: int64

TXNDC11
False    183
Name: TXNDC11, dtype: int64

TXNDC12
False    183
Name: TXNDC12, dtype: int64

TXNDC15
False    183
Name: TXNDC15, dtype: int64

TXNDC16
False    183
Name: TXNDC16, dtype: int64

TXNDC17
False    183
Name: TXNDC17, dtype: int64

TXNDC2
False    152
True      31
Name: TXNDC2, dtype: int64

TXNDC3
False    171
True      12
Name: TXNDC3, dtype: int64

TXNDC5
False    183
Name: TXNDC5, dtype: int64

TXNDC6
False    183
Name: TXNDC6, dtype: int64

TXNDC9
False    183
Name: TXNDC9, dtype: int64

TXNIP
False    183
Name: TXNIP, dtype: int64

TXNL1
False    183
Name: TXNL1, dtype: int64

TXNL4A
False    183
Name: TXNL4A, dtype: int64

TXNL4B
False    183
Name: TXNL4B, dtype: int64

TXNRD1
False    183
Name: TXNRD1, dtype: int64

TXNRD2
False    183
Name: TXNRD2, dtype: int64

TXNRD3IT1
False    183
Name: TXNRD3IT1, dtype: int64

TXN
False    183
Name: TXN, dtype: int64

TYK2
False    183
Name: TYK2, dtype: int64

TYMP
False    183
Name: TYMP, dtype: int64

TYMS
False    183
Name: TYMS, dtype: int64

TYRO3
False    183
Name: TYRO3, dtype: int64

TYROBP
False    183
Name: TYROBP, dtype: int64

TYRP1
False    176
True       7
Name: TYRP1, dtype: int64

TYR
True     122
False     61
Name: TYR, dtype: int64

TYSND1
False    183
Name: TYSND1, dtype: int64

TYW1B
False    183
Name: TYW1B, dtype: int64

TYW1
False    183
Name: TYW1, dtype: int64

TYW3
False    183
Name: TYW3, dtype: int64

U2AF1L4
False    183
Name: U2AF1L4, dtype: int64

U2AF1
False    183
Name: U2AF1, dtype: int64

U2AF2
False    183
Name: U2AF2, dtype: int64

UACA
False    183
Name: UACA, dtype: int64

UAP1L1
False    183
Name: UAP1L1, dtype: int64

UAP1
False    183
Name: UAP1, dtype: int64

UBA1
False    183
Name: UBA1, dtype: int64

UBA2
False    183
Name: UBA2, dtype: int64

UBA3
False    183
Name: UBA3, dtype: int64

UBA52
False    183
Name: UBA52, dtype: int64

UBA5
False    183
Name: UBA5, dtype: int64

UBA6
False    183
Name: UBA6, dtype: int64

UBA7
False    183
Name: UBA7, dtype: int64

UBAC1
False    183
Name: UBAC1, dtype: int64

UBAC2
False    183
Name: UBAC2, dtype: int64

UBAP1
False    183
Name: UBAP1, dtype: int64

UBAP2L
False    183
Name: UBAP2L, dtype: int64

UBAP2
False    183
Name: UBAP2, dtype: int64

UBASH3A
False    183
Name: UBASH3A, dtype: int64

UBASH3B
False    183
Name: UBASH3B, dtype: int64

UBB
False    183
Name: UBB, dtype: int64

UBC
False    183
Name: UBC, dtype: int64

UBD
False    183
Name: UBD, dtype: int64

UBE2A
False    183
Name: UBE2A, dtype: int64

UBE2B
False    183
Name: UBE2B, dtype: int64

UBE2CBP
False    183
Name: UBE2CBP, dtype: int64

UBE2C
False    183
Name: UBE2C, dtype: int64

UBE2D1
False    183
Name: UBE2D1, dtype: int64

UBE2D2
False    183
Name: UBE2D2, dtype: int64

UBE2D3
False    183
Name: UBE2D3, dtype: int64

UBE2D4
False    183
Name: UBE2D4, dtype: int64

UBE2E1
False    183
Name: UBE2E1, dtype: int64

UBE2E2
False    183
Name: UBE2E2, dtype: int64

UBE2E3
False    183
Name: UBE2E3, dtype: int64

UBE2F
False    183
Name: UBE2F, dtype: int64

UBE2G1
False    183
Name: UBE2G1, dtype: int64

UBE2G2
False    183
Name: UBE2G2, dtype: int64

UBE2H
False    183
Name: UBE2H, dtype: int64

UBE2I
False    183
Name: UBE2I, dtype: int64

UBE2J1
False    183
Name: UBE2J1, dtype: int64

UBE2J2
False    183
Name: UBE2J2, dtype: int64

UBE2K
False    183
Name: UBE2K, dtype: int64

UBE2L3
False    183
Name: UBE2L3, dtype: int64

UBE2L6
False    183
Name: UBE2L6, dtype: int64

UBE2MP1
False    183
Name: UBE2MP1, dtype: int64

UBE2M
False    183
Name: UBE2M, dtype: int64

UBE2NL
False    166
True      17
Name: UBE2NL, dtype: int64

UBE2N
False    183
Name: UBE2N, dtype: int64

UBE2O
False    183
Name: UBE2O, dtype: int64

UBE2Q1
False    183
Name: UBE2Q1, dtype: int64

UBE2Q2P1
False    183
Name: UBE2Q2P1, dtype: int64

UBE2Q2
False    183
Name: UBE2Q2, dtype: int64

UBE2QL1
False    183
Name: UBE2QL1, dtype: int64

UBE2R2
False    183
Name: UBE2R2, dtype: int64

UBE2S
False    183
Name: UBE2S, dtype: int64

UBE2T
False    183
Name: UBE2T, dtype: int64

UBE2U
True     122
False     61
Name: UBE2U, dtype: int64

UBE2V1
False    183
Name: UBE2V1, dtype: int64

UBE2V2
False    183
Name: UBE2V2, dtype: int64

UBE2W
False    183
Name: UBE2W, dtype: int64

UBE2Z
False    183
Name: UBE2Z, dtype: int64

UBE3A
False    183
Name: UBE3A, dtype: int64

UBE3B
False    183
Name: UBE3B, dtype: int64

UBE3C
False    183
Name: UBE3C, dtype: int64

UBE4A
False    183
Name: UBE4A, dtype: int64

UBE4B
False    183
Name: UBE4B, dtype: int64

UBFD1
False    183
Name: UBFD1, dtype: int64

UBIAD1
False    183
Name: UBIAD1, dtype: int64

UBL3
False    183
Name: UBL3, dtype: int64

UBL4A
False    183
Name: UBL4A, dtype: int64

UBL4B
False    129
True      54
Name: UBL4B, dtype: int64

UBL5
False    183
Name: UBL5, dtype: int64

UBL7
False    183
Name: UBL7, dtype: int64

UBLCP1
False    183
Name: UBLCP1, dtype: int64

UBN1
False    183
Name: UBN1, dtype: int64

UBN2
False    183
Name: UBN2, dtype: int64

UBOX5
False    183
Name: UBOX5, dtype: int64

UBP1
False    183
Name: UBP1, dtype: int64

UBQLN1
False    183
Name: UBQLN1, dtype: int64

UBQLN2
False    183
Name: UBQLN2, dtype: int64

UBQLN4
False    183
Name: UBQLN4, dtype: int64

UBQLNL
False    182
True       1
Name: UBQLNL, dtype: int64

UBR1
False    183
Name: UBR1, dtype: int64

UBR2
False    183
Name: UBR2, dtype: int64

UBR3

False    183
Name: UBR3, dtype: int64

UBR4
False    183
Name: UBR4, dtype: int64

UBR5
False    183
Name: UBR5, dtype: int64

UBR7
False    183
Name: UBR7, dtype: int64

UBTD1
False    183
Name: UBTD1, dtype: int64

UBTD2
False    183
Name: UBTD2, dtype: int64

UBTF
False    183
Name: UBTF, dtype: int64

UBXN10
False    183
Name: UBXN10, dtype: int64

UBXN11
False    183
Name: UBXN11, dtype: int64

UBXN1
False    183
Name: UBXN1, dtype: int64

UBXN2A
False    183
Name: UBXN2A, dtype: int64

UBXN2B
False    183
Name: UBXN2B, dtype: int64

UBXN4
False    183
Name: UBXN4, dtype: int64

UBXN6
False    183
Name: UBXN6, dtype: int64

UBXN7
False    183
Name: UBXN7, dtype: int64

UBXN8
False    183
Name: UBXN8, dtype: int64

UCA1
False    179
True       4
Name: UCA1, dtype: int64

UCHL1
False    183
Name: UCHL1, dtype: int64

UCHL3
False    183
Name: UCHL3, dtype: int64

UCHL5
False    183
Name: UCHL5, dtype: int64

UCK1
False    183
Name: UCK1, dtype: int64

UCK2
False    183
Name: UCK2, dtype: int64

UCKL1AS
False    183
Name: UCKL1AS, dtype: int64

UCKL1
False    183
Name: UCKL1, dtype: int64

UCN2
False    180
True       3
Name: UCN2, dtype: int64

UCN3
False    175
True       8
Name: UCN3, dtype: int64

UCN
False    175
True       8
Name: UCN, dtype: int64

UCP1
True     128
False     55
Name: UCP1, dtype: int64

UCP2
False    183
Name: UCP2, dtype: int64

UCP3
False    183
Name: UCP3, dtype: int64

UEVLD
False    183
Name: UEVLD, dtype: int64

UFC1
False    183
Name: UFC1, dtype: int64

UFD1L
False    183
Name: UFD1L, dtype: int64

UFM1
False    183
Name: UFM1, dtype: int64

UFSP1
False    183
Name: UFSP1, dtype: int64

UFSP2
False    183
Name: UFSP2, dtype: int64

UGCG
False    183
Name: UGCG, dtype: int64

UGDH
False    183
Name: UGDH, dtype: int64

UGGT1
False    183
Name: UGGT1, dtype: int64

UGGT2
False    183
Name: UGGT2, dtype: int64

UGP2
False    183
Name: UGP2, dtype: int64

UGT1A10
False    171
True      12
Name: UGT1A10, dtype: int64

UGT1A1
False    160
True      23
Name: UGT1A1, dtype: int64

UGT1A3
False    105
True      78
Name: UGT1A3, dtype: int64

UGT1A4
True     122
False     61
Name: UGT1A4, dtype: int64

UGT1A6
False    178
True       5
Name: UGT1A6, dtype: int64

UGT1A7
True     126
False     57
Name: UGT1A7, dtype: int64

UGT1A8
False    160
True      23
Name: UGT1A8, dtype: int64

UGT1A9
False    160
True      23
Name: UGT1A9, dtype: int64

UGT2A1
True     124
False     59
Name: UGT2A1, dtype: int64

UGT2A3
False    176
True       7
Name: UGT2A3, dtype: int64

UGT2B10
False    114
True      69
Name: UGT2B10, dtype: int64

UGT2B11
False    118
True      65
Name: UGT2B11, dtype: int64

UGT2B15
False    181
True       2
Name: UGT2B15, dtype: int64

UGT2B28
True     125
False     58
Name: UGT2B28, dtype: int64

UGT2B4
False    115
True      68
Name: UGT2B4, dtype: int64

UGT2B7
False    179
True       4
Name: UGT2B7, dtype: int64

UGT3A1
True     92
False    91
Name: UGT3A1, dtype: int64

UGT3A2
False    159
True      24
Name: UGT3A2, dtype: int64

UGT8
False    183
Name: UGT8, dtype: int64

UHMK1
False    183
Name: UHMK1, dtype: int64

UHRF1BP1L
False    183
Name: UHRF1BP1L, dtype: int64

UHRF1BP1
False    183
Name: UHRF1BP1, dtype: int64

UHRF1
False    183
Name: UHRF1, dtype: int64

UHRF2
False    183
Name: UHRF2, dtype: int64

UIMC1
False    183
Name: UIMC1, dtype: int64

ULBP1
False    182
True       1
Name: ULBP1, dtype: int64

ULBP2
False    183
Name: ULBP2, dtype: int64

ULBP3
False    183
Name: ULBP3, dtype: int64

ULK1
False    183
Name: ULK1, dtype: int64

ULK2
False    183
Name: ULK2, dtype: int64

ULK3
False    183
Name: ULK3, dtype: int64

ULK4
False    183
Name: ULK4, dtype: int64

UMODL1
False    138
True      45
Name: UMODL1, dtype: int64

UMOD
True     93
False    90
Name: UMOD, dtype: int64

UMPS
False    183
Name: UMPS, dtype: int64

UNC119B
False    183
Name: UNC119B, dtype: int64

UNC119
False    183
Name: UNC119, dtype: int64

UNC13A
False    183
Name: UNC13A, dtype: int64

UNC13B
False    183
Name: UNC13B, dtype: int64

UNC13C
False    132
True      51
Name: UNC13C, dtype: int64

UNC13D
False    183
Name: UNC13D, dtype: int64

UNC45A
False    183
Name: UNC45A, dtype: int64

UNC45B
False    151
True      32
Name: UNC45B, dtype: int64

UNC50
False    183
Name: UNC50, dtype: int64

UNC5A
False    183
Name: UNC5A, dtype: int64

UNC5B
False    183
Name: UNC5B, dtype: int64

UNC5CL
False    183
Name: UNC5CL, dtype: int64

UNC5C
False    180
True       3
Name: UNC5C, dtype: int64

UNC5D
False    153
True      30
Name: UNC5D, dtype: int64

UNC80
False    181
True       2
Name: UNC80, dtype: int64

UNC93A
False    148
True      35
Name: UNC93A, dtype: int64

UNC93B1
False    183
Name: UNC93B1, dtype: int64

UNG
False    183
Name: UNG, dtype: int64

UNKL
False    183
Name: UNKL, dtype: int64

UNK
False    183
Name: UNK, dtype: int64

UOX
False    153
True      30
Name: UOX, dtype: int64

UPB1
False    177
True       6
Name: UPB1, dtype: int64

UPF0639
False    144
True      39
Name: UPF0639, dtype: int64

UPF1
False    183
Name: UPF1, dtype: int64

UPF2
False    183
Name: UPF2, dtype: int64

UPF3A
False    183
Name: UPF3A, dtype: int64

UPF3B
False    183
Name: UPF3B, dtype: int64

UPK1A
False    145
True      38
Name: UPK1A, dtype: int64

UPK1B
False    177
True       6
Name: UPK1B, dtype: int64

UPK2
False    166
True      17
Name: UPK2, dtype: int64

UPK3A
False    172
True      11
Name: UPK3A, dtype: int64

UPK3BL
False    178
True       5
Name: UPK3BL, dtype: int64

UPK3B
False    182
True       1
Name: UPK3B, dtype: int64

UPP1
False    183
Name: UPP1, dtype: int64

UPP2
False    153
True      30
Name: UPP2, dtype: int64

UPRT
False    183
Name: UPRT, dtype: int64

UQCC
False    183
Name: UQCC, dtype: int64

UQCR10
False    183
Name: UQCR10, dtype: int64

UQCR11
False    183
Name: UQCR11, dtype: int64

UQCRB
False    183
Name: UQCRB, dtype: int64

UQCRC1
False    183
Name: UQCRC1, dtype: int64

UQCRC2
False    183
Name: UQCRC2, dtype: int64

UQCRFS1
False    183
Name: UQCRFS1, dtype: int64

UQCRHL
False    183
Name: UQCRHL, dtype: int64

UQCRH
False    183
Name: UQCRH, dtype: int64

UQCRQ
False    183
Name: UQCRQ, dtype: int64

URB1
False    183
Name: URB1, dtype: int64

URB2
False    183
Name: URB2, dtype: int64

URGCP
False    183
Name: URGCP, dtype: int64

URM1
False    183
Name: URM1, dtype: int64

UROC1
False    121
True      62
Name: UROC1, dtype: int64

UROD
False    183
Name: UROD, dtype: int64

UROS
False    183
Name: UROS, dtype: int64

USE1
False    183
Name: USE1, dtype: int64

USF1
False    183
Name: USF1, dtype: int64

USF2
False    183
Name: USF2, dtype: int64

USH1C
False    182
True       1
Name: USH1C, dtype: int64

USH1G
False    122
True      61
Name: USH1G, dtype: int64

USH2A
False    182
True       1
Name: USH2A, dtype: int64

USHBP1
False    183
Name: USHBP1, dtype: int64

USMG5
False    183
Name: USMG5, dtype: int64

USO1
False    183
Name: USO1, dtype: int64

USP10
False    183
Name: USP10, dtype: int64

USP11
False    183
Name: USP11, dtype: int64

USP12
False    183
Name: USP12, dtype: int64

USP13
False    183
Name: USP13, dtype: int64

USP14
False    183
Name: USP14, dtype: int64

USP15
False    183
Name: USP15, dtype: int64

USP16
False    183
Name: USP16, dtype: int64

USP18
False    183
Name: USP18, dtype: int64

USP19
False    183
Name: USP19, dtype: int64

USP1
False    183
Name: USP1, dtype: int64

USP20
False    183
Name: USP20, dtype: int64

USP21
False    183
Name: USP21, dtype: int64

USP22
False    183
Name: USP22, dtype: int64

USP24
False    183
Name: USP24, dtype: int64

USP25
False    183
Name: USP25, dtype: int64

USP27X
False    183
Name: USP27X, dtype: int64

USP28
False    183
Name: USP28, dtype: int64

USP2
False    183
Name: USP2, dtype: int64

USP30
False    183
Name: USP30, dtype: int64

USP31
False    183
Name: USP31, dtype: int64

USP32
False    183
Name: USP32, dtype: int64

USP33
False    183
Name: USP33, dtype: int64

USP34
False    183
Name: USP34, dtype: int64

USP35
False    183
Name: USP35, dtype: int64

USP36
False    183
Name: USP36, dtype: int64

USP37
False    183
Name: USP37, dtype: int64

USP38
False    183
Name: USP38, dtype: int64

USP39
False    183
Name: USP39, dtype: int64

USP3
False    183
Name: USP3, dtype: int64

USP40
False    183
Name: USP40, dtype: int64

USP42
False    183
Name: USP42, dtype: int64

USP43
False    183
Name: USP43, dtype: int64

USP44
False    180
True       3
Name: USP44, dtype: int64

USP45
False    183
Name: USP45, dtype: int64

USP46
False    183
Name: USP46, dtype: int64

USP47
False    183
Name: USP47, dtype: int64

USP48

False    183
Name: USP48, dtype: int64

USP49
False    183
Name: USP49, dtype: int64

USP4
False    183
Name: USP4, dtype: int64

USP51
False    183
Name: USP51, dtype: int64

USP53
False    183
Name: USP53, dtype: int64

USP54
False    183
Name: USP54, dtype: int64

USP5
False    183
Name: USP5, dtype: int64

USP6NL
False    183
Name: USP6NL, dtype: int64

USP6
False    183
Name: USP6, dtype: int64

USP7
False    183
Name: USP7, dtype: int64

USP8
False    183
Name: USP8, dtype: int64

USP9X
False    183
Name: USP9X, dtype: int64

USP9Y
False    125
True      58
Name: USP9Y, dtype: int64

USPL1
False    183
Name: USPL1, dtype: int64

UST
False    183
Name: UST, dtype: int64

UTF1
False    92
True     91
Name: UTF1, dtype: int64

UTP11L
False    183
Name: UTP11L, dtype: int64

UTP14A
False    183
Name: UTP14A, dtype: int64

UTP14C
False    183
Name: UTP14C, dtype: int64

UTP15
False    183
Name: UTP15, dtype: int64

UTP18
False    183
Name: UTP18, dtype: int64

UTP20
False    183
Name: UTP20, dtype: int64

UTP23
False    183
Name: UTP23, dtype: int64

UTP3
False    183
Name: UTP3, dtype: int64

UTP6
False    183
Name: UTP6, dtype: int64

UTRN
False    183
Name: UTRN, dtype: int64

UTS2D
False    178
True       5
Name: UTS2D, dtype: int64

UTS2R
False    93
True     90
Name: UTS2R, dtype: int64

UTS2
False    147
True      36
Name: UTS2, dtype: int64

UTY
False    120
True      63
Name: UTY, dtype: int64

UVRAG
False    183
Name: UVRAG, dtype: int64

UXS1
False    183
Name: UXS1, dtype: int64

UXT
False    183
Name: UXT, dtype: int64

VAC14
False    183
Name: VAC14, dtype: int64

VAMP1
False    183
Name: VAMP1, dtype: int64

VAMP2
False    183
Name: VAMP2, dtype: int64

VAMP3
False    183
Name: VAMP3, dtype: int64

VAMP4
False    183
Name: VAMP4, dtype: int64

VAMP5
False    183
Name: VAMP5, dtype: int64

VAMP7
False    183
Name: VAMP7, dtype: int64

VAMP8
False    183
Name: VAMP8, dtype: int64

VANGL1
False    183
Name: VANGL1, dtype: int64

VANGL2
False    183
Name: VANGL2, dtype: int64

VAPA
False    183
Name: VAPA, dtype: int64

VAPB
False    183
Name: VAPB, dtype: int64

VARS2
False    183
Name: VARS2, dtype: int64

VARS
False    183
Name: VARS, dtype: int64

VASH1
False    183
Name: VASH1, dtype: int64

VASH2
False    183
Name: VASH2, dtype: int64

VASN
False    183
Name: VASN, dtype: int64

VASP
False    183
Name: VASP, dtype: int64

VAT1L
False    183
Name: VAT1L, dtype: int64

VAT1
False    183
Name: VAT1, dtype: int64

VAV1
False    183
Name: VAV1, dtype: int64

VAV2
False    183
Name: VAV2, dtype: int64

VAV3
False    183
Name: VAV3, dtype: int64

VAX2
False    182
True       1
Name: VAX2, dtype: int64

VBP1
False    183
Name: VBP1, dtype: int64

VCAM1
False    183
Name: VCAM1, dtype: int64

VCAN
False    183
Name: VCAN, dtype: int64

VCL
False    183
Name: VCL, dtype: int64

VCPIP1
False    183
Name: VCPIP1, dtype: int64

VCP
False    183
Name: VCP, dtype: int64

VCX3A
False    128
True      55
Name: VCX3A, dtype: int64

VCX3B
True     126
False     57
Name: VCX3B, dtype: int64

VDAC1
False    183
Name: VDAC1, dtype: int64

VDAC2
False    183
Name: VDAC2, dtype: int64

VDAC3
False    183
Name: VDAC3, dtype: int64

VDR
False    183
Name: VDR, dtype: int64

VEGFA
False    183
Name: VEGFA, dtype: int64

VEGFB
False    183
Name: VEGFB, dtype: int64

VEGFC
False    183
Name: VEGFC, dtype: int64

VENTX
False    183
Name: VENTX, dtype: int64

VEPH1
False    181
True       2
Name: VEPH1, dtype: int64

VEZF1
False    183
Name: VEZF1, dtype: int64

VEZT
False    183
Name: VEZT, dtype: int64

VGF
False    182
True       1
Name: VGF, dtype: int64

VGLL1
False    175
True       8
Name: VGLL1, dtype: int64

VGLL2
True     111
False     72
Name: VGLL2, dtype: int64

VGLL3
False    183
Name: VGLL3, dtype: int64

VGLL4
False    183
Name: VGLL4, dtype: int64

VHL
False    183
Name: VHL, dtype: int64

VIL1
False    183
Name: VIL1, dtype: int64

VILL
False    183
Name: VILL, dtype: int64

VIM
False    183
Name: VIM, dtype: int64

VIPAR
False    183
Name: VIPAR, dtype: int64

VIPR1
False    183
Name: VIPR1, dtype: int64

VIPR2
False    182
True       1
Name: VIPR2, dtype: int64

VIP
False    180
True       3
Name: VIP, dtype: int64

VIT
False    172
True      11
Name: VIT, dtype: int64

VKORC1L1
False    183
Name: VKORC1L1, dtype: int64

VKORC1
False    183
Name: VKORC1, dtype: int64

VLDLR
False    183
Name: VLDLR, dtype: int64

VMA21
False    183
Name: VMA21, dtype: int64

VMAC
False    183
Name: VMAC, dtype: int64

VMO1
False    183
Name: VMO1, dtype: int64

VN1R1
False    183
Name: VN1R1, dtype: int64

VNN1
False    183
Name: VNN1, dtype: int64

VNN2
False    183
Name: VNN2, dtype: int64

VNN3
False    178
True       5
Name: VNN3, dtype: int64

VOPP1
False    183
Name: VOPP1, dtype: int64

VPRBP
False    183
Name: VPRBP, dtype: int64

VPREB3
False    180
True       3
Name: VPREB3, dtype: int64

VPS11
False    183
Name: VPS11, dtype: int64

VPS13A
False    183
Name: VPS13A, dtype: int64

VPS13B
False    183
Name: VPS13B, dtype: int64

VPS13C
False    183
Name: VPS13C, dtype: int64

VPS13D
False    183
Name: VPS13D, dtype: int64

VPS16
False    183
Name: VPS16, dtype: int64

VPS18
False    183
Name: VPS18, dtype: int64

VPS24
False    183
Name: VPS24, dtype: int64

VPS25
False    183
Name: VPS25, dtype: int64

VPS26A
False    183
Name: VPS26A, dtype: int64

VPS26B
False    183
Name: VPS26B, dtype: int64

VPS28
False    183
Name: VPS28, dtype: int64

VPS29
False    183
Name: VPS29, dtype: int64

VPS33A
False    183
Name: VPS33A, dtype: int64

VPS33B
False    183
Name: VPS33B, dtype: int64

VPS35
False    183
Name: VPS35, dtype: int64

VPS36
False    183
Name: VPS36, dtype: int64

VPS37A
False    183
Name: VPS37A, dtype: int64

VPS37B
False    183
Name: VPS37B, dtype: int64

VPS37C
False    183
Name: VPS37C, dtype: int64

VPS37D
False    183
Name: VPS37D, dtype: int64

VPS39
False    183
Name: VPS39, dtype: int64

VPS41
False    183
Name: VPS41, dtype: int64

VPS45
False    183
Name: VPS45, dtype: int64

VPS4A
False    183
Name: VPS4A, dtype: int64

VPS4B
False    183
Name: VPS4B, dtype: int64

VPS52
False    183
Name: VPS52, dtype: int64

VPS53
False    183
Name: VPS53, dtype: int64

VPS54
False    183
Name: VPS54, dtype: int64

VPS72
False    183
Name: VPS72, dtype: int64

VPS8
False    183
Name: VPS8, dtype: int64

VRK1
False    183
Name: VRK1, dtype: int64

VRK2
False    183
Name: VRK2, dtype: int64

VRK3
False    183
Name: VRK3, dtype: int64

VSIG10L
False    183
Name: VSIG10L, dtype: int64

VSIG10
False    183
Name: VSIG10, dtype: int64

VSIG1
False    182
True       1
Name: VSIG1, dtype: int64

VSIG2
False    183
Name: VSIG2, dtype: int64

VSIG4
False    183
Name: VSIG4, dtype: int64

VSIG8
False    171
True      12
Name: VSIG8, dtype: int64

VSNL1
False    182
True       1
Name: VSNL1, dtype: int64

VSTM1
False    143
True      40
Name: VSTM1, dtype: int64

VSTM2A
False    155
True      28
Name: VSTM2A, dtype: int64

VSTM2B
True     127
False     56
Name: VSTM2B, dtype: int64

VSTM2L
False    183
Name: VSTM2L, dtype: int64

VSX1
False    144
True      39
Name: VSX1, dtype: int64

VSX2
True     103
False     80
Name: VSX2, dtype: int64

VTA1
False    183
Name: VTA1, dtype: int64

VTCN1
False    180
True       3
Name: VTCN1, dtype: int64

VTI1A
False    183
Name: VTI1A, dtype: int64

VTI1B
False    183
Name: VTI1B, dtype: int64

VTN
False    183
Name: VTN, dtype: int64

VWA1
False    183
Name: VWA1, dtype: int64

VWA2
False    183
Name: VWA2, dtype: int64

VWA3A
False    175
True       8
Name: VWA3A, dtype: int64

VWA3B
False    183
Name: VWA3B, dtype: int64

VWA5A
False    183
Name: VWA5A, dtype: int64

VWA5B1
False    174
True       9
Name: VWA5B1, dtype: int64

VWA5B2
False    182
True       1
Name: VWA5B2, dtype: int64

VWC2
False    111
True      72
Name: VWC2, dtype: int64

VWCE
False    183
Name: VWCE, dtype: int64

VWDE
False    180
True       3
Name: VWDE, dtype: int64

VWF
False    183
Name: VWF, dtype: int64

WAC
False    183
Name: WAC, dtype: int64

WAPAL
False    183
Name: WAPAL, dtype: int64

WARS2
False    183
Name: WARS2, dtype: int64

WARS
False    183
Name: WARS, dtype: int64

WASF1
False    183
Name: WASF1, dtype: int64

WASF2
False    183
Name: WASF2, dtype: int64

WASF3
False    183
Name: WASF3, dtype: int64

WASH2P
False    183
Name: WASH2P, dtype: int64

WASH3P
False    183
Name: WASH3P, dtype: int64

WASH5P
False    183
Name: WASH5P, dtype: int64

WASH7P
False    183
Name: WASH7P, dtype: int64

WASL
False    183
Name: WASL, dtype: int64

WAS
False    183
Name: WAS, dtype: int64

WBP11P1
False    183
Name: WBP11P1, dtype: int64

WBP11
False    183
Name: WBP11, dtype: int64

WBP1
False    183
Name: WBP1, dtype: int64

WBP2NL
False    180
True       3
Name: WBP2NL, dtype: int64

WBP2
False    183
Name: WBP2, dtype: int64

WBP4
False    183
Name: WBP4, dtype: int64

WBP5
False    183
Name: WBP5, dtype: int64

WBSCR16

False    183
Name: WBSCR16, dtype: int64

WBSCR17
False    182
True       1
Name: WBSCR17, dtype: int64

WBSCR22
False    183
Name: WBSCR22, dtype: int64

WBSCR26
False    181
True       2
Name: WBSCR26, dtype: int64

WBSCR27
False    183
Name: WBSCR27, dtype: int64

WBSCR28
False    169
True      14
Name: WBSCR28, dtype: int64

WDFY1
False    183
Name: WDFY1, dtype: int64

WDFY2
False    183
Name: WDFY2, dtype: int64

WDFY3
False    183
Name: WDFY3, dtype: int64

WDFY4
False    183
Name: WDFY4, dtype: int64

WDHD1
False    183
Name: WDHD1, dtype: int64

WDR11
False    183
Name: WDR11, dtype: int64

WDR12
False    183
Name: WDR12, dtype: int64

WDR13
False    183
Name: WDR13, dtype: int64

WDR16
False    166
True      17
Name: WDR16, dtype: int64

WDR17
False    181
True       2
Name: WDR17, dtype: int64

WDR18
False    183
Name: WDR18, dtype: int64

WDR19
False    183
Name: WDR19, dtype: int64

WDR1
False    183
Name: WDR1, dtype: int64

WDR20
False    183
Name: WDR20, dtype: int64

WDR24
False    183
Name: WDR24, dtype: int64

WDR25
False    183
Name: WDR25, dtype: int64

WDR26
False    183
Name: WDR26, dtype: int64

WDR27
False    183
Name: WDR27, dtype: int64

WDR31
False    183
Name: WDR31, dtype: int64

WDR33
False    183
Name: WDR33, dtype: int64

WDR34
False    183
Name: WDR34, dtype: int64

WDR35
False    183
Name: WDR35, dtype: int64

WDR36
False    183
Name: WDR36, dtype: int64

WDR37
False    183
Name: WDR37, dtype: int64

WDR38
False    144
True      39
Name: WDR38, dtype: int64

WDR3
False    183
Name: WDR3, dtype: int64

WDR41
False    183
Name: WDR41, dtype: int64

WDR43
False    183
Name: WDR43, dtype: int64

WDR44
False    183
Name: WDR44, dtype: int64

WDR45L
False    183
Name: WDR45L, dtype: int64

WDR45
False    183
Name: WDR45, dtype: int64

WDR46
False    183
Name: WDR46, dtype: int64

WDR47
False    183
Name: WDR47, dtype: int64

WDR48
False    183
Name: WDR48, dtype: int64

WDR49
False    134
True      49
Name: WDR49, dtype: int64

WDR4
False    183
Name: WDR4, dtype: int64

WDR52
False    183
Name: WDR52, dtype: int64

WDR53
False    183
Name: WDR53, dtype: int64

WDR54
False    183
Name: WDR54, dtype: int64

WDR55
False    183
Name: WDR55, dtype: int64

WDR59
False    183
Name: WDR59, dtype: int64

WDR5B
False    183
Name: WDR5B, dtype: int64

WDR5
False    183
Name: WDR5, dtype: int64

WDR60
False    183
Name: WDR60, dtype: int64

WDR61
False    183
Name: WDR61, dtype: int64

WDR62
False    183
Name: WDR62, dtype: int64

WDR63
False    175
True       8
Name: WDR63, dtype: int64

WDR64
False    120
True      63
Name: WDR64, dtype: int64

WDR65
False    165
True      18
Name: WDR65, dtype: int64

WDR66
False    183
Name: WDR66, dtype: int64

WDR67
False    183
Name: WDR67, dtype: int64

WDR69
False    135
True      48
Name: WDR69, dtype: int64

WDR6
False    183
Name: WDR6, dtype: int64

WDR70
False    183
Name: WDR70, dtype: int64

WDR72
False    178
True       5
Name: WDR72, dtype: int64

WDR73
False    183
Name: WDR73, dtype: int64

WDR74
False    183
Name: WDR74, dtype: int64

WDR75
False    183
Name: WDR75, dtype: int64

WDR76
False    183
Name: WDR76, dtype: int64

WDR77
False    183
Name: WDR77, dtype: int64

WDR78
False    183
Name: WDR78, dtype: int64

WDR7
False    183
Name: WDR7, dtype: int64

WDR81
False    183
Name: WDR81, dtype: int64

WDR82
False    183
Name: WDR82, dtype: int64

WDR83
False    183
Name: WDR83, dtype: int64

WDR85
False    183
Name: WDR85, dtype: int64

WDR86
False    183
Name: WDR86, dtype: int64

WDR87
False    92
True     91
Name: WDR87, dtype: int64

WDR88
False    178
True       5
Name: WDR88, dtype: int64

WDR89
False    183
Name: WDR89, dtype: int64

WDR8
False    183
Name: WDR8, dtype: int64

WDR90
False    183
Name: WDR90, dtype: int64

WDR91
False    183
Name: WDR91, dtype: int64

WDR92
False    183
Name: WDR92, dtype: int64

WDR93
False    183
Name: WDR93, dtype: int64

WDSUB1
False    183
Name: WDSUB1, dtype: int64

WDTC1
False    183
Name: WDTC1, dtype: int64

WDYHV1
False    183
Name: WDYHV1, dtype: int64

WEE1
False    183
Name: WEE1, dtype: int64

WEE2
False    145
True      38
Name: WEE2, dtype: int64

WFDC10B
False    157
True      26
Name: WFDC10B, dtype: int64

WFDC12
False    101
True      82
Name: WFDC12, dtype: int64

WFDC13
True     92
False    91
Name: WFDC13, dtype: int64

WFDC1
False    183
Name: WFDC1, dtype: int64

WFDC2
False    183
Name: WFDC2, dtype: int64

WFDC3
False    181
True       2
Name: WFDC3, dtype: int64

WFDC5
True     93
False    90
Name: WFDC5, dtype: int64

WFIKKN1
False    183
Name: WFIKKN1, dtype: int64

WFIKKN2
False    177
True       6
Name: WFIKKN2, dtype: int64

WFS1
False    183
Name: WFS1, dtype: int64

WHAMML1
False    183
Name: WHAMML1, dtype: int64

WHAMML2
False    182
True       1
Name: WHAMML2, dtype: int64

WHAMM
False    183
Name: WHAMM, dtype: int64

WHSC1L1
False    183
Name: WHSC1L1, dtype: int64

WHSC1
False    183
Name: WHSC1, dtype: int64

WHSC2
False    183
Name: WHSC2, dtype: int64

WIBG
False    183
Name: WIBG, dtype: int64

WIF1
False    132
True      51
Name: WIF1, dtype: int64

WIPF1
False    183
Name: WIPF1, dtype: int64

WIPF2
False    183
Name: WIPF2, dtype: int64

WIPF3
False    182
True       1
Name: WIPF3, dtype: int64

WIPI1
False    183
Name: WIPI1, dtype: int64

WIPI2
False    183
Name: WIPI2, dtype: int64

WISP1
False    183
Name: WISP1, dtype: int64

WISP2
False    182
True       1
Name: WISP2, dtype: int64

WISP3
False    158
True      25
Name: WISP3, dtype: int64

WIT1
False    173
True      10
Name: WIT1, dtype: int64

WIZ
False    183
Name: WIZ, dtype: int64

WLS
False    183
Name: WLS, dtype: int64

WNK1
False    183
Name: WNK1, dtype: int64

WNK2
False    183
Name: WNK2, dtype: int64

WNK3
False    180
True       3
Name: WNK3, dtype: int64

WNK4
False    183
Name: WNK4, dtype: int64

WNT10A
False    183
Name: WNT10A, dtype: int64

WNT10B
False    182
True       1
Name: WNT10B, dtype: int64

WNT11
False    183
Name: WNT11, dtype: int64

WNT16
False    176
True       7
Name: WNT16, dtype: int64

WNT1
False    169
True      14
Name: WNT1, dtype: int64

WNT2B
False    183
Name: WNT2B, dtype: int64

WNT2
False    180
True       3
Name: WNT2, dtype: int64

WNT3A
False    151
True      32
Name: WNT3A, dtype: int64

WNT3
False    182
True       1
Name: WNT3, dtype: int64

WNT4
False    183
Name: WNT4, dtype: int64

WNT5A
False    183
Name: WNT5A, dtype: int64

WNT5B
False    183
Name: WNT5B, dtype: int64

WNT6
False    178
True       5
Name: WNT6, dtype: int64

WNT7A
False    174
True       9
Name: WNT7A, dtype: int64

WNT7B
False    183
Name: WNT7B, dtype: int64

WNT8B
False    130
True      53
Name: WNT8B, dtype: int64

WNT9A
False    182
True       1
Name: WNT9A, dtype: int64

WNT9B
False    159
True      24
Name: WNT9B, dtype: int64

WRAP53
False    183
Name: WRAP53, dtype: int64

WRB
False    183
Name: WRB, dtype: int64

WRNIP1
False    183
Name: WRNIP1, dtype: int64

WRN
False    183
Name: WRN, dtype: int64

WSB1
False    183
Name: WSB1, dtype: int64

WSB2
False    183
Name: WSB2, dtype: int64

WSCD1
False    183
Name: WSCD1, dtype: int64

WSCD2
False    179
True       4
Name: WSCD2, dtype: int64

WT1
False    175
True       8
Name: WT1, dtype: int64

WTAP
False    183
Name: WTAP, dtype: int64

WTIP
False    183
Name: WTIP, dtype: int64

WWC1
False    183
Name: WWC1, dtype: int64

WWC2
False    183
Name: WWC2, dtype: int64

WWC3
False    183
Name: WWC3, dtype: int64

WWOX
False    183
Name: WWOX, dtype: int64

WWP1
False    183
Name: WWP1, dtype: int64

WWP2
False    183
Name: WWP2, dtype: int64

WWTR1
False    183
Name: WWTR1, dtype: int64

XAB2
False    183
Name: XAB2, dtype: int64

XAF1
False    183
Name: XAF1, dtype: int64

XAGE1D
True     111
False     72
Name: XAGE1D, dtype: int64

XBP1
False    183
Name: XBP1, dtype: int64

XCL1
False    177
True       6
Name: XCL1, dtype: int64

XCL2
False    178
True       5
Name: XCL2, dtype: int64

XCR1
False    147
True      36
Name: XCR1, dtype: int64

XDH
False    182
True       1
Name: XDH, dtype: int64

XG
False    174
True       9
Name: XG, dtype: int64

XIAP
False    183
Name: XIAP, dtype: int64

XIRP1
False    183
Name: XIRP1, dtype: int64

XIST
False    161
True      22
Name: XIST, dtype: int64

XKR3
True     114
False     69
Name: XKR3, dtype: int64

XKR4
False    161
True      22
Name: XKR4, dtype: int64

XKR5
False    173
True      10
Name: XKR5, dtype: int64

XKR6
False    183
Name: XKR6, dtype: int64

XKR7
False    138
True      45
Name: XKR7, dtype: int64

XKR8
False    183
Name: XKR8, dtype: int64

XKR9
False    183
Name: XKR9, dtype: int64

XKRX
False    181
True       2
Name: XKRX, dtype: int64

XK
False    183
Name: XK, dtype: int64

XPA
False    183
Name: XPA, dtype: int64

XPC
False    183
Name: XPC, dtype: int64

XPNPEP1
False    183
Name: XPNPEP1, dtype: int64

XPNPEP2
False    178
True       5
Name: XPNPEP2, dtype: int64

XPNPEP3
False    183
Name: XPNPEP3, dtype: int64

XPO1
False    183
Name: XPO1, dtype: int64

XPO4
False    183

Name: XPO4, dtype: int64

XPO5
False    183
Name: XPO5, dtype: int64

XPO6
False    183
Name: XPO6, dtype: int64

XPO7
False    183
Name: XPO7, dtype: int64

XPOT
False    183
Name: XPOT, dtype: int64

XPR1
False    183
Name: XPR1, dtype: int64

XRCC1
False    183
Name: XRCC1, dtype: int64

XRCC2
False    183
Name: XRCC2, dtype: int64

XRCC3
False    183
Name: XRCC3, dtype: int64

XRCC4
False    183
Name: XRCC4, dtype: int64

XRCC5
False    183
Name: XRCC5, dtype: int64

XRCC6BP1
False    183
Name: XRCC6BP1, dtype: int64

XRCC6
False    183
Name: XRCC6, dtype: int64

XRN1
False    183
Name: XRN1, dtype: int64

XRN2
False    183
Name: XRN2, dtype: int64

XRRA1
False    183
Name: XRRA1, dtype: int64

XYLB
False    183
Name: XYLB, dtype: int64

XYLT1
False    183
Name: XYLT1, dtype: int64

XYLT2
False    183
Name: XYLT2, dtype: int64

YAF2
False    183
Name: YAF2, dtype: int64

YAP1
False    183
Name: YAP1, dtype: int64

YARS2
False    183
Name: YARS2, dtype: int64

YARS
False    183
Name: YARS, dtype: int64

YBX1
False    183
Name: YBX1, dtype: int64

YBX2
False    171
True      12
Name: YBX2, dtype: int64

YDJC
False    183
Name: YDJC, dtype: int64

YEATS2
False    183
Name: YEATS2, dtype: int64

YEATS4
False    183
Name: YEATS4, dtype: int64

YES1
False    183
Name: YES1, dtype: int64

YIF1A
False    183
Name: YIF1A, dtype: int64

YIF1B
False    183
Name: YIF1B, dtype: int64

YIPF1
False    183
Name: YIPF1, dtype: int64

YIPF2
False    183
Name: YIPF2, dtype: int64

YIPF3
False    183
Name: YIPF3, dtype: int64

YIPF4
False    183
Name: YIPF4, dtype: int64

YIPF5
False    183
Name: YIPF5, dtype: int64

YIPF6
False    183
Name: YIPF6, dtype: int64

YIPF7
True     105
False     78
Name: YIPF7, dtype: int64

YJEFN3
False    181
True       2
Name: YJEFN3, dtype: int64

YKT6
False    183
Name: YKT6, dtype: int64

YLPM1
False    183
Name: YLPM1, dtype: int64

YME1L1
False    183
Name: YME1L1, dtype: int64

YOD1
False    183
Name: YOD1, dtype: int64

YPEL1
False    183
Name: YPEL1, dtype: int64

YPEL2
False    183
Name: YPEL2, dtype: int64

YPEL3
False    183
Name: YPEL3, dtype: int64

YPEL4
False    183
Name: YPEL4, dtype: int64

YPEL5
False    183
Name: YPEL5, dtype: int64

YRDC
False    183
Name: YRDC, dtype: int64

YSK4
False    123
True      60
Name: YSK4, dtype: int64

YTHDC1
False    183
Name: YTHDC1, dtype: int64

YTHDC2
False    183
Name: YTHDC2, dtype: int64

YTHDF1
False    183
Name: YTHDF1, dtype: int64

YTHDF2
False    183
Name: YTHDF2, dtype: int64

YTHDF3
False    183
Name: YTHDF3, dtype: int64

YWHAB
False    183
Name: YWHAB, dtype: int64

YWHAE
False    183
Name: YWHAE, dtype: int64

YWHAG
False    183
Name: YWHAG, dtype: int64

YWHAH
False    183
Name: YWHAH, dtype: int64

YWHAQ
False    183
Name: YWHAQ, dtype: int64

YWHAZ
False    183
Name: YWHAZ, dtype: int64

YY1AP1
False    183
Name: YY1AP1, dtype: int64

YY1
False    183
Name: YY1, dtype: int64

YY2
False    181
True       2
Name: YY2, dtype: int64

ZACN
False    98
True     85
Name: ZACN, dtype: int64

ZADH2
False    183
Name: ZADH2, dtype: int64

ZAK
False    183
Name: ZAK, dtype: int64

ZAP70
False    183
Name: ZAP70, dtype: int64

ZBBX
False    127
True      56
Name: ZBBX, dtype: int64

ZBED1
False    183
Name: ZBED1, dtype: int64

ZBED2
False    178
True       5
Name: ZBED2, dtype: int64

ZBED3
False    183
Name: ZBED3, dtype: int64

ZBED4
False    183
Name: ZBED4, dtype: int64

ZBED5
False    183
Name: ZBED5, dtype: int64

ZBP1
False    183
Name: ZBP1, dtype: int64

ZBTB10
False    183
Name: ZBTB10, dtype: int64

ZBTB11
False    183
Name: ZBTB11, dtype: int64

ZBTB12
False    183
Name: ZBTB12, dtype: int64

ZBTB16
False    182
True       1
Name: ZBTB16, dtype: int64

ZBTB17
False    183
Name: ZBTB17, dtype: int64

ZBTB1
False    183
Name: ZBTB1, dtype: int64

ZBTB20
False    183
Name: ZBTB20, dtype: int64

ZBTB22
False    183
Name: ZBTB22, dtype: int64

ZBTB24
False    183
Name: ZBTB24, dtype: int64

ZBTB25
False    183
Name: ZBTB25, dtype: int64

ZBTB26
False    183
Name: ZBTB26, dtype: int64

ZBTB2
False    183
Name: ZBTB2, dtype: int64

ZBTB32
False    182
True       1
Name: ZBTB32, dtype: int64

ZBTB33
False    183
Name: ZBTB33, dtype: int64

ZBTB34
False    183
Name: ZBTB34, dtype: int64

ZBTB37
False    183
Name: ZBTB37, dtype: int64

ZBTB38
False    183
Name: ZBTB38, dtype: int64

ZBTB39
False    183
Name: ZBTB39, dtype: int64

ZBTB3
False    183
Name: ZBTB3, dtype: int64

ZBTB40
False    183
Name: ZBTB40, dtype: int64

ZBTB41
False    183
Name: ZBTB41, dtype: int64

ZBTB42
False    183
Name: ZBTB42, dtype: int64

ZBTB43
False    183
Name: ZBTB43, dtype: int64

ZBTB44
False    183
Name: ZBTB44, dtype: int64

ZBTB45
False    183
Name: ZBTB45, dtype: int64

ZBTB46
False    183
Name: ZBTB46, dtype: int64

ZBTB47
False    183
Name: ZBTB47, dtype: int64

ZBTB48
False    183
Name: ZBTB48, dtype: int64

ZBTB49
False    183
Name: ZBTB49, dtype: int64

ZBTB4
False    183
Name: ZBTB4, dtype: int64

ZBTB5
False    183
Name: ZBTB5, dtype: int64

ZBTB6
False    183
Name: ZBTB6, dtype: int64

ZBTB7A
False    183
Name: ZBTB7A, dtype: int64

ZBTB7B
False    183
Name: ZBTB7B, dtype: int64

ZBTB7C
False    183
Name: ZBTB7C, dtype: int64

ZBTB8A
False    183
Name: ZBTB8A, dtype: int64

ZBTB8B
False    123
True      60
Name: ZBTB8B, dtype: int64

ZBTB8OS
False    183
Name: ZBTB8OS, dtype: int64

ZBTB9
False    183
Name: ZBTB9, dtype: int64

ZC3H10
False    183
Name: ZC3H10, dtype: int64

ZC3H11A
False    183
Name: ZC3H11A, dtype: int64

ZC3H12A
False    183
Name: ZC3H12A, dtype: int64

ZC3H12B
False    183
Name: ZC3H12B, dtype: int64

ZC3H12C
False    183
Name: ZC3H12C, dtype: int64

ZC3H12D
False    183
Name: ZC3H12D, dtype: int64

ZC3H13
False    183
Name: ZC3H13, dtype: int64

ZC3H14
False    183
Name: ZC3H14, dtype: int64

ZC3H15
False    183
Name: ZC3H15, dtype: int64

ZC3H18
False    183
Name: ZC3H18, dtype: int64

ZC3H3
False    183
Name: ZC3H3, dtype: int64

ZC3H4
False    183
Name: ZC3H4, dtype: int64

ZC3H6
False    183
Name: ZC3H6, dtype: int64

ZC3H7A
False    183
Name: ZC3H7A, dtype: int64

ZC3H7B
False    183
Name: ZC3H7B, dtype: int64

ZC3H8
False    183
Name: ZC3H8, dtype: int64

ZC3HAV1L
False    183
Name: ZC3HAV1L, dtype: int64

ZC3HAV1
False    183
Name: ZC3HAV1, dtype: int64

ZC3HC1
False    183
Name: ZC3HC1, dtype: int64

ZC4H2
False    183
Name: ZC4H2, dtype: int64

ZCCHC10
False    183
Name: ZCCHC10, dtype: int64

ZCCHC11
False    183
Name: ZCCHC11, dtype: int64

ZCCHC12
False    183
Name: ZCCHC12, dtype: int64

ZCCHC14
False    183
Name: ZCCHC14, dtype: int64

ZCCHC16
True     108
False     75
Name: ZCCHC16, dtype: int64

ZCCHC17
False    183
Name: ZCCHC17, dtype: int64

ZCCHC18
False    183
Name: ZCCHC18, dtype: int64

ZCCHC24
False    183
Name: ZCCHC24, dtype: int64

ZCCHC2
False    183
Name: ZCCHC2, dtype: int64

ZCCHC3
False    183
Name: ZCCHC3, dtype: int64

ZCCHC4
False    183
Name: ZCCHC4, dtype: int64

ZCCHC5
False    160
True      23
Name: ZCCHC5, dtype: int64

ZCCHC6
False    183
Name: ZCCHC6, dtype: int64

ZCCHC7
False    183
Name: ZCCHC7, dtype: int64

ZCCHC8
False    183
Name: ZCCHC8, dtype: int64

ZCCHC9
False    183
Name: ZCCHC9, dtype: int64

ZCRB1
False    183
Name: ZCRB1, dtype: int64

ZCWPW1
False    183
Name: ZCWPW1, dtype: int64

ZCWPW2
False    183
Name: ZCWPW2, dtype: int64

ZDBF2
False    183
Name: ZDBF2, dtype: int64

ZDHHC11
False    183
Name: ZDHHC11, dtype: int64

ZDHHC12
False    183
Name: ZDHHC12, dtype: int64

ZDHHC13
False    183
Name: ZDHHC13, dtype: int64

ZDHHC14
False    183
Name: ZDHHC14, dtype: int64

ZDHHC15
False    183
Name: ZDHHC15, dtype: int64

ZDHHC16
False    183
Name: ZDHHC16, dtype: int64

ZDHHC17
False    183
Name: ZDHHC17, dtype: int64

ZDHHC18
False    183
Name: ZDHHC18, dtype: int64

ZDHHC19
False    149
True      34
Name: ZDHHC19, dtype: int64

ZDHHC1
False    183
Name: ZDHHC1, dtype: int64

ZDHHC20
False    183
Name: ZDHHC20, dtype: int64

ZDHHC21
False    183
Name: ZDHHC21, dtype: int64

ZDHHC22
False    158
True      25
Name: ZDHHC22, dtype: int64

ZDHHC23
False    183
Name: ZDHHC23, dtype: int64

ZDHHC24
False    183
Name: ZDHHC24, dtype: int64

ZDHHC2
False    183
Name: ZDHHC2, dtype: int64

ZDHHC3
False    183
Name: ZDHHC3, dtype: int64

ZDHHC4
False    183
Name: ZDHHC4, dtype: int64

ZDHHC5
False    183
Name: ZDHHC5, dtype: int64

ZDHHC6
False    183
Name: ZDHHC6, dtype: int64

ZDHHC7
False    183
Name: ZDHHC7, dtype: int64

ZDHHC8P1
False    183
Name: ZDHHC8P1, dtype: int64

ZDHHC8
False    183
Name: ZDHHC8, dtype: int64

ZDHHC9
False    183
Name: ZDHHC9, dtype: int64

ZEB1

False    183
Name: ZEB1, dtype: int64

ZEB2
False    183
Name: ZEB2, dtype: int64

ZER1
False    183
Name: ZER1, dtype: int64

ZFAND1
False    183
Name: ZFAND1, dtype: int64

ZFAND2A
False    183
Name: ZFAND2A, dtype: int64

ZFAND2B
False    183
Name: ZFAND2B, dtype: int64

ZFAND3
False    183
Name: ZFAND3, dtype: int64

ZFAND5
False    183
Name: ZFAND5, dtype: int64

ZFAND6
False    183
Name: ZFAND6, dtype: int64

ZFAT
False    183
Name: ZFAT, dtype: int64

ZFC3H1
False    183
Name: ZFC3H1, dtype: int64

ZFHX3
False    183
Name: ZFHX3, dtype: int64

ZFHX4
False    183
Name: ZFHX4, dtype: int64

ZFP106
False    183
Name: ZFP106, dtype: int64

ZFP112
False    183
Name: ZFP112, dtype: int64

ZFP14
False    183
Name: ZFP14, dtype: int64

ZFP161
False    183
Name: ZFP161, dtype: int64

ZFP1
False    183
Name: ZFP1, dtype: int64

ZFP28
False    183
Name: ZFP28, dtype: int64

ZFP2
False    183
Name: ZFP2, dtype: int64

ZFP30
False    183
Name: ZFP30, dtype: int64

ZFP36L1
False    183
Name: ZFP36L1, dtype: int64

ZFP36L2
False    183
Name: ZFP36L2, dtype: int64

ZFP36
False    183
Name: ZFP36, dtype: int64

ZFP37
False    183
Name: ZFP37, dtype: int64

ZFP3
False    183
Name: ZFP3, dtype: int64

ZFP41
False    183
Name: ZFP41, dtype: int64

ZFP42
True     122
False     61
Name: ZFP42, dtype: int64

ZFP57
False    168
True      15
Name: ZFP57, dtype: int64

ZFP62
False    183
Name: ZFP62, dtype: int64

ZFP64
False    183
Name: ZFP64, dtype: int64

ZFP82
False    183
Name: ZFP82, dtype: int64

ZFP90
False    183
Name: ZFP90, dtype: int64

ZFP91
False    183
Name: ZFP91, dtype: int64

ZFP92
False    165
True      18
Name: ZFP92, dtype: int64

ZFPL1
False    183
Name: ZFPL1, dtype: int64

ZFPM1
False    183
Name: ZFPM1, dtype: int64

ZFPM2
False    183
Name: ZFPM2, dtype: int64

ZFR2
False    176
True       7
Name: ZFR2, dtype: int64

ZFR
False    183
Name: ZFR, dtype: int64

ZFX
False    183
Name: ZFX, dtype: int64

ZFYVE16
False    183
Name: ZFYVE16, dtype: int64

ZFYVE19
False    183
Name: ZFYVE19, dtype: int64

ZFYVE1
False    183
Name: ZFYVE1, dtype: int64

ZFYVE20
False    183
Name: ZFYVE20, dtype: int64

ZFYVE21
False    183
Name: ZFYVE21, dtype: int64

ZFYVE26
False    183
Name: ZFYVE26, dtype: int64

ZFYVE27
False    183
Name: ZFYVE27, dtype: int64

ZFYVE28
False    183
Name: ZFYVE28, dtype: int64

ZFYVE9
False    183
Name: ZFYVE9, dtype: int64

ZFY
False    135
True      48
Name: ZFY, dtype: int64

ZG16B
False    182
True       1
Name: ZG16B, dtype: int64

ZG16
False    121
True      62
Name: ZG16, dtype: int64

ZGLP1
False    183
Name: ZGLP1, dtype: int64

ZGPAT
False    183
Name: ZGPAT, dtype: int64

ZHX1
False    183
Name: ZHX1, dtype: int64

ZHX2
False    183
Name: ZHX2, dtype: int64

ZHX3
False    183
Name: ZHX3, dtype: int64

ZIC1
True     128
False     55
Name: ZIC1, dtype: int64

ZIC2
False    156
True      27
Name: ZIC2, dtype: int64

ZIC5
False    131
True      52
Name: ZIC5, dtype: int64

ZIK1
False    183
Name: ZIK1, dtype: int64

ZIM2
False    97
True     86
Name: ZIM2, dtype: int64

ZKSCAN1
False    183
Name: ZKSCAN1, dtype: int64

ZKSCAN2
False    183
Name: ZKSCAN2, dtype: int64

ZKSCAN3
False    183
Name: ZKSCAN3, dtype: int64

ZKSCAN4
False    183
Name: ZKSCAN4, dtype: int64

ZKSCAN5
False    183
Name: ZKSCAN5, dtype: int64

ZMAT1
False    183
Name: ZMAT1, dtype: int64

ZMAT2
False    183
Name: ZMAT2, dtype: int64

ZMAT3
False    183
Name: ZMAT3, dtype: int64

ZMAT4
False    158
True      25
Name: ZMAT4, dtype: int64

ZMAT5
False    183
Name: ZMAT5, dtype: int64

ZMIZ1
False    183
Name: ZMIZ1, dtype: int64

ZMIZ2
False    183
Name: ZMIZ2, dtype: int64

ZMPSTE24
False    183
Name: ZMPSTE24, dtype: int64

ZMYM1
False    183
Name: ZMYM1, dtype: int64

ZMYM2
False    183
Name: ZMYM2, dtype: int64

ZMYM3
False    183
Name: ZMYM3, dtype: int64

ZMYM4
False    183
Name: ZMYM4, dtype: int64

ZMYM5
False    183
Name: ZMYM5, dtype: int64

ZMYM6
False    183
Name: ZMYM6, dtype: int64

ZMYND10
False    183
Name: ZMYND10, dtype: int64

ZMYND11
False    183
Name: ZMYND11, dtype: int64

ZMYND12
False    183
Name: ZMYND12, dtype: int64

ZMYND15
False    183
Name: ZMYND15, dtype: int64

ZMYND17
False    183
Name: ZMYND17, dtype: int64

ZMYND19
False    183
Name: ZMYND19, dtype: int64

ZMYND8
False    183
Name: ZMYND8, dtype: int64

ZNF100
False    183
Name: ZNF100, dtype: int64

ZNF101
False    183
Name: ZNF101, dtype: int64

ZNF107
False    183
Name: ZNF107, dtype: int64

ZNF10
False    183
Name: ZNF10, dtype: int64

ZNF114
False    183
Name: ZNF114, dtype: int64

ZNF117
False    183
Name: ZNF117, dtype: int64

ZNF121
False    183
Name: ZNF121, dtype: int64

ZNF124
False    183
Name: ZNF124, dtype: int64

ZNF12
False    183
Name: ZNF12, dtype: int64

ZNF131
False    183
Name: ZNF131, dtype: int64

ZNF132
False    183
Name: ZNF132, dtype: int64

ZNF133
False    183
Name: ZNF133, dtype: int64

ZNF134
False    183
Name: ZNF134, dtype: int64

ZNF135
False    183
Name: ZNF135, dtype: int64

ZNF136
False    183
Name: ZNF136, dtype: int64

ZNF137
False    183
Name: ZNF137, dtype: int64

ZNF138
False    183
Name: ZNF138, dtype: int64

ZNF140
False    183
Name: ZNF140, dtype: int64

ZNF141
False    183
Name: ZNF141, dtype: int64

ZNF142
False    183
Name: ZNF142, dtype: int64

ZNF143
False    183
Name: ZNF143, dtype: int64

ZNF146
False    183
Name: ZNF146, dtype: int64

ZNF148
False    183
Name: ZNF148, dtype: int64

ZNF14
False    183
Name: ZNF14, dtype: int64

ZNF154
False    183
Name: ZNF154, dtype: int64

ZNF155
False    183
Name: ZNF155, dtype: int64

ZNF157
False    137
True      46
Name: ZNF157, dtype: int64

ZNF160
False    183
Name: ZNF160, dtype: int64

ZNF165
False    183
Name: ZNF165, dtype: int64

ZNF167
False    183
Name: ZNF167, dtype: int64

ZNF169
False    183
Name: ZNF169, dtype: int64

ZNF16
False    183
Name: ZNF16, dtype: int64

ZNF174
False    183
Name: ZNF174, dtype: int64

ZNF175
False    183
Name: ZNF175, dtype: int64

ZNF177
False    183
Name: ZNF177, dtype: int64

ZNF17
False    183
Name: ZNF17, dtype: int64

ZNF180
False    183
Name: ZNF180, dtype: int64

ZNF181
False    183
Name: ZNF181, dtype: int64

ZNF182
False    183
Name: ZNF182, dtype: int64

ZNF184
False    183
Name: ZNF184, dtype: int64

ZNF185
False    183
Name: ZNF185, dtype: int64

ZNF187
False    183
Name: ZNF187, dtype: int64

ZNF189
False    183
Name: ZNF189, dtype: int64

ZNF18
False    183
Name: ZNF18, dtype: int64

ZNF192
False    183
Name: ZNF192, dtype: int64

ZNF193
False    183
Name: ZNF193, dtype: int64

ZNF195
False    183
Name: ZNF195, dtype: int64

ZNF197
False    183
Name: ZNF197, dtype: int64

ZNF19
False    183
Name: ZNF19, dtype: int64

ZNF200
False    183
Name: ZNF200, dtype: int64

ZNF202
False    183
Name: ZNF202, dtype: int64

ZNF204P
False    183
Name: ZNF204P, dtype: int64

ZNF205
False    183
Name: ZNF205, dtype: int64

ZNF207
False    183
Name: ZNF207, dtype: int64

ZNF208
False    182
True       1
Name: ZNF208, dtype: int64

ZNF20
False    183
Name: ZNF20, dtype: int64

ZNF211
False    183
Name: ZNF211, dtype: int64

ZNF212
False    183
Name: ZNF212, dtype: int64

ZNF213
False    183
Name: ZNF213, dtype: int64

ZNF214
False    183
Name: ZNF214, dtype: int64

ZNF215
False    183
Name: ZNF215, dtype: int64

ZNF217
False    183
Name: ZNF217, dtype: int64

ZNF219
False    183
Name: ZNF219, dtype: int64

ZNF221
False    183
Name: ZNF221, dtype: int64

ZNF222
False    183
Name: ZNF222, dtype: int64

ZNF223
False    183
Name: ZNF223, dtype: int64

ZNF224
False    183
Name: ZNF224, dtype: int64

ZNF225
False    183
Name: ZNF225, dtype: int64

ZNF226
False    183
Name: ZNF226, dtype: int64

ZNF227
False    183
Name: ZNF227, dtype: int64

ZNF229
False    183
Name: ZNF229, dtype: int64

ZNF22
False    183
Name: ZNF22, dtype: int64

ZNF230
False    183
Name: ZNF230, dtype: int64

ZNF232
False    183
Name: ZNF232, dtype: int64

ZNF233
False    183
Name: ZNF233, dtype: int64

ZNF234
False    183
Name: ZNF234, dtype: int64

ZNF235
False    183
Name: ZNF235, dtype: int64

ZNF236
False    183
Name: ZNF236, dtype: int64

ZNF238
False    183
Name: ZNF238, dtype: int64

ZNF239
False    183
Name: ZNF239, dtype: int64

ZNF23
False    183
Name: ZNF23, dtype: int64

ZNF248
False    183
Name: ZNF248, dtype: int64

ZNF24
False    183
Name: ZNF24, dtype: int64

ZNF250
False    183
Name: ZNF250, dtype: int64

ZNF251
False    183
Name: ZNF251, dtype: int64

ZNF252
False    183
Name: ZNF252, dtype: int64

ZNF253
False    183
Name: ZNF253, dtype: int64

ZNF254
False    183
Name: ZNF254, dtype: int64

ZNF256
False    183
Name: ZNF256, dtype: int64

ZNF257
False    181
True       2
Name: ZNF257, dtype: int64

ZNF259
False    183
Name: ZNF259, dtype: int64

ZNF25
False    183
Name: ZNF25, dtype: int64

ZNF260
False    183
Name: ZNF260, dtype: int64

ZNF263
False    183
Name: ZNF263, dtype: int64

ZNF264
False    183
Name: ZNF264, dtype: int64

ZNF266
False    183
Name: ZNF266, dtype: int64

ZNF267
False    183
Name: ZNF267, dtype: int64

ZNF268
False    183
Name: ZNF268, dtype: int64

ZNF26

False    183
Name: ZNF26, dtype: int64

ZNF271
False    183
Name: ZNF271, dtype: int64

ZNF273
False    183
Name: ZNF273, dtype: int64

ZNF274
False    183
Name: ZNF274, dtype: int64

ZNF275
False    183
Name: ZNF275, dtype: int64

ZNF276
False    183
Name: ZNF276, dtype: int64

ZNF277
False    183
Name: ZNF277, dtype: int64

ZNF280A
False    109
True      74
Name: ZNF280A, dtype: int64

ZNF280B
False    181
True       2
Name: ZNF280B, dtype: int64

ZNF280C
False    183
Name: ZNF280C, dtype: int64

ZNF280D
False    183
Name: ZNF280D, dtype: int64

ZNF281
False    183
Name: ZNF281, dtype: int64

ZNF282
False    183
Name: ZNF282, dtype: int64

ZNF283
False    183
Name: ZNF283, dtype: int64

ZNF284
False    183
Name: ZNF284, dtype: int64

ZNF285
False    182
True       1
Name: ZNF285, dtype: int64

ZNF286A
False    183
Name: ZNF286A, dtype: int64

ZNF286B
False    183
Name: ZNF286B, dtype: int64

ZNF287
False    183
Name: ZNF287, dtype: int64

ZNF28
False    183
Name: ZNF28, dtype: int64

ZNF292
False    183
Name: ZNF292, dtype: int64

ZNF295
False    183
Name: ZNF295, dtype: int64

ZNF296
False    183
Name: ZNF296, dtype: int64

ZNF2
False    183
Name: ZNF2, dtype: int64

ZNF300
False    183
Name: ZNF300, dtype: int64

ZNF302
False    183
Name: ZNF302, dtype: int64

ZNF304
False    183
Name: ZNF304, dtype: int64

ZNF30
False    183
Name: ZNF30, dtype: int64

ZNF311
False    182
True       1
Name: ZNF311, dtype: int64

ZNF317
False    183
Name: ZNF317, dtype: int64

ZNF318
False    183
Name: ZNF318, dtype: int64

ZNF319
False    183
Name: ZNF319, dtype: int64

ZNF320
False    183
Name: ZNF320, dtype: int64

ZNF321
False    182
True       1
Name: ZNF321, dtype: int64

ZNF322A
False    183
Name: ZNF322A, dtype: int64

ZNF322B
False    183
Name: ZNF322B, dtype: int64

ZNF323
False    183
Name: ZNF323, dtype: int64

ZNF324B
False    183
Name: ZNF324B, dtype: int64

ZNF324
False    183
Name: ZNF324, dtype: int64

ZNF326
False    183
Name: ZNF326, dtype: int64

ZNF329
False    183
Name: ZNF329, dtype: int64

ZNF32
False    183
Name: ZNF32, dtype: int64

ZNF330
False    183
Name: ZNF330, dtype: int64

ZNF331
False    183
Name: ZNF331, dtype: int64

ZNF333
False    183
Name: ZNF333, dtype: int64

ZNF334
False    183
Name: ZNF334, dtype: int64

ZNF335
False    183
Name: ZNF335, dtype: int64

ZNF337
False    183
Name: ZNF337, dtype: int64

ZNF33A
False    183
Name: ZNF33A, dtype: int64

ZNF33B
False    183
Name: ZNF33B, dtype: int64

ZNF341
False    183
Name: ZNF341, dtype: int64

ZNF343
False    183
Name: ZNF343, dtype: int64

ZNF345
False    183
Name: ZNF345, dtype: int64

ZNF346
False    183
Name: ZNF346, dtype: int64

ZNF347
False    183
Name: ZNF347, dtype: int64

ZNF34
False    183
Name: ZNF34, dtype: int64

ZNF350
False    183
Name: ZNF350, dtype: int64

ZNF354A
False    183
Name: ZNF354A, dtype: int64

ZNF354B
False    183
Name: ZNF354B, dtype: int64

ZNF354C
False    182
True       1
Name: ZNF354C, dtype: int64

ZNF358
False    183
Name: ZNF358, dtype: int64

ZNF35
False    183
Name: ZNF35, dtype: int64

ZNF362
False    183
Name: ZNF362, dtype: int64

ZNF365
False    183
Name: ZNF365, dtype: int64

ZNF366
False    183
Name: ZNF366, dtype: int64

ZNF367
False    183
Name: ZNF367, dtype: int64

ZNF37A
False    183
Name: ZNF37A, dtype: int64

ZNF37B
False    183
Name: ZNF37B, dtype: int64

ZNF382
False    182
True       1
Name: ZNF382, dtype: int64

ZNF383
False    183
Name: ZNF383, dtype: int64

ZNF384
False    183
Name: ZNF384, dtype: int64

ZNF385A
False    183
Name: ZNF385A, dtype: int64

ZNF385B
False    181
True       2
Name: ZNF385B, dtype: int64

ZNF385D
False    183
Name: ZNF385D, dtype: int64

ZNF389
False    181
True       2
Name: ZNF389, dtype: int64

ZNF391
False    183
Name: ZNF391, dtype: int64

ZNF394
False    183
Name: ZNF394, dtype: int64

ZNF395
False    183
Name: ZNF395, dtype: int64

ZNF396
False    183
Name: ZNF396, dtype: int64

ZNF397OS
False    183
Name: ZNF397OS, dtype: int64

ZNF397
False    183
Name: ZNF397, dtype: int64

ZNF398
False    183
Name: ZNF398, dtype: int64

ZNF3
False    183
Name: ZNF3, dtype: int64

ZNF404
False    183
Name: ZNF404, dtype: int64

ZNF407
False    183
Name: ZNF407, dtype: int64

ZNF408
False    183
Name: ZNF408, dtype: int64

ZNF410
False    183
Name: ZNF410, dtype: int64

ZNF414
False    183
Name: ZNF414, dtype: int64

ZNF415
False    183
Name: ZNF415, dtype: int64

ZNF416
False    183
Name: ZNF416, dtype: int64

ZNF417
False    183
Name: ZNF417, dtype: int64

ZNF418
False    183
Name: ZNF418, dtype: int64

ZNF419
False    183
Name: ZNF419, dtype: int64

ZNF41
False    183
Name: ZNF41, dtype: int64

ZNF420
False    183
Name: ZNF420, dtype: int64

ZNF423
False    183
Name: ZNF423, dtype: int64

ZNF425
False    183
Name: ZNF425, dtype: int64

ZNF426
False    183
Name: ZNF426, dtype: int64

ZNF428
False    183
Name: ZNF428, dtype: int64

ZNF429
False    183
Name: ZNF429, dtype: int64

ZNF430
False    183
Name: ZNF430, dtype: int64

ZNF431
False    183
Name: ZNF431, dtype: int64

ZNF432
False    183
Name: ZNF432, dtype: int64

ZNF433
False    183
Name: ZNF433, dtype: int64

ZNF434
False    183
Name: ZNF434, dtype: int64

ZNF436
False    183
Name: ZNF436, dtype: int64

ZNF438
False    183
Name: ZNF438, dtype: int64

ZNF439
False    183
Name: ZNF439, dtype: int64

ZNF43
False    183
Name: ZNF43, dtype: int64

ZNF440
False    183
Name: ZNF440, dtype: int64

ZNF441
False    183
Name: ZNF441, dtype: int64

ZNF442
False    183
Name: ZNF442, dtype: int64

ZNF443
False    183
Name: ZNF443, dtype: int64

ZNF444
False    183
Name: ZNF444, dtype: int64

ZNF445
False    183
Name: ZNF445, dtype: int64

ZNF446
False    183
Name: ZNF446, dtype: int64

ZNF449
False    183
Name: ZNF449, dtype: int64

ZNF44
False    183
Name: ZNF44, dtype: int64

ZNF451
False    183
Name: ZNF451, dtype: int64

ZNF454
False    183
Name: ZNF454, dtype: int64

ZNF45
False    183
Name: ZNF45, dtype: int64

ZNF460
False    183
Name: ZNF460, dtype: int64

ZNF461
False    183
Name: ZNF461, dtype: int64

ZNF462
False    183
Name: ZNF462, dtype: int64

ZNF467
False    183
Name: ZNF467, dtype: int64

ZNF468
False    183
Name: ZNF468, dtype: int64

ZNF469
False    183
Name: ZNF469, dtype: int64

ZNF470
False    183
Name: ZNF470, dtype: int64

ZNF471
False    183
Name: ZNF471, dtype: int64

ZNF473
False    183
Name: ZNF473, dtype: int64

ZNF474
False    179
True       4
Name: ZNF474, dtype: int64

ZNF480
False    183
Name: ZNF480, dtype: int64

ZNF483
False    182
True       1
Name: ZNF483, dtype: int64

ZNF484
False    183
Name: ZNF484, dtype: int64

ZNF485
False    183
Name: ZNF485, dtype: int64

ZNF486
False    183
Name: ZNF486, dtype: int64

ZNF487
False    183
Name: ZNF487, dtype: int64

ZNF488
False    183
Name: ZNF488, dtype: int64

ZNF48
False    183
Name: ZNF48, dtype: int64

ZNF490
False    183
Name: ZNF490, dtype: int64

ZNF491
False    183
Name: ZNF491, dtype: int64

ZNF492
False    160
True      23
Name: ZNF492, dtype: int64

ZNF493
False    183
Name: ZNF493, dtype: int64

ZNF496
False    183
Name: ZNF496, dtype: int64

ZNF497
False    183
Name: ZNF497, dtype: int64

ZNF498
False    183
Name: ZNF498, dtype: int64

ZNF500
False    183
Name: ZNF500, dtype: int64

ZNF501
False    183
Name: ZNF501, dtype: int64

ZNF502
False    183
Name: ZNF502, dtype: int64

ZNF503
False    183
Name: ZNF503, dtype: int64

ZNF506
False    183
Name: ZNF506, dtype: int64

ZNF507
False    183
Name: ZNF507, dtype: int64

ZNF510
False    183
Name: ZNF510, dtype: int64

ZNF511
False    183
Name: ZNF511, dtype: int64

ZNF512B
False    183
Name: ZNF512B, dtype: int64

ZNF512
False    183
Name: ZNF512, dtype: int64

ZNF513
False    183
Name: ZNF513, dtype: int64

ZNF514
False    183
Name: ZNF514, dtype: int64

ZNF516
False    183
Name: ZNF516, dtype: int64

ZNF517
False    183
Name: ZNF517, dtype: int64

ZNF518A
False    183
Name: ZNF518A, dtype: int64

ZNF518B
False    183
Name: ZNF518B, dtype: int64

ZNF519
False    183
Name: ZNF519, dtype: int64

ZNF521
False    183
Name: ZNF521, dtype: int64

ZNF524
False    183
Name: ZNF524, dtype: int64

ZNF525
False    183
Name: ZNF525, dtype: int64

ZNF526
False    183
Name: ZNF526, dtype: int64

ZNF527
False    183
Name: ZNF527, dtype: int64

ZNF528
False    183
Name: ZNF528, dtype: int64

ZNF529
False    183
Name: ZNF529, dtype: int64

ZNF530
False    183
Name: ZNF530, dtype: int64

ZNF532
False    183
Name: ZNF532, dtype: int64

ZNF534
False    183
Name: ZNF534, dtype: int64

ZNF536

False    174
True       9
Name: ZNF536, dtype: int64

ZNF540
False    183
Name: ZNF540, dtype: int64

ZNF541
False    178
True       5
Name: ZNF541, dtype: int64

ZNF542
False    183
Name: ZNF542, dtype: int64

ZNF543
False    183
Name: ZNF543, dtype: int64

ZNF544
False    183
Name: ZNF544, dtype: int64

ZNF546
False    183
Name: ZNF546, dtype: int64

ZNF547
False    183
Name: ZNF547, dtype: int64

ZNF548
False    183
Name: ZNF548, dtype: int64

ZNF549
False    183
Name: ZNF549, dtype: int64

ZNF550
False    183
Name: ZNF550, dtype: int64

ZNF551
False    183
Name: ZNF551, dtype: int64

ZNF552
False    183
Name: ZNF552, dtype: int64

ZNF554
False    183
Name: ZNF554, dtype: int64

ZNF555
False    183
Name: ZNF555, dtype: int64

ZNF556
True     109
False     74
Name: ZNF556, dtype: int64

ZNF557
False    183
Name: ZNF557, dtype: int64

ZNF558
False    183
Name: ZNF558, dtype: int64

ZNF559
False    183
Name: ZNF559, dtype: int64

ZNF560
True     111
False     72
Name: ZNF560, dtype: int64

ZNF561
False    183
Name: ZNF561, dtype: int64

ZNF562
False    183
Name: ZNF562, dtype: int64

ZNF563
False    183
Name: ZNF563, dtype: int64

ZNF564
False    183
Name: ZNF564, dtype: int64

ZNF565
False    183
Name: ZNF565, dtype: int64

ZNF566
False    183
Name: ZNF566, dtype: int64

ZNF567
False    183
Name: ZNF567, dtype: int64

ZNF568
False    183
Name: ZNF568, dtype: int64

ZNF569
False    183
Name: ZNF569, dtype: int64

ZNF570
False    183
Name: ZNF570, dtype: int64

ZNF571
False    183
Name: ZNF571, dtype: int64

ZNF572
False    183
Name: ZNF572, dtype: int64

ZNF573
False    183
Name: ZNF573, dtype: int64

ZNF574
False    183
Name: ZNF574, dtype: int64

ZNF575
False    183
Name: ZNF575, dtype: int64

ZNF576
False    183
Name: ZNF576, dtype: int64

ZNF577
False    183
Name: ZNF577, dtype: int64

ZNF578
False    183
Name: ZNF578, dtype: int64

ZNF579
False    183
Name: ZNF579, dtype: int64

ZNF57
False    183
Name: ZNF57, dtype: int64

ZNF580
False    183
Name: ZNF580, dtype: int64

ZNF581
False    183
Name: ZNF581, dtype: int64

ZNF582
False    183
Name: ZNF582, dtype: int64

ZNF583
False    183
Name: ZNF583, dtype: int64

ZNF584
False    183
Name: ZNF584, dtype: int64

ZNF585A
False    183
Name: ZNF585A, dtype: int64

ZNF585B
False    182
True       1
Name: ZNF585B, dtype: int64

ZNF586
False    183
Name: ZNF586, dtype: int64

ZNF587
False    183
Name: ZNF587, dtype: int64

ZNF589
False    183
Name: ZNF589, dtype: int64

ZNF592
False    183
Name: ZNF592, dtype: int64

ZNF593
False    183
Name: ZNF593, dtype: int64

ZNF594
False    183
Name: ZNF594, dtype: int64

ZNF595
False    183
Name: ZNF595, dtype: int64

ZNF596
False    183
Name: ZNF596, dtype: int64

ZNF597
False    183
Name: ZNF597, dtype: int64

ZNF598
False    183
Name: ZNF598, dtype: int64

ZNF599
False    183
Name: ZNF599, dtype: int64

ZNF600
False    183
Name: ZNF600, dtype: int64

ZNF605
False    183
Name: ZNF605, dtype: int64

ZNF606
False    183
Name: ZNF606, dtype: int64

ZNF607
False    183
Name: ZNF607, dtype: int64

ZNF608
False    183
Name: ZNF608, dtype: int64

ZNF609
False    183
Name: ZNF609, dtype: int64

ZNF610
False    183
Name: ZNF610, dtype: int64

ZNF611
False    183
Name: ZNF611, dtype: int64

ZNF613
False    183
Name: ZNF613, dtype: int64

ZNF614
False    183
Name: ZNF614, dtype: int64

ZNF615
False    183
Name: ZNF615, dtype: int64

ZNF616
False    183
Name: ZNF616, dtype: int64

ZNF618
False    183
Name: ZNF618, dtype: int64

ZNF619
False    183
Name: ZNF619, dtype: int64

ZNF620
False    183
Name: ZNF620, dtype: int64

ZNF621
False    183
Name: ZNF621, dtype: int64

ZNF622
False    183
Name: ZNF622, dtype: int64

ZNF623
False    183
Name: ZNF623, dtype: int64

ZNF624
False    183
Name: ZNF624, dtype: int64

ZNF625
False    183
Name: ZNF625, dtype: int64

ZNF626
False    183
Name: ZNF626, dtype: int64

ZNF627
False    183
Name: ZNF627, dtype: int64

ZNF628
False    183
Name: ZNF628, dtype: int64

ZNF629
False    183
Name: ZNF629, dtype: int64

ZNF630
False    183
Name: ZNF630, dtype: int64

ZNF638
False    183
Name: ZNF638, dtype: int64

ZNF639
False    183
Name: ZNF639, dtype: int64

ZNF641
False    183
Name: ZNF641, dtype: int64

ZNF642
False    183
Name: ZNF642, dtype: int64

ZNF643
False    183
Name: ZNF643, dtype: int64

ZNF644
False    183
Name: ZNF644, dtype: int64

ZNF646
False    183
Name: ZNF646, dtype: int64

ZNF648
False    109
True      74
Name: ZNF648, dtype: int64

ZNF649
False    183
Name: ZNF649, dtype: int64

ZNF652
False    183
Name: ZNF652, dtype: int64

ZNF653
False    183
Name: ZNF653, dtype: int64

ZNF654
False    183
Name: ZNF654, dtype: int64

ZNF655
False    183
Name: ZNF655, dtype: int64

ZNF658
False    183
Name: ZNF658, dtype: int64

ZNF660
False    181
True       2
Name: ZNF660, dtype: int64

ZNF662
False    183
Name: ZNF662, dtype: int64

ZNF664
False    183
Name: ZNF664, dtype: int64

ZNF665
False    183
Name: ZNF665, dtype: int64

ZNF667
False    183
Name: ZNF667, dtype: int64

ZNF668
False    183
Name: ZNF668, dtype: int64

ZNF669
False    183
Name: ZNF669, dtype: int64

ZNF670
False    183
Name: ZNF670, dtype: int64

ZNF671
False    183
Name: ZNF671, dtype: int64

ZNF672
False    183
Name: ZNF672, dtype: int64

ZNF673
False    183
Name: ZNF673, dtype: int64

ZNF674
False    183
Name: ZNF674, dtype: int64

ZNF675
False    183
Name: ZNF675, dtype: int64

ZNF676
False    178
True       5
Name: ZNF676, dtype: int64

ZNF677
False    183
Name: ZNF677, dtype: int64

ZNF678
False    183
Name: ZNF678, dtype: int64

ZNF680
False    183
Name: ZNF680, dtype: int64

ZNF681
False    183
Name: ZNF681, dtype: int64

ZNF682
False    183
Name: ZNF682, dtype: int64

ZNF683
False    181
True       2
Name: ZNF683, dtype: int64

ZNF684
False    183
Name: ZNF684, dtype: int64

ZNF687
False    183
Name: ZNF687, dtype: int64

ZNF688
False    183
Name: ZNF688, dtype: int64

ZNF689
False    183
Name: ZNF689, dtype: int64

ZNF691
False    183
Name: ZNF691, dtype: int64

ZNF692
False    183
Name: ZNF692, dtype: int64

ZNF695
False    178
True       5
Name: ZNF695, dtype: int64

ZNF696
False    183
Name: ZNF696, dtype: int64

ZNF697
False    183
Name: ZNF697, dtype: int64

ZNF699
False    183
Name: ZNF699, dtype: int64

ZNF69
False    183
Name: ZNF69, dtype: int64

ZNF700
False    183
Name: ZNF700, dtype: int64

ZNF701
False    183
Name: ZNF701, dtype: int64

ZNF702P
False    182
True       1
Name: ZNF702P, dtype: int64

ZNF703
False    183
Name: ZNF703, dtype: int64

ZNF704
False    183
Name: ZNF704, dtype: int64

ZNF705A
True     113
False     70
Name: ZNF705A, dtype: int64

ZNF706
False    183
Name: ZNF706, dtype: int64

ZNF707
False    183
Name: ZNF707, dtype: int64

ZNF708
False    183
Name: ZNF708, dtype: int64

ZNF709
False    183
Name: ZNF709, dtype: int64

ZNF70
False    183
Name: ZNF70, dtype: int64

ZNF710
False    183
Name: ZNF710, dtype: int64

ZNF711
False    183
Name: ZNF711, dtype: int64

ZNF713
False    183
Name: ZNF713, dtype: int64

ZNF714
False    183
Name: ZNF714, dtype: int64

ZNF717
False    183
Name: ZNF717, dtype: int64

ZNF718
False    183
Name: ZNF718, dtype: int64

ZNF71
False    183
Name: ZNF71, dtype: int64

ZNF720
False    183
Name: ZNF720, dtype: int64

ZNF721
False    183
Name: ZNF721, dtype: int64

ZNF727
False    173
True      10
Name: ZNF727, dtype: int64

ZNF732
False    178
True       5
Name: ZNF732, dtype: int64

ZNF737
False    183
Name: ZNF737, dtype: int64

ZNF738
False    183
Name: ZNF738, dtype: int64

ZNF740
False    183
Name: ZNF740, dtype: int64

ZNF746
False    183
Name: ZNF746, dtype: int64

ZNF747
False    183
Name: ZNF747, dtype: int64

ZNF749
False    183
Name: ZNF749, dtype: int64

ZNF74
False    183
Name: ZNF74, dtype: int64

ZNF750
False    181
True       2
Name: ZNF750, dtype: int64

ZNF75A
False    183
Name: ZNF75A, dtype: int64

ZNF75D
False    183
Name: ZNF75D, dtype: int64

ZNF761
False    183
Name: ZNF761, dtype: int64

ZNF763
False    183
Name: ZNF763, dtype: int64

ZNF764
False    183
Name: ZNF764, dtype: int64

ZNF765
False    183
Name: ZNF765, dtype: int64

ZNF766
False    183
Name: ZNF766, dtype: int64

ZNF767
False    183
Name: ZNF767, dtype: int64

ZNF768
False    183
Name: ZNF768, dtype: int64

ZNF76
False    183
Name: ZNF76, dtype: int64

ZNF770
False    183
Name: ZNF770, dtype: int64

ZNF771
False    183
Name: ZNF771, dtype: int64

ZNF772

False    183
Name: ZNF772, dtype: int64

ZNF773
False    183
Name: ZNF773, dtype: int64

ZNF774
False    183
Name: ZNF774, dtype: int64

ZNF775
False    183
Name: ZNF775, dtype: int64

ZNF776
False    183
Name: ZNF776, dtype: int64

ZNF777
False    183
Name: ZNF777, dtype: int64

ZNF778
False    183
Name: ZNF778, dtype: int64

ZNF77
False    183
Name: ZNF77, dtype: int64

ZNF780A
False    183
Name: ZNF780A, dtype: int64

ZNF780B
False    183
Name: ZNF780B, dtype: int64

ZNF781
False    181
True       2
Name: ZNF781, dtype: int64

ZNF782
False    183
Name: ZNF782, dtype: int64

ZNF784
False    183
Name: ZNF784, dtype: int64

ZNF785
False    183
Name: ZNF785, dtype: int64

ZNF786
False    183
Name: ZNF786, dtype: int64

ZNF787
False    183
Name: ZNF787, dtype: int64

ZNF788
False    183
Name: ZNF788, dtype: int64

ZNF789
False    183
Name: ZNF789, dtype: int64

ZNF790
False    183
Name: ZNF790, dtype: int64

ZNF791
False    183
Name: ZNF791, dtype: int64

ZNF792
False    183
Name: ZNF792, dtype: int64

ZNF793
False    183
Name: ZNF793, dtype: int64

ZNF799
False    183
Name: ZNF799, dtype: int64

ZNF79
False    183
Name: ZNF79, dtype: int64

ZNF7
False    183
Name: ZNF7, dtype: int64

ZNF800
False    183
Name: ZNF800, dtype: int64

ZNF804A
False    180
True       3
Name: ZNF804A, dtype: int64

ZNF805
False    183
Name: ZNF805, dtype: int64

ZNF808
False    183
Name: ZNF808, dtype: int64

ZNF80
False    166
True      17
Name: ZNF80, dtype: int64

ZNF813
False    182
True       1
Name: ZNF813, dtype: int64

ZNF814
False    183
Name: ZNF814, dtype: int64

ZNF815
False    183
Name: ZNF815, dtype: int64

ZNF816A
False    183
Name: ZNF816A, dtype: int64

ZNF81
False    183
Name: ZNF81, dtype: int64

ZNF821
False    183
Name: ZNF821, dtype: int64

ZNF823
False    183
Name: ZNF823, dtype: int64

ZNF826
False    183
Name: ZNF826, dtype: int64

ZNF827
False    183
Name: ZNF827, dtype: int64

ZNF828
False    183
Name: ZNF828, dtype: int64

ZNF829
False    178
True       5
Name: ZNF829, dtype: int64

ZNF830
False    183
Name: ZNF830, dtype: int64

ZNF831
False    182
True       1
Name: ZNF831, dtype: int64

ZNF833
False    183
Name: ZNF833, dtype: int64

ZNF835
False    181
True       2
Name: ZNF835, dtype: int64

ZNF836
False    183
Name: ZNF836, dtype: int64

ZNF837
False    183
Name: ZNF837, dtype: int64

ZNF839
False    183
Name: ZNF839, dtype: int64

ZNF83
False    183
Name: ZNF83, dtype: int64

ZNF841
False    183
Name: ZNF841, dtype: int64

ZNF843
False    182
True       1
Name: ZNF843, dtype: int64

ZNF844
False    183
Name: ZNF844, dtype: int64

ZNF845
False    183
Name: ZNF845, dtype: int64

ZNF846
False    183
Name: ZNF846, dtype: int64

ZNF84
False    183
Name: ZNF84, dtype: int64

ZNF853
False    183
Name: ZNF853, dtype: int64

ZNF85
False    183
Name: ZNF85, dtype: int64

ZNF860
False    183
Name: ZNF860, dtype: int64

ZNF862
False    183
Name: ZNF862, dtype: int64

ZNF876P
False    183
Name: ZNF876P, dtype: int64

ZNF878
False    176
True       7
Name: ZNF878, dtype: int64

ZNF879
False    182
True       1
Name: ZNF879, dtype: int64

ZNF880
False    183
Name: ZNF880, dtype: int64

ZNF883
False    182
True       1
Name: ZNF883, dtype: int64

ZNF8
False    183
Name: ZNF8, dtype: int64

ZNF90
False    183
Name: ZNF90, dtype: int64

ZNF91
False    183
Name: ZNF91, dtype: int64

ZNF92
False    183
Name: ZNF92, dtype: int64

ZNF93
False    183
Name: ZNF93, dtype: int64

ZNF98
False    163
True      20
Name: ZNF98, dtype: int64

ZNF99
True     103
False     80
Name: ZNF99, dtype: int64

ZNFX1
False    183
Name: ZNFX1, dtype: int64

ZNHIT1
False    183
Name: ZNHIT1, dtype: int64

ZNHIT2
False    179
True       4
Name: ZNHIT2, dtype: int64

ZNHIT3
False    183
Name: ZNHIT3, dtype: int64

ZNHIT6
False    183
Name: ZNHIT6, dtype: int64

ZNRD1
False    183
Name: ZNRD1, dtype: int64

ZNRF1
False    183
Name: ZNRF1, dtype: int64

ZNRF2
False    183
Name: ZNRF2, dtype: int64

ZNRF3
False    183
Name: ZNRF3, dtype: int64

ZP1
False    166
True      17
Name: ZP1, dtype: int64

ZP3
False    183
Name: ZP3, dtype: int64

ZPBP2
True     125
False     58
Name: ZPBP2, dtype: int64

ZPLD1
False    178
True       5
Name: ZPLD1, dtype: int64

ZRANB1
False    183
Name: ZRANB1, dtype: int64

ZRANB2
False    183
Name: ZRANB2, dtype: int64

ZRANB3
False    183
Name: ZRANB3, dtype: int64

ZRSR2
False    183
Name: ZRSR2, dtype: int64

ZSCAN12P1
False    183
Name: ZSCAN12P1, dtype: int64

ZSCAN12
False    183
Name: ZSCAN12, dtype: int64

ZSCAN16
False    183
Name: ZSCAN16, dtype: int64

ZSCAN18
False    183
Name: ZSCAN18, dtype: int64

ZSCAN1
False    172
True      11
Name: ZSCAN1, dtype: int64

ZSCAN20
False    183
Name: ZSCAN20, dtype: int64

ZSCAN21
False    183
Name: ZSCAN21, dtype: int64

ZSCAN22
False    183
Name: ZSCAN22, dtype: int64

ZSCAN23
False    179
True       4
Name: ZSCAN23, dtype: int64

ZSCAN29
False    183
Name: ZSCAN29, dtype: int64

ZSCAN2
False    183
Name: ZSCAN2, dtype: int64

ZSCAN4
False    171
True      12
Name: ZSCAN4, dtype: int64

ZSCAN5A
False    183
Name: ZSCAN5A, dtype: int64

ZSCAN5B
False    166
True      17
Name: ZSCAN5B, dtype: int64

ZSWIM1
False    183
Name: ZSWIM1, dtype: int64

ZSWIM3
False    183
Name: ZSWIM3, dtype: int64

ZSWIM4
False    183
Name: ZSWIM4, dtype: int64

ZSWIM5
False    183
Name: ZSWIM5, dtype: int64

ZSWIM6
False    183
Name: ZSWIM6, dtype: int64

ZSWIM7
False    183
Name: ZSWIM7, dtype: int64

ZUFSP
False    183
Name: ZUFSP, dtype: int64

ZW10
False    183
Name: ZW10, dtype: int64

ZWILCH
False    183
Name: ZWILCH, dtype: int64

ZWINT
False    183
Name: ZWINT, dtype: int64

ZXDA
False    183
Name: ZXDA, dtype: int64

ZXDB
False    183
Name: ZXDB, dtype: int64

ZXDC
False    183
Name: ZXDC, dtype: int64

ZYG11A
False    140
True      43
Name: ZYG11A, dtype: int64

ZYG11B
False    183
Name: ZYG11B, dtype: int64

ZYX
False    183
Name: ZYX, dtype: int64

ZZEF1
False    183
Name: ZZEF1, dtype: int64

ZZZ3
False    183
Name: ZZZ3, dtype: int64

psiTPTE22
False    182
True       1
Name: psiTPTE22, dtype: int64

In [11]:
df1.isnull().sum(axis=1)

rid
SLC35E2       0
A1BG          0
A1CF          2
A2BP1        42
A2LD1         0
A2ML1        27
A2M           0
A4GALT        0
A4GNT         9
AAA1         58
AAAS          0
AACSL        76
AACS          0
AADAC         4
AADAT         0
AAGAB         0
AAK1          0
AAMP          0
AANAT        60
AARS2         0
AARSD1        0
AARS          0
AASDHPPT      0
AASDH         0
AASS          0
AATF          0
AATK          0
ABAT          0
ABCA10        0
ABCA11P       0
             ..
ZSCAN18       0
ZSCAN1       11
ZSCAN20       0
ZSCAN21       0
ZSCAN22       0
ZSCAN23       4
ZSCAN29       0
ZSCAN2        0
ZSCAN4       12
ZSCAN5A       0
ZSCAN5B      17
ZSWIM1        0
ZSWIM3        0
ZSWIM4        0
ZSWIM5        0
ZSWIM6        0
ZSWIM7        0
ZUFSP         0
ZW10          0
ZWILCH        0
ZWINT         0
ZXDA          0
ZXDB          0
ZXDC          0
ZYG11A       43
ZYG11B        0
ZYX           0
ZZEF1         0
ZZZ3          0
psiTPTE22     1
Length: 18465, dtype: int64

In [12]:
li=df1.isnull().sum(axis=1).tolist()
cnt=0
for i in li:
 if(i!=0):
  cnt+=1 
cnt

4367

So Number of genes with NaN Values is :4367

In [13]:
df.data_df.dropna(axis=0,inplace=True)

In [14]:
df.data_df.reset_index(drop=True, inplace=True)

In [15]:
import cmapPy.pandasGEXpress.write_gct as wr
wr.write(df, "PAAD_Clean.gct", data_null='NaN', metadata_null='-666', filler_null='-666', data_float_format='%.4f')

In [16]:
df.data_df.shape

(14098, 183)